### ISSUE TITLE
App stops responding after opening the laptop lid

### ISSUE THREAD

**Issue by aleksandr-cherkashin** [folivoraAI/BetterTouchTool#1002]
#### Description of bug/feature request/question:
After the very last update, the app sometimes stops responding right after I open my laptop's lid. It happens pretty often now.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

MacBook Pro

#### Device information:

Type of Mac: MacBook Pro (Retina, 15-inch, Late 2013)
macOS version: Sierra 10.12.4 (16E195)
BetterTouchTool version: 2.11(630)

**Comment by iamcaner** [comment]
Experiencing exact same issue on last two release.

**Comment by fifafu** [comment]
Would be great if you could try the latest alpha version (v2.17)
