### ISSUE TITLE
BetterTouchToolScriptRunner Using 100% of CPU

### ISSUE THREAD

**Issue by shreezus** [folivoraAI/BetterTouchTool#1013]
#### Description of bug/feature request/question:

BetterTouchToolScriptRunner is using 99.9% of my CPU. The only enabled Applescript is the Spotify "Now Playing" TouchBar widget.

#### Device information:

Type of Mac: 2016 rMBP 15 TouchBar
macOS version: 10.12.5
BetterTouchTool version: 2.18 (638)

**Comment by fifafu** [comment]
I have made some little adjustments in v2.19 alpha, could you check that?
Otherwise it would be great if you'd go to the About tab in the BTT preferences and press the "Export Debug Info" button. It will create a "BetterTouchToolDebug" folder on your desktop that could be very helpful for me (boastr.net@gmail.com)

**Comment by shreezus** [comment]
Appears to be fixed as of 2.20 onwards. ScriptRunner is now behaving normally. Thanks!

**Comment by oschrenk** [comment]
I experience a similar issue. BetterTouchToolScriptRunner is using 100% CPU.
 
Running:
2017 rMBP 15 TouchBar
10.13.1 Beta (17B35a), although I saw this also on 10.13.0
BetterTouchTool version: 2.310

Restarting BTT  helped.

I exported Debug information. Can I send those to you?

**Comment by mainstreetmark** [comment]
I also have 100%+ CPU when using a Applescript to show what's playing, even if i set it to run only every 30 seconds.

**Comment by fifafu** [comment]
@mainstreetmark which version of BTT are you running?

**Comment by mainstreetmark** [comment]
2.332

**Comment by fifafu** [comment]
Could you post the Apple script you are using?

**Comment by mainstreetmark** [comment]
if application "Spotify" is running then
	tell application "Spotify"
		if player state is playing then
			return (get name of current track) & " - " & (get artist of current track)
		end if
	end tell
end if

if application "iTunes" is running then
	tell application "iTunes"
		if player state is playing then
			return (get name of current track) & " - " & (get artist of current track)
		end if
	end tell
end if
return "▶️"

**Comment by mainstreetmark** [comment]
Yep, so running bettertouchtool on battery kills the mac in 3.5 hours.

I set the above script to run every 30 seconds, with no real effect.  BTT uses 110% cpu, though sometimes it does not.   Is there some sort of logfile I can provide?  Should I delete the script action to see if it helps?

**Comment by fifafu** [comment]
Are these the only scripts you have configured?
You could check whether there are any BetterTouchTool logs in the MacOS console app. Otherwise I could send you a debug version that will log some more information.

**Comment by fifafu** [comment]
I think the script runner has been improved a lot in recent versions thus I'm closing here. In case this issue still happens to you, please comment again, then I may reopen.

**Comment by mainstreetmark** [comment]
I will keep an eye on it, but haven't had a flare up in a few weeks.

And, I love the double-finger volume thing.  Thanks for that!
