### ISSUE TITLE
BTT doesn't open anymore... :(

### ISSUE THREAD

**Issue by Punktwolke** [folivoraAI/BetterTouchTool#1015]
**Hi guys!**

I have an issue with my licensed BTT on MacOS Sierra.
The problem started a few weeks ago. I can’t use BTT, can’t open it and always when I slide over its symbol the loading circle becomes visible.
I already restarted the system a few times and reinstalled the app. But it only worked for a few hours.
What can I do?

**Device information**
Type of Mac: MacBook Pro Retina 13" (Mid 2014)
macOS version: MacOS Sierra 10.12.5
BetterTouchTool version: 2.12

**Comment by fifafu** [comment]
Try updating to v2.20 alpha (https://boastr.net/releases/btt2.20.zip )
