### ISSUE TITLE
Latest update breaks Remember/Save Mouse Position

### ISSUE THREAD

**Issue by paulmoons** [folivoraAI/BetterTouchTool#1018]
**Issue:** Since latest update (v2.20), my custom "four finger swipe down to show desktop" action (which pulls down the multiple desktops at the top) no longer saves/remembers the mouse position.

**Input device affected:** Built in Touchpad.

**Type of Mac:** MacBook Pro 13" with TouchBar)
**macOS version:** 10.12.5
**BetterTouchTool version:** 2.20

**Additional Information:** This gesture worked perfectly through all previous versions.

Cheers,

Paul
---

**Comment by fifafu** [comment]
Could you check if this has been fixed with version v2.260?

**Comment by paulmoons** [comment]
Thanks for applying a fix. I've tested it throughout the day and v2.260 seems to have fixed it. Thanks again.
