### ISSUE TITLE
Lost all settings!

### ISSUE THREAD

**Issue by yepeesteve** [folivoraAI/BetterTouchTool#1022]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

After the last update, I lost all of my previously saved settings.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Across the app - all saved settings for trackpad, mouse, and keyboard - all are gone!

#### Device information:

Type of Mac: MacBook Pro (Retina, 13-inch, Mid 2014)
macOS version: 10.12.4 (16E195)
BetterTouchTool version: 2.20

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by jaunt** [comment]
This just happened to me.

**Comment by jeremyramin** [comment]
+1
