### ISSUE TITLE
[Feature Request] Organization system

### ISSUE THREAD

**Issue by Natste** [folivoraAI/BetterTouchTool#1039]
As someone who has many keyboard gestures, it would be quite useful to be able to group them or be able to organize them in some way. A few ideas would be color coding, folders, categories/tags, or just the ability to create a drop down list similar to (but distinct from) the existing multi-action gestures. Thanks for all the great work!

**Comment by umtpz** [comment]
Thats what I planning to ask for. Would be nice and neat to have sub menus. Like window management, music controls, folders, applications, etc. Hope it'll be easy to make it.

**Comment by kengranger** [comment]
I am new to BTT but love it already. I would really appreciate some method of organizing my shortcuts, keystrokes, etc. I've been using another product (similar but not exactly) and have a boatload of text expansions that I am planning on porting over. Categories or something would be really handy.

Great product. Love it. Well done.
