### ISSUE TITLE
Threefinger tip-tap (middle finger)

### ISSUE THREAD

**Issue by hvedemelsbof** [folivoraAI/BetterTouchTool#1047]
Threefinger tip-tap (middle finger) seems unstable lately. I use it to close tabs in browser (⌘W). Also the left and right threefinger tiptap seemed worse, but it has helped to decrease the double-tap delay and also to allow the fingers to be closer in the trackpad-setting.

Built-in trackpad, Macbook Pro

Type of Mac: MacBook Pro (Retina, 13-inch, Late 2013)
macOS version: 10.11.6 (15G31)
BetterTouchTool version: 2.20 (641)

**Comment by redandgold45** [comment]
I'm also having trouble with registering the three finger tip-tap. I have it mapped to middle click to open and close tabs and after the update, it has worked maybe 75% of the time. I messed with the tap settings in the trackpad settings but nothing has worked.

**Comment by hvedemelsbof** [comment]
Solved by disabling thumb-correction
