### ISSUE TITLE
Modifier keys + single tap, is it possible?

### ISSUE THREAD

**Issue by nikitavoloboev** [folivoraAI/BetterTouchTool#105]
#### Description of your bug/question/feature request...:
I wish I can map a gesture like so : 

![2016-12-13 at 23 20](https://cloud.githubusercontent.com/assets/6391776/21161866/c12e47b2-c18a-11e6-8a1c-cab7f8d7cc5d.png)

But not just for middle but trigger on all single touches when these modifier keys are pressed. Is it possible to do? I tried mapping every single on of the options (top, left, right and so on) but that doesn't work reliably. I just want to map something to a single finger touch.

**Comment by fifafu** [comment]
I'll look into this. However when this is used, tap to click won't work anymore.

**Comment by nikitavoloboev** [comment]
Thank you. It would be really handy for me.
