### ISSUE TITLE
Question Regarding Tab Key

### ISSUE THREAD

**Issue by FM-Guy** [folivoraAI/BetterTouchTool#1053]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
I'm trying to fill in a login dialog ,that I have to use a lot, by using Utility Action "Insert / Paste Custom Text".  I'm trying to use Tab to go from the Account field to the Password field and I can't get it to work. It just puts everything into the Account field. ex. "name       password"

Is there a way to advance from one field to another?

#### Device information:

Type of Mac:
iMac
El Capitan: 
BetterTouchTool version: 
2.20
#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by RyantheFarmer** [comment]
It might be better for you to actually use an Apple Script to accomplish this goal.

Just put the following in AppleScript Editor:

tell application "System Events"
    set uname to "super_secret_username"
    set pword to "super_secret_password"
    keystroke uname
    keystroke tab
    keystroke pword
    keystroke return
end tell

Save it to a file, and link it to your command in BTT.  There is an option in BTT to run AppleScripts, which is super nifty for these kinds of things.
