### ISSUE TITLE
"Trigger Context Menu Item" doesn't work for Finder's context menu. 

### ISSUE THREAD

**Issue by wongjustin99** [folivoraAI/BetterTouchTool#1057]
#### Description of bug/feature request/question:
"Trigger Context Menu Item" doesn't work for Finder's context menu. 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
MacBook keyboard shortcut. 

#### Device information:

Type of Mac: MacBook Pro MacBook Pro (Retina, 15-inch, Mid 2014)
macOS version: 10.11.4 (15E2066)
BetterTouchTool version: 2.20

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
Tested to make sure my shortcut was working, then tested that other applications (Chrome) work with Context Menu trigger. 

Is Finder just not supported for this action? 

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by wongjustin99** [comment]
Hi, Not sure if this was closed as a mistake, but I didn't see any resolution to the ticket. Thanks!

**Comment by fifafu** [comment]
The BTT issue tracker has moved to https://community.folivora.ai early this year. In case you still need help with this issue / feature / question please create a new post there.
