### ISSUE TITLE
TouchBar Widget Code in Background doesn't run

### ISSUE THREAD

**Issue by derRAV3N** [folivoraAI/BetterTouchTool#1058]
#### Description of bug/feature request/question:
I have 3 Buttons on the Touchbar which function as a toggle, I'll show one here, this is the Code for the return Value:

```
set ShellReturn to do shell script "/path/to/android/adb/file/adb devices"
if ShellReturn contains ":" then
	return "ADB connected"
else
	return "Connect via ADB"
end if
```

Now this runs just fine and displays the Status just like normal. But then I have an attached Action "Run Apple Script in Background", which should run when I press on the Button and previously did work fine:

```
display dialog "Please enter Smartphone-IP:" default answer "192.168.0.3"
set IpAdresse to text returned of the result

set ShellReturn to do shell script "/path/to/android/adb/file/adb connect " & IpAdresse
if ShellReturn is "connected to " & IpAdresse & ":5555" then
	display dialog "ADB connected." buttons {"OK"} default button 1
else
	display dialog "Error message: 
\"" & ShellReturn & "\"" buttons {"OK"} default button 1
end if
```

So this does work fine when I test-run it in the configuration menu, but when I touch the button on the TouchBar, it just disappears for a few seconds and then reappears again, but without having done anything.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
TouchBar

#### Device information:

Type of Mac: MacBook Pro 2016 13" with TouchBar
macOS version: 10.12.5 (16F73)
BetterTouchTool version: 2.20 (641)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
Sadly I don't really know if this appeared after an update, since I didn't use my MacBook for a week now and don't really know what I did then.

**Comment by derRAV3N** [comment]
Any Update on this?

**Comment by fifafu** [comment]
Sorry for not replying to this issue before.

When running in background mode, Apple Scripts can not display UI like the dialog. That's probably why it was failing.

In the latest version (v2.503) you can make the Apple Script on the "Main Thread" / not in background. This will allow you to dispaly dialogues etc.
