### ISSUE TITLE
Using Emoji clears the clipboard

### ISSUE THREAD

**Issue by gunnarbeutner** [folivoraAI/BetterTouchTool#1059]
#### Description of bug/feature request/question:

When using the emoji buttons on the TouchBar BetterTouchTool clears the clipboard and whatever contents were stored there are lost.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

TouchBar

#### Device information:

Type of Mac: MacBook Pro (2016)
macOS version: 10.12.5
BetterTouchTool version: 2.20

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

None

**Comment by mergesort** [comment]
I'm seeing this as well, and would love it to be fixed. Love the touchbar support in general though, quite fantastic.
