### ISSUE TITLE
Number of buttons under "Favourites" on Touch Bar

### ISSUE THREAD

**Issue by congruencebrah** [folivoraAI/BetterTouchTool#1063]
**Question 1:**
It seems I am only limited to 4 buttons in the "favourites" area on my Touch Bar. Is there any way to expand this?

**Question 2:**
I've configured two new Global Touch Bar buttons in the main BTT window. However, they will only appear in my Touch Bar's "main container" if I tap on the "BTT Touch Icon" on my control strip.

Is there any way to make my new buttons permanent in the "main container" or is this a system-wide limit?

_Note: By "main container" I mean the area where app-specific buttons appear like music controls in iTunes._

=================================================
**Affected input device:**
MacBook Touch Bar

**Device information:**
Type of Mac:MacBook Pro 13"
macOS version: 10.12.4
BetterTouchTool version: 2.20

**Comment by fifafu** [comment]
BTT can't really influence the macOS Control Strip, thus there is no way to add more items to it.

You could however choose to hide the macOS control strip completely and fully replace it with the BTT Touch Bar (in the general touchbar settings in BTT)

In general BTT shows it's touch bar until you hide it again.
