### ISSUE TITLE
Macbook Pro 2016 Trackpad issue

### ISSUE THREAD

**Issue by skalpjaeger** [folivoraAI/BetterTouchTool#1066]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Since i have the new Macbook with the bigger Trackpad, i often have the problem that i touch the Trackpad by accident (laying in the bed sometimes it seems that its even caused by the blanket which touches the Trackpad) or when im typing i touch it with my hand. The Trackpad does not work then anymore (klicking has no effect etc). Until today, i thought that its a problem of the new Macbook but I realized, that it only occur when Bettertouchtool is active. When its closed, the Trackpad worked as it should...

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Trackpad

#### Device information:

Type of Mac: Macbook Pro 13 2016 with Touchbar
macOS version: 10.12.5
BetterTouchTool version: 2.20

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Do you have thumb handling activated in the advanced trackpad prefs? (Should be on by default)

**Comment by skalpjaeger** [comment]
Yep it is and i just deactivated it but there is no difference :/ And unfortunately it is really Bettertouchtool because every time i deactivate it, the Trackpad works absolutely fine even with my hand on it...

**Comment by fifafu** [comment]
It depends a lot on the gestures you add in BTT. For some gestures  BTT needs to e.g. block clicks when it recognizes touches.

**Comment by skalpjaeger** [comment]
Do u know the problematic gestures? These are mine...

<img width="1127" alt="screenshot_2017-06-12 19 58 37" src="https://user-images.githubusercontent.com/29382197/27047775-8beec56a-4fa9-11e7-948f-b52bd5412340.png">

**Comment by fifafu** [comment]
In your case it's probably the corner click gestures

**Comment by skalpjaeger** [comment]
damn it seems you are a god, i deleted them and the problem seems to be solved...thanks for the incredible and fast support! Is there a chance to fix this?

**Comment by bewebste** [comment]
I've had an issue very similar to this, with a Magic Trackpad. For me, the problem started relatively recently (maybe the last 2-3 weeks?), so it does seem like some recent update might have changed something. (I'm currently running 2.21 with alpha updates enabled) In experimenting, it seemed like the thing that would most consistently stop clicks from working was doing a double click on something beforehand. Normal clicks would then not register, but I could "unstick" things by performing a force click, and then regular clicks would start working again.

Reading this thread, I tried disabling gestures one by one, and eventually found it was a two-finger force click gesture that seemed to be the culprit. So, I hope that data point is helpful, and let me know if there's any other info I can provide.
