### ISSUE TITLE
Gestures on Login Screen Broken? 

### ISSUE THREAD

**Issue by sachinsid** [folivoraAI/BetterTouchTool#1071]
I used to be able to use BTT to unlock my Mac via a TrackPad gesture (Action was typing in the password). It has completely stopped working recently even though BTT is running in the backgroud. 

MacBook Pro (Retina, 15-inch, Mid 2015)
Built In Force Touch Trackpad
macOS version: 10.12.5 (16F73)
BetterTouchTool version: 2.20 (641) 

Also noticed that the action does not work consistently even after I have logged in ever since I upgraded both my OS and BTT. I tried changing the Custom Action to a Paste instead of a Type, but does'nt change results. I use this gesture 100's of times a day (unlocking, desktop applications, VPN etc), and  is causing a major grief in terms of productivity.

**Comment by fifafu** [comment]
Depending on how you log out BTT disables itself in order to be able to support multiple users on one system. This should however be improved with the next alpha version.

The paste action should work fine, what exactly doesn't work for you when using it?

**Comment by sachinsid** [comment]
I don't log off from my mac, I just lock it. BTT is running it the background, but does not respond when I perform my gesture on the trackpad. It takes atleast 6-8 attempts at the same gesture for it to work, and even then sometime it just does not work, and I need to reenter my password manually. 

The latest version also did not help.

**Comment by joeycozza** [comment]
I believe I have a similar issue with using keyboard shortcuts from the Lock Screen. I use the Lock shortcut, and want to use the Unlock shortcut, but it doesn't seem to trigger when I use my defined shortcut for the unlock.  

I also tried doing the Paste Text shortcut, and it also does not seem to trigger from the Lock screen.
