### ISSUE TITLE
Close Window Below Cursor stops working randomly

### ISSUE THREAD

**Issue by tonynca** [folivoraAI/BetterTouchTool#1073]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
"Close Window Below Cursor" stops working randomly. I need to restart BTT to get it to work again.
I'm using 'Corner Click Bottom Left' as my gesture.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Trackpad/MBP Trackpad

#### Device information:

Type of Mac: mid-2014 rMBP 15" 
macOS version: 10.12.5
BetterTouchTool version: 2.20

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
If this happens again please open the BTT preferences, then go to the About tab and click the "Export Debug Info" button. This will create a folder on your desktop. If possible please send the contents to boastr.net@gmail.com, this may help me identify the issue (it's most likely some incompatible app that breaks it, so I should blacklist it)

**Comment by tonynca** [comment]
Reinstalling fixed it. Thanks.
