### ISSUE TITLE
Application switcher both ways

### ISSUE THREAD

**Issue by btyin22** [folivoraAI/BetterTouchTool#1074]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
I'd like to be able to use the application switcher to go left as well right through the apps open. i.e. Command Shift Tab. Currently I invoke the application switcher using five finger tap, and then each tip tap moves the selector one to the right. 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
All Macs 

#### Device information:

Type of Mac: MacBook Pro 13st 2013
macOS version: 10.12.2
BetterTouchTool version: 2.20 (640)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by mikeweilgart** [comment]
+1.  It would be great if this worked with alt-tab, also.  (Currently, as I described in a comment on #879, I can't work out any way to make shift-tab take me backwards in the list.  Shift just exits the application switcher if it was opened with alt-tab.)

**Comment by Coletrane** [comment]
It would also be great if holding down the custom key combination kept cycling through the app icons like holding down command + tab/ command + shift + tab does.
