### ISSUE TITLE
Two finger double tap stopped working again!

### ISSUE THREAD

**Issue by mrdampsquid** [folivoraAI/BetterTouchTool#1076]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Two finger double tap not recognized, live view shows taps in right place, but nothing triggers.  This was working, then didn't work reliably, then last month or two was fine again, and now not working at all.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Magic Mouse

#### Device information:

Type of Mac: MacBook Pro mid 2015
macOS version: 10.12.5
BetterTouchTool version: 2.10(626) and 2.20(641)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
This seems to work fine here. Are you sure you have disabled double-tap in system preferences?

![image](https://user-images.githubusercontent.com/8820811/27178172-84386264-51c9-11e7-9dee-607222caacc9.png)

**Comment by mrdampsquid** [comment]
Yep, this has always been disabled - I checked anyways.  I’m also having trouble with app specific settings for at least one app so far that used to work fine.  Two finger double tap has always been problematic. :(

**Comment by fifafu** [comment]
If possible please go to the about tab in BetterTouchTool and click the export debug info button. This will create a folder on your desktop called BetterTouchToolDebug. Please send the contents of that folder to boastr.net@gmail.com.

Using that I may be able to reproduce the issue.

**Comment by mrdampsquid** [comment]
I rebooted the Mac since, now it’s working again, both the double tap, and the app specific. (I had previously restarted BTT and upgraded to the latest non-alpha, without success)  I happy to send the info below if that’s still useful, just let me know.
Thanks
Bob
