### ISSUE TITLE
Global actions holding touchbar BTT icon?

### ISSUE THREAD

**Issue by koro-xx** [folivoraAI/BetterTouchTool#1077]
According to the docs holding the BTT icon in the touchbar forces the global actions to be displayed if there are app-specific actions. However when I hold the BTT icon what I see is an earth globe 
button added to the actions in my app, which does nothing when pressed. 

#### Device information:

Macbook pro 13'' Touchbar
macOS Sierra 10.12.5
BTT 2.20 (641)

**Comment by el-lsan** [comment]
+1
