### ISSUE TITLE
[Drawing] Straight line gestures?

### ISSUE THREAD

**Issue by iandol** [folivoraAI/BetterTouchTool#1094]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
I've used mouse gestures since forever (when they were first introduced with Opera many many moons ago). Straight line gestures are very useful as they are the simplest to execute, and get you 4 useful gestures depending on direction or more if you take diagonals into account. It would be great to be able to use single-line gestures in BTT.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Magic Mouse / Macbook trackpad / Magic trackpad

#### Device information:

Type of Mac: iMac / MBP
macOS version: 10.12.5
BetterTouchTool version: 2.21

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
I will add support for straight lines soon (hopefully by the end of the month)

**Comment by JannesMeyer** [comment]
I just wanted to let you know that I would definitely buy Better Touch Tool if it had this feature.

I just started the trial and I'm a bit disappointed that the recognition accuracy for straight lines is so bad. Even after setting the maximum gesture rotation to 4 degrees.

**Comment by fifafu** [comment]
Oh good point - I started the implementation a few months ago but forgot about it.
Will try to finish the straight line recognition next week.
