### ISSUE TITLE
[Feature Request] Scrolling text

### ISSUE THREAD

**Issue by nlpthk** [folivoraAI/BetterTouchTool#1099]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

I thought it would be neat if text were able to scroll within its Touch Bar button. This would only apply to those strings/lines/text that were too large for the given box dimensions. I think the now playing widget would have a good use for this, since not all titles can fit within the margins. 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Touch Bar

#### Device information:

Type of Mac:
macOS version: 
BetterTouchTool version: 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by g2010a** [comment]
This would be brilliant! I have an updates and news ticker and forcing headlines to <40 characters makes it inconvenient.

**Comment by ronunism** [comment]
+1 to this idea.
