### ISSUE TITLE
BTT interferes with itself when running in multiple user accounts

### ISSUE THREAD

**Issue by briankendall** [folivoraAI/BetterTouchTool#1109]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

Starting in 2.20, BTT interferes with itself when running in multiple user accounts. When switching between users, BTT does not disable itself when its user account becomes inactive, and instead continues to receive mouse and keyboard input. The result is that you cannot use BTT in a second user account if it has actions assigned to the same events as an instance of BTT running in the first user account.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Regular mouse and keyboard (but presumably affects all input devices)

#### Device information:

Type of Mac: 2017 iMac 27", 2009 Mac Pro, 2015 MacBook Air (but presumably this affects all Macs)
macOS version: 10.12.5
BetterTouchTool version: 2.20

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

N/A

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by bilal-khan** [comment]
I've been seeing this issue before 2.20 (and still present in 2.20).

Mac Pro 2009, 10.12.5 (Happened in all versions of 10.12, and maybe earlier)

**Comment by fifafu** [comment]
Yes, this has always been like this.
However it's on my todo list and I hope to be able to fix it sometime soon.

**Comment by briankendall** [comment]
I've downgraded to 2.12 and it doesn't have the problem, so it was introduced sometime between 2.12 and 2.20.

**Comment by fifafu** [comment]
Mh, that must be some coincidence then, because I have known about the underlying issue for a long time and not fixed it yet.
2.12 definitely also contains that behavior, but maybe it doesn't occur in your specific setup.

**Comment by bilal-khan** [comment]
I would ❤️ a fix for this!
Right now i have to quit BTT on one account each time i switch. It's so sad to have to quit software you love ☹️

**Comment by fifafu** [comment]
If possible, please try version 2.260 - I can't promise it's working correctly yet, but I added some initial workarounds. Will need to see if it works this way or if I need to do further adjustments.

**Comment by bilal-khan** [comment]
Installed the update, will run it for 24/48 hrs and report back!

**Comment by ming-jen** [comment]
I have been using version 2.260 for days and it does not fix this problem. The only solution is to restart BTT, and do the same when I get back into the other user account.

**Comment by briankendall** [comment]
2.261 doesn't fix it for me either. What I do to work around it is disable BTT before I switch to another user account.

Any reason why BTT couldn't just automatically disable itself when the user session it's running in becomes inactive? That way there's only one instance of BTT enabled at a time.

**Comment by bilal-khan** [comment]
For what it's worth, seems to be working for me...

**Comment by bilal-khan** [comment]
I take it back, this morning it started breaking for me ☹️

**Comment by valrus** [comment]
Happening for me too in 2.297, though disabling BTT in the account I'm not using is an acceptable workaround for me for now.

**Comment by FryJay** [comment]
I just bought BTT and I run into this issue as I use a home and work account on my laptop and I just leave them both logged in most of the time.  My workaround is just shutting off BTT on whichever account I'm not using at the time.

**Comment by briankendall** [comment]
Does anyone know if this issue is fixed in 2.313? I'm still holding on 2.12 since that's the last version that didn't have this bug.

**Comment by fifafu** [comment]
No, but I think I may have identified the issue last weekend. There should be a update that includes a workaround next weekend!

**Comment by avtraino** [comment]
This is happening for me on 2.332. 

I'd be happy to provide more information for troubleshooting if necessary.

**Comment by avtraino** [comment]
Also on 2.340.

Specifically, under Mouse settings, the option "Inverse scrolling for normal mice only".

This overlaps when running on two users so it's double-inverted on one user (i.e., not inverted)

**Comment by guness** [comment]
I am currently using latest version of BTT. I have two users on my Mac. Even tried to quit on first user and try on second user, but no luck. Second user cannot use BTT to alter touch bar.
