### ISSUE TITLE
Modifiers for touchbar buttons not working properly?

### ISSUE THREAD

**Issue by annoyingfolo** [folivoraAI/BetterTouchTool#1116]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
I have set up a button that I only want to appear while a certain modifier is pressed. Now this works as intended, but if a press any other modifier the button appears anyway.

The button, named test, is set up with control as modifier and is placed in a button group. If I press control, the other buttons in the group are hidden and the test button appears as intended. Releasing control hides test and the other buttons reappear. If I instead press alt/cmd/fn/shift the test button appears along the other buttons in the group. Releasing the modifier hides test again.

This doesn't seem correct to me...

Video:
https://dl.dropboxusercontent.com/u/15985477/BTT.mov 
Button settings:
https://dl.dropboxusercontent.com/u/15985477/BTT.JPG

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Touch bar

#### Device information:

Type of Mac: MacBook Pro, touch bar 13"
macOS version: Sierra, 10.12.5
BetterTouchTool version: 2.20

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by CarlAndersson** [comment]
This seems to still be a bug in 2.536. Worth to note is that the problem is only for buttons/widgets with modifier keys in groups. Buttons/widgets outside groups work as intended.
