### ISSUE TITLE
Support top/bottom thirds/two thirds window resize actions

### ISSUE THREAD

**Issue by swrobel** [folivoraAI/BetterTouchTool#1124]
#### Description of bug/feature request/question:
Feature request: it would be useful for those of us who use vertically-oriented monitors to have top/bottom thirds & two thirds options.

**Comment by aoeusnth** [comment]
This would also be greatly useful to those with very large monitors (like my 48" 4K) which often is used in lieu of two portrait monitors.

**Comment by jjaaccoobb** [comment]
Bump. Would love this feature for my vertical monitor to use the top two thirds for an editor, bottom third for a terminal. Please implement!
