### ISSUE TITLE
Failed to import/export across Macs

### ISSUE THREAD

**Issue by xunlao** [folivoraAI/BetterTouchTool#1127]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

I tried to export settings (preset)from 1 machine to another using export+import/sync with dropbox, but none works on the target machine.

Attached the log from the target machine.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

All

#### Device information:

Type of Mac: Macbook Pro 15' 2016
macOS version: 10.12.5  (both machines)
BetterTouchTool version: 2.260 (both machines)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

[com.hegenberg.BetterTouchTool.plist.txt](https://github.com/fifafu/BetterTouchTool/files/1104331/com.hegenberg.BetterTouchTool.plist.txt)

[log-86EC4D.txt](https://github.com/fifafu/BetterTouchTool/files/1104327/log-86EC4D.txt)
[log-A3ADD0.txt](https://github.com/fifafu/BetterTouchTool/files/1104328/log-A3ADD0.txt)

**Comment by fifafu** [comment]
Hi,

Could you please attach the exported json?  (Or send it to boastr.net@gmail.com)

This may help me identify why it's not working for you.

**Comment by xunlao** [comment]
Please see in the attachment.

[2017-6-26 BBT 4*3fing,4*4fing.json.txt](https://github.com/fifafu/BetterTouchTool/files/1106284/2017-6-26.BBT.4.3fing.4.4fing.json.txt)


Thanks

**Comment by mylemans** [comment]
I have the same issue, could it be because the other one doesn't have all the apps that I exported from?
