### ISSUE TITLE
Feature request: Move window *while* mouse button is pressed

### ISSUE THREAD

**Issue by sos4nt** [folivoraAI/BetterTouchTool#1129]
I want to move the window under the cursor via a mouse button.

The action _"Start/Stop Moving"_ under _"Window Resize & Move"_ almost does what I want. But it is a toggle action, i.e. I have to **click** the mouse button (press it and release it) to start moving the window and click it again to stop moving the window.

This mode switch seems unintuitive to me. I'd like to have the option to move a window *while* holding down the mouse button, i.e. pressing the button starts moving the window and releasing the button stops moving it.

**Comment by fifafu** [comment]
Hi,

you may be able to achieve this by adding the action twice, once on mouse-down and once on mouse up. See this screenshot:

![image](https://user-images.githubusercontent.com/8820811/27659723-dd8d47ea-5c54-11e7-932f-15e26c5a99a7.png)

**Comment by sos4nt** [comment]
I've already tried that, but it stops working when I add it twice. The action seems to always be triggered upon mouse-up, i.e. moving doesn't start before I release the button.

**Comment by fifafu** [comment]
You are right, I'll try to fix this!

**Comment by fluffynuts** [comment]
The requested feature would make this action a lot more like the "alt-drag" behavior of *nix desktops and the "Alt-Drag" application (win32) which attempts to mimick this.
Personally, I'd /really/ like this feature -- the current mechanism feels a little odd to me.

**Comment by erlingur** [comment]
Was this ever fixed or worked out?

**Comment by Rob-ot** [comment]
This would be such a huge feature for me. Like fluffynuts said, it's common behavior on *nix and Alt-drag does it well on Windows, but there is currently no way to do this on OSX (that I've found). I already bought BTT in hopes this feature is added soon.

Thanks!

**Comment by round** [comment]
Best alternative to this behavior that I've found is HyperDock:
![image](https://user-images.githubusercontent.com/2340336/49549856-fb159780-f8b7-11e8-8a3c-60e8bae5ab7c.png)
https://bahoom.com/hyperdock

**Comment by Rob-ot** [comment]
@round Wow it works! Thanks so much!
