### ISSUE TITLE
[FEATURE REQUEST] Numbers to select Clipboard History item to paste

### ISSUE THREAD

**Issue by DCNielsen** [folivoraAI/BetterTouchTool#1143]
#### Description of bug/feature request/question:

A common feature of many Clipboard management tools is that once the Clipboard comes up, the user can press a number to choose item 1-9 or 1-0 to paste. This is something I miss from the managers I've used and would love to have so I can replace them with BTT.

**Comment by fifafu** [comment]
I'll add this soon!
