### ISSUE TITLE
[Feature Request] Regular Mouse Gestures & Chording

### ISSUE THREAD

**Issue by rodalpho** [folivoraAI/BetterTouchTool#1153]
Currently BTT only supports trackpad and magic mouse drawing gestures.

Mouse gestures are activated by pressing a button and then moving the pointer. Mouse Chording is activated by pressing one mouse button followed by another. A couple shortcuts I like to use in my browser:

RMB+moveleft to Switch to Left Tab (cmd-option-leftarrow)
RMB+moveup to Open new Tab (cmd-T)
RMB+mousewheelup to Zoom In Page (cmd+) 
Hold RMB then press LMB chord to Close Current Tab (cmd-W)
Hold LMB then press RMB chord to Re-open Last Closed Tab (cmd-shift-T)

You can do this in a browser via addons like the excellent Firegestures for Firefox, but I have yet to find a great consistently-working mouse gesture extension for Chrome or Safari, and would love to use mouse gestures and chords in other applications too.

**Comment by djohnsen** [comment]
I use [Steermouse](http://plentycom.jp/en/steermouse/index.html) (mostly to support my ancient Kensington Expert Mouse trackball) which provides chording capabilities.

Be warned that the behavior is a little inconsistent (some apps grab/ignore part of the clicks on primary buttons) and Steermouse will complain that BTT interferes with it (though I have not noticed specific problems)
