### ISSUE TITLE
Keyboard Shortcuts Stop Working After Fast User Switching

### ISSUE THREAD

**Issue by Haravikk** [folivoraAI/BetterTouchTool#1158]
#### Description of bug/feature request/question:

This issue appears to affect the two most recent versions of BTT (currently on v2.261), basically I have a setup with multiple user accounts for different purposes, and often switch between them. All the accounts have BTT enabled (one system-wide copy, per-user instances on login) with the same set of keyboard shortcuts, mostly just a bunch of media controls (volume up/down/mute, play/pause and next song).

However, in the last few versions I've encountered an annoying issue whereby switching users sometimes (but not always) causes all of my custom BTT shortcuts to stop working on the account that I have just switched to, giving me an error beep instead and forcing me to quit and relaunch BTT to restore them.

More annoying still is that the issue is intermittent with no obvious pattern to it, i.e- it doesn't happen every time I switch, so unfortunately I have no way to force it to happen, or an idea what could be triggering BTT to "forget" its shortcuts.

This is a problem that I have encountered in the past, but only immediately after installing a BTT update under one user account, while others are logged in with BTT loaded, whereby other accounts would experience the issue and I'd have to close the old version and launch the new one manually for each of them, either that or restart. However, this issue is happening this time even on a freshly started machine; it just (seemingly) randomly occurs after switching users, but not always.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Keyboard I suppose?

#### Device information:

Type of Mac: Mac Mini (2012)
macOS version: 10.11.5
BetterTouchTool version: 2.261

**Comment by Haravikk** [comment]
Anyone else experiencing this? Anything else I can do to debug it?

This issue is effectively rendering BTT unusable for me now, as keyboard shortcuts are the main thing I use it for (plus window snapping); as I say it didn't affect older versions so it's a regression somewhere, but I have no idea what is actually triggering the problem, except that it only occurs after user switching.

**Comment by klutzak** [comment]
I have this issue as well. I have a scroll wheel -left and -right click action set up. It works fine in my first user but when I switch to another user and try to use the custom action it does not work. In addition, the BTT icon in my menu bar greys out when I attempt to use the custom action, until I restart BTT from the preferences - if that helps any troubleshooting...

**Comment by joshuasmay** [comment]
I'm also experiencing this. I find I have to restart BTT each time I fast switch.

**Comment by Haravikk** [comment]
Same. If there's no sign of any progress on this I'm going to have uninstall BTT and look elsewhere for custom shortcuts, as in its current form BTT is simply unusable.

**Comment by fifafu** [comment]
I have not yet looked into this issue, but it's high up on my Todo list.

Best 
Andreas

**Comment by Haravikk** [comment]
I haven't noticed this problem in a while now, is anyone else who was affected still experiencing it?

**Comment by Haravikk** [comment]
So unfortunately this problem is back following the latest update (v2.405), fast user switching to another account renders BTT unusable.

However, there's something extra weird with the issue; it seems that when BTT under one user becomes unresponsive, the keyboard shortcuts are actually operating BTT for *different* user, which raises some serious issues with how BTT operates.

To give you a reproduction:

1. On a system with multiple user-accounts, enable BTT to open on login two or more of them, using the same set of keyboard shortcuts. In my case I map F1 to send space to iTunes (to play/pause), F2 for mute, F3 for volume down, F4 for volume up, F5 for Spotlight and F6 to send Command + Right to iTunes (for next song), these are to match the media keys of my Microsoft Ergo Sculpt keyboard under macOS. Ensure two of these accounts are logged in.
2. Switch from one account to the other.
3. Attempt to use your keyboard shortcuts, particularly those sending key-presses to an application.
4. Switch to the other user account and do the same.

In one or both user accounts you may find that the shortcuts don't appear to work, however, it's possible that the shortcuts are in fact operating upon the other account! For example, with two accounts Foo and Bar, I might press F1 while switched into Foo, and find that upon switching to Bar that iTunes is now playing music!

There's definitely something screwy with the way that BTT is dispatching shortcuts, key-press actions in particular, and it may have something to do with how it operates when running under multiple user accounts on the same system.

**Comment by fifafu** [comment]
Yes, sorry I still haven't addressed multi user support. Currently BTT still listens globally for keyboard shortcuts.

This is currently on the roadmap for the v2.5 release in April.

**Comment by dploeger** [comment]
Any news on this? We have 2.5 now and the problem is still there.
