### ISSUE TITLE
2 Finger Swipe From Right Edge - not working

### ISSUE THREAD

**Issue by sk91ca** [folivoraAI/BetterTouchTool#1159]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
When using "2 Finger Swipe From Right Edge", no assigned action works.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Macbook Pro trackpad

#### Device information:

Type of Mac: Macbook Pro (Late 2013)
macOS version: macOS Sierra 10.12.5
BetterTouchTool version: 2.260

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by adidoes** [comment]
I have the same issue ever since updating to Sierra.
