### ISSUE TITLE
REQUEST: Window Snapping to 1/3 of the display

### ISSUE THREAD

**Issue by fabi94music** [folivoraAI/BetterTouchTool#1160]
#### Description of bug/feature request/question:
Would be awesome to have the ability to drag a window to the bottom 1/3 and it snaps to one third of the screen, similar to Magnet. As it is already possible to use this via Shortcuts or predefined actions it would be wonderful if you could support this via  windows snapping :) 
Oh and I would love to have the option to adjust the roundness of the edges in Window Snapping, just like in Snap Area options.

#### Device information:

Type of Mac: MacBook Pro 15inch
macOS version: 10.12.5
BetterTouchTool version: 2.261

**Comment by fifafu** [comment]
I'll probably add more default snapping areas soon, however you can already define your own, custom snap areas by clicking the BTT menubar icon and selecting the add new snap area item.

**Comment by fabi94music** [comment]
Thank you! Yeah I know, but the snap areas only work on the specific monitor the were set, right? 
Would be awesome to have snap areas across al monitors (I have an external monitor connected to my Macbook)
