### ISSUE TITLE
[IMPROVEMENT] Show/Hide Hidden Files in Finder

### ISSUE THREAD

**Issue by jshrek** [folivoraAI/BetterTouchTool#1165]
#### Description of bug/feature request/question:
When you assign the Predefined Action under Utility Actions > Show/Hide Hidden Files in Finder to a keyboard shortcut in Finder (let's use FN+Double-Click_Window_Title_Bar) and then you use this shortcut in Finder, it will cause Finder to close. You then need to re-open Finder, and then you will see the hidden files are shown. If you use the shortcut again, it causes Finder to close again. When you re-open it again, the files are hidden again.

However there is another shortcut of SHIFT+CMD+.(period) that instantly shows/hides hiddens files in Finder and it does not close Finder (and therefore you don't have to re-open it).

So my improvement/suggestion is that it may be possible to improve the performance of Show/Hide Hidden Files In Finder by changing it to the SHIFT+CMD+. instead of doing whatever you are currently doing.

Thanks

**Comment by fifafu** [comment]
Unfortunately this only works on the most current version of macOS, but yes I should add that for versions >= 10.12.
