### ISSUE TITLE
Mouse speed modifier does not work

### ISSUE THREAD

**Issue by smxshxishxad** [folivoraAI/BetterTouchTool#1173]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
I would like to slow pointer speed using modifier key when I engaged to accurate task.
Modifier key stopped working when I started to use roller mouse by Contour Design.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Roller mouse by contour design

#### Device information:

Type of Mac: iMac (Late 2015)
macOS version: OS X El Capitan
BetterTouchTool version: 2.266

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by cleverjackal** [comment]
Only works on El Capitan and earlier

**Comment by whirka** [comment]
I'm encountering this bug on El Capitan as well.

BetterTouchTool version 2.293
OSX El Capitan 10.11.6
Macbook Pro (Late 2013)

I used to have my mouse setting at 8 and noticed that it was moving very slow. I looked into my BetterTouchTool mouse speed settings and it was set at 3. I try to change it and the mouse stays at a constant speed. I close the panel and go back in and it is still showing at 3. If I use the modifier setting (ctrl key) I can achieve higher speeds, but nothing I try allows the "Default" to change anymore.

**Comment by eljeffe58** [comment]
Are there plans for this issue to be fixed?

**Comment by TeeJay942** [comment]
I'm having a similar issue.  The MacOS .GlobalPreferences for mouse scaling is being changed when BTT's "mouse speed" setting is changed.  This doesn't make sense since as you increase mouse speed in BTT, the increase to mouse scrolling actually slows down the mouse.  It's very hard to figure out a setting that's usable.
