### ISSUE TITLE
Archicad mouse stick

### ISSUE THREAD

**Issue by Andru-bonus** [folivoraAI/BetterTouchTool#1182]
When BTT is working when I select any item in Archicad using Magic Mouse or Any other mouse - it not only selects, but also makes smth like double click - so the item is dragging and I need to press ESC to disable dragging...

**Comment by bdarch** [comment]
This is a "me too" regarding the Archicad problem. 
When shift-clicking to select an element, there is a very short delay after moving the mouse away from the selected element or elements before the cursor starts to drag the selected elements. By "start to drag" I mean the selected set suddenly jumps to the current cursor position. ESC stops the drag. When selecting multiple elements the number of clicks varies before this "drag bug" kicks in.
