### ISSUE TITLE
Resize window to center of screen

### ISSUE THREAD

**Issue by chessisamazing27** [folivoraAI/BetterTouchTool#1194]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

The option for center window moves the current window to the center. Is there possible if there is a center window option that resizes the window to the center of the screen rather than just not affecting the window size. 

#### Device information:

Type of Mac:
macOS version: 
BetterTouchTool version: 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by L-C-P** [comment]
I would subscribe to the request. I'm still using SizeUp! in addition to center the window and set it to an absolute or relative screen size.

**Comment by supa42** [comment]
I kinda have this set up already. Set action to resize to a corner of the screen, then attach an action to centre the window :)

**Comment by fifafu** [comment]
In v2.460 (alpha) there is a new predefined action which can do all sorts of custom window moving and resizing:
![image](https://user-images.githubusercontent.com/8820811/39365653-08ef6b04-4a32-11e8-98be-4befc40b4506.png)
