### ISSUE TITLE
Customize control strip icon

### ISSUE THREAD

**Issue by bongardino** [folivoraAI/BetterTouchTool#1196]
Specifically referring to the icon enabled via  
Gestures > Touch Bar > General Touch Bar Settings - Show BetterTouchTool Icon in Control strip

By default this is the BTT logo.  Is this customizable?   If not changeable through the UI, is it referenced anywhere we can change it manually?

**Comment by fifafu** [comment]
That’s currently not possible, but I like the idea and will try to make this customizable!
