### ISSUE TITLE
Feature Request: Remove emoji widget left and right buttons

### ISSUE THREAD

**Issue by mergesort** [folivoraAI/BetterTouchTool#1199]
Description of bug/feature request/question:

Remove the left and right buttons on the emoji widget. I would love to be able to just have the emoji widget be swipe oriented, since I don't ever want to use the buttons to browse back and forth.

Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

TouchBar

Device information:

Type of Mac: MacBook Pro (2016)
macOS version: 10.12.5
BetterTouchTool version: 2.266

**Comment by JCLaHoot** [comment]
It should be optional. Having to navigate all the emoji simply by scrolling would taker too long
