### ISSUE TITLE
Keyboard Sequence: Allow "long" press of a button

### ISSUE THREAD

**Issue by fantaaaaaa** [folivoraAI/BetterTouchTool#120]
Would it be possible to implement a longpress of a button for keyboard sequences?

It would be great if we could press and hold the CMD key for example to trigger an action. Or Longpress CMD followed by S to shut the mac down for example.

I imagined this would be possible by adding a "delay" inbetween a press and a release here:

<img width="1099" alt="screenshot 2016-12-15 10 22 18" src="https://cloud.githubusercontent.com/assets/24585031/21218385/abd40c90-c2b0-11e6-870e-1cda759d53f8.png">

**Comment by fifafu** [comment]
This will be added soon!

**Comment by fantaaaaaa** [comment]
is this already available in 2.0? cant see it anywhere...

**Comment by fifafu** [comment]
No will be available sometime in February

**Comment by fantaaaaaa** [comment]
hey andreas. is this still being planned for some time in february or soon? would be awesome!

**Comment by fifafu** [comment]
This issue was moved to https://community.folivora.ai/t/keyboard-sequence-allow-long-press-of-a-button/94

**Comment by fifafu** [comment]
Sorry, please ignore the previous message. The migration didn't work correctly, for now the issues will stay here.
