### ISSUE TITLE
Color temperature changes with shortcut activation

### ISSUE THREAD

**Issue by Kapowpenguin1** [folivoraAI/BetterTouchTool#1200]
#### Description of bug/feature request/question:
Whenever I try to use "Move right a space" with a button on my mouse, whenever I'm on the home screen of my Mac with no windows open, the color temperature swaps between cold and warm whenever I activate the shortcut. The shortcut itself doesn't activate. Unsure if I'm doing something wrong, or making a mistake. Also, I tried pressing the same buttons without BTT open, and they don't do anything, so I'm sure it's BTT. 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Redragon mouse (Centrophorus)- It's those two buttons red buttons on the side I use.

#### Device information:

Type of Mac: MacBook Air (11-inch, Mid 2013)
macOS version: 10.12.5
BetterTouchTool version: 2.266 (656)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---
I don't know if any more info is needed, and will try to provide if that's the case.

**Comment by fifafu** [comment]
Could you send me an export of your gestures to boastr.net@gmail.com? (Alternatively go the the “About” tab in BTT and click the “export debug information” button, this will create a folder on your desktop. You can also send that folder to me).

Do you maybe have the “toggle night shift” action assigned somewhere?
