### ISSUE TITLE
Refactor: Switching Master preset should keep current master preset active?

### ISSUE THREAD

**Issue by kamykaze** [folivoraAI/BetterTouchTool#1211]
Currently, when I have two presets (eg: presetA, presetB), switching the master preset from presetA to presetB, makes it so presetA is inactive, and presetB is active (and new master)

I'm sure this was the intended behavior, and works great if you're only using one preset at a time.

My use case is a bit different. I have one preset per device, plus a base preset that I always have active. This is so that whether I'm on my laptop, work computer, etc. I can sync all my presets, and only turn on those presets that are relevant (magic mouse on the imac, but trackpad on the laptop, keyboard on both)

The problem now is that whenever I want to switch master preset to add a gesture for a specific device, the previous preset becomes inactive.

It would be nice if both presets remained active.

**Comment by fifafu** [comment]
The "Switch to preset" predefined action allows you to switch the master preset and also keep other presets enabled, see this screenshot:

![image](https://user-images.githubusercontent.com/8820811/28286484-a1fde80e-6b38-11e7-93ea-9e8f7bbd5df5.png)

Maybe I can add a setting that lets you always keep other presets enabled also when switching via the normal "Manage Presets" button.
