### ISSUE TITLE
Not finding the default snap locations

### ISSUE THREAD

**Issue by roseSentient2015** [folivoraAI/BetterTouchTool#1213]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
When I pull and snap to top right corner under default settings to snap to half-screen (height and width) it isn't snapping.

Been using BTT for over 1 year with default settings without issues.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Macbook Pro
Magic Mouse
Double-Screen Set up (I've used this for over 1 year.  Set up screen displays to snap accordingly to both screens.)

#### Device information:

Type of Mac: Macbook Pro
macOS version: OS X El Capitan 10.11.6
BetterTouchTool version: 2.266

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Have you tried to restart your Mac? There hasn't been a change to this for quite a while.
