### ISSUE TITLE
Feature Request: Application disable Drawings

### ISSUE THREAD

**Issue by iandol** [folivoraAI/BetterTouchTool#1217]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Some programs like Vivaldi or Opera already implement their own mouse gestures (what BTT calls Drawings). Currently we have to completely disable BTT for such programs. It would be nice if we could disable "drawings" but still allow gestures / keyboard control etc.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Mouse / trackpad

#### Device information:

Type of Mac: iMac Late 2015
macOS version: 10.12.5
BetterTouchTool version: 2.270

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by qywx** [comment]
I there a way to **disable them at all**? 

I want to application defined dragging while right button pressed.  Useful for 3d editors and even to drag file in finder and open context menu to select action.
