### ISSUE TITLE
Allow re-map of mouse right click without modifier

### ISSUE THREAD

**Issue by aioue** [folivoraAI/BetterTouchTool#1219]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

Want to remap right-click on my mouse to another button, but BTT wants me to select a modifier.

I would like to re-map that button without a modifier.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Evoluent external USB mouse

#### Device information:

Type of Mac: MBP
macOS version: Sierra
BetterTouchTool version:  2.265 latest

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
The BTT issue tracker has moved to https://community.folivora.ai early this year and all issues here have been auto-closed now. In case you still need help with this issue / feature / question please create a new post there.
