### ISSUE TITLE
Cannot find experimental dragging option for touchpad anymore

### ISSUE THREAD

**Issue by hoanghuynh** [folivoraAI/BetterTouchTool#1221]
#### Description of bug/feature request/question:

Previous versions of BTT seems to have this option called "Experimental dragging" for trackpad that is killer for me. It's the number one reason I bought BTT because I hate the drag lock delay of Mac OS.

But I can't seem to find this option now? Am I missing something?

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

MacBook Trackpad while dragging

#### Device information:

Type of Mac: MacBook Pro (Retina, 15-inch, Late 2013)
macOS version: 10.12.5 (16F73)
BetterTouchTool version: 2.270 (658)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

On an old version where the option is available:

![image](https://user-images.githubusercontent.com/105269/28335543-f2a3a096-6c28-11e7-9521-696883bd5133.png)

Newer versions where I can't find the option anymore:

![image](https://user-images.githubusercontent.com/105269/28335690-790a9504-6c29-11e7-82cc-8c3f6ed69674.png)

---

**Comment by stroka99** [comment]
+1

**Comment by psymps** [comment]
+1

Same issue as the OP. Would really like to remove the drag delay found in MacOS

**Comment by alekdimi** [comment]
+1

**Comment by pbastowski** [comment]
I bought BetterTouchTool in large part because of this functionality. Please bring it back.

**Comment by dbogoslovtsev** [comment]
Please bring it back, tap and drag delay is really annoying

**Comment by kaeliss** [comment]
+1

Please bring the option back, this option was the primary reason why I purchased BTT.

**Comment by hoanghuynh** [comment]
Agreed, this is like the main reason I bought BTT.

**Comment by fifafu** [comment]
I'll look into this, but as far as I remember macOS 10.11.x broke this feature (it was called  experimental for a reason :-))

So it may not come back.


You can try old versions if you are still on the older macOS (https://boastr.net/releases)

**Comment by mh82** [comment]
I'm using a Macbook Pro that is of late 2017 but the drag/release day still occurs.
