### ISSUE TITLE
The size of the trackpad on the 15" tbMBP causes tons of accidental 5 finger taps

### ISSUE THREAD

**Issue by lanza** [folivoraAI/BetterTouchTool#1231]
#### Description of bug/feature request/question:
The gigantic trackpad means that your palm will rest on the upper right and left corners of trackpad. This causes BTT to recognize your palm as finger taps. So you'll occasionally get erroneous 5 & 4 finger taps.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
15" tbMBP Trackpad

#### Device information:

Type of Mac: 15" tbMBP
macOS version: 10.12.*
BetterTouchTool version: 2.266

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Make sure palm / thumb handling is activated in the advanced BetterTouchTool touchpad settings. If that doesn't work for you, currently there is no way to improve the behavior. You may need to remove the 4/5 finger taps for now.

I'll continue to improve this, but BTT is already filtering many touches, in some cases it's just not feasible to differentiate between accidental and normal touches :-(
