### ISSUE TITLE
Feature Request: make snap areas retain snapped window size after dragging

### ISSUE THREAD

**Issue by queryquandary** [folivoraAI/BetterTouchTool#1235]
Sometimes I just want to resize a window to a preset size but also want to drag it around to different parts of the screen while retaining the size defined in the snap area.  Right now the snap area resizes the window but if I drag it somewhere else on the screen it reverts to its previous dimensions.  I'd like to request an option on each snap area to retain the snapped window dimensions after the window has been dragged to another part of the screen.

**Comment by tnaseem** [comment]
I was going to ask the same thing. :)

Currently, to retain the new 'snapped' window size I just quit the app and restart. But, it's not ideal, so this feature would be a nice addition, and like @queryquandary suggested, make it an option per snap area.
