### ISSUE TITLE
Touchbar Font color and Groups

### ISSUE THREAD

**Issue by martin072** [folivoraAI/BetterTouchTool#124]
Feature request

Noticed it is only possible to change the background color of a touchbar button, not the foreground color (seems to be white all the time). Would be nice to customise this.

I use BTT in the Terminal app, and it is very useful with Terminal commands. Since these commands can be different for various types of usages, it would be nice if you could create 'sub-group' with custom buttons.

Macbook pro touchbar 2016
BTT 1.963(552)

**Comment by CappyD** [comment]
I agree... sometimes the foreground color for the text and/or icon is white, sometimes black.  Having a default of white or black to ensure good contrast with the background color is a good idea (white foreground by default if the background is dark and vice versa).  But being able to select a foreground color just like for the background would be good.

**Comment by fifafu** [comment]
Currently BTT uses the system default behavior which uses a popular algorithm to decide whether the font should be white or black. I'll check if I can override that to let you customize it.
