### ISSUE TITLE
Compatibility issue with Powerpoint 2016

### ISSUE THREAD

**Issue by sachinsid** [folivoraAI/BetterTouchTool#1248]
MacBook Pro (Retina, 15-inch, Mid 2015)
Built In Force Touch Trackpad
macOS version: 10.12.5 (16F73)
BetterTouchTool version: 2.270 (658)

I have run into issues with Powerpoint 2016 on Mac when BTT is running in the background. The issue is with loosing ability to modify and edit any tables in powerpoint and is detailed in the thread below: 

https://answers.microsoft.com/en-us/msoffice/forum/msoffice_powerpoint-mso_mac/mac-powerpoint-2016-table-issues-overwrite-delete/85da9b7d-d8ec-45e7-9854-5317edd39c89

If I quit BTT, and restart Powerpoint, the issue does not occur again. Is it possible to provide some sort of fix for the situation, as BTT is crucial for my day to day tasks?

**Comment by fifafu** [comment]
Microsoft already knows about the issue and I hope they will fix it soon. For now you can disable BTT for PowerPoint (click the BetterTouchTool icon  in the menubar and select "disable for current application", it will remember that decision)

It may be enough to disable window snapping for PowerPoint.

**Comment by Mooz80** [comment]
Hi, 
By any chances, does new version of BetterSnapTool solves this issue? Still not clear if it's a Microsoft bug or 3rd party windows snapping app.

https://answers.microsoft.com/en-us/msoffice/forum/msoffice_powerpoint-mso_mac-mso_mac2016/mac-powerpoint-2016-table-issues-overwrite-delete/85da9b7d-d8ec-45e7-9854-5317edd39c89

**Comment by sachinsid** [comment]
No, in fact the problem has gotten much worse. Even disabling BTT for PowerPoint does not fix the issue for me and only completely killing it and restarting PowerPoint fixes it. 

 Pretty annoying issue for me as other than this bug, BTT works well for me.  The link to the discussion on the Microsoft site seems to indicate that they are not able to reach the developer “Microsoft can work with 3rd party developers, but as has already been pointed out, the developer of the app has been unresponsive. There's nothing Microsoft can do. They didn't make the window manager, someone else did.“ 

Can the BTT developer confirm if this is the case and if so, please see what can be done to fix the issue?

**Comment by fifafu** [comment]
Unfortunately this is a bug in Powerpoint regarding the Accessibility API. However disabling Bettersnaptool/BetterTouchTool for PowerPoint should still work, are you sure this doesn't work for you anymore?

**Comment by sachinsid** [comment]
Positive. Disabling BTT for PowerPoint still causes issues with tables in PowerPoint. I need to completely exit the app and restart PPT for the issues not to occur.

**Comment by netplus502** [comment]
Hi, I had same issue but disabling BetterTouchTool for PowerPoint works well. I just tried,

1. disabling BetterTouchTool for PowerPoint
2. Reboot MAC
3. Open power point file

That's all !

**Comment by Mooz80** [comment]
@sachinsid did you try what netplus502 suggested to see if it fixes the problem? 
I was about to purchase BTT, but the 2 comments seems to be in contradictions. 
I'm using Magnet at the moment and the same bug is still there after updating PowerPoint to the latest version today (15.40 171108). I just want to spend my money right.

**Comment by Mooz80** [comment]
Any updates on this subject? Tried the latest update of PowerPoint 2016 (15.41) and issue is still there... who's side to fix it? Thanks
