### ISSUE TITLE
Must restart bettertouchtool after wake up

### ISSUE THREAD

**Issue by toby1991** [folivoraAI/BetterTouchTool#1249]
#### Description of bug/feature request/question:

Must restart bettertouchtool after wake up

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

 Magic Mouse 2

#### Device information:

Type of Mac: **mbp**
macOS version:  **osx el capitan 10.11.6**
BetterTouchTool version: **2.270**

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by regua** [comment]
I have the same issue on MacOS 10.12.4. It has been occurring for some time now, but previously I did not need to restart after each wake up (only sometimes), and now it happens every single time.
