### ISSUE TITLE
Capslock Toggle functionality seems broken

### ISSUE THREAD

**Issue by quintrino** [folivoraAI/BetterTouchTool#1256]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

Created multiple keyboard shortcuts using Toggle Capslock. No longer functioning

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Macbook Keyboard

#### Device information:

Type of Mac: iMac 27in 2011
macOS version: El Capitan
BetterTouchTool version: 2.270

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by quintrino** [comment]
Just as an update it appears that this issue has been fixed on my Sierra MBP but is still present on my El Capitan iMac

**Comment by Yulianita75** [comment]
Please I have the same problem. I am using Mac SIerra 10.12.6, toggle caps on/off doesn't work
