### ISSUE TITLE
key sequence triggers multiple times on unrequired key UPs

### ISSUE THREAD

**Issue by gdbing** [folivoraAI/BetterTouchTool#1257]
#### Description of bug/feature request/question:

key sequences with unrequired "key UP"s trigger for every "key UP" after last required key
eg. 
![screen shot 2017-07-25 at 12 50 38 am](https://user-images.githubusercontent.com/8458547/28561448-5a113b04-70d3-11e7-9d61-cc071214a17a.png)
This is a key sequence to open a new terminal window. If I keep the modifier keys held down for a second it works as expected, but if I release the modifier keys right after completing the key sequence, it triggers 3-5 times depending on the timing of release

#### Affected input device:

Macbook Air builtin keyboard

#### Device information:

Type of Mac: Macbook Air
macOS version: High Sierra beta 17A306f
BetterTouchTool version: 2.270

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Comment by nielsr2** [comment]
I'm having the same issue.

It seems to trigger the action as many times, as there are keys in the sequence. I can avoid it by keeping the modifiers down for a bit as well.

I'm using the sequence to run an Applescript.

 **Device Information:** 
MacBook Pro (Retina, 13-inch, Mid 2014)
Affects both built-in and third-gen Apple Wireless Keyboard.
Sierra 10.12.5 (16F73)
BetterTouchTool version 2.270

**Comment by fifafu** [comment]
Weird, I can't seem to reproduce this. Could you attach an export of your gesture? (You can also just cmd+c on the key sequence and cmd+v here)

**Comment by nielsr2** [comment]
```
{
  "BTTTriggerType" : 624,
  "BTTTriggerClass" : "BTTTriggerTypeKeyboardShortcut",
  "BTTPredefinedActionType" : 49,
  "BTTPredefinedActionName" : "Open Application \/ File \/ Apple Script …",
  "BTTLaunchPath" : "file:\/\/\/Users\/n\/Google%20Drive\/SCRIPTS\/lookupword.scpt",
  "BTTEnabled" : 1,
  "BTTShortcutKeyCode" : -1,
  "BTTShortcutModifierKeys" : -1,
  "BTTOrder" : 0,
  "BTTKeySequence" : {
    "BTTPauseBefore" : 0.01279633620689655,
    "BTTPauseBetween" : 0.303155637254902,
    "BTTKeyCount" : 6,
    "BTTKeySequenceDownKeys" : [
      {
        "BTTKEYCode" : 55,
        "BTTKEYDown" : 1,
        "BTTKEYOrderRelevant" : 1,
        "BTTKEYRequired" : 1,
        "BTTKEYTime" : 5.22943e+08
      },
      {
        "BTTKEYCharacter" : "$",
        "BTTKEYCode" : 10,
        "BTTKEYDown" : 1,
        "BTTKEYOrderRelevant" : 1,
        "BTTKEYRequired" : 1,
        "BTTKEYTime" : 5.22943e+08
      },
      {
        "BTTKEYCharacter" : "1",
        "BTTKEYCode" : 18,
        "BTTKEYDown" : 1,
        "BTTKEYOrderRelevant" : 1,
        "BTTKEYRequired" : 1,
        "BTTKEYTime" : 5.22943e+08
      }
    ],
    "BTTKeySequenceMixedKeys" : [
      {
        "BTTKEYCode" : 55,
        "BTTKEYDown" : 1,
        "BTTKEYOrderRelevant" : 1,
        "BTTKEYRequired" : 1,
        "BTTKEYTime" : 5.22943e+08
      },
      {
        "BTTKEYCharacter" : "$",
        "BTTKEYCode" : 10,
        "BTTKEYDown" : 1,
        "BTTKEYOrderRelevant" : 1,
        "BTTKEYRequired" : 1,
        "BTTKEYTime" : 5.22943e+08
      },
      {
        "BTTKEYCharacter" : "1",
        "BTTKEYCode" : 18,
        "BTTKEYDown" : 1,
        "BTTKEYOrderRelevant" : 1,
        "BTTKEYRequired" : 1,
        "BTTKEYTime" : 5.22943e+08
      },
      {
        "BTTKEYCharacter" : "1",
        "BTTKEYCode" : 18,
        "BTTKEYOrderRelevant" : 1,
        "BTTKEYRequired" : 1,
        "BTTKEYTime" : 5.22943e+08
      },
      {
        "BTTKEYCharacter" : "$",
        "BTTKEYCode" : 10,
        "BTTKEYTime" : 5.22943e+08
      },
      {
        "BTTKEYCode" : 55,
        "BTTKEYTime" : 5.22943e+08
      }
    ],
    "BTTKeySequenceUpKeys" : [
      {
        "BTTKEYCharacter" : "1",
        "BTTKEYCode" : 18,
        "BTTKEYOrderRelevant" : 1,
        "BTTKEYRequired" : 1,
        "BTTKEYTime" : 5.22943e+08
      },
      {
        "BTTKEYCharacter" : "$",
        "BTTKEYCode" : 10,
        "BTTKEYTime" : 5.22943e+08
      },
      {
        "BTTKEYCode" : 55,
        "BTTKEYTime" : 5.22943e+08
      }
    ]
  }
}
```

**Comment by fifafu** [comment]
@nielsr2 sorry for the delay - I just tried your sequence, but still it seems to work fine here.
I wonder if I forgot about some setting that could cause this...

So the behavior on your machine when using this sequence is:

1. You press cmd
2. You press ^(while cmd is still pressed)
3. You press 1 (while cmd & ^are still pressed)
4. It triggers for the first time when the 1 key goes up again
5. It triggers another time when the cmd key goes up again?

Did I understand correctly? On my machine it only seems to trigger for step 4

**Comment by nielsr2** [comment]
It triggers when I lift the 1 key, as supposed to with the settings.

But if I don't hold CMD and $ just for a sec, until the dialog that my script triggers appears, it triggers it multiple times. There also seems to be a bit of randomness. 

However, I played around with some different trigger sequences. And using shift-$-1 (and 1 up) works perfectly. But CMD-fn-1 ( and 1 up ) haves the same issues. So I’ll probably just avoid CMD in the future.

I’ve replicated the issues on an late 2009 iMac with El Capitan, and it acts the same way.
