### ISSUE TITLE
Keyboard shortcuts for mouse buttons repeating multiple times

### ISSUE THREAD

**Issue by Caleb10E** [folivoraAI/BetterTouchTool#1262]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

In my use case, which is assigning "cmd+[" and "cmd+]" to my normal mouse's back and forward buttons respectively for flipping through pages in Chrome, Finder, Spotify, etc, *my actions quickly repeat three times every time I press one of the buttons on my mouse*. This happens with any keyboard shortcut I set for these mouse buttons, but not with any of the predefined actions. These functions should only be happening once.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Bluetooth Mouse (Razer Orochi 2013)

#### Device information:

Type of Mac: 2012 MacBook Air 13"
macOS version: 10.12.6
BetterTouchTool version: 2.270

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

[Screenshot 1: My actions with the mouse-up workaround applied](http://imgur.com/v15qaR7)
[Screenshot 2: Advanced gesture settings window with the workaround applied](http://imgur.com/qdTIzAJ)
[Streamable 1: How Finder reacts when I press "cmd+[" and "cmd+]" on my keyboard (how I want my BTT actions to act)](https://streamable.com/preoy)
[Streamable 2: How Finder reacts when I use my BTT actions (no workaround) on my mouse (how my BTT actions are currently acting)](https://streamable.com/wp94t)

The only way I've been able to get around it is by setting the commands to trigger on mouse-up, rather than the default and preferred trigger on mouse-down.

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Weird, could you maybe attach an export of your setup where the problem appears? (Via the "Manage Presets" button).

It should only repeat if the repeat checkbox is checked

**Comment by Caleb10E** [comment]
Here you go.

[Caleb_Setup.json.zip](https://github.com/fifafu/BetterTouchTool/files/1183774/Caleb_Setup.json.zip)
