### ISSUE TITLE
Using Sierra Split View (automating two apps)

### ISSUE THREAD

**Issue by DanielGwalter** [folivoraAI/BetterTouchTool#1266]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

Is it possible to load two applications and then place them side by side from a touch bar button?

for example, I always run Airmail and Skype in full screen side by side (split view).  I would like to launch an action from the touchbar that sets this up for me but cannot find a way of automating split view.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
macbook pro 2016 with touchbar 

#### Device information:

Type of Mac:
macOS version: 
BetterTouchTool version: 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by sc-surfer** [comment]
Great suggestion! I would use this also.

**Comment by nathggns** [comment]
+1
