### ISSUE TITLE
"Hide All Windows" Leaves Window Open

### ISSUE THREAD

**Issue by HFTobeason** [folivoraAI/BetterTouchTool#1267]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

I have Cmd-K assigned to "Hide All Windows".  Invoking the shortcut will switch me to Finder, but will most often leave one application's windows open.  I haven't been able to figure out the logic of which application's window gets left open - it may be random.

#### Device information:

Type of Mac: MacBook Pro (15-inch, Late 2016)
macOS version: 10.13 Beta (17A315i)
BetterTouchTool version: 2.270 (658)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by HermanKopinga** [comment]
+1 Have been experiencing the same behaviour on Sierra (10.12) and now High Sierrra (10.13). Current version of BTT: 2.313
Fix is usually to use the hotkey twice to hide all-all windows.

**Comment by jbyler** [comment]
I see this too.  I was going to report it as "Hide All Windows action is unreliable".  Most of the time it takes 3 or 4 invocations of the shortcut to get all the windows hidden.  I've tried to work around it making my BTT shortcut have multiple steps and invoke "Hide All Windows" more than once, maybe with a delay in between.  Also tried using an AppleScript action to hide specific applications that seem to cause problems more frequently than others ... but I couldn't find any workaround that reliably hides all windows with just one shortcut.

I'm on 10.11.6 "El Capitan" still.

**Comment by HFTobeason** [comment]
BTT still exhibits this behavior as of v2.318 (702) running under macOS 10.13.2 (17C88).

**Comment by HFTobeason** [comment]
Whoops - closed by mistake!!!
