### ISSUE TITLE
BTT Remote can't connect

### ISSUE THREAD

**Issue by felixbinder** [folivoraAI/BetterTouchTool#1271]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
I can't connect to BTT - the list in the BTT remote app remains empty. Bonjour doesn't work on either private Wifi network or tethering. I can't find a BTT remote tab to get the IP and port information to add manually.

Also, the troubleshooting page throws a 404 error
#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
BTT Remote 2.2.2

#### Device information:

Type of Mac: 11,3
macOS version: 10.12.5 (16F73)
BetterTouchTool version: 2.2750 (658)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Do you have a firewall installed on your Mac?

To see the IP open the BetterTouchTool preferences, then click on BTT Remote. The ip and port is shown below the table.

**Comment by felixbinder** [comment]
The tab was disabled. I found it now, you can close this issue.

Thanks for the swift response, and sorry for not getting it!
