### ISSUE TITLE
[Feature Request] Richer Touch Bar button script output

### ISSUE THREAD

**Issue by ellerychan** [folivoraAI/BetterTouchTool#1273]
#### Description of bug/feature request/question:

It would be very useful to have a slightly richer interface for the Touch Bar.  I love the simplicity of the current interface (output text from script shows up as a Touch Bar button).  I would not want what I am about to suggest to replace that, but to be an additional option.

At a minimum, it would be very useful to be able to attach some arbitrary user data to the Touch Bar button that is created, and have that user data either *be* a command that is executed when the button is activated, or be *passed to* another script when the button is activated.

Other things that would be useful to control from the button creation script:
* button color
* text color
* text font
* button icon
* button position
* button width
* animation

Maybe one script could even produce *multiple* button specifications.

Perhaps the button specification could be output by the script as JSON text.

##### Where this would be useful

I recently made a little script to fetch article headlines from an RSS feed, and to display one at random, in the Touch Bar every couple of minutes.  Touching the button brings up the article in a browser.  It would be useful to attach the URL to the button so I did not have to store it externally.  It would also be nice to be able to color-code the headlines by type, and attach the icon of the news source.

##### Examples

<img width="1085" alt="touch bar shot 2017-07-31 at 10 42 50 pm" src="https://user-images.githubusercontent.com/6425759/28807129-e4899cae-7641-11e7-995f-2c3222f87f31.png">
<img width="1085" alt="touch bar shot 2017-07-31 at 10 35 47 pm" src="https://user-images.githubusercontent.com/6425759/28807164-16a6e17e-7642-11e7-9f3a-2fda13a99a77.png">

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Touch Bar

#### Device information:

Type of Mac:  15" MacBook Pro with Touch Bar
macOS version:  Sierra
BetterTouchTool version: 2.270 (658)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

n/a

**Comment by OrbitalTech** [comment]
Unrelated to your issue, if I could get that script off you, that would be amazing. @ellerychan

**Comment by ellerychan** [comment]
Sure!  I just put it up on GitHub:  https://github.com/ellerychan/bttouchbarss.git

I haven’t worked on it since I posted the Feature Request, but let me know if you add anything that would make this easier to implement.

**Comment by OrbitalTech** [comment]
I'll probably introduce some kind of scrolling text, although it looks glitchy due to the touchbar not using a monospaced font. Do you mind if I add it to my repository of BTT scripts I'm trying to grow?

**Comment by ellerychan** [comment]
Tried to contact you by email to discuss further.

**Comment by OrbitalTech** [comment]
@ellerychan Didn't receive anything. Email me at russellbloxwich@gmail.com.
