### ISSUE TITLE
[Q] What determines Touch Bar button max text length?

### ISSUE THREAD

**Issue by ellerychan** [folivoraAI/BetterTouchTool#1274]
#### Description of bug/feature request/question:

I'm curious what controls the length of the text allowed in a Touch Bar button before it gets truncated.  Sometimes the button can be quite long before the text gets truncated with an ellipsis.  Other text gets truncated to a much shorter length.  I haven't detected a pattern.

I have also seen, on a small number of occasions, two lines of text in the button, but do not know how to make that happen, either.

I realize the Touch Bar feature is still under development.  Partly I'm just curious as to why, but also it would be nice to have more control over formatting (see my other Issue #1273).

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Touch Bar

#### Device information:

Type of Mac: 15" MacBook Pro with Touch Bar
macOS version: Sierra
BetterTouchTool version: 2.270 (658)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

<img width="1085" alt="touch bar shot 2017-07-31 at 10 35 47 pm" src="https://user-images.githubusercontent.com/6425759/28807490-cae2bce8-7643-11e7-8dae-ed01beda597e.png">
<img width="1085" alt="touch bar shot 2017-07-31 at 10 42 50 pm" src="https://user-images.githubusercontent.com/6425759/28807494-cdcf984a-7643-11e7-81d6-5fe2a482b118.png">

**Comment by mmBs** [comment]
@fifafu Can you please follow with this question up? I'm also really curious about it, as I use Spotify script in my Touchbar global settings and I would like to set the fixed width of the script widget. Sometimes a title of a song is so long, that it covers more then half of the touchbar and moves all other icons defined for an application scope to the right.

**Comment by ellerychan** [comment]
I have come to suspect that the truncation of my text is occurring outside of BTT.  However, as @mmBs says, some width control would still be convenient.

**Comment by Dave-c-Ross** [comment]
Did the feature of fixed-width is part of the current GA version ?
