### ISSUE TITLE
Example BTT Configuration Repository

### ISSUE THREAD

**Issue by rscosworth** [folivoraAI/BetterTouchTool#1276]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

It would be great to have a repository where folks can upload their BTT touchbar examples along with a touchbar screenshot of their bar, I think this tool is very powerful but very few probably have the imagination or knowhow to full make use of it's power. People could then look and lift what they deem applicable to them and incorporate into their own config. Thoughts?

**Comment by universvm** [comment]
It is a great idea!

I think people could just upload their configuration somewhere. Then a program could run through all the configuration and display common configurations for a specific short cut eg. 'Three finger tap -> 27% of users use it to "Search Text on Google"'.

I don't think it should be hard but could help people become more productive.
