### ISSUE TITLE
Assigned action overrides another shortcut

### ISSUE THREAD

**Issue by modytiger123** [folivoraAI/BetterTouchTool#1278]
The issue I'm facing is described in the screenshot below; I have created a shortcut which does an assigned action, somehow, the assigned action overrides another shortcut with the same combination of keys.

This issue is a big problem when coding/typing emails/surfing internet.

#### Device information:

Type of Mac: MacBook Pro 14,2
macOS version: 10.12.6
BetterTouchTool version: 2.270

![bttissue](https://user-images.githubusercontent.com/16306760/28853372-6e499892-7730-11e7-8d20-c95102be6837.png)

**Comment by fifafu** [comment]
This is currently the intended behavior, I'll check if I can add an option to disable this (there are use cases for both behaviors)
