### ISSUE TITLE
App (Cubase) issues with shift + scroll / delayed mouse clicks

### ISSUE THREAD

**Issue by stevefoxon** [folivoraAI/BetterTouchTool#1284]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug:

There are 2 issues here in one. Firstly I have an app called Cubase where Shift + Scroll should scroll the timeline horizontally, but when BTT is enabled shift + scroll does nothing. Disable BTT completely and it works as it should. So, I set it so that BTT is disabled just for Cubase (as I have nothing specific set for it anyway), but then that give me another even worse problem. When switching to other apps (e.g Finder, Mail etc) most of the time, the fist click of the mouse is not recognised, and then when I click again, the previous click happens. So for example, I click on an email and nothing happens, so I then click on a different email, and the previous one is selected, and then the 2nd one if I click on a 3rd mail, and so on. This has not been an issue until now as I had a mouse with a tilt wheel for horizontal scrolling, but my new mouse doesn't't have that. 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

A standard trackball mouse.

#### Device information:

Type of Mac: Mac Pro 7,1
macOS version: 10.12.6
BetterTouchTool version: 2.270

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

The only way around this is to disable BTT completely (i.e. for all apps) when using this app. 

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Could you attach an export of your BetterTouchTool settings? (Do you have any action set up for scrolling?)

You can export the settings json via the "Manage Presets" button.

**Comment by stevefoxon** [comment]
Here you go. I have also discovered over the last couple of days that the behaviour is the same in all apps, not just Cubase. I only have keyboard shortcuts / settings, I don't have anything for the mouse.
[Default.json.zip](https://github.com/fifafu/BetterTouchTool/files/1226573/Default.json.zip)

**Comment by stevefoxon** [comment]
Hi. An update for you and an apology. I also use Steermouse (as there are some things A better touch tool can't do) and they must be interfering with each other. I installed Steermouse, and everything functioned as it should with BTT and the shift + scroll. It's odd that disabling BTT stops the problem even with Steermouse enabled though.

**Comment by fifafu** [comment]
Thank you, that's very interesting! I'll look into this.
