### ISSUE TITLE
BTT Takes Long to Run in System Start-up

### ISSUE THREAD

**Issue by semihyagli** [folivoraAI/BetterTouchTool#1288]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

BTT takes about 4 secs before running initially.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Macbook Tracpad

#### Device information:

Type of Mac: 15" MacBook, Late 2016
macOS version: 10.12.6
BetterTouchTool version: 2.270 (658)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

This has been going on for a while, I send a prior post, I thought it was my error, but the delay issue has been going on for a while. I should say since the update with the clipboard, I started having issues. 

Thanks for support

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Do you have external hard drives connected to your mac?

**Comment by semihyagli** [comment]
Yes, indeed. However, I dont always connect it. But the issue seems to be independent of whether I connect the external drive or not.
