### ISSUE TITLE
Request: Caffeinated function to prevent sleep 

### ISSUE THREAD

**Issue by fabi94music** [folivoraAI/BetterTouchTool#1289]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
A function to prevent sleep would be very great. There are awesome apps on MAS like Lungo, Amphetamine etc. or on Github (KeepingYouAwake). Would be great to have the ability to handle that in BTT and BTT Remote

#### Device information:

Type of Mac:
macOS version: 
BetterTouchTool version: 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
You could use the "Execute terminal command" action and use it to triggers this command:
```/usr/bin/caffeinate```

However to stop it again you'd need another command triggering this: ```killall caffeinate```

I think it should be easy to integrate in BTT though,  so I'll look into it!
