### ISSUE TITLE
Request: suppress hand edge touching touchpad of actual macbook pro when hand rests on lower edge of laptop 

### ISSUE THREAD

**Issue by FrankOnGit** [folivoraAI/BetterTouchTool#1290]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
The touchpad of the actual MacbookPro is so big and placed so close to the lower edge to the unibody so that the hand easily touches one of the lower corners of the touchpad so it is recognized as a second fingertip.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Trackpad

#### Device information:

Type of Mac: MacBook Pro (15-inch, 2016)
macOS version: 10.12.4 (16E195)
BetterTouchTool version: 2.270

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

![handtouchingtrackpadcorner](https://user-images.githubusercontent.com/27725043/28986372-f729b5c4-7966-11e7-8ef1-3c6e64bd2cec.jpg)

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
The upcoming version should improve this, you can already try it by downloading this build: https://bettertouchtool.net/releases/btt2.271.zip

**Comment by FrankOnGit** [comment]
Hi Andreas

Wow, this was pretty fast reaction! Thank you for the new revision, I will report if anything behaves not as expected.
Thanks a lot for this great tool!

Sincerely
Frank.

**Comment by fifafu** [comment]
Ahh sorry, I think I uploaded the wrong build. I won't be able to upload the correct one until tomorrow!

**Comment by fifafu** [comment]
But nevertheless the 2.271 build should also bring some improvements already.
