### ISSUE TITLE
Macbook trackpad taps not registering

### ISSUE THREAD

**Issue by digitalself** [folivoraAI/BetterTouchTool#1303]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
When BTT is enabled, at least 50% of trackpad taps do not register, requiring multiple taps to register a click. Doesn't appear to affect actual clicks (similarly, magic mouse is not affected)

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Macbook trackpad

#### Device information:

Type of Mac: Macbook Pro Retina Late 2013 13inch
macOS version: 10.12.6
BetterTouchTool version: 2.273 (662)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by tonynguyen1901** [comment]
Im having a similar situation as well but mine is 3 fingers drag, it feels like the trackpad is not responsive sometimes

**Comment by wagnerone** [comment]
I have this issue too. Almost every initial "tap" of the track pad to click something doesn't register, but the followup tap does register. I'm using 2.405 (756) on 10.13.3.
