### ISSUE TITLE
SVG Preview for Clipboard manager

### ISSUE THREAD

**Issue by DCNielsen** [folivoraAI/BetterTouchTool#1312]
#### Description of bug/feature request/question:
I would love to be able to preview copied SVG visuals in the Clipboard manager. That would be outstandingly helpful. Working in Illustrator, those Clipboard copied items are represented as code that I can't read when I browse back through and I have to guess which one I'm looking for.

**Comment by fifafu** [comment]
Good idea, I'll add this.
