### ISSUE TITLE
Can not connect BTT Remote to Mac

### ISSUE THREAD

**Issue by caleb-ravel** [folivoraAI/BetterTouchTool#1313]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

I can see my MBP but cannot connect. 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
iPhone 6 Plus

#### Device information:

Type of Mac: 2017 MBP 15in i7
macOS version: 10.12.6
BetterTouchTool version: 2.270

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

[log-C73327.txt](https://github.com/fifafu/BetterTouchTool/files/1219979/log-C73327.txt)

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Do you have a firewall enabled on your Mac?
