### ISSUE TITLE
Retain cursor position

### ISSUE THREAD

**Issue by rebdeg** [folivoraAI/BetterTouchTool#1315]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

When I drag a window to the top, it will be resized for the top half of the screen, as expected. When I then position my cursor on the right side top of that windows and drag it away from the top, it will resize to its original size, however I then find my cursor way outside of that window, positioned somewhere on the desktop. 

If possible the cursor should retain its relative position on the window when it is resized to its original size.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

n/a

#### Device information:

Type of Mac: iMac 27 5k
macOS version: 10.12.6
BetterTouchTool version: 2.281

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Unfortunately that's a bug Apple has introduced in 10.12 and still not fixed in  10.13 :-(
I haven't found a way to prevent this behavior...
