### ISSUE TITLE
BetterTouchTool susceptible to dylib hijacking

### ISSUE THREAD

**Issue by rosch100** [folivoraAI/BetterTouchTool#1322]
#### Description of bug/feature request/question:
Scanning BTT with Objective-See's Dylib Hijack Scanner reveals a security vulnerability of BTT:
<img width="1248" alt="bildschirmfoto 2017-08-16 um 12 37 08" src="https://user-images.githubusercontent.com/5745224/29359804-6b9ab76a-8280-11e7-89a7-c5af2a93cb46.png">

Please check yourself at: https://objective-see.com/products/dhs.html

BTT Version 2.281

**Comment by fifafu** [comment]
Hey,

Unfortunately the Wacom driver framework doesn't exist on all systems, thus it needs to be linked dynamically.
I'm not sure if there is a way to prevent this. Do you know of any?

However if I'm not mistaken an attacker would need admin privileges on your machine to place a file in that folder, thus this shouldn't be a real issue (if he already has admin privileges he doesn't need a dylib to hijack)

Best 
Andreas

**Comment by rosch100** [comment]
Unfortunately, I don't know of any other way of linking the framework. 

I'm not a MacOS software developer, so without much research, I cannot judge the severity of the vulnerabilty. I suggest you check Patrick Wardles elaborate research about this type of vulnerability and how to prevent it: https://s3.amazonaws.com/s3.synack.com/canSecW.pdf

Thanks!
