### ISSUE TITLE
Feature request: Save window state (open window on same position)

### ISSUE THREAD

**Issue by fabi94music** [folivoraAI/BetterTouchTool#1323]
#### feature request/question:

Save the window position of e.g. Preview window or chat windows (e.g. center) and reopen the app with the same position.

#### Device information:

Type of Mac:
macOS version: 
BetterTouchTool version: 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by mattorp** [comment]
The app Stay may do what you are looking for.

**Comment by rodalpho** [comment]
There are several non-BTT apps that do this. I use Moom myself.

I would like BTT to implement this functionality so I can reduce the number of tweak apps running. BTT already replaces like 5 other tweak apps, this would make it 6.

One critical component of this request (for me, anyway) is the ability to trigger sets of saved window states based on events. For example, I want my windows arranged like X when my mac only has one monitor, and arranged like Y when it has 3 monitors (ie, plugged-in at work).

**Comment by sammcj** [comment]
I too would love this as a BTT feature, I use BTT for all my window snapping and hotkeys so I don't really want to install other apps that also do window management.
