### ISSUE TITLE
Restarting BBT resets cursor size

### ISSUE THREAD

**Issue by sunnymiu** [folivoraAI/BetterTouchTool#1333]
#### Description of bug/feature request/question:

Restarting BBT will reset mouse cursor size settings in Accessibility. Once restarted the cursor size will change back to normal i.e. the default size. Have to revert by manually going to Accessibility settings and reapplying the size. 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Software-wise problem so it does not affected by any input device. 

#### Device information:

Type of Mac: MacBook Pro (Retina, 15-inch, Early 2013)
macOS version: 10.12.6 (16G29)
BetterTouchTool version: 2.291 (669)

**Comment by fifafu** [comment]
I think this will only happen if you change the cursor size while BTT is active. If you quit BTT, then change it in the Accessibility options and then start BTT, it should work.

Still a bug but that should be a workaround for now :-)
