### ISSUE TITLE
Whole Palm gesture does not work after update to 2.292 version

### ISSUE THREAD

**Issue by zingfrid** [folivoraAI/BetterTouchTool#1344]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
I use whole palm gesture very often. It does not worked well before, but after one of latest updates, where "improvement of palm gestures" were introduced, it stopped worked at all. I've tried different positions of palm (before it helped) but no luck.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Magic Trackpad (1st gen) and MacBoook Pro 2015 trackpad. 

#### Device information:

Type of Mac: MacBook Pro 2015
macOS version: 10.12.6
BetterTouchTool version: 2.292

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by zingfrid** [comment]
Looks like related to #1346

**Comment by fifafu** [comment]
Ah I totally forgot about that (very old) gesture :-) 
Currently you'll need to disable thumb/palm handling in the advanced preferences if you want to use this. I'll check if I can add some workaround to make it work while keeping that option enabled.

**Comment by zingfrid** [comment]
Yes, it helps. Thanks. Can be closed now.
