### ISSUE TITLE
Five-finger-click ist not working reliably anymore on external ForceTouch Trackpad. :/

### ISSUE THREAD

**Issue by dionysos283** [folivoraAI/BetterTouchTool#1346]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

I use an external Magic Trackpad with ForceTouch on my MacBook Pro, which I connect to an external monitor and close it. After charging the Trackpad (connecting it with my MacBook vie USB), Five-Finger-Clicks stopped working reliably. Sometimes it works, sometimes not. I tried restarting BTT, restarting my Mac, off/on the Trackpad - all multiple times, nothing works. It feels like the Trackpad doesn't click (like it's off - no haptic feedback), but only with Five-Finger-Clicks. When I quit BTT I can do Five-Finger-Clicks without problems (of course without features of BTT). So I think the problem is with BTT.
Hope you can help me. Thanks! :)

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Magic Trackpad with ForceTouch

#### Device information:

Type of Mac: MacBook Pro 13" Late 201
macOS version: Sierra
BetterTouchTool version: 2.292

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Could you check if it works better if you have all fingers in the "center area" of the trackpad?

**Comment by dionysos283** [comment]
I just checked and there is no noticeable difference if I try in the center. In the center the Trackpad also sometimes doesn't click (no haptic feedback). Hope that helps.
