### ISSUE TITLE
4 finger click/tab only works on lower half on the trackpad

### ISSUE THREAD

**Issue by krabar** [folivoraAI/BetterTouchTool#1347]
#### Description of bug/feature request/question:

Since the last update 4 finger gestures only work on the lower half on the trackpad.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Macbook Trackpad

#### Device information:

Type of Mac: MacBook Pro (13-inch, Mid 2010)
macOS version: 10.12.5 (16F73)
BetterTouchTool version: 2.292 (671)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

It goes away when "Thumb / Palm handling" is disabled in advanced settings.
It doesn't help to tick "Exclude custom 4 finger sequences from thumb / palm filtering".

**Comment by AriBerlin** [comment]
Thanks, unchecking the "Thumb/Palm handling" option helped me out, too.
