### ISSUE TITLE
"Hold" and "Double Tap" Support for Touch Bar

### ISSUE THREAD

**Issue by 0xenwumme** [folivoraAI/BetterTouchTool#1348]
Hope I'm in the right spot for feature suggestions.

It would be nice if BTT Touch Bar widgets/buttons/etc. could be configured to only trigger their functions on Double Tap or Hold. I often hit the buttons by accident.

**Comment by AndrewC7** [comment]
I would love to see this too. Single tap does one action, double tap does another. Currently trying to attach multiple actions to one widget but having no luck...maybe this could be the answer?

**Comment by jtmorgan** [comment]
I would also like to see this. I grew dependent on "double tap to select and hold this [desktop icon/Firefox tab" when I was using JiTouch. I like BTTs power and flexibility more overall, but this type of functionality is missing.

**Comment by dumptruckman** [comment]
Was this added? I too would love to see this feature. I can't seem to find such an option so I'm assuming it's not in yet.
