### ISSUE TITLE
Trackpad Invert Requires BTT Restart When Waking Computer

### ISSUE THREAD

**Issue by jeffbernst** [folivoraAI/BetterTouchTool#1349]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

The feature in BTT to invert behavior of my magic trackpad works great, but the functionality doesn't work after my computer sleeps -- requires a restart of BTT to continue working.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Magic Trackpad 1 on Macbook Air (11 inch mid 2013)

#### Device information:

Type of Mac: Macbook Air (11 inch mid 2013)
macOS version: 10.12.6
BetterTouchTool version: 2.292

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by milch** [comment]
I have the same issue, although it doesn't even just seem to be limited to waking up from sleeping. Sometimes it seemingly randomly stops working, and I have to restart BTT for it to start working again

**Comment by milch** [comment]
@jeffbernst I found a workaround: 

- Open the BTT preferences
- Click on "Other"
- Click on "+ Configure New Trigger"
- Select "After Mac Wakes From Sleep"
- Select "Restart Better Touch Tool" from Predefined Actions

![screen shot 2017-09-22 at 11 01 58](https://user-images.githubusercontent.com/279407/30737059-7eb6c7b8-9f85-11e7-8048-71cefeffe64a.png)

So far it seems like this is working.

**Comment by jeffbernst** [comment]
@milch Cool thanks!

**Comment by fifafu** [comment]
That's quite weird because BTT should automatically restart itself after sleep.
Could you please check whether activits monitor shows the BTT helper tool called "BTTRelaunch" ?

**Comment by milch** [comment]
@fifafu I just double checked, I do in fact have the BTTRelaunch helper running. 

Note that since I've set it up my workaround it hasn't always worked, but it does make it work like 75% of the time
