### ISSUE TITLE
3 finger click not working as expected

### ISSUE THREAD

**Issue by sirbuckets** [folivoraAI/BetterTouchTool#1356]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

**#### Description of bug/feature request/question:**

I use 3 fingers to click the trackpad to simulate a middle click (mainly to open new tabs in firefox) and more often than not it does not register as a middle click.

**#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):**

MacBook Trackpad

**#### Device information:**

Type of Mac: MacBook Pro (13-inch, Mid 2012)
macOS version: Sierra 10.12.6
BetterTouchTool version: 2.292

**#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):**

Also, I have 3 finger swipe up (open new tab) and swipe down (close current tab) gestures that don't always work correctly. Sometimes it'll just scroll, and then when the swipe down to close does work, it'll start scrolling the previous tab. Is there a way to downgrade? Everything used to work perfectly

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Does disabling thumb/palm handling help in your case?

![image](https://user-images.githubusercontent.com/8820811/29637422-5bc80df4-8854-11e7-8c08-cada9a32527b.png)

**Comment by sirbuckets** [comment]
Yes, my 3 finger clicks are now working as they used to. The only thing that's left is when I use the 3 finger swipe down (close tab in FF, cmd W), sometimes it scrolls the previous tab when it gets to it after closing. Doesn't always do it, just sometimes and I'm not sure what's causing it.
