### ISSUE TITLE
action triggering at random after update (2.293)

### ISSUE THREAD

**Issue by mhristof** [folivoraAI/BetterTouchTool#1373]
---

#### Description of bug/feature request/question:
im getting random triggers after the last update

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
trackpad

#### Device information:

Type of Mac: System Version: macOS 10.12.6 (16G29)
      Kernel Version: Darwin 16.7.0
BetterTouchTool version: 2.293

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
![image](https://user-images.githubusercontent.com/24205462/29669895-da6ece58-88dc-11e7-8abc-828cfd6b6626.png)

this is the action thats triggering at random.

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
How random?
BTT will only trigger that gesture if it had recognized 4 fingers on your trackpad for a short amount of time (5 also work if one of them is your thumb).

Could you check via Live View what BTT sees?

**Comment by mhristof** [comment]
I'd say it happened around 10-20 times in a period of 8 hours. Ill try and keep any eye out on live view but its going to be tricky as it happens during work time. Is there a log i could check/send ?
