### ISSUE TITLE
Siri remote registering wrong action

### ISSUE THREAD

**Issue by xiaoken** [folivoraAI/BetterTouchTool#1379]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

Clicking the trackpad of Siri remote always results in "left click" registered.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Siri remote trackpad.

#### Device information:

Type of Mac: 2013 late retina 13 inch
macOS version: 10.11.6
BetterTouchTool version: 2.293

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

This began to act like this starting from around 2 weeks ago.
workaround is to restart bettertouchtool.

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Mhh maybe you accidentally activated the mouse mode for the siri remote? Does the mouse move when sliding over the remote touchpad?
Could you post your configuration here?

**Comment by xiaoken** [comment]
Nope i didn't activate mouse mode, i have been using this remote for at least 5 months from now, it began acting like this in august.
Would this be enough? thanks :)
![image](https://user-images.githubusercontent.com/5938911/29739323-98a0f33c-8a00-11e7-911b-12504e52acba.png)

**Comment by fifafu** [comment]
Do you maybe have arrow down mapped to leftclick in the keyboard tab?

If possible try to reproduce the issue, then go to the about tab in BetterTouchTool and click the "export debug information" button. This will create a folder called BetterTouchToolDebug on your desktop. That could be very helpful to figure out what's wrong (boastr.net@gmail.com)

**Comment by xiaoken** [comment]
Nope, i didn't make any changes rather than regularly updating BTT.
The log was sent to your email, thanks :)
