### ISSUE TITLE
[Bug] Gestures don't work unless I reopen BTT app

### ISSUE THREAD

**Issue by haniag** [folivoraAI/BetterTouchTool#1383]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
1) This has happened in previous versions, but is currently un-tolerable in latest update. BTT doesn't activate gestures until its opened and closed again. After a while, the same happens where gestures no longer work, and I need to open BTT and close it to make it work.

2) This latest update forces Finder gestures macOS wide. In the past, whatever gestures I setup for Finder only worked in Finder. Now, they are working everywhere. For example, I had set the CMD+X to be CMD+C in Finder. Now, CMD+X in other applications only works as copy, and not cut, which means that BTT is forcing this gesture system-wide!!

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Keyboard

#### Device information:

Type of Mac: Late 2013
macOS version: 10.12.6
BetterTouchTool version: 2.292

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

I am seriously thinking of no longer updating BTT. The app has ballooned so much that quality is an issue. 

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
You can always downgrade to previous versions (https://boastr.net/releases), however I haven't had similar reports for the current versions thus I assume something might be broken/corrupted  in your preset. (Severe bugs like this usually already get reported during the alpha phase)

Could you please go to the about tab in BetterTouchTool, then click the export debug info button? This will create a folder called BetterTouchToolDebug on your desktop, it would be great if you could send that to boastr.net@gmail.com and reference this issue.

**Comment by haniag** [comment]
File sent. 

So, should I completely remove BTT and start new? How can I completely remove the presets?

Also, please don't forget about second issue.

Thanks.
