### ISSUE TITLE
Volume Up/Down trigger no longer works with Apple Remote

### ISSUE THREAD

**Issue by pintapass** [folivoraAI/BetterTouchTool#1385]
#### Description of bug/feature request/question:

Volume Up/Down trigger no longer works with Apple Remote

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Apple Remote (anodized aluminum)

#### Device information:

Type of Mac: iMac 27" (2011)
macOS version: High Sierra (10.3) Public Beta 6
BetterTouchTool version: 2.293

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

This has been a persistent issue throughout multiple versions of BTT and High Sierra Public Beta.

**Comment by fifafu** [comment]
Unfortunately I don't have any working Mac with the IR receiver anymore :-(
However the code for this hasn't changed. If it doesn't work anymore it's probably an issue with High Sierra, but I'm not sure whether I'll ever be able to fix it.

**Comment by fifafu** [comment]
I got one of these Apple Remote adapters for my new Mac, but it seems to work correctly here.
Do you still experience this?

Closing here, but will reopen if necessary.
