### ISSUE TITLE
1 Finger Tap Right Side Midle for Left Mouseclick not working anymore

### ISSUE THREAD

**Issue by ich12** [folivoraAI/BetterTouchTool#1392]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

See Title

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
MagicTrackpad

#### Device information:

Type of Mac: Macbook pro
macOS version: 10.12.6
BetterTouchTool version: 2.295 (674)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
This seems to work fine here, do other actions work if you assign them to the gesture?

**Comment by ich12** [comment]
When i assign open Launchpad to the same gesture it needs a double Tab on the Trackpad to launch the action. But double Tab is not working for the action right click...Both actions need only one Tab with the gesture Bottom Tap Right. Strange...
