### ISSUE TITLE
Toggle Night Shift shortcut doesn't take selected color temperature from settings

### ISSUE THREAD

**Issue by b16tran** [folivoraAI/BetterTouchTool#1414]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Toggle night shift shortcut seems to work but is taking the default color temperature. I have it set in the display settings to more warm but it doesn't seem to inherit that setting.

#### Device information:

Type of Mac:
macOS version: 
BetterTouchTool version: 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by b16tran** [comment]
Also randomly disables itself at times

**Comment by fifafu** [comment]
Unfortunately BTT doesn't know about the system settings as there is no public API for that as far as I know. I'll check if I can somehow get that information, but currently I don't know whether this will be possible.
