### ISSUE TITLE
BTT and system don't see most of additional keys on my Logitech g300s.

### ISSUE THREAD

**Issue by Oschly** [folivoraAI/BetterTouchTool#1416]
Hi! I tried many programs to make visible most of my additional keys on my Logitech G300s, but nothing works. Just when I am pressing them, BTT doesn't react, system too. Logitech Gaming Software doesn't help and it's making worse mouse usability, because this drivers with LGS cursor when is near something "clickable" (like close button) it's very slow down and when it is on button it doesn't react on mouse's moves. I don't know what to do.

(https://user-images.githubusercontent.com/20259008/29925198-d55cc9d2-8e5f-11e7-85fc-5b1d5bf04c87.png)
On this photo I selected by red dots what buttons don't work and I indicated by arrow a button what I want to disable his function (it's changes mouse's dpi and profile).

My OS version: macOS Sierra 10.12.6
My Mac: iMac 21.5" Late 2013
BetterTouchTool version is the newest.
I tried rebooting :D

**Comment by fifafu** [comment]
This issue was moved to https://community.folivora.ai/t/btt-and-system-dont-see-most-of-additional-keys-on-my-logitech-g300s/60

**Comment by fifafu** [comment]
Sorry, please ignore the previous message. The migration didn't work correctly, for now the issues will stay here.
