### ISSUE TITLE
3 finger gestures have suddenly been desensitized 

### ISSUE THREAD

**Issue by jebediah2** [folivoraAI/BetterTouchTool#1417]
#### Description of bug/feature request/question:
As of late (1 week or so) my 3 finger swipes and clicks have been a pain to perform, requiring several attempts every time. Swipes are somewhat better performing since I increased sensitivity in the advanced config, but it still isn't like it used to, and clicks aren't configurable that way so these remain very annoying.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Trackpad on Macbook Air recent gen

#### Device information:
Type of Mac: Macbook Air
macOS version: 10.12.6
BetterTouchTool version: 2.296 and the one before

**Comment by fifafu** [comment]
Maybe try turning off Thumb Handling in the Advanced Trackpad preferences. Does this help?
![image](https://user-images.githubusercontent.com/8820811/30248125-5102c8ba-9622-11e7-973c-37e3e72e3598.png)

**Comment by havumigi** [comment]
Hello,

I think I have the same problem, starting around the same time as jebediah2, and I think straight after the 2.297 update was installed. Three finger swipes and five finger tap were only recognised some of the time.

From looking at the live view, I think I've understood the problem: touches on the top 2cm or so of the trackpad are not recognised by BTT. If I use the bottom ca. 80% of the trackpad, everything works as expected; if any finger is on the top section, the event is not recognised.

This is all visible in BTT's live view - sliding a finger down from the top of the trackpad starts to move the cursor straight away, but the touch doesn't show up in the live view until around 2cm down. 

Cursor movement, two-finger scrolling and four-finger space switching (controlled by the OS) work fine anywhere on the trackpad.

Macbook pro mid 2012, non-retina
