### ISSUE TITLE
Global Multitouch Gestures on Touchbar

### ISSUE THREAD

**Issue by leleSahil** [folivoraAI/BetterTouchTool#142]
## Global Multitouch Gestures on Touchbar

It would be extremely useful if we could take advantage of the touchbar's multitouch abilities just like the trackpad. I imagine options where sliding with two fingers anywhere on the touchbar will automatically slide the volume up and down or sliding with three fingers automatically adjust the brightness. 

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

Touchbar

**Comment by pallavmac** [comment]
Wow. This would be an amazing feature!

**Comment by pallavmac** [comment]
Another way the multitouch could be used is for example you could have cmd/control/shift buttons on the touchbar which could be held before pressing another button so that the button does something different.

**Comment by fifafu** [comment]
I could add multitouch gestures, however currently I can only get touch events if the BTT Touch Bar is being shown. I'll dig deeper into this soon.

**Comment by leleSahil** [comment]
If we could get it at first so that it works when the BTT Touch Bar is open that would be awesome! As of now since chrome and my other main used applications don't have touchbar support, I pretty much always have the BTT touch bar open

**Comment by leleSahil** [comment]
Any update on this feature?

**Comment by fifafu** [comment]
Two, Three and Four Finger swipes have now been added in alpha v2.468 and can e.g. be used to adjust volume or brightness:

![image](https://user-images.githubusercontent.com/8820811/39425163-75c22ff6-4c7a-11e8-98fb-a15fb3accf27.png)
