### ISSUE TITLE
[Feature Request] Ear protection for Touch Bar volume slider

### ISSUE THREAD

**Issue by schart** [folivoraAI/BetterTouchTool#1423]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
I'm guessing I'm not the first one to accidentally tap the far end of the volume slider only to have my ears blasted by whatever I'm listening to. A great solution would be so that you have to slide the far end, so if you tap on it past a certain point to the right, it will only go up to say 70% and you have to slide the rest up.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Touch Bar

#### Device information:

Type of Mac: Macbook Pro 15" 2016
macOS version: 10.12.6
BetterTouchTool version: 2.296

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by schart** [comment]
My poor ears are still affected by this, hopefully something will be integrated soon.

**Comment by fifafu** [comment]
right now the easiest solution would be to use the two finger swipe gesture instead, it is always relative to how far you have swiped on the BetterTouchTool Touch Bar. 
![image](https://user-images.githubusercontent.com/8820811/40630388-a1e18406-62d2-11e8-82c7-05ccd4345236.png)
