### ISSUE TITLE
Feature Request: Connect BT Device Action (AirPods)

### ISSUE THREAD

**Issue by KimchaC** [folivoraAI/BetterTouchTool#1429]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
I would like to have the ability to initiate a connection to a bluetooth device (particularly AirPods) similar to how Tooth Fairy works, but directly from BTT.

I would like to use it with the TouchBar and envision it like this:
- Show unconnected AirPods symbol when not connected
- On click show spinning wheel while connecting
- Once connected and while connected show connected symbol

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Any, but particularly Touch Bar

#### Device information:

Type of Mac: 2017 MBP with TB
macOS version: 
BetterTouchTool version: 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by sidewinder12s** [comment]
Could add this as a built in, there are a few examples of applescripts for this. Not sure if there are any ways to do it other than through the UI

```
activate application "SystemUIServer"
tell application "System Events"
	tell process "SystemUIServer"
		-- Working CONNECT Script.  Goes through the following:
		-- Clicks on Bluetooth Menu (OSX Top Menu Bar)
		--    => Clicks on SX-991 Item
		--      => Clicks on Connect Item
		set btMenu to (menu bar item 1 of menu bar 1 whose description contains "bluetooth")
		tell btMenu
			click
			tell (menu item "NAME’s AirPods" of menu 1)
				click
				if exists menu item "Connect" of menu 1 then
					click menu item "Connect" of menu 1
					return "Connecting..."
				else
					-- click btMenu -- Close main BT drop down if Connect wasn't present
					-- return "Connect menu was not found, are you already connected?"
					click menu item "Disconnect" of menu 1
					return "Disconnecting..."
				end if
			end tell
		end tell
	end tell
end tell
```

Note that the `NAME’s AirPods` has a special apostrophe that Apple uses. Seems that if you use the MacBook Keyboard's apostrophe this will fail. Replace the name with your name (or really any BT device) and it'll connect pretty seamlessly.

**Comment by KimchaC** [comment]
Thanks! Currently I am using the app Tooth Ferry, which allows you to bind connecting to airpods to a keyboard shortcut and I make my touchbar button just do that .

But that and your solution doesn't allow you to display an icon that's connected or disconnected :)
