### ISSUE TITLE
Shortcut to expanded control strip

### ISSUE THREAD

**Issue by mjstew33** [folivoraAI/BetterTouchTool#1432]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

Could we get a shortcut that allows us to jump straight to the "expanded control strip" ? Right now there's only one way to get there if you allow BTT to take over the touchbar: hide BTT touch bar, then hit the little arrow on the small controlstrip, then you can get there. There's some actions in there that I jump to at times - like adjusting brightness of the keys in low light.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
MacBook Pro Touch Bar 

#### Device information:

Type of Mac: MBP
macOS version: 10.12.6
BetterTouchTool version: latest 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by lightheaded** [comment]
I would really like that as well. I'd like to configure a trackpad gesture to show the expanded control strip. The current workaround is to re-create the default expanded control strip..
