### ISSUE TITLE
Accept Midi input

### ISSUE THREAD

**Issue by tbgulli** [folivoraAI/BetterTouchTool#1440]
would be awesome and add a ton of possible controllers if BTT would accept midi input.

**Comment by dayAlone** [comment]
it will be great!

**Comment by ZAUmusic** [comment]
Still wondering when we'll see MIDI implementation...

**Comment by spaceleviathan** [comment]
FWIW I'd love to see Midi input as well!

**Comment by leny** [comment]
Any news on this?

There was this reference in the [changelog](https://updates.bettertouchtool.net/bettertouchtool_release_notes.html) for version `2.305` (September, 19, 2017):

> Preparations for upcoming MIDI device support

But no news since...

**Comment by fifafu** [comment]
@leny will be the next big addition to BTT. Currently it's planned for release in October (had to postpone for various reasons)

**Comment by leny** [comment]
Great! Can't wait to see that!

Thanks for the update 👍
