### ISSUE TITLE
Interference with Logitech Options software

### ISSUE THREAD

**Issue by ZappoB** [folivoraAI/BetterTouchTool#1459]
#### Description of bug/feature request/question:

BTT seems to interfere with the Logitech Options software which came with my MX Master. After a short standby about 1 min. the mousepointer can't be moved an no click is recognised. The BT connection is still active, but the mouse doesn't work. On a standby of only some seconds, or a long standby of about an hour the mouse keeps working.

To get the mouse to work again, I have to deactivate the BT on my Mac and to reenable it, after then I have to switch the mouse off and on, to get the correct settings from the Options software.

If I unload BTT this does not happen.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Logitech MX Master mouse, BT connection

#### Device information:

Type of Mac: MacBook Air
macOS version: 10.12.6
BetterTouchTool version: 2.297

**Comment by fifafu** [comment]
That's weird, I also have the MX Master but so far everything works fine here.
BTT should not be able to influence mouse movement anyways. 

I'll keep an eye on this, but at the moment I don't think BTT can cause such behavior. Can you really reproduce this and pin it down to BTT?
