### ISSUE TITLE
Thumb recognition doesn't work properly since version 2.20

### ISSUE THREAD

**Issue by nrmilstein** [folivoraAI/BetterTouchTool#1464]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

Ever since it was updated in version 2.20 (around then), thumb recognition hasn't worked properly for me.

Here is how looks now (2.300): https://gfycat.com/gifs/detail/BonyIndolentGosling
And here is how it looked before (2.13): https://gfycat.com/gifs/detail/CompetentOptimalHammerheadbird

I have my thumb resting on the bottom of the trackpad in both screen captures.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

MacBook Pro Trackpad, Magic Trackpad (original)

#### Device information:

Type of Mac: MacBook Pro (13 Inch, Mid 2010)
macOS version: 10.12.6
BetterTouchTool version: 2.300

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

Here are my current thumb recognition settings (2.300):

![screen shot 2017-09-11 at 5 03 42 pm](https://user-images.githubusercontent.com/2774325/30281970-283711be-9714-11e7-9187-5dc65010c778.png)

And my ones before (2.13):

![screen shot 2017-09-11 at 5 12 06 pm](https://user-images.githubusercontent.com/2774325/30282028-5bda9f22-9714-11e7-83d7-421f39553460.png)

Here are my gestures: [BTT settings.json.zip](https://github.com/fifafu/BetterTouchTool/files/1293016/BTT.settings.json.zip)

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
This looks like the intended behavior but it's hard to tell.
In general BTT has introduced a change to allow the thumb to participate in gestures if it's placed on the trackpad at roughly the same time as the other fingers (e.g. to allow 4 finger clicks that include the thumb).

I have added an option to disable this behavior in v2.301 alpha, maybe you can try whether this helps in your case. Unfortunately the old thumb handling didn't work well on the new Macbooks thus I needed to rework it completely.

**Comment by nrmilstein** [comment]
Thanks for your response. I don't think that's the problem, because my thumb was resting on the bottom of the trackpad for the entirety of the previous videos (nonetheless, I appreciate the option and would leave it disabled).

Here's what I have with the option disabled in the alpha version (2.301): https://gfycat.com/gifs/detail/YellowishClumsyHarrierhawk

I think I see the problem: thumb recognition seems to work fine with swipe gestures, but after a click gesture, the thumb shows up again on the live view for a brief moment. The first click gesture (4-finger click) in a sequence typically goes through, but any gestures following in the next couple seconds after a click fail, and I can see the thumb suddenly show up in the live view for a couple seconds.
