### ISSUE TITLE
[Feature Request] Send modifiers being pressed and "Assigned Action" together

### ISSUE THREAD

**Issue by zupodaniel** [folivoraAI/BetterTouchTool#1468]
Description of feature request:

When I define an action button to touch bar using "custom keyboard command" or even using a predefined action like "ESC (Escape key)" BTT doesn't respect modifiers being pressed (command, option, etc...) and send only the command without any modifiers applied. Is it possible to send modifiers by default or create a configuration in action properties to respect them?

**Comment by fifafu** [comment]
For ESC this is now possible using the predefined action ESC. For other keys this is currently not possible as it conflicts with other BTT functionality. But maybe I can make it an option.

**Comment by zupodaniel** [comment]
Thanks, for me it's good enough.
