### ISSUE TITLE
Menu bar icon

### ISSUE THREAD

**Issue by korcad** [folivoraAI/BetterTouchTool#1473]
Sorry if I sound so picky here, but the menu bar icon doesn't align with other apps. The top part of the icon is too short. This is on the latest macOS with the latest BTT. 

Thanks.

**Comment by alex-taffe** [comment]
Same here, clearly not a large priority though. I'd be willing to modify the artwork to fix this

**Comment by fifafu** [comment]
I have slightly changed the icon position in the latest alpha. Could you check whether it looks better now? I  think it's now in line with the Apple icons.

**Comment by alex-taffe** [comment]
Looks much better now. Just as a comparison, here’s pre alpha build:
<img width="97" alt="screen shot 2017-12-17 at 3 26 57 pm" src="https://user-images.githubusercontent.com/6820226/34083454-12a13920-e33f-11e7-9b8f-0c21c292a575.PNG">


and here’s with the latest alpha:
<img width="106" alt="screen shot 2017-12-17 at 3 27 05 pm" src="https://user-images.githubusercontent.com/6820226/34083449-07ed2fac-e33f-11e7-8526-7de173c07a10.PNG">
