### ISSUE TITLE
2 finger TipTap extremely touchy, 3 finger TipTap rarely works

### ISSUE THREAD

**Issue by Saoirse1916** [folivoraAI/BetterTouchTool#1474]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
With version 2.297 the two finger TipTap which I use to cycle through browser tabs fires off constantly, even when just clicking something on a page.  So I figured I'd switch to the three finger TipTap but I could only get that to work about one out of every 10 attempts.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Magic Trackpad, MacBook Trackpad

#### Device information:

Type of Mac: Late 2013 MacBook Pro
macOS version: 10.12.16
BetterTouchTool version: 2.297

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by BClev** [comment]
I have the exact same issue with the exact same laptop (Macbook Pro - Late 2013). For me, this is problematic with Chrome. It used to work flawlessly.

**Comment by cleverjackal** [comment]
In my experience TipTap gestures do get fired accidentally now.
