### ISSUE TITLE
Trackpad option to create margins

### ISSUE THREAD

**Issue by datico** [folivoraAI/BetterTouchTool#1481]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of feature request:
Problem: The new 2017 Macbook Pro (for example) has a giant trackpad, which you can't help but touch when typing. Apple's software is supposed to be smart enough to prevent this, and perhaps it is; I didn't seem to have trouble until installing BTT. (Thus...is this really a bug?)

Feature request: I would like the ability in BTT to define margins/zones on the left, right, top and bottom of the trackpad. (Similar to the Mouse interface for defining left, right, and middle-click zones).  Some might use these margins for special scrolling/scrubbing features, but I would assign a left and right margin to do nothing, thus virtually shrinking the size of my trackpad back to something more normal and eliminating accidental palm-interactions.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
MacBook Pro Trackpad

#### Device information:

Type of Mac: MacBook Pro 14,3 
macOS version: 10.12.6
BetterTouchTool version: 2.301

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by lacostenycoder** [comment]
I've been searching for a solution for this problem for over 2 years!  Please support this feature!!  I would gladly pay $$$  for this.  I tried Karabiner but that doesn't work either. I've mistyped this post 5 times already thanks to shit mac trackpad!
