### ISSUE TITLE
Five finger tap seems to have stopped working in High Sierra

### ISSUE THREAD

**Issue by DanMelbourne** [folivoraAI/BetterTouchTool#1490]
---

#### Description of bug/feature request/question:

I use five finger tap gesture a lot. It seems to have stopped working in High Sierra. 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Inbuilt trackpad on MacBook Pro.

#### Device information:

Type of Mac: MacBook Pro
macOS version: 10.13 Beta (17A362a)
BetterTouchTool version: 2.302 (680)

**Comment by mikecole20** [comment]
Same here.

**Comment by mikecole20** [comment]
Just upgraded to 2.303 and the five finger tap seems to be working. Not sure if 5 finger click works or not though, as I am unable to get the haptic feedback when pressing with five fingers.
