### ISSUE TITLE
safari doesn't go away in app switcher when switching

### ISSUE THREAD

**Issue by Sebastian-blu** [folivoraAI/BetterTouchTool#1494]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

safari icon shows in switcher while I'm actively using safari, unlike the rest apps which go away when I am not focused on them

#### Device information:
Model Name:	MacBook Pro
  Model Identifier:	MacBookPro13,3
  Processor Name:	Intel Core i7
  Processor Speed:	2.9 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	8 MB
  Memory:	16 GB
macOS version: 10.12.6
BetterTouchTool version: 2.297

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Which app switcher are you referring to? The one in the Touchbar?

**Comment by Sebastian-blu** [comment]
yeah
