### ISSUE TITLE
Touch Bar Colours Disappear When Using Second Display

### ISSUE THREAD

**Issue by rscosworth** [folivoraAI/BetterTouchTool#1495]
#### Description of bug/feature request/question:
When second (external) display is active, intermittently the Touch Bar will loose some colours on the Touch Bar icons.
When primary (Macbook) display is active the colours return to the Touch Bar icons.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Touch Bar

#### Device information:
Type of Mac: 2017 Macbook Pro Touch Bar
macOS version: 10.12.6
BetterTouchTool version: 2.302 (680)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
<img width="1085" alt="touch bar shot 2017-09-19 at 10 19 56" src="https://user-images.githubusercontent.com/29540836/30585536-16e7e3b8-9d25-11e7-971f-a07543ec8da3.png">
<img width="1085" alt="touch bar shot 2017-09-19 at 10 20 12" src="https://user-images.githubusercontent.com/29540836/30585541-1b3ad9c0-9d25-11e7-92f2-a56076af206e.png">

**Comment by fifafu** [comment]
That's weird, I can't seem to reproduce this.
Would it be possible to share your setup with me? (Using the Manage Presets button and using the export functionality)

**Comment by rscosworth** [comment]
Hi Andreas,

Attached is the export of my configuration.

It’s odd as it is intermittent, but I have most noticed it when it is a Java application which is live on the second screen, the tool bar will then switch between greyed out when on the second screen, and full of colour when back on the main screen.

Thanks
Ross
