### ISSUE TITLE
Snap Areas trouble with two identical displays

### ISSUE THREAD

**Issue by adlibdalom** [folivoraAI/BetterTouchTool#1496]
#### Description of bug/feature request/question:
I'm having an issue with Snap Areas on my two identical displays (Samsung SyncMaster F2380). Every area I define, regardless of monitor, ends up moving all windows to ”first” monitor, despite areas being created on my second monitor.

#### Device information:
Type of Mac: MacMini Late 2014 (Macmini7,1)
macOS version: 10.12.6
BetterTouchTool version: 1.7

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
Holler if you need additional information.

**Comment by fifafu** [comment]
This is indeed a problem. I'll be looking into it. (Some monitors apparently don't report different serial numbers and thus BTT/BST gets confused)

**Comment by johnatgh** [comment]
@fifafu This bug also exists in BetterSnapTool, but hoping it gets fixed in BTT. Thanks for your great work!
