### ISSUE TITLE
`Move Window to next Monitor` doesn't honor monitor positions

### ISSUE THREAD

**Issue by keichinger** [folivoraAI/BetterTouchTool#1502]
#### Description of bug/feature request/question:
My monitors are arranged like this:
![2017-09-20 at 08 39](https://user-images.githubusercontent.com/439899/30630084-52f4c0a0-9ddf-11e7-869c-3eed53895518.jpg)

However, the original arrangement was more like this where each number is from left to right:
![2017-09-20 at 08 39](https://user-images.githubusercontent.com/439899/30630107-6d11b182-9ddf-11e7-8ba6-4c8a4cb829f9.jpg)

Now when using the `Move Window to Next Monitor` functionality bound to a keyboard shortcut, it's moving the windows based on the second screenshot and not the first. This is happening even after restarting BTT multiple times.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
All

#### Device information:

Type of Mac: MacBook Pro Late 2016 TouchBar
macOS version: Sierra
BetterTouchTool version: 2.304 (682)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
-

**Comment by djohnsen** [comment]
I commented on #514 about using Spectacle to get previous/next window mapped into touchpad swipes via BTT - see there for further details if needed.
