### ISSUE TITLE
BTT icon resizing does not work on Apple Script widgets

### ISSUE THREAD

**Issue by fantaaaaaa** [folivoraAI/BetterTouchTool#1508]
When resizing the icons of regular Buttons they can be smaller or larger but when changing the setting for Widgets it does not seem to work - theres no visible effect.

could you look into this and maybe fix it? thanks!

**Comment by fifafu** [comment]
This issue was moved to https://community.folivora.ai/t/btt-icon-resizing-does-not-work-on-apple-script-widgets/36

**Comment by fifafu** [comment]
Sorry, please ignore the previous message. The migration didn't work correctly, for now the issues will stay here.
