### ISSUE TITLE
FR: Disable Snap on 2nd Display

### ISSUE THREAD

**Issue by yarg-master** [folivoraAI/BetterTouchTool#1514]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Feature Request

A way to disable snap on a 2nd display. Or alternatively a global 'snaps enabled' per display.

The fullscreen snap feature can sometimes drag windows from the currently used display to  another display and this can be really frustrating. In a 'stacked' screen display (one display above another) a window only needs to be in the bottom 3rd of my main display to jump down to the bottom display (which will often happen if I organising/shifting around windows).

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Macbook Pro

#### Device information:

Type of Mac: 2012 Macbook Pro 13inch
macOS version: 10.11.6
BetterTouchTool version: 2.297

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
This issue was moved to https://community.folivora.ai/t/fr-disable-snap-on-2nd-display/40

**Comment by fifafu** [comment]
Sorry, please ignore the previous message. The migration didn't work correctly, for now the issues will stay here.
