### ISSUE TITLE
Trigger Context Menu Item is broken in iTunes 

### ISSUE THREAD

**Issue by chrisduong** [folivoraAI/BetterTouchTool#1519]
#### Description of bug/feature request/question:

Trigger Context Menu Item is broken in iTunes.

I assigned one keyboard shortcut to choose the first item in the context menu with the value (1) for iTunes. When I press the shortcut, the context menu shown up but the first item has not been chosen.

I copied this same shortcut to Safari, it works fine.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

iTunes

#### Device information:

Type of Mac: Macbook Pro 2016 
macOS version: 10.12.6
BetterTouchTool version:  2.304

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
The action seems to work fine here, what exactly are you trying to trigger?

**Comment by chrisduong** [comment]
I want a shortcut to show me "Which playlist a song belong to", please see the picture, then you understand.

I tested with simple case in iTunes, I set "Trigger the Context Menu Item" to select the first Item, which is "Add to Playlist" but it cannot be picked up either.

<img width="779" alt="ko" src="https://user-images.githubusercontent.com/1848882/31065484-41b2cc0e-a778-11e7-9629-3eacbc1ca05f.png">



<img width="647" alt="xsg" src="https://user-images.githubusercontent.com/1848882/31065428-c0e17134-a777-11e7-9c76-059c51892fb9.png">

**Comment by fifafu** [comment]
Ah sorry, this action is not supposed to **_show_** the context menu. It's supposed to trigger an action in that context menu. You use case is currently not possible with BTT .

Or well, you could use a hack like in this screenshot:
![image](https://user-images.githubusercontent.com/8820811/31623918-4efd4c02-b2a1-11e7-99ac-b07f055d05fe.png)
