### ISSUE TITLE
Delete Screenshot button

### ISSUE THREAD

**Issue by W00DCH1P** [folivoraAI/BetterTouchTool#1520]
Feature requested:
Please place a delete screenshot button on the screenshot window, its quite a mission having to go into the pictures folder to delete the screenshots.

Affected input device:
My hands

#### Device information:

Type of Mac: MacBook Pro
macOS version: 12.13
BetterTouchTool version: 2.304

**Comment by fifafu** [comment]
This issue was moved to https://community.folivora.ai/t/delete-screenshot-button/45
