### ISSUE TITLE
Recent emoji in touch bar widget doesn't count emoji used in BTT

### ISSUE THREAD

**Issue by JCLaHoot** [folivoraAI/BetterTouchTool#1530]
#### Description of bug/feature request/question:
The recent emoji used in the BTT emoji widget map to the system-wide recent emoji. However, when you use BTT to type emoji, the list of recent emoji is never updated to take these into account. Emoji typed using the Apple emoji touchbar widget do get added to system-wide recent emoji.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Touch Bar

#### Device information:

Type of Mac: MacBook Pro 2017
macOS version:  10.12.6
BetterTouchTool version: 2.305

**Comment by mjstew33** [comment]
agreed, also having this issue in High Sierra. really miss having my frequently used characters (particularly!) in the touch bar.

**Comment by fifafu** [comment]
Unfortunately there is no public API to add Emoji to the recently used list. In case I figure out how to do it I'll add it to BTT, but for now I don't know how to :-(

**Comment by JCLaHoot** [comment]
I think a custom BTT implementation of the emoji-list could work well for people who exclusively use the BTT emoji picker.
