### ISSUE TITLE
Corner taps are not working reliably on new MBP Touch Bar

### ISSUE THREAD

**Issue by robertschwenkler** [folivoraAI/BetterTouchTool#1532]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Single finger corner taps, which I've been using to open apps/bring apps to the front, are not working reliably. When I look in the Live View window it looks like my input should be triggering the action, but much of the time it's not.

I haven't been able to discern any distinguishing elements on my end that are causing this action to trigger or not trigger. I'm not doing it any differently than I did on my 15" MBP Retina, I was used to this input trigger working perfectly there.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Mac trackpad

#### Device information:

Type of Mac: 2016 MBP 15" Touch Bar
macOS version: 10.12.6
BetterTouchTool version: 2.304

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Maybe try turning off "Thumb Handling" in the advanced trackpad pereferences. The corner taps are kind of tricky in combination with thumb handling, thus it might cause some issues.
