### ISSUE TITLE
[Bug] Copied "No Action" shortcut always causes crash 

### ISSUE THREAD

**Issue by shimj** [folivoraAI/BetterTouchTool#1547]
#### Description of bug:

When I copy and paste a shortcut whose action is "No Action" and change the shortcut of the pasted item, the pasted item will not have any description in the action area. This doesn't matter in Sierra, but causes a crash in High Sierra when I try to tigger the pasted item.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Keyboard

#### Device information:

Type of Mac: MBP 2017 with touch bar
macOS version: 10.13
BetterTouchTool version: 2.305

Crash log: [BetterTouchTool_2017-08-28-165055_Minjis-MacBook-Pro.txt](https://github.com/fifafu/BetterTouchTool/files/1332598/BetterTouchTool_2017-08-28-165055_Minjis-MacBook-Pro.txt)

**Comment by fifafu** [comment]
Hey,

thanks a lot for reporting. If possible, could you attach an export of a crashing setup? (Click the manage presets button to export the current setup)

Best,
Andreas

**Comment by shimj** [comment]
[Test.json.txt](https://github.com/fifafu/BetterTouchTool/files/1351206/Test.json.txt)
This is the simplest setup to reproduce the bug.
Pressing `⌘+x` continuously always causes crash. (only one press sometimes doesn't cause crash.)
However, my friend's macbook air 2017 cannot reproduce this bug...

**Comment by fifafu** [comment]
Unfortunately I also can't seem to reproduce the crash on my machine. Does this still happen with the latest version of BTT?
