### ISSUE TITLE
Weird interaction between "4 fingers swipe up launchpad" and "4 fingers swipe down mission control"

### ISSUE THREAD

**Issue by Jusant234** [folivoraAI/BetterTouchTool#156]
Hello,

First, congrats for your amazing software.

I've added 2 new four fingers gestures with btt (and disabled those from syst pref): 
- 4 fingers swipe up activates launchpad
- 4 fingers swipe down activates mission control

A bug occurs on this specific case : 
1. I start launchpad (4 fingers up)
2. Exit launchpad with esc key (without starting any app)
3. I try to use mission control (4 fingers down)
=> Launchpad starts again instead of mission control

I'm using the 13" MacBook Pro late 2016 without touchbar, and the built-in trackpad.
I'm running Sierra 10.12.2 and BTT 1.971.

Of course, this is a really minor issue, but still worth reporting.

Btw, i've found old forum posts talking about experimental dragging to remove the annoying tap and drag release delay but I can't find it now. You removed it ?

Regards,
Bye

**Comment by fifafu** [comment]
This issue was moved to https://community.folivora.ai/t/weird-interaction-between-4-fingers-swipe-up-launchpad-and-4-fingers-swipe-down-mission-control/93

**Comment by fifafu** [comment]
Sorry, please ignore the previous message. The migration didn't work correctly, for now the issues will stay here.
