### ISSUE TITLE
BTT causes delay/hiccups in entering password after wake from sleep

### ISSUE THREAD

**Issue by jeroenh** [folivoraAI/BetterTouchTool#1572]
#### Description of bug/feature request/question:

When BTT is active, and I try to unlock my mac after waking it from sleep, it causes issues with entering my password. There are delays in typing, and some keystrokes aren't registered.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

MacBook built-in keyboard

#### Device information:

Type of Mac: MacBook Pro
macOS version: 10.12.6
BetterTouchTool version: 2.305

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by jeroenh** [comment]
Most annoying of this particular bug is that the stutter happens in two stages. Even if you wait a few seconds before starting to type your password to avoid the initial hiccup, there is another one that happens and eats several characters when you're busy typing your password.

**Comment by dionysos283** [comment]
I have the same problem. It almost never unlocks the Mac. Instead there is an infinite entering of wrong passwords.
