### ISSUE TITLE
Magic Mouse spaces geasture

### ISSUE THREAD

**Issue by sunadmn** [folivoraAI/BetterTouchTool#1573]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
2 finger swipe up -> Show Spaces stopped working with latest update.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Magic Mouse

#### Device information:

Type of Mac: MacBook Pro (Retina, 15-inch, Mid 2014)
macOS version: High Sierra 10.13
BetterTouchTool version: 2.310

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by sunadmn** [comment]
This corrected itself after a reboot, but after sleeping over night the issue has come back. I have tried restarting the application and it does not help. It looks like to resolve this I must reboot.

**Comment by fifafu** [comment]
I don't think there has been any change related to this. However maybe it's related to macOS 10.13. Are you using the predefined action "Mission Control" to show spaces?

**Comment by sunadmn** [comment]
I have been using the same profile since back in 2009 when spaces was a
thing. I just export and re-import the same config. Odd enough 2.270 on my
iMac (27-inch, Late 2013) with 10.13 doesn't have the issue so I downgraded
to see if that would fix the problem. It didn't so I am not sure if it's
10.13 or 10.13 and hardware on my macbook pro that is causing it. I
attached a screen capture of my config.
