### ISSUE TITLE
MBP 2016 brightness increasing automatically with extended display

### ISSUE THREAD

**Issue by anas2204** [folivoraAI/BetterTouchTool#1583]
#### Description of bug/feature request/question:
Whenever I connect (or disconnect) my MacBook Pro 2016 with Touch Bar to an extended display, its brightness increases one or multiple blocks. This happened after upgrading to High Sierra. The steps to reproduce are:
Put your brightness to a certain level.
Connect an extended display (I tested with multiple displays, HDMI to USB-C or VGA to USB-C)
Check if the brightness increased or not.

After going through multiple rounds with Apple Support (SMC and NVRAM Reset, macOS reinstall), I notice this happens only when BTT was active. It'll be of immense help if you can take a look into this!

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Macbook

#### Device information:

Type of Mac: MacBook Pro 2016 with Touch Bar
macOS version: 10.13
BetterTouchTool version: 2.310

**Comment by fifafu** [comment]
Weird. I'll see if I can figure out what could cause this (currently I really have no idea as BTT shouldn't do anything to your display brightness)
