### ISSUE TITLE
Actions in BTT Remote need more love (aka BTT Remote as an external TouchBar)

### ISSUE THREAD

**Issue by SynerG** [folivoraAI/BetterTouchTool#1584]
BTT excels at providing custom Actions to control your Mac with any input method (Trackpad, TouchBar, Mouse).

When I found BTT Remote, I got really excited as I expected the same excellence in defining custom Actions, but with all the potential that provides the screen of the iPhone.
However, Actions in BTT Remote look like an after thought while the app focuses on other features (e.g. trackpad, mini-trackpad, on-screen keyboard).

There is only me to blame, as I don't use BTT Remote away from my Mac to move the mouse around, but I use it *while sitting at my Mac*. 
![external touchbar](https://user-images.githubusercontent.com/7237097/31306032-c45b6fc6-ab47-11e7-9e8e-14b8432059d0.png)

For me, it works/should work **as an external TouchBar** that shows contextual Actions to be performed at the current Application. But, in contrast with trackpad gestures/hotkeys/mouse buttons, you don't need to learn them by heart, you can actually see the Action that you are going to perform.

The TouchBar is great in the latest Macbook Pros, but **too often there is no one available** (any iMac, older Macbooks, or even new Macbooks used with the lid closed connected to external displays).

It would be great to have the same kind of functionality available from the screen of your iPhone.

However, the current way of presenting Actions in **a scrollable list**, that only uses a fraction of the screen real-estate **is not good enough**.

**Limitations of the current Actions list:**
- The list share the screen with other widgets. Actions should be able to cover the full screen
-  Each list item uses the full width of the iPhone screen so much space is wasted. Multiple icons/Actions could fit in the same row.
- The scrollable list makes it unpredictable where each Action is going to be placed on the screen, so your fingers cannot learn to find them.
- In landscape, even less Actions are able to fit per screen. Lanscape orientation is the most natural position to have your iPhone next to your keyboard as an external TouchBar.
- Actions cannot be set in groups. The TouchBar support allows to group multiple actions into a button/folder that is expanded when pressed. It would be great if Actions could be grouped in BTT Remote in a similar way.

**Possible solution:**
- Allow to show Actions in their own screen. As a grid of icons. Fullscreen
- and support Button Groups (as the TouchBar feature)

Very similar to how the "Function keys" (brightness up/down, volume up/down) are currently presented in BTT Remote, but I would like to have my own Actions (and use the full screen):
<img width="237" alt="current grid of keys" src="https://user-images.githubusercontent.com/7237097/31306064-5cab215e-ab48-11e7-9934-028265cf7afa.png">
Note: this screen has multiple pages of icons that you can swipe, this could be an alternative to the "Button Group" concept of grouping Actions.

In essence, is a concept similar to the programmable keyboards (that you set next to your regular keyboard) where each key is programmed to perform a specific action in the application:
![programmable keyboards](https://user-images.githubusercontent.com/7237097/31306204-36d42356-ab4b-11e7-8ef3-49f050215543.png)

But with the benefit that you do not need to memorize each key, as you can seen the grid of icons available for each app.

The current list of Actions is good, but it could be improved.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
iPhone/iPad with BTT Remote

**Comment by fifafu** [comment]
Yes I agree. There will be a big update to BTT Remote, but it is not yet ready... (currently I assume it will take until the end of the year for it to be finished, but maybe I'll be faster)
