### ISSUE TITLE
Snap Area Malfunction

### ISSUE THREAD

**Issue by chewie62** [folivoraAI/BetterTouchTool#1586]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

As of past month or more, snap areas have been defective. When dragging window to a custom snap area, the snap area will glitch and will not respond to the window that I'm dragging to be resized.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Macbook trackpad, mouse

#### Device information:

Type of Mac: Macbook Pro Retina 13" Late 2013
macOS version: macOS Sierra 10.12.6
BetterTouchTool version: 2.310

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Unfortunately I'm currently unable to reproduce this.

If possible please go to the about tab in BTT and click the "Export debug information button". This will create a folder called "BetterTouchToolDebug" on your Desktop, please send the contents of that to boastr.net@gmail.com
