### ISSUE TITLE
[Feature Request] Trigger for app gets focused/defocused

### ISSUE THREAD

**Issue by MHX792** [folivoraAI/BetterTouchTool#1590]
I need to launch a script everytime an app gets opened or focused and another script when when it loses focus or gets closed.
Seeing this functionality in BTT would be great.

**Comment by fifafu** [comment]
That should be relatively easy to add. I'll look into this.

**Comment by 3bbing** [comment]
Could you explain quickly where to find the trigger in case it was added? I too need to run a key Combo App-specific whenever I move focus from the app's window. 
Or simply said: I want to Ctrl+S everytime I leave a Word/Excel etc window. Tired of the non-working autosave of MS Office...
Didin't find it in "Other" neither in "Normal Mice". Would have expected it at "Other" -> "Window Buttons & Click Actions". I'm on 2.687. Thanks!
