### ISSUE TITLE
[Potentially critical] [Bug] Removing applications in imported preset will cause applications in original preset to be removed as well

### ISSUE THREAD

**Issue by cleverjackal** [folivoraAI/BetterTouchTool#1592]
#### Description of bug/feature request/question:

1. Make sure you have only one preset (I tried this with one preset only). Let's call this "My Preset 1."
2. Export the preset.
3. Import the preset. Rename the imported preset to "My Preset 2."
4. Set the master preset to "My Preset 2."
5. Remove some applications in the left panel.
6. Set the master preset to "My Preset 1."
7. Look at the left panel. You'll see that the applications which were removed from "My Preset 2" were _also_ removed from "My Preset 1."

#### Device information:

Type of Mac: MacBook Pro
macOS version: High Sierra
BetterTouchTool version: 2.310 (687)

**Comment by fifafu** [comment]
Thanks for reporting, I'll look into this!

One tip: you can always press cmd+z to undo changes if you notice anything went wrong.

**Comment by cleverjackal** [comment]
Great, thanks!
