### ISSUE TITLE
Application Switcher

### ISSUE THREAD

**Issue by GitHubswn** [folivoraAI/BetterTouchTool#1594]
We know you are busy but I'm not getting a respond from you via email (5 Days). So I have to post it on here.

*Not being able to use this gestures for days is annoying.
** I use 'Application switcher' a lot. Pls fix it.

#### Description of bug/feature request/question:

After installing High Sierra  'Application Switcher' suddenly stops working AFTER A PERIOD OF TIME (with in the hour)
Using keyboard shortcut, Command-Tab AND Command+Shift+Tab also stops working. The only way to get it to work again is to Restart my Mac. Then stops working again after 30 minutes.

SO LONG AS  BetterTouchTool is completely disable in the background, PRESSING CMD+TAB work fine.

 
#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

MacBook Trackpad

#### Device information:

Type of Mac: Early 2013
macOS version: 10.13 
BetterTouchTool version: 2.310

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

It is not High Sierra issue.  Been using my Mac without BTT and pressing Command-Tab works fine the entire day. As soon as I start BTT within 30 min 'Application switcher stops working so does keyboard shortcut Command-Tab.

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Unfortunately I haven't been able to reproduce this yet and haven't had similar reports yet :-(
I'll let you know if I find anything.

**Comment by FryJay** [comment]
I've also encountered this.  It's happened twice now.
