### ISSUE TITLE
Keyboard Commands/Shortcuts Are Not Working

### ISSUE THREAD

**Issue by HammerOfThor88** [folivoraAI/BetterTouchTool#1599]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
As of today, BTT is not picking up keyboard sequences for saved autofill information.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
MacBook Pro Keyboard, and Apple USB Keyboard

#### Device information:

Type of Mac: 
Macbook Pro 15 inch 2017
2.9 GHz i7
macOS version: 10.13
BetterTouchTool version: 2.310

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Have you tried to restart your Mac? I haven't had any similar reports and am unable to reproduce this on my machines.

**Comment by HammerOfThor88** [comment]
Andreas,

I was able to get it working by uninstalling and reinstalling BTT. Thanks
for checking on this for me :)

Josh

**Comment by msafi** [comment]
Restarting my Mac fixed the issue. Thanks.
