### ISSUE TITLE
Adding Application multiple times

### ISSUE THREAD

**Issue by moodhugs** [folivoraAI/BetterTouchTool#1600]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

I added many apps to the list a long time ago by selecting file. Now there is an option to select apps that are running. So I tried it and it added duplicates. Annoying but not the end of the world. But then I tried to delete one of them it deleted all the configurations for both. Luckily i only lost one Touch-bar item. but i still have one otheritem duplicated and can never remove it because i don't want to lose all the configurations.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Preferences interface

#### Device information:

Type of Mac: MacBook Pro (15-inch, 2016)
macOS version: 10.12.6 (16G29)
BetterTouchTool version: 2.310 (687)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Weird, for me it seems to  allow duplicates (this is intended for various reasons) but it also only deletes the selected one, not both of them.

One tip: you can always press cmd+z to undo your changes in BTT.
