### ISSUE TITLE
Magic mouse scrolling issue

### ISSUE THREAD

**Issue by matrosovas** [folivoraAI/BetterTouchTool#1601]
#### Description of bug/feature request/question:
Magic mouse one finger scrolling stops working randomly, after it crashes I can no longer scroll nor go back/forward with side swipes in safari. Need to restart BTT to get it working again.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Magic Mouse

#### Device information:

Type of Mac: macbook pro 15' 2016
macOS version: 10.13
BetterTouchTool version: 2.310

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
Restarting or disabling BTT fixes the issue

**Comment by fifafu** [comment]
Weird. Can you see any usage pattern that causes this? Or does it seem to be completely random?

Any info could be helpful.

**Comment by matrosovas** [comment]
I use multiple monitors so maybe that changes something but I find that it breaks sometimes when focusing from one application to another.

**Comment by mifield** [comment]
I am affected by the same issue.

Description of bug/feature request/question:

Magic mouse one finger scrolling stops working randomly, after it crashes I can no longer scroll nor go back/forward.

This issue has been happening for at least a couple of months.

Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Magic Mouse

Device information:

Type of Mac: mac pro Early 2008
macOS version: 10.11.6 (latest for my mac pro)
BetterTouchTool version: 2.313 (691) Licensed

Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

The mouse work fine for several minutes and the stops scrolling/back/forward, most of the times just opening the BetterTouchTool preferences fixes the issue.

With BetterTouchTool closed no issues with the mouse.

**Comment by mifield** [comment]
I started noticing this issue in Opera. Today I have uninstalled Opera and the issue is less frequent and just by changing the focus of the scrolling window and back seems to fix it. No need to open the preferences.

**Comment by mifield** [comment]
Day 2: I am not noticing any issues with the mouse. Uninstalling Opera seemed to do it!
