### ISSUE TITLE
Mission Control / Show Desktop no longer working

### ISSUE THREAD

**Issue by apetronix** [folivoraAI/BetterTouchTool#1602]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
The "Mission Control & Immediately Show Desktop Preview" option no longer seems to be working on 2.310.

It only activates Mission Control, but does not show the Desktop Preview anymore.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Keyboard and Mouse Buttons

#### Device information:

Type of Mac: iMac
macOS version: 10.12.6
BetterTouchTool version: 2.310

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
I've tested it on a keyboard shortcut and mouse button, both give the same result described above.

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
This seems to work fine here (and there hasn't been a change). Have you already tried to restart your machine?

**Comment by kachkaev** [comment]
After upgrading to Macos High Sierra and switching to a new 2017 makbook, the gesture works for me half of the times. Can't figure out what exactly prevents desktops from showing.

**Comment by connorsadlervelo** [comment]
I am seeing the same as kachkaev - I just downloaded BTT and this isn't a great start to be honest 8[

**Comment by connorsadlervelo** [comment]
PS I am on a brand new Macbook Pro with Force touchpad

**Comment by samfearn** [comment]
Sorry to comment on a closed thread, but was any progress made with this? I'm experiencing the same issue as described above on Mojave.
