### ISSUE TITLE
Window Snapping Issues

### ISSUE THREAD

**Issue by gregalanraslan** [folivoraAI/BetterTouchTool#1607]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
BUG: Set 4-finger swipe gestures to snap windows. However, Microsoft Office apps do not snap unless the cursor is over the menu bar, and it seems that other applications are presenting with the same issue since the update to High Sierra. For example, Preview is having the same issue.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

MacBook Trackpad

#### Device information:

Type of Mac: Macbook Pro 2015
macOS version: 10.13
BetterTouchTool version: 2.310 (687)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Thanks for reporting, I'll look into this.

**Comment by fifafu** [comment]
Mhh I can't seem to reproduce this with Preview (and currently don't have office installed).
Are you sure you haven't accidentally set the trigger option to only trigger while hovering the menubar?

See this screenshot
![image](https://user-images.githubusercontent.com/8820811/31616566-50856f8c-b28d-11e7-9e81-95007145fc9a.png)

**Comment by gregalanraslan** [comment]
Andreas,

I am unable to get to this menu. Can you please share the steps taken to find this?

Thanks!

Greg
