### ISSUE TITLE
Snap multiple Apps at the same time

### ISSUE THREAD

**Issue by keaang** [folivoraAI/BetterTouchTool#1616]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Hi, I just purchased BetterTouchTool, so I'm new to it.  After playing around with it for about an hour I couldn't get it to do what I wanted, so I want to know if this is possible or not.  I would like to snap multiple applications to specific areas with one keyboard shortcut, touchbar icon, or gesture.  So for example, lets say I have 3 applications, Firefox, Outlook, Evernote.  When I press a keyboard shortcut/touchbar icon/gesture I want to snap/position Firefox to the 3rd left of the screen, and snap/position Outlook to the center 3rd of the screen, and position/snap Evernote to the right 3rd of the screen all at the same time.

Is this possible?  If not, can I request this as a feature request?

#### Device information:

Type of Mac: Macbook Pro 15" Early 2016 Touchbar
macOS version: Sierra
BetterTouchTool version: 2.310(687)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by keaang** [comment]
I figured out a workable solution using a combination of Applescript and Predefined Action.  I thought I would share it in case anyone else is trying to accomplish the same.  Works really well on my Ultrawide external monitor.  Awesome application by the way!

I created the following Global Workflow with a Touchbar Button but can be assigned to a keyboard shortcut as well.

First step is to make the application the forefront window using Applescript command from the Predefined Action "Run Apple Script" . See the screenshot below for the simple Applescript command.
![image](https://user-images.githubusercontent.com/17499917/31567310-7f274802-b034-11e7-8ca9-f187c232d60c.png)

Next Attach Additional Action, and select Window Resize and Move and select the type of window resizing you want.  In my case I want the first application to be "Resize window to Left Third"

Add additional Actions and repeat the two steps above for the other two applications but change the applescript to activate the other two applications and "Resize Window to Middle Third" and then "Resize window to Right Third"
 

![image](https://user-images.githubusercontent.com/17499917/31567072-50257de0-b033-11e7-910b-972f85b31b3c.png)

**Comment by fifafu** [comment]
I think this might be a good feature, but I'm not yet sure how to add it without make it very complicated to set up. (Snap areas are already complicated :-)).

I'll leave this open for now, in case anybody has suggestions on how to integrate such a multi-snap, please post them here.
