### ISSUE TITLE
Siri remote mouse control

### ISSUE THREAD

**Issue by knuckles76** [folivoraAI/BetterTouchTool#1618]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

Once the Siri remote mouse control times out, it won’t reinitiate. I have to restart BTT to get mouse control back. 

#### Device information:

Type of Mac: MacBook Pro 13inch mid-2012
macOS version: 10.13
BetterTouchTool version: 2.310 (687)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Thanks for reporting, I'll look into this.

**Comment by Worie** [comment]
I wasn't able to get this feature to work at all unfortunetely. Sorry for using this thread, but i thought it fits. 

I've got MacBook Pro Retina 13" mid 2014, first tried to use it on OSX Sierra 10.12.5 and 10.12.6 - the remote wasn't recognized at all. After update to 10.13.1 BTT recognized it, but toggling mouse control does not work. The monits/dialog show up, but mouse is controllable.  
I wonder if there are any steps I'm missing or there's some other related problem to this?

I know that there are more urgent issues atm, but at this point - I had to ask for help :)

**Comment by carloverthepond** [comment]
I also have the same issue, once the new Siri remote mouse control times out, it won’t reinitiate. Pressing Siri remote wakes it up and shows connection via bluetooth preferences. However BTT doesn't show connection and won't register inputs from Siri remote. Restart BTT then shows its connected but still won't register commands. 

Affected input device Siri Remote 4K

Device information:

Type of Mac: iMac (Retina 5K, 27-inch, 2017)
macOS version: 10.13.1 (17B48)
BetterTouchTool version: 2.314 (693) (older versions do the same thing)
