### ISSUE TITLE
Siri Remote, Repeat 1 Finger Click actions for Plex

### ISSUE THREAD

**Issue by occamsrazorben** [folivoraAI/BetterTouchTool#1619]
#### Description of bug/feature request/question:

Need to enable repeat key press actions for Siri Remote trackpad 1 Finger clicks.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Siri Remote

#### Device information:

Type of Mac: Macbook Pro
macOS version: 10.11.6
BetterTouchTool version: 2.311 Alpha

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

Hi,
I just bought a Siri Remote and am trying out BTT. My main purpose is to replicate the use of the old Apple silver infrared remote when used with Plex Home Theater, and I have mostly achieved that with these actions:

<img width="1014" alt="btt actions" src="https://user-images.githubusercontent.com/32790360/31574099-ab36359c-b0d0-11e7-95fc-7cc7df9b4f6b.png">

The issue I am having is the "Up" and "Down" key presses that get triggered by "1 Finger Click Top/Bottom" don't get repeated when the click is held down. I tried to set up additional action as "1 Finger Click and Hold Top" but it also generates a single key "Up" press.

What I think I need is a key repeat option, as seems to be available when using the actual keyboard and as described here:

https://github.com/fifafu/BetterTouchTool/issues/157

But that option doesn't seem to be available for the Siri Remote options. Is there some other way I can generate repeated key "Up" and "Down" presses to scroll quickly up and down menus/long lists in Plex?

Thanks.....

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
That should be possible, I'll look into this.

**Comment by occamsrazorben** [comment]
Hi,
Just checking back to see if this might be on the roadmap...
Thanks.

**Comment by caliph2** [comment]
Hello.  Got BTT a few weeks ago -- really enjoying it, thanks for all the work!  I'd like to second this request for Repeat Key for Siri Remote.  I'm trying to pan screen using Stellarium software -- I use arrows on keyboard. Need to be able to hold down mouse button clicks to repeat this action.  Panning one click at a time is painfully slow.

**Comment by HazCod** [comment]
Pinging in
