### ISSUE TITLE
clipboard manager problem with adobe illustrator 

### ISSUE THREAD

**Issue by lalapo420** [folivoraAI/BetterTouchTool#1625]
copy text with style will separate to many object, for example: i copy one text with 3 layer style, it will paste as 3 objects, 4 layer style will paste as 4 objects....

**Comment by fifafu** [comment]
Interesting, I'll look into this!

**Comment by fifafu** [comment]
Do you still encounter this issue?
If so, which Illustrator are you running exactly?

I have heard people could solve various clipboard issues with illustrator by disabling "include svg code" in its options:

![image](https://user-images.githubusercontent.com/8820811/37252146-a531b50c-251c-11e8-90ab-c4798eb1ecb4.png)

**Comment by lalapo420** [comment]
yes, i still encounter this issue, disabling "include svg code" still not working, i use macOS 10.13.3 and lastest illustrator CC 22.0.1
