### ISSUE TITLE
[Feature Request] Multi-Monitor vs Laptop alone window position saving and rearrangement

### ISSUE THREAD

**Issue by bobharrisbtt** [folivoraAI/BetterTouchTool#1626]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
[Feature Request]
I have BetterTouchTool suggestion for your consideration.

It is an expansion of your Window Snapping.  I would like BetterTouchTool to help me arrange my open application windows, as I move between working on my laptop alone, and when I plug in an external monitor (or 2).

Since BetterTouchTool knows how to move and resize windows, as well as remember previous sizes and locations, I was wondering if you could add a feature that would allow me to memorize window arrangements when I'm using multiple monitors, and when I'm just using my laptop away from my desk.  Then either automatically arrange the windows when I switch configurations, or at least give me an easy to trigger action to establish that configuration.

I know that on the surface it sounds easy, but I'm sure there will be lots of issues, such as what if the app is not running at the time, and what about new windows in the same app, or fewer windows, etc...

Bonus points, if you can also include the desired Dock location.  For example, I like my Dock on the left, but when I plug into a 4K monitor positioned to the left of my MacBook Pro, the Dock moves, so I change the Dock location to the Right.  I know it is a personal preferences, but if memorizing window locations, could include that, it would be a nice detail for me.

I know there are separate utilities that do this (such as Stay <http://cordlessdog.com/stay>), but I already use BetterTouchTool, and the fewer apps and utilities I have running 24/7, the happier I'll be.

Also, I figure this might be an area that BetterTouchTool might like to expand into which would enhance its value.

Thank you for reading my suggestion.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
N/A

#### Device information:

Type of Mac: Late 2016 15" Macbook Pro
macOS version: Sierra 10.12.6
BetterTouchTool version: 2.310

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by rodalpho** [comment]
Yes I use Moom for this purpose, and while it works fine would love to consolidate functions under BTT as it does so much more.
