### ISSUE TITLE
[Feature request] Horizontal centring 

### ISSUE THREAD

**Issue by welpo** [folivoraAI/BetterTouchTool#1627]
I would love to have the ability to centre a window but ONLY horizontally (or ONLY vertically).

Instead of placing the window at the absolute centre of the monitor, this feature would allow to move it up and down and then centre it on the horizontal axis.

**Comment by fifafu** [comment]
In v2.460 (alpha) there is a new predefined action which can do all sorts of custom window moving and resizing:
![image](https://user-images.githubusercontent.com/8820811/39365653-08ef6b04-4a32-11e8-98be-4befc40b4506.png)
