### ISSUE TITLE
"BetterTouchTool version incompatibile"

### ISSUE THREAD

**Issue by jonathanapp** [folivoraAI/BetterTouchTool#1629]
All of a sudden BTT won't launch.

Screenshot:

https://imgur.com/a/3aqhb
![image](https://user-images.githubusercontent.com/13562081/31667220-c854fb74-b31c-11e7-990e-162fe5638c77.png)

**Comment by fifafu** [comment]
Hey,

you have probably started an older version of BetterTouchTool. Where is
your BetterTouchTool file located?
Maybe try re-downloading from my website: https://boastr.net/downloads

Best,
Andreas

2017-10-17 15:23 GMT+02:00 jonathanapp <notifications@github.com>:
