### ISSUE TITLE
Odd bug with Logic Pro X...

### ISSUE THREAD

**Issue by fKing** [folivoraAI/BetterTouchTool#1630]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
When running Logic Pro X with BTT also running, Logic's internal plugins often have random parameter jumps; ie, in the Gain control, when I click OUT of that plugin, the Gain jumps all the way to the left. Happens in various versions of mac OS (for some time) but not consistent!

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Logic Pro X internal plugins

#### Device information:

Type of Mac: 2015 Macbook Pro, i7, 16gb Ram
macOS version: 10.13
BetterTouchTool version: 2.310

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
only workaround right now is to disable BTT

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Could you check whether 2.313 alpha fixes this?

**Comment by fKing** [comment]
so far so good! (but it's only been 20 minutes). still, no jumping knobs in LX. will keep an eye on it and report back IF the issue returns.

**Comment by RumplesWrinkles** [comment]
Hi fKing and fifafu. I'm also experiencing this issue in Logic 10.3.2. I'm running the latest BTT (2.313), and would really appreciate a fix for this. BTT is essential to my workflow, including the work I do within Logic. Here's a GIF of the issue - https://gfycat.com/DazzlingPinkFurseal

**Comment by fifafu** [comment]
@rumpleswrinkles are you sure it works when BTT is closed? This should be fixed with current BTT versions, however other apps may still cause it as in the end it's a macOS bug.

**Comment by RumplesWrinkles** [comment]
Hi Andreas,

Yes, I’ve confirmed it works with BTT closed. Not sure what else to do at
this point. I actually had to restart for it to work again, setting BTT to
not open on startup. Disabling BTT in Logic doesn’t seem to do the trick
either.

**Comment by fifafu** [comment]
I'm currently closing some older issues, in case this still doesn't work correctly, please comment again or open a new issue.

I'll have much more time moving forward as I'm now self-employed. I'm sorry I was not able to solve/reply to this earlier.

**Comment by RumplesWrinkles** [comment]
Hi Andreas,

That’s fantastic news, congratulations on becoming self-employed! I can
still confirm this issue within Logic Pro X and BTT. Let me know if there’s
any information I can provide to assist with this issue.
