### ISSUE TITLE
regression: grabbing broken with three fingers track pad in some plugins doesn't let go when grabbing new knob

### ISSUE THREAD

**Issue by Sebastian-blu** [folivoraAI/BetterTouchTool#1631]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
hey this is the same problem I had reported before and had been fixed and is now bugged again in the 2.310 version, if I grab a know or lever in sound toys plugins then grab a new one they both knobs will adjust. 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
track pad

#### Device information:

MacBook Pro
  Model Identifier:	MacBookPro13,3
  Processor Name:	Intel Core i7
  Processor Speed:	2.9 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	8 MB
  Memory:	16 GB
macOS version: sierra
BetterTouchTool version: 2.310

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Could you check whether 2.313 alpha fixes this?

**Comment by Sebastian-blu** [comment]
Yea it is :-) wondering if it would be possible to prevent the touchbar from changing when an audio plugin is open inside of an app like logic or bitwig. As of now it changes to the global settings when I open a floating plugin. 

Barry
