### ISSUE TITLE
[Feature Request] Excluding gestures for custom apps to perform the default action

### ISSUE THREAD

**Issue by hIUG** [folivoraAI/BetterTouchTool#1632]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
So, you can add specific gestures to specific apps, which is awesome. I would like to add exceptions to globally defined gestures.
For example, I have the global gesture "pinch-out"="cmd+c" and "pinch-in"="cmd+v" to copy/paste... But, only on Safari, I want to add an exception for this gesture and make use of the normal behavior for pinching in and out (normal OS zoom behavior).

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Trackpad

#### Device information:

Type of Mac: MacBook Air
macOS version: OS Sierra 10.12.6
BetterTouchTool version: 2.310

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
Right now, I have to disable better touch for current app Safari when I want to zoom in or out with the natural OS zoom in/out feature. Then, whenever I'm done and I want to keep making normal use of the other gestures while using Safari (globally defined gestures) I have to enable back better touch for current app Safari. 

---

...I'm currently paying my license :)
**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by hIUG** [comment]
Maybe this feature would be useful for other users as well.

**Comment by fifafu** [comment]
You can do this by adding Safari to the list of applications on the left side. Then configured the same gesture and assign the predefined action "do nothing / apple default".
