### ISSUE TITLE
[Feature Request] multiple window switching action

### ISSUE THREAD

**Issue by mp3foley** [folivoraAI/BetterTouchTool#1638]
It would be great if the Launch App trigger (Open Application/File/AppleScript) action would cycle application windows if the application was already focused.  This allow switching to an application and then switching/cycling windows of that app all using the same shortcut, rather than the current method of one shortcut to switch to the application and then using CMD+` to switch windows. 

I found this type of feature useful under Ubuntu using [jumpapp](https://github.com/mkropat/jumpapp) assigned to a keyboard shortcuts to switch to commonly used applications and then cycle through application windows.

This is similar to issue #1104, but more general, so please merge them if it makes sense.

**Comment by brantwedel** [comment]
Workaround: If you are comfortable with Apple Script, this example might help you that I posted in #1104 https://gist.github.com/brantwedel/db3f231c6d63ac677972e9be5f90aef6#file-btt-chrome-cycle-tabs-scpt
