### ISSUE TITLE
Old clipboard history not purged

### ISSUE THREAD

**Issue by nathanielcook** [folivoraAI/BetterTouchTool#1641]
#### Description of bug/feature request/question:
I had my "keep items in history for x days" set to 0.8 days, yet I saw stuff in the history from 4 days ago. I have since cleared the history and set it to 0.2 days to see if that helps. But it seems like there is a bug somewhere. Is it possible that it's because the setting of 0.8 days came in via Dropbox sync from another device? (I'm not sure if I set the retention days setting on this machine or another one; it's possible I changed it on the other one and it was propagated.)

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Clipboard Manager

#### Device information:

Type of Mac: MacBook Pro (Retina, 15-inch, Mid 2014)
macOS version: 10.12.6
BetterTouchTool version: 2.310 (687)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
Nothing yet

**Comment by fifafu** [comment]
Mhh, are those old items maybe "starred"? (Starred items won't be deleted). The clipboard manager related settings are not synced.

If that's not it, I'll look into it!

**Comment by nathanielcook** [comment]
No, I didn't star any items at all.

**Comment by nathanielcook** [comment]
Just noticed this happened again. Had to clear manually. No starred items. Retention was set to 0.2 days and stuff was in there from December. This is a security concern.
