### ISSUE TITLE
Not showing snap areas most of the time

### ISSUE THREAD

**Issue by tevyaw** [folivoraAI/BetterTouchTool#1642]
#### Description of bug/feature request/question:
Snap areas don't show up when dragging a window. Frequently have to restart BTT to get them to show. Possibly started since the High Sierra update, or around that time.

#### Device information:

Type of Mac: 2015 MBP 13" retina
macOS version: 10.13
BetterTouchTool version: 2.310

**Comment by sunnyskc** [comment]
Having this issue as well:
Top edge to maximize stops working at the same time as snap area issues

Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Device information:

Type of Mac: iMac (27-inch, Late 2013)
macOS version: 10.13.1
BetterTouchTool version: 2.332(713)
