### ISSUE TITLE
[Feature Request] Right-button-drag support, 2-finger-drag for magic trackpad

### ISSUE THREAD

**Issue by JurekR** [folivoraAI/BetterTouchTool#1647]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Hi, some Apps (e.g. Renoise DAW) require a right-mouse-button push-down while dragging on a gui control. Since the Apple Magic Trackpad has shitty hardware buttons, I like to use two finger touch for right click. But then right-click and holding-down-dragging does not work. Could your software support this?

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Apple Magic Trackpad

#### Device information:

Type of Mac: MacPro
macOS version: 10.12.6
BetterTouchTool version: recent trial 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
This issue was moved to https://community.folivora.ai/t/feature-request-right-button-drag-support-2-finger-drag-for-magic-trackpad/41

**Comment by fifafu** [comment]
Sorry, please ignore the previous message. The migration didn't work correctly, for now the issues will stay here.
