### ISSUE TITLE
GESTURES to Move Window to Next Monitor not working

### ISSUE THREAD

**Issue by Bullets00** [folivoraAI/BetterTouchTool#1650]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
No gestures are working to move window to next monitor. Used to work now does not.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Mackbook trackpad

#### Device information:

Type of Mac: MacBook Pro
macOS version: Sierra 10.12.6 
BetterTouchTool version: 2.310 (687)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

Been a user and big fan of your software for many years, longer than can remember and have witnessed its evolution and continued usability. Not sure why none of my work arounds are not solving the issue. It was working fine just up until about a month ago. Please advise. Thank you and keep up the amazing work.

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by angr76** [comment]
I also have problem with Move To Next Monitor. This used to work back in the days (I've been around for many years), but it stopped working, not sure when. 

Macbook Pro 13inch 2016, running High Sierra.

*Nothing* happens on my "... Next Monitor"-shortcuts. I've tried using the same shortcuts with Spectacle from a tip in another thread here and that works between Monitors just fine. I've tried using different ones etc. 

Happy to share whatever may help to resolve this. 

![screen shot 2018-03-20 at 09 30 23](https://user-images.githubusercontent.com/37574543/37643638-7e5e425e-2c21-11e8-8d20-ce3f0724b7c4.png)

![screen shot 2018-03-20 at 09 32 18](https://user-images.githubusercontent.com/37574543/37643721-c7b7529c-2c21-11e8-92e5-55459ce4165a.png)
