### ISSUE TITLE
[Bug] Memory spikes with BetterTouchToolScriptRunner

### ISSUE THREAD

**Issue by nlpthk** [folivoraAI/BetterTouchTool#1655]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

Random spikes with CPU process. Running two AppleScript widgets on the Touch Bar.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

MacBook Touch Bar

#### Device information:

Type of Mac: MBP Touch Bar
macOS version: High Sierra
BetterTouchTool version: 2.311

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by ValentinJesse** [comment]
I have the same issue. The cpu goes to 100% when firing up 3 simple scripts.

**Comment by fifafu** [comment]
If possible please provide the scripts you are using. Basically BTT just tells the system to execute the scripts, but maybe I can see what's wrong if you post the scripts.
