### ISSUE TITLE
Trackpad corner clicks recognized only sporadically

### ISSUE THREAD

**Issue by Malorkus** [folivoraAI/BetterTouchTool#1658]
#### Description of bug/feature request/question:
I have BTT actions set to trigger on top left click and top right click of the force touch trackpad. The clicks are only recognized by BTT about half the time. The other times it either does nothing or acts like a normal click. The force touch trackpad haptics always make the "click" properly regardless. 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Macbook Trackpad

#### Device information:

Type of Mac: Macbook Pro 13" 2017 with touch bar
macOS version: 10.13
BetterTouchTool version: 2.310 (687)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

Restarting my system does not fix the problem.
I have tested the problem in the BTT "Live View". The corner clicks show the expected visual feedback and are within the proper region of the trackpad, but again, the gesture itself is only recognized in Live View about half the time, consistent with my other experience. Other gestures (e.g. three finger click) are recognized reliably both in daily use and live view.

**Comment by ZV95** [comment]
I would back this issue up as well, it only seems to occur when it wants to... For me this is with the 3D Touch Trackpad from Apple (external) and an iMac
