### ISSUE TITLE
Better Touch tool does not stay running 

### ISSUE THREAD

**Issue by jazzlw** [folivoraAI/BetterTouchTool#1659]
#### Description of bug/feature request/question:
Better touch tool does not seem to stay running anymore.  Usually when I go to use it after a while I notice that it's not running and have to launch it again.  It's not clear to me when this happens, but it seems that if I haven't launched it in a while it's generally no longer running.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
better touch tool

#### Device information:

Type of Mac: Retina Macbook pro 15 inch with touchbar
macOS version: 10.12.6
BetterTouchTool version: 2.310

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

I looked through the console and I couldn't find any crash reports but I might have missed them.

---

**Comment by whitverj** [comment]
I'm noticing the same thing.
