### ISSUE TITLE
I want to specify a key code in the Keyboard Keys list of Trigger Predefined Action

### ISSUE THREAD

**Issue by sawanoboly** [folivoraAI/BetterTouchTool#166]
#### Description of your feature request

Since I want to emulate the key kode (keycode: 104) or eisuu (keycode: 102) key which exists on the JIS keyboard with the key sequence assignment function, I am happy that you can directly specify the key code.

**What kind of Mac are you using?**

MacBook Pro (Retina, 13-inch, Late 2013) US-key layout.

**Which input device
embedded Keyboard.

**Which versions of macOS and BetterTouchTool are you running?**

- macos: 10.12.2（16C67）
- BTT: 1.963(552)

**Other information:**

**Comment by fifafu** [comment]
Good idea, I'll add this!
