### ISSUE TITLE
"NSSQLiteErrorDomain Error 8"

### ISSUE THREAD

**Issue by kmishra9** [folivoraAI/BetterTouchTool#1660]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

Hey there, I get a popup like this any time I start up Better Touch Tool. Any idea what it might be? For reference, this is a new computer restored via a Time Machine backup after my original computer was stolen. Still, Time Machine essentially restores this to be the exact same state as the original computer so I'm wondering what the issue could possibly be.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Functionally, the touch bar works just fine with the settings I've set... there don't seem to be any issues. However, sometimes up to 7 of these messages will "spam" my screen and I'll need to exit out of them by clicking "OK". Nothing actually seems to be disrupted though...

#### Device information:

Type of Mac: 15" Macbook Pro (2017)
macOS version: 2.310 (687)
BetterTouchTool version: 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

Screenshot:
![snip20171024_1](https://user-images.githubusercontent.com/10662252/31971216-ad3ef99e-b8cf-11e7-9603-f3725ba893c8.png)

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by lifecube** [comment]
I also have the same error, after using migration assistant to restore from time machine from my old macbook to a new macbook with touch bar.
