### ISSUE TITLE
[Request] Chrome TouchBar YouTube Player Support

### ISSUE THREAD

**Issue by dariusdubreu** [folivoraAI/BetterTouchTool#1663]
Hello! 

Is there a possibility to control Youtube Player in chrome from touchbar (like in Safari for example) using BTT? 
Thanks a lot!

**Comment by MrJarnould** [comment]
I'd be interested in this as well.

**Comment by fifafu** [comment]
Unfortunately this is very unlikely to happen in BTT as I can't get such deep access to an application. I think this must be done in a Chrome extension or similar.
