### ISSUE TITLE
EarPods Actions

### ISSUE THREAD

**Issue by pallavmac** [folivoraAI/BetterTouchTool#167]
#### Description of your feature request:
Would it be possible to have an action so that pressing the play/pause on the EarPods activates the play/pause actions such as the one on the function row/touchbar? Because pressing the play/pause on the earphones currently only controls iTunes. But if spotify is open then it does not get controlled by the earphones. If this isn't possible then no problem - you can close this thread.

**Comment by fifafu** [comment]
Yep, I'll look into that!

**Comment by queuebit** [comment]
👍 I came here looking for this too.
I am often watching Netflix or Amazon Video in Chrome and want to map the button to spacebar to pause, and instead it just opens up iTunes :(
