### ISSUE TITLE
[Feature request] 'ignore areas' on side of Magic Trackpad to avoid accidental palm

### ISSUE THREAD

**Issue by sohocoke** [folivoraAI/BetterTouchTool#1670]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

With my iMac I use a Magic Trackpad placed under my keyboard's space bar, to mimic the position of a built-in trackpad on my MacBook. I used to have the trackpad inverted prior to Sierra, and now use the the 'mirror' option in BTT. Here's a picture: https://www.dropbox.com/s/n9iistjgukk53cg/IMG_1995.JPG?dl=0

I would love to set up some 'ignore areas' on either side of the trackpad, since despite the 'ignore palm' option, I still get accidental clicks when my palm touches the sides of the trackpad while I type.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Magic Trackpad

#### Device information:

Type of Mac: iMac 27" (Retina)
macOS version: 10.12 Sierra
BetterTouchTool version: Latest release version

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by toinbis** [comment]
+1
