### ISSUE TITLE
BTT cannot read Magic Mouse battery level (reports 0%)

### ISSUE THREAD

**Issue by benface** [folivoraAI/BetterTouchTool#1672]
#### Description of bug/feature request/question:

In the "Mouse" tab (advanced mode), I checked "Warn if battery level is lower than" and selected 20%. I had no notification when the battery level fell below 20%, and I'm now at 12%. Furthermore, I can see that BTT doesn't actually know the current battery level because under the checkbox, it says "Current battery level: 0%".

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Wireless Magic Mouse

#### Device information:

Type of Mac: MacBook Pro (Late 2013)
macOS version: 10.13
BetterTouchTool version: 2.311

Thank you!

**Comment by geraldcor** [comment]
I too am affected by this:

MacBook Pro (Retina Mid 2015)
macOS 10.12.6
BTT Version 2.318

Thanks

**Comment by Troglos** [comment]
Same problem here
"Current battery level: 0%".
High Sierra 10.13.2
Mac mini (Late 2014)

Before I buy it I want to be sure it works

**Comment by ianhallsg** [comment]
Same for me.
MacBook Pro (Retina, 13-inch, Early 2015)
High Sierra 10.13.2
BTT Version 2.320

**Comment by zyumbik** [comment]
I'm having the same problem. Also, the system message about low battery doesn't appear and my Magic Mouse just silently turns off when it runs out of battery. When this happens I have to stop in the middle of what I'm doing and wait for the battery to recharge.

iMac 27" Mid 2011, macOS 10.13.3

**Comment by fifafu** [comment]
Hey,

this will be fixed soon!

**Comment by msemp** [comment]
I've seen several recent updates to BTT, but no specific mention of battery level for the MagicMouse 2. Is this perhaps fixed, and I just haven't realized it? If so, I'll be buying! (But my trial period has run out, so I can't simply try it myself and see.)

**Comment by zyumbik** [comment]
Still doesn't work with my Magic Mouse (not 2). BTT 2.426.

**Comment by SannePetersNL** [comment]
Still doesn't work here. Newest version of BTT. 2.530 MacOS Sierra.

**Comment by poxley** [comment]
The only reason I purchased BTT was for this feature. I figured I'd play around with some other settings (several months later, I still haven't), but I decided it was worth the cost just to know before the last minute that my mouse needed charging. This is really frustrating!

**Comment by SannePetersNL** [comment]
Why is it closed?

**Comment by fifafu** [comment]
The BTT issue tracker has moved to https://community.folivora.ai early this year and all issues here have been auto-closed now. In case you still need help with this issue / feature / question please create a new post there.
