### ISSUE TITLE
[Feature request] Remap simple click with modifier key

### ISSUE THREAD

**Issue by champagnealexandre** [folivoraAI/BetterTouchTool#1675]
#### Description of bug/feature request/question:

I notice I can't create any trackpad gesture with only the "click" action + a modifier key (e.g. Command). That would be helpful for instance to create a gesture where trackpad click + Command would trigger Middle Click. Right now I only seem to be able to map parts of the trackpad with the click gesture (top right, etc.)

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

MacBook Trackpad.

#### Device information:

Type of Mac: MBP 2013
macOS version: Sierra
BetterTouchTool version: Latest

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

None.

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by tb87** [comment]
Have you had time to look at this? I don't think it would take much time to implement.

Thanks! :-)
