### ISSUE TITLE
[Feature request] Searchable shortcuts

### ISSUE THREAD

**Issue by waxfingers** [folivoraAI/BetterTouchTool#1681]
At least in my case - but  I suspect I'm not alone - there are just too many shortcuts/gesture/sequences. It would be neat If I could search for them in a programmatic way. It could be just one general search input space (window) where further discrimination (i.e. per application, description /notes) could be done through words or better simple tags (then shortcuts and other assets would have to be taggable). Hitting on the search's return could "take me there" and scripts/apps used could also be searchable. Ideally but probably irrealistic is a GUI where both text search and visual one, not dissimilar from the one's editing platform have

![](https://support.apple.com/library/APPLE/APPLECARE_ALLGEOS/Product_Help/en_US/PUBLIC_USERS/133280/S1800_CommandEditor.png)

Cheers

**Comment by blizzrdof77** [comment]
This would be great. I think more often than anything, I find myself trying to track down a global shortcut I set accidentally. 

As an example, a few days ago I realized I had "Alt+F2" assigned to open my notification center (instead of increasing my brightness). It took me a few minutes to track down the gesture causing it (and another 30 minutes to search Github and create this mockup), but being able to search by gestures would have been useful in this situation - as well as many others 😃 .

In any case, as enticing as that example GUI image is @waxfingers - I put together one that might be a bit more practical for @fifafu to implement in the existing UI. Anyways, thank you both (@waxfingers for the great feature request and @fifafu for - well, obviously an amazingly useful app that I simply couldn't live without)!

![image](https://user-images.githubusercontent.com/890252/37559367-fd539394-29fa-11e8-8f87-c6d7e546e476.png)

**Comment by waxfingers** [comment]
@blizzrdof77 I'm a bit of a megalomaniac, specially regarding the work of others :P 
**Your proposal is more than enough GUI wise**. The search capabilities is what seems more important.    
Ideally, search would not be constricted by app, (much faster problem solving) unless the specific app was tagged/called/indicated so. There's another big incentive for ALSO adding tags to a searchable database, and I mean BTT's own inner simple tag system, and that is to stop wasting time organising shortcuts, gestures, etc around somekind of messy visual logic. I, myself had previously (https://github.com/fifafu/BetterTouchTool/issues/1654) asked for the ability to group the shortcuts, but it is clearer now, that is a solution to a problem. If a simple enough fast tagging system could be implemented together with a little search engine I believe the whole shortcut managing, problem solving, locating and even referencing would not even become a problem.

Of course this is purely theoretical and just my opinion 🦄; personally I'm keen on text cues or tag based hierarchies that can be organized in a simple and fast way and give some audiovisual feedback. That's why I heavily use flashlight (spotlight's capabilities extension with hundreds of plugging through code injection)  and BTT and for instance CommandPost to assist in video editing. 

 _ _ _ _ _ 
 _ _ _ _ _ 
Just talking about spotlight it came to mind another good example. If one uses a key sequence to trigger an action (let's say I type `command+m+p+v+c+o` to open mpv's config file in an editor), chances are that it's going to disturb some running application (i.e. the Finder), the "delete typed characters" and "perform cmd+z" are solutions to a problem that it could be obliterated for good if a simple text box was called and then insert the key sequence... which (if wished so) could become a more "natural caller" ("edit mpv conf") << and that I would never have to remember 'cause it'd be what I wanted to do in the first place; action=trigger. I'm aware that these are the ways of alfred, launchbar, cerebro, zazu, etc. I have used them and much preffer how BTT is simpler to set up but it can also quickly assemble very complex workflows. Even if BTT does not ever implement something like this, maybe itT could be summoned say through spotlight , where one would type the (example) sequence which then would be send back to BTT.... I digresssssszzzzzz

 

Sorry for long diatribe. **Thanks for taking the time to put a nice GUI example together**

**Comment by waxfingers** [comment]
I've moved request to folivora forum, closing this

**Comment by blizzrdof77** [comment]
What's folivora forum @waxfingers ? Could you provide a link?

**Comment by waxfingers** [comment]
Sure thing @blizzrdof77 
https://community.folivora.ai/t/consider-adding-search-to-shortcuts/2032/2
