### ISSUE TITLE
[Feature Request] Touchbar widget applescript text return - Auto-scroll/Ticker for RSS news feeds

### ISSUE THREAD

**Issue by tojoleon** [folivoraAI/BetterTouchTool#1685]
#### Description of feature request
My objective is to get a functioning RSS news feed ticker on the Touchbar

I would like to request the below feature for the Touch Bar widget -> Apple script return
      1)  **Auto scroll the return** from applescript like a news ticker if length the text returned is more than the allocated width of the widget on the Touchbar
      2)  **Adjust Font color of the return** on the Touchbar

#### Device information:
Type of Mac: **MacBook Pro Touch Bar 2016**
macOS version: **macOS High Sierra**
BetterTouchTool version: **2.311**

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
Please check the below link to a RSS Touchbar project which has implemented the ticker functionality to RSS feeds. 
https://github.com/a-yasui/RSSTouch

I have an AppleScript that return pending headlines from Vienna to test the same -

```
set messageList to {}
tell application "Vienna"
	repeat with pendingMessage in (articles of current folder whose read is false)
		tell pendingMessage
			--get sender's name
			set senderName to author
			--if there is no name, or the address line is malformed, better to show just the address
			if senderName is equal to author then
				set senderName to author
			end if
			
			--mark flagged messages specially
			if pendingMessage is flag then
				set bullet to "» "
			else
				set bullet to "• "
			end if
			
			copy bullet & senderName & tab & title & linefeed to end of messageList
		end tell
	end repeat
end tell

messageList as text

--currently using the below in absence of the ticker function on the TouchBar
--set t to some item of messageList as text
--text 1 thru -2 of t
```

**Comment by araa47** [comment]
Would be great if this could be implemented or if anyone knew a way I could create the effect myself on BTT to make my touch bar look more like a news ticker where it auto scrolls allowing me to read all the information.
