### ISSUE TITLE
[Feature Request] Apple Watch App

### ISSUE THREAD

**Issue by TaylerUva** [folivoraAI/BetterTouchTool#170]
It would be really nice if a companion app was created for the Apple Watch similar to the iOS app. I would find this even more useful as the watch is always on my wrist. Even if it just had the same functionality as the iOS app it would be super useful. Thanks and keep up the great work!

**Comment by fifafu** [comment]
Late Update:
Apple Watch App for BTT Remote will probably be released in March :-)

**Comment by fifafu** [comment]
This issue was moved to https://community.folivora.ai/t/feature-request-apple-watch-app/91

**Comment by fifafu** [comment]
Sorry, please ignore the previous message. The migration didn't work correctly, for now the issues will stay here.

**Comment by Malauch** [comment]
Hi, is there any update in that matter? It would be very nice feature to have BTT remote on Apple Watch.
