### ISSUE TITLE
Snap Areas Flickering

### ISSUE THREAD

**Issue by Claywd** [folivoraAI/BetterTouchTool#1707]
#### Description of bug/feature request/question:
The snap areas are flickering like crazy when dragging windows around on the screen. 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Screen

#### Device information:

Type of Mac: Mac Pro 5,1
macOS version: 10.13.1
BetterTouchTool version: 2.313 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
Using a AMD Vega 64 8Gb Limited Edition GPU, and nVidia GTX 980. It happens on both used separately.

**Comment by fifafu** [comment]
Unfortunately I don't know what is causing this. Apparently it only happens with some specific GPUs, thus it seems to be some sort of driver issue but I do not really know yet.

I can add an option to don't use the GPU accelerated rendering, but this would make the animations less fluid :-(

**Comment by Claywd** [comment]
what framework is it using for GPU accelerated rendering? 

I'm wondering because Apple invested heavily in graphics creating Metal and Metal 2 to ultimately replace OpenGL on the mac in the long run. If you're using OpenGL, maybe they depreciated the method your using and its a simple case of updating the framework and library. I don't know enough about graphics to be extremely helpful but this didn't happen as bad before Apple made all this graphics development stuff lately. 

When the snap areas appear the whole screen literally freezes and glitches out for a moment like its playing catchup. weird.
