### ISSUE TITLE
No option for 1 Finger double-tap

### ISSUE THREAD

**Issue by NewHere17** [folivoraAI/BetterTouchTool#1717]
Description of bug/feature request/question:
I don't find 1 Finger double-tap very helpful.
However, I don't see an option to select 1-finger double tap. Is it there and I just don't see it?

Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Built-in force touch trackpad

Device information:
Type of Mac: MacBook Pro 2017 edition
macOS version: 10.13
BetterTouchTool version: 2.313

What is the correct option, to start something with a click (f.e. with two fingers or three fingers) equal where on the trackpad the click is?

**Comment by fifafu** [comment]
Hey,

what exactly do you want to do? Do you want to use the double-tap to drag? This can be enabled in System Preferences => Accessibility => Mouse & Trackpad => Trackpad Options

**Comment by NewHere17** [comment]
Hi,

it would be great, with the  1 finger double-tap over the dock to minimize the active window.
Additionally, it is equal where on the trackpad the tap is. The whole trackpad activates these feature.

**Comment by ruslaniv** [comment]
Came here looking exactly for this! Could this (1 finger double tap) be possibly implemented?

**Comment by NewHere17** [comment]
I need the feature still.

**Comment by NewHere17** [comment]
hi,  why is it closed? i didn´t find the option in version 2.660

**Comment by fifafu** [comment]
The BTT issue tracker has moved to https://community.folivora.ai early this year and all issues here have been auto-closed now. In case you still need help with this issue / feature / question please create a new post there.
