### ISSUE TITLE
BetterSnapTool - Multi-Monitor custom areas flashing and unresponsive for 3-5 seconds

### ISSUE THREAD

**Issue by fjaxyu** [folivoraAI/BetterTouchTool#1718]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
So I have a MacBook Pro with 2 external monitors connected with the custom snap areas feature on each of them. There are three on the first, two on the second, and one on the third. 

When I go and move the windows to a snap area, all of the snap areas will flash and I'm unable to move the windows (this doesn't happen every time, but most of the time). if I let go of the window, the snap areas are still there and still flashing and I simply have to wait in order for them to disappear. Eventually, when I try again (usually the second time works) it will let me snap the windows as expected.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Multiple Monitors (haven't tested this without the extra monitors).

#### Device information:

Type of Mac: MacBook Pro (Retina, 13-inch, Early 2015)
macOS version: 10.13
BetterTouchTool version: 1.8

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
I've also noticed that this happens when I'm working and have a number of programs open. Chrome, Webstorm, Terminal (with Node running), Numbers, and iTunes are what I have open on a regular basis. Checking the Activity Monitor, it tells me that I've got 6.42 gb of 8.00 gb of memory used. CPU usage is at about 20% used.

*I also don't remember this happening before 10.13.*

[Here's a link with a video that will show what is happening](https://youtu.be/5UNhLCFkyio). This is a video of only the center monitor, the largest one, where it seems to occur the most (because that's where most of my attention takes place).

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
That's very weird. Is there anything special about your displays? How are they connected?

**Comment by fjaxyu** [comment]
###Main Display###
This is monitor displayed in the video
Connection: HDMI connected with a thunderbolt display adapter
Monitor: HP 27er

###Second Display###
Still happens on this monitor
Connection: HDMI connected to the built-in HDMI port
Monitor: HP 22er

I would say that it more frequently happens on the external monitors. I'm not sure I've really noticed it on the main laptop display, but I can't say for sure. Some testing (for a minute or so) led me to believe that it doesn't happen on the built-in laptop display.

**Comment by sthilaire** [comment]
I have this behavior also.  The snap area indicators will stay after the mouse is released, or flicker when the mouse button is held down.  Re-starting BTT and it is still repeatable.

**Comment by fjaxyu** [comment]
So I've noticed, just recently, that I can make the squares responsive if I hold the window inside of the flashing area and wait until it becomes solid. Once it becomes solid, I move the window out of the square and then back in and it will snap!

**Comment by howardcrut** [comment]
I have same frustrating behavior. Two external monitors connected to MacBook Pro (Retina, 15-inch, Late 2013). macOS 10.13.3. Graphics: NVIDIA GeForce GT 750M 2 GB Intel Iris Pro 1536 MB
BST: v1.8

**Comment by fjaxyu** [comment]
Personally, I've noticed this happen more often than not with a JetBrains IDE open. I've used Webstorm, PhpStorm, and DataGrip and it seems to happen when one of them is open and I try to move that window specifically. It does it with other apps (like chrome, or terminal), but it doesn't seem to last as long as the IDE.

**Comment by marcuspolk** [comment]
Experience this as well very frequently. System: OSX 10.13.3, 4k display via thunderbolt 2 > displayport.  Usually it lasts 3-5 seconds but had a particularly bad case of it earlier today. Froze my entire mac for > 1 minute. Couldn't use force quit, had to quit from activity monitor. While it's frozen i can still move windows around, but can't do anything with the content of the windows. Scrolling them over the boxes as mentioned above does not always fix it for me. Very fast flickering.. All over the screen. I  have 24 custom regions (4k monitor makes BST is necessary)

**Comment by howardcrut** [comment]
Any progress on providing a fix for this? It does not matter what programs I have running, it happens 99% of the time when dragging any window from one monitor to the other. (I do **not** have JetBrains IDE, Webstorm, PhpStorm, or DataGrip.) Seems like the same issue (#1827) is reported here, too: https://github.com/folivoraAI/BetterTouchTool/issues/1827
