### ISSUE TITLE
Maximize Window to Next Monitor

### ISSUE THREAD

**Issue by Calange** [folivoraAI/BetterTouchTool#1720]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

When I use my shortcut to "Maximize Window to Next Monitor" the window is not completely maximize on my macbook screen.

My second monitor is a Samsung S27D850 it is connected with Display Port on a belkin dock that is connecter with USB-C on my macbook.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Keyboard Shortcut

#### Device information:

Type of Mac: MacBook Pro 13-inch, 2017 (MacBookPro14,2)
macOS version: 10.12.6
BetterTouchTool version: 2.313

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

Workaround : when I launch for the first time an application, the shortcut work correctly but when I use it again the window is not completely maximize on my macbook screen (work fine on my Samsung monitor).

<img width="775" alt="capture d ecran 2017-11-09 a 10 44 44" src="https://user-images.githubusercontent.com/29873186/32598858-14470416-c53b-11e7-9302-db2b7e2e32a2.png">

<img width="1680" alt="capture d ecran 2017-11-09 a 10 41 39 2" src="https://user-images.githubusercontent.com/29873186/32598875-1e8205de-c53b-11e7-92c4-8c20c4b14307.png">

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Thanks for reporting! I'll try to reproduce it on my machines.
