### ISSUE TITLE
OpenOffice Draw crashes on Click-Drag with BTT on, doesn't with BTT off

### ISSUE THREAD

**Issue by ranjoh** [folivoraAI/BetterTouchTool#1722]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
New user.  Please be gentle.

Environment:
iMac (Retina 5K 27-inch, 2017)
Corded USB Mouse and Keyboard
MacOS Sierra Version 10.12.6
OpenOffice Draw, Apache OpenOffice 4.1.3
BetterTouchTool Version 2.313 (691)

I launched BetterTouchTool.  OpenOffice Draw will immediately crash to a bug report screen on the first pixel of drag on any left-click and drag.  I have tried all the tools.  Line, circle, rectangle.  I can left-click, but then with the first pixel of drag, it crashes.

I quit BetterTouchTool.  OpenOffice Draw works as expected.

#### Device information:

Type of Mac:  iMac (Retina 5K 27-inch, 2017)
macOS version: MacOS Sierra Version 10.12.6
BetterTouchTool  version: 2.313 (691)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Unfortunately that's a bug in Open Office then. However you should be able to disable BTT just for Open Office by clicking the BTT menubar icon and selecting "disable for active application"(it will remember that decision)

Probably Open Office doesn't handle an API that BTT uses correctly.

**Comment by ranjoh** [comment]
Thanks.  I was already planning to do this.  Apache is aware of this as I have sent four crash reports with my notes.  The last one was the found combination of Draw and BTT.

While I have your attention, I have a question about setting up a mouse action that isn't working correctly even after multiple attempts.  Trying to do a center-wheel click as a Universal No-Op without much success.  What is the proper forum in which to bring this up?

Randy
