### ISSUE TITLE
Issues with Snap Areas on High Sierra

### ISSUE THREAD

**Issue by mcamou** [folivoraAI/BetterTouchTool#1725]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

I have a couple of problems after moving to a 2017 MacBook Pro and adding a third monitor. I am attaching a [screen recording](https://github.com/fifafu/BetterTouchTool/files/1461106/BetterTouchTool.mov.gz) which will hopefully show them.

1. There is a specific Snap Area which is in my middle monitor. When dragging into it, the window snaps to the left monitor (which is vertically smaller) and back, which makes it vertically smaller than the drag area. Using a hotkey to move the window to the proper place works correctly.  Other snap areas don't seem to have that problem.

 In the screen recording this shows up as the window blinking for a moment, but it's actually appearing momentarily in the other monitor. The snap area does not show on the screen recording because it's on the left half of the menu bar.

2. In some cases, dragging a window to a Snap Area will not move the window to the proper place/size, and will also leave the Snap Areas overlay on. Clicking on any other window doesn't clear up the problem. The only thing that seems to clear the overlay is clicking on the desktop. Trying again after that will usually fix the problem.

3. Performance is very sluggish (i.e. Snap Areas take too long to come up).

4. If I move a window to a Snap Area, then move it elsewhere, the window does not keep its size, the size goes back to whatever it was before snapping.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

All mice/trackpads (this happens when dragging onto a Snap Area)

#### Device information:

Type of Mac: MacBook Pro 15" 2017
macOS version: 10.12.6
BetterTouchTool version: 2.313 (691)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

See [screen recording](https://github.com/fifafu/BetterTouchTool/files/1461106/BetterTouchTool.mov.gz)

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Hey,

could you go to the About tab in BTT and click the "Export Debug Information" button? This will create a folder called BetterTouchToolDebug on your Desktop. If possible please send the contents to boastr.net@gmail.com

Maybe I can see what's wrong then.

**Comment by ftrotter** [comment]
I am having the same problem. 
It flashes to the "right" second monitor. Then back the "left" third monitor (which is where the snap area is) and then appears in the right place on the "left" monitor, but way to short.

**Comment by mcamou** [comment]
@fifafu just sent the debug info, I hope there's something useful there. Please ping me if there's anything else I can do.
