### ISSUE TITLE
Custom Touchbar slider sending MIDI CC feature request

### ISSUE THREAD

**Issue by childrenof9** [folivoraAI/BetterTouchTool#173]
Feature request:

Would be great to create custom sliders in the touchbar so I can use it as a controllor for music apps like ableton/cubase. Would be handy if It can send MIDI CC! :)

**Comment by aaronweewee** [comment]
I TOTALLY AGREE  it would be amazing if it could do that. It would make playing live alot more intresting

**Comment by childrenof9** [comment]
Indeed, can you imagine: evert plugin an unique slider or 2, directly on the touchbar :o

**Comment by childrenof9** [comment]
Ah didn't understand that a feature request was something the developer made... 

hope it will be possible though to add midi cc's :)
