### ISSUE TITLE
TipTap gesture unresponsive with more than 1 fixed finger

### ISSUE THREAD

**Issue by Suavatore** [folivoraAI/BetterTouchTool#1732]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
When using the TipTap gesture with more than one fixed finger, the gesture is often not recognised (roughly 1 out of every 3 taps is recognised). The normal TipTap (1 Finger Fix) works perfectly, however.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Trackpad

#### Device information:

Type of Mac: MacBook Pro 2017 
macOS version: High Sierra
BetterTouchTool version: 2.313 (691)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
There is currently an issue where the fingers need to be spread quite a bit on the new bigger trackpads. This will be fixed with the next update.
