### ISSUE TITLE
Conflict with Steermouse app

### ISSUE THREAD

**Issue by sj1233** [folivoraAI/BetterTouchTool#1734]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Logitech m510

#### Device information:

Type of Mac: MacBook Pro 
macOS version: Sierra 
BetterTouchTool version: 2.313

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by chessisamazing27** [comment]
I have also noticed this issue while using steer mouse. With BetterTouchTool activated, many of the chording functions fail to work properly often not having buttons jam where one button in the chording seems to activate the whole chording even if it is not pressed.

**Comment by fifafu** [comment]
Unfortunately I don't think this can be fixed. It's a general issue with macOS that sometime happens when multiple apps use the same way to intercept events.
