### ISSUE TITLE
Unreliable Three Finger Click as Middle Click for Opening Links in New Tabs

### ISSUE THREAD

**Issue by proactivematter** [folivoraAI/BetterTouchTool#1739]
#### Description of bug/feature request/question:

So, I came from a desktop and was used to using the **middle click** on my mouse for **opening links in new tabs**. I configured **three finger clicks** to act as **middle click**, but - sometimes it works, sometimes it doesn't, and, worst of all, _sometimes it does but besides opening a new tab it will also act as a normal click, so I'll have 2 pages showing the same content_.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Macbook 15" 2017 Trackpad

#### Device information:

Type of Mac: Macbook 15"2017
macOS version: 10.13.1
BetterTouchTool version: 2.313 (691)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

Had previously also configured 3 finger taps for this function and it was even more problematic.

Thank you. Cheers!

**Comment by fifafu** [comment]
Maybe try disabling thumb handling in the advanced BetterTouchTool preferences. In general the three finger click & tap  should be one of the most reliable gestures and I haven't had many issues with it yet.

**Comment by wirhabenzeit** [comment]
I have exactly the same problem. I could imagine that it is related to the 10.13.2 beta. 

The live view does not show anything strange but I guess the two three finger tap events occur almost almost at the same time so that they can't be distinguished in the live view.

**Comment by proactivematter** [comment]
Hey Fifafu. I tried disabling thumb recognition, but it didn't work. But I think I've found out just now a crucial point to this issue. You tell me, see if it's of any use to you...!

When I press+depress for a 3 finger click (without removing the fingers from the trackpad), the link will open on a new tab normally; It is only after this, when I lift off my fingers off from the trackpad, that the page I am currently on will also act as if I had simply clicked on the link.

Step by step:

1.) Place cursor on top of link
2.) Remove finger
3.) Place 3 fingers
4.) 3 finger click  >>>   link opens in separate tab
5.) Remove fingers   >>>   current page also "clicks" link

Thanks again! Loving BTT more every day!

**Comment by fifafu** [comment]
Mhh I'm still unable to reproduce this :-( 
Does BetterTouchTool have the permissions in System Preferences => Security & Privacy => Accessibility?

**Comment by fifafu** [comment]
Do you have any other mouse or keyboard related tools running? It's possible that something is conflicting with BTT.

**Comment by proactivematter** [comment]
I do not. I don't use any other interface / input software either, only BTT.

Quick off-topic: I really can't praise you enough Andreas. I was playing around with custom window snap areas for the first time just now and wow... so awesome, so many options! You blow my mind...

**Comment by fifafu** [comment]
Thanks! :-)

It would be great if you could go to the about tab in BTT and click the "Export Debug Information" button. This will create a folder called BetterTouchToolDebug. If possible please send that to boastr.net@gmail.com and reference this issue, it may help me figure out what's wrong because I'm still unable to reproduce it here :-(
