### ISSUE TITLE
Touch Bar App Switcher Changes

### ISSUE THREAD

**Issue by erod998** [folivoraAI/BetterTouchTool#1742]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Whenever I use the touch bar app switcher widget, it doesn't show the same open apps as the OS one. Whenever I use Cmd+H to hide an app, the widget no longer displays it. Also, when trying to switch to fullscreen apps the widget does not always do it. I see this sometimes with having a icon in the Touch Bar with the action set to open a specific app. Maybe it is intended to be this way in terms of the app switcher, but is there any way to make it display the same apps in the OS switcher? Also, is there a way to lessen the amount of space the icons have between each other in the Touch Bar? Just too much space for me. 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Touch Bar

#### Device information:

Type of Mac: 2016 MacBook Pro
macOS version: 10.13
BetterTouchTool version: 2.313 (691)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by vockleya** [comment]
I'm running into this same issue at the moment. It seems that the touch bar app switcher doesn't show any programs that have been hidden using cmd-h. If this is intended behavior, it would be great if there could be an option to show all open programs, instead of just non-hidden ones.
