### ISSUE TITLE
TipTap gestures only work during first minutes

### ISSUE THREAD

**Issue by nmaxcom** [folivoraAI/BetterTouchTool#1744]
Well, pretty much what it says in the title.

I have plenty of keyboard configs and some with the trackpad. I have 2, 2 finger tiptaps and another 2, 4 finger drags. The tiptaps are the nightmare here and what stops working.

These trackpad tiptaps gestures usually don't work. To make them work I have to quit and reopen the app, and then they work flawlessly.

The live view responds exactly as the system (when gestures work, they are correctly identified in the live view and the opposite).

This goes well for a few minutes, 5 to 10 and then it stops working so I go to square 1. And like I said, for some reason, the other two 4 finger drags that I have, work flawlessly, in the same trackpad.

#### Device information:

Type of Mac: MBP 15" 2017
macOS version: 10.12.6
BetterTouchTool version: 2.310(687)

**Comment by fifafu** [comment]
Weird, could you please go to the about tab in BetterTouchTool and click the "export debug information" button?
This will create a folder called BetterTouchToolDebug on your desktop. If possible please send it to boastr.net@gmail.com

**Comment by nmaxcom** [comment]
I couldn't examine the information inside the WAL file. It's either password protected or somehow invalid.

Which is it? I can't just send away a file that I don't know what information it has.

**Comment by fifafu** [comment]
All the files combined. They contain the whole BTT setup, BTT logs and license information. In order to debug this I'd need all of them so I can replicate the exact same setup.

**Comment by nmaxcom** [comment]
Excuse me,  but you didn't answer my question at all.

Like I said, I was able to check all the files except the before mentioned.
But when I tried examining the *.v2-wal file through a sqlite interface
(exactly as I did with the other dB file) I was prompted for a password.

Again, you can't expect me to send logs from my computer without me making
sure what's in them.

So what is the password?

**Comment by fifafu** [comment]
There is no password. These are files generated when you create a core data database using sqllite. The WAL files are for write ahead logging (https://www.sqlite.org/wal.html)

**Comment by nmaxcom** [comment]
I'm aware it's a WAL file, hence saying it was password protected or somehow invalid/corrupted.
I did check it with my friendly hex editor and tried out some grammar but still there were important chunks I couldn't see.

But oh well, give me any public key of yours and I'll send you the logs under the agreement that you'll use any and all information contained in the logs for the only purpose of software development.

**Comment by fifafu** [comment]
```
-----BEGIN PGP PUBLIC KEY BLOCK-----

mQINBFoRfy4BEADUTQpdbKfa57eN2MblsSlUy1LN1y6ZnUEN+leNtTfMQo2eoFKk
HibW2Dvviy/bZynEP29XLWmolMl1y4nrrosJJ/vcS+XoPHPZZRcRyiGAsuHnlm1U
Imjo8Ra7llxLEZs1L/I5oma72yYbcJFZ3qtjWpwlU9cnuexbpOhm5Wjy8xSFH/mC
esdeiEBf8mR0HWr989qLYhWqnNqewq9kB9OIAgm1/zvGiHwRxW21TMPD18/AM7Hg
ZwscttvWuYqE5fSs3pXhxPo/51UcGcFx/1rSlJGe/a0qFyJVPegFxiCCR6HD6My0
ryGJ0sBkpuXnteJVXNEwuqRlFqGXZ+BHZgwgz1wVAIPzE2hwgOHAriF1Vf0W+P7S
Alvzd1QcBcsWmg5Yxkf3ZJZHNoPlfgl7l/KnSp0i9rbIFnySPVTrzThYoepyw+f5
SfZCoAG4qD0nKXRsIuBbjtqJtWNtJmx/22/y7trCHrptu2hmQRnMHCB9gsaRXx11
279crO7n6zfSwFJGS0KH8vmUMrOUxNw4f+zQaMgghTuBObR5aCyZri+MVEqOE+3c
P+jq9Xybm0u8kD3w2TZpe/xxxmLMRgbZ+Fk/VBNj8U/+1r+bcKx/GGaP+jGEoPeD
B8bmsRfDAo4tijbfGwdrWHcZ3wN8mbFYBOt7jPBf0YwQEUmzZS68atmS/wARAQAB
tChBbmRyZWFzIEhlZ2VuYmVyZyA8Ym9hc3RyLm5ldEBnbWFpbC5jb20+iQJUBBMB
CAA+FiEEyK0qTCQMqFwnnyezmmMclDh/SrcFAloRfy4CGwMFCQlopIAFCwkIBwIG
FQgJCgsCBBYCAwECHgECF4AACgkQmmMclDh/SreYLhAAzY4dLop1lRVsI1Ml8POy
Pav00wEi/lquXL//TSGEdTspebZztWjzzGtFwOkN43N+J8FSRLCBcLlJYlLfKoCC
3XQD0NSmMVsfvS0SIX2I7RG6PmEnkgCkpGtEhU9VkpjsR8HtOiib37g1vq0yLuX8
V5n/DFMiGhFumkdi22Vd3u/H+fX7IVU0b2ve0BTHdDOzyQ+PQtNhipPZE8AX3Uxd
G29ABRqVDbfeiGwiluckZ/cmIidss8PJN6wHjjuBXJtBOr5uLCPOHn3sISOw2ywo
7HKcp5xRDgIyBm6cneG93YgiwgGocF3f02zwFhDcHe48BhiNrZDprfVv/9xiPbD0
mVJz5beUK55ILMOU9vYcgEVB082hMNpYhz1I5xZMY6Zz6nGi1y4aEBOQBT0opQIF
BXEm8W0ZXV2yAanMvbGCDCGEdyAXH8GAzXBsrHCJEVN2YdF9gOjUcWbuTrg3FIS0
32n96f01OKNjx57Ihm6uiRsSTtloFqdrPLWyu1no411Uc/DNaXkzG5UnyQimET+A
loZAvCGxdV4U8v6dSr43j8u2tCEVSfULFEn559dLd4udYMLGsOJAa4Uc3qqjZCow
GaT2HPOHBf6b/QgNmYQ05Zbng6PHpmTJO+vtx5lllEpRZMv+E+ikF4uU1x5/cmYA
pxgqP/plMAsxaJCLexyEyHm5Ag0EWhF/LgEQANgUffPISwOinfPgS8Yhp9Dvn67Y
b844w3Dc2ywbe1+/CFuEDSSh29rDJI1pV5YhzhpQLv9XS89zmHWOTxojQ3BNw6bl
vqMxwUbTCYe2Q5izJGXXtq6ha/oMfMR3hv2DWg7WO6whzMiXhfMm8bzMwuCRnL0N
ssDSec9mSrmGtS1EvZzv30wNNylPNlBjG9aIK97cEwXyW/dFIP97+KfJT/P3v3XF
GO2amYwH3RGnMcXcVLF7KAhmhl93OI1YN/gP2zp0dc11B6ZHXXBlbwmc2cyNqh4n
lImcH8XTSzciWAZtYkEBCCsbTKoONL8nTD84wPnxdkkDDj0mecCDYq0htigrtwEZ
10MItd9b3J3DsUwjyUZWyJDSrz34TKRYmZpEyk8Hp4Fxnw86aZV7kWNcdtrhpBnh
uMXanmkX/m3/SUvWFcDar4S5Ws1A2oCtju/jY88y2oOStjf8tGNqYw++TOO1avKe
tawmbsvhK5aSoA5xPY/S1omotjYN2aPsFnVF7nCQYeXB0y7ReXPt7YZ0gQ9Sj01Z
WVXWBuhXrFyYF9sNqFjGJdQGjfTeQLML28PfU0RuRfeQ+6d/e/rOHtO32vvKfDJn
F9qlTNmHaKpZfnx/FoZbtUbKFJk+RhyYmobbJcobFxGRcWaukLF1ktWy78L+YKV8
araql4DlEmkj/ZhnABEBAAGJAjwEGAEIACYWIQTIrSpMJAyoXCefJ7OaYxyUOH9K
twUCWhF/LgIbDAUJCWikgAAKCRCaYxyUOH9Kt2crEACuqTCf2uozp1Sj8zF3Ay4Q
5qe3TT3c8UcYa5AtrowdNHgr9w0RPPvxyHfjxM7kqzOqGh7lkfB1V4GVMekNcqL6
lHc3bsUOMuXzhKIV+2WCaFsNdcnqnn+4WugyqCwE2sen7dIGzMykHzpurHMOjW8m
7EPzq0UhCWJp0bQ4V+HEYHiN5qRAKCMYBRgkmbffE7J62cP3pk3y2S1vohs6ymAh
n+N4lmV84qXjNMoGYrmEiwMvPlcC5icthx0f5lxnu5DJNGIy5V3DA21yF0Pu+nUo
COL18J7xURWVHJ4AnUY9iMVaUIPFyVvY6qPMSfxvedkt0cULov4dT8tEWgz3vCBr
PjnGvpP+ZE/93qEbGUH03Ch1rIctuSJ71j72+qxpYbl5T5fXm3YtYAupCpzMFg0G
gS5dUp+qKewwoj6qx6NYparddrcErLnlwPQGMlBGNANhv68crJXQi3ipvcvhwXYU
gzB22D8QnYSESbceLZD7NVAwGI8PORCTf46GMVH3sod44G6ArcKfTxqqUYdHlR1d
z2C3T7YPmSpSRa5xdLGxa5WdeFi8WyZsox+iiPyHELY8MPS1T5RqhtxVJ8wXjKG1
FubANJ8HmDgyOL3DcdU7EOFzAaATaWU+MoW1cBrxxL6en442vuHZFHFRnq/eWjF5
HDgtrlBRjJojR5q/NwXWtQ==
=ioSN
-----END PGP PUBLIC KEY BLOCK-----
```

If you feel better about it you can also send it to me without the WAL file first and I'll only request it if needed.

**Comment by nmaxcom** [comment]
It's allright. Here's the whole thing.

In the meantime, 

I decided to uninstall it and download a free/trial version. So far, seems to work fine...

PS: GitHub doesn't support files ending in GPG. Just in case, original file name is
![bettertouchtooldebug zip gpg](https://user-images.githubusercontent.com/8936090/33117240-f4767112-cf67-11e7-95ae-f793e259ddd5.gif)
: `BetterTouchToolDebug.zip.gpg`
