### ISSUE TITLE
Windows virtual desktop (Parallels) with Magic Trackpad 2 gesture

### ISSUE THREAD

**Issue by rodolphb** [folivoraAI/BetterTouchTool#1747]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

HI, I am disturbing with a gesture that switch to windows 10 virtual desktops view (running under Parallels).

It concerns a right slide gesture from the left border.

Just tell me how to desactivate this feature. Iam driving crazy

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Magic Trackpad 2

#### Device information:

Type of Mac: 18,3
macOS version: 10.13.1
BetterTouchTool version: 2.313

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Sorry I do not know what kind of gestures you have configured in BTT. Please provide more details.

**Comment by rodolphb** [comment]
I did not configure any extra gestures concerning windows 10 ... or gesture from trackpad left side to the center.

I am very embarrassed

**Comment by fifafu** [comment]
Sorry but I don't fully understand the issue.
Is this something that is caused by BTT or is this something you wish would be doing?

**Comment by rodolphb** [comment]
Sorry, I could not reply you earlier.

do not really know if BTT is involve in this issue but there is no such gesture in OSX.

How can I guide you ? Screenshots ?

See you
