### ISSUE TITLE
BTT randomly starts swallowing cmd-w commands

### ISSUE THREAD

**Issue by chmac** [folivoraAI/BetterTouchTool#1748]
#### Description of bug/feature request/question:

Randomly <kbd>cmd</kbd>+<kbd>w</kbd> and <kbd>cmd</kbd>+<kbd>shift</kbd>+<kbd>w</kbd> stop working across all apps. I eventually figured out that if I restart BTT they start working again.

It's possible that this is connected to booting the android emulator, not sure. Seeing the same problem and solution on 2 different macs.

I have one keyboard mapping for <kbd>cmd</kbd>+<kbd>w</kbd> and <kbd>cmd</kbd>+<kbd>shift</kbd>+<kbd>w</kbd> but only in the `iTerm2` application. I'm trying now to disable that, will see if the issue persists. To be clear, this issue affects all programs.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Keyboard

#### Device information:

Type of Mac: iMac retina
macOS version: 10.12.6 (also on 10.13)
BetterTouchTool version: 2.313

**Comment by fifafu** [comment]
Weird. Does this maybe happen after using iTerm2?

**Comment by chmac** [comment]
@fifafu Could do, I use `iTerm2` **a lot**. It's setup on a system wide single key shortcut, so I toggle in and out of it hundreds of times per day.

**Comment by fifafu** [comment]
In case you notice this happening again it would be great if you could go to the about tab in BTT and click the "Export Debug Info" button. It will create a folder called BetterTouchToolDebug on your desktop. If possible send that to boastr.net@gmail.com
