### ISSUE TITLE
BetterTouchTool crashing when pressing a mouse button

### ISSUE THREAD

**Issue by eggsmack** [folivoraAI/BetterTouchTool#1750]
![screen shot 2017-11-17 at 11 39 43](https://user-images.githubusercontent.com/33750336/32943327-09bdeb98-cb8c-11e7-9f62-80954f0214e3.png)
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

BetterTouchTool keeps shutting down when I click button nr. 6 with my mouse(Evoluent Vertical Mouse 4).

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Normal mice Evoluent Vertical Mouse 4

#### Device information:

Type of Mac: Macbook Pro Retina 15" 2016
macOS version: High Sierra
BetterTouchTool version: 2.313(691)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
![screen shot 2017-11-17 at 11 37 15](https://user-images.githubusercontent.com/33750336/32943276-e2fe25b8-cb8b-11e7-8734-c238368b2b2e.png)

**Comment by fifafu** [comment]
If possible please try to delete the triggers where you didn't assign any action in BTT.
