### ISSUE TITLE
Allow slider widget placement in Main Container

### ISSUE THREAD

**Issue by CappyD** [folivoraAI/BetterTouchTool#1759]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
The configuration for a slider widget (volume, brightness) only allows placement as "stick to" left or right side. I want to be able to put buttons or other widgets on either side. Can you add the ability to place a slider widget in the main container?

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
touch bar

#### Device information:

Type of Mac: 2016 MBPro 13"
macOS version: 10.13.1
BetterTouchTool version: 2.313

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Unfortunately this is complicated because the main container is scrollable in BTT and the slider widgets "steal" these touches. (That's the reason why it's not yet possible)
