### ISSUE TITLE
Clipboard manager has multiple entries without me having copied something multiple times [bug]

### ISSUE THREAD

**Issue by felixbinder** [folivoraAI/BetterTouchTool#1761]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
The clipboard manager shows multiple entries for some entries, usually spaced 15-45 minutes apart with the icon of random applications. All of these are items I have copied once, which get added multiple times. This should be an easy fix: just don't add an item to the list if its the most recent one. I have tried clearing the clipboard manager multiple times to no avail. I use no other clipboard manager.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Clipboard Manager

#### Device information:

Type of Mac: MacBook Pro (Retina, 15-inch, Mid 2014)
macOS version: 10.13.1 (17B48)
BetterTouchTool version: 2.313 (691)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
I've attached two screenshots. Happy to provide more information.
<img width="877" alt="screen shot 2017-11-19 at 21 00 18" src="https://user-images.githubusercontent.com/24477285/32994904-69798c8a-cd6d-11e7-8839-0e4bd08dc983.png">
<img width="877" alt="screen shot 2017-11-19 at 21 00 31" src="https://user-images.githubusercontent.com/24477285/32994894-4af72588-cd6d-11e7-981f-867f8ff6dbb5.png">

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
That's weird, something must be increasing the change counter of your clipboard (BTT only copies something if the counter has changed).

Can you think of any other app that may modify your clipboard?

**Comment by felixbinder** [comment]
I use a custom keyboard layout (with the standard Mac tools, not Karabiner etc). Outside of that no. Happens also when no program is running. I used to use flycut before, which didn’t have that problem (but it definitely isn’t running). I use handoff, that modified the clipboard, no?

**Comment by fifafu** [comment]
Mhh it's kind of weird, but I'll add a check to prevent this!

**Comment by felixbinder** [comment]
The bug still happens in version 2.320 
<img width="877" alt="screen shot 2018-01-04 at 12 51 16" src="https://user-images.githubusercontent.com/24477285/34562340-39709b1e-f14e-11e7-890f-1e4349559e89.png">
It tends to add new entries when the computer is asleep.
