### ISSUE TITLE
Option to move one monitor left/right

### ISSUE THREAD

**Issue by xanstheman** [folivoraAI/BetterTouchTool#1766]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

Hi,
This is a feature request, not a bug.

Currently, you have the following options:

1. "Move Window One Space/Desktop Left"
2. "Move Window One Space/Desktop Right"
3. "Move Window to Next Monitor"

I wonder if you could make #3 more similar to # 1 and 2, where you can "Move Window One Monitor Left" and "Move Window One Monitor Right". I have multiple monitors, and this would be very handy.

Thank you! This is an awesome tool already, and I have thoroughly enjoyed using it!

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
All

#### Device information:

Type of Mac: iMac 2017
macOS version: 10.13.1
BetterTouchTool version: 2.313

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by svenwiegand** [comment]
Would be very helpful in a three monitor setup! [Spectacle](https://www.spectacleapp.com/) (which is also open source) provides this feature.

**Comment by fifafu** [comment]
This is now possible with the "Custom Move & Resize" action. 

![image](https://user-images.githubusercontent.com/8820811/39932559-bbe749d4-5540-11e8-81fc-78acc1ecbdc3.png)
