### ISSUE TITLE
4 finger tap sometimes stop working - need to restart BTT to make it work

### ISSUE THREAD

**Issue by jieliu8sc** [folivoraAI/BetterTouchTool#1772]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Sometime 4 finger tap stops working. Restarting BetterTouchTool makes it work again. But it's very annoying because I'd have to keep restarting BetterTouchTool

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Trackpad

#### Device information:

Type of Mac: MacBook Pro (15-inch, 2017)
macOS version: Sierra, 10.12.6
BetterTouchTool version: 2.313

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
What kind of action do you have assigned to it?

**Comment by jieliu8sc** [comment]
Keyboad Enter key

**Comment by jieliu8sc** [comment]
I replied on Nov 22, why is this in "Needs Reply" ?

**Comment by fifafu** [comment]
Because I need to reply :-)
Sorry I  haven't gotten to do much lately. Starting on February 1. I'll be self employed and go through all the issues asap.
