### ISSUE TITLE
Snap Areas are removed/disabled when I change display resolution

### ISSUE THREAD

**Issue by CalderH** [folivoraAI/BetterTouchTool#1774]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

I sometimes change my display resolution (System Preferences → Displays → Resolution). When that happens, the Snap Areas I’ve set get removed or disabled somehow. I’d prefer if they stayed active, but scaled so they always fill the whole screen.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

MacBook Pro (2016, 13ʺ with Touch Bar)

#### Device information:

Type of Mac: MacBook Pro
macOS version: 10.13
BetterTouchTool version: 2.313

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Unfortunately snap areas are currently specific to a display and its exact configuration (For technical reasons)

The api has improved with the latest macOS, so maybe I can change this soon.

I think there are already a few issues about this topic here.

**Comment by CalderH** [comment]
Okay, I see. Thanks for letting me know.

Sorry I didn’t see the other issues; I tried to search for it but I must not have entered the right terms.

**Comment by fifafu** [comment]
Don't worry, I'll link them later (currently on mobile)

**Comment by mccorkle** [comment]
Is there a way to mitigate this (e.g. can I edit a json file by hand) to move my snap config from one resolution to another?  I just noticed this issue with build 2.332 (713).

**Comment by fifafu** [comment]
@mccorkle that's not possible yet but it's on my todo list for February

**Comment by mccorkle** [comment]
Thanks.  I'll check back in around March :-)

**Comment by ThienJP** [comment]
any updates on this? I work with a 4k monitor and depending on the work I do I change the scaling but snap areas are always gone which defeats the purpose.

**Comment by fifafu** [comment]
Not yet. Snap areas are currently still specific for a display setup (A big update for window snapping and snap areas is planned for may, there I'll be able to add an auto-scaling option)
