### ISSUE TITLE
Need way to control repeat for Touch Bar buttons

### ISSUE THREAD

**Issue by CappyD** [folivoraAI/BetterTouchTool#178]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:
We need to be able to at least turn repeat on/off for touch bar buttons.  The control needs to be at the gesture level since you might want some buttons to repeat and others not.  Buttons appear to repeat now.  If you have a button that creates a new tab in Safari or a new mail message in Mail, and if you let your finger stay on the button a little too long then you get a LOT of new tabs or mail windows opening.  Of course, being able to control the delay to repeat and repeat rate would be good options to have too, and these could be at the global level instead of the gesture level.

**What kind of Mac are you using?**
2016 MacBook Pro 13"

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

**Which versions of macOS and BetterTouchTool are you running?**
10.12.2 and 1.978

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by golodenko** [comment]
@fifafu sorry to bother, but was this feature released? Version went over 2.2.

**Comment by fifafu** [comment]
Nope, not yet!
