### ISSUE TITLE
BUG: BTT TouchBar Global Settings are fully replaced when in FaceTime call, shouldn't be

### ISSUE THREAD

**Issue by petelp1** [folivoraAI/BetterTouchTool#1787]
#### Description of bug/feature request/question:
- I have a full set of Global TouchBar Icons setup in BTT Global settings
- FaceTime is not listed anywhere in my BTT settings
- Allow Systems Apps to Replace BTT Control strip icon is turned off
- I've tried with and without "Show BTT icon on Left Side" 

1-  Make A FaceTime call, 
2- TouchBar shows default APPLE FaceTime touchBar settings, completely replacing my global BTT touchBar settings. This should not be happening 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

MacBook Pro TouchBar

#### Device information:

Type of Mac:         MacBook Pro (13-inch, 2016, Four Thunderbolt 3 Ports) with TouchBar
macOS version:    macOS Sierra 10.12.6
BetterTouchTool version:       2.313 (691)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

![img_0048](https://user-images.githubusercontent.com/33965526/33222088-4f8ea252-d109-11e7-9b79-d41db97e50c7.jpg)
![img_0049](https://user-images.githubusercontent.com/33965526/33222089-4fa5f0e2-d109-11e7-9bac-c236933a5c35.jpg)

**Next Photo shows my touchBar with my global BTT icons,**

![img_0050](https://user-images.githubusercontent.com/33965526/33222090-4fc3f146-d109-11e7-81ae-bf1a50b691dd.jpg)

**Next Photo shows my touchBar when in FaceTime call**

![img_0051](https://user-images.githubusercontent.com/33965526/33222091-4fda2f2e-d109-11e7-9849-5317126e28ec.jpg)

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Thanks for reporting, but unfortunately I probably won't be able to workaround this. Facetime has higher priority than BTT ;-(

**Comment by petelp1** [comment]
Perhaps you could create a customizable keyboard shortcut action that the user could employ, AFTER FaceTime has replaced BTT,  which would trigger an action to replace FaceTime touchBar with BTT.

The FaceTime TouchBar replaces BTT each time a call is made.  But may not mess with it well AFTER the call is made (until the next call)?

I assume you override the touchBar at time of app activation, Also if you could detect when a facetime call is made or when its replaced you might be able to do it once for each call?
