### ISSUE TITLE
BTT Pinch In gesture in Safari

### ISSUE THREAD

**Issue by mrGibi** [folivoraAI/BetterTouchTool#1789]
#### Description of bug/feature request/question:
I have a "pinch in" gesture in Safari set to Command+W (close tab), but Safari randomly overwrites (?) this gesture with "Tabs Expose" (Show All Tabs). Google told me that Safari doesnt have any (even hidden) option to disable this gesture, but maybe it is possible in BetterTouchTool to somehow block Safari from receiving this gesture etc?

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Macbook Trackpad

#### Device information:

Type of Mac: MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)
macOS version: 10.13.1
BetterTouchTool version: 2.313 (and many before) 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
None... yet? ;)

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by james-rose** [comment]
I have the same problem.  It seems to happen randomly, and I haven't figured out what may trigger it.

**Comment by james-rose** [comment]
I now changed it to a "rotate left" gesture with Safari and this one doesn't seem to have a problem.
