### ISSUE TITLE
[Feature Request] Button group options

### ISSUE THREAD

**Issue by CyborgSemon** [folivoraAI/BetterTouchTool#1790]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of feature request:

Would it be possible to have the button group also be able to act like a widget? Basically what I'm trying to make, is a widget that updates with what song is currently playing on Spotify (using AppleScript), but also have it so when it is pressed it shoes up a new group of controls to control Spotify.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Touch Bar

#### Device information:

Type of Mac: 13" Pro with Touch bar
macOS version: 10.13.1
BetterTouchTool version: 2.313

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
You can already assign the "Open Touch Bar Group With Name" action to a widget. This should allow you to achieve this.

**Comment by CyborgSemon** [comment]
ahhhh I see! Thank you. However could you add an option to the button group that hides the button group on the touch bar if it is assigned to a widget? What I have currently done is have it only show when all 4 of the modifiers are pressed down so it doesn't show up. it seems fine as it is, but it is just more of an ease of use feature.

Thanks anyway!

**Comment by CyborgSemon** [comment]
Wait... I derped a little. It actually doesn't work. Not to sure why either.
here are some pictures of my set up

I have a Spotify widget that uses AppleScript to updates the text on the widget to tell me what song is playing

<img width="621" alt="screen shot 2017-12-23 at 5 35 44 pm" src="https://user-images.githubusercontent.com/26075792/34317709-83ca5104-e808-11e7-99c0-80b40ea36ef4.png">

Then when pressed it (is supposed to) open up the button group called "Spotify_buttons"

<img width="715" alt="screen shot 2017-12-23 at 5 34 04 pm" src="https://user-images.githubusercontent.com/26075792/34317706-6ecdea0e-e808-11e7-9013-07a260905880.png">

Then it runs another piece of AppleScrip that makes Spotify the front mode app on the screen.

<img width="446" alt="screen shot 2017-12-23 at 5 34 45 pm" src="https://user-images.githubusercontent.com/26075792/34317715-a1056f2e-e808-11e7-9163-0a31d38f40fd.png">

This is the button group

<img width="532" alt="screen shot 2017-12-23 at 5 34 19 pm" src="https://user-images.githubusercontent.com/26075792/34317718-aca2f464-e808-11e7-8c74-5f29337f72d5.png">

Yeah. not quite sure why it doesn't work... but hey :P
Sorry for derping xD

**Comment by OrbitalTech** [comment]
This may be a-lot easier if you just use <a href="https://developer.apple.com/library/content/documentation/AppleScript/Conceptual/AppleScriptLangGuide/reference/ASLR_cmds.html#//apple_ref/doc/uid/TP40000983-CH216-SW60">activate</a>.
