### ISSUE TITLE
[Feature request] Wait momentarily before accepting inputs

### ISSUE THREAD

**Issue by Sir-Cumference** [folivoraAI/BetterTouchTool#1799]
I was wondering if there was a way to wait a moment before accepting another BTT input, after an action has been done. I tried adding a delay, but that still accepts new gestures and only delays them. I also tried disabling gesture recognition temporarily, but that did not affect anything.

**Comment by CyborgSemon** [comment]
Instead of having a BTT delay, add an additional action and set it to apple script. in the apple script write this:

```
tell application "System Events"
    delay 1
end tell
```
The delay function should work in the way that you want it. it basically freezes BTT (I think)

Hope this works :)
