### ISSUE TITLE
Open group in group

### ISSUE THREAD

**Issue by mattorp** [folivoraAI/BetterTouchTool#1802]
#### Description of bug/feature request/question:
I can't seem to open a group in another touch bar group using the predefined actions. Does the name have to include the parent and in which case, how should the string be build?

In case it isn't possible, being able to define a group within a group would be a useful feature.

#### Affected input device:
This affects the touch bar.

#### Device information:

Type of Mac: Macbook 13" 2017 with Touchbar
macOS version: 10.13.1
BetterTouchTool version: 2.313

**Comment by fifafu** [comment]
This issue was moved to https://community.folivora.ai/t/open-group-in-group/55
