### ISSUE TITLE
FEATURE REQUEST: snap area with pinned window functionality

### ISSUE THREAD

**Issue by mcsper** [folivoraAI/BetterTouchTool#1803]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---
Is it possible to make a snap area apply a pin tag (made up name) to a window so that it floats above any other windows? maybe on different spaces too?

#### Device information:

Type of Mac:
macOS version: 
BetterTouchTool version: 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by shane-onezine** [comment]
yep.... i second that.. was actually reading this before jumping here....
[https://apple.stackexchange.com/questions/219116/any-nice-stable-ways-to-keep-a-window-always-on-top-on-the-mac](url) 
i think it would be a good feature to complement the existing window snapping feature..

**Comment by themikesam** [comment]
+1
