### ISSUE TITLE
one finger clicks unresponsive

### ISSUE THREAD

**Issue by tnaz** [folivoraAI/BetterTouchTool#1814]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
in all versions after 2.313 there seems to be an issue when i click on the trackpad with one finger. the click is not registered and will have to use much more pressure (or a force touch) to get the one finger click to work. there also seems to be variation in the location of where on the trackpad i am clicking. 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
mbp trackpad

#### Device information:

Type of Mac: MBP 2016 touchbar 15"
macOS version: 10.13.1
BetterTouchTool version: 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by tnaz** [comment]
@fifafu any luck looking this over by any chance? i often have to click more than once for it to register an action. of note- one finger taps have no issue.

**Comment by fifafu** [comment]
Could you check whether 2.320 alpha fixes your issue?

**Comment by wagnerone** [comment]
I have a similar issue. Almost every initial "tap" (I rarely click to mechanically move the track pad) of the track pad to click something doesn't register, but the followup tap does register. I'm using 2.405 (756) on 10.13.3.

**Comment by fifafu** [comment]
@wagnerone this is usually caused by some conflicting app running. Unfortunately I currently don't know of any incompatibilities but try quitting apps to find out which on.

Another user recently had a similar issue caused by a broken USB device connected to his Mac.

**Comment by wagnerone** [comment]
Thanks. I'll try to narrow it down. After I quit BTT I find I want it back, so I relaunch it pretty quickly. I've noticed the "initial tap ignored" thing doesn't happen immediately after relaunching BTT. It takes a while for that to start happening again.
