### ISSUE TITLE
Better touch tool 3 finger double tap lag

### ISSUE THREAD

**Issue by jeremypng99** [folivoraAI/BetterTouchTool#1815]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
enabling 3 finger double tap on global for shortcut for hide results in a delay, sometimes it does not register the double tap and I would have to do the gesture twice. 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
macbook trackpad

#### Device information:

Type of Mac: 2017 macbook pro 13 inch
macOS version: 10.13.1
BetterTouchTool version: 2.310

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
You mean it delays the normal three finger tap? (That is to be expected as BTT needs to wait to ensure you wanted to trigger a three finger double tap instead.)

If that's not what you meant, please try updating to the latest BetterTouchTool version  first.

**Comment by jeremypng99** [comment]
Hi, yes it delays the normal three finger double tap. However, I do not have anything under three finger single tap so there shouldn’t be a lag.
