### ISSUE TITLE
1 Finger Tap Left registering as Right Click instead of Left Click

### ISSUE THREAD

**Issue by croissantfriend** [folivoraAI/BetterTouchTool#1817]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
I have "1 Finger Tap Left" set to "Left Click" on my Magic Mouse. This works fine most of the time, but occasionally tapping with one finger on the left side of the mouse triggers a right click instead. The issue is temporarily resolved by opening BetterTouchTool.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Magic Mouse (not Magic Mouse 2)

#### Device information:

Type of Mac: iMac (27-inch, Mid 2011)
macOS version: High Sierra 10.13.1
BetterTouchTool version: 2.317

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
![screen shot 2017-11-30 at 8 08 56 pm](https://user-images.githubusercontent.com/34118891/33467590-627c459e-d60a-11e7-9934-0f4be69af0f1.png)

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by croissantfriend** [comment]
Bumping as I'm still getting the issue, unfortunately.

**Comment by croissantfriend** [comment]
Update after a while, the issue seems to occur (apparently exclusively, but not 100% certain on that) when the Mac wakes up from sleep.

**Comment by fifafu** [comment]
Very weird issue :-)
Does your BetterTouchTool restart itself after sleep? (It should do that).
Could you try to open the BTT window and check if it's still open after waking the Mac from sleep? (This would mean BTT hasn't restarted correctly)

**Comment by ambianceambiance** [comment]
same problem here
