### ISSUE TITLE
Add support for spacers on Touch Bar

### ISSUE THREAD

**Issue by ErikMinekus** [folivoraAI/BetterTouchTool#1821]
#### Description of bug/feature request/question:

The Touch Bar has support for flexible space items, to evenly match the space between sections of buttons. See the item in the bottom right of this screenshot:

![Touch Bar](https://www.imore.com/sites/imore.com/files/styles/xlarge/public/field/image/2016/11/touch-bar-control-strip-customization-panel.jpg?itok=25oouEIF)

Is it possible to add support for these to BTT?

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Touch Bar

#### Device information:

Type of Mac: MacBook Pro 2016 15"
macOS version: 10.13.1
BetterTouchTool version: 2.317

**Comment by dirkvranckaert** [comment]
Any update on when this might be coming?

**Comment by OrbitalTech** [comment]
Free Space after this button is a feature now. Surely this does whats asked for? This can be removed from the TODO list?

**Comment by fifafu** [comment]
@OrbitalTech, no the requested feature is different (flexible space). I'll leave this open for now, however I'm not sure yet whether I'll be able to integrate it. (BTT doesn't use the standard Touch Bar stuff obviously :-))
