### ISSUE TITLE
Keep getting spurious tiptaps when dragging to highlight text

### ISSUE THREAD

**Issue by CPStagg** [folivoraAI/BetterTouchTool#1826]
#### In the last couple of weeks, I've started seeing regular spurious Tiptap Right (and TT Left) gestures when dragging to highlight text. My method of doing this is to click-hold the trackpad with my thumb (on my right hand) and then use my index finger to select the highlighted text.

I can see how in principle BTT might recognize the first contact of the index finger as being a tiptap right. Yet until recently it never did so, seemingly because it required the index finger to be released before the gesture triggered. But this isn't what I'm seeing any more. Around half the time I attempt the click drag, the tiptap gesture appears to be recognized, even though I have not released contact with the index finger. As I've mapped TTR to "open new tab", I am constantly getting new tabs opening whenever I try to highlight text. On one of the machines I also get tiptap left being recognized some of the time, seemingly simultaneously with tiptap right, while performing the drag. The TT gestures are typically triggered halfway through the drag, despite the index finger not being removed from contact (and despite the fact that it is to the right of the thumb yet sometimes triggering TTL).

I'm seeing this on two separate Macs, two separate OSs and two separate trackpads. So I don't think it is e.g. an isolated hardware issue.

#### Device information:

Type of Mac: 2007 MBP; 2009 iMac
macOS version: El Capitan (MBP); High Sierra (iMac)
BetterTouchTool version: 2.318 on both.

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Mhh I could imagine this being related to thumb handling.
Maybe try turning it off in the preferences and check if anything changes. See this screenshot:

<img width="1127" alt="grafik" src="https://user-images.githubusercontent.com/8820811/34084611-f563194c-e383-11e7-8ecd-0b72b1f2ddc9.png">

**Comment by felixbinder** [comment]
I can second this problem. Disabling thumb handling doesn't help at all. Using 2.320 on a 2014 MBP. Easy fix would be to disable tiptap gestures triggering when the trackpad is pressed down, I suppose
