### ISSUE TITLE
Laggy/choppy snap areas

### ISSUE THREAD

**Issue by almirramic** [folivoraAI/BetterTouchTool#1827]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

I work on multiple screens and for each screen I have 9 snap areas. What happens almost consistently is when I start dragging, all areas on on all screen start to flicker and dragging either fails or is very laggy, choppy or even unresponsive. Sometimes even if I release the pointer, the areas remain and they continue to flicker until they stop by them selves or I interrupt them by clicking something. This has gotten so bad now, that I am learning to live without snap areas, hoping a fix will come soon.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Any pointing device.

#### Device information:

Type of Mac: MBP 15" 2017
macOS version: 10.13.1 (latest) 
BetterTouchTool version: 2.318 (latest)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

I used to use BetterSnapTool for snap areas and I think it used to work better (less laggy/choppy) than BetterTouchTool. But my impression is that BetterSnapTool may be discontinued (?)

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by docmars** [comment]
It seems this has come back for me too.

The moment I disable Snap Areas, window dragging becomes smooth as butter again. When I have it on, it feels like trying to pull a dog away from its bone so I can give it a bath—lots of resistance and friction. 😩

My environment is as follows:
- Macbook Pro 15" Mid 2015
- macOS 10.12.3
- 2 external monitors, clamshell mode
- BTT 2.340 (719)

**Comment by fifafu** [comment]
Are you maybe running any jetbrains IDEs?

**Comment by docmars** [comment]
I'm not—though I'm not sure about @almirramic.

For me, it doesn't seem to matter what's running. When I unplug my monitors and move windows around on my Macbook's display exclusively, I don't see any lag/jank. The moment I use my monitors again, it comes right back.

**Comment by bigH** [comment]
I have the same behavior also:
Running OS X 10.13.6
15' Retina MBP (Touchbar) - 2017
Better Snap Tool 1.9

These programs are _usually_ running all the time:
 - Chrome
 - Slack
 - iTerm
 - Fantastical
