### ISSUE TITLE
Scroll action for normal mice

### ISSUE THREAD

**Issue by ursbraem** [folivoraAI/BetterTouchTool#1832]
#### Description of bug/feature request/question:
Is it possible to assign a "scroll left/right" action to a normal mouse's buttons? I didn't find it. Don't want to install logitech's custom tool (asks for update 2x a week)

**Comment by joantune** [comment]
I have an issue with my microsoft mouse where the scroll just plainly doesn't work. I was looking for BetterToucTool to address the issue but I cannot add a trigger to the scroll  :( otherwise it works perfectly for the other buttons, but what I really wanted was the ability to scroll with the mouse

**Comment by Muscarv2** [comment]
I'm highly interested in this getting added. I want to be able to use cmd + the scroll wheel to switch spaces like with trackpad and magic mouse.

**Comment by fifafu** [comment]
@Muscarv2 that can be done in the "normal mice tab" in BetterTouchTool already.

**Comment by Muscarv2** [comment]
@fifafu I missed that option somehow, sorry. Thanks for the answer!

**Comment by jbyler** [comment]
Hmm, unless I'm mistaken, '[that can be done in the "normal mice tab" in BetterTouchTool already](https://github.com/folivoraAI/BetterTouchTool/issues/1832#issuecomment-359243056)' is not accurate.  The normal mice tab allows to associate different actions to mouse buttons, but there is no action to simulate scroll events.  See [this comment](https://github.com/folivoraAI/BetterTouchTool/issues/970#issuecomment-303968446) on issue 970 for the contradictory opinion.
