### ISSUE TITLE
Pinch/zoom not working in Chrome, when bettertouchtool is loaded

### ISSUE THREAD

**Issue by planetscripton** [folivoraAI/BetterTouchTool#1839]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
When bettertouchtool is loaded, pinch/zoom does not work in Chrome, or works intermittently.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Macbook trackpad

#### Device information:

Type of Mac: macbook pro 15"
macOS version: 10.13.1
BetterTouchTool version: 2.318 (702)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

As soon as I quit bettertouchtool, pinch/zoom starts working in Chrome immediately.
I have tried turning off the thumb/palm handling setting, but no change.

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by NevinBR** [comment]
I do not confirm. (I am on BTT 2.318, macOS 10.12.6, Chrome 62.0.3202.94)

In my experience Chrome requires the pinch-to-zoom gesture to be done rapidly, at least at the start, regardless of whether BTT is running.

**Comment by babalooza** [comment]
I do confirm planetscripton. With BTT loaded (2.318 - 702) Chrome (63.0.3239.84) doesn't recognize pinch/zoom, no matter how fast or slow I pinch. As soon as I quit BTT pinch/zoom works in Chrome, slow and fast.

All on a MacBook Air with a Magic Trackpad. Using the built-in Trackpad, pinch/zoom kinda works with the fast approach, but not reliably.

Going to chrome://flags and changing Touch Events API from Automatic to Enabled doesn't help.

**Comment by M-AR** [comment]
I do confirm. I have the same issue. When BTT is activated pinch to zoom works only occasionally and is very unreliable. As soon as i deactivate it for chrome zooming starts working again. 

The fast approach does not help either. It sometimes works after trying it multiple times but rarely on the first try. I also find that when BTT is disabled i can pinch slowly and still get chrome to zoom (it's not as responsive as safari but it works nonetheless).

**Device information:**
Type of Mac: macbook pro 13" 2017
macOS version: 10.13.2
BetterTouchTool version: 2.318 (702)
Chrome: 63.0.3239.84

**Comment by mikew** [comment]
Ah, I thought it was a recent update to Chrome that broken pinch-to-zoom. Disabling BTT here also makes the gesture work fine in Chrome.

**Comment by HenrikEckermann** [comment]
same here...

**Comment by albusrhino** [comment]
I'm also having pinch zoom issues. Working great, seems to be triggered when adding gestures to trackpad for Photos. Certain shortcuts mess it up, I have to delete everything and the start over adding my gestures.

**Comment by mzavattaro** [comment]
Can confirm the issue persists but across all apps that support pinch to zoom. Quitting BTT and turning pinch to zoom off and back on in the macOS trackpad settings allows it to work again.
