### ISSUE TITLE
Global gestures stop working after waking from sleep on MacOS 10.13.1 MacBook Pro 2016

### ISSUE THREAD

**Issue by chadlangston** [folivoraAI/BetterTouchTool#1840]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Device information:

Type of Mac:
macOS version: 
BetterTouchTool version: 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by LuyangCAT** [comment]
I also encountered the same problem on my trackpad：global gesture e.g. one finger click == command+T. and window snapping also has no response if i don't use trackpad after a while . It will not recover normal status until restart BTT.

Device information:
Type of Mac:MacBook pro 15 Mid 2015
macOS version:macOS high sierra 10.13.1 (17B1003)
BetterTouchTool version:2.318(702)

**Comment by fifafu** [comment]
Could you check in Activity Monitor whether the BTTRelaunch app is running? (It is reponsible for restarting BTT after sleep)

**Comment by LuyangCAT** [comment]
BTTRelaunch app is running.
