### ISSUE TITLE
Three finger force click (middle finger harder)

### ISSUE THREAD

**Issue by DrParanoia** [folivoraAI/BetterTouchTool#1841]
Hi! If possible, would be nice to have an option for when middle finger is pressed harder with a 3 finger force click (makes snapping windows to a third of the screen a bliss).

Also, if it's not hard to implements, same principle can apply for 4 fingers for example (first, second, third, fourth finger harder)?

Thanks for your hard work!

**Comment by fifafu** [comment]
Unfortunately in my experience the middle finger force can not be distinguished reliably from the others (you can see that if you open the live view, at least for my hands the force looks pretty similar for all fingers when trying to do a harder click with the middle finger)

**Comment by DrParanoia** [comment]
That's strange, it works perfectly fine for me. The line that connects the touch point surely is wrong in many times, but it can be fairly easy distinguished by coordinates.
![image](https://user-images.githubusercontent.com/1381419/33902772-c329eb80-df7e-11e7-8903-7a0f9ae6151b.png)

Thanks for answering by the way!
