### ISSUE TITLE
Mouse shortcuts don't work in Microsoft Outlook 2016 

### ISSUE THREAD

**Issue by kamil6x** [folivoraAI/BetterTouchTool#1842]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Middle mouse clicks are mapped to CTRL-C and CTRL-V; they work in all apps except when Microsoft Outlook 2016 is in focus; the shortcut is not triggered at all (eg. not the keyboard mapping but the HUD display doesn't show the mouse button being pressed).

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Mouse.

#### Device information:

Type of Mac: Macbook pro 2015
macOS version: 10.11.6 (15G1611)
BetterTouchTool version: 2.313

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Did you maybe disable BTT for Outlook? This seems to be working fine here.

**Comment by kamil6x** [comment]
So I have global shortcuts and then I added 2 shortcuts that are outlook specific; I would assume the global shortcuts should work in Outlook?  See attached images below.
![screenshot 2017-12-20 18 49 26](https://user-images.githubusercontent.com/3533839/34220988-c26ebc82-e5b6-11e7-9e63-b8aa4feb51c5.png)
![screenshot 2017-12-20 18 49 15](https://user-images.githubusercontent.com/3533839/34220997-c9ae9382-e5b6-11e7-8d94-42bef4a26b7e.png)
