### ISSUE TITLE
Feature request: touch bar like tiles on BTT Remote

### ISSUE THREAD

**Issue by JCLaHoot** [folivoraAI/BetterTouchTool#1845]
#### Feature request 
I've grown used to the touch bar controls with BTT, but when I'm on a non touch bar mac I'd like to be able to get some similar functionality. I see that I can map custom actions for BTT remote, but it's not arranged in a way that's nearly as intuitive as the touch bar. 

On iPad, there's a huge potential to create a VERY powerful control panel! Instead of seeing the standard input keys, I'd love to be able to have a large control panel, with my actions arranged in a grid. Kind of like what DJs use, but with custom sizing and room for widgets (like emoji picker, or dials, etc...
![image](https://user-images.githubusercontent.com/12401777/33730842-3ab6a6a4-db4f-11e7-862d-b648318142ad.png)

I think if you created this, it would be game changer for a lot of people.
If you need any help designing something like this in a more concrete way I'd be happy to help as well :)

**Comment by fifafu** [comment]
I will add this (at least something similar) in february. (From then on I'll work fulltime as indie developer and have more time :-)

It has been on my todo list for quite a while
