### ISSUE TITLE
Custom slider docs

### ISSUE THREAD

**Issue by nmaxcom** [folivoraAI/BetterTouchTool#1848]
Kudos for making what Apple should have. Great software, thank you.

I have a slider that I'd love to customize but the documentation about it is empty. So I don't know how to do it.
I have a custom shell app that controls the night shift value, from 0 to 100. I feel like this should be just one simple line of code but the example by default doesn't help, at all.

![image](https://user-images.githubusercontent.com/8936090/33751799-a175a79e-dbdd-11e7-80df-72ee00f4b8d7.png)

Well, what's the slider value that I can feed to the third party app? It's not in the docs and strangely I haven't found anything online.

**Comment by fifafu** [comment]
If you assign the predefined action "Run Apple Script in background" (the only one it will allow you to assign), it will show an example on how to configure it. The script in your screenshot can set the initial value of the slider.

<img width="1320" alt="grafik" src="https://user-images.githubusercontent.com/8820811/33857869-df735ae4-decd-11e7-9527-3d43534e2450.png">

I'll add this to the docs soon.

**Comment by danbrag** [comment]
Hi!
Thanks for the clarification...not OP.

When you say "The script in your screenshot can set the initial value of the slider." -- do you mean that every time the bar or group is opened it will revert back to that value? Can we leave the script blank if we only want the Predefined Action to take place?

Thanks again!

**Comment by dvkch** [comment]
Hi! I spent some time trying to configure this slider, and the official docs were not giving examples on it, but this thread seems to contain enough information. I'd suggest setting the "Run apple script in background" predefined action as default, or explaining in the "Advanced configuration" window that the "update value script' is configured elsewhere, the script there is only the "initial value script".

Thanks again for this amazing tool!
