### ISSUE TITLE
[Touch Bar] Inconsistent width of battery widget

### ISSUE THREAD

**Issue by ErikMinekus** [folivoraAI/BetterTouchTool#1851]
#### Description of bug/feature request/question:

As you can see in the screenshots below, the spacing around the remaining battery time seems to change randomly, causing the width of the widget to constantly jump around.

<img width="1085" alt="touch bar-schermafbeelding 2017-12-09 om 14 40 18" src="https://user-images.githubusercontent.com/1819481/33796157-5ac1c8b0-dcef-11e7-940f-9fac92e84466.png">
<img width="1085" alt="touch bar-schermafbeelding 2017-12-09 om 14 40 31" src="https://user-images.githubusercontent.com/1819481/33796158-5ad75982-dcef-11e7-9a5f-9a4168c58515.png">

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Touch Bar

#### Device information:

Type of Mac: MacBook Pro 2016 15"
macOS version: 10.13.2
BetterTouchTool version: 2.318

**Comment by neohq** [comment]
I can confirm this. The padding is also working only for the right side.
