### ISSUE TITLE
[Feature request] Tap + hold + slide gesture

### ISSUE THREAD

**Issue by lightheaded** [folivoraAI/BetterTouchTool#1853]
#### Description of feature request:
I would like to configure my Touch Bar brightness/volume button to act like the one in the default extended control strip – by dragging without raising my finger, as demonstrated in [this video](https://youtu.be/8LIJLLmjrok?t=46). Currently I have to tap, raise my finger, hit the slider, raise my finger and tap close (last one being optional), but still a lot more movement and much slower than with the dragging gesture.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Touch Bar

#### Device information:

Type of Mac: Macbook Pro 2017
macOS version: 10.13.1 (17B1003)
BetterTouchTool version: 2.318

**Comment by fifafu** [comment]
This feature is a bit complicated, but alpha v2.468 ALPHA adds a possible alternative.
You can now add two/three/four finger swipe gestures to the Touch Bar and use them e.g. to change volume/brightness just by sliding with two fingers anywhere on the bar.


![image](https://user-images.githubusercontent.com/8820811/39425163-75c22ff6-4c7a-11e8-98fb-a15fb3accf27.png)

**Comment by lightheaded** [comment]
Thanks! This is very exciting news! I upgraded to the lifetime license just because of that feature (well, actually, because of all the others too).
