### ISSUE TITLE
[BUG] Touch bar widgets and buttons not updating

### ISSUE THREAD

**Issue by CyborgSemon** [folivoraAI/BetterTouchTool#1863]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug:

I have a touch bar widget that tells me what song is current playing on Spotify that updates every 1 second. Recently this has not been updating to the current song AND any app specific buttons stay even when the app is closed. The only way to fix this at the moment is by clicking command because I have a button that shoes up when I hold command. When I click command everything updates, but then it stays in the current start after clicking command.

#### Device information:

Type of Mac: MacBook Pro 13" Touch bar
macOS version: 10.13.2
BetterTouchTool version: 3.318

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Do you  only have the spotify script or others as well? The scripts are executed in sequence and if one of them is blocking, it will block the rest.

**Comment by CyborgSemon** [comment]
I have one other (The one that shows up when I hold command) that starts a program called XAMPP but it is quite extensive because there alot of steps to get the program completely up and running. so far it seems that if XAMPP is **not** running, the touch bar freezes up. But if it is running it doesn't freeze up

buttons and widgets I have globally:

<img width="818" alt="screen shot 2017-12-12 at 11 45 16 am" src="https://user-images.githubusercontent.com/26075792/33857784-04f46db2-df32-11e7-9a69-1c8dd06f44e9.png">

XAMPP start up program:

<img width="541" alt="screen shot 2017-12-12 at 11 46 10 am" src="https://user-images.githubusercontent.com/26075792/33857796-1a11ea9e-df32-11e7-8d7f-1fa5c08928ef.png">

XAMPP widget:

<img width="246" alt="screen shot 2017-12-12 at 11 47 14 am" src="https://user-images.githubusercontent.com/26075792/33857831-3fdda59c-df32-11e7-86b4-d1ce2455e46e.png">

Second AppleScript starts XAMPP

Last AppleScript:

<img width="853" alt="screen shot 2017-12-12 at 11 49 24 am" src="https://user-images.githubusercontent.com/26075792/33857900-962c1492-df32-11e7-91aa-baa483ad68e8.png">


Spotify Widget:

<img width="625" alt="screen shot 2017-12-12 at 11 51 01 am" src="https://user-images.githubusercontent.com/26075792/33857947-c66351ca-df32-11e7-8f40-cb6226a76dbe.png">



A lot of screenshots I know, I'm sorry. I just cant find out why the XAMPP widget would fail and cause the rest of them to freeze when XAMPP isn't running.

Thanks

**Comment by fifafu** [comment]
Does this still happen? Have you tried executing the apple scripts in the apple script editor? Do they work fast in general?

**Comment by CyborgSemon** [comment]
It has happened a few times since I posted this but not all the time. All the applescripts work instantly with in the apple script editor with the exception of the second apple script for XAMPP as that has to wait for a colour in XAMPP to change from orange to green which takes about 30 ish seconds. While the second XAMPP apple script is running, the BTT touch bar does freeze up, but I saw this in another post about applescripts that take a while to complete so I didn't mention it. When the script finishes everything goes back to normal

The issue that I was mentioning on the last few posts was happening even when the XAMPP script wasn't running

**Comment by djohnsen** [comment]
@CyborgSemon - I noticed a similar problem when attempting to implement a Spotify display/play/pause/launch button - the button for the track name would not update unless I pressed the modifier key I'd set up to display alternate buttons. This was even true for the simple example @fifafu posted in another bug that toggled between 'button press' and 'timed execution'.

I ended up removing the modifier key checkmark from all my touchbar buttons and reorganizing them under button groups instead. Button updates then worked correctly.

I just tried adding the simple button example back in, after setting a different button to display on modifier only, and the problem did not reoccur. I suspect there's something going on somewhere in the order in which buttons were added and the use of modifier keys to display them. 

A possibly-related side note: I keep Activity Monitor open, and sometimes find a BetterTouchToolScriptRunner process eating a CPU by itself. That will cause any other scripts to react like molasses if at all. I'll force quit the process and restart BTT to get things back to normal. I'll open a separate bug for that at some point when I can provide more useful data; point being, it might have something to do with your scripts being uncooperative.

**Comment by CyborgSemon** [comment]
It is happening again. So far it seems to happen when my mac is left on for to long. The last time it happened I restarted the mac and it seemed to work again. This time the mach has been on for a little of a week and just been left on sleep with the lid down.

Not sure if this is what causes this or not, its more of an observation :P

**Comment by CyborgSemon** [comment]
It is still happening btw. I have tried turning off all of the modifier keys and restarted my mac and the issue is still there

**Comment by CyborgSemon** [comment]
@fifafu any update on getting this fixed?
Thanks
