### ISSUE TITLE
Key sequence works only in CAPS

### ISSUE THREAD

**Issue by ruslaniv** [folivoraAI/BetterTouchTool#1865]
#### Description of bug/feature request/question:
I have created a global key sequence - Double Press "G" to trigger a shortcut CMD+OPT+CTRL+"G" (this will search selected text in Google).
Pressing a shortcut works. 
Double pressing letter "G" does not work.
BUT! Double pressing letter "G" while holding SHIFT - works. 
So it looks like BTT recorded a key sequence for capital letters. 
Is it possible to specify small letter case while recording a key sequence? 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Macbook built-in keyboard. Apple BT keyboard. 

#### Device information:
Type of Mac: Macbook Pro late 2013
macOS version: 10.13.2
BetterTouchTool version: 2.318

**Comment by fifafu** [comment]
Key Sequences don't look at the case of the letters, however if you use shift while entering the key sequence, it will be required.

Could you post a screenshot of your sequence here?

**Comment by RuslanIsh** [comment]
![screenshot 2017-12-12 12 11 44](https://user-images.githubusercontent.com/7631314/33871771-bfcc2f5a-df35-11e7-98a3-f5117bb824bd.png)
![screenshot 2017-12-12 12 11 56](https://user-images.githubusercontent.com/7631314/33871777-c2ab715e-df35-11e7-9573-a2dd2208722e.png)

**Comment by RuslanIsh** [comment]
Well, the problem was so obvious that I spent half a day trying to figure it out. I have the key "G" assigned both to the shortcut AND the triggered action.

**Comment by fifafu** [comment]
Interesting, I think it should still work with the cmd+opt+control+G shortcut.
I'll look into this.
