### ISSUE TITLE
automatic colorisation of TouchBar battery widget

### ISSUE THREAD

**Issue by peytonkelvin** [folivoraAI/BetterTouchTool#1867]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

Touch Bar Battery widget Color changing from green to red according to %.

also, the "infinite" sign brings no value to the user. I'd rather remove it, change the battery logo instead to something similar to that of iOS plugged batterie icon or add the % instead to keep an eye on level of charge.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Macbook Pro 15 Touch Bar

#### Device information:

Type of Mac: MacBook Pro 15 Touch bar
macOS version:  10.13.1
BetterTouchTool version: 2.318

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by OrbitalTech** [comment]
This is now possible to do manually, on the latest alpha version which you can find <a href="https://updates.bettertouchtool.net/alpharls.html">here</a>.

I'll be creating one of my own soon and you'll be able to find it <a href="https://github.com/OrbitalTech/BTT-Scripts">here</a>.
