### ISSUE TITLE
Cannot click anymore in Chrome after some time

### ISSUE THREAD

**Issue by plindelauf** [folivoraAI/BetterTouchTool#1868]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
After some time single clicks in Chrome do not work anymore. Double clicks are interpreted as single clicks. Hover-overs don't work either. I need to quit BetterTouchTool for it to work again.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
* MacBook Pro Touch Bar
* Logitech Mouse on MacBook Pro

#### Device information:

Type of Mac: Pro 15" Late 2016
macOS version: 10.13.1
BetterTouchTool version: 2.318 (702)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Have you modified the force touch settings in BTT? (see this screenshot for the defaults)
<img width="1127" alt="grafik" src="https://user-images.githubusercontent.com/8820811/34062749-8daa9a00-e1ee-11e7-94de-26622da93f95.png">

**Comment by cornelius1** [comment]
I'm seeing a similar issue with version 2.405 with Macbook Pro 2016: tapping and on-hover mouse cursor changes on websites on Chrome (and Safari) become inconsistent or completely broken until an actual click using the trackpad (tapping is not enough). The issue goes away for a while when I restart BetterTouchTool and then comes back in a few hours.

**Comment by cornelius1** [comment]
FWIW, this issue still is there with version 2.417. When it starts happening, everything is affected:
- The dock's magnification effect becomes "frozen" (i.e. isn't updated as you move the mouse pointer along the dock).
- macOS stops highlighting the menu item under the mouse pointer.
- Hovering no longer works in browsers, as mentioned above.

**Comment by plindelauf** [comment]
@fifafu Sorry, I completely missed your question. No, I did not touch those settings. I only added a few touchbar macros.
