### ISSUE TITLE
Move inside the Application Switcher while it is open

### ISSUE THREAD

**Issue by fttx** [folivoraAI/BetterTouchTool#1873]
Hi,

is there a way to have a Windows10-like app switcher using the trackpad?

What i want to achieve is that when i do a swipe right with 3 fingers the following things happen:
1. the cursor get disabled
2. the macOS Application Switcher appears
3. (still holding the 3 fingers over the trackpad) if i move my fingers to the left it moves the selection over the app that is on the left side of the current selection
3. similarly, if i move my fingers to the right it moves the selection to the right of the currently selected app
4. If i move the fingers further, it should keep cycling the selection
5. When i finally release the fingers it closes the Application Switcher
6. The application gets switched and cursor is restored to the previous position

I've tried "Use special application switcher" but in order to move inside the application switcher i've either use the cursor (which is awkward) or keep 3 fingers down and and do a second stroke of the swipe which is more awkward

**Comment by fifafu** [comment]
You can use the special application switcher mode and then e.g. assign the appswitcher action to a three finger click

<img width="1127" alt="grafik" src="https://user-images.githubusercontent.com/8820811/34084424-6d372ac0-e380-11e7-86a2-ec3308cffcb6.png">

<img width="1127" alt="grafik" src="https://user-images.githubusercontent.com/8820811/34084428-82cc98ca-e380-11e7-8d8f-38a8c80c26bc.png">

This will keep the switcher open as long as you touch the trackpad, so you can move your fingers to select the app you want. It doesn't work exactly like in your description though. That's currently not possible and would require BTT to implement its own custom app switcher.

**Comment by fttx** [comment]
I think that is only a matter of detecting the gestures, the mechanism that i've described can be achieved with the sole use of keyboard shortcuts: cmd+tab and cmd+shift+tab or even by the arrow keys. As matter of fact that as long as you don't release the cmd key the app switcher stays open

**Comment by fifafu** [comment]
Actually I think it already works pretty much as you described if you configure it like in the screenshots. Three finger swiping will scroll through the list of apps and releasing the fingers from the trackpad (or clicking) will switch to the app

**Comment by fttx** [comment]
I can't get it to scroll with 3 fingers (click works), but i noticed it only now that if the application switcher is open, and i do a scroll with 2 fingers it actually works natively, but it still isn't perfect because the y-scroll isn't locked.
I use the three finger scroll on my windows laptop all the time, and i think that this feature can save a lot of time especially if you use more than one monitor because it removes the pain of moving the cursor across the monitors
