### ISSUE TITLE
Disable horizontal single finger scolling for ... not working

### ISSUE THREAD

**Issue by dnash21e** [folivoraAI/BetterTouchTool#1876]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Using apple magic mouse.  I want vertical scrolling but not horizontal scrolling.
The Disable horizontal single finger scrolling... option does not work.
I have tried setting it for both global and app specific.  
I have restarted the machine.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
apple magic mouse  A 1296 3vdc

#### Device information:

Type of Mac: MacBook Pro 15-inch-2017
macOS version: 10.12.6
BetterTouchTool version: 2.318

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

<img width="1015" alt="screen shot 2017-12-14 at 8 17 00 am" src="https://user-images.githubusercontent.com/3009096/33999538-fb255130-e0a7-11e7-901c-b0e063683d4e.png">

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by mts749** [comment]
I have the same bug but a workaround is to disable horizontal scrolling on a app specific basis.

MacBook Pro 15-inch-2017
macOS version: 10.12.6
BetterTouchTool version: 2.313

**Comment by dnash21e** [comment]
Thanks.  I have also tried that but was unable to disable it - even on an app specific basis.   Maybe I'm missing something?

**Comment by mts749** [comment]
It seems to work some of the time and not other times and 0 times with Excel (arggh!) 
No discernible pattern that I can perceive. It would be good to have a proper fix if possible.
