### ISSUE TITLE
Enhancement Request:: Be able to move a window to a mouse position - to facilitate moving a window to a specific Monitor. 

### ISSUE THREAD

**Issue by brianliddle** [folivoraAI/BetterTouchTool#1878]
Currently, you can move your mouse to any monitor using the "Move mouse to cursor position".   What would be infinitely more useful, would be to move a window to a cursor position - i.e. orchestrate which monitor (as well as place in the monitor) a Window should go.

**Comment by fifafu** [comment]
In v2.460 (alpha) there is a new predefined action which can do all sorts of custom window moving and resizing:
![image](https://user-images.githubusercontent.com/8820811/39365653-08ef6b04-4a32-11e8-98be-4befc40b4506.png)

It can also move a window to the screen the mouse cursor is on (although not yet to exact the mouse cursor position. I'll add this with the next version.
