### ISSUE TITLE
BetterTouchTool causes Notification Center slide out by itself every now and then

### ISSUE THREAD

**Issue by MilooHub** [folivoraAI/BetterTouchTool#1879]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Recently, Notification Center on the right will slide out by itself every now and then without me doing any thing. The timing for this to happen is sort of unpredictable since sometimes it happens while I am typing on keyboard, sometimes I am not even touching my Macbook Pro at all. And sometimes it happens in the morning, sometimes afternoon or evening.

When Notification Center slides out by itself, it may interrupt my normal workflow, say I am trying on TextEdit then the focus move to Notification Center on the right side, then I have to slide it away so I could get back to my work with TextEdit. When this keeps happening(sometimes twice every 5 minutes), it gets really annoying!

The reason I suspect BetterTouchTool is causing this Notification Center issues, is I have tried to quit all other apps/daemons I am running on my Macbook Pro one by one, the issue remains until I quit BetterTouchTool, then the issue never come back for whole day.

BTW, I also have setup Multiple Space/Desktop via Apple's Space feature, and I have installed TotalSpace2(bought a single user license), I do not know if Spaces feature cause some conflicts with BetterTouchTool.

Hopefully this could be fixed asap, and I would love to provide further details if needed.

Also thank you for developing such an god-send app, it is a life saver and a must for me in my everyday workflow now. So I sincerely hope this Notification Center slide out bug could be squashed soon.

All the best.
#### Device    ###information:

Type of Mac:Macbook Pro, Retina, 15inch, Mid 2015
macOS version: 10.13.2
BetterTouchTool version: 2.318(702)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Do you have the "Show Notification Center" action configured in BTT?
Or maybe you accidentally trigger the system's two finger swipe from the edge gesture? You can disable that in System Preferences => Trackpad => More Gestures

**Comment by MilooHub** [comment]
It turns out there is a trigger called **Bluetooth LE Device Came Close** somehow setup on my BTT which is associated with **Show Notification Center** under `Other` tab.

I remove that and the annoying problem resolved!!

Thanks for the hint!
