### ISSUE TITLE
After rebooting my MacBook, clicking on the touch bar does not work. The BTT app will not work until you restart it.

### ISSUE THREAD

**Issue by rjudy** [folivoraAI/BetterTouchTool#1880]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
After rebooting my MacBook, clicking on the touch bar does not work.
The BTT app will not work until you restart it.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
After rebooting my MacBook, clicking on the touch bar does not work.
The BTT app will not work until you restart it.

#### Device information:

Type of Mac: MacBook Pro 13.3 Touch Bar 3.1gHz i5(2017)
macOS version: 10.13.2
BetterTouchTool version: 2.318(702)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
After rebooting my MacBook, clicking on the touch bar does not work.
The BTT app will not work until you restart it.

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
In general BTT should restart automatically after sleep.
Could you check via activity monitor whether the "BTTRelaunch" app is running?

**Comment by jBellree** [comment]
Hi,

When my MacBook Pro goes in to sleep, the better touch app doesn't work on waken, you have to launch / start it again. To answer your question above, yes the "BTTRelaunch" app is running. 

The first image is whats running as soon as my Mac comes out of sleep, the second is after I've restarted BetterTouch. 

Hope this helps.


<img width="556" alt="screen shot 2017-12-21 at 16 32 52" src="https://user-images.githubusercontent.com/34748375/34265227-395a89a0-e66d-11e7-8f8e-3f7d11b763eb.png">



<img width="563" alt="screen shot 2017-12-21 at 16 33 10" src="https://user-images.githubusercontent.com/34748375/34265226-3931e7b6-e66d-11e7-97b9-ce4fe630e24e.png">
