### ISSUE TITLE
Feature request: Update initial value of Custom Apple Script Slider

### ISSUE THREAD

**Issue by horvathb** [folivoraAI/BetterTouchTool#1881]
I use a Custom Apple Script Slider to adjust iTunes sound volume. It'd be useful if the initial value would update every X seconds (like the Run Apple Script and Show Return Value widget does).

The issue is that if for whatever reason iTunes sound volume is changed not via the widget, this will not be reflected in the state of the slider.

**Comment by fifafu** [comment]
Yep, good idea. I'll add this soon!

**Comment by horvathb** [comment]
Great, thanks! This would also allow us to create a slider to show player position.
