### ISSUE TITLE
Name of keyboard key functions / Make actions accessible from Apple Script

### ISSUE THREAD

**Issue by hekevintran** [folivoraAI/BetterTouchTool#19]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:
It would be very helpful for me to have BetterTouchTool actions accessible via command line or Applescript.  My situation is that I have 2 Macs.  One is connected to my projector as a media centre.  The other operates as my remote control by logging into the first Mac via VNC.  I want to be able to control the volume on the first Mac through the second Mac’s volume keys.  I was able to hack together a solution by calling Applescripts wired up to the volume keys using Quicksilver triggers:

set vol to output volume of (get volume settings)
if vol > 90 then # 100 max
	set volume output volume 100
else
	set volume output volume (vol + 3)
end if

This works but the problem is that this script does not call the "native" volume functions that are called by default when you press the volume keys and so the visual volume indicator does not display.  I have 2 basic questions:

1) Can you point me to information on how to call these "native" functions?  In BTT they are listed under the Keyboard Keys menu of the Trigger Predefined Action menu.  I’ve looked around hard and cannot find these functions.  I assume the must be calls to some Cocoa framework.

2) Is it possible for BTT to expose the Keyboard Keys actions to the command line or to Applescript so that I can call into them from my setup?

**What kind of Mac are you using?**
MacBook Pro 2012 13"

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
N/A

**Which version of macOS are you running?**
10.11.6

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by rodgerwerner** [comment]
Hmm, this might be hard to do, as the bezel services seem to be tied to one login and stored for subsequent boots. Basically, the 'feature' would have to both SHOW and ALTER the values on another computer ... I don't think the bezel server can work like that.

https://robert.sesek.com/2016/3/bezelservices_on_os_x.html

**Comment by fifafu** [comment]
Hi,

good idea, I wanted to make the actions accessible from outside of BTT anyways.
For now you could just assign some other keyboard shortcut to trigger them, then trigger that shortcut from Apple Script.

Best,
Andreas

**Comment by hekevintran** [comment]
@rodgerwerner Thanks for the link describing BezelServices.  This was what I was looking for.  I just didn't know what the OS called it.  I agree with you that getting one Mac to control another's BezelServices probably wouldn't work.  This isn't exactly what I'm trying to do though.  I'm just trying to get a way to bind a custom key to a BezelServices event (volume up/down).  This way I could hit the custom key through VNC on the second Mac, thus controlling the volume on the first Mac :).

**Comment by fifafu** [comment]
I'm closing this old issue.
Recent BetterTouchTool versions have added multiple scripting capabilities:
https://docs.bettertouchtool.net/docs/scripting_btt.html
