### ISSUE TITLE
“Unlock Screen” action sometimes writes the password twice, potentially causing it to be disclosed

### ISSUE THREAD

**Issue by izeau** [folivoraAI/BetterTouchTool#1903]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

“Unlock Screen” action sometimes writes and enters the password twice. This can cause the password to be sent to an opened software: Mac unlocks, BTT types the password again in the foreground window (e.g Slack) and hits enter automatically.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

—

#### Device information:

Type of Mac: MacBook Pro (Retina, 13-inch, Early 2015)
macOS version: 10.13.1
BetterTouchTool version: 2.318 (702)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

I’m using _alt + 4 finger force click_ to unlock the screen.
The only workaround I’ve found yet is to use an innocuous word as a password…

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by Benimation** [comment]
I've had the same problem. It actually happened a few times that my password (or parts of it) got send in a private message to someone..

Type of Mac: MacBook Pro (Retina, 15-inch, Mid 2014)
macOS version: 10.13.2
BTT version: 2.318 (702)

I'm using a tap sequence to unlock, so it seems the problem is entirely in the performed action.

**Comment by SylvainCecchetto** [comment]
Same bug here :

Mac: MacBook Pro (Retina 13 pouces, début 2015)
macOS: 10.13.2
BTT version: 2.332

Gesture: 3 fingers click swipe up
