### ISSUE TITLE
UI sluggish when plugged into LG 34UC99-W Monitor

### ISSUE THREAD

**Issue by cdeutsch** [folivoraAI/BetterTouchTool#1905]
#### Description of bug/feature request/question:

When my MacBook is plugged into my external monitor via USB C, the `WindowServer` process spikes and dragging around windows (especially Chrome tabs) because super slow eventually crawling to an almost lock up.

Everything is fine when not connected to the monitor.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

When plugged into the monitor I also use a Microsoft Ergonomic 4000 keyboard and Logitech G502 mouse.

I'm running a VMWare Fusion VM in the background.

#### Device information:

Type of Mac: MacBook Pro (15-inch, 2017) with TouchBar
macOS version: 10.12.6 (16G1036)
BetterTouchTool version: 2.320

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

I've tried disabling most of BetterTouchTools features with no luck.

I primarily use BetterTouchTools to remap keyboard input and have a couple of TouchBar modifications.

Turning off the TouchBar feature didn't change anything.

Diagnostic info
[BetterTouchToolDebug.zip](https://github.com/fifafu/BetterTouchTool/files/1572723/BetterTouchToolDebug.zip)

**Comment by fifafu** [comment]
Does turning off BTT competely solve the issue?
Apple has improved window server performance a lot with macOS 10.13

**Comment by cdeutsch** [comment]
> Does turning off BTT competely solve the issue?

Yes, quitting BetterTouchTool solves it. (I'll play around with quitting other apps to see if it's a bad combo of apps)

> Apple has improved window server performance a lot with macOS 10.13

Good to know. I may upgrade over the holidays. Thanks 👍
