### ISSUE TITLE
Two-finger Tip-taps don't work anymore

### ISSUE THREAD

**Issue by spaceshipcamp** [folivoraAI/BetterTouchTool#1917]
Description: 
The very first feature I ever used on BTT was "tip-tap right" and "tip-tap left". I used those gestures to toggle left and right between open tabs in Chrome, Safari, and Finder. They don't work anymore. I've tried everything I can for months. 3-finger "tip-taps" work fine but 2-finger tip-taps do not.

Affected input device: 
MacBook Trackpad

Device information:
MacBook Pro
macOS version: MacOS 10.13.2
BetterTouchTool version: 2.320 (750)

**Comment by fifafu** [comment]
Strange, they work fine here. Maybe check if you modified the tip tap settings in the advanced trackpad prefs.

If you can't figure out what's wrong please go to the about tab in BetterTouchTool and click the "export debug information" button. This will create a folder called BetterTouchToolDebug on your desktop. Send that to boastr.net@gmail.com, then I'll be able to tell why it isn't working.

**Comment by BClev** [comment]
I had this same issue for the past 6 months, but then just now I found that "Compatibility mode" was enabled in the "App Specific" settings for Chrome. I disabled it, and now tip-taps work perfectly.
