### ISSUE TITLE
Apple Remote (Silver) stops responding after few minutes!

### ISSUE THREAD

**Issue by gepohe** [folivoraAI/BetterTouchTool#192]
Apple Remote (Silver) stops responding after few minutes!

Hi guys,
I do not know when it started exactly but for a long time my Apple Remote stops responding to BTT gestures as well as factory default gestures after few minutes of working perfect.

The remote works fine when I boot up in safe mode,
I have changed the battery of Remote as well..
Any more suggestion are welcome..

It is really starting to annoy me as I use BTT only for remote gestures..
Thanks in advance

I use MacBook Pro Late 2011 (8,1)
Running macOS Sierra 10.12.2
BTT version of 1.963 (552)

**Comment by fifafu** [comment]
This issue was moved to https://community.folivora.ai/t/apple-remote-silver-stops-responding-after-few-minutes/88

**Comment by fifafu** [comment]
Sorry, please ignore the previous message. The migration didn't work correctly, for now the issues will stay here.
