### ISSUE TITLE
REQUEST: Keyboard Sub-Division

### ISSUE THREAD

**Issue by nivek88** [folivoraAI/BetterTouchTool#1938]
#### Description of bug/feature request/question:
Is it possible to implement some kind of a sub-division for the keyboard, distinguishing the internal Macbook keyboard and external (bluetooth) keyboards? 
Cause mainly I'm using my MBP closed on an external display, with an external mouse and keyboard from Apple. Due to the fact that the external keyboard isn't backlit the keys F5 and F6 don't have a direct function, thus I've added a shortcut for one of them to trigger an app. 
But when I'm using the MBP as laptop with the internal keyboard again I need to deactivate the BTT to change the backlight and reactivate the BTT again. 
So implementing an inquiry to distinguish between internal and external keyboard would be very helpful. There's already a similar function/inquiry implemented for the trackpad shortcuts what is working quite fine :)

#### Affected input device:
Keyboard

#### Device information:

Type of Mac: MBP 13" Late 2013
macOS version: 10.12.6
BetterTouchTool version: 2.318

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
[Bildschirmfoto 2017-12-29 um 17.27.08.pdf](https://github.com/fifafu/BetterTouchTool/files/1593489/Bildschirmfoto.2017-12-29.um.17.27.08.pdf)
[Bildschirmfoto 2017-12-29 um 17.27.26.pdf](https://github.com/fifafu/BetterTouchTool/files/1593490/Bildschirmfoto.2017-12-29.um.17.27.26.pdf)

**Comment by miechu** [comment]
Yeah, I'd second that - different keyboard layouts on my macbook's keyboard and on logitech's one. Therefore media keys are labeled differently.
