### ISSUE TITLE
Current battery level %0

### ISSUE THREAD

**Issue by Troglos** [folivoraAI/BetterTouchTool#1946]
#### Description of bug/feature request/question:
Current battery level %0

#### Affected input device
Magic Mouse 2

#### Device information:
Type of Mac: Mac mini (Late 2014)
macOS version: High Sierra
BetterTouchTool version: 2.320 trial

#### Additional information 
I was gonna buy it just to change the low battery level warning percentage, but obviously if you don't fix it...

**Comment by drivenfaroff** [comment]
Same issue in 2.500 on iMac (Late 2015) running High Sierra.

Under Advanced > Mouse settings, current batterylevel: 0%.

Wanted to use this to adjust low battery warning to something like 10%. But the notification isn't working probably because of this issue.
