### ISSUE TITLE
Ignore areas only work with the Magic Mouse, not the trackpad from the 2016 MacBook Pro

### ISSUE THREAD

**Issue by Grolubao** [folivoraAI/BetterTouchTool#196]
Hi,

I would like to use the "Ignore Areas" defined in the section "Mouse" to apply also to my trackpad. Essentially the trackpad from the 2016 is too big, and I would like to make it smaller since I'm accidentally clicking the edges of the trackpad too often. If this feature also worked for the trackpad that would solve my problems.

It seems this works only for the BTT gestures, but it would be great if it could completely ignore those areas system wide

Thanks,
Rafael

**Comment by Grolubao** [comment]
@fifafu Could you please tell me if this is going to be implemented? I hear many people complaining about the size of the trackpad and would be great if we could just shrink the trackpad size via BTT

**Comment by fifafu** [comment]
Not sure yet

**Comment by Jimgitsit** [comment]
Would love this feature as well. I miss being able to rest my thumb just below the spacebar. Would like to basically disable about half an inch along the top of the trackpad.

**Comment by monstermac77** [comment]
Completely agree. Due to the trackpad's size increase on the 2016 Macbook Pro, my normal typing position has the base of my left thumb resting on the upper left corner of the trackpad pretty much all the time. It's driving my crazy. I'd say every 3 minutes I have to consciously lift my hand to get it off of the trackpad because a either a gesture, or even scrolling or pointing isn't working because of the extraneous input.

**Comment by cocoahuke** [comment]
@Grolubao
@fifafu  
@Jimgitsit 
@monstermac77 
Everyone check out my work! This is the solution of adjust Trackpad to any size.
[https://github.com/cocoahuke/shrink_trackpad](https://github.com/cocoahuke/shrink_trackpad)

**Comment by Grolubao** [comment]
> @Grolubao
> @fifafu
> @Jimgitsit
> @monstermac77
> Everyone check out my work! This is the solution of adjust Trackpad to any size.
> https://github.com/cocoahuke/shrink_trackpad

Mate, thank you so much, works wonders! This is what I was looking for ages! Will throw in a couple bucks on you. Cheers!!!!! 💃

**Comment by monstermac77** [comment]
> @Grolubao
> @fifafu
> @Jimgitsit
> @monstermac77
> Everyone check out my work! This is the solution of adjust Trackpad to any size.
> https://github.com/cocoahuke/shrink_trackpad

Wow, really cool stuff! I'll try it out when I have the time to configure it. Thanks for your work on this!
