### ISSUE TITLE
BTT gestures don't seem to work to activate the Evernote Web Clipper extension in Chrome

### ISSUE THREAD

**Issue by dorindon** [folivoraAI/BetterTouchTool#1971]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Hello,
I have been using the Evernote Web Clipper extension for Chrome for many years.
It is possible to define a keyboard shortcut to activate it, which works perfectly.
Since I often use it, I wanted to create a BTT gesture with a single action: assign the keyboard shortcut corresponding to the evernote web clipper.
I am unable to ascertain why it does not work.
I tried:
- changing the shortcut
- restarting both Chrome and BTT many times.
This does not make sense and has not happened to me before with BTT.

Is there perhaps an alternative way to activate a Chrome extension with BTT?

Please note that it is **not useful to activate the extension via the context menu**: when activated via the context menu, the page is sent to evernote automatically, and the user is not given the opportunity to change the title, specify the notebook, tags, etc. t

thanks very much for your time and help

#### Device information:

Type of Mac: IMAC retina
macOS version: 10.12.6
BetterTouchTool version: 2.318
latest Apple Magic Trackpad

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
This seems to be a bug in the webclipper extension as it only reacts to one kind of shortcuts. However I think it works when using the "Send Shortcut to specific application" predefined action. (As this simulates the keys using another technique).

![image](https://user-images.githubusercontent.com/8820811/36026811-feea23e0-0d98-11e8-99af-437888f905d9.png)

**Comment by fifafu** [comment]
In case this also doesn't work you can try enabling compatibility mode for chrome, which tries to simulate real key presses (can be problematic in some situations)

![image](https://user-images.githubusercontent.com/8820811/36026877-38678bf8-0d99-11e8-9de4-2b95a6e24c0b.png)
