### ISSUE TITLE
Preview.app resize / move using modifier + mouse (depends on pointer position)

### ISSUE THREAD

**Issue by jvlatzko** [folivoraAI/BetterTouchTool#1976]
#### Description of bug/feature request/question:

macOS' Preview app for PDF etc. does not comply with BTT's settings for resize/move. I've configured windows to move with ctrl+pointer and resize with alt+pointer, which works beautifully (and was the reason I've donated 5+ years ago :-) )

I found it depends on where the curser is when the action is initiated. If it rests on app interface (say, the top bar or the scroll bar), all is as expected. 
If however, the pointer is located inside the displayed content (say, a PDF), nothing happens. 

I expect this to be a fuc*up on Apple's side? 

#### Device information:

Type of Mac: Retina MacBook Pro late 2014
macOS version: 10.13.2
BetterTouchTool version: 2.318 (702)

**Comment by jvlatzko** [comment]
What I meant to say among the bug report: thanks again for your fantastic work =)

**Comment by justin-r-r** [comment]
I experience this, but intermittently. (and I also concur on the awesome work on BTT!!)

Perhaps related: PDF documents viewed from within the Safari app display this problem, too (and sometimes even when I'm not experiencing the issue in Preview). As jvlatzko said for Preview, in Safari the issue also only occurs when the mouse position when starting the move/resize is *within* the PDF. It works fine when the mouse starts on the menubar, or even the small grey border area surrounding the PDF.

My modifier keys are the same as jvlatzko.

Type of Mac: iMac 5k 2014 and MacBook Air early 2015
macOS version: 10.13.2
BetterTouchTool version: 2.318
