### ISSUE TITLE
BTT Remote port keeps changing

### ISSUE THREAD

**Issue by pighair** [folivoraAI/BetterTouchTool#1978]
#### Description of bug/feature request/question:

BTT Remote's port changes time to time without any my action, so it's hard to use it when I'm not at my home.
I have a NAS so I set DMZ server setting to the NAS in my router. So I need to set port forwarding to access BTT Remote on my Mac.
But at most of trial I can't connect because port has been changed. Of course I can set it by accessing my Mac via VNC, and find port number, and change my router setting, but it is not practical at all.

Can I have firm port number for BTT remote? I tried to find any menu to set it but failed.
Or is there any neat solution for my case?

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
N/A

#### Device information:

Type of Mac: Mac Pro (mid-2010)
macOS version: 10.13.2
BetterTouchTool version: 2.318

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
In general the port number should be fix, BTT selects one at random when it first starts up and saves it. Only when the port is already taken/blocked BTT chooses a new one.

Are you maybe having two separate instances of BTT installed?
