### ISSUE TITLE
Allow to search jump on items inside `Show Menubar in Context` window

### ISSUE THREAD

**Issue by nikitavoloboev** [folivoraAI/BetterTouchTool#1981]
#### Description of bug/feature request/question:
In `Show Menubar in Context` action when you activate it first time and see this:

![2018-01-12 at 15 58](https://user-images.githubusercontent.com/6391776/34880675-7c7b0e6c-f7b1-11e7-85ad-5bdc23a69d2b.png)

I would like to be able to type `H` and `History` menu to be activated: 

![2018-01-12 at 15 59](https://user-images.githubusercontent.com/6391776/34880711-9a2e437a-f7b1-11e7-8cc8-495d725be4fd.png)

Currently when I do it nothing happens. However this feature works when trying to do it inside any of the menu bar items like here: 

![2018-01-12 at 16 00](https://user-images.githubusercontent.com/6391776/34880765-c51ee9c2-f7b1-11e7-8c9b-9645e819693e.png)

I can start typing `sh` and `Share` menu will be activated.

Thank you a lot if you do add this feature. It would be incredibly useful.

**Comment by fifafu** [comment]
Good idea, I'll add this!
