### ISSUE TITLE
Modifier-key move windows function doesn't work for spacebar-preview windows

### ISSUE THREAD

**Issue by sorttouchtool** [folivoraAI/BetterTouchTool#1982]
#### Description of bug/feature request/question:

The "modifier key" to move windows works for all windows except for spacebar-preview (the popup preview of a file that you get when you press spacebar). In other words, I use the "fn" key to move windows, and all windows will obey and start moving when I use this key and trackpad, except for the spacebar-preview window.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Macbook Trackpad w/keyboard

#### Device information:

Type of Mac: Pro Retina 15 2017
macOS version: 10.13.2
BetterTouchTool version: 2.318

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Unfortunately this is a bug in the preview window, as it doesn't correctly implement the necessary API. I'll report it to Apple, but not sure whether they will fix it...

**Comment by justin-r-r** [comment]
FWIW, I'm not experiencing this problem. I use "ctrl" as my modifier key for window dragging in BTT. iMac 5k 2014
macOS version: 10.13.2
BetterTouchTool version: 2.318

**Comment by sorttouchtool** [comment]
By the way, I found that it also doesn't work for certain safari windows depending on the content. Specifically, I noticed when I am in a safari window with a PDF open in the browser, it will not drag the window if my cursor is on the PDF.

**Comment by justin-r-r** [comment]
I am experiencing the Safari/PDF issue as well. Also in the Preview app (different than the preview window described here) and in Excel. Maybe this incorrect API implementation is fairy widespread. 😣

**Comment by justin-r-r** [comment]
Thanks, Andreas! Keep up the insanely incredible work!
