### ISSUE TITLE
BTT remote Auto Connect

### ISSUE THREAD

**Issue by knoajp** [folivoraAI/BetterTouchTool#1984]
When there is only one computer to connect to, I want BTT remote automatically connect to the one.

**Comment by fifafu** [comment]
Good idea, I'll add this.
Tip: If you "force touch" the BTT icon on the iPhone there is an option "reconnect to last used mac" which might be helpful for you.

**Comment by knoajp** [comment]
Thank you very much. Glad to hear that.
(Unfortunately, currently I'm using iPhone SE of no force touch :-)
