### ISSUE TITLE
[Bug] System Colours (NSColor)

### ISSUE THREAD

**Issue by n0mar** [folivoraAI/BetterTouchTool#1985]
### EXPLANATION 

I’m trying to make the Touch Bar have *native* colours. For example, in Logic Pro, the Touch Bar correctly displays the colours as intended

### HOW TO REPLICATE

1. Open the colour picker (i.e. "TouchBar Button Color”)
2. In the colour picker, choose the third tab: **Color Palettes**
3. Choose the Developer color palette via the dropdown menu
4. Select a system*x*Color
5. Save

### THE PROBLEM

The Touch Bar does not respect the system colour, and instead, as Apple insists *not* to do, hardcodes the hex/RBG value.

Please see for more:
[Visual Design - Touch Bar - Human Interface Guidelines for macOS Apps](https://developer.apple.com/macos/human-interface-guidelines/touch-bar/touch-bar-visual-design/)

---
---

#### Device information:

Type of Mac: MacBook Pro 2016 Touch Bar
macOS version: macOS High Sierra Version 10.13.2 (17C205)
BetterTouchTool version: Version 2.318

**Comment by fifafu** [comment]
I'll improve this soon. Currently BTT stores the color as a rgba string so people can edit it in the JSON export, but it causes issues like this. I think I'll switch to storing the archived NSColor directly, which is not human readable but accurate.
