### ISSUE TITLE
Second click as three click not working at finder

### ISSUE THREAD

**Issue by cinges** [folivoraAI/BetterTouchTool#1989]
**Description of bug/feature request/question:**
Secondary(right) click does not work sometimes in finder. I have set three fingers click as secondary click (secondary click is turned off in setting) and from time to time its not reacting to three finger click in finder, or dock, or desktop. I must go to another desktop, where is chrome, use there three finger click, and then go back and use it again and then it works (see video https://www.youtube.com/watch?v=m2ZHx37V08E )(*Update* - now going to another desktop wont help, only restart of BTT). 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Macbook Trackpad and also Magic Trackpad 2

#### Device information:

Type of Mac: Macbook Pro 15 mid 2015
macOS version: 10.13.2
BetterTouchTool version: 2.324 (709)

**Comment by fifafu** [comment]
Could you check if disabling thumb handling fixes your issue? Possibly BTT thinks one of your fingers is a thumb and doesn't allow the three finger click because of that.

![image](https://user-images.githubusercontent.com/8820811/35733649-80df7132-081e-11e8-8121-4c96b3d33142.png)

**Comment by cinges** [comment]
Its dissabled all the time, because I thought that can cause this problem :) Don't have idea, what can cause problem, its like every every time in finder its not working... 
![screen shot 2018-02-03 at 11 22 03](https://user-images.githubusercontent.com/30551743/35766261-1aeb1658-08d5-11e8-91f8-681cea91f06c.jpg)
