### ISSUE TITLE
Stream keystrokes

### ISSUE THREAD

**Issue by iTechieGuy** [folivoraAI/BetterTouchTool#2006]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

An additional feature, the "streams" keystroke. If someone would check the Steam Keystroke command, if the gesture is triggered, a somewhat continuous stream of the Keyboard action would continue until the gesture stopped.

For instance, in both Pixelmator and Pixelmator Pro, the "[" and "]" keys control the size of the brush. If I wanted a big change in the size of the brush using a gesture /action from BetterTouchTool, I currently wound have do multiple gestures. With the "stream", as long as I was doing the gesture, The action would be signaled.  

Probably would be good include some type of speed control which would control of the triggering rate.

#### Device information:

Type of Mac:
macOS version: 
BetterTouchTool version: 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
It's a good idea, but currently most BTT gestures are "discrete" so they don't track the state of the gesture. I plan to change this in the future, but it will take a while until this will become possible.
