### ISSUE TITLE
Add input (command line or flags) for script based widgets

### ISSUE THREAD

**Issue by clayshieh** [folivoraAI/BetterTouchTool#2016]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Add input (command line or flags) for script based widgets so that widgets can use user input in scripts. 

Specifically, I currently have a widget that displays the SSID of the network my mac is currently connected to because it saves clicks from having to click on the wifi in the menu bar to see what I'm connected to but I've been wanting to write a button/widget group that allows me to display and connect to a few SSID's that I prefer based on the SSID that I commonly get connected to first at different locations. The addition of shell script is very useful but there is currently no support for actions after pressing a widget button. Would it be possible to add support for input arguments or flag input for widgets? I'd imagine that widgets would also thus need to be support having a value assigned to it such as it's last return value or it's current displayed text to use as the flag input.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Touch Bar

#### Device information:

Type of Mac: MacBook Pro (15-inch, 2017)
macOS version: 10.12.6
BetterTouchTool version: 2.332 (713)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
You already can trigger actions when pressing the widget button (just assigning a predefined action).

However I'm not sure how you would want to gather the user input. You mean it should just pass the current widget value to the action?

So for example look at this screenshot:
![image](https://user-images.githubusercontent.com/8820811/35729851-4715cc48-0810-11e8-9081-8be727708a47.png)

Would you like the shell script action to get the current widget value as input? Or are you looking for something else? (I think I may not have fully understood your usecase)

**Comment by clayshieh** [comment]
I'll explain what I'm trying to achieve in detail.

I currently have a widget that uses a shell script to display the current network that I am connected to. I would like to set it up so that I can press the widget and it open a "widget group" with each widget displaying the SSID of nearby networks from something like `/.../airport -s`. I would then like to be able to press one of the widget buttons with the SSID that I want to connect to and have it run a shell script with its current display value as an argument (i.e. network1 so that I can execute something like `networksetup -setairportnetwork en0 network1`) to change my current network. 

An argument with it's current display value is needed because the SSID's nearby is dynamic and should ideally be the display value of the widget itself. Please let me know!

**Comment by clayshieh** [comment]
And just to add on to that, because widgets constantly run scripts to show the return value this feature request would also need to allow buttons to execute shell scripts upon being pressed rather than being constantly run

**Comment by OrbitalTech** [comment]
This is something I am working on myself. It will be possible soon, as the developer is adding new features. If you're interested in doing this for yourself, see <a href="https://updates.bettertouchtool.net/alpharls.html">this</a>. Under alpha 2.426 you'll see how you might make something like this. New features are being added frequently, so if I were you, I'd hold off for a little while longer.

Some personal notes on this specific project:
In order for this to work, you're going to need to get the password from the keychain. This feature will never work for enterprise networks because enterprise networks require user/pass which the networksetup commands don't deal with.

I personally am using a lot of Applescript to do all of my buttons, and using `do shell script "networksetup -setairportnetwork en0 network1" ` for running my shell scripts.

**Comment by clayshieh** [comment]
@OrbitalTech thanks for the heads up! I would not have noticed otherwise. In my opinion, I think it'd also be useful if there was no distinction between buttons and widgets because then you'd be able to combine button groups with widgets which would be the equivalent to a widget group.

**Comment by clayshieh** [comment]
@OrbitalTech ah sorry for the confusion. I'm talking about the ability for a widget to have the functionality of being able to display a value from a script AND being able to open a button group. I believe currently you can only do one or the other but not both at the same time. 

Right now I have a widget displaying the SSID of the network I'm connected to but I'd like to be able to press said widget and expand it into a group that displays lets say 3 other widgets that I could press to connect to networks that depends on what the previous value of the widget was. Might be niche for my case but I always have the problem where my mac connects to xfinity wifi first (even though its priority is lower but I guess it just shows up first?) and because i know i only see xfinity when I'm at home or something then I'd like to be able to press the widget that displays xfinity and present me with widgets that allow me to connect to my home network based on the fact that the value of the widget was xfinity. 

That being said, it probably isnt possible to create a clean way of doing this because there doesn't seem to be a way to dynamically create widgets so it might just have to be done statically for now where I statically display options based on the value passed into it or something. Not sure gonna have to look at what I can do.

**Comment by fifafu** [comment]
This will be possible with the next version although it'll be a bit complicated to set up :-)
Attached a working copy of the documentation for that (not yet finished and not online yet).

The current alpha doesn't support most of it, but the next one should be quite powerful.
[apple_script.pdf](https://github.com/fifafu/BetterTouchTool/files/1891860/apple_script.pdf)

**Comment by OrbitalTech** [comment]
Well, there is a semi clean way to do this. The way I've been doing this so far:
I have like 10 buttons, and they all have the same script. Their script gets the _n_th wifi network and displays its name. Upon tapping them, the predefined action is set to run applescript where it uses the networksetup command to connect to the _n_th network.

As for having a display value script and opening a button group, just follow this:
<img width="819" alt="screen shot 2018-04-10 at 9 04 01 am" src="https://user-images.githubusercontent.com/23006558/38523062-86daa00c-3c9e-11e8-9a6b-12cc14e36808.png">
Now your widget is set up, use the predefined action "Open TouchBar group with name".
<img width="369" alt="screen shot 2018-04-10 at 9 04 10 am" src="https://user-images.githubusercontent.com/23006558/38523090-985acb7c-3c9e-11e8-92b2-6acee570bd54.png">
I'm not so sure about hiding the group, but I'm sure you could hide the group in another group. Give it a name like "    " and set its colour to #000000.

As for your X-finity, I'm not in the US but last time I was there I remember it having a web log in? If its lower in the list, just remove it from your network preferences like so:
<img width="528" alt="screen shot 2018-04-10 at 9 10 04 am" src="https://user-images.githubusercontent.com/23006558/38523245-feff83f4-3c9e-11e8-8991-d198109c90c2.png">

Just click the minus.

As I said before though, and as Fifafu has just said, the newest alphas are coming out with more and more useful applescript functionality. I asked in past and Fifafu has confirmed that there will be the ability to add buttons using applescript.

**Comment by clayshieh** [comment]
@fifafu it does indeed look a bit complicated but its great to see that the support for custom functionality is being added. Thanks so much for making it possible and I look forward to the updates!

@OrbitalTech yeah thats approximately what I had in mind, what I meant by clean way was dynamic widget generation rather than having to do hard coded based widgets. As for the xfinity issue, its not that I don't want to connect to the network permanently (I still do when it's available and nothing else is) it's more of a corner case of when my computer sometimes connects to it first when I'm at home rather than my main wifi which a widget displaying my currently connected network has saved me a considerable amount of time because of the slow action of having to check which wifi I'm connected to by clicking my menu bar. 

But all in all I think we were both trying to solve the same general problem and I'd be more than happy to share my configuration with you here once the patch is out and stable and I write it up!
