### ISSUE TITLE
Toggle switch for any switchable thing.

### ISSUE THREAD

**Issue by squirrel2000thefuturesquirrel** [folivoraAI/BetterTouchTool#2023]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

Hi! Nice tool, I am just finding my way around.

I am trying to make a wifi toggle switch on one key, so that after you push it and turn the wifi on it will then turn the same button into an off button. This switch function is obviously super useful for almost anything that works like that!

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Touch Bar 

#### Device information:

Type of Mac: 15" 2017 MacBook Pro
macOS version: 10.13.2
BetterTouchTool version: 2.332

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by Worie** [comment]
+1 

That would be really nice to have, but I'm not sure how easy it would be to implement. Currently I have a workaround for that, using TouchBar widget that runs Apple Script which toggles the state. I did it for the bluetooth button, but toggling it isn't really neat (preferences pane has to be shown for a frame or so, the button is click and then it closes).

**Comment by fifafu** [comment]
The problem is that many things are "switchable" but BTT would always need to check whether a switch has occured outside of BTT. (I.e. You toggle your wifi off in BTT, but turn it on again via the menubar.

Thus it's not possible to add a generic solution for that. 

However I will soon add some helper functions that will make it possible to easily implement stuff like this.

**Comment by DavidChenware** [comment]
Are these `helper functions that will make it possible to easily implement stuff like this` in a current version of BTT yet?

**Comment by fifafu** [comment]
BetterTouchTool is now quite scriptable and allows you to implement things like this, e.g. using the variables http://docs.bettertouchtool.net/docs/apple_script.html
