### ISSUE TITLE
Second monitor snap area behavior incorrect with uBar

### ISSUE THREAD

**Issue by chrisjcameron** [folivoraAI/BetterTouchTool#2030]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Using a Finder window as the test case, the window does not snap to the snap area outline on the second monitor:

When 1) uBar is showing and 2) the top of the second screen is not aligned with the top of the main screen and 3) the secondary screen has fewer (effective) pixels that the main screen, the window does not fill the full length of the snap area (sometimes less than half). The final length of the snapped window seems to depend on how much the top of the main and secondary screens are misaligned. The width snaps correctly.

When 1) uBar is showing  and 2) the secondary screen has more pixels than the main screen, the window fills the snap area but fails to allow room for uBar toolbar. The snapped window is partially beneath the uBar. 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
30" Cinema HD (2560x1600) as main, 2013 rMBP (scaled, one tick towards "more space") as secondary. Incorrect snapping is observed on second screen only; When Cinema is secondary, the snapping is incorrect on Cinema. 

#### Device information:

Type of Mac: rMBP 2013
macOS version: 10.12.6 (16G1114)
BetterTouchTool version: 2.332 (713)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
Can provide screen captures if needed. 

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by chrisjcameron** [comment]
PS: Confirmed to persist after a system reboot.

**Comment by fifafu** [comment]
Thanks for reporting, I'll look into it :-)

**Comment by ethantang93** [comment]
Yes, I ran into the same problem. I am using a 2015 13' Macbook Pro
