### ISSUE TITLE
[Feature Request] Ability to open touch bar button groups when modifiers are set  or are set for other apps

### ISSUE THREAD

**Issue by amatrosovas** [folivoraAI/BetterTouchTool#2036]
Ability to open touch bar button groups that have modifiers or are set for other apps would add a great deal of flexibility in ability to reference and jump to specific button presets.

**Comment by fifafu** [comment]
Sorry I'm not sure whether I understand correctly.
Do you have an example?

You want to open the group when specific modifier keys are pressed?

**Comment by amatrosovas** [comment]
I have group in global that only appears when I hold CMD+OPTION keys down. I would like to be able to access that group through other actions without having press modifiers. One other option would be to be able to open the group defined for other specific apps.
