### ISSUE TITLE
Button Spacing Changing

### ISSUE THREAD

**Issue by CarterVE** [folivoraAI/BetterTouchTool#2037]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Hi,

I'm having an issue where the spacing of my widgets on the right side of the touch bar changes after opening a group. The initial spacing is incorrect for a couple widgets, but corrects itself when a group is opened. This is really annoying, as it means I need to open a group and close it again after first starting BTT. 

Please let me know if you have any suggestions!

Thanks,
Carter

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Touch Bar

#### Device information:

Type of Mac: MacBook Pro 15" 2017
macOS version: 10.13.2
BetterTouchTool version: 2.332

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

Initial spacing:
<img width="1085" alt="touch bar shot 2018-01-28 at 9 18 02 pm" src="https://user-images.githubusercontent.com/18474523/35491028-fd5204f6-0471-11e8-9768-33cbe9a8ee2a.png">

After opening and closing a group:
<img width="1085" alt="touch bar shot 2018-01-28 at 9 18 18 pm" src="https://user-images.githubusercontent.com/18474523/35491039-0c9bd7a2-0472-11e8-8eff-08dd00d0ec0e.png">

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Hi Carter, 

are you using negative values in the button setup? I think then it might be the same issue as here:
#2013 

I'm closing here and continue to track it in the other issue. It should be resolved soon.

**Comment by fifafu** [comment]
A wait, the other issue was also created by you? What's the difference between the two issues?

**Comment by CarterVE** [comment]
I noticed different behavior between the two, the first was the negative spacing on the right side causing apps to fall off the end of the touch bar, whereas this was causing app spacing to change (for example, the moon icon has strangely large spacing around it until a group is opened). I'm not sure, they may be caused by the same thing, but wanted to make sure you were aware of both!
