### ISSUE TITLE
>2 Widget icon settings?

### ISSUE THREAD

**Issue by CarterVE** [folivoraAI/BetterTouchTool#2038]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

Feature request/Question: Is it possible to set the widget icon to more than two different images based on different return values? Either by specifying the image path in the script, or otherwise in the BTT app interface? 

Please let me know if this is possible, or if not please add this functionality (perhaps a + button to add more icon options?). It would be so useful!!

Thanks!
Carter

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Touch Bar

#### Device information:

Type of Mac: MacBook Pro 15" 2017
macOS version: 10.13.2
BetterTouchTool version: 2.332 (713)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
This is currently not possible.
Maybe in future versions, but I'll need to think about how to implement it.
You can however use emoji in the widget title

**Comment by CarterVE** [comment]
Ok thanks anyway! Please consider implementing it, especially just having the option to add more icons with a + button would be so useful for things like an accurate volume indicator based on the current system volume!
Thanks!

**Comment by andyconlin** [comment]
I'll second this feature request, as I think it would be fun to add album art to a music widget, though in all honesty, it's possible the size is better suited to an application icon and not album art.  Even still, there could definitely be uses for dynamic icons as returned by scripts.

**Comment by fifafu** [comment]
You can already do this if you can somehow get the icon path or the icon data as base64.
In your widget you can either return a string (then you have the 2 icon limitation) or you can return a JSON object like this (all params optional):

```JSON
{"text":"newTitle", "icon_data":"base64_icon_data", "icon_path":"file_path_to_new_icon", "background_color": "255,85,100,255"}
```

**Comment by andyconlin** [comment]
Excellent!  I will experiment with what can be done with that method.
