### ISSUE TITLE
Custom Snap areas disappeared and can't restore from .json backup

### ISSUE THREAD

**Issue by gngan1** [folivoraAI/BetterTouchTool#2040]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
I downloaded Alfred 3. After making a few changes in Alfred's preference, all of my custom snap areas disappeared (spend a lot of time to make them look good to me). Imported the default.json (Which I had exported to my folder for backup) doesn't restore the settings for the snap areas. All the mouse and key short-cuts settings in BTT are not affected. Only thing that may worth mention is I have enabled the "Dropbox Sync" feature in BTT before the first time I install Alfred 3. 

Followup: restart iMac. Custom snap areas still disappeared.  I disabled the "Dropbox Sync" in BTT and re-created the snap areas while Alfred 3 is still running. So far no issue. But I dare not to run/change Alfred's preference at the moment.

Perhaps the main questions is 
(1) can I save the settings of the custom snap areas?
(2) I find that custom snap areas can only be set up on one monitor (in my case, the external monitor)

BTT is a great utilities and really appreciate all your huge efforts. It an utility that worth paying and I sure will keep paying if new versions are coming out! Thanks
#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Magic Mouse2, no trackpad, one external 3840x2160 monitor attached to iMac Pro via DP1.2

#### Device information:

Type of Mac:iMac Pro
macOS version: 10.13.3
BetterTouchTool version: 2.332(713)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
I would like to give you a screen shot of my snap area but can't use grab while in snap area setup mode.

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Hey,

could you attach the preset json you exported? I think it should contain the snap areas.
However a few users have reported an issue that causes snap areas to not be shown sometimes - I'm currently looking into this.

Snap Areas are currently specific to a display setup (for technical reasons), this may however change in the future. So even if you change the resolution or position of the display in system preferences => Displays, the snap areas may disappear.

**Comment by gngan1** [comment]
I have overwritten the old one with the new setting .json file. The old one is Default.json and the new one is BTT Settings for iMacPro (after snap settings is lost and I rebuild the new snap areas). I didn’t change the resolution of my external monitor and iMac. It just disappeared after I first ran Alfred 3 preference pane. Now they live in peace together.

Thanks
