### ISSUE TITLE
Plain text - configuration file

### ISSUE THREAD

**Issue by michaelfresco** [folivoraAI/BetterTouchTool#2044]
#### Description of bug:
The plist file is hard to read with an external text editor. It also prevents us to put the BTT config file in the dotfiles repo.

#### Solution:
Have a plain text configuration file.

**Comment by fifafu** [comment]
Plists are the default property lists in macOS. There are many editors that can read them. Unfortunately this won't change as I'm making extensive use of NSUserdefaults to store data.

However I plan to add an option to include the plist settings in the json exporter/importer soon.

**Comment by michaelfresco** [comment]
JSON would be a big step in the right direction. Thanks for considering it. 👍

**Comment by michaelfresco** [comment]
I'm trying to put the following files under version control. 

11:42 btt_data_store.v2
12:27 btt_data_store.v2-shm
12:27 btt_data_store.v2-wal

But they constantly change with each time the application opens and closes. You'd expect that the keys are saved under `.v2` and that -shm and -wal are just caching files. But I noticed that's not working for me to save the shortcuts. I have to add them all.

Would it perhaps be possible to load all the keys from a json file, each time at startup? That way, we could erally put the json under version control.

**Comment by fifafu** [comment]
@michaelfresco sorry no, the data format of BTT will continue to be this sqlite/coredata database.
Why not add these 3 files?

The JSON export/import is basically just an additional way for exporting/importing data to another system but it won't replace the database.

**Comment by michaelfresco** [comment]
@fifafu 
It's the best alternative we have right now, so I'll add all 3 files.

I forgot it was a sqlite3 database. That explains a lot actually. Each time you fire up BTT, that sqlite3 DB will change a bit (on a bit-level) ofc, which also explains why I get all these changes detected by git, even when you don't remap any keys.

**Comment by fifafu** [comment]
Yup, it also updates some internal stuff that's kept to make some BTT functionality work smoothly (e.g. some timestamps)

**Comment by michaelfresco** [comment]
(I could write some small script to dump the sqlite3 store, so technically it would be stable for git) 

Shall we close this issue? Thanks for the quick feedback.

**Comment by fifafu** [comment]
I'm still thinking about an option to have a static json loaded on startup to completely replace the core-data store. So we can leave this issue open for now. However this is something mid-term, it will probably not be added in one of the very next versions.

**Comment by kyounger** [comment]
That would be HUGE win for managing my config. It would also be a great avenue toward being able to easily share individual mappings, sort of how Karabiner-Elements does.

**Comment by fifafu** [comment]
In recent versions you can put a preset file called .btt_autoload_preset.json into you user folder. It will always be loaded on startup.

For sharing individual mappings you should however just use the standard preset feature.

**Comment by kyounger** [comment]
Is this the same format as the exported preset file? Does it include all settings and mappings?

**Comment by fifafu** [comment]
Yes

**Comment by michaelfresco** [comment]
Awesome implementation! The JSON file is splendid! I noticed that if you have 4 shortcuts for an app, you also see 4 items in file. :smile:
