### ISSUE TITLE
[Feature Request x2] Always on touchbar and esc key placement

### ISSUE THREAD

**Issue by mirrorforthestars** [folivoraAI/BetterTouchTool#2054]
An option to keep the touchbar awake indefinitely. I understand this may cause burn-in. Example of current problem with the Apple software design: I'll be watching a film or working on a project and I first have to wake the touchbar to either press escape or change volume. A one button press is now maybe 3. I'd take always on (or in sync with the screen powersaving setting) with burn-in anyday.

Secondly, I see similar things have been requested, but is it possible to switch around the ESC and X buttons when "Show ESC button on the left side of the touch bar" is checked? I ask because it is horrible to have to think when BTT is on and you dont reach to touch the top left to ESC but just to the right as the X is where ESC would be.

Thanks for the powerful software!

**Comment by fifafu** [comment]
I think I could add an advanced option to keep it awake (I'll put a big warning there though :-))

Unfortunately the X button is added by the system and I can not influence it at all. The only way to get rid of it is to disable the macOS Control Strip in BetterTouchTool's general preferences and create your own control strip). This is what I'm usually doing and there will soon be some improvements to make it possible to replicate the macOS Control Strip better.

Here a screenshot where I replaced the control strip with BTT:
![image](https://user-images.githubusercontent.com/8820811/35723520-ddf694c8-07fa-11e8-9768-fee46d63fa28.png)

**Comment by mirrorforthestars** [comment]
You are a life saver if you do!

Great, looking forward to the improvements. In your setup/screenshot, does it also show the “App Controls”? Cause what id love are app controls but with a persistent volume slider to the right like yours- basically bringing back a better semblance to before the touchbar.

Cheers!


On 2 February 2018 at 09:24:53, Andreas Hegenberg (notifications@github.com<mailto:notifications@github.com>) wrote:

I think I could add an advanced option to keep it awake (I'll put a big warning there though :-))

Unfortunately the X button is added by the system and I can not influence it at all. The only way to get rid of it is to disable the macOS Control Strip in BetterTouchTool's general preferences and create your own control strip). This is what I'm usually doing and there will soon be some improvements to make it possible to replicate the macOS Control Strip better.

Here a screenshot where I replaced the control strip with BTT:
[image]<https://user-images.githubusercontent.com/8820811/35723520-ddf694c8-07fa-11e8-9768-fee46d63fa28.png>

**Comment by mirrorforthestars** [comment]
In stead of the warning, you could do what TV overlays do and have scrolling text on the touchbar to stop burn-in ...or stream adverts! I'm j/k on both counts of course.

**Comment by fifafu** [comment]
BTT can only completely replace the Touch Bar (there is no API to do anything else), so it wouldn't show the default App Controls anymore, but you can configure custom ones in BTT.

Preventing burnin on oleds is its own research field, I'm sure I could only do it wrong thus there will definitely be a warning. Maybe I can additionally add some scrolling stuff though :-). However as said I can not influence the App Controls shown by other apps.

(I have not yet checked whether it's at all possible to keep the Touchbar awake)
