### ISSUE TITLE
[FEATURE REQUEST] Set default window size and placement for individual apps

### ISSUE THREAD

**Issue by robinckarlsson** [folivoraAI/BetterTouchTool#2056]
I think it would be really great if we could tell BTT to always resize/place a window from a certain app when opening the window. For instance, always open word-documents to left third of screen, etc.

Cheers
Robin

**Comment by waxfingers** [comment]
Don't know if this can be of any use to you, but what I personally do is create a normal action with its shortcut and then attach an additional action. As an example I've assigned a global shortcut to show BTT's  preferences ( Command + F2) and then attach a _Maximize Window Left_ (Ctrl + 9 in my layout). That's going to open BTT's main window maximised to half left screen =)
Additionally you might want to create your own window snapping areas and then have the window resized and placed exactly as you wish... see below for 1 third of left screen; remember that to add/edit snap areas, BTT's menu bar icon must be visible, as is from there you access the whole shibang.

![btt-window-scs_web](https://user-images.githubusercontent.com/13238340/35767243-a2dc9090-08e0-11e8-96bc-b0ef986a45d8.jpg)



![btt-window-scs_web](https://user-images.githubusercontent.com/13238340/35767363-f63efd98-08e2-11e8-85de-ea44d468ac49.jpg)

**Comment by robinckarlsson** [comment]
That pretty nifty, thought I don't think it would work for me (correct me if I'm wrong here). I'd like to be able to open, for instance, 10 word-documents and have them all maximize to left third of screen. With your method, I'd have to open each one separately, right?

**Comment by waxfingers** [comment]
I see, you want more of a permanent fix. Well if I understand it correctly... it could also redistribute the real state apps use with per program option, yeah that's cool =)

Meanwhile maybe a patch could be to search for an applescript and adapt it to your needs or use something rougher like assigning `command + opt + n` to `command + n` (or whatever new doc word's shortcut is) or with a menu trigger to` FIle; New` (or whatever new doc word's menu is)and add the desired window placement in an additional action; I've tested with a text app and each new document will open in the same spot; ugly but does the job.

**Comment by robinckarlsson** [comment]
Ok cool thanks, maybe I’ll give that a go! A proper BTT solution would be great though.
