### ISSUE TITLE
Odd keystroke sequence cant be deactivated?!

### ISSUE THREAD

**Issue by Satori83** [folivoraAI/BetterTouchTool#2068]
So I turn on my computer today and try to type the letters "php" but it automatically turns to this "₱", the Philippine currency symbol. So far Ive tried:

1. Checking keyboard settings and region
2. Trying my wired apple keyboard and logitech wireless
3. Tested the Keyboard viewer and noticed something change in the function keys really fast, i recorded it and noticed the F16 key appeared which is not even used on my Logitech, my main keyboard See: https://satori-design.d.pr/QHy1Lr
5. Tried turning Fn keys off and on
6. Tried Resetting NVRAM
7. Reinstalled OSX Sierra
8. Tried remapping with two programs, Karabiner and Better Touch Tool, which when recorded in Better Touch showed the actual keys being hit as phpv See: https://satori-design.d.pr/ldRMcJ

How come when I try to assign it something else or even to reprint the correct text, it doesnt work?

**Comment by fifafu** [comment]
Mh I don't think this is related to BTT or do you have anything related configured there?

Maybe a text replacement in System Preferences => Keyboard => Text?

**Comment by Satori83** [comment]
No I dont. And its not BTT causing it because I installed BTT to try and override this. Was just hoping you had some incite as to why it cant be overridden so maybe I could track down or get it to work.
