### ISSUE TITLE
Feature Request: Define Trackpad Edge

### ISSUE THREAD

**Issue by LibertarianVoter** [folivoraAI/BetterTouchTool#2075]
#### Device information:

Type of Mac: iMac (21.5-inch, Mid 2010)
macOS version: 10.13.3
BetterTouchTool version: 2.332 (713)

**Comment by proactivematter** [comment]
This is a great idea. This is especially true for the new (huge) trackpads.

My personal quarrel with trackpad edge is in assigning corner clicks in BTT. I always have to press it oh so close to the edge that it sometimes makes the assigned shortcut require more effort / concentration / time than doing it by conventional means.
