### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by appetrosyan** [folivoraAI/BetterTouchTool#2076]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

Ability to trigger different actions depending on return Value of AppleScript for Touch Bar widgets. Actions like sending keyboard input or controlling the focused application are useful, but can be triggered from within the appleScript, but actions like opening a new Touch Bar button group, can't.

This would allow for context sensitive Touchbar groups to exist. For example I plan on using them to have different Touch Bar groups depending on the major mode of emacs. 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Touchbar

#### Device information:

Type of Mac: MBP 2017 w/ TouchBar
macOS version: High Sierra
BetterTouchTool version: 2.332

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by OrbitalTech** [comment]
Something like this will be possible soon using the alpha versions. Follow it here:
https://github.com/fifafu/BetterTouchTool/issues/2410
The alpha releases can be found <a href="https://updates.bettertouchtool.net/alpharls.html">here</a> and details on how you might implement this can be found under alpha 2.426.
