### ISSUE TITLE
Mouse tilt-wheel behaves like two buttons in Sierra, but is overridden by shift-scroll (horizontal scroll) in High Sierra

### ISSUE THREAD

**Issue by iaian7** [folivoraAI/BetterTouchTool#2083]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

I use the same Logitech mouse with a tilting scroll wheel both at home and at work. At home I'm running macOS Sierra, and have it set up so the tilt wheel (recognised as "Scroll Left" and "Scroll Right" buttons) will cycle through tabs (or other functions, depending on the app). Shift-vertical-scrolling then scrolls horizontally in all apps, as expected (except a few Adobe apps that are weird, but that's Adobe's fault!).

At work, however, I'm running macOS High Sierra, and shift-vertical-scrolling behaves like it's activating the tilt-wheel. If I try to scroll horizontally, it will change tabs in Safari! The Better Touch Tool settings are the same on both computers.

Now, perhaps this is expected behaviour - the tilt wheel is recognised as "Scroll Left" and "Scroll Right" after all. However, running BetterTouchTool in Sierra allows for behaviour that's far more customisable - the tilt wheel does not behave like a horizontal scroll, but as actually button presses, which is much more powerful (and preferred)!

Is this a limitation of High Sierra? I don't have any other mouse drivers installed that I'm aware of, certainly not the Logitech software, and I think I'm running pretty much all the same general utilities (Dropbox, iStat Menus, Aflred), so I'm not sure what else could be different...other than the OS itself.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Logitech G700 mouse.

#### Device information:

Type of Mac: 2015 iMac 27" (works nicely), 2013 Mac Pro (not so much).
macOS version: Sierra 10.12.6 (works nicely), High Sierra 10.13.3 (not so much).
BetterTouchTool version: All recent versions, and 2.340 for certain.

Of note; the same 2013 Mac Pro and G700 mouse currently "broken" with High Sierra worked as expected last year when it was running Mavericks and an older version of BetterTouchTool. My assumption is that the bug is in macOS High Sierra, and my hope is that BetterTouchTool might be able to work around it somehow!

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by Jorrrb** [comment]
I am experiencing the same situation. Prior to upgrading to High Sierra shift+scrolling the mouse wheel up or down would horizontally scroll and the tilt wheel would swipe between desktop screens. After upgrading to High Sierra the tilt wheel still functions to switch between my desktops screens, but shift+scrolling the mouse wheel behaves the same as the tilt wheel function instead of horizontally scrolling.

MacBook Pro (Retina, 15-inch, Mid 2014)
OSX High Sierra 10.13.3
BTT 2.340

**Comment by yuzukosh** [comment]
I'm having the exact same issue too, is there a difference in the way that High Sierra recognizes the left/right wheel tilt on Logitech mice?

**Comment by wzaatar** [comment]
+1, using left/right to swipe between desktop screen but buttons are not being recognized by BTT although they are by MacOS. What's the fix please?

I'm using the Logitech MX3200 combo.

**Comment by neonbaer** [comment]
hey there,

is there a fix by now?
