### ISSUE TITLE
Mouse left click frequently missed

### ISSUE THREAD

**Issue by dysquard** [folivoraAI/BetterTouchTool#2086]
#### Description of bug/feature request/question:
Mouse left click frequently missed. Almost miss 2 clicks in 5. After disable BTT , mouse works fine.
I tried several mouses, all the same problem.
Trackpad is not affected by this bug.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Normal Mice

#### Device information:

Type of Mac: MacBook Pro (15-inch, 2016)
macOS version:  10.13.3
BetterTouchTool version: 
2.340

**Comment by fifafu** [comment]
There is a bug in some apps that use an older version of electron/chrome  that could cause this.

Does this happen in specific apps for you?

**Comment by dysquard** [comment]
It happens in all apps, system windows, anything, not specific one.

**Comment by fifafu** [comment]
Do you have any triggers/gestures configured for mouse/magic mouse in BTT?

**Comment by dysquard** [comment]
Yes ,but these configurations have been set for nearly 6 months. It doesn't cause any bug before. I just encounter this in about one week.
<img width="657" alt="screen shot 2018-02-11 at 10 05 38 am" src="https://user-images.githubusercontent.com/16001323/36068568-65c9f22c-0f13-11e8-9673-873a57bc577c.png">
