### ISSUE TITLE
Report： "before mac goes to sleep" and "after mac wakes from sleep" doesn't work in some cases

### ISSUE THREAD

**Issue by luchenguang** [folivoraAI/BetterTouchTool#2092]
#### Description of bug/feature request/question:
 In BTT's "other" tag , I configure 2 triggers. One named "before mac goes to sleep" and another named "after mac wakes from sleep". Their actions are  Execute Terminal Command to close Wi-Fi when I close the screen and open Wi-Fi when I open it. But there is a problem that if I close Mac's screen for a long time (e.g. one night), it doesn't work to open Wi-Fi when I open Mac,  I have already  select to Launch BTT on startup, but it doesn't work too.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
"after mac wakes from sleep"
"before mac goes to sleep"

#### Device information:

Type of Mac: MacBook Pro 2017 13''
macOS version: 10.13.3
BetterTouchTool version: 2.340

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by afeblot** [comment]
Exact same symptoms for me with a python script. The script seems just not be executed after 20 hour periods of sleep (ensured by writing a new log file on each execution).
BTT 2.427
Mac OS 10.13.5
iMac Mid 2009 with SSD

**Comment by afeblot** [comment]
So... there is a problem, confirmed by 2 users, and you just close the issue without a single explanation?

**Comment by fifafu** [comment]
The BTT issue tracker has moved to https://community.folivora.ai early this year and all issues here have been auto-closed now. In case you still need help with this issue / feature / question please create a new post there.

**Comment by afeblot** [comment]
ok, thanks, I will.
