### ISSUE TITLE
Support for USB-HID-Gamepad/Joystick

### ISSUE THREAD

**Issue by alexkazik** [folivoraAI/BetterTouchTool#2094]
#### Description of feature request:

I use a "Game Keyboard", which is from the point of the system just a USB-HID-Joystick with 21 buttons and one joystick.
I'd like to assign mouse/keyboard shortcuts for those keys, depending on the Application.

#### Affected input device:

USB HID Joystick

**Comment by evanc** [comment]
I would also like support for this- I would like to use a USB gamepad I have sitting around to control my music and trigger other shortcuts.

**Comment by jeffmann** [comment]
You could try something like [Enjoyable](https://yukkurigames.com/enjoyable/) to assign buttons to a keyboard hotkey, then use BTT to define the action.

Alternatively there's "Joystick Mapper" on the Mac app store, and "ControllerMate" that looks quite advanced, though a bit expensive.

**Comment by evanc** [comment]
^^ that's actually what I've done, I used controllermate to assign all of the controller's buttons to F13-16 with different variations of control, command, option, and shift. It would just be nice to be able to do it all in the same app.

**Comment by jeffmann** [comment]
I agree that would be nice...

**Comment by fifafu** [comment]
I may be able to add this. Will look into it soon.

**Comment by WeddingArch** [comment]
That would be amazing - I've invested in BTT and would love to see a solution for a PS4 controller that I'd like to use to interface with my Macbook :D Thanks!

**Comment by alexkazik** [comment]
Any news?

**Comment by jeffmann** [comment]
@alexkazik BetterTouchTool is no longer using GitHub for Issue Tracking. See the readme.
