### ISSUE TITLE
Brightness Slider Issue

### ISSUE THREAD

**Issue by CarterVE** [folivoraAI/BetterTouchTool#2097]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

Hi,

I'm having trouble with the brightness slider, I've got it set to show when holding the <Control> button, but when I do the brightness slider stops working. It drops to 0 even though the brightness is obviously not 0, and dragging the slider does not change the brightness.

It works in all other cases, including if you have it set to show when holding <Shift>, <Option>, or <Command>, but unfortunately I have other groups set to show when those buttons are pressed... Please fix if possible!

Thanks!

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Touch Bar

#### Device information:

Type of Mac: MacBook Pro 15" 2017
macOS version: 10.13.3
BetterTouchTool version: 2.340 (719)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

Here's a picture I took displaying the issue (couldn't take a screenshot as I was holding control, sorry)!

![img_6354](https://user-images.githubusercontent.com/18474523/36078520-9c19873e-0f45-11e8-9df8-677b8a22098d.JPG)

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
The problem is that ctrl is currently used for changing the brightness of external displays, however I think I can make that optional.
