### ISSUE TITLE
Magic Mouse 1 Finger Tap Doesn't Work on Wake Up

### ISSUE THREAD

**Issue by martinbottanek** [folivoraAI/BetterTouchTool#2104]
#### Description of bug/feature request/question:

After wake up, both 1 Finger Tap Left & Right do not work as intended. Sometimes Tap Left opens a right click menu

This doesn't happen when I manually lock the screen of my computer. I can reproduce the issue only when I login back using Fingerprint.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Magic Mouse

#### Device information:

Type of Mac: MacBook Pro 15 w/touch
macOS version: 10.13.3
BetterTouchTool version: 2.340

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by tobo2** [comment]
**Description of bug/feature request/question:**

I have the same/similar issue. Sometimes taps stop working altogether, and other times left tap acts as right click.

For me this issue happens regardless of how the computer was locked, put to sleep or restarted.

**Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):**

Magic Mouse 2

**Device information:**

Type of Mac: iMacPro1,1
macOS version: 10.13.4
BetterTouchTool version: 2.503 (841)

**Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):**

Opening up BTT preferences seems to fix the issue.
