### ISSUE TITLE
Enhanced Touch Bar Items

### ISSUE THREAD

**Issue by xmattydx** [folivoraAI/BetterTouchTool#2106]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

Allow enhanced touch bar items. For instance, for the battery widget, allow the color to change depending on the percentage of battery remaining. 0-20% Red, 20-40% Orange, 40-60% Yellow, >60% Green.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Touch Bar

#### Device information:

Type of Mac: Macbook Pro Retina 15"
macOS version: 10.13.3
BetterTouchTool version: 2.340 (719) 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by OrbitalTech** [comment]
This feature is now possible using the latest alpha.
Find it <a href="https://updates.bettertouchtool.net/alpharls.html">here</a>.
See the details of alpha 2.426 for more info.

You should expect to see something along the lines of this <a href="https://github.com/OrbitalTech/BTT-Scripts">here</a> soon.

**Comment by fifafu** [comment]
The next alpha will also allow to return a json dictionary containing icon data, which may make this even easier than using the updateWidget functionality :-) So this will definitely be feasible, but I'd wait a few more alphas until this is stable.
