### ISSUE TITLE
[v2.340] Fn+1-finger moving window sometimes cannot snap window any more

### ISSUE THREAD

**Issue by GJRobert** [folivoraAI/BetterTouchTool#2109]
#### Description of bug/feature request/question:
Snapping windows to sides/corners/full screen requires moving windows to the trigger edges/points. Before v2.340, I used to snap windows with 3-finger movements, and with Fn+1-finger movements provided by BTT too (I prefer Fn+1-finger movements because this prevents windows  being moved to adjacent workspaces). But after v2.340, sometimes it's not possible to snap windows when moving windows with Fn+1-finger movements. I must trigger snapping by 3-finger movements first, and only then Fn+1-finger movements can also trigger snapping.

After restarting the laptop the issue persists. Thanks for your attention!

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
MacBook Trackpad AFAIK

#### Device information:

Type of Mac: MacBook Air 2013-Mid
macOS version: 10.11 El Capitan
BetterTouchTool version: 2.340

**Comment by fifafu** [comment]
Is it possible that this happens if the window is not focused when you start the moving?

**Comment by GJRobert** [comment]
Hi, I'm not so sure if it has to do with focus now, but in my memory, BTT never behaved like this before.

And in my experiments, it does not seem that the failed trigger is related to unfocused window. After BTT becomes normal again, unfocused windows can be snapped normally too.
