### ISSUE TITLE
Delay with CMD+SHIFT+[number] Commands

### ISSUE THREAD

**Issue by eggplantsplz** [folivoraAI/BetterTouchTool#2120]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
I use a keyboard shortcut, set in BTT, CMD+[Number] or CMD+shift+[number] for multiple actions, such as launching certain applications or, for example, switching between conversation in the messages app (CMD+1 for previous conversation, CMD+2 for next conversation)

With the latest update, there is a noticeable delay in the launching or recognition of these commands. I'll have to trigger it 2-3 times before it registers, wereas before it would be instantaneous. I've tried a restart of the computer, but realized this was only the case after I updated to the latest alpha.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
MBP keyboard commands

#### Device information:

Type of Mac: 2017 MBP 
macOS version: 10.13.4 Beta (17E150g)
BetterTouchTool version: 2.341 (720)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Hi,

Thanks for reporting!
Does enabling "trigger on key down" remove the delay, or is it still there? (Using the little gear icon left of the shortcut recorder field)

**Comment by eggplantsplz** [comment]
Yes it does - is this a new feature?

**Comment by fifafu** [comment]
No, but the keyboard handling has been completely rewritten to be more flexible (e.g. now the fn key is supported). 

I assume there is still an issue with the "on key up" triggering. I'll look into it.

**Comment by eggplantsplz** [comment]
Ah that's great to know re: FN key. That'll open doors for a ton of new options. 

Thanks - I'll use this as my go-to fix for any other keyboard delay issues for the time being. Will there be any unwanted side effects from enabling "trigger on key down"?

**Comment by fifafu** [comment]
No I don't think this will cause issues. (I also thought about making it the default)

**Comment by fifafu** [comment]
Could you check whether this is fixed with v2.344?

**Comment by eggplantsplz** [comment]
No issues yet - will keep you posted in case anything comes up.
