### ISSUE TITLE
PyCharm / IntelliJ Idea : selecting with drag outside of editor window lets selection "hang"

### ISSUE THREAD

**Issue by richard-vogl** [folivoraAI/BetterTouchTool#2134]
#### Description of bug/feature request/question:

In PyCharm (current Version: PyCharm 2017.3.2 (Professional Edition) Build #PY-173.4127.16, built on December 18, 2017 ) when selecting-dragging with mouse and leaving the editor pane, the selection hangs:
newly typed text and after cursor movement selection will happen (as if mouse button is still pressed) and text will be overwritten / deleted.
See linked video and pycharm issue (and linked issues):
https://youtrack.jetbrains.com/issue/IDEA-183604
https://youtrack.jetbrains.com/_persistent/mouse%20bug.mov?file=74-474847&c=true

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Affects: Magic Mouse, Magic Trackpad

#### Device information:

Type of Mac: MacBook Pro (Retina, 15-inch, Late 2013
macOS version: 10.13.3 (17D47)
BetterTouchTool version: 2.340

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
Stopping BTT resolves the issue.

**Comment by fifafu** [comment]
I'm usually running some "workaround code" for jetbrain products as they often struggle with similar issues. Maybe they changed their bundle name or something similar and BTT doesn't recognize it anymore. I'll check if I can download a current trial version.

**Comment by fifafu** [comment]
Btw. which version of BTT are you running?

**Comment by richard-vogl** [comment]
BetterTouchTool version: 10.13.3 (17D47)

**Comment by fifafu** [comment]
That's your macOS version :-)

**Comment by richard-vogl** [comment]
ah I see :) that explains the question
BetterTouchTool 2.340

**Comment by fifafu** [comment]
Could you run this terminal command:
```mdls -name kMDItemCFBundleIdentifier -r /Applications/PyCharm.app```
and let me know the output? (may save me from installing pycharm)

**Comment by richard-vogl** [comment]
mdls -name kMDItemCFBundleIdentifier -r /Applications/PyCharm.app
com.jetbrains.pycharm%

**Comment by fifafu** [comment]
Mhm unfortunately that looks like in previous versions. Are you sure this goes away when you quit BTT? (The bug can be triggered by any app that uses a specific event handling technique, not only BTT)

**Comment by richard-vogl** [comment]
well, it's 100% reproducible when BTT runs, 0% reproducible when I quit BTT. sample size ~5 tries

**Comment by fifafu** [comment]
Ok, for now you can try to disable BTT for pycharm (click the BTT menubar icon while in PyCharm and select 'disable BetterTOuchTool for current app')

I'll try to reproduce it, but I may not be able to fix this on my side.
