### ISSUE TITLE
Feature request: Action to "hold down mouse button" (& ability to trigger action while keys held)

### ISSUE THREAD

**Issue by TheBloke** [folivoraAI/BetterTouchTool#2135]
#### Description of bug/feature request/question:

I would like an Action (or multiple) for **Hold Down Left Mouse Button**;  or **Hold Down Mouse Button X** (Left, Right, Middle).  We have the option to do Left/Right/Middle Click, but this is a single click, not the same as a "Left Mouse Down" action.

Here is my use case: I have a Magic Trackpad 2, and when using Photoshop I thought I could use it a little like a graphics tablet.  Easier to draw than using a mouse.  However it only draws/paints when I click.  So in order to paint, I have to apply pressure while dragging my finger, like a click and drag.

This makes it quite hard and uncomfortable to draw.

Instead I thought it might be good if I could assign an action to "hold down Left Mouse button" and assign this to a keyboard shortcut.  So I press the keys and now the LMB is held down, so whenever I move my finger over the trackpad, it draws all the time. 

Ideally, I would need to hold down the keyboard shortcut constantly to replicate the "hold left mouse down", and when I release the keys it would stop the action.  I think I can achieve this with Keyboard Shortcuts -> Advanced Gesture Settings -> Repeat action while shortcut is pressed.  Although this has options "Repeat rate" and in the case of "LMB Down"  I don't want it triggered over and over, I want it triggered once and held, and at the end of the old, a "LMB Up" is sent.

So maybe this would require a second change:  the ability to specify that a Keyboard Shortcut sends one action while held (ie LMB Down) and then a second one at the end (ie LMB Up).

As this is a special case, it could also be a special type of action:  "Send key/mouse press while held down", which gives a dialogue where we can specify the Down action of any keyboard key, plus LMB, RMB, MMB Down.  Then when the action is no longer being fired, it sends the Up/Release code for the configured key/button.

Alternatively, I could have a keyboard shortcut that triggers "LMB held down" and then another for "LMB released".  That would require fewer changes in the app.

Thanks.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

All (but I would only use it from Keyboard)

**Comment by TheBloke** [comment]
Just to add that I have realised that I can now easily achieve this using Karabiner-Elements, software I use to remap keyboard keys.  Just today the author added the ability to map a key to "Mouse Down".

So this is not a big request from me any more.  But maybe it would still be useful to others.

**Comment by waxfingers** [comment]
For a long time I had Karabiner working alongside with **BTT** but then once in a while arose  "incompatibilities", which were (logically) twice as annoying to detect and solve. That and other issues that are not important in the present subject matter made me realize 2 things:
- 1 I wanted the _less is more_ path and
- 2 I was not exploring **BTT**'s incredible potential

Today BTT achieves almost all that I had Karabiner doing for me (not the key exchange of keys or other complex actions which in the grand scheme of things one understands them as very relative) and is one less app to deal with. All that said, there is room for improvement and some features that if I would personally like to see implemented in this absolutely orgazmic platform that is **BTT**

**Comment by TheBloke** [comment]
I use Karabiner purely for the key swapping you mention - basically, for making my British PC keyboard work OK with macOS.  For example swapping " and @, putting the `, \, |, ', # and ~ keys where they should be, etc.

I guess Karabiner can do more than that, but as you say I prefer to do anything else with BTT, which I find to be one of the most powerful pieces of macOS customisation software around.   Especially when used with a Magic Trackpad (either built in to Macbook Pro, or an external peripheral), where the advanced gestures make one feel like a macOS ninja :)

**Comment by fifafu** [comment]
@TheBloke for such basic remappings there is even a macOS internal tool which can do this (I'll soon create a little blog post about how to use it).

As for the "hold down mouse button", this will definitely be added soon.

**Comment by waxfingers** [comment]
> which I find to be one of the most powerful pieces of macOS customisation software around
I'll sign on that.

**Comment by yay** [comment]
That's why I just bought BTT for and realized it's not possible :\

**Comment by TheBloke** [comment]
Don't worry, BTT is well worth a purchase at any price.  You can find a hundred other uses :)

But here's how to achieve what you want:

- [Download Karabiner-Elements](https://github.com/tekezo/Karabiner-Elements/releases)
- Open the Preferences on the first tab (Simple Modifications)
- Add a key mapped to button3; here's what it looks like for when I map F1 to LMB (button1): [screenshot](https://i.imgur.com/soQP73R.png)
- That's it!

**Comment by TheBloke** [comment]
That said, I do think this would be a good addition to BTT.

I didn't realise until I added this how incredibly useful it is.  I not only use it for drawing in Photoshop, I now use it all the time.  For example, dragging a file from Path Finder on monitor 2 to some app on monitor 4 means I have to cover 4000+ pixels.  This gets really tiring trying to drag-click this on the Magic Trackpad.

So now I just hold down F1 and can move the cursor with my finger with no pressure, and in many motions as is required.  It's so much nicer.

**Comment by TheBloke** [comment]
@yay  you're welcome!

That's interesting about the dragging.  But it doesn't seem to work for me?   I just tested it in a couple of places (from both Path Finder, and Finder) and the moment I release pressure on my finger, the drag cancels.  I can't see any options under Trackpad that controls this.

Unless BTT is affecting it  somehow.  But I doubt it, because it doesn't interfere with basic one-finger click/drag, I believe.

Can you give me an example of where this works?

Unless of course it's something specific to a MacBook trackpad that doesn't apply to the external Magic Trackpad 2.

**Comment by fifafu** [comment]
@TheBloke, this only works if you use tap to drag. For "click-drags" it cancels immediately.
Tap to drag can be activated in System Preferences => Accessibility => Mouse & Trackpad => Trackpad => Trackpad Options => Without Drag Lock

**Comment by TheBloke** [comment]
@fifafu  Oh wow, I never knew about those options!

I tried it and at first I thought it was really awesome - I really liked the "with drag lock" in particular, so a drag could last forever until another tap.

Unfortunately it seems this only works in Finder.  Or at least, it doesn't work in Path Finder, Adobe Premiere, or even Apple's own Final Cut Pro.   Maybe it works in some other basic Apple apps like Photos, but it's not a general thing.

So for now I think I will stick with my keyboard solution.  Which is a shame because I really like the option of multi-step drag with trackpad alone.

Any chance you could re-implement the feature in BTT in a way that works in all apps? :)   If you could provide a way to do exactly what "with drag lock" and "without drag lock" do, but working everywhere, that would be fantastic.  I suppose it should be technically possible - you can just pass a continuous "hold LMB" to keep the drag going regardless of whether the user is currently holding or not, and then control it by checking for the tap sequeneces as Apple does with its setting.

But I guess I should open a different feature request for that :)

Thanks again!

**Comment by fifafu** [comment]
Mhh it should work in all apps. Does the "Without Drag Lock" option work? (it also allows like 2 seconds where you can reposition your finger before cancelling the drag)

**Comment by TheBloke** [comment]
Ahhh sorry you are right, yes I can get it to work in other apps.

I wasn't double-tapping quite fast enough I think.  And Path Finder recognises a single tap as "rename item", so that easily triggers if you don't do the double tap right.

But yes I have now got it to work in Photos, FCP, and Premiere.  And I see it basically works for any "hold mouse" operation, eg it even works in this text box to select text.  

I will definitely keep this on and try making it a part of my regular routine.  It's really handy to have an easy drag when covering large screen distances, and for dragging effects onto the timeline in FCP/Premiere, and probably many other uses.

In fact, I can even use it for my original request - as a way to draw in Photoshop! :)  I think I will still use the keyboard key for that, because it's nice to be able to instantly start/stop the operation by toggling a key; doing it with trackpad taps feels a little more imprecise, especially when a mis-tap will result in modifiyng the picture.    But it's great to know there's this option as well.

Thanks again @fifafu.  And @yay too for first mentioning it.

**Comment by yay** [comment]
@TheBloke Sorry, I should have been more specific. You can drag simply by placing _three_ fingers together over whatever you want to drag and moving them around. I guess, over time I got so used to this, that I stopped noticing that I'm using three fingers to drag instead of one, haha :)

**Comment by TheBloke** [comment]
I understand, @yay :)

That's also an Accessibility option, right?  "Three finger drag" ?  

I don't think I will use that because I worry it will conflict with my three-finger BTT Gestures.  But With Lock is doing the job great so I'm happy :)

**Comment by yay** [comment]
Yep, I was in the process of making a screenshot :)

<img width="780" alt="screen shot 2018-02-27 at 19 11 11" src="https://user-images.githubusercontent.com/1799756/36739880-18bddcb4-1bf2-11e8-9310-d9fb7f175139.png">

**Comment by RogerPAlexander** [comment]
@TheBloke, I want to do almost exactly what you have set up -- hold down F1 and then draw in Photoshop by just moving my finger on the trackpad.

My slight change is that I want to press F1 to *hold down the left mouse button* and then press it again to release the mouse button.  That way I don't have to hold F1 with one hand to draw with the other; I just press to toggle.

I have been scouring the Internet looking for a way to do this.  I think Keyboard Maestro could do it, but I would prefer a free solution.

I can't get the built-in Mac accessibility options to work for me -- three finger drag does exactly what I want, but I want to be able to use just one finger.  I can't figure out how drag lock works..

**Comment by TheBloke** [comment]
@RogerPAlexander Have you looked at Karabiner-Elements? 

That's what I use to map F1 to LMB, while held down.  That's a simple assignment, sent in Karabiner's  Simple Modifications:

![screenshot_2018-07-07 15 59 16_ahqnsy](https://user-images.githubusercontent.com/784313/42412148-b8419236-81fe-11e8-873c-6b4017d4ef53.png)

But Karabiner also supports 'Complex Modifications'.  That's where you can configure multi-key combos, stuff like "if X and Y are pressed at the same time, then do Z".

I don't know for certain if Karabiner can do what you want - set up F1 as a toggle - but there's definitely a chance.

Its documentation is here: https://pqrs.org/osx/karabiner/document.html

I notice under complex modifications it says: "Map keys by complex rules. e.g., key to modifiers, modifiers+key to key, send key event if pressed alone, etc."

I think for certain you could set it such that F1 holds LMB down (sending the key event LEFT_MOUSE_DOWN or whatever it's called), and then F2 releases it (sending LEFT_MOUSE_UP - or whatever it's called).   

I don't know off the top of my head how you would set up one key to toggle between the two states, but hopefully there's a way.  

If not, you could raise it as a feature request to Karabiner-Elements.  The developer updates it fairly often.
