### ISSUE TITLE
Custom app Touch Bar buttons disappearing when "Show macOS Control Strip" unchecked

### ISSUE THREAD

**Issue by jasonbytec** [folivoraAI/BetterTouchTool#2137]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
I have a custom Touch Bar set up for IntelliJ IDEA. In order to remove the "cross" button, I have unchecked "Show macOS Control Strip". This works the first time I switch to IntelliJ. However, when I switch away and then back to IntelliJ, all I can see is the escape key on the left and no custom buttons

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Touch Bar

#### Device information:
Type of Mac: Macbook Pro 13,3
macOS version: 10.13.3
BetterTouchTool version: 2.340

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by eripa** [comment]
I have the same issue. The macOS Control Strip keeps coming back even though I have it unchecked. I used to be able to always shows the BTT control strip and forget about the macOS one.

**Comment by eripa** [comment]
I ended up doing this to fix it:

- export my current presets in BTT to a `.json` file
- open the terminal and run:

```shell
rm -rf ~/Library/Application\ Support/BetterTouchTool
rm ~/Library/Preferences/com.hegenberg.BetterTouchTool.plist
rm -rf ~/Library/Application\ Support/com.hegenberg.BetterTouchTool
rm -rf ~/Library/Application\ Support/BetterTouchTool
rm -rf /Applications/BetterTouchTool.app
```

- I reinstalled the application 
- registered my licenses
- imported my old preset profile
- removed the  built-in standard preset profile
- changed my profile to be the default one
- changed the settings to enable touch bar support and unchecked the macOS control strip

now it works..

I suspect that there's some setting/cache thing in the folders that I removed that stopped it from working properly.
