### ISSUE TITLE
Black image icons are not changing to white when using black background button on touch bar

### ISSUE THREAD

**Issue by zupodaniel** [folivoraAI/BetterTouchTool#2139]
All old icons assigned are correctly displaying white, even if the file inserted was black. New icons inserted, custom or in the predefined list are not changing to be white. 

Background colour of button is: #121212 and any image of the predefined list or external sources.

BTT version is 2.340.

**Comment by fifafu** [comment]
Mh this seems to work fine here. However BTT checks whether the picture contains color - if so it doesn't automatically change it. Only if black/white icons are used.

Are you sure it also doesn't work with the included icons?

**Comment by zupodaniel** [comment]
Yes, I'll send you a short video.

https://www.dropbox.com/s/e7zxia11bbobmrr/20180221_113735_1.mp4?dl=0

**Comment by zupodaniel** [comment]
@fifafu Any idea to solve that problem? BTT is really less customizable with this bug. I'm using now v2.467 and the same behaviour continues.

**Comment by fifafu** [comment]
unfortunately I haven't had similar reports yet and am unable to reproduce it here.
Could you maybe send me an image that doesn't work?
Or is it really all images (including the ones available in BTT?)

**Comment by zupodaniel** [comment]
All imagens including the ones available in BTT. I'm sending you my profile by email to check if you can reproduce in your machine. Thank you.

**Comment by fifafu** [comment]
This is how your Touch Bar looks on my machine (while in Chrome)

https://github.com/folivoraAI/BetterTouchTool/issues/2139

**Comment by zupodaniel** [comment]
It's ok because I have used white icons to be the forward and reward buttons. Try to change these buttons to black color images and you'll see that they won't change to white.

**Comment by fifafu** [comment]
They do here :-(
![image](https://user-images.githubusercontent.com/8820811/39576935-280edaf8-4ee0-11e8-9401-9e4edc8dc51d.png)

Do you have any special color profiles activated for your display? Maybe that somehow confuses BTT.

**Comment by zupodaniel** [comment]
Yes, my displays are configured with a color profile made by displaycal and the hardware colorimeter 1DisplayPro

**Comment by zupodaniel** [comment]
Yes, I can confirm that disabling profiles the function that check if the color needs to change works as expected again.
