### ISSUE TITLE
Better support for Elecom Huge M-HT1DRBK

### ISSUE THREAD

**Issue by lykahb** [folivoraAI/BetterTouchTool#2140]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
BTT does not recognize the FN buttons.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Elecom Huge M-HT1DRBK

#### Device information:

Type of Mac: Macbook Pro 2015
macOS version: High Sierra, 10.13.3
BetterTouchTool version: 2.340

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by TheBloke** [comment]
Did you see the help under "if buttons are not recognised":

```
Other Mice

If you have installed any driver/software for your mouse, make sure to not assign any actions to the buttons in that software. 
If this doesn't help try to uninstall the driver/software. If your mouse buttons are still not being recognized afterwards, your mouse is most likely not supported in BTT. 
Some mice also act as keyboard - you may try if a shortcut is recognized in BTT's keyboard tab when pressing a button.
```

My guess is that the Fn button is not even being seen by BTT.   If you have the ability to map the buttons use a  driver, you could map the Fn buttons to some keyboard shortcut (shift-command-option-F9 or whatever) and then assign that as a keyboard gesture in BTT.  

But I don't see a macOS driver available for this mouse, only Windows.

To check if any keyboard key is already being sent, go to:
- Keyboard Gestures -> Add New Shortcut or Key Sequence -> Key Sequence -> Record New Key Sequence.  

Now press your Fn buttons and see if any keys appear in the recording.  If they do, then you can map them in BTT's Keyboard Gestures.

If nothing appears there, finally you could double check no mouse code is being sent by downloading and installing [Karabiner-Elements](https://github.com/tekezo/Karabiner-Elements/releases), then from its menu bar select "Open Event Viewer"

In the Event Viewer, click in the Mouse Area using first normal buttons (left mouse button etc) and then your Fn buttons.   You will definitely see log entries for Left Mouse Button but do you see them for the Fn buttons?

If not, then macOS is not even seeing these button presses and nothing can use them.

If they are being picked up, then list which codes it's sending and then BTT might be able to use them.  Or they might be remappable in Karabiner into a keyboard shortcut that BTT can then recognise.

**Comment by lykahb** [comment]
Thank you for the explanation. The manufacturer provides a driver for MacOS http://www.elecom.co.jp/global/download/utility/mouse_assistant/mac/index.html, but it is so buggy that even the settings window cannot open. It is no longer installed on the machine.

I tried the Event Viewer, the Fn buttons are not reported. Thank you, this is not a BTT issue.

**Comment by TheBloke** [comment]
You are welcome.  I have had similar problems with gaming mice in the past.   Very few have decent macOS software.

If you want to try another mouse, then I know that Razer's software works OK on Mac.  They don't have a trackball mouse, but they have lots of general gaming mice with lots of buttons.   Logitech do have a trackball mouse, and I know they have Mac software (it is shown in the BTT documentation.)  I have no personal experience of using it though.

In the end I instead bought an Apple Magic Trackpad 2 and it is one of the best peripherals I ever bought - thanks to BTT advanced gestures.  I now hugely prefer it to using a mouse.  And the experience of a trackpad is somewhat similar to a trackball.

I can highly recommended it, if you are able to get one.  Even the Trackpad 1 would be good (and much cheaper), though it is nice to have the Force Touch of the Trackpad 2.

**Comment by stevenla** [comment]
I have a lot of trouble with the included ELECOM drivers. I can't uninstall it, and I can't re-install it. If it's supported by BTT, that would be awesome.

**Comment by lykahb** [comment]
@TheBloke 
I found a similar issue with HID that got fixed in the linux kernel driver https://blog.flameeyes.eu/2017/04/elecom-deft-and-the-broken-descriptor/

This will likely solve the Fn problems with most Elecom trackballs. Can it be ported to BetterTouchTool?

**Comment by TheBloke** [comment]
@lykahb  that's a device driver fix.  That information could be used by someone to create a working macOS driver for these devices (or modify an existing one), but I don't believe it's anything BTT can help with.

BTT uses the standard operating system APIs to access and use devices - it sits at a level above device drivers, and requires the drivers are in-place and working in order to get the information it requires.

In other words I don't believe there's anything Andreas can do with that information to make the device work in BTT.  Other than actually making a device driver himself, which I can't imagine he is ever going to want to do :) Especially not for a relatively niche piece of hardware.

But if there's any macOS developers out there who have an Elecom, they could perhaps make an open-source driver for the device using the information you provided, and then anyone using that driver would get full functionality in BTT (and other apps.)

Really though it's down to Elecom themselves - they should be made aware of the required fix and perhaps they'll add it to their drivers.  Then again, you said it's so buggy it doesn't even open, so I guess they're unlikely to be helpful.

**Comment by fifafu** [comment]
Unfortunately @TheBloke is right.

However I plan to add a feature to BTT that would allow to listen to "raw device hid events" which may work for this device. However this is still a few versions away from being usable.
