### ISSUE TITLE
basic functions in BTT

### ISSUE THREAD

**Issue by qeisar** [folivoraAI/BetterTouchTool#2142]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Hi, It seems that one of the basic functions in BTT that I heavily rely on is not behaving properly. I define one app specific keyword (command +3) to simulate ( command + K followed by Enter). It is simple but for hundreds of times per day, it saves me a lot of time. Now, it works only for a couple of times, then it stops working. 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Keyboard shortcut

#### Device information:

Type of Mac: MacBook Pro 2015 15"
macOS version: High Sierra 10.13.3
BetterTouchTool version: 2.340 (719)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Do you still encounter this with more recent versions?
