### ISSUE TITLE
Window Snap in BTT

### ISSUE THREAD

**Issue by regmikewall** [folivoraAI/BetterTouchTool#2143]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.): iMAC with Magic Mouse q
2

#### Device information:

Type of Mac: iMAC
macOS version: 10.12.6
BetterTouchTool version: 2.340

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
Tried to use window snap, does not work as the video shows, I have the check box checked, I have stopped BTT and then relaunched.  I have not configured my magic mouse 2 yet.

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Hi,

sorry I  think you forgot to include the link to the video.
In general window snapping works fine. Make sure to have BTT enabled in System Preferences => Security & Privacy => Privacy => Accessibility

 Best,
Andreas

**Comment by regmikewall** [comment]
Andreas, 

 

Tried to send you a video, 19mb in size, it was rejected, what size video do you accept, will try to share it with you via dropbox.  See below for the fact that BTT is enabled in Accessibility.

 

 

Mike 

From: Mike & Reggi Wallace <regina.michael80@gmail.com>
Date: Thursday, February 22, 2018 at 5:11 PM
To: fifafu/BetterTouchTool <reply@reply.github.com>
Subject: Re: [fifafu/BetterTouchTool] Window Snap in BTT (#2143)

 

Andreas, 

 

Thank you for your quick response

 

here is the video

 

I have BTT Enabled in my SP/S&P/P/as mentioned.

 

 

Mike

**Comment by regmikewall** [comment]
Hi there,

Mike Wallace (regina.michael80@gmail.com) invited you to edit the folder " BTT " on Dropbox.

Mike said:
"Here is the video, please let me know you got it."

Go to folder[1]

Enjoy!
The Dropbox team

[1]: https://www.dropbox.com/l/scl/AACx1Z3L-rlH9BlTzjQIskorwgrINcbqRNM

**Comment by regmikewall** [comment]
Andreas

 

I sent you a dropbox share with the video, Please let me know you got it.

 

 

Mike 

 

From: Mike & Reggi Wallace <regina.michael80@gmail.com>
Date: Thursday, February 22, 2018 at 5:17 PM
To: fifafu/BetterTouchTool <reply@reply.github.com>
Subject: Re: [fifafu/BetterTouchTool] Window Snap in BTT (#2143)

 

Andreas, 

 

Tried to send you a video, 19mb in size, it was rejected, what size video do you accept, will try to share it with you via dropbox.  See below for the fact that BTT is enabled in Accessibility.

 

 

Mike 

From: Mike & Reggi Wallace <regina.michael80@gmail.com>
Date: Thursday, February 22, 2018 at 5:11 PM
To: fifafu/BetterTouchTool <reply@reply.github.com>
Subject: Re: [fifafu/BetterTouchTool] Window Snap in BTT (#2143)

 

Andreas, 

 

Thank you for your quick response

 

here is the video

 

I have BTT Enabled in my SP/S&P/P/as mentioned.

 

 

Mike

**Comment by fifafu** [comment]
mhh looks all good.
There is currently one known app which (as far as I know) breaks all window snapping tools, it's "Dragon Dictate". Do you maybe have that installed?
(I had hoped BTT 2.340 would workaround this though)

**Comment by regmikewall** [comment]
No, I do have ghosterly installed, could that be an issue?

 

Are there some settings that might cause this issue?

 

I have Textexpander, Commander One, Mail, Safari, Calendar, SpellCatcher, Messanger, Excel, Activity Monitor, Adobe Creative Cloud, Malwarbytes running.

 

 

Mike

**Comment by fifafu** [comment]
I have not heard of any issues with these apps :-(
If you have not done this yet, maybe try to reboot your Mac.

If this doesn't help I will check whether one of the apps causes an issue.

Is there maybe anything special about your display setup?

I'm now going to sleep (Germany), so I won't be able to look into it until tomorrow.

**Comment by regmikewall** [comment]
Andreas,

 

Have a good sleep, not normal screen set up, will do some more checking and get back to you tomorrow.

 

 

Mike

**Comment by regmikewall** [comment]
Good Morning Andreas

 

Still “Window Snap” does not work, even after my computer being shut down overnight.

 

Another question. – is there any timeline on when the documentation will be completed, little hard to learn a new app when you have limited documentation?

 

So far am learning the app by trial and error. So a functionality I would like to use is:

 

I Want to be able to swipe a window (not full screen) off my computer screen to an attached monitor either right or left, which Action group & action should I use?  Not clear what I need to do.

 

Thanks in advance for your help

 

Mike

**Comment by regmikewall** [comment]
Andreas

 

Any idea when the documentation will be completed or at least the magic mouse 2 documentation will be done.

 

The window snapping still is not working 

 

Thanks in advance for your help

 

 

Mike

**Comment by fifafu** [comment]
It will never be finished as BTT continues to change, but I'll add more pages in the coming weeks and months now that I'm self employed. However there are tons of tutorials and youtube videos out there, this should be a pretty good resource already :-)

Unfortunately I haven't been able to figure out what could break the Window Snapping on your machine :-( I have not had any similar reports yet and the apps you listed seem to be fine.
I still assume it is some app that breaks the snapping, but I don't know which it could be :-(

**Comment by regmikewall** [comment]
Are there apps or setting that will break snapping that you know of, I can see if this is the issue on my computer

 

 

Mike

**Comment by fifafu** [comment]
The only problematic app I know so far is "Dragon Dictate" (some voice recognition software)

**Comment by regmikewall** [comment]
What about setting on the computer – Popups, etc…..

 

 

Mike

**Comment by fifafu** [comment]
Nothing really relevant as far as I know.
The only precondition is the Accessibility API being activated for BTT, but it would warn you if that would not be enabled already. 

One thing you could try is whether the "custom snap area" feature is working. (Select some App window, then click  the BTT menubar icon and click "Snap Areas => Create Custom Snap Area")

**Comment by regmikewall** [comment]
Andreas

 

That worked, got a pinkish area around the whole window, clicked on the center area, got a bluish area that I could then resize for the snap area, then clicked cmd + w to exit.

 

 

Mike

**Comment by fifafu** [comment]
and does this area appear now when you drag a window?

**Comment by regmikewall** [comment]
No, same issue

 

 

Mike
