### ISSUE TITLE
Ctrl + Trackpad Tap in virtual machine Windows

### ISSUE THREAD

**Issue by ssblee** [folivoraAI/BetterTouchTool#2145]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

I am using Parallels Desktop to use Windows in my MacBook.
I switched on the macOS preference "Trackpad -> Point & Click -> Tap to Click".
Then the behavior of "Ctrl + Trackpad Tap" within the Windows installation is different!

1. When BetterTouchTool is **off**, "Ctrl + Trackpad Tap" is translated to "Ctrl + Click" in Windows.
2. When BetterTouchTool is **on**, "Ctrl + Trackpad Tap" is translated to "Right Click" in Windows.

On the other hand, the following behaviors are consistent, independent from whether BTT is on or off:
* Ctrl + Trackpad Tap: Right Click. (since I turned on the macOS preference "Trackpad -> Point & Click -> Tap to Click")
* Ctrl + Trackpad Click: Right Click.
* Ctrl + Trackpad Click: Ctrl + Click.

In my opinion, "Ctrl + Trackpad Tap" should be "Ctrl + Click" in windows, as it is without BTT, since I didn't change / make any setting about "Ctrl + Trackpad Tap" within BTT.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

MacBook native Trackpad and bluetooth Trackpad

#### Device information:

Type of Mac: MacBook Pro (Retina, 15-inch, Mid 2014)
macOS version: 10.12.6(16G1212)
BetterTouchTool version: 2.340 (719)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
In general BTT doesn't do anything if you don't have it configured to do it. Did you maybe create a trigger in the normal mouse tab in BTT?

Sorry for not replying earlier.

**Comment by ssblee** [comment]
>> Did you maybe create a trigger in the normal mouse tab in BTT?

No. I didn't create any trigger for normal mouse and magic mouse.
I've set only 3-finger left/right gestures for trackpad, and set some shortcuts for keyboard.
