### ISSUE TITLE
Add Numeric Keypad Keys

### ISSUE THREAD

**Issue by bassplayinMacFiend** [folivoraAI/BetterTouchTool#2150]
Blender uses numeric keypad presses to change views, and uses the numbers above the keyboard to change layers. Is there a way to make number keys for the touchpad that transmit numeric keypad codes while the number keys send regular number key codes.

Right now I need to either use an external USB keyboard with a number pad or connect an external number pad and I would like to replace this with BTT.

**Comment by mgmhunt** [comment]
Recognise standard number presses vs numeric presses also.  ie recognise difference between the two in the 'Custom Keyboard Shortcut' input box. (Perhaps checkbox for 'doesn't matter' ie 0 on keyboard AND numeric keypad 0 do same thing?)
