### ISSUE TITLE
Feature Request: BTT scripting

### ISSUE THREAD

**Issue by TheBloke** [folivoraAI/BetterTouchTool#2159]
#### Description of feature request:

I'm sure you've thought of this and maybe it's a lot of work.  But I'd love to see a scripting system in BTT.

- A new action, "Run script".
- The ability to write a script that at the least can run any other BTT action, but ideally can also  manipulate Gestures and also interact with the macOS environment (enumerate windows; read active Finder windows; etc.)

A primary purpose would be a replacement for Action Groups:  rather than stringing together "Attach additional action", I would just write a little script that ran each action in turn.

This would also make it much easier to replicate complex actions, like the action series I use for "Move Monitor X a Space" (which requrires: Hide Mouse Pointer; Save Mouse Position ; Move Mouse to ... ; Move Left a Space ; Restore Mouse Position ; Show Mouse Pointer).

This would enable much more sophisticated control:  for example, perform different actions dependent on how many active monitors there are, or dependent on which Space I am currently on.

Ideally a script could also manipulate BTT;  for example, a script that disables or enables certain gestures.

Potentially it would allow for some much more complex actions.  For example:
- Enumerate open windows, and create a Touch Bar icon for each of them, thus creating a Touch Bar window switcher.
- Iterate through all Firefox windows on current monitor, and split their windows evenly across the monitor
- Trigger the screenshot dialogue, and when the screenshot is taken save it to a file which is opened in Photoshop.  In a timer loop, monitor the saved filename for changes; when the file is changed, upload it to Imgur then prompt to delete it.

Some of these might require a complex set of script methods with the ability to interact with macOS in general.  I don't know how much work this is, and to what extent an existing scripting language could be integrated into BTT.  

Or maybe it can be kept simpler by allowing the user to run shell/AppleScript scripts that perform these functions, then process their result.  For example if there's a shell script that can enumerate windows and return their ID, then the BTT scripting would just need to be able to call this script and iterate through its output.  It'd be nicer if BTT Script had native methods, but processing external scripts could be an easier solution.

I know there are many other tools for automating workflows - I already have both Alfred and Keyboard Maestro installed, which can create advanced macros/scripts to achieve some of these things.  I could trigger them from BTT to run some workflows.

But BTT's big advantage is its huge list of advanced Actions.  A scripting language that could leverage these actions and be easily triggered direct in BTT, and also can monitor and modify BTT's behaviour, could be hugely powerful.  I would rather have BTT  do these things, than implement them in another app and then try to integrate them with BTT's other actions.

**Comment by TheBloke** [comment]
As a first, simple step, a 'script' could be as simple as a text box into which the user can add a list of tokens specifying BTT actions.    No other syntax, no iterators or conditionals, just eg:
```
ShowHideMouseCursor
SaveCurrentMousePosition
MoveMouseTo: 1133,999
MoveLeftASpace
RestoreSavedMousePosition
ShowHideMouseCursor
```

This isn't a script language, just a literal script of actions to run unconditionally one after the other.

But it would serve as a useful replacement for long Attach Additional Action lists which are currently difficult and time consuming to manage.

It could then be later expanded into a more complex scripting language if/when that's possible.

**Comment by TheBloke** [comment]
Another alternative to a complex  built-in scripting language:

provide a way to trigger a BTT action externally.  For example, be able to run:
- `/Applications/BetterTouchTool.app/Contents/MacOs/RunCommand "MoveLeftASpace"`
- `/Applications/BetterTouchTool.app/Contents/MacOs/RunCommand "Maximize Window"`
- `/Applications/BetterTouchTool.app/Contents/MacOs/RunCommand "3FSwipeLeft"`

etc

If this was possible, then the user could create an Action that runs a shell script or AppleScript which can trigger BTT actions.  This external script could then also do more advanced system stuff, like iterating through a list of open windows, and call BTT actions on the result as appropriate.

It wouldn't be as nice as integrated scripting, but it would presumably be much quicker and easier to implement.

It would require that these BTT actions could take some parameters, such as a WindowID or whatever's required to run commands on a given window.  And ideally RunCommand would return some output given details of the action, for example if Screenshot is run, it would output the name of the resulting file. 

I don't know to what extent  it's possible to write a shell or Apple script that iterates windows, gets the current active monitor/space number, etc; maybe those sort of example scripts wouldn't be possible with this method.   But a more advanced language like Python might be able to do it, and a Python script can be easily called from BTT.

So while the result wouldn't be as good as a fullly integrated scripting engine, it might still provide some extra functionality and power, without requiring much work in BTT itself.

**Comment by TheBloke** [comment]
> provide a way to trigger a BTT action externally. For example, be able to run:

I just discovered by accident that this already exists.  BTT creates URLs for every gesture, eg `btt://83BD4D13-616D-4DA8-A546-01812BD0B066`

This can be triggered from a shell script, eg: `open 'btt://.....'`

So this could be used for some basic scripting tasks - BTT calls a script which in turn can call BTT actions.

But passable arguments would be required for something closer to the sophistication I was ultimately hoping for.

Still, it's good that this exists already.

**Comment by fifafu** [comment]
I plan to make this much more flexible soon!
