### ISSUE TITLE
Edge Recognition Area

### ISSUE THREAD

**Issue by k-44** [folivoraAI/BetterTouchTool#2166]
#### Description of feature request:

Please make the "Edge Recognition Area" bigger (or configurable).

In Advanced Settings > Window Snapping you can change the size of the "Corner Recognition Area" from 1 to 80 pixels. I would like to have a similar setting for "Edge Recognition Area" (e.g. left side of the screen), because I have multiple monitors and always slide to the next monitor, before the edge get's recognized, since the area is (my guess) about 10 pixels wide only. 

Also I would prefer to make the corner recognition area bigger like say max. 250 pixels (instead of max. 80; I have big screens). The same for the "Edge Recognition Area".

Btw.: love your software! Thanks for the good work!

**Comment by thunder-road** [comment]
Second this. Great software and very useful. 

One thing i'm having difficulty with is the snapping. The way its implemented it seems it goes by the position of the mouse. This makes it hard to use the trackpad as you usually tend to grab a window at the top in the middle of the window frame, thus to drag to a corner you have to drag a long way down in the corners to get it to snap, even with corner recognition set to 80. This is on a MacBook pro 15". 

I think it might be worth considering having an option that worked by using the actual window edge/corner X/Y positions to make the determination, especially for small windows, it would be ideal for them. I can see how this might not work for say a larger window the height of the screen say, but perhaps you could throw some logic in there to fall back to the current method for tall windows.Anyway throwing out some ideas. 

Thanks for listening, and great work!
