### ISSUE TITLE
Feature request: Focus follow mouse

### ISSUE THREAD

**Issue by sbogun** [folivoraAI/BetterTouchTool#2170]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Feature request: Focus follow mouse

If the mouse is moved over to another window (which may be a window of another application) this windows gets the focus and is activated without the need to click into the window (Zooom/2 provided this feature, but was discontinued).

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Any tracking device (mouse, trackpad, ...)

#### Device information:

Type of Mac: MacBook Pro (Retina, 13-inch, Early 2015)
macOS version: 10.13.3
BetterTouchTool version: BetterSnapTool 1.8

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by mgmhunt** [comment]
Upvote!! Set either global or on a per app basis would be great.

**Comment by waxfingers** [comment]
Indeed it would be nice 👍. For more "adventurous" people, currently it is possible to do that and a zagilion more things with ***Afloat*** plugin running within mySIMBL & [flashlight](https://github.com/w0lfschild/Flashlight).   
   
![fm_mysimbl_web](https://user-images.githubusercontent.com/13238340/38887750-9415d6fa-4271-11e8-9c5f-d42c5c9e8508.jpg)

**Comment by mgmhunt** [comment]
Above solution requires turning off System Integrity Protection, so something that doesn't require that step would be great.  Tempting to turn off SIP (for XtraFinder too..) but would prefer to avoid this for work computers.

**Comment by fifafu** [comment]
the problem with this feature is that it can only be implemented efficiently with hacks like used in afloat.

I'm currently thinking about adding an optional feature that would however also require to disable SIP temporarily.

**Comment by waxfingers** [comment]
> but would prefer to avoid this for work computers.
I perfectly understand you

For completeness (and fairness) sake I'll add that flashlight only needs SIP disabling for installation, then you can re-enable it. BTW I'm running XtraFinder and Flashlight (Afloat plugin among many others) with SIP enabled, macos 10.13.4 =)  

@fifafu I had a (wet) dream; calling BTT (search its shortcuts' database, run a script, interact...) through spotlight, powered by mySIMBL / Flashlight 🍄

**Comment by ussher** [comment]
Thanks for that info @waxfingers it does work to bring the focus TO flashlight when the mouse is over it, but it doesn't work to put the focus on any other windows when the mouse is moved away from flashlight.  I was hoping it would work for moving between any windows to bring whatever is under mouse into focus.  For you does it work to focus any open windows?
