### ISSUE TITLE
Feature Request: Finder's Dialog Windows

### ISSUE THREAD

**Issue by kefirux** [folivoraAI/BetterTouchTool#2173]
#### Description of bug/feature request/question:

Finder's shortcuts \ gestures don't work in dialog windows. So my request is to fix it. I used to use Xgestures and it had an option to control dialog windows.

**Comment by fifafu** [comment]
Can you give an example? I think BTT actions should work everywhere in Finder.

**Comment by fifafu** [comment]
Ah I understand.

I think I can add this.
However unfortunately this would require BTT to check everytime whether such a dialog is open before triggering anything, which definitely has a performance impact. Thus I'd not enable this behavior by default.

**Comment by kefirux** [comment]
That would be lovely, thank you

**Comment by kefirux** [comment]
Hi! I saw that you'd added this feature into the build, thank you. However I have a question: where do I find this option in the settings?
