### ISSUE TITLE
CPU Usage too high!

### ISSUE THREAD

**Issue by robgraeber** [folivoraAI/BetterTouchTool#2174]
#### Description of bug/feature request/question:
Hi there, I noticed an issue where sometimes BTT's script runner goes to 100% and the whole computer is not very responsive. Also the overall CPU Time is way too high (4x the CPU Time of google drive!) that I'm considering uninstalling to increase my battery life.

<img width="525" alt="screen shot 2018-03-03 at 7 07 11 pm" src="https://user-images.githubusercontent.com/2387719/36941732-42d1a0ee-1f17-11e8-8010-51ac12e0c559.png">

#### Device information:

Type of Mac: Macbook Pro
macOS version: 10.13.3
BetterTouchTool version: 2.340

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

Here's the custom touch bar scripts I have (API keys removed). Theres 1 script for bitcoin prices, 1 for stock prices, 1 for weather, and 1 for spotify. The 3 scripts that make api requests are ran every few minutes, the spotify script that checks the currently playing song is ran every 1 second.
 
[Default copy.json.zip](https://github.com/fifafu/BetterTouchTool/files/1778128/Default.copy.json.zip)

**Comment by fifafu** [comment]
You probably have some touch bar scripts running that cause problems. Try to disable them if possible.

**Comment by robgraeber** [comment]
I think it's coming from this script:
```applescript
 if application "Spotify" is running then
	tell application "Spotify"
		if player state is playing then
			return (get artist of current track) & " - " & (get name of current track)
		else
			return "No Song Playing"
		end if
	end tell
 else
	return "No Song Playing"
 end if
```

**Comment by robgraeber** [comment]
I tried editing the script to this and it seems to be fixed so far, I'll report back if I still have the issue:
```applescript
with timeout of 1 second
	if application "Spotify" is running then
		tell application "Spotify"
			if player state is playing then
				return (get artist of current track) & " - " & (get name of current track)
			else
				return "No Song Playing"
			end if
		end tell
	else
		return "No Song Playing"
	end if
end timeout
```

**Comment by robgraeber** [comment]
Nvm that didn't fix it, I'll narrow it down some more.

**Comment by fifafu** [comment]
Mhh, could you check whether there is a "massive" amount of logs in the macOS Console.app related to BetterTouchToolScriptRunner?

**Comment by fifafu** [comment]
This crash has already been fixed :-)

Could you go to the about screen in BTT and click the "Export debug information" button? This will create a folder called BetterTouchToolDebug on your Desktop. Would be great if you could zip & mail that to boastr.net@gmail.com (please reference this issue). Maybe I can reproduce the issue here.

**Comment by robgraeber** [comment]
Okay emailed the debug info.

Seems like the last guy that had the issue was running the same spotify script: https://github.com/fifafu/BetterTouchTool/issues/1013

I don't really know enough about applescript to know how that script can hang. Whatever it is, it takes some time to happen. Maybe more than an hour but less than a day.

**Comment by merlinND** [comment]
I am experiencing the same issue: everything works perfectly well for a long time, with only small CPU usage spikes for `BetterTouchToolScriptRunner` whenever scripts are run.
However, sometimes, it gets stuck at 100% usage forever. I am using a Spotify "what's playing" script (see below), one to get the next calendar event, one for unread e-mail count. I have been experiencing this issue for months.

I am e-mailing you the exported debug information and one "diagnostic" file I found in the Console.

Here's the Spotify script that I am using:

```applescript
if application "Spotify" is running then
	tell application "Spotify"
		if player state is playing then
			set theTrack to current track
			set theArtist to artist of theTrack
			set theName to name of theTrack
			-- set playStatus to "playing"
			-- return ("♫ " & (theArtist as string) & " - " & (theName as string))
			return ((theArtist as string) & " — " & (theName as string))
		else
			return ""
		end if
	end tell
else
	return ""
end if
```

**Comment by robgraeber** [comment]
Seems like other projects have the same issue with spotify's applescript integration: https://github.com/ShyykoSerhiy/vscode-spotify/issues/12

But apparently there's a private API and an unofficial node.js library for accessing it: https://github.com/ShyykoSerhiy/spotilocal

**Comment by fifafu** [comment]
That's interesting, I'll look into it. (Although using a nodejs library is probably not the way to go, most users won't have nodejs installed)

**Comment by merlinND** [comment]
Interesting find @robgraeber!
As a workaround, we could maybe have a BTT option to kill the script's process after x seconds?  
Similar to what [Rob proposed](https://github.com/fifafu/BetterTouchTool/issues/2174#issuecomment-370351742) with the timeout, but at the BTT level so that a hung script wouldn't pose problems.

**Comment by fifafu** [comment]
Yes, I that should work. I think I'll add a general timeout option, that may make sense for other scripts too.

**Comment by fifafu** [comment]
One thing that would be interesting:
If the CPU is at 100%, does killing the BetterTouchToolScriptRunner process solve the issue again for a bit? (terminal command: ```killall BetterTouchToolScriptRunner```)

**Comment by robgraeber** [comment]
It might be possible to package any node.js app as a binary with https://github.com/zeit/pkg or https://github.com/nexe/nexe

So in theory it can be brew installed as 1 package, obviously a PITA though.

**Comment by merlinND** [comment]
> If the CPU is at 100%, does killing the BetterTouchToolScriptRunner process solve the issue again for a bit? (terminal command: `killall BetterTouchToolScriptRunner`)

Yes, that's how I've solved it so far. Btw, it's nice that BTT recovers by restarting the process when necessary!

**Comment by fifafu** [comment]
@merlinND great, I think then the easiest solution for me is to add a timeout option that just kills the process if it doesn't return the result within x seconds.

**Comment by merlinND** [comment]
@fifafu Awesome! Thanks for being so responsive, and thanks for this amazing tool!
As someone said in another issue, you single-handedly made the TouchBar a must-have when even Apple didn't!

**Comment by robgraeber** [comment]
@merlinND As a workaround for now, it might be possible to use a timeout via a shell script:   

`brew install coreutils`
```shell
gtimeout 1 osascript <<EOD
         if application "Spotify" is running then
		tell application "Spotify"
			if player state is playing then
				return (get artist of current track) & " - " & (get name of current track)
			else
				return "No Song Playing"
			end if
		end tell
	else
		return "No Song Playing"
	end if
EOD
```

**Comment by fifafu** [comment]
Have you experienced this issue with recent BetterTouchTool versions?

I had forgotten about it, but I have added an option to set a timeout. (Currently only via this terminal command):
```defaults write com.hegenberg.BetterTouchTool BTTAppleScriptTimeout 50```

The default value is 100 seconds.
