### ISSUE TITLE
macOS style button into control slider

### ISSUE THREAD

**Issue by SweetJD** [folivoraAI/BetterTouchTool#2181]
I'd like to request a new type of control slider. On the system wide controller, you can push down on the volume or brightness buttons to summon a slider. Would it be possible to implement this feature in BTT?

**Comment by draculaentsteint** [comment]
was also wondering if this is possible, since it would require less space and i'd love to remove the macos control strip to get rid of the x on the left hand side of the touchbar.

**Comment by fifafu** [comment]
This feature is a bit complicated, but alpha v2.468 ALPHA adds a possible alternative.
You can now add two/three/four finger swipe gestures to the Touch Bar and use them e.g. to change volume/brightness just by sliding with two fingers anywhere on the bar.


![image](https://user-images.githubusercontent.com/8820811/39425163-75c22ff6-4c7a-11e8-98fb-a15fb3accf27.png)
