### ISSUE TITLE
[Feature Request] Magic Mouse action 2 fingers: (1 finger swap and 1 finger fixed)

### ISSUE THREAD

**Issue by davizucon** [folivoraAI/BetterTouchTool#2190]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Feature request for magic mouse/trackpad using two fingers. For instance, to close a windows hold ring finger and swap index finger to left.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Magic Mouse/Trackpad

#### Device information:

Type of Mac:
macOS version: 
BetterTouchTool version: 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by davizucon** [comment]
Hi @fifafu, has this feature been implemented?

**Comment by fifafu** [comment]
The BTT issue tracker has moved to https://community.folivora.ai early this year and all issues here have been auto-closed now. In case you still need help with this issue / feature / question please create a new post there.
