### ISSUE TITLE
Custom Snap Areas Break Until BTT Restart

### ISSUE THREAD

**Issue by CarterVE** [folivoraAI/BetterTouchTool#2191]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

I've been noticing an issue where my custom snap areas will not work after sleeping my computer (most times, sleeping the computer does not always break them). This issue does not affect the default snap areas, only the custom ones I have created. The only way I've found to get them to work again is to restart BTT, which isn't such a big deal, but is annoying to do every time I sleep my computer.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

MacBook Trackpad

#### Device information:

Type of Mac: MacBook Pro 2017 15"
macOS version: 10.13.3
BetterTouchTool version: 2.340 (719)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by verdi1987** [comment]
I have had this issue for a very long time — at least a year or more. For me it is reproducible 100% of the time when my Mac has slept for any significant period (say an hour or longer).

I have 9 custom snap areas across two monitors (6 on one, 3 on the other).

As the OP stated, the workaround is to restart BTT.

**Comment by verdi1987** [comment]
This issue seemed to have been resolved for me over the last month or so but has resurfaced again in 2.530 (865).
