### ISSUE TITLE
Rate limiting for AppleScript Slider?

### ISSUE THREAD

**Issue by bn86** [folivoraAI/BetterTouchTool#2192]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

I am using the AppleScript slider to send its value via MQTT to an Arduino, which is _really exciting_. Just got my MacBook Pro today, so naturally this is what I'm playing with first :)

The problem is, it sends so many values, it's still sending them long after I finished sliding. I think some kind of rate limiting would help. I think I need to be able to move the slider fast, and have it only send a few values, rather than hundreds. Maybe this limiting could just go in the script? Any ideas would be greatly appreciated.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Touch Bar

#### Device information:

Type of Mac: MacBook Pro
macOS version:  10.13.3 
BetterTouchTool version: 2.355

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

Here's my existing code:

	on bttWidgetSliderMoved(sliderValue)
	
	set message to sliderValue
	
	do shell script "curl [-X POST 'http://try:try@broker.shiftr.io/example' -d '" & message & "'"
	
	end bttWidgetSliderMoved

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
You can already do that,see this screenshot:
![image](https://user-images.githubusercontent.com/8820811/37241155-970ba4ce-2454-11e8-94ef-47cfbb1dbc36.png)

**Comment by fifafu** [comment]
Ah no you want it to send "all" possible values, but only after a given time has passed after the last send?

**Comment by bn86** [comment]
Thanks for your help.

I tried that 20% thing, but that still sends lots of data. When I move the slider slowly, all the values have time to send and it all works quite smoothly, but if I move the slider fast the values are still being sent for a few seconds after I've finished sliding. 

I think if the slider moves fast, there's no need to send all the values, just the final one?

**Comment by brantwedel** [comment]
If you are feeling a bit adventurous, this should work:
```
on bttWidgetSliderMoved(sliderValue)
    set message to sliderValue
    # save time and random number (since apple script time is only available as seconds)
    # execute shell command in background with a short delay to see if value changes
    do shell script "(defaults write local.yourscriptname.yournamespace last_value_time \"" & (time of (current date)) & "_" & (random number from 1 to 1000) & "\"; " & "MY_VAL=$(defaults read local.yourscriptname.yournamespace last_value_time); sleep 0.5; MY_VAL_2=$(defaults read local.yourscriptname.yournamespace last_value_time); [ \"$MY_VAL_2\" == \"$MY_VAL\" ] && curl [-X POST 'http://try:try@broker.shiftr.io/example' -d '" & message & "'";) &>/dev/null &disown"
end bttWidgetSliderMoved
```
