### ISSUE TITLE
[QUESTION] Widget functionality

### ISSUE THREAD

**Issue by CarterVE** [folivoraAI/BetterTouchTool#2206]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

I was wondering, do widgets run if they are in a button group and the group is not open? What about if they are set for a specific app (not global) and the app is not active? What if the app is not open (quit)?

Trying to understand the energy impact of my scripts.

Thanks!

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Touch Bar

#### Device information:

Type of Mac: MacBook Pro 15" 2017
macOS version: 10.13.3
BetterTouchTool version: 2.340 (719)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
- Widgets in groups only run if the group is open
- App specific widgets only run if that app is front most  (thus they also don't run if the app is quit)

You could e.g. verify this by displaying a notification:
https://developer.apple.com/library/content/documentation/LanguagesUtilities/Conceptual/MacAutomationScriptingGuide/DisplayNotifications.html

**Comment by CarterVE** [comment]
Fantastic thank you!
