### ISSUE TITLE
Mapping to keyboard arrows impossible in Xee3 app

### ISSUE THREAD

**Issue by aitte2** [folivoraAI/BetterTouchTool#2207]
#### Description of bug/feature request/question:

In TextEdit, I can say: "Input: Keyboard W. Action: Keyboard DownArrow". And it works. Pressing W goes down in the text.

I try the same in Xee3 (a photo viewer app), but nothing happens. I wonder if this is due to a bug in Xee or in the way BTT emulates the "fake keyboard arrow events"?

Perhaps Xee is doing some kinda "very raw keyboard reading" so that BTT events don't work in it... I would not be surprised if it does some kinda raw old API for direct keyboard access, because Xee is able to do remap of practically any command/key and take over even from system commands. So Xee may be more like a videogame, doing direct keyboard "stealing" of input so that BTT never has a chance to affect it. I dunno...

I did however try this: Map W to "R" (rotate in Xee3) and that worked. So whatever is wrong, it seems to only affect BTT's attempts to emulate arrow keys.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Keyboard

#### Device information:

Type of Mac: MBP 2010
macOS version: 10.12
BetterTouchTool version: 2.365 (749)

**Comment by fifafu** [comment]
It seems to work fine here, but maye try enabling compatibility mode for Xee (but please update to BTT 2.366 alpha via "check for alpha version updates" before doing so, because I just fixed an issue with compatibility mode)

![image](https://user-images.githubusercontent.com/8820811/37256892-3d0e3136-2561-11e8-89d6-fb523b2d3400.png)

**Comment by aitte2** [comment]
Hi Andreas! Thanks for your fast reply. I felt bad for making this ticket when I saw that you have 1000 tickets. Yikes. I hope you're feeling okay. :-)

Okay so I updated BTT to 2.66 alpha, created a brand new BTT profile to avoid conflicts. Clicked "Add new: Running apps: Xee3". Then set a shortcut under the Keyboard (I also tried Trackpad) as `Shortcut: W` and `Trigger Other Keyboard Shortcut: <downarrow inserted by pressing downarrow in the field>`. I tried compatibility mode on and off.

It doesn't work. But I think this may be something on my system conflicting with BTT, because I pressed "W" a ton of times and saw it ONCE scroll down a bit... so it's possible that something on my system is interfering with arrow key emulation.

Since it works for you, I will drop this ticket. Let's close it.

**Comment by fifafu** [comment]
Nah if it doesn't work we can leave it open. Maybe somebody else encounters the same issue and may have other insights!


Many of the issues here are just feature requests or questions, so no need to worry ;-)

**Comment by fifafu** [comment]
And I think depending on what you need to trigger you may need to use fn+arrow down/up instead of just a raw arrow.

**Comment by aitte2** [comment]
@fifafu Thanks for the tips! What I was trying to trigger is the "panning" feature when Xee3 is zoomed in. To pan around the image. I wanted to rebind it all so that I don't have to use the tiny MacBook arrow keys. Which is why I tried to make WASD move up/down/left/right.

Anyway, you're right... someone else may have this issue and provide insight here. I guess it can remain open. :-) For now I'll forget the idea since it seems impossible. I can live with the regular arrow keys. So the only reason to keep this ticket open is to help others in the future. Anyway thank you and take care! :)

**Comment by fifafu** [comment]
It's possible that this works now with the latest version, but I haven't tested.

**Comment by aitte2** [comment]
@fifafu Ok I upgraded to alpha 2.422 (779) now. I tried binding "C" to "down arrow" and with/without compatibility mode. Like last time, it does "something". A few blips of moving down _sometimes_. But it's not reliable.

I think it's Xee's fault. So don't worry about it. :) Because I can use BTT to rebind downarrow in TextEdit and it works fine there.
