### ISSUE TITLE
Using BTT with Inqscribe

### ISSUE THREAD

**Issue by AlexPassmore** [folivoraAI/BetterTouchTool#2208]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

Has anyone tried using this app with Inqscribe? https://www.inqscribe.com

This app allows transcription / notation of audio and video files, and one can set up shortcut keys to execute various functions.  It doesn't natively support the touch bar, and BTT seems like the perfect solution, however it doesn't seem to work.

It will send plain text characters, and they will appear in the text window, but it doesn't seem to trigger any shortcuts.  Very occasionally it seems that a trigger will work, but this really is very rare, and will be an isolated event.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Touch Bar

#### Device information:

Type of Mac: MacBook Pro 15" 2017
macOS version: High Sierra
BetterTouchTool version: Lastest plus 2.340

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
It seems to work fine on my machine, but I'm currently on the latest BTT alpha.
Could you try whether that changes anything? (check for alpha version updates)

**Comment by AlexPassmore** [comment]
Im testing with 2.365 - is that the same as you are testing on?

**Comment by fifafu** [comment]
yes

**Comment by fifafu** [comment]
could you show me an example trigger you set up for Inqscribe?

**Comment by AlexPassmore** [comment]
in BTT?

Here:

As you can see I have tried a couple of options.


<img width="1015" alt="inqsribe triger" src="https://user-images.githubusercontent.com/37269971/37256927-63afd4aa-2559-11e8-83d7-bc687303da88.png">

**Comment by fifafu** [comment]
Ah now I see - I missed the shortcuts configuration in the Inqscribe settings.

It looks like Inqscribe is directly accessing the hardware properties for whatever reason - BTT can't emulate that unfortunately.

Also the usual Apple Script workaround (tell application "System Events" to keystroke "p" using option down) doesn't work for InqScribe. 

I think you'll need to ask them whether there is any way to trigger these shortcuts using software.

**Comment by AlexPassmore** [comment]
Ah I see

Thanks for looking into it.

I'll get in touch with them, although there has been so little development in the last few years ~I don't hold much hope.

Anyway, thanks again
