### ISSUE TITLE
Double click occurring in remote desktop with 3-Finger tap as middle mouse click

### ISSUE THREAD

**Issue by rwardnavex** [folivoraAI/BetterTouchTool#2219]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Working in a virtual machine with Windows 10 with remote desktop for Mac, I'm now experiencing 2 clicks for one 3-finger tap on the trackpad. This just started happening after the update to 2.4 today. It is independent of browser used. 

3-finger tap is configured as middle mouse click with no additional action.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Magic Trackpad

#### Device information:

Type of Mac: MacBook Pro 15" w/ Touch Bar 
macOS version: 10.13.3
BetterTouchTool version: 2.4 (updated from 2.34?? today)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
There hasn't been a change to the middle click action (and it seems to work fine here). Are you sure this is related to the new update?

You can however downgrade easily via https://bettertouchtool.net/releases/btt2.340.zip

**Comment by aaronryden** [comment]
started happening to me as well. Toggling disable for all apps seems to fix it for a few hours.
