### ISSUE TITLE
Shortcuts assigned to Num Pad keys don't work after 2.4 update

### ISSUE THREAD

**Issue by Alex7Sher** [folivoraAI/BetterTouchTool#2220]
#### Description of bug/feature request/question:
Shortcuts assigned to Num Pad keys don't work after 2.4 update. I have a bunch of shortcuts assigned to numpad keys (Pad 1-9, Pad 0, Pad - , Pad +). Before the update I think I had version BetterTouchTool 2.332 and the shortcuts worked. Now if I open notepad for example and try to use the shortcuts like before, it just types a number. Before this no numbers were typed from using the numpad keys assigned to BetterTouchTool shortcuts.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Keyboard

#### Device information:

Type of Mac: mac mini (late 2012) 2.3GHz Intel Core i7
macOS version: 10.13.3
BetterTouchTool version: 2.401

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

**Comment by fifafu** [comment]
There is an issue on some few Macs that couldn't be identified yet (it seems to be a macOS issue) which causes the new shortcut system to fail on these machines.

In that case you can enable the old shortcut system in the advanced preferences.

![image](https://user-images.githubusercontent.com/8820811/37295435-78d01664-2618-11e8-8846-4a24478626f9.png)

**Comment by Alex7Sher** [comment]
Thank you for such a quick response! I really appreciate it. Didn't know about that setting. Seems like it made my (num pad) shortcuts work again. Thank you fro your help!
