### ISSUE TITLE
tabs viewer

### ISSUE THREAD

**Issue by mdelapenam** [folivoraAI/BetterTouchTool#2224]
#### Description of bug/feature request/question:

hi, mi name is michael and I'm new using BTT.
i have a macbook touch bar and menawhile i was searching apps for the touch bar i found your app. 
i was searching an option for tabs viewer like safari but added to others apps like office word, mozilla, etc.
can i do this confignuration to mi PC? thanks.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

touch bar configuration

#### Device information:

Type of Mac: Macbook pro touch bar 3.5GHz Intel Core i7
macOS version: macOS Sierra
BetterTouchTool version: 2.402

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

<img width="605" alt="captura de pantalla 2018-03-12 a la s 15 42 33" src="https://user-images.githubusercontent.com/37311737/37309176-1cb7b558-260e-11e8-8e29-580c0a011243.png">
---

**Comment by fifafu** [comment]
Sorry this is not possible. 

Maybe in the future I can add a "window switcher" widget, but currently something like that is not available.

**Comment by fifafu** [comment]
This would definitely be better done with native code. Problem is taking screenshots of tabs as that's probably not something most browsers would support.
