### ISSUE TITLE
Feature Request: Touch Bar button group triggers shortcut on open

### ISSUE THREAD

**Issue by daniellund14** [folivoraAI/BetterTouchTool#2225]
#### Description feature request:
I think it would be a great feature to add the ability to trigger a shortcut on a touch bar folder button, which then opens the sub items. The setup would be something like a debug button that triggers the debug command, and then opens a subfolder with debug actions such as step over, step in, etc.

**Comment by fifafu** [comment]
Yes good idea.

For now you can use a hacky workaround to achieve this:

- Create a new group and name it something (e.g. test-group)
- Set the background to black
- Set the padding to a negative value to basically make the group invisible
- Create a new Touch Bar button and assign the action "Open Touch Bar Group With Name"
- Attach an additional action to that button - this can e.g. be a shortcut
![image](https://user-images.githubusercontent.com/8820811/37310891-b7acb1da-2645-11e8-810e-df6486d5983f.png)
![image](https://user-images.githubusercontent.com/8820811/37310894-bbc11180-2645-11e8-8d0f-2a9331f35a9c.png)

**Comment by daniellund14** [comment]
@fifafu thanks for the workaround, would definitely love to see the main folder have the ability to trigger an action, but a good workaround for now. Thanks!
