### ISSUE TITLE
Window snapping to a wrong side of the screen

### ISSUE THREAD

**Issue by Hl2run** [folivoraAI/BetterTouchTool#2234]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
When I drag a window to snap to one side of the screen it snaps to the other side. It has been happening for couple months now.

Restaring BTT does fix the issue.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Moving the window with keyboard shortcuts and moving with a mouse.

#### Device information:

Type of Mac: MBPr 15" 2013, iMac 2011
macOS version:  10.13.3, 10.12.6
BetterTouchTool version: All for the last couple months.

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

![1](https://user-images.githubusercontent.com/426875/37349478-d143f5e0-26d6-11e8-901a-03872363f88c.gif)

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
has anything changed or is there anything special about your display config?
I don't think I have had similar reports for neither BST nor BTT so far :-/

**Comment by Hl2run** [comment]
It happens with my iMac and MBPr. I use both with external monitors, but it happens with no extra screens connected as well.

With my MBPr I have 27" Dell U2717D and some random 19" DVI screen. Connected thru DP and HDMI. Running the MBPr in clamshell mode.

At home 27" iMac 2011 with the same 27" Dell U2717D and some random 19" DVI screen.

It has been like this for quite a long time, only now I forced myself to report it :)

**Comment by Hl2run** [comment]
BTW, I am not runing any other "special" utilities that could interfere.

**Comment by Hl2run** [comment]
I never used any snap areas.

I have multiple keyboard and trackpad shortcuts and gestures setup. Nothing CRAZY advanced.

I rarely add new shortcuts and stuff, so I setup them manually on both Macs.

I mean, I can live with it if it is too strange to fix.

**Comment by fifafu** [comment]
It would be great if you'd go to the about tab in BTT and click the "export debug info" button. This will create a folder BetterTouchToolDebug on your Desktop. Maybe I can reproduce this if you send that to boastr.net@gmail.com :-)

**Comment by Hl2run** [comment]
You've got mail!

**Comment by fifafu** [comment]
Unfortunately even with your setup I can't seem to reproduce it :-(
Does this happen on all your monitors?

What kind of mouse are you using?

**Comment by Hl2run** [comment]
I use Logitech MX Revolution mice with both computers, however, It happens with keyboard shortcuts setup for moving the windows as well.

And there is one more thing :) I don't have it on video, but what it does is totally strange.

I have a frontmost active window. I press the keyboard shortcut to snap it to a side of a screen BUT it does nothing, BUT the window beneath this active window snaps to the side of the screen and the active one does not move at all :D 

I know, it sounds crazy, but it really happens. Don't sweat over it, I can live with it. Thanks for all the time you put into it, it is THE BEST APP for my Mac.

**Comment by fifafu** [comment]
Mhh that sounds like something is interfering with BTT which causes BTT to grab the wrong window  :-/ but I'm not sure yet.

Do you maybe have dragon Dictate installed? (It's known to break window snapping apps)

I'll create a debug version that logs some specific things tomorrow. Would be great if you could try running that :-)
Then we'll see whether BTT at least thinks it's doing the right resizing, or if it makes done wrong assumptions for some reason.

**Comment by Hl2run** [comment]
OMG, you are amazing.

I do not have Dragon Dictate installed.
