### ISSUE TITLE
Immediately after waking from sleep, maximize window left/right goes to 1/4 screen width rather than 1/2

### ISSUE THREAD

**Issue by NevinBR** [folivoraAI/BetterTouchTool#2235]
#### Description of bug/feature request/question:

I have BTT shortcuts for maximize window left/right, which make things fill half of the screen on one side or the other.

However, in the first couple seconds after waking my Mac from sleep, those same shortcuts will resize windows to fill only one quarter of the screen horizontally. The window still goes all the way from top to bottom, and it moves to the correct edge of the screen, but its width becomes only half of what it should, namely a quarter of the screen width.

This is 100% consistent, occurring every time I try to maximize a window to half the screen immediately after waking the computer from sleep. I believe this has been happening for a long time (ie. many versions of BTT) so it probably isn’t a recent change.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

MacBook Pro with retina display, both keyboard and trackpad shortcuts

#### Device information:

Type of Mac: 2013 Retina MacBook Pro 15.4″
macOS version: 10.12.6
BetterTouchTool version: 2.400

**Comment by fifafu** [comment]
I think this may not be solvable but I'll try to reproduce it.
The necessary system APIs sometimes seem to take a bit until they give BTT the correct values :-/
