### ISSUE TITLE
move window to secondary screen "above" primary screen doesn't work reliably.

### ISSUE THREAD

**Issue by tkiehl** [folivoraAI/BetterTouchTool#2237]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

When the secondary screen is arranged above the primary screen then one cannot use bettertouch's move window functionality to move a window up, from the primary screen to the secondary screen. The effect is a little erratic, sometimes it will work when the selected window is in the background, but not usually and rarely when the window of interest already has focus.

What does work: Moving a window from the secondary screen "down" to the primary.

***After more fiddling around to better diagnose this, it seems this is connected to the speed at which the window is dragged. Dragging quickly to the secondary screen works, going slowly doesn't work, with the window just getting stuck at the top of the primary screen.***

FYI, this issue presents itself when window snapping in bettertouchtool is disabled.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

MacBook Pro Trackpad

#### Device information:

Type of Mac: MacBook Pro 15" 2017
macOS version: 10.13.3 (have seen it on early versions too)
BetterTouchTool version: 2.403 (754) and some earlier.

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

I guess the workaround is to always drag your windows **FAST!**

---

**Comment by mesqueeb** [comment]
I have the same problem!
It works with dragging the window **FAST**! : D

Thanks for your great program though!

**Comment by fifafu** [comment]
This is probably caused by the "delay mission control" option in the advanced window snapping options.

Could you try to disable that?

**Comment by tkiehl** [comment]
I have window snapping disabled entirely. Should I enable it and select
that option?

---
Thomas R. Kiehl, Ph.D.
  Principal Investigator
  Neural Stem Cell Institute
  One Discovery Drive
  Rensselaer NY 12144, USA

  Clinical Assistant Professor
  Computer Science Department
  College of Engineering and Applied Science
  University at Albany
  Albany NY 12222, USA

  e: tomkiehl@neuralsci.org
  p: 518.694.8188
  f: 518.694.8187

On Fri, Mar 30, 2018 at 8:14 AM, Andreas Hegenberg <notifications@github.com

**Comment by fifafu** [comment]
Maybe try that. It could be that I forgot to disable  the functionality in the case window snapping has been disabled.

**Comment by tkiehl** [comment]
Nope, that doesn't seem to change anything.
