### ISSUE TITLE
"Context Menu" key mapping on atached USB keyboard no longer working after 2.4 update

### ISSUE THREAD

**Issue by grumpy123** [folivoraAI/BetterTouchTool#2239]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
After 2.4 update mapping of "Context Menu" key on Logitech K120 keyboard is no longer working.
Reverting to the old engine (via Advanced Settings) doesn't help.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
USB-connected keyboard Logitech K120.

#### Device information:

Type of Mac: MacBook Pro 2017
macOS version: latest
BetterTouchTool version: 2.4003

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
Used to work with the previous version.

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by Sinetempore** [comment]
Same issue here, Context Menu shortcuts do not work as before... it works if you repeat twice the shortcut.
