### ISSUE TITLE
Keystrokes captured by BetterTouchTool instead of task switcher

### ISSUE THREAD

**Issue by tsanikgr** [folivoraAI/BetterTouchTool#2241]
#### Description of bug/feature request/question:

After updating to 2.402, the following behavior was changed:
BetterTouchTool is capturing keyboard events, even when the task switcher is open, whereas in previous versions it was letting them propagate to the task switcher. Thus, I was able to press  `⌘ + TAB`, let go of `TAB` (while holding the  `⌘` button down), and then was able to switch between apps using the `←` and `→ ` buttons.

I have the keyboard shortcuts `⌘ + ←` and `⌘ + → ` mapped to snapping my windows at the left and right half of the screen respectively, so now when I let go of the `TAB` button, and press the arrows, the top-most window behind the task switcher snaps right or left.

Is it possible to somehow make the task switcher capture the keyboard events before better touch tools handles them (i.e. revert to the behavior prior to v2.4)?

Thanks in advance,
Nikos

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Keyboard

#### Device information:

Type of Mac: MacBook Pro touch bar
macOS version: 10.12.6
BetterTouchTool version: 2.402

**Comment by fifafu** [comment]
Unfortunately I currently don't think this is possible using the new shortcut system.
You can however enable the old implementation in the advanced preferences. However you'll loose the new functionalities that are possible with the new system.

![image](https://user-images.githubusercontent.com/8820811/37372716-12075e68-2714-11e8-97cb-0720ae0f16f1.png)

I'll check if I can somehow make this work in future versions

**Comment by tsanikgr** [comment]
Thanks a lot for the quick reply. Where can I find a list of the new functionalities that are possible with the new system?

Thanks

**Comment by fifafu** [comment]
https://updates.bettertouchtool.net/bettertouchtool_release_notes.html :-)

**Comment by tsanikgr** [comment]
Awesome thanks a lot!
Best OSx app hands down! 👏
