### ISSUE TITLE
Four finger gesture triggers hotkey and dismisses

### ISSUE THREAD

**Issue by nikitavoloboev** [folivoraAI/BetterTouchTool#2246]
#### Description of bug/feature request/question:

I have a hotkey in BetterTouchTool gesture that shows Bartender with a hotkey. The bartender is activated with `⌥⇧⌘W`. Here is the binding:

![2018-03-14 at 10 44](https://user-images.githubusercontent.com/6391776/37394726-bb366424-2774-11e8-8a72-3c5278112cc6.png)

And here is the hotkey defined in Bartender:
![2018-03-14 at 10 46](https://user-images.githubusercontent.com/6391776/37394789-e77a3fba-2774-11e8-9236-19339e58d4aa.png)

If I just activate the hotkey myself, the bartender bar shows. I press the hotkey again and it goes away.

With that gesture however for some reason, I click with four fingers (and keep pressing) and it shows. But as soon as I release my fingers it immediately disappears as if pressing the `⌥⇧⌘W` again.

The issue didn't exist a month or week ago as I have been using this gesture with same hotkey for a long time and it worked like I wanted. I four finger click once, bartender menu shows. I four finger click again, it goes away.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Trackpad

#### Device information:

Type of Mac:
macOS version: 10.11.6
BetterTouchTool version: 2.403

**Comment by fifafu** [comment]
I can't seem to reproduce this :-( However I also don't have access to a 10.11.6 machine.

You could try to activate the hud for the gesture to see if it gets triggered twice for some reason:
![image](https://user-images.githubusercontent.com/8820811/37400319-dcfa2ce8-2784-11e8-928d-e9aa53656405.png)

**Comment by nikitavoloboev** [comment]
How do I activate this HUD, I can't find a way 😞

**Comment by fifafu** [comment]
![image](https://user-images.githubusercontent.com/8820811/37401324-fda30886-2787-11e8-92cc-aeafea1b843b.png)

**Comment by nikitavoloboev** [comment]
Everything seems fine there. Also the gesture works fine when I activate whilst BTT is active and at front. But does the wrong thing with dismissing when outside of BTT.
