### ISSUE TITLE
Remap Keys for Remote Desktop Connections to Windows

### ISSUE THREAD

**Issue by msi-matthew** [folivoraAI/BetterTouchTool#2248]
#### Description of feature request:

Would like to remap command and control keys

cmd --> ctrl
ctrl   --> cmd

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Keyboard

#### Device information:

Type of Mac: Macbook
macOS version: High Sierra
BetterTouchTool version: 2.403

**Comment by yaseent** [comment]
The only thing I can think of is that you will need to install a key-remapper on the windows machine.
