### ISSUE TITLE
square bracket EU keyboard

### ISSUE THREAD

**Issue by valossy** [folivoraAI/BetterTouchTool#2251]
#### Description of bug/feature request/question:

Hello, have a bug with a specific app. I don't know if it can help other but I'll put here.
I want to create square bracket for an app called Pyzo and these shortcut are not working. It write { instead of [ 99% of the time (screen). I tried with safari and it work perfectly fine. Custom touch bar for pyzo don't work too. I was wondering if this bug affect only this app or other are concerned too.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Touch Bar

#### Device information:

Type of Mac: MacBook Pro 13" with Touch Bar
macOS version: 10.13.3
BetterTouchTool version: 2.403

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

<img width="272" alt="image messages 3548400906" src="https://user-images.githubusercontent.com/37267717/37462623-eb627e88-2852-11e8-8abe-0059b7b8540e.png">

**Comment by fifafu** [comment]
what shortcut do you need to send to create a square bracket? ( I have a germany keboard here it is opt+5 )

**Comment by valossy** [comment]
for [ it's option+shift+( and ] it's option+shift+)

**Comment by fifafu** [comment]
Maybe try v2.407 alpha, I slightly changed how modifier keys are being sent.
Otherwise maybe try to use the "paste/type text" action instead (and select type instead of paste)

**Comment by valossy** [comment]
mhhh it don't work either. (line 1)
I tried as you said with "type" and it send q instead. (line 3)
"paste" seems to work but it is kind of slow. It is probably fast enough for me. Maybe the app don't really like shortcut like that. (line 5) 
<img width="208" alt="image messages 645388445" src="https://user-images.githubusercontent.com/37267717/37534682-c7877844-2945-11e8-97db-d6bbec88be21.png">
