### ISSUE TITLE
Double click on the window titlebar to maximize window acting strangely

### ISSUE THREAD

**Issue by Clifford-Yen** [folivoraAI/BetterTouchTool#2252]
#### Description of bug/feature request/question:
I have set a trigger to maximize window when double clicking on the window titlebar for a long time. But after update to version 2.405, take Chrome as the example, would maximize and fill the entire desktop, then flash back to the original position immediately.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
MacBook Trackpad. I didn't try other devices.

#### Device information:

Type of Mac: MacBook Pro 13" 2014 mid (MacBookPro11,1)
macOS version: 10.11.6
BetterTouchTool version: 2.405

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
For your information, I take two screenshots below.

This is the window BEFORE double clicking.
![screen shot 2018-03-15 at 19 45 53 2](https://user-images.githubusercontent.com/6063670/37462017-6b401ee8-288b-11e8-8891-56e031557236.jpg)

Then AFTER double clicking, the window size has changed, but the position flashes back immediately to the original position.
![screen shot 2018-03-15 at 19 46 08 2](https://user-images.githubusercontent.com/6063670/37462136-ccd65438-288b-11e8-8b93-eec78474455b.jpg)

It's worth to note that this issue does NOT happen for all applications. Applications like Vienna, Wunderlist all working correctly. But please forgive me have suffered from this issue enough, so I have rolled back to previous regular update (2.340, which works perfectly) without trying other applications.

I can confirm this issue once happened, but I cannot tell which version in the past. Hope this help. I would stay with the previous version temporarily.

**Comment by yaseent** [comment]
Try disabling (unchecking) this (curcled in Red)
![screen shot 2018-03-15 at 14 36 29](https://user-images.githubusercontent.com/21298730/37463678-ad8d3178-285e-11e8-9aba-3bdc32934786.png)

**Comment by Clifford-Yen** [comment]
Yes, I have tried to uncheck it with no luck.

**Comment by whirka** [comment]
I am encountering the same issue. Especially with chrome. Most other applications are maximizing correctly when I double click on the title bar.

**Comment by jerryctt** [comment]
I have same issue as well.

**Comment by jerryctt** [comment]
I meet this issue again in 2.442(803) and this issue is only for chrome window. Double click only resize the chrome window but doesn't move the window to top-left corner.

macOS version: 10.12.6
Chrome version: 66.0.3359.117
BetterTouchTool: 2.442 (803)

This issue is same to issue https://github.com/fifafu/BetterTouchTool/issues/2337, but closed.

**Comment by fifafu** [comment]
Weird, I think it may be related to the new chrome which was released today. (66). I'll check it.
