### ISSUE TITLE
Feature request: CPU usage/history widget

### ISSUE THREAD

**Issue by lodeth** [folivoraAI/BetterTouchTool#2254]
#### Description of feature request:
CPU usage/history widgets for Touch Bar would be nice.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Touch Bar

**Comment by OrbitalTech** [comment]
Just make a Widget using "Run Applescript and Show Return Value".

Paste this code:

`set usedCPU to (do shell script "top -l 2 -F -R | awk '/CPU usage/ && NR>5 {printf \"%d\", $7+0}'") as integer
set returnVal to usedCPU & "%" as string
return returnVal`

I recommend setting it to update every second.

To explain, we are using applescript to call a shell script. We are then parsing the shell script to get the number we want. Then we return it with a % icon.

**Comment by fifafu** [comment]
@OrbitalTech I think using the shell script widget like this would be more performant:

![image](https://user-images.githubusercontent.com/8820811/37622028-e75ff204-2bc0-11e8-99ae-96b4e9668f63.png)

ps -A -o %cpu | awk '{s+=$1} END {print s "%"}'

**Comment by OrbitalTech** [comment]
Due to the extreme variance of cpu usage at any given time, that returns values like 70% when actual usage is more in the realms of 20%.

Parsing the first two percentages from this would be better (System & User. Third is IDLE).
`top -l 2 -F -R | awk '/CPU usage/ && NR>5 '; printf $5}`
I'm not great with parsing text outside of java, so someone else will have to do this.

**Comment by fifafu** [comment]
iostat seems to be faster than top and also gives user and system cpu:

```
user_cpu=`iostat | tail -n1 | awk '{print $4}'`
system_cpu=`iostat | tail -n1 | awk '{print $5}'`
total_cpu=`expr $user_cpu + $system_cpu`
echo $total_cpu'%'
```

**Comment by fifafu** [comment]
mh or does this do something different?

**Comment by OrbitalTech** [comment]
Alright, I've had a little play and this seems to be getting me the numbers I want. Not necessarily the best way to go about it, but it works for me.

`totalString=`top -l 2 -F -R | awk '/CPU usage/ && NR>5 '; printf $5}`
N=3

usr=`echo $totalString | cut -d ' ' -f3 | cut -c1-4`
sys=`echo $totalString | cut -d ' ' -f5 | cut -c1-4`

totalUsage=`echo $usr + $sys | bc`

echo $totalUsage%
`

**Comment by oliviermattelaer** [comment]
I would propose the following script: 
total_cpu=`iostat -c2 | tail -n1 | awk '{print $4+$5}'`
echo $total_cpu%

This script runs for a total of  1 second but does not actually use any cpu (and seems quite accurate)

**Comment by OrbitalTech** [comment]
That script gives me "%" with no percentage attached. I'm not quite sure what I'm doing wrong to be honest. This seems very similar to what Fifafu proposed, which turned out to be something different altogether.

**Comment by oliviermattelaer** [comment]
Looks like some formatting issue with the insert command block in my previous comment.
This should fix it:
```
total_cpu=`iostat -c2 | tail -n1 | awk '{print $4+$5}'`
echo $total_cpu%
```

The inspiration come from Fifafu (obviously) but the -c2 provides the result average on 1 second. (This is why that script runs for 1 second).

**Comment by OrbitalTech** [comment]
Looks like it is only returning the value of user usage rather than the total. Thats based on a quick comparison with activity monitor. Its in the right range though, so I might be wrong.

**Comment by oliviermattelaer** [comment]
I have checked and it really returns the sum of those two. The numbers are not in exact agreement with activity monitor indeed but this might be due to the way those numbers are evaluated in each case.
 
Actually, I face an issue when I plugged an external hard drive. To avoid such issue I change the script to:
```
total_cpu=`iostat -c2 -d -C -n0 | tail -n1 | awk '{print $0+$1}'`
echo $total_cpu%
```
