### ISSUE TITLE
Please make "Prevent recursive triggers" default to true

### ISSUE THREAD

**Issue by arkban** [folivoraAI/BetterTouchTool#2265]
#### Description of bug/feature request/question:

Please make "Prevent recursive triggers" default to true. Or an option to change the default.

#### Device information:

Type of Mac: MacBook Pro (Retina, 15-inch, Mid 2015)
macOS version: 10.13.3 (17D102)
BetterTouchTool version: 2.405

**Comment by fifafu** [comment]
This issue was moved to https://community.folivora.ai/t/please-make-prevent-recursive-triggers-default-to-true/38

**Comment by fifafu** [comment]
Sorry, please ignore the previous message. The migration didn't work correctly, for now the issues will stay here.
