### ISSUE TITLE
Disabling app-specific shortcut also disables global shortcut with same trigger while in that app

### ISSUE THREAD

**Issue by NevinBR** [folivoraAI/BetterTouchTool#2276]
#### Description of bug/feature request/question:

When a global shortcut and an app-specific shortcut both have the same trigger, disabling the app-specific shortcut \*also\* disables the global shortcut while in that app. Simple example:

Global shortcut: change ⌘I to ⌘O
Finder-specific shortcut: change ⌘I to ⌘K

Unchecking the “enabled” box for the Finder-specific shortcut causes ⌘I to have its normal behavior in Finder (show Get Info window), and not trigger the global shortcut.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

MacBook Pro keyboard

#### Device information:

Type of Mac: 2013 Retina MacBook Pro 15.4″
macOS version: 10.12.6
BetterTouchTool version: 2.411

**Comment by NevinBR** [comment]
>This is actually intended to be like this. I know it may be a little confusing but changing this would break many setups.

For that use-case (disabling a global shortcut in a specific app) wouldn’t it make more sense to introduce a “Pass through” action that means, “BTT ignores this input, process it normally”?

Then the “enabled” checkbox could do what it says.

**Comment by fifafu** [comment]
Yes that already exists (do nothing or use apple default)

However it has been like this for almost 8 years and people are using both methods to achieve this.

Changing it would break too many setups at this point.

**Comment by NevinBR** [comment]
> Yes that already exists (do nothing or use apple default)

Oh, right! So, with that use-case easily achieved, why not have the “enabled” checkbox do what it says?

> Changing it would break too many setups at this point.

I do not find this convincing. If disabling one shortcut \*also\* disables another (that doesn’t even appear on the same screen), that strikes me as an obvious bug.

Besides, as you pointed out, we already have one very clear way to say “In this app, this shortcut should use its default action” — namely with an app-specific shortcut set to “Use Apple Default Or Do Nothing”.

We do \*not\* currently have a clear way to say “I have this shortcut, and I want to try going without it to see what that’s like.”

In most circumstances, that is what unchecking the “enabled” box does. However, when both a global and an app-specific shortcut use the same gesture, there is no way to disable just the app-specific shortcut.

Duplicating the profile and deleting the shortcut is a workaround, but when there are several shortcuts that you want to try switching on and off independently, it is no longer viable.

**Comment by fifafu** [comment]
Sorry, I know that it's not very nice  but I don't want to answer all the emails about users whose presets don't work anymore as they used to.
This is such an edge case, I'll be able to spend that time on more useful things.

The enabled checkbox had its origins in allowing users to disable a  shortcut for a specific app, allowing to disable global shortcuts was a nice side effect. 

However I'll add it to the documentation and will keep it in mind for the big Ui update I have planned.

**Comment by NevinBR** [comment]
Okay, thanks.
