### ISSUE TITLE
Anyones pinch to zoom feature stop working often?

### ISSUE THREAD

**Issue by dancinbananas** [folivoraAI/BetterTouchTool#2284]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Device information: 

Type of Mac: 2016 Macbook Pro TB 2.9ghz
macOS version: 10.13.3
BetterTouchTool version: 2.407

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by drs-nyc** [comment]
Yes, I've seen the same issues for a while. I also will turn it on and off multiple times until it allows the standard zoom pinch features to work on apps like Photoshop and Safari.
