### ISSUE TITLE
TipTap Right/Left leaves Ctrl stuck

### ISSUE THREAD

**Issue by CraigMcK** [folivoraAI/BetterTouchTool#2286]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

I currently only use TipTap Right & Left to change between windows in Royal TSX, but since the latest update this is leaving Ctrl stuck, which causes issues interacting with remote desktops.  I can switch manually between windows and no issue, only when using TipTap does this present

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

MacBook Pro Trackpad

#### Device information:

Type of Mac: Pro 2016 Touchbar
macOS version: High Sierra
BetterTouchTool version: 2.405

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
How have you configured your shortcuts for Royal TSX? In recent versions they should be configured like any other shortcuts without the previously necessary workarounds.

Try updating to the latest alpha of BTT, there have been some fixes in regards to remote desktop apps.

**Comment by CraigMcK** [comment]
Hiya, I have them set as Ctrl Tab and Shift Ctrl Tab keyboard shortcuts
    On Tuesday, 20 March 2018, 11:52:27 GMT, Andreas Hegenberg <notifications@github.com> wrote:  
 
 
How have you configured your shortcuts for Royal TSX? In recent versions they should be configured like any other shortcuts without the previously necessary workarounds.

Try updating to the latest alpha of BTT, there have been some fixes in regards to remote desktop apps.

**Comment by fifafu** [comment]
I can't seem to reproduce this here :-(

If possible go to the about tab in BTT and click the "export debug information" button. This will create a folder called BetterTouchToolDebug on your Desktop. Would be great if you could send that to boastr.net@gmail.com and reference this issue then I'll look into it.
