### ISSUE TITLE
Feature request: global config for snap area drop targets colours & alignment

### ISSUE THREAD

**Issue by samsalisbury** [folivoraAI/BetterTouchTool#2295]
I would like to not have to individually move and style snap areas, as this takes time and it's hard to get them all aligned exactly. If possible, I would prefer a single global setting to have the drop targets mimic the shape of the area they represent, and a single setting for colours.

Ideally, drop targets would default to occupying the centre of the snap area they represent, and would mimic that snap area's dimensions on a smaller scale. (e.g. "snap area is 10% of the height/width of the represented area")

#### Device information:

Type of Mac: 2016 MacBook Pro
macOS version: 10.13.3
BetterTouchTool version: 2.417

**Comment by samsalisbury** [comment]
@fifafu was this closed intentionally? If so, are you able to say why this isn't being considered?

**Comment by fifafu** [comment]
The BTT issue tracker has moved to https://community.folivora.ai early this year and all issues here have been auto-closed now. In case you still need help with this issue / feature / question please create a new post there.
