### ISSUE TITLE
Logitech Trackball MX Ergo...BTT Workaround??

### ISSUE THREAD

**Issue by johnnyyukon** [folivoraAI/BetterTouchTool#2302]
Just got MX Ergo (Type of Mac: Mini,   macOS version: 10.13.3  BetterTouchTool version: 2.405)        
which uses "Logitech Options" to map buttons and whatnot.

I switched from the Logitech M570 for, possibly, boring reasons in the below paragraph.

So I got kind of sick of constantly returning and replacing the Logitech m570.  I've owned about 10 (that includes free replacements) and after about 4-6 months, without fail, the ball or 3 little bearings or SOMETHING causes them to be way less smooth. Not super bad, but enough to effect the work I do-precision oriented stuff.

**PROBLEM:**   unlike the m570, BTT does not recognize the "forward" and "backward" buttons.
I use these buttons with BTT like a madman.  Depending on the app, for example, "forward" is programed for 3 things usually, for the 3 places you can click:  Dock, Menu Bar, and big ol space in between (desktop basically).

Very cool very helpful.  

But while BTT recognizes virtually every other button on the ERGO (scroll up down left right, etc.) not my 2 precious "forward" "backward" buttons.

They CAN be programmed with Logitech Options, but obviously inferior to BTT, not for Menubar clicks or Dock clicks.

I've tried a variety of things like using Logitech Options to program forward button to some random keystroke combo, but you can't enter that in BTT in mouse devices, you have to click a button.

I saw Andreas Hegenberg (@fifafu wie geht's, Alter?) post for workarounds for the MX Ergo's predecessor, MX Master (I think).  And looks like I may be out of luck for now, as the workarounds are limited.

Anyway, maybe there's a solution, maybe not, maybe in the future.  Just thought I'd post cuz I think the MX Ergo is relatively new and haven't found any posts/issues about it.

Peace out.
Johnny

**Comment by johnnyyukon** [comment]
anything?

**Comment by fifafu** [comment]
Have a look here: http://docs.bettertouchtool.net/docs/normal_mice_problems.html

**Comment by johnnyyukon** [comment]
yesssir, that was the "post" I had referred to that I saw, and tried a few things.  And again tried a few things last night.  But alas, seems the only buttons that work are left/right click, and middle click.

Or more specifically, BTT at least recognizes scroll left/right (tilt on wheel)  but can't seem to program those with BTT.  forward and back buttons not recognized at all.  MIddle click IS recognized and I can program it with BTT just like good old times.

Again, as your article mentions, I can program scroll left/right back forward using Logitech Options and either A.  just using it without BTT, or B. Map arbitrary keyboard stroke then using KEYBOARD devices to map to some action.  

But Keyboard section does not allow for "keystroke in menu/dock"  but also only played with for 2 hours.   May give another go later and report back with mroe specifics cuz there were some things that worked some that didn't.

I also haven't tried uninstalling Logitech Options, but not sure that would do anything.  Could be worth a try.

Thansk for response.

**Comment by yongar** [comment]
I also have new Ergo and I mapped the back and forward to a specific keys.
Something weird that I do not use often, yet.. 

I went to Keyboard and use the shortcut to do some actions. Attached screenshot is for Chrome.
Back is assigned in Logitech 
I use that key for something else on other application, you get the idea.

![2018-04-20_21-37-56](https://user-images.githubusercontent.com/2595314/39080425-2002d6cc-44e3-11e8-9567-935f44b2c34e.png)

![2018-04-20_21-34-32](https://user-images.githubusercontent.com/2595314/39080412-d3f5e21a-44e2-11e8-86de-2c20c4a6f391.png)

**Comment by johnnyyukon** [comment]
@yongar hey, yeah that's essentially what I've done but the BIG point is that, while you can make shortcuts like that for every app, it's still only ONE shortcut....

Whereas on the Mouse gesture page, there is the option for clicking on the main area (desktop) or menubar, or dock.  Which is awesome because it essentially allows for THREE different shortcuts for one button.  For example, using the M570, on, say, Chrome, the "Back" button zooms out on the webpage clicking "normally."  but same button, click on menu bar and it hides Chrome, further....clicking on the Dock, same button, in Chrome,  it turns on the Microphone for Dragon Dictate.

But I'm kind of using the "scroll left"  "scroll right" and "precision"  buttons on the Ergo to compensate.
