### ISSUE TITLE
Feature Request: action based on URL of active tab of a browser

### ISSUE THREAD

**Issue by sanfm12** [folivoraAI/BetterTouchTool#2303]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Hi, I've been combining BTT and applescript to use the same keyboard shortcut to activate different actions, according to the URL of the active tab, mostly on Safari.
It's very useful, but as my knowledge on apple scripting is very limited, I cannot perform as many tasks as I'd like to, so that I think it would be a great idea if BTT could recognize URLs and trigger specific shortcuts on them on its own, without relying on applescript.
I'll give you an example: I press the  "¥" key and BTT:
1) triggers the "smart zoom" action if the active URL in Safari contains "nytimes".
2) triggers "capture screenshot" if the active URL in Safari contains "youtube".
3) triggers "show clipboard/pasteboard history" if the active URL in Safari contains "blogger".

#### Device information:

Type of Mac: macbook pro
macOS version: 10.11.6
BetterTouchTool version: 2.405 (756)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by OrbitalTech** [comment]
You can get the URL of an active tab in Safari by doing the following:
`set theURL to URL of front document`

You might find the resources on this website useful should you wish to endeavour more: https://www.alfredforum.com/topic/2013-how-to-get-frontmost-tab%E2%80%99s-url-and-title-of-various-browsers/

As for having different functions for different websites, you could do something along the lines of
`set theString to "youtube"`
`if theURL contains theString then`
`--Put the features here, in this case screenshot`
`end if`

I understand you said you'd rather not have to rely on applescript, but I've personally become quite fond of applescript and find that if you put a little bit of time into researching what you need to do then you'll often find a solution.

This is also quite a specific use case. There wouldn't be that many situations in which you'd need different functions for different websites.
