### ISSUE TITLE
Feature Request: trigger action on app launch

### ISSUE THREAD

**Issue by sanfm12** [folivoraAI/BetterTouchTool#2304]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

Hi, it would be great to have some actions to be triggered when an specific app is launched.
Some examples:
1) when application "Spotify" is launched, "enter fullscreen" is triggered.
2) when application "Word" is launched, "play/pause" is triggered.
3) when application "iBooks" is launched, "hide all windows" is triggered.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
A new input should be created, such as "trigger action by app launch".

#### Device information:

Type of Mac: macbook pro
macOS version: 10.11.6
BetterTouchTool version: 2.405 (756)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
This will be added soon!
