### ISSUE TITLE
Feature request: actions to only change window size/position in one dimension

### ISSUE THREAD

**Issue by thedjinn** [folivoraAI/BetterTouchTool#2315]
Hello! Long time happy BTT user here. Recently I've added a secondary monitor to my setup and started making use of the actions to move a window to the left/middle/right third areas of the screen. This works great, but what I am missing is a way to combine this with the move to top-left/bottom-left/... actions.

A quick solution would be to add six similar options to partition the screen into six areas (e.g. left lane, top half), but this becomes messy. Therefore I propose an action to move a window to the top or bottom half of the screen without changing x position and width. The benefit of having an option like this is that you can also use it with windows that require custom widths.

**Comment by fifafu** [comment]
In v2.460 (alpha) there is a new predefined action which can do all sorts of custom window moving and resizing:
![image](https://user-images.githubusercontent.com/8820811/39365653-08ef6b04-4a32-11e8-98be-4befc40b4506.png)
