### ISSUE TITLE
Activating clipboard history using CMD key then 'P' to "Paste as plain text" does not 'release' CMD key from DOWN state.

### ISSUE THREAD

**Issue by semiconducted** [folivoraAI/BetterTouchTool#2319]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Activating clipboard history using the CMD button (in my case CMD+DOWN) and then pressing P (still while CMD keyDown) to "Paste as plain text" causes the **CMD key to act as if it 'stuck' down in all apps** thereafter. 

To 'release' the CMD key, I must press CMD+DOWN again to bring up clipboard and then ESC to close the window.

This behavior DOES NOT OCCUR if I press CMD+DOWN to bring up clipboard, RELEASE the CMD key, then press CMD(again)+P to "Paste as plain text".

Related Feature Requests: 
1. I would love to customize the default behavior - only rarely do I ever want to paste WITH formatting. In my view, once invoking history, just pressing Enter alone should paste the item without formatting, especially on the first item. If you want to paste WITH formatting, you can still use the default copy/paste directly (without invoking BTT). 
2. If not the above I would love to be able to customize the keyboard shortcuts for the paste options so I could achieve the above scenario. I tried through System Preferences > Keyboard > Shortcuts and id had no effect.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Macbook keyboard - all apps

#### Device information:

Type of Mac: MacBook Pro (15-inch, 2016)
macOS version: 10.13.3 (17D102)
BetterTouchTool version: 2.421 (778)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
weird, I can't seem to reproduce this.
Could you post a screenshot of your config?

I can add an option to paste without formatting (won't make it default though)

**Comment by dhammy0110** [comment]
Attached are screenshots of every config page - I also just completely uninstalled LaunchBar, which I used to use just for the clipboard history but have not had it running in a very long time.
I thought there might be a conflict in my ios / system keyboard shortcuts, but I see nothing obvious.



Thanks again for your help!

Lastly, here are screenshots of the ongoing behavior:
0. CMD-DOWN is what I use to invoke clipboard manager so I can repeatedly hit DOWN to scroll through the list.
1. Selected and hit CMD-C to copy "ongoing behavior” text above
2. hit CMD-DOWN to invoke clipboard manager
3. see:

4. immediately hit “CMD-p” while STILL holding down CMD key
5. ongoing behavior <- this pasted correctly, however keyboard acts as though CMD is being held down - LEFT, and RIGHT move the cursor to the beginning and end of the sentence,
6. pressing DOWN arrow brings up clipboard manager again and I again see:

7. Press ESC to close clipboard manager, but CMD key is still stuck.
8. Only way to fix is to hit CMD-DOWN to again invoke clipboard manager, THEN press ESC again.

A. I currently have “Paste selection...” turned off:


B. Turning “Paste selection...” feature ON will cause the same issue if I do not release the CMD key before pressing DOWN arrow (my shortcut to invoke the clipboard manager).

Hope this helps!

- Damon





P.S. I took screenshots of every BTT and Mac OS System Preferences screen, but that made the email too big to send - let me know if you want them.

**Comment by stephenhau** [comment]
I have almost this same issue. 

**Description:**
1. Set a keyboard shortcut in BTT to Paste Specific Items from Clipboard, Position 1, paste as plain text.
2. Select 3 files in Finder, and hit CMD+C – this will save the thumbnails and filenames as formatted text. 
3. Open TextEdit.
4. Use your keyboard shortcut from Step 1 to paste as plain text (that is, it should then only paste the filenames)
5. Discover that key presses after that behave as if CMD+CTRL is held down. For example, pressing "f" will invoke the CMD+CTRL+f in your app (**not** just CMD as in OP's issue), causing TextEdit to go into full screen view.
6. To 'exit' this problem, open BTT's clipboard manager, select the gear at the top right, "Clear all history".

**Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):**
Keyboard

**Device information:**
iMac (Retina 5K, 27-inch, Late 2015)
3.2 GHz Intel Core i5
32 GB 1867 MHz DDR3
AMD Radeon R9 M390 2048 MB

If you need more info, I'll be happy to provide.

**Comment by semiconducted** [comment]
My quick solution to ‘exit’ the problem is to invoke the clipboard manager and then simply hit ‘esc’ to close the window. The ‘stuck’ keys are then released (for me).
Hopefully this works in your case!

- Damon

____
Damon Hamm
www.semiconducted.com

**Comment by stephenhau** [comment]
I was hoping to use a single "paste as plain text" keyboard shortcut across all the programs I use. Until it's fixed, it's easier for me to learn the shortcuts rather than invoke/esc the clipboard manager. Thanks all the same!

**Comment by semiconducted** [comment]
Ah, I like that you created a custom ‘paste as text’ shortcut. Good to know, thanks! 
My ’show clipboard manager’ shortcut happens to be CMD-[down-arrow] so my finger is already on the down-arrow to scroll through the history.
However, I DO use the default CMD-p shortcut to paste as plain text and still experience the same ‘sticking’ issue.
