### ISSUE TITLE
BTT eats shortcut key inputs after update

### ISSUE THREAD

**Issue by OwenDostie** [folivoraAI/BetterTouchTool#2320]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
I use BTT as a "numpad", so that when I'm holding the left alt key, a grid of numbers appears under my right hand. It was working flawlessly for the longest time, but stopped behaving properly after I updated recently. 

What's happening is that the first number I press will have the "alt" modifier applied to it, causing a symbol to be typed. For example: if I want to type 5667 it will show up like this ∞667. 

For some reason, this error does not occur in Pages or Numbers , but does occur in every other circumstance that I've tested. 

### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Keyboard 
I use the Dvorak keyboard layout if that matters at all here. 

#### Device information:

Type of Mac: MacBook Pro 15 inch 2016
macOS version: 10.13.1
BetterTouchTool version: 2.422 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
Restarting my computer, re-implementing the shortcuts & enabling the old keyboard implementation has not fixed anything. 

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
I have had a similar report with someone who's usong Dvorak. Unfortunately I have no experience with that layout.

For now easiest is probably to downgrade if you are usong dvorak. (Https://boastr.net/releases) v2.340 should work fine.

I'll see if I can reproduce it on my machine. 
Do you use any special Dvorak configuration?

**Comment by OwenDostie** [comment]
I use the standard Dvorak configuration. I guess my layout is a little different because I have caps lock set to be a second backspace key

**Comment by OwenDostie** [comment]
And thanks a lot for the quick response, I really wasn't expecting that :)

owendostie@gmail.com (mailto:owendostie@gmail.com)
617-800-6366

**Comment by fifafu** [comment]
Unfortunately I can't seem to reproduce this here.

If possible go to the about tab in BTT and click the "export debug information" button. This will create a folder called BetterTouchToolDebug on your Desktop. Would be great if you could send that to boastr.net@gmail.com and reference this issue then I'll look into it.
