### ISSUE TITLE
Application Specific Touchbar Predefined Sets

### ISSUE THREAD

**Issue by macMikey** [folivoraAI/BetterTouchTool#2324]
My touchbar is set to use the extended control strip.
I'd like to be able to have an application-specific setting to make Terminal switch it so f1..fn, but I don't see anything like that in BTT

**Comment by OrbitalTech** [comment]
<img width="207" alt="screen shot 2018-03-26 at 8 12 08 am" src="https://user-images.githubusercontent.com/23006558/37878998-90b29fee-30cd-11e8-9a7f-ac7a045e5d51.png">
This is where you'll find application specifics. Clicking the plus button allows you to set up custom touch bar buttons for each application.

I'm not quite sure what you mean by Terminal, but hopefully this helps.

**Comment by macMikey** [comment]
I know how to set up application specific buttons.  What I want to do is use an already-system-defined set for the Terminal (you know, the command line), namely f1,f2,f3 etc. without having to set it up and then figure out what the control characters are that they correspond to.

**Comment by OrbitalTech** [comment]
You can either fully replace the touchbar with BTT or not have it at all. If you want to have the original buttons provided in terminal, then you can disable BTT for terminal, but you can't have both.

If you need the F keys, just press Fn.

**Comment by macMikey** [comment]
Except it doesn't work.
Here is the BTT setup.
Touchbar does not change.

<img width="1017" alt="screen shot 2018-03-25 at 19 27 40" src="https://user-images.githubusercontent.com/10867016/37881309-fad52852-3063-11e8-8da7-b12a6d487848.png">

**Comment by macMikey** [comment]
Here is the touchbar both in terminal and not
<img width="1085" alt="touch bar shot 2018-03-25 at 19 35 09" src="https://user-images.githubusercontent.com/10867016/37881312-1d0b5e46-3064-11e8-9d91-43abdc6413fe.png">

**Comment by OrbitalTech** [comment]
Alright, I've recreated your buttons in my BTT, and it works fine. The screenshot you took of the touchbar shows the default apple control strip when you hit the arrow to expand it, rather than BTT.

Can you just make sure that the BTT touch bar is enabled in the app specific menu, and that it is open? If its open, could you try hitting "Command + Q" to quit the application outright and then reopening it?

**Comment by macMikey** [comment]
OK, I see the problem.  You have to then go into settings and activate the configuration.  Screenshot attached for the next person to run into this problem.

![image](https://user-images.githubusercontent.com/10867016/37916712-8ca85020-30ea-11e8-8430-4cec18f821d0.png)
