### ISSUE TITLE
JumpDesktop

### ISSUE THREAD

**Issue by johnfugh** [folivoraAI/BetterTouchTool#2325]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Using JumpDesktop to remote connect to MacBook Retina and my Keyboard Shortcuts are not working.  They used to work, but not sure what version they stopped working.  

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Keyboard

#### Device information:

Type of Mac: MacBook Retina
macOS version: High Sierra 10.13.3
BetterTouchTool version: 2.444

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
Have not found workaround.  They work locally, but not remotely.

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
I have no experience with JumpDesktop, but maybe try enabling compatibility mode for it:

![image](https://user-images.githubusercontent.com/8820811/38376128-331a2a36-38f8-11e8-85e4-e17ff1b6df97.png)

if that doesn't help try to enable the old shortcut implementation in the advanced settings => keyboard:

![image](https://user-images.githubusercontent.com/8820811/38376156-427e6e74-38f8-11e8-9576-e5d28979d851.png)
