### ISSUE TITLE
High Memory Consumption with Touchbar ScriptRunner

### ISSUE THREAD

**Issue by eidermar** [folivoraAI/BetterTouchTool#2327]
#### Description of bug/feature request/question:

I have BTT running with 4 simple Touchbar buttons and a the Spotify track name script that was shared here. Memory consumption of the ScriptRunner is as high as 4GB with this setup. This seems excessive, is this behaviour to be expected?

![btt_memory_consumption](https://user-images.githubusercontent.com/16689717/37890702-d7e830aa-30d1-11e8-849c-8a99b688a0c6.png)

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Touchbar

#### Device information:

Type of Mac: MBPT 2016
macOS version: High Sierra 10.3.3
BetterTouchTool version: 2.422

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

Here's my setup:

![btt setup](https://user-images.githubusercontent.com/16689717/37890784-24fb33c4-30d2-11e8-9515-b47464365cca.png)

**Comment by trevorhardy** [comment]
I'm seeing a similar behavior. After running for 45 minutes with two global widgets, BTT is consuming 200MB of memory (and growing).

**Comment by trevorhardy** [comment]
I modified one of the widget scripts that was running to refresh every 100s (instead of 1s) and this has slowed the rate of memory consumption. Memory consumption is still high (~180MB after 25 minutes) but growing much more slowly.

**Comment by amarpatel** [comment]
Same issue for me:

![image](https://user-images.githubusercontent.com/5858247/38401965-bcde2f46-390d-11e8-8b56-67cb44eba9bf.png)

**Comment by fifafu** [comment]
I have finally identified the issue with BetterTouchToolScriptRUnner (it's an Apple bug).
I have found a workaround and will add it to the next version.
