### ISSUE TITLE
Recursive trigger not being prevented

### ISSUE THREAD

**Issue by soapergem** [folivoraAI/BetterTouchTool#2330]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

I've got two different keyboard shortcuts which should work, but appears to have a bug. One keyboard shortcut is to map ⌘E to trigger a predefined action: Open Finder. The second is to map ^E to trigger another keyboard shortcut, namely ⌘E. However the latter option also has the "Prevent recursive triggers" checkbox enabled.

I use an open source image editing program called Gimp which uses ⌘E to Export (effectively save) images. So because of these two keyboard shortcuts I have set up, I would expect ^E to bring up the Export menu. However it just opens Finder instead. And obviously pressing ⌘E directly also opens up Finder. So I seem to be stuck. As far as I can tell I have everything configured as it should be but it's just not working in this case.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

I'm on a MacBook Pro running macOS Sierra, version 10.12.6. I'm using an external bluetooth keyboard from Microsoft called the Sculpt Desktop.

#### Device information:

Type of Mac: MacBook Pro
macOS version: Sierra 10.12.6
BetterTouchTool version: 2.422

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Weird, this seems to work fine here.

If possible go to the about tab in BTT and click the "export debug information" button. This will create a folder called BetterTouchToolDebug on your Desktop. Would be great if you could send that to boastr.net@gmail.com and reference the issue then I'll look into it.
