### ISSUE TITLE
Automatically switch to old keyboard implementation if secure input is enabled not working as intended.

### ISSUE THREAD

**Issue by m3kwong** [folivoraAI/BetterTouchTool#2332]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
I expect that this feature would fall back to old style.  Here is how to reproduce it.  Use Notes App or Xcode. The option:  Automatically switch to old keyboard implementation if secure input is enabled not working as intended ( i expect it to fall back to old implementation)

The KB short cuts defined in BTT will not work unless I check off "Always use old keyboard shortcut".

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
macbook keyboard

#### Device information:

Type of Mac:  MacBook Pro 2016
macOS version: 10.13.3
BetterTouchTool version: 2.422(779)  the previous version didn't work either, not sure when it stopped.  

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Sorry, there are some apps that can cause issues with this (e.g. some anti virus software). I currently believe this is not fixable but I'll continue looking into it.

Do you have any anti virus related software installed? (So far that was mostly the problem, but I'm also looking for other conflicting apps)

**Comment by m3kwong** [comment]
No i don’t have anti virus installed.  

But I get this when I’m in the notes app:



But what I thought was that if you enable this option, it will automatically fall back to original(old keyboard short implementation) option so everything would still work.



i think that is the bug.

**Comment by m3kwong** [comment]
I have to manually switch this on to get my shortcut to work in notes.

**Comment by fifafu** [comment]
The problem is that neither Notes nor Xcode activate secure input on normal systems unless password fields are active. It seems to be an issue triggered by some third party apps, but I do not have a list of these yet. Somehow the state of the secure input flag is weird, which causes BTT's auto-switch to fail as far as I can tell so far.

(Github removes screenshots when attaching them to e-mails, you need to reply on the web page unfortunately)
