### ISSUE TITLE
Request for setting to reduce tap delay

### ISSUE THREAD

**Issue by npdbharris** [folivoraAI/BetterTouchTool#2336]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

There's currently a delay after trackpad tapping, presumably in order to allow time to detect a double-tap. It would be wonderful if I could shorten that delay (it seems like 500-750ms, and I'd have it set to 150-200ms). The default value turns my hair gray :)

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Trackpad, Mid-2015 Macbook Pro Retina

#### Device information:

Type of Mac: Mid-2015 Macbook Pro Retina Trackpad
macOS version: 10.12.16
BetterTouchTool version: 2.422

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

Thanks! :)

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
I think it gets a little bit faster if you disable double-tap to drag in System Preferences, but apart from that I don't think there is a way to achieve this.
