### ISSUE TITLE
Lost Custom Snap Areas

### ISSUE THREAD

**Issue by BradNeiman** [folivoraAI/BetterTouchTool#2339]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
I was happily using BetterSnapTool for years (since 2015). About a week ago, I lost all my custom Snap Areas. I just upgraded to BetterTouchTool, tried clicking "Import existing Snap Areas from BetterSnapTool (experimental)," restarted my machine & still no custom Snap Areas.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
MacBook Pro (Retina, 15-inch, Mid 2014)

#### Device information:

Type of Mac: MacBook Pro (Retina, 15-inch, Mid 2014)
macOS version: 10.13.3
BetterTouchTool version: 2.422

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Did you maybe change your screen resolution or switch to a new monitor? (Snap areas are currently vound to a specific display setup).

You could zip the ~/Library/Application Support/BetterSnapTool folder and send it to boastr.net@gmail.com, then I'll check if there is still something to recover.

**Comment by pbchase** [comment]
I've had this same problem for years with Better Snap Tool. It started when I had two offices. The snap areas I define on one monitor are not valid on another even though it has exactly the same geometry. 

I only have one office now, but yesterday I briefly connected to a co-worker's monitor.  Today when I returned to my own office all my custom snap areas are gone. It's exasperating. Can custom snap areas be "reused" on monitors of similar geometry? Could they be stored independently of the monitor so I could apply them to another monitor?

**Comment by pbchase** [comment]
@fifafu, thanks for the reply. I see the conflict with multi-display use case. 

I do like your proposed solution.  I think it would help me a lot.  My use cases are: laptop, laptop attached to a single display with the lid closed, laptop attached to a projector with mirrored screens.  I think your proposal might allow me to have my standard snap areas available at all times. That would be useful.

**Comment by kimaldis** [comment]
I've just started noticing something like this too. Suddenly all my custom areas wouldn't appear when I used <fn>drag to move windows around. Also, none of the standard resize areas - top, left, right, etc - aren't working. I can drag windows around but they won't resize wherever the mouse goes. Then suddenly they'll re-appear. I've tried most things to get them back - restarting BTT, messing with preferences, adding more areas and rebooting the machine - without result. Edit snap areas does show the areas and I am able to make changes.

Macbook pro, retina, 2017
OS X 10.13.4 (17E199)
BTT 2.466 (820)

I am using multiple desktops.

**Comment by kimaldis** [comment]
Interestingly, if I disable snap area feature and restart BTT I get my default areas back but not my custom areas. Right now, snapping to default areas only works if I have snap area feature disabled.  

A side effect of this seems to be that custom areas are no longer coming and going randomly, they're simply not working at all. This is eating into my workflow a bit so if there are any suggestions ....

**Comment by kimaldis** [comment]
Also, if snap area feature is disabled the edit custom areas menu item disappears.

**Comment by kimaldis** [comment]
OK, so I killed all my custom areas after enabling custom area features, went out for a walk. When I came back the default areas were suddenly working, even with custom areas enabled - recall, enabling custom areas killed all window size changing. So I created a new custom area and suddenly no custom areas, default or custom, worked any more.

**Comment by kimaldis** [comment]
And, sigh, having said that, it's all working again after a few minutes. Sorry I can't supply anything more reproduceable.

**Comment by kimaldis** [comment]
Is there any news on this? I've had to revert to BetterSnapTool to get snap areas to work.

**Comment by fifafu** [comment]
unfortunately I have no idea. Bettersnaptool uses the same snapping code as BTT.

maybe go to the about tab in BetterTouchTool and click the export debug info button. This will create a folder called BetterTouchToolDebug on your desktop. If you send that to me via andreas@folivora.ai I'll check if I can see anything.

**Comment by charginghawk** [comment]
I recently changed my displays and lost my snap areas. I used the same monitors but rearranged them, which seems like it was enough to do it.

To recover them, I opened up `~/Library/Application\ Support/BetterSnapTool/storedata`. There I located the appropriate `BSTDRAGPOINT`s, which are the snap areas. They have `idrefs` to the old `BSTCDISPLAY`, which is the display, and the old `BSTCDISPLAY` had it's own `idrefs` references back to the snap areas.

I created a new snap area on the display I wanted, which was then added to the end of the file. I was able to use this new information to identify the new `BSTCDISPLAY`. Setting the `idrefs` on the old `BSTDRAGPOINT`s to the new `BSTCDISPLAY`,  and setting the `idrefs` on the new `BSTCDISPLAY` back to the old `BSTDRAGPOINT`s, I was able to recover my snap areas.

On a side note, the snap areas were just vertical thirds because I have a vertical monitor, maybe that'd be a good feature.

**Comment by fifafu** [comment]
hah nice work 👍 (would have been slightly easier by exporting your preset and then editing the json a d reimporting).

For thirds and stuff like this you can also use the "custom resize and move" action (but only if you don't need to access them by dragging). 


I'm still working on the bigger snap area and window snapping update which will solved  the display-specific settings issue.

**Comment by philtim** [comment]
Is there a way to manually edit the exported preset json so that custom snap areas are working on a different monitor?

I'm working for a client where one sits every day at another desk (open space), but the monitors are all the same (same brand, same resolutions, same model). Therefore I have to create the same custom snap areas over and over again.

**Comment by jsunsawyer** [comment]
@philtim I would also like to be able to import my snap area settings for another, same resolution monitor. Every monitor I use is 2560x1440 and I am required to manually re-set my snap areas for each monitor, which might not seem like a lot to everyone, but I heavily rely on snap areas for my workflow.
