### ISSUE TITLE
Shift, Command keys cause touch bar shell-script widgets to reload

### ISSUE THREAD

**Issue by etaba** [folivoraAI/BetterTouchTool#2347]
#### Description of bug/feature request/question:

I love the ability to make custom touchbar shell-script widgets. But whenever i press Command, or Shift, it causes all the shell script buttons to rerun the shell scripts. This is bothersome when you have made many buttons whose scripts take longer than a second to run, since usage of these 2 keys is naturally pretty high when you're using your computer. If this is behaving as intended can a disable option be added?

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Touch Bar

#### Device information:

Type of Mac: MacBook Pro (15-inch, 2017)
macOS version: Sierra 10.12.6
BetterTouchTool version: 2.421

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

Reproduction steps:
1) create touchbar shell-script widget which returns a random value.
2) press command or shift and note that the script is being run every time those keys are pressed.

**Comment by fifafu** [comment]
I think there have been some improvements in the latest alpha version. Would be great if you could test that.
