### ISSUE TITLE
4 finger tap to enable drawing not working in Chrome (Mac OS)

### ISSUE THREAD

**Issue by snsokstan** [folivoraAI/BetterTouchTool#2348]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
  I want to create a gesture that moves tabs forward and backward in Chrome. I created a 4 finger tap to enable drawing. That does not work in Chrome. The four finger tap opens drawing in other applications but not chrome.  It does work in Safari.

This feature alone is what I want BTT for.

#### Device information:

Type of Mac: iMac Late 2014 Retina 5K
macOS version: 10 13 3
BetterTouchTool version: 2.442

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Sounds like you override the gesture for Chrome.
Make sure you don't have it configured differently for Chrome, e.g. in this screenshot it would override the global 4 finger tap for chrome and cause it to do nothing:

![image](https://user-images.githubusercontent.com/8820811/38085197-fc93143a-334f-11e8-9ead-c4905c2bebb6.png)

**Comment by snsokstan** [comment]
Thanks. I deleted any actions specific to Chrome just to be sure. That didn't make a difference. I just have the 4 finger tap as a global. It works in every application including Opera but it does not work in Chrome.  I also tried disabling all my extensions.

**Comment by fifafu** [comment]
If possible go to the about tab in BTT and click the "export debug information" button. This will create a folder called BetterTouchToolDebug on your Desktop. Would be great if you could send that to andreas@folivora.ai then I'll look into it!
