### ISSUE TITLE
BTT keeps restarting after waking from sleep

### ISSUE THREAD

**Issue by JuiceL** [folivoraAI/BetterTouchTool#2349]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Since updating, BTT keeps saying it needs to restart after waking from sleep.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Macbook Pro 2016

#### Device information:

Type of Mac: Macbook Pro 2016
macOS version:  10.13.3
BetterTouchTool version: 2.422 (779)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by robin3** [comment]
I have this problem too. It seems to occur on wake from sleep and when logging in from the lock screen (e.g. after the screen saver has been activated)

15" Macbook Pro 2017
Mac OS 10.13.13
BTT 2.422

**Comment by JuiceL** [comment]
Hi,

Thanks for the quick response  I’ll download it now and give it a try.

Thanks!

**Comment by robin3** [comment]
Updated - but just got the message again.

Note: not upon waking from screensaver this time

![screen shot 2018-03-29 at 17 54 11](https://user-images.githubusercontent.com/3845427/38102182-69431d6c-337a-11e8-991e-565095303198.png)

**Comment by hodak** [comment]
I'm getting this error a lot since yesterday too. Couple of differences - it's not only after waking up - I restarted Mac and it still happens. It happens roughly every 30 minutes - 1 hour. I don't have "Always use old keyboard shortcut implementation" enabled. It's getting really frustrating.

**Comment by fifafu** [comment]
Mh are you already on macOS 10.13.4?

In general the message only appears when the system fails to install the BetterTouchTool event handler for unknown reasons.

However I think I can make it so BTT just restarts in this case, without showing the message.

**Comment by hodak** [comment]
I'm still on Sierra 10.12.6. I have not reinstalled BTT recently and it used to work fine, I saw this alert for the first time yesterday.

**Comment by robin3** [comment]
It restarted several times today already. @fifafu is there any logging data I can send you which might help with debugging?

**Comment by fifafu** [comment]
Debugging won't help (I already know when this message is being shown, however it seems to be a macOS bug).

You can try to update to the latest alpha version. I have changed it, so it just restarts with no error message.

**Comment by mikeweilgart** [comment]
I've been having this problem, too, and not only when waking from sleep.

It's notable that before the last time I updated, I almost never had to restart BTT to get it working again.  I also have the "use old keyboard shortcuts" box checked.

While making the restart silent may be more convenient, is it truly necessary to restart so often?  :(

**Comment by hodak** [comment]
I'm using the newest alpha and I've just received this 
![image](https://user-images.githubusercontent.com/3764926/38294516-677f845a-37eb-11e8-9dde-e4889d7cad10.png)

**Comment by fifafu** [comment]
Ah it's showing the accessibility api popup?

That sounds like a file permission problem on your system  then, which would explain why almost nobody seems to be affected by this issue.

I think you may need to fix the file permissions of this file: ~/Library/Preferences/com.hegenberg.BetterTouchTool.plist (or just delete the file, however it contains the BetterTouchTool settings - but not the gestures and triggers, they are saved somewhere else)

**Comment by robin3** [comment]
I just got this message too. I've been using BTT for months, and haven't touched the permissions.

Currently running the latest alpha.

Also worth noting that this is the first time 'Need to restart BTT' box has been accompanied by the 'BTT is now ready to use' box. On all previous occasion this issue occurred, the 'Need to restart BTT' box appeared alone.

![screen shot 2018-04-04 at 15 20 50](https://user-images.githubusercontent.com/3845427/38313420-e48c962e-381b-11e8-89fb-e0f5f4965f26.png)

**Comment by fifafu** [comment]
that's "good" so you both seem to encounter the same base issue. 

There are two cases when the ready to use window shows up:
- if BTT can't write to it's settings file due to corrupted/broken file permissions (in that case deleting the ~/Library/Preferences/com.hegenberg.BetterTouchTool.plist  or fixing it's permissions will fix the issue)
- if the Apple API AXIsProcessTrustedWithOptions() returns false (which means macOS thinks the Accessibiity API in System Preferences => Security & Privacy => Privacy => Accessibility is not enabled for BTT). This is unfortunately completely handled by the system, so let's hope it's not that.

If possible go to the about tab in BTT and click the "export debug information" button. This will create a folder called BetterTouchToolDebug on your Desktop. Would be great if you could send that to boastr.net@gmail.com and reference this issue then I'll look into it.

**Comment by robin3** [comment]
Thanks @fifafu I've emailed you the debug info.

Also, here's a screenshot of the accessibility status and read/write permissions on the plist file. Looks like the plot was (re)created today?

<img width="942" alt="image 2018-04-04 15-48-47" src="https://user-images.githubusercontent.com/3845427/38315505-8a05c5cc-3820-11e8-8c15-0bca12e407df.png">

**Comment by fifafu** [comment]
I have added some more workarounds to the latest BTT alpha. Maybe check whether that fixes the issue for you.

**Comment by hodak** [comment]
I checked the `com.hegenberg.BetterTouchTool.plist` file - I don't think there were permissions problem with it, it had the same permissions as all the other files in this directory.

I don't know if that's strange, but there couple of these files:

```
λ ~/Library/Preferences > ls -al | grep Better
-rw-------    1 hodak  staff   136293 Apr  4 11:49 com.hegenberg.BetterTouchTool.plist
-rw-------    1 hodak  staff        0 Aug 22  2017 com.hegenberg.BetterTouchTool.plist.5G6kupY
-rw-------    1 hodak  staff        0 Feb 14 17:06 com.hegenberg.BetterTouchTool.plist.5UHWM53
-rw-------    1 hodak  staff        0 Sep  9  2017 com.hegenberg.BetterTouchTool.plist.KOKZpcS
-rw-------    1 hodak  staff        0 Sep 28  2016 com.hegenberg.BetterTouchTool.plist.QgbVxBr
-rw-------    1 hodak  staff        0 Jul  3  2017 com.hegenberg.BetterTouchTool.plist.QlJeASh
-rw-------    1 hodak  staff        0 Mar  1  2017 com.hegenberg.BetterTouchTool.plist.W9G8bon
-rw-------    1 hodak  staff        0 Mar 21  2017 com.hegenberg.BetterTouchTool.plist.dC4YsN0
-rw-------    1 hodak  staff        0 Sep 25  2016 com.hegenberg.BetterTouchTool.plist.l6U80iV
-rw-------    1 hodak  staff        0 Sep 26  2016 com.hegenberg.BetterTouchTool.plist.zRRFxS2
```

I removed them all and then imported my preset yesterday. I haven't received this error today, so I guess it fixed this. Thank you
