### ISSUE TITLE
Feature request: suspend wait action (and following one) if some other action are trigger

### ISSUE THREAD

**Issue by oliviermattelaer** [folivoraAI/BetterTouchTool#2356]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

I would like to be able to close a group window on the touchbar automatically after N second without activity (or similarly N seconds after having to push some button.

One possibility would be to be able to further customize the 
"wait for N second" action by 
"wait N seconds, cancel the subsequent action if another BTT action occurs during that time"

**Comment by OrbitalTech** [comment]
You could probably pull this off in a round-a-bout way using applescript. Set up some form of cross script variable (maybe using a plist) and then just update the seconds remaining. As part of a predefined action script, you could set the value back to N.

Not sure. Maybe have a play around and let me know where you get with it. Would be a nice built-in feature though.
