### ISSUE TITLE
Inconsistent behavior for Restore Old Window Size

### ISSUE THREAD

**Issue by NevinBR** [folivoraAI/BetterTouchTool#2357]
#### Description of bug/feature request/question:

I just updated from MacOS 10.12.6 to 10.13.4, and now BTT’s “Restore Old Window Size” action is quite inconsistent.

Sometimes—and I’m not yet sure what (if any) specific situation causes this—when I hit my “Restore Old Window Size” shortcut, it resizes the window to a different size than the last time. In between, I have not manually resized the window, though I have used BTT actions for “Maximize Window” and/or “Maximize Window Left / Right”.

The new “old window size” will be either maximized, or maximized to half the screen—namely one of the sizes that I used BTT to set it at. It is especially jarring when the “old window size” unexpectedly becomes “filling the entire screen”.

I cannot reliably reproduce this, it seems to occur occasionally and at random. Will update if I figure out how to make it happen on demand.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

MacBook Pro keyboard

#### Device information:

Type of Mac: 2013 retina MacBook Pro 15.4″
macOS version: 10.13.4
BetterTouchTool version: 2.423

**Comment by fifafu** [comment]
Unfortunately I haven't been able to reproduce this yet. In case you figure out a way to trigger the issue, please let me know!
