### ISSUE TITLE
Feature request: Open apps in full screen by default

### ISSUE THREAD

**Issue by mirekmazel** [folivoraAI/BetterTouchTool#2359]
I'd really appreciate being able to have all applications launch as full screen apps (if possible). Could that be done?

**Comment by TheBloke** [comment]
I am going to want something like this soon as well.  Specifically, I am setting up a MBP for my elderly mother.  I want to ensure that Chrome and maybe some other apps are always open and always Full Screen, so I can just teach her to use Three-Finger-Swipe-Left/Right to go between the (very few) apps she will use.

I think ideally this would be solved by one or more new Other gestures: "On Any App Launch", "On App Launch [specific app]", "On BTT launch"

There is already "After launching on Mac with Serial Number.." which basically acts like "On BTT launch" if the current SN is entered.  I could use this to open and then Full Screen specific apps.  

But for the OP's requirement, and better handling of what I want, I think "On Any App Launch" and a configurable "On App Launch" would be ideal, then they can easily run Full Screen or many other actions.
