### ISSUE TITLE
BTT and latest Firefox

### ISSUE THREAD

**Issue by knutov** [folivoraAI/BetterTouchTool#2365]
#### Description of bug/feature request/question:

Keyboard shortcuts are not working with latest BTT (including alpha version) and latest Firefox (59.0.2). 
![2018-04-02 13 53 44](https://user-images.githubusercontent.com/255869/38190371-4dfda2e2-367d-11e8-9bca-77d891d4fcf4.png)

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

MacBook keyboard
#### Device information:

Type of Mac: MacBook Pro 13" early 2015
macOS version:  10.13.3
BetterTouchTool version: 2.423

**Comment by fifafu** [comment]
Seems to work fine here, but maybe try enabling the old shortcut implementation in the advanced preferences -> keyboard.

**Comment by knutov** [comment]
@fifafu Thanks, it helps! After enabling "Always use old keyboard shortcut implementation". 

I think new mode is mostly better for me, is it possible to use old style only for Firefox?

**Comment by TheBloke** [comment]
> I think new mode is mostly better for me, is it possible to use old style only for Firefox?

@knutov Create an App Specific entry for Firefox then click the cog next to App Specific with Firefox selected, and choose the option as below:

![screenshot_2018-04-02 14 34 21_tlz1t4](https://user-images.githubusercontent.com/784313/38198092-436ff004-3683-11e8-83f4-3018263f14f7.png)

**Comment by knutov** [comment]
@TheBloke tryed to do so and not all shorcuts are working: 

![2018-04-03 3 58 16](https://user-images.githubusercontent.com/255869/38220385-4ab6956e-36f3-11e8-8c0e-9165236e5d21.png)

command+1/2 are working but command+f11/f12 are not working in this case

**Comment by fifafu** [comment]
That compatibility option only affects "sending shortcuts to an app" not receiving shortcuts.

Have you already tried to delete the non-working shortcut and record it again? It's possible that a previous version didn't record it correctly.

**Comment by knutov** [comment]
Oh, sorry, I forgot about this issue.
As for now the problem is still exists.
Compatibility option do not changes anything visible.

And more detailed description of problem is: BTT works fine some time after starting app,macbook,etc, but then accidently stops working. Then I do "Disable+Enable BTT for All (or active) app" and then it works again for some time (it can be minutes or hours)
