### ISSUE TITLE
BTT is in Applications Folder But Error Message Says It's Not

### ISSUE THREAD

**Issue by mabritt** [folivoraAI/BetterTouchTool#2369]
I'm on version 2.318 (702) and when I click on "Check for regular updates" I get this error message: https://www.screencast.com/t/lWrwMkHg

BTT is already in my Applications folder. Why is this happening and what can I do? 

Type of Mac: MacBook Pro
macOS version: 10.12.6
BetterTouchTool version: 2.318 (702)

**Comment by fifafu** [comment]
Sounds like some file permission problem.
Could you try to delete it and move it to the Applications folder again?
