### ISSUE TITLE
Feature Request: add multicolor visualizer for music (itunes/spotify, etc)

### ISSUE THREAD

**Issue by jzadra** [folivoraAI/BetterTouchTool#2373]
It would be awesome to have a multicolor visualizer something like these below for music that is playing regardless of source (itunes, spotify, etc).

Perhaps an option could be included that would display it while music is playing, along with music controls, after a certain amount of touchbar activity (or just as a small widget).  If it were large, then touching it could hide it so that the usual controls become visible.

![image](https://user-images.githubusercontent.com/25590353/38214745-d784ad80-3682-11e8-979d-ffb44bb5c03f.png)

![image](https://user-images.githubusercontent.com/25590353/38214763-dfeda12a-3682-11e8-80e6-a212e5334127.png)

BTW, BTT is my favorite app of all time! Thank you so much for all your hard work developing it!

**Comment by OrbitalTech** [comment]
I don't think this is really close to possible. You might be able to achieve this when Fifafu introduces the ability to set icons using applescript. I believe as a feature, its marked as something on its way but I  wouldn't hold my breath for any time soon.
