### ISSUE TITLE
[Bug] "Type Custom Text" by typing freezes dropdown menus

### ISSUE THREAD

**Issue by felixbinder** [folivoraAI/BetterTouchTool#2374]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
I'd like to activate the paste by typing action while a dropdown menu (in my case safari, but it happens elsewhere too) is open. The menu is long and I want to find a specific entry. Typing the text out "by hand" works fine, the corresponding item is selected. When the Type Custom Text action is activated with the "insert text by typing" option being active, the dropdown menu simply freezes and stops reacting to mouse and keyboard input. It can be closed by opening mission control.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Happens when the action is triggered by keyboard, mouse and as part of a series of actions which also opens the dropdown menu

#### Device information:

Type of Mac:MacBookPro11,3
macOS version: macOS 10.13.3 (17D102)
BetterTouchTool version: 2.422

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

<img width="393" alt="screen shot 2018-04-02 at 18 40 36" src="https://user-images.githubusercontent.com/24477285/38219845-9772f3be-36a5-11e8-9c0e-85f4f715bac0.png">
<img width="1127" alt="screen shot 2018-04-02 at 18 40 18" src="https://user-images.githubusercontent.com/24477285/38219846-9b677486-36a5-11e8-8f88-7faf5e5d8996.png">

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
This issue was moved to https://community.folivora.ai/t/bug-type-custom-text-by-typing-freezes-dropdown-menus/46

**Comment by fifafu** [comment]
Sorry, please ignore the previous message. The migration didn't work correctly, for now the issues will stay here.
