### ISSUE TITLE
Menubar in Context Menu prevents trackpad gestures

### ISSUE THREAD

**Issue by NevinBR** [folivoraAI/BetterTouchTool#2376]
#### Description of bug/feature request/question:

I have a BTT gesture for 3-finger double-tap that sends “Show Menubar in Context Menu”, and it works.

I have a BTT gesture for 5-finger tap that sends Esc, and it works.

However, once I bring up the menubar with a 3-finger double-tap, the 5-finger tap gesture has no effect. Whereas the actual Esc key closes the popup menu, the gesture which sends Esc does not. In fact, all of my trackpad gestures that send keyboard actions have no effect when the menubar is showing in a context menu.

Or at least, that’s how it behaves when I make a minimal profile to test. What I actually see with my main setup is, while the menubar is showing in the context menu, triggering another trackpad shortcut that sends a keyboard action has no effect, and it makes all subsequent taps and clicks also have no effect. In particular, I cannot close the context menu by clicking away from it, nor activate one of its items by clicking on it, after attempting to activate such a trackpad shortcut.

When I made a minimal profile to test, I found that trackpad gestures have no effect while that menu is up, but I could not reproduce the “prevent all clicks and taps” behavior that I continue to observe with my main setup.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

MacBook Pro trackpad

#### Device information:

Type of Mac: 2013 Retina MacBook Pro 15.4″
macOS version: 10.13.4
BetterTouchTool version: 2.423

**Comment by NevinBR** [comment]
Here is a simple BTT profile that produces the issue:
[Test.json.zip](https://github.com/fifafu/BetterTouchTool/files/1882683/Test.json.zip)

It has two gestures:

• 3-finger click sends “Show menubar in context menu”
• 4-finger click sends cmd-shift-tab (cycle through open apps)

With this setup:

1\) Do a 3-finger click to bring up the menubar context menu.
2\) Do a 4-finger click. Nothing seems to happen.

Now try clicking normally—no effect. Can’t even click on items in the menubar context menu. Need use the keyboard to get out of it.

**Comment by fifafu** [comment]
Unfortunately this is a known issue (macOS context menus run in a specific runloop and block others).

I have made it less bad with the new alpha version, in that it disables all other BTT functionality while that menu is open, which prevents the click problem. I think this should be good enough (in the long run I may need to move it to a separate process)
