### ISSUE TITLE
Touch Bar Battery widget: shows remaining time instead of charge when plugged in

### ISSUE THREAD

**Issue by Shnub** [folivoraAI/BetterTouchTool#2379]
#### Description of bug/feature request/question:

I have the Battery widget configured to only show charge percentage next to the icon, but **not** the remaining time. This works as expected when running on battery. When I plug in the power cord, however, the percentage switches to either "?:??" or "∞", depending on whether the battery is charging or fully charged. If I unplug the cord again, "?:??" is first shown, then after a few minutes it updates back to showing the percentage again.

Also (somewhat less importantly), the battery icon changes to "half empty" as soon as it first updates back to showing the percentage; but "half empty" + "100 %" seems rather inconsistent. ;-) (It _does_ show a full battery icon _before_ that update, i. e. immediately after disconnecting the power cord. Apparently, the gradation of that icon and its correlation with the percentage value could be improved.)

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Touch Bar

#### Device information:

Type of Mac: 15" MBP 2017
macOS version: 10.13.4
BetterTouchTool version: 2.422

**Comment by fifafu** [comment]
This is because the macOS battery service takes a few minutes to calculate the remaining battery or the remaining charging time.
However it should now show ?:?? forever while it is charging, so that sounds like a bug I'll need to look into.

I'll soon add a dynamic battery icon :-)

**Comment by Shnub** [comment]
To be clear, the "∞" icon _never_ goes away when plugged in.

Also, from my understanding it should never show "?:??" _as the percentage value_. That value is always displayed by macOS as between 0 and 100, and should show in BTT as such as well. As I said, I have "remaining time" switched **off**—I should never see anything but a percentage value.

> I'll soon add a dynamic battery icon :-)

Cool!

**Comment by fifafu** [comment]
Ah I see. Yep I'll fix that.

**Comment by Shnub** [comment]
Appreciated. :-)

**Comment by shotbybradley** [comment]
Any updates on this?

**Comment by Bidule200** [comment]
This bug is still present in BTT 2.636...
