### ISSUE TITLE
Auto Scrolling Feature

### ISSUE THREAD

**Issue by pallavmac** [folivoraAI/BetterTouchTool#238]
#### Description of your feature request...:
An option to start/stop scrolling would be amazing, wether someone is reading an article or browsing Facebook, they can sit back and watch the page scroll! Speed could be custom set and there could be a toggle to start stop scrolling as well as one to speed up/slow down the scrolling. This could be an amazing feature and I have not seen it implemented in any other app!

**Comment by fifafu** [comment]
This issue was moved to https://community.folivora.ai/t/auto-scrolling-feature/89

**Comment by fifafu** [comment]
Sorry, please ignore the previous message. The migration didn't work correctly, for now the issues will stay here.
