### ISSUE TITLE
Touch Bar Animations

### ISSUE THREAD

**Issue by ghost** [folivoraAI/BetterTouchTool#2384]
I think it would be awesome if you could add touch bar animations, like when you open the default volume or brightness sliders on Apple's control strip. This would be great for custom sliders in BTT, and when folders are opened. Please let me know if this is possible or coming soon!

**Comment by OrbitalTech** [comment]
I believe this as a feature has been asked before and discussed by some users. You can follow it here: https://github.com/fifafu/BetterTouchTool/issues/1273

Although, I personally don't expect to see this any time soon as there are more pressing matters for the developer to attend to.
