### ISSUE TITLE
Snap Areas

### ISSUE THREAD

**Issue by CarterVE** [folivoraAI/BetterTouchTool#2385]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

Hi,

I'm having an issue where my snap areas will sometimes randomly vanish, especially when I'm using/changing presets. It would be so great to be able to see a list of the snap areas in BTT, so I can import them from a previous preset that I've saved, or in some other way save my snap areas. I usually have many custom areas configured, and it takes me a long time to re-create every one. This is especially frustrating because they exist in previous presets.

Thanks,
Carter

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Trackpad?

#### Device information:

Type of Mac: MacBook Pro 15" 2017
macOS version: 10.13.3
BetterTouchTool version: 2.423 (780)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Is this maybe related to the duplicate UUID problem you found? (The Snap Areas are already all saved in the preset file)

**Comment by CarterVE** [comment]
This is certainly possible, unfortunately even after changing the UUID as you suggested, I've still found that when toggling between presets my snap areas will sometimes vanish (I haven't been able to narrow it down to a specific action, unfortunately). 

If there was a way to view them in the main BTT window, I could simply copy them from an older preset, but at the moment the only way I've found to fix the issue is to replace my default preset with an older exported version, because I can't transfer them between presets. To avoid this I've been using BetterSnapTool and BetterTouchTool at the same time, but this seems excessive.
