### ISSUE TITLE
Toolbar widget : Getting current title

### ISSUE THREAD

**Issue by bpillon** [folivoraAI/BetterTouchTool#2397]
Hello,
I would like to get the current (or previous depends on how you see that) title for a widget. How to do this ?

example :
```if application "Spotify" is running then
	tell application "Spotify"
		if player state is playing then
			return (get artist of current track) & " - " & (get name of current track)
		else
			return **CURRENT_TITLE** (= last played track)
		end if
	end tell
end if```

Thanks !

**Comment by OrbitalTech** [comment]
Here you go:

```
tell application "Spotify"
		if player state is playing then
                         set currentTitle to (get artist of current track) & " - " & (get name of current track)
			return currentTitle
		else
			return currentTitle
		end if
	end tell

```

Although, you can find an example of a spotify widget here:

https://github.com/OrbitalTech/BTT-Scripts/tree/master/Spotify

**Comment by bpillon** [comment]
Thanks ! I didn't know that variables kept their value between executions.

**Comment by OrbitalTech** [comment]
Oh, I don't think they do, but to be honest with you I've never come across a situation when I haven't had a song paused/played in Spotify.

One way to deal with this is to write the information to a file (keeps between individual boots of a computer) or save it as a property.

Propertys keep their value between executions.

Read more <a href="https://developer.apple.com/library/content/documentation/AppleScript/Conceptual/AppleScriptLangGuide/conceptual/ASLR_variables.html">here</a>.
