### ISSUE TITLE
updateTouchBarWidget updates all widgets

### ISSUE THREAD

**Issue by OrbitalTech** [folivoraAI/BetterTouchTool#2401]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
When you call updateTouchBarWidget, it updates all widgets regardless of UUID. Then other widgets will reset their icon and or text when they next run. (Only applies to applescript widgets)

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

TouchBar

#### Device information:

Type of Mac: Macbook Pro 2017 512Gb with Touchbar
macOS version: 10.13.3
BetterTouchTool version: 2.426

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Sorry, I seem to have tested something before releasing and disabled the UUID check 🙈
It should now be working.
