### ISSUE TITLE
Request: Typing Suggestions Widget

### ISSUE THREAD

**Issue by CyrusOmerta** [folivoraAI/BetterTouchTool#2402]
Feature Request - Typing Suggestion Touchbar Widget

#### Device information:

Type of Mac: 2017 13' MacBook Pro 
macOS version: 10.13.4
BetterTouchTool version: 2.422

As with the Messages and Safari app i think it would be great if we could have a typing suggestion widget, showing 3 typing suggestions. You wouldn't need to write it from scratch if you can find the original coding in messages.

**Comment by GoldenChaos** [comment]
Would LOVE this, especially if it can surface the same autofill information that shows up on the system standard touch bar - word suggestions, emoji, and autofill information.
