### ISSUE TITLE
Can't get rid of contextual menus in App Switcher

### ISSUE THREAD

**Issue by CabildoBaggins** [folivoraAI/BetterTouchTool#2405]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead. 

---

#### Description of bug/feature request/question:
Please only post one bug or feature request per issue.

I use BTT to access the Mac's Application Switcher using a three finger tap. When I click on an app's icon to select I get a contextual menu and can't actually select the app. This started happening when I upgraded to OS X High Sierra.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Magic Mouse

#### Device information:

Type of Mac: iMac
macOS version: 10.13.4
BetterTouchTool version: 2.425

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
What kind of contextual menu? What's the content?
Do you maybe have the three finger tap multiple times configured in BTT?

**Comment by CabildoBaggins** [comment]
It’s the only thing I have configured with BTT. Here’s a screenshot

Cary

Cary Wolfson
Producer, "Blues From the Red Rooster Lounge”
http://tinyurl.com/jyp5l68

**Comment by CabildoBaggins** [comment]
I thought I had sent you this before but apparently not. (My email was acting weird for a while.)

Anyway here is what I get after I select the App Switcher using BTT. The only way I can actually select an app is to hover over its icon and hit Return.



Cary

Cary Wolfson
Producer, "Blues From the Red Rooster Lounge”
http://tinyurl.com/jyp5l68
