### ISSUE TITLE
Using BTT escape key functionality problems. Reposted and updated from #1621

### ISSUE THREAD

**Issue by kalobkalob** [folivoraAI/BetterTouchTool#2408]
I keep running into different programs where the escape button doesn't function like it should. I use option+esc as a hotkey for a mac os hotkey. Currently I encountered it not working with Snes9x. Snes9x has the option to freeze the state of the game. This is a way to save the game and reload it.

When in the freeze screen, you have to press esc to get out of it. The BTT esc button doesn't work for this.

A good example of this is the game: http://store.steampowered.com/app/230050/DLC_Quest/
In the game you have to press the esc key to access the menu. I have to actually quit BTT in order to play the game because it breaks functionality completely.

Device information:
Type of Mac: MacBook Pro 15" 2016
macOS version: 10.13.4
BetterTouchTool version: 2.425

**Comment by mluisbrown** [comment]
Since #1621 was closed I'm commenting here. I have exactly the same problem as @bmorton reported [here](https://github.com/fifafu/BetterTouchTool/issues/1621#issuecomment-379141732)

I can no longer use the Esc key to escape out of the Cmd+Tab switcher. This works fine in the normal TouchBar.

**Comment by fifafu** [comment]
@mluisbrown unfortunately a change in macOS made it impossible. This can not be fixed in BTT. I recommend to remap e.g. caps-lock to escape in System Preferences => Keyboard Modifiers.

**Comment by mluisbrown** [comment]
@fifafu that's a bummer 😕 Just out of curiosity, can you tell me what the change was, or point me to a link that explains this? (I'm a developer, I can handle it 😛 )

**Comment by fifafu** [comment]
macOS now disables all app-specific touch bars when either mission control or app switcher is active
