### ISSUE TITLE
keep buttons in group in place when tapping group

### ISSUE THREAD

**Issue by moshed** [folivoraAI/BetterTouchTool#241]
currently tapping a group opens the buttons in that group all the way on left side of the touchbar. would it be possible to open them starting in the same spot that the parent button group folder is in to minimize the amount you need to move to to tap it?

**Comment by fifafu** [comment]
yep I'll will look into something like this, however it's a bit complicated.
A hacky workaround for now: maybe create a black button with a space as title and add some padding to it in the advanced button config ;-)

**Comment by moshed** [comment]
that works for now! thanks!

**Comment by fifafu** [comment]
This issue was moved to https://community.folivora.ai/t/keep-buttons-in-group-in-place-when-tapping-group/90

**Comment by fifafu** [comment]
Sorry, please ignore the previous message. The migration didn't work correctly, for now the issues will stay here.
