### ISSUE TITLE
Action to enable/disable particular preset

### ISSUE THREAD

**Issue by ReDetection** [folivoraAI/BetterTouchTool#2411]
#### Description of bug/feature request/question:

Vas3k's subscriber here. At the moment I only found an action to set presets, which means to replace all enabled presets with a different set of presets. This is not very handy if I just want to extend functionality temporarily by touching a button. I propose to have an enable and disable preset action which mean to add or remove particular preset from the list of enabled ones. Sounds like an easy feature, right? :)

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
I'm using only TouchBar features

#### Device information:
macOS version: High Sierra
BetterTouchTool version: 2.422

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
<more><img width="362" alt="screen shot 2018-04-07 at 11 05 38" src="https://user-images.githubusercontent.com/458005/38451099-a1453ada-3a53-11e8-8695-590e2c951537.png" />
<img width="543" alt="screen shot 2018-04-07 at 11 05 25" src="https://user-images.githubusercontent.com/458005/38451100-a76c52f4-3a53-11e8-9557-1d4a3047e478.png"/>

</more>

**Comment by ReDetection** [comment]
okay

**Comment by fifafu** [comment]
The BTT issue tracker has moved to https://community.folivora.ai early this year and all issues here have been auto-closed now. In case you still need help with this issue / feature / question please create a new post there.

**Comment by ReDetection** [comment]
Ah, thank you for the explanation! ❤️

**Comment by fifafu** [comment]
Btw.: I think this something like this is included in the current versions and called "Toggle Preset", maybe this will already solve your issue.
