### ISSUE TITLE
Random Text Appearing inside widget with return value disabled.

### ISSUE THREAD

**Issue by OrbitalTech** [folivoraAI/BetterTouchTool#2413]
#### Description of bug/feature request/question:
Random Text Appearing inside widget with return value disabled.

When you hit save, its not there, but then it seems to update and the color changes and the letters show up.
In this case, its in the play pause button on the right.
<img width="1085" alt="touch bar shot 2018-04-08 at 12 11 00 am" src="https://user-images.githubusercontent.com/23006558/38454766-8166896c-3ac1-11e8-8f28-c4878c9270e8.png">
Its the exact same script as last time. I ended up completely wiping out my BTT data and starting from scratch. (Keeping a backup of course).
[BetterTouchToolDebug.zip](https://github.com/fifafu/BetterTouchTool/files/1886335/BetterTouchToolDebug.zip)

Heres my debug file.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Touchbar.

#### Device information:

Type of Mac: Macbook Pro 2017 13" 512gb with Touchbar
macOS version: 10.13.3
BetterTouchTool version: 2.428

**Comment by OrbitalTech** [comment]
This has stopped. No explanation.

**Comment by fifafu** [comment]
i know what's causing it (bug in the caching method). Will also be fixed with next version hopefully :-)
