### ISSUE TITLE
Bug using Normal Mice

### ISSUE THREAD

**Issue by rochakagrawal** [folivoraAI/BetterTouchTool#2416]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead. 

---

#### Description of bug/feature request/question:

When using "Normal Mice" input device

- Trying to configure the scroll up and scroll down button to move "spaces" in Mac
-  if I using the gesture - "Scroll Up", and select settings to activate only when mice is at Menu Bar position,   action attached -> move OSX Space to the left,  IT WORKS
- If use the gesture "Scroll Down", and select settings to activate only when mice is at menu bar position, action attached -> move OSX space to the right, IT WORKS BUT it also disable the normal scroll down action of the mouse.  So I can't scroll down on a webpage for example. Same attain for "scroll up" works perfectly

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Normal Mice

#### Device information:

Type of Mac: MacBook Air, 2013 June
macOS version:  Latest High Sierra 10.13.4
BetterTouchTool version: 2.422

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
I think this should be fixed in the latest version
