### ISSUE TITLE
USB mouse left click stops working

### ISSUE THREAD

**Issue by dsedivec** [folivoraAI/BetterTouchTool#2417]
#### Description of bug/feature request/question:

After some minutes of using a USB mouse on my MacBook Pro, the mouse's left click will stop working until I move or click my Magic Trackpad or quit BTT.

Steps to reproduce:

1. Start BTT
1. Connect USB mouse
1. Go about my usual business (usually web browsing and/or playing games)
1. Wait until left click stops working on the USB mouse (usually happens within thirty minutes, sometimes within two minutes)

When left click stops working on my USB mouse, any of the following things will make it start working again:

* Move the pointer with either my Bluetooth Magic Trackpad or with the built-in trackpad
* "Left" click with either the Magic Trackpad or with the built-in trackpad
* Quit BTT

Doing any of these three things will make the USB mouse left click start working again—for a while.  Eventually (again, say within thirty minutes, and sometimes as quickly as just a couple minutes) it will break again and I will have to repeat this process.

Note that I can still move the mouse cursor with the USB mouse when this happens, I just can't click with it.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

I have experienced this with both a Logitech Anywhere MX and a Razer DeathAdder USB mouse.

#### Device information:

Type of Mac: MacBook Pro Retina 15", late 2013
macOS version: 10.13.4
BetterTouchTool version: BetterTouchTool 2.425

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

Middle and right click on the USB mouse are not affected, they keep working normally.  The USB mouse's scroll wheel keeps working.  BTT button mappings configured for the USB mouse keep working.  Only left clicking on the USB mouse is affected.

I have had this problem with BTT for as long as I can remember, I'd say at least a couple years, including under OS X 10.11 and probably 10.9 before that.

*Possibly* related issues: #191, #625, #810

**Comment by fifafu** [comment]
This issue was moved to https://community.folivora.ai/t/usb-mouse-left-click-stops-working/51

**Comment by dsedivec** [comment]
> This issue was moved to https://community.folivora.ai/t/usb-mouse-left-click-stops-working/51

@fifafu FYI I cannot open that URL.  "Oops! That page doesn’t exist or is private."

**Comment by fifafu** [comment]
Meh sorry, the migration process didn't work correctly :-)
Will leave the issues here for now!
