### ISSUE TITLE
"Move Window to Desktop #" doesn't work across monitor

### ISSUE THREAD

**Issue by sjackwu** [folivoraAI/BetterTouchTool#2419]
#### Description of bug/feature request/question:
The recent release of BetterTouchTool has a new feature "move (active) window to desktop # e.g. desktop 1". It works fine when the "from" and the "to" desktops are in the same monitor. However, if they are in different monitors (e.g. desktop 1 is in the macbook air main display, and desktop 3 is in the external monitor), the action won't work properly.

Follow the example above, say I have Firefox in desktop 1 in main display, the "move window to desktop 3" action will bring desktop 3 to its display (external monitor), but won't bring the Firefox window from desktop 1 to desktop 3.
 
#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
I don't think it's relevant, but since you ask, I assign the action to a keyboard shortcut.

#### Device information:

Type of Mac: Macbook Air (13-inch, early 2014)
macOS version: 10.13.4
BetterTouchTool version: 2.428

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
Workaround: I can use "maximize window to next monitor" afterward. So this is more like a need to update the description of "move window to desktop #" (and in the help files) so that users understand what it does correctly.

**Comment by fifafu** [comment]
Sorry, unfortunately this can't be fixed currently as BTT just reuses the default Apple "Move to Desktop" shortcuts from System Preferences => Keyboard => Shortcuts, which behave the same way. I think Apple has decided different display are completely separated for some reason :-(

Maybe in the future I'll look at the private API that allows to have more control over this, but for now it just uses the Apple Shortcuts.
