### ISSUE TITLE
Inconsistent window maximization when MacOS status-bar is hidden

### ISSUE THREAD

**Issue by SlawaGurevich** [folivoraAI/BetterTouchTool#2420]
Good day to all,

I have notices a strange behavior when maximizing windows either by dragging them to the top edge or using an action (two-finger swipe up in my case on my Magic Mouse) when the status bar on top of the screen is set to hide automatically.

The issue is, that some apps *will* be maximized to the full height of the screen (for example Chrome). Some apps, however, (in my case Postbox) are maximized with a gap for the status bar, even if it is hidden.

MacBook Pro Retina Mid-2012
macOS Sierra 10.12.6
BetterTouchTool version: 2.422

Here is Chrome after maximizing:
![chrome](https://user-images.githubusercontent.com/13917864/38492923-bb381a2c-3bf0-11e8-92c5-952a8899aea7.png)

And here is Postbox after the same action:
![postbox](https://user-images.githubusercontent.com/13917864/38492925-bb567f6c-3bf0-11e8-9746-14b87e02fcb5.png)

Regards
Slawa

**Comment by fifafu** [comment]
unfortunately this is a macOS 10.12.x bug as far as I know.
See #2338

**Comment by SlawaGurevich** [comment]
I see. So macOS is the culprit again.

Would it be an option to include an "Always maximize to full-screen" option? Then you would just need to check the screen's resolution. It could be used as a workaround for this Problem on 10.12 . Maybe even with "Leave space for status bar", since it is always the same height.

Regards
Slawa

**Comment by fifafu** [comment]
Yes, that could work. I'll check!

**Comment by SlawaGurevich** [comment]
Thank you, very appreciated. 👍
