### ISSUE TITLE
Import/export feature so that we can build 'packages' of buttons for others

### ISSUE THREAD

**Issue by lukejagger** [folivoraAI/BetterTouchTool#2421]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead. 

Need an import/export feature so that we can build 'packages' of buttons for others.   Couldn't find a way to backup/save/export in the current version.

It would need to save any Applescript associated with the buttons, along with icons, colours etc.

---

#### Description of bug/feature request/question:
Please only post one bug or feature request per issue.

#### Device information:

Type of Mac:
macOS version: 
BetterTouchTool version: 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
The easiest way to put specific buttons in a new preset that can be exported goes like this:

1. Create a new Preset
2. Make the new Preset the Master Preset
3. Ctrl+C and Ctrl+V the specific buttons you want to have added to that new preset.
4. Export that preset.

I know it's a little overhead, but it works well. Alternatively you can also edit the resulting JSON file in a text editor.

**Comment by OrbitalTech** [comment]
While we're on the topic of exporting/importing. How does <a href="https://chrislennon.github.io/Crypto-Touchbar-App/">this</a> work?

I'm looking at moving my repository of scripts to a website, and I'd like to be able to download my scripts straight into BTT. Ideally, the site would support users adding their own but I'm focusing on just sharing my own scripts at the moment.

**Comment by fifafu** [comment]
I'm currently finishing the site to share presets, but you can definitely create your own also :-)

It works using the custom btt:// url scheme. To import triggers you need to base64 encode the json and pass it like this:

```JavaScript
{
  "BTTGestureNotes" : "Test",
  "BTTTriggerType" : 104,
  "BTTTriggerTypeDescription" : "3 Finger Tap",
  "BTTTriggerClass" : "BTTTriggerTypeTouchpadAll",
  "BTTPredefinedActionType" : -1,
  "BTTPredefinedActionName" : "No Action",
  "BTTShortcutToSend" : "55,0",
  "BTTEnabled" : 1,
  "BTTOrder" : 0
}
```

Becomes

```
ew0KICAiQlRUR2VzdHVyZU5vdGVzIiA6ICJUZXN0IiwNCiAgIkJUVFRyaWdnZXJUeXBlIiA6IDEwNCwNCiAgIkJUVFRyaWdnZXJUeXBlRGVzY3JpcHRpb24iIDogIjMgRmluZ2VyIFRhcCIsDQogICJCVFRUcmlnZ2VyQ2xhc3MiIDogIkJUVFRyaWdnZXJUeXBlVG91Y2hwYWRBbGwiLA0KICAiQlRUUHJlZGVmaW5lZEFjdGlvblR5cGUiIDogLTEsDQogICJCVFRQcmVkZWZpbmVkQWN0aW9uTmFtZSIgOiAiTm8gQWN0aW9uIiwNCiAgIkJUVFNob3J0Y3V0VG9TZW5kIiA6ICI1NSwwIiwNCiAgIkJUVEVuYWJsZWQiIDogMSwNCiAgIkJUVE9yZGVyIiA6IDANCn0=
```

And the url would look like this:
btt://jsonimport/ew0KICAiQlRUR2VzdHVyZU5vdGVzIiA6ICJUZXN0IiwNCiAgIkJUVFRyaWdnZXJUeXBlIiA6IDEwNCwNCiAgIkJUVFRyaWdnZXJUeXBlRGVzY3JpcHRpb24iIDogIjMgRmluZ2VyIFRhcCIsDQogICJCVFRUcmlnZ2VyQ2xhc3MiIDogIkJUVFRyaWdnZXJUeXBlVG91Y2hwYWRBbGwiLA0KICAiQlRUUHJlZGVmaW5lZEFjdGlvblR5cGUiIDogLTEsDQogICJCVFRQcmVkZWZpbmVkQWN0aW9uTmFtZSIgOiAiTm8gQWN0aW9uIiwNCiAgIkJUVFNob3J0Y3V0VG9TZW5kIiA6ICI1NSwwIiwNCiAgIkJUVEVuYWJsZWQiIDogMSwNCiAgIkJUVE9yZGVyIiA6IDANCn0=

It allows single triggers, an array of triggers, a complete app (ctrl+c after clicking on an app in BTT), an array of apps, or a complete preset.

**Comment by OrbitalTech** [comment]
Oh sweet. I'll halt production then. If you ever need a moderator of any kind to help manage so you can focus on BTT, I'm more than happy to help!

You're a big fan of base64 and JSON aren't you?

**Comment by fifafu** [comment]
Very nice! I hope to have it ready by the end of the week. Definitely looking for moderators.
People who post their presets/configs will be able to add documentation in markdown and are free to promote their own projects.
I'm still deciding whether I will review every submission (as they could do bad things when loaded into BTT) or not...

JSON is just the easiest format and can be used natively in JavaScript which will be very useful on the new sharing platform and for some really powerful BTT features I'm currently building :-). Base64 just to prevent encoding problems.

**Comment by OrbitalTech** [comment]
Could a user run `sudo rm -rf /` using the shell widget/applescript do? If so, it might pay to have someone review every submission.

**Comment by ipetraka** [comment]
The described technique of creating a preset and copying and pasting stuff in would be greatly enhanced by adding the capability to select multiple gestures at once! I have many dozens of overrides for one program I'd like to bundle up, and manually copying one at at time is indeed a *bit of overhead*. ;)
