### ISSUE TITLE
Alpha - Applescript Widgets Won't Keep Settings

### ISSUE THREAD

**Issue by ediskrad73** [folivoraAI/BetterTouchTool#2422]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead. 

---

#### Description of bug/feature request/question:
Please only post one bug or feature request per issue.

The Applescript widget will not keep its background settings and returns to the default state.

Default state:

<img width="1085" alt="touch bar shot 2018-04-09 at 8 54 02 am" src="https://user-images.githubusercontent.com/22204514/38498948-187ab32e-3bd4-11e8-8934-9657d704048d.png">

So I'll go into settings and hit save, nothing is changed.

<img width="1015" alt="screen shot 2018-04-09 at 8 54 09 am" src="https://user-images.githubusercontent.com/22204514/38498957-1da2f352-3bd4-11e8-9f38-82079b85b56b.png">

The background will change to black.

<img width="1085" alt="touch bar shot 2018-04-09 at 8 54 13 am" src="https://user-images.githubusercontent.com/22204514/38498964-229e424e-3bd4-11e8-95e8-bd6d0bf71772.png">

But the next time the widget is refreshed (i.e. a new song) it returns back to the default background.

<img width="1085" alt="touch bar shot 2018-04-09 at 8 54 21 am" src="https://user-images.githubusercontent.com/22204514/38498967-27edb310-3bd4-11e8-9d93-a0b32f046967.png">

This only began with the last couple of alpha releases.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

MacBook Pro 2017 15" Touchbar

#### Device information:

Type of Mac: Macbook Pro 2017 15" Touchbar
macOS version: 10.13.5 Beta (17F35e)
BetterTouchTool version: 2.428 (785) Alpha

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Comment by fifafu** [comment]
The current alpha is kind of experimental (but will be quite powerful soon). If possible go back to the stable version for now: https://bettertouchtool.net/releases/btt2.422.zip

**Comment by ediskrad73** [comment]
confirming that this works on the stable release - thank you!
