### ISSUE TITLE
Feature request: Trigger Button refresh after clicking another button in TouchBar

### ISSUE THREAD

**Issue by leipert** [folivoraAI/BetterTouchTool#2423]
#### Description of bug/feature request/question:

I have two buttons in the touchbar:
1. shows the current track and toggles play/pause
2. "next track" button which skips current track (only shown if something is playing)

If I click on "next track", it takes up to 10 seconds to get the current track updated. Is there something I could do to trigger that update? I tried calling the `btt://` url, but it doesn't seem to work...

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

- TouchBar

#### Device information:

Type of Mac: MBP 15" 2017
macOS version: 10.13.4 (17E199)
BetterTouchTool version: 2.424

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

<img width="1085" alt="btt-shot" src="https://user-images.githubusercontent.com/2906107/38500760-a2b5f62a-3c0b-11e8-9da6-1a0a4aacb5d3.png">

**Comment by fifafu** [comment]
It's possible with the new alpha, however I'd recommend to wait until the next alpha version as I'm currently working on the documentation and because I have already renamed some things since the last alpha.
