### ISSUE TITLE
New Buttons Different Default Color

### ISSUE THREAD

**Issue by CarterVE** [folivoraAI/BetterTouchTool#2424]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead. 

---

#### Description of bug/feature request/question:
Please only post one bug or feature request per issue.

I've noticed that recently new buttons I create have a slightly darker color than ones I've previously made. Not only this, but when I try to change the color to match the others with the RGB/Grayscale sliders, the color will change after I click Save. Please fix this, the behavior is so inconsistent I cannot find a simple way around it (ie. just make new buttons X% brighter or something).

Thanks!

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Touch Bar

#### Device information:

Type of Mac: MacBook Pro 15" 2017
macOS version: 10.13.3
BetterTouchTool version: 2.425 (782)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

<img width="1085" alt="touch bar shot 2018-04-09 at 12 42 44 pm" src="https://user-images.githubusercontent.com/18474523/38510829-3429b8b6-3bf4-11e8-90db-ad8fccc96ca6.png">

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Sorry that's a bug in the current alphas, will be fixed with the next update later today or tomorrow. v2.422 should work correctly https://bettertouchtool.net/releases/btt2.422.zip

**Comment by CarterVE** [comment]
Awesome thanks!
