### ISSUE TITLE
Every time I open a window, it gets taller :)

### ISSUE THREAD

**Issue by osmannuriguler** [folivoraAI/BetterTouchTool#2433]
Hello guys,

I have noticed a really interesting bug/issue on my mac. I use "Snap Areas" feature for a long time and I love it. I am having this issue for a week I think. Every time I open a window it gets taller and taller. How is this possible? :) You can see it in the video below. Is there anybody having the same issue because I want to understand if it is causing by BetterTouchTool or the MacOS.

https://www.youtube.com/watch?v=uz_CguVwJ3I

Type of Mac: MacBook Air (13-inch, Mid 2013)
macOS version: 10.13.4
BetterTouchTool version: 2.425

**Comment by osmannuriguler** [comment]
Anyone else? :(

**Comment by fifafu** [comment]
Looks like some sort of weird rounding error. However BTT doesn't interact with a window unless it is currently being snapped, which is why I think this is a macOS bug.
However possibly it's caused by the window resizing API BTT uses.  Unfortunately I can't seem to be able to reproduce it here.

Does it happen when BTT is quit?

Are you using a scaled display resolution?

**Comment by osmannuriguler** [comment]
It is also happening when BTT is not running. I have checked it with some apps (Spotify, Finder, Mail etc.) but this is only happening in Safari.

So I thought for a while and discovered this;

In the view section of the Safari dropdown menu, by default "Show Tab Bar" is checked on my mac. I was keeping it checked to prevent the size of the window changing by itself when I open a new tab.
(Yes I am a little obsessed with symmetry :)

When I uncheck that option and launch the Safari again, BOOM! It fixed!

So, it wasn't even related with BTT. 
It is only an annoying bug in the latest version of High Sierra..

You can close and delete the issue Andreas, thank you!
