### ISSUE TITLE
Feature Request: Application Specific Override of Global Buttons

### ISSUE THREAD

**Issue by Garethp** [folivoraAI/BetterTouchTool#2434]
#### Description of bug/feature request/question:
I think it'd be a good feature to be able to have application specific overrides for global touch items. For example, I've got a touchbar button for Terminal that opens the Terminal Application. However, if I'm *in* Terminal already, I'd like it if I could change it so that the Terminal button opens a new tab or window instead of opening the application, without having to disable global buttons for Terminal and re-add the ones I want to keep.

At the moment I've just changed the button to Open Terminal and *then* press Command+N, but this is sometimes a bit buggy.

#### Device information:
Type of Mac: Macbook Pro 2016
macOS version: 10.13.4
BetterTouchTool version: 2.425

**Comment by fifafu** [comment]
Fow now maybe this option may help:

![image](https://user-images.githubusercontent.com/8820811/38612576-74c91184-3d87-11e8-8ead-0236b364cb3e.png)

**Comment by Garethp** [comment]
Thanks. I looked at that, but I'm not keen at the moment. I'm still trying to decide what my global actions will be, and that means that if I change my global actions I need to remember to change it in Terminal and other Applications that I decide to do something similar (For example, I might want my IDE button to change to a "Run Tests" button).

I may end up doing that for the mean time, but I hope that this feature is something that isn't too hard to implement
