### ISSUE TITLE
Crashing while using external monitor

### ISSUE THREAD

**Issue by richard5150** [folivoraAI/BetterTouchTool#2435]
**Description of bug/feature request/question:**
Better touch tool crashes regularly when snapping and I need to re-open the app. This has been happening for a few months.

**Affected input device:**
Macbook magic trackpad 2

**Device information:**
Type of Mac: MacBook Pro (Retina, 15-inch, Mid 2014)
macOS version: El Capitan
BetterTouchTool version: 2.425

**Comment by fifafu** [comment]
Would be great if you could attach crashlogs from the macOS console app => user reports (if there are any).
However I believe I know the window snapping crash and unfortunately it is a bug in macOS 10.11 which can not be fixed.
