### ISSUE TITLE
"Disable horizontal single finger scrolling" setting has no effect

### ISSUE THREAD

**Issue by polarbreeze** [folivoraAI/BetterTouchTool#2437]
Hi, I am trying to use BTT to disable horizontal single finger scrolling in a particular app, "MuseScore". However, when I select that feature it has no effect. In case it's an issue with that particular app, I tried setting it to disable for "global". That also had no effect. MacBook, High Sierra 10.13.3. Thanks.
![screen shot 2018-04-11 at 17 25 40](https://user-images.githubusercontent.com/26418826/38644334-2b09ed1c-3dae-11e8-9621-d301d2e9fd61.jpg)

**Comment by fifafu** [comment]
Please use the issue template next time.
Which input device are you using? Magic Mouse?

**Comment by polarbreeze** [comment]
OK, sorry, didn't know there was a template to use.
I'm using Magic Mouse.

**Comment by fifafu** [comment]
Thanks, I'll check that tomorrow.

In general this feature has some limitations. It currently only blocks scrolls when they happen while a finger is touching the surface of the Magic Mouse. (it doesn't block momentum scrolls where the finger isn't touching anymore.

**Comment by polarbreeze** [comment]
Oh, it's OK, I thought that simply checking the feature in the list would block single finger scrolling; however it seems I also have to set up the gesture mapping in the other panel. It's working now - and I see what you mean about the momentum scroll not being blocked but that's OK actually.

**Comment by fifafu** [comment]
Ah interesting, what exactly did you need to setup to make it start working?

I'm looking for a solution to the momentum scroll problem with one of the next updates.

**Comment by polarbreeze** [comment]
![screen shot 2018-04-11 at 17 45 34](https://user-images.githubusercontent.com/26418826/38644910-3b0e8e1e-3db0-11e8-97d1-1c9df1339668.jpg)

**Comment by polarbreeze** [comment]
I've disabled inertia scrolling in System Preferences, that took care of it.

**Comment by polarbreeze** [comment]
I don't know if you already have this feature in there but I'd love to have a feature "disable diagonal scrolling" - which means that when I scroll the system will decide whether I meant horizontal or vertical and will only execute one or the other - it will not move diagonally.

**Comment by polarbreeze** [comment]
Hmm, buoyed by my success with Magic Mouse, I tried to set up to disable 2-finger horizontal swipe on my trackpad. It does not seem to have worked - the double swipe still behaves as before and movers the image horizontally on the screen.
![screen shot 2018-04-11 at 17 45 34](https://user-images.githubusercontent.com/26418826/38645716-1154f83a-3db3-11e8-9240-ba32040a9db8.jpg)

**Comment by fifafu** [comment]
Jup, BetterTouchTool can only block single finger scrolling.

(And actually the gestures you added should not be required because they do nothing if you assign "no action". I assume I currently only disable  single finger scrolling if at least one gesture is added, which explains why it started working)

**Comment by polarbreeze** [comment]
Ah, that must be it, thanks!

**Comment by abku** [comment]
Any idea of how to achieve this?

I have set 1 finger swipe left and right to No Action.
The magic mouse still scrolls horizontally and drives me nuts.

I have also tried the option of Scrolling Interia.  This setting disables All scrolling and not just horizontal.  Any other way to achieve this?
