### ISSUE TITLE
Two-stage haptic feedback for Touch Bar button presses

### ISSUE THREAD

**Issue by GoldenChaos** [folivoraAI/BetterTouchTool#2440]
Right now you can have the Taptic Engine fire once when your finger lifts off a button, but it should fire twice: Once when my finger lands on the button, and a second time when it releases. Both haptic events could be customizable the way the current single event is. This would make it consistent with the trackpad and be a better overall haptic experience, I think.

**Comment by amarpatel** [comment]
Haptic would be nice for long presses.  Not sure about release, how would you feel it if your finger is released?

**Comment by GoldenChaos** [comment]
@amarpatel Right now it *only* does haptic on finger release, which is why I'm suggesting adding additional haptic feedback on press as well. It would make them a lot easier to feel.

**Comment by amarpatel** [comment]
@GoldenChaos Yikes, I didn't realize that.  I usually old my buttons down for the repeated triggers.  I'm on board now :)
