### ISSUE TITLE
Script widget no longer appears on latest 2.430b

### ISSUE THREAD

**Issue by cameroncooke** [folivoraAI/BetterTouchTool#2441]
#### Description of bug/feature request/question:

Mute script widget no longer appears on Touch Bar 2.430 beta. The script worked in previous stable release but no longer appears on the Touch Bar.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

MacBook Pro Touch Bar.

#### Device information:

Type of Mac: MacBook Pro (15-inch, 2017)
macOS version: 10.13.4
BetterTouchTool version: 2.430

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

[mute_widget.json.zip](https://github.com/fifafu/BetterTouchTool/files/1904472/mute_widget.json.zip)

[BetterTouchToolDebug.zip](https://github.com/fifafu/BetterTouchTool/files/1904465/BetterTouchToolDebug.zip)

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Could you check if that works with 2.431?

**Comment by cameroncooke** [comment]
On `2.431` the button does appear but it appears incorrectly and the button height is wrong and text is appearing even though the button is set to icon only.

<img width="1085" alt="1" src="https://user-images.githubusercontent.com/630601/38738175-54ead214-3f29-11e8-8ffd-e48b60f743ab.png">

On tapping the button the button state updates the the button looks normal.

<img width="1085" alt="2" src="https://user-images.githubusercontent.com/630601/38738176-550f6eda-3f29-11e8-8cc8-589cea065036.png">

<img width="1085" alt="3" src="https://user-images.githubusercontent.com/630601/38738177-55319aaa-3f29-11e8-9e75-7eb5e2575160.png">

When BTT reloads the button is drawn incorrectly again until it's tapped on. This wasn't happening on the latest stable release version.

**Comment by fifafu** [comment]
Ah that's interesting. Thanks for testing! Will fix it later.

**Comment by fifafu** [comment]
I THINK this should now be fixed in v2.432

**Comment by cameroncooke** [comment]
On further investigation the button height is incorrect until tapped and then it appears correctly. Reloading BTT and then button renders incorrectly again.
