### ISSUE TITLE
Touch Bar Widget for Upcoming Calendar-Events

### ISSUE THREAD

**Issue by HensaHenni** [folivoraAI/BetterTouchTool#2442]
#### Description of feature request:

I'd be awesome if someone could help me out.
I'm trying to create a Touch Bar Widget that shows me the Upcoming Calendar Events. 
Thing is, I'm usually not checking my Calendar-App enough.

There are several widgets that show the Reminders etc. which is not, what I want. 
I want a widget that works with the calendar app.

Is that even possible?  

#### Device information:
Type of Mac: MBP 13-inch, 2017, Touch Bar, 16GB RAM
macOS version: 10.13.4 
BetterTouchTool version: 2.425 (782)

**Comment by OrbitalTech** [comment]
I might look at doing something like this, but for now have a look at the Dictionary for the Calendar app.

You might be able to do something along the lines of,
`description of the first event of the calendar`

Regardless, I'll add it to my personal list of widgets to create and I'll come back here when I finish it.

**Comment by GoldenChaos** [comment]
It would be cool if this BTT widget could get calendar events without needing to open the calendar app. I use Fantastical, so I'd really love to not need to have both open.

**Comment by adambrault** [comment]
@fifafu That would be awesome. Any chance you’ve started this yet?

**Comment by Lubits** [comment]
@fifafu You closed this issue, however, there's no native calendar widget yet as far as I can tell.

Is this still something your planning on implementing?
