### ISSUE TITLE
Feature request: Add option to hide touch bar groups

### ISSUE THREAD

**Issue by ulope** [folivoraAI/BetterTouchTool#2450]
#### Description of feature request:
As far as I can tell there is currently no option to hide the "trigger" button of a button group in the touch bar.
This would however be useful if a button group should only be accessible through another action (e.g. when touching an AppleScript widget).

#### Affected input device:
Touch Bar

#### Device information:

Type of Mac: MBP 15" 2017
macOS version: Sierra 10.12.6
BetterTouchTool version: 2.425

**Comment by fifafu** [comment]
It can be done entering a high enough negative padding value.
But I definitely agree this should be a option!
