### ISSUE TITLE
Copy/Paste Not Working

### ISSUE THREAD

**Issue by CarterVE** [folivoraAI/BetterTouchTool#2452]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead. 

---

#### Description of bug/feature request/question:
Please only post one bug or feature request per issue.

I'm having an issue with copy/paste in BetterTouchTool. I can't seem to copy or paste widgets/buttons in the Touch Bar section, or triggers in the Other section. I also can't copy and paste between presets (not sure if this is due to the same bug or not).

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Touch Bar, Triggers

#### Device information:

Type of Mac: MacBook Pro 15" 2017
macOS version: 10.13.3
BetterTouchTool version: 2.435

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
It seems to work fine here, does it work after restarting BTT?
Do you have a Master Preset selected? (I think there might be a bug where in some situations the master preset can become unselected)

**Comment by CarterVE** [comment]
You're right, I've been switching presets a lot and I think this caused the issue somehow. Restarting BTT fixed it however, sorry I should have tried that before posting!
