### ISSUE TITLE
Custom Tap Sequence: 3 fingers for mouse & trackpads?

### ISSUE THREAD

**Issue by Shnub** [folivoraAI/BetterTouchTool#2453]
#### Description of bug/feature request/question:

Currently the only available Custom Tap Sequence (or the only entry under "Your Own Gestures", for that matter) is using 4 fingers on trackpads. Is it possible to also offer this for 3 fingers only, and especially for the Magic Mouse? This would, first and foremost, enable "1-2-3" taps (left, middle, right, or vice versa), which I think are amongst the easiest and most natural movements for human fingers in general. The Magic Mouse has enough space for three fingers, and I don't see why trackpads should be limited to four fingers only. (In fact, I believe tap sequences more complex than simple left-to-right would be _much_ easier to memorize and execute with three fingers than with four.)

**Comment by fifafu** [comment]
This issue was moved to https://community.folivora.ai/t/custom-tap-sequence-3-fingers-for-mouse-trackpads/16
