### ISSUE TITLE
REQUEST: Bluetooth support for BTT Remote

### ISSUE THREAD

**Issue by Bidulglloq** [folivoraAI/BetterTouchTool#2454]
Want to use **BTT Remote** app on my iPhone to control PPT on my mac, when visiting customers or prospects. 
Means I do not have access to their WiFi network

     ==>  Need **Bluetooth** connection

Thanks

**Comment by ZV95** [comment]
+1 for this, would be a great feature!

**Comment by Askern** [comment]
Yes, yes, yes. Please please please. I know a lot of teachers, who would like to control their PPPs with their iPads or iPhones, resulting in not carrying a pointer (which has to be charged, has to work etc.) in different classes at different schools with no or very bad Internet or no mobile connection at all! I am telling, that this would be a Killer feature resulting buying my colleagues this app only for the bluetooth controlling reason. Also if you should forget all your devices, you still can borrow the iPhone of your student and control your presentation. 
There was the same request 1 year ago and I hope it will be realized soon (https://github.com/folivoraAI/BetterTouchTool/issues/747)

**Comment by fifafu** [comment]
Still working on the bigger BTT Remote update, but it will be included eventually.
Continue here: #747
