### ISSUE TITLE
Idea for cut + paste in Finder

### ISSUE THREAD

**Issue by MHX792** [folivoraAI/BetterTouchTool#2460]
When user presses `CMD+X`, set a bool value, e.g. `shouldMove` to `true`. Then trigger `CMD+C`. The next time the user presses `CMD+V` in Finder trigger `CMD+ALT+V` for moving the item. Then set `shouldMove` to `false`.

Any idea of if BTT is currently capable of this? Or will it be in the future? 
Would be nice to see it!

**Comment by fifafu** [comment]
It's currently not possible, but I will add variables and conditions soon, so it could become possible!
