### ISSUE TITLE
BTT disables 3finger dragging in Logic Pro X

### ISSUE THREAD

**Issue by EdgarRothermich** [folivoraAI/BetterTouchTool#2462]
Anybody using Logic Pro X with BTT?
With the 3-finger drag enabled in the System Preferences, you can move the Volume Faders in Logic with the 3-finger slide. However, if I have a least one Gesture in BTT (not only for the Logic app), that uses three fingers then I cannot slide the faders anymore. I have to use click-drag
I can see that a few gestures have the red warning that you have to disable the three-finger drag, but this happens with most of the three finger (and some four finger) gestures.

Another side effect is even worse. When I have a window (i.e. an open Plugin window) that has two rotary knows, then when changing the value of the first knob (with the three-finger gesture) and then slide over the second knob to change its value, then the value of the first knob goes back to zero. Now I have to use click-drag. This is really bad and makes BTT totally unusable for Logic Pro X.
The interesting thing is that the Volume fader in Pro Tools has no problems with that.

To reproduce that bug, just start with an empty BTT with not Gestures, nothing. If I create the TIpTapMiddle (2 Finger fix) in the Globals setting (not even Logic), then you can experience the bug, Fader not responding, previously updated knob values reset to zero when changing a different knob value

I read a similar post from last October, but my experience is that it never worked and was never fixed. I use BTT for many years now. Any updates on that?

Thanks

[Logic Pro X - BTT Bug.zip](https://github.com/fifafu/BetterTouchTool/files/1917549/Logic.Pro.X.-.BTT.Bug.zip)

**Comment by EdgarRothermich** [comment]
Forgot to mention, I use BTT v2.425

**Comment by EdgarRothermich** [comment]
If you don't have Logic, you can see a similar bu in GarageBand (which has the same code base as Logic Pro). You can download GarageBand for free from the App Store to verify the bug
Attached is a screenshot that shows two areas where the three-finger drag on a slider stopped working once you have once you have just one three finger gesture loaded in a BTT Preset.

<img width="1718" alt="three-finger drag" src="https://user-images.githubusercontent.com/33160708/38886974-5e4f0086-422c-11e8-83d0-4ebc0b3b93c4.png">

**Comment by chrissia33** [comment]
omg....  i stumbled upon your post. previewing for a different issue.  I have been stumped by this since the Logic 10.0.1 update.  or that was my signpost.  i scoured the forums, apple, couldn't get anyone to even admit that three-finger drag would not work on sliders.  I hadn't even remotely considered BTT to be the culprit.  I hadn't been using BTT too much in Logic for this reason.  And I have been confounded by the no three finger drag.  Thank you......

**Comment by fifafu** [comment]
Could you check if enabling three finger drag optimizations fixes this?
![image](https://user-images.githubusercontent.com/8820811/38985922-114b33d6-43cb-11e8-9e91-f982a3f0ae41.png)

**Comment by EdgarRothermich** [comment]
Andreas, sorry for the late response but I was busy producing a YouTube video about the Trackpad, where I also praised your BTT app (https://youtu.be/CtvZN2EyTAc @20:41).

The suggestion with the settings works. Now I can use the 3-finger drag to slide the fader in Logic. However, this setting has a bad side effect, because now other three finger gestures don't work. TipTapRight (2 Fingers fixed), TipTapLeft (2 FIngers fixed), TipTapMiddle (2 FIngers fixed).

Currently at v2.467

**Comment by fifafu** [comment]
unfortunately this is not fixable.
The three finger drag is a very problematic gesture as it changes the basic behavior of the trackpad (which is why apple has hidden it in the accessibility options). In general I recommend to use double tap to drag instead.
