### ISSUE TITLE
"Custom Click Shift+click" action broken in 2.425?

### ISSUE THREAD

**Issue by EdgarRothermich** [folivoraAI/BetterTouchTool#2463]
The "Custom Click Shift+click" action is broken in the latest BTT version 2.425.
I used this action, which worked fine in 4.313 and I can verify that when switching between the two versions. One is working, the other on his not


<img width="836" alt="custom click action" src="https://user-images.githubusercontent.com/33160708/38839835-6ac3c720-4191-11e8-8281-78ca9071a026.png">

#### Affected input device:
Trackpad

#### Device information:

Type of Mac: iMac 2017
macOS version: 10.12
BetterTouchTool version:

**Comment by fifafu** [comment]
Weird, this seems to work fine here (I don't have logic pro, but in the other apps I tested it worked).
Have you tried to delete the action and add it again? Maybe I accidentally broke some config or something  like that.

**Comment by EdgarRothermich** [comment]
Yes, I tried it numerous times. Assigned different gestures. Same behavior on my iMac and MacBook.
I don't know if it has something to do with Logic Pro, which has major problems with BTT (see my other posts). However, this action worked in Logic in the previous BTT build.
