### ISSUE TITLE
Disable escape on touch pad and remap to tilde 

### ISSUE THREAD

**Issue by PeterKindfield** [folivoraAI/BetterTouchTool#2464]
#### Description of bug/feature request/question:
I have set Touch Bar action name escape to no action and created a shortcut for shift-` to map to escape but the touchbar escape still operates.

#### Affected input device
MacBook Touch Bar

#### Device information:

Type of Mac: MacBook Pro (15 inch, 2017)
macOS version: 10.13.4
BetterTouchTool version: 2.425 (782)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
I will be very 😆 to buy BTT if I can get it to disable the Touch Bar escape which renders my Mac almost useless to me because It is right where I habitually rest my pinky 😒

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
The only way to get rid of the esc button is to completely replace the touch bar with a custom one.
To achieve this, go to the general touch bar settings in BetterTouchTool and disable "Show macOS Control Strip"

![image](https://user-images.githubusercontent.com/8820811/38878180-a57d0dfc-4260-11e8-8c8d-abe19fc89137.png)

Afterwards you can add your custom buttons, sliders and widgets to the Touch Bar.

**Comment by PeterKindfield** [comment]
Thanks so much…. I remember reading that somewhere… brain fart… will order at end of trial… a life (or at least work) saver for me!

Peter Kindfield
Former Directory of Educational Services, NeXT Inc.
Current Principal, The Farm School

**Comment by PeterKindfield** [comment]
I have unchecked Show macOS Control Strip but the control strip still shows and the darn escape function still “works”

**Comment by PeterKindfield** [comment]
Hey Andreas,

I still can’t get this to work.

Is BTT yours?

If you give me specific barebones instructions on how to disable the touchbar escape and leave the rest of the Touchbar as is by replacing it with a custom bar minus the scape key, I will be happy to write it up for you for use by others (In used to be in charge of user education and docs at NeXT).

Peace,

—Peter

**Comment by fifafu** [comment]
You need to configure at least one button in BTT for it's touch bar to show up by default.
You could force it to show an empty touch bar by creating a keyboard shortcut in BTT and assigning "Toggle BTT Touch Bar"

But most of the time it makes sense to configure some buttons in BTT.

**Comment by PeterKindfield** [comment]
Thanks! That helps. My problem is that I constantly hit that  leftmost spot on the touchbar with my pinky. Can I shift my new google BTT Touchbar button to the right some?

**Comment by fifafu** [comment]
Currently the only option to do that is create a button which comes before the google button and make it black (invisible).

**Comment by PeterKindfield** [comment]
Cool. I’ll try that.

**Comment by PeterKindfield** [comment]
Sweet. I made it black and named it a bunch of spaces. Got me what I wanted.
