### ISSUE TITLE
add "Drag" or "hold down left mouse button" as a predefined action

### ISSUE THREAD

**Issue by stutterrrrer** [folivoraAI/BetterTouchTool#2469]
Is that possible?
I wish to have a shortcut that functions as:

"hold down left mouse button"
"move mouse to ..."
"lift left mouse button"

to realize dragging with keyboard.

**Comment by waxfingers** [comment]
change "y" key for what you want =)

![drag_btt_web](https://user-images.githubusercontent.com/13238340/38887210-186a0748-4270-11e8-8f3c-2fb5028d16cf.jpg)

**Comment by stutterrrrer** [comment]
thank you so much, didn't know BTT could do that.
But it turns out the "move mouse to position" action can't be used for dragging, I'm guessing it's because the mouse movement is not continuous.
Nevertheless, thanks a bunch, I'm sure this feature would come in handy soon.

**Comment by waxfingers** [comment]
> But it turns out the "move mouse to position" action can't be used for dragging

You sure...? 'Cause if I add a *move mouse to X Y position* to the first shortcut in the above example, and I am, say, on a Finder's window it would do exactly that, hold the window and drag it to coordinates' position (as long as you hold the "y").
