### ISSUE TITLE
Ability to only show global touch bar buttons only on demand

### ISSUE THREAD

**Issue by matrosovas** [folivoraAI/BetterTouchTool#247]
#### Description of your bug/question/feature request...:
Currently I have a set up where global buttons launch specific scripts. The problem is though that I had to go through every app and add per app setting so that default view would be app touch bar configuration(except a few exceptions). I would love it if I could just get to global view on demand rather than having it by default. This also causes an issue when apps like 1password pop fingerprint request and it gets hidden behind global buttons. 

Another thing that should be implemented is to revert to correct state of the touch bar after global button view is toggled off(revert to either per app touch bar view or the default app view based on which state we came from)

**What kind of Mac are you using?**
15' 2016 TB

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
Touch Bar

**Which versions of macOS and BetterTouchTool are you running?**
1.985

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)
Add ability to have global buttons only show on demand.

**Comment by fifafu** [comment]
I think it is already like that.
If you press the BTT icon in the Control Strip the BetterTouchTool Touch Bar will stay hidden until you press that button again (unless you have app-specific visibility overrides).

**Comment by matrosovas** [comment]
You're right, the issue was that I have BTT icon hidden and for some reason it decided to always be on and I could not figure a way out to have it off by default. Thanks!

**Comment by matrosovas** [comment]
What about adding an option to only toggle touch bar for specific app? The thing is that I have BTT button hodden and if I trigger buttons to show I usually just want that happening for one app, but this forces global actions to show on every app without predefined actions untill I toggle it off.

**Comment by fifafu** [comment]
When clicking the "App-specific" button below the app list in BTT you can set touchb ar options for specific apps.

**Comment by matrosovas** [comment]
Tried that. If I go to lets say safari and toggle btt menu and do a custom shortcut, it automatically show global btt buttons for all other apps once I switch to them(they need to not have any specific rules defined) and this causes the bug defined in the first comment. I do the btt menu toggling via assigning toggle action to keyboard shortcut if that helps. My understanding is that if I toggle btt menu on one app it should not automatically show global buttons for all other apps if that is not defined specifically.

**Comment by fifafu** [comment]
That's intended, if you press the BTT button the Touch Bar will stay open until you press it again. You shouldn't add global buttons if you only want to show them for specific apps.

See this screenshot for toggling BTT Touch Bar: 
![image](https://cloud.githubusercontent.com/assets/8820811/21994486/3cacc79c-dc20-11e6-9d3a-3a1818b55805.png)

**Comment by matrosovas** [comment]
i have no issue with global button toggling and it works as expected. After reading your answers I just realised that after I toggle btt bar for an app it stays on for all apps. Would be nice to be able to only toggle btt bar for only the specific app rather that having it on by default for all apps after toggling on. Just a suggestion for my specific scenario :)

**Comment by fifafu** [comment]
Ok, I think could add an option "Automatically close BetterTouchTool Touch Bar after switching apps"

**Comment by matrosovas** [comment]
Unless the app has specified that it needs to show BTT by default, this would actually be awesome!

**Comment by NoPinHD** [comment]
May I ask is this feature "Automatically close BetterTouchTool Touch Bar after switching apps" has some progress now? Thanks.
