### ISSUE TITLE
keyboard shortcuts in 441

### ISSUE THREAD

**Issue by fortunesfavorite** [folivoraAI/BetterTouchTool#2473]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead. 

---

#### Description of bug/feature request/question:  Keyboard shortcuts no longer work.
Please only post one bug or feature request per issue.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

 keyboard

#### Device information:

Type of Mac: MacBook Pro 15 inch late 2013
macOS version:  10.13.4
BetterTouchTool version: 2.441

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

<img width="1440" alt="btt" src="https://user-images.githubusercontent.com/38477287/38898915-3832891c-424b-11e8-80ef-9d9f3b1aca84.png">

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
I think v 2.441 was buggy in a few ways. This should all be fixed in more recent versions.
