### ISSUE TITLE
AppleScript Widget not running on appear in 2.441 anymore

### ISSUE THREAD

**Issue by SenshiSentou** [folivoraAI/BetterTouchTool#2474]
#### Description of bug/feature request/question:
I'm using a "Run AppleScript and Show Return Value" widget set on my touch bar, set to run every 5 seconds (specifically, Spotify's current track name). I also have a hotkey assigned to switch between different presets. There was a notable change in behaviour here:

- A few versions ago, whenever the preset with this widget was brought up the script would run after a miniscule delay before refreshing ±2-3 times, showing a few artifacts in the process. No biggie.
- One version ago it worked *perfectly*. I would bring up the preset and the text would refresh instantly, and only once. No delays, no artifacts.
- In the current version, I will bring up the preset and the script won't execute until 5 seconds (the widget's refresh rate) have passed. This is not desirable in this case.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Touch Bar

#### Device information:

Type of Mac: MacBook Pro 15", 2017
macOS version: MacOS 10.12.6
BetterTouchTool version: 2.441 (802)

**Comment by fifafu** [comment]
Could you check whether this version fixes your issue? https://bettertouchtool.net/releases/btt2.442.zip

**Comment by fifafu** [comment]
Sorry, had to change this again as it's not always wanted to have it that way.
https://bettertouchtool.net/releases/btt2.442b.zip

I added an option now:
(Run on becoming visible)

![image](https://user-images.githubusercontent.com/8820811/38914075-5a41be04-42de-11e8-8647-5e1423df74fe.png)

**Comment by SenshiSentou** [comment]
Yup, works like a charm! I did notice a small delay again, but that's totally fine. Thanks for the option!
