### ISSUE TITLE
Zooming everything on screen!?!?

### ISSUE THREAD

**Issue by 00998878** [folivoraAI/BetterTouchTool#2475]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead. 

---

#### Description of bug/feature request/question: I don’t believe this is a bug and is rather a purposeful feature that is useless and extremely annoying! When I am scrolling a single page, using the app, there are times that it thinks I want to zoom in, but it doesn’t just zoom the page I’m on it zooms in the entire computer screen. This is a completely useless feature and I feel like it adds drag to scrolling since it has to decide if its scrolling or zooming the whole dang screen. If anything please make it so I can disable that zoom. Was this zoom “feature” even intentional by zooming the whole screen. Since most, if not all, zoom features I have ever used only zooms in on the page or picture that is currently active?? Please fix this or help me disable it because this happens all the time, even when I’m concentrating on keeping my fingers nice and vertical while scrolling since I know if they go even the slightest bit horizontal it zooms the whole screen. Thanks for you time. Please, make your product Great again! 
 
Please only post one bug or feature request per issue.

#### Device information:

Type of Mac:
macOS version: 
BetterTouchTool version: 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
This is a macOS feature you probably have activated in system preferences -> Accessibility

It's called display zoom or something like that.

In case you are talking about btt remote, you can disable zooming in its preferences.
