### ISSUE TITLE
[Bug] After most recent update: "no multitouch capable trackpad found"

### ISSUE THREAD

**Issue by Olivertubs** [folivoraAI/BetterTouchTool#2477]
#### Description of bug/feature request/question:
After skipping several version because I was scared that it will break BBT, I finally decided to install the newest update, which broke BTT.

There is not much more to say. After installing it, I get the notification "no multitouch capable trackpad found. That's it. No gestures work anymore. 

Restarting my machine did not help. 

#### Device information:

Type of Mac: Macbook Pro (13 inch, Mid 2010)
macOS version: Sierra (10.12.6 (16G1114))
BetterTouchTool version: 2.313 or 2.441 (See edit below!)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
None

Is there any workaround? If not, is there an older version that I can install? My productivity went down by like 20% since BTT stopped working.

edit: On the "About" site, it says BTT Version 2.313, while in the "Check for Updates" popup, it says "You're up to date! BetterTouchTool 2.441 is currently the newest version available"

**Comment by fifafu** [comment]
Huh something seems to be broken there.
Could you try to download the new version manually from my website https://folivora.ai/downloads?

Maybe the auto updater could not update correctly for some reason.

**Comment by Olivertubs** [comment]
Yes that worked, but only after I also deleted the files in:

    ~/Library/Application Support/BetterTouchTool
    ~/Library/Preferences/com.hegenberg.BetterTouchTool.plist

Thanks!

**Comment by Olivertubs** [comment]
I have to reopen it. 

It seems to be a license problem. Everything worked properly, until it asked for a license and I imported my (legitimately bought) license file. 

After that, I got the message "no multitouch capable trackpad found" again. And it still shows that I have a trial verion, altough the license file was imported successfully.

**Comment by fifafu** [comment]
could you check this version, I think there may have been an issue that caused the license eligibility check to fail on some systems and not display the correct notification before/after updating: https://bettertouchtool.net/releases/btt2.444b.zip

Note: BetterTouchTool licenses receive free updates for two years. Afterwards the last version you received in that timeframe can still be used forever. Possibly your license is older than two years (however BTT should show a message to you about it).

If 2.444 doesn't work, try this: https://bettertouchtool.net/releases/btt2.426_recovery.zip
It's the last version covered by licenses bought more than two years ago.

Best,
Andreas

**Comment by Olivertubs** [comment]
Hi, my license was indeed older than 2 years old. I never got a notification about it though. 

I bought new one, definitely worth it! :) Awesome app!

I downloaded the version you linked and it shows the window "your licence is too old [...] three options: buy new licence, downgrade, trial" 

The funny thing is: There is no way to import a new license at that point haha. After I bought the new license, I would have had to downgrade BTT, import my license and then update again. Instead I replaced the .bettlicense file in the BTT directory with my new licence file, but that shouldn't be the way to go haha

Best, 
Oliver

**Comment by rafabenavente** [comment]
Hi,
I had the same issue, and again was related to having a too old licence.
Solution? I also chose to renew it. Excellent app, really worth it.
Regards from Chile,
Rafa

**Comment by kenmhaggerty** [comment]
Hi — Having this issue as well but I am on a lifetime license on version 2.636. Please let me know what info I can provide to help debug. For me I am setting up a new machine from a Time Machine backup. BTT seems to be working fine on my other devices.
