### ISSUE TITLE
Crash App when trying checking regular update

### ISSUE THREAD

**Issue by pelennor** [folivoraAI/BetterTouchTool#2478]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead. 

---

#### Description of bug/feature request/question:
Please only post one bug or feature request per issue.

When I try checking for regular updates on menu bar, btt crashes and restarts.
I attach debug info.

#### Device information:

Type of Mac: MacBook Pro (15", 2017)
macOS version: 10.13.4
BetterTouchTool version: 2.425

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
[BetterTouchToolDebug.zip](https://github.com/fifafu/BetterTouchTool/files/1922256/BetterTouchToolDebug.zip)

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.
[BetterTouchTool_2018-04-18-112342_Sangminui-MacBook-Pro.zip](https://github.com/fifafu/BetterTouchTool/files/1922260/BetterTouchTool_2018-04-18-112342_Sangminui-MacBook-Pro.zip)

**Comment by fifafu** [comment]
Unfortunately I think you may need to upgrade manually via https://folivora.ai/downloads 

I have had one similar report recently but haven't been able to find the cause. I think it might be a weird issue in 2.425 that luckily  only affects very few users.
