### ISSUE TITLE
Recover settings when switching to Setapp

### ISSUE THREAD

**Issue by eurobubba** [folivoraAI/BetterTouchTool#2484]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead. 

---

#### Description of bug/feature request/question:
Since I'm a Setapp subscriber, I switched to the Setapp version of BTT when I received a license renewal notice. However I seem to have lost all my old settings. Can I get them back, other than by recreating them manually?

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Trackpad, keyboard

#### Device information:

Type of Mac: MacBook Pro 2011
macOS version: 10.13.4
BetterTouchTool version: 2.441|801 (Setapp)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Hi!

You should be able to rename the ~/Library/Preferences/com.hegenberg.BetterTouchTool.plist to ~/Library/Preferences/com.hegenberg.bettertouchtool-setapp.plist (delete the existing setapp one before doing that and make sure BTT is quit)

Best,
Andreas

**Comment by ferra-andre** [comment]
Hi @fifafu,
and for the usage log?

**Comment by fifafu** [comment]
that is included in the plist so if you rename the old plist to the com.hegenberg.bettertouchtool-setapp.plist it will have the usage log.

**Comment by ferra-andre** [comment]
it does not seem to work, it starts from scratch.
thanks

**Comment by fifafu** [comment]
mh it definitely should.
Maybe try com.hegenberg.BetterTouchTool-Setapp.plist as name
