### ISSUE TITLE
Hidden Touch Bar widgets still have space after widget

### ISSUE THREAD

**Issue by GoldenChaos** [folivoraAI/BetterTouchTool#2487]
#### Description of bug/feature request/question:
Not sure if this is an intentional behavior or not, but hidden touch bar widgets with space added after them will not hide the extra space, not matter what. This leads to inconsistent padding between widgets depending on what apps are open, which is mildly irritating. If a widget is configured and returns "", the user-configured space after the widget should also not be displayed.

#### Device information:

Type of Mac: MBP 15" 2016
macOS version: 10.13.5 Beta
BetterTouchTool version: 2.443

**Comment by fifafu** [comment]
Thanks for reporting, I'll fix that with the next update (alpha probably tomorrow).

**Comment by GoldenChaos** [comment]
This is still unfixed in the latest alpha. Is a fix for this still planned?
