### ISSUE TITLE
Keyboard shortcuts not working when old keyboard implementation is active

### ISSUE THREAD

**Issue by johnpane** [folivoraAI/BetterTouchTool#2488]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead. 

---

#### Description of bug/feature request/question:

I have the up-arrow and down-arrow mapped as shown here.

<img width="1012" alt="screen shot 2018-04-18 at 15 08 39" src="https://user-images.githubusercontent.com/14841761/38960791-c3897654-431a-11e8-8efa-f2c5cd597cd9.png">

This has stopped working under the old keyboard implementation, which I have seen activated by Safari. The keystrokes are not remapped while the old keyboard implementation is in effect.

It works fine under the "new" keyboard implementation. 

Prior to the existence of the new keyboard implementation (i.e., when the keyboard implementation was old), this worked fine for a very long time.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
MacBook Pro, built-in keyboard

#### Device information:

Type of Mac: MacBook Pro (15-inch, Late 2016)
macOS version: 10.13.4
BetterTouchTool version: 2.443 (805)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

It is set to "automatically" switch to the old keyboard implementation.

<img width="1008" alt="screen shot 2018-04-18 at 15 09 25" src="https://user-images.githubusercontent.com/14841761/38961008-66c5458c-431b-11e8-8518-7b8cd0e7a122.png">

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by johnpane** [comment]
These keyboard mappings also do not work when the "old keyboard implementation" is active.

<img width="1016" alt="screen shot 2018-05-17 at 06 37 01" src="https://user-images.githubusercontent.com/14841761/40172546-dee24e10-599c-11e8-8da0-5373b2a52495.png">

**Comment by fifafu** [comment]
Have you enabled "prevent recursive triggers" in the settings for these shortcuts? Otherwise they will just trigger themselves again and again and crash BTT.

**Comment by johnpane** [comment]
No, that is not necessary. We corresponded about this a long time ago. The trigger is an extended keyboard input and the remapped key is on the main number row above the letters. This has worked for many years and is not the reason for the current issue (as evidenced by my earlier report).

**Comment by johnpane** [comment]
It seems like a flag can get stuck in the OS, keeping the "old keyboard implementation" active even if I restart BTT. It blamed it on Mail.app, so I quit that and then it blamed it on Finder. I had to reboot to get BTT to go back to using its newer keyboard implementation.

**Comment by fifafu** [comment]
Could you try if the shortcuts work if you re-record the arrow & extended keyboard inputs? It is possible that the old version didn't record everything that is now necessary to reliably recognize the key.

**Comment by johnpane** [comment]
I can try that. Would that also explain the issue I first posted here last month? These were all recorded under the old implementation and now work fine under the new implementation.

Our original discussion of the numeric keypad remapping was in #468

**Comment by fifafu** [comment]
Yes, that should solve this too.
I think the problem may be with "implicit" function keys. For example arrow keys always implicitly press the FN key automatically and this may also be the case for your other keys. There may have been a problem when migrating these to the new data model ;-(

**Comment by johnpane** [comment]
I re-recorded them and they now work when I manually set "Always use old keyboard shortcut implementation" and when that is not set. I'll let you know if there are any further problems with this when the old method is invoked automatically.
