### ISSUE TITLE
Exported Presets Icon Dimensions Change

### ISSUE THREAD

**Issue by CarterVE** [folivoraAI/BetterTouchTool#2489]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead. 

---

#### Description of bug/feature request/question:
Please only post one bug or feature request per issue.

After exporting a preset, when I re-import it the icons' dimensions are all smaller/changed. This happens whether the preset has been compressed or not.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Touch Bar

#### Device information:

Type of Mac: MacBook Pro 15" 2017
macOS version: 10.13.3
BetterTouchTool version: 2.443

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

<img width="1085" alt="touch bar shot 2018-04-18 at 11 24 15 pm" src="https://user-images.githubusercontent.com/18474523/38969763-e18e2740-435f-11e8-8145-2f4170d8d06f.png">

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Thanks for reporting! WIll be fixed with the next update.

**Comment by fifafu** [comment]
Should be working correctly again in the latest alpha version
