### ISSUE TITLE
Move a full-screen window one space to the left/right

### ISSUE THREAD

**Issue by stutterrrrer** [folivoraAI/BetterTouchTool#2493]
The 
move window to next space/ previous space
action doesn't work with full screen apps.
Is it possible to move a full-screen window with a shortcut?

the full screen windows always open at the rightmost space and I have a habit of moving them to the right of the first desktop.

**Comment by oliviermattelaer** [comment]
Hi,

I think that you can do that via an applescript. 
Looks like the following thread is doing something around those lines.
https://stackoverflow.com/questions/48197607/applescript-fullscreen-app-and-arrange-order-in-high-sierra
