### ISSUE TITLE
Move window one space to left/right not working at all

### ISSUE THREAD

**Issue by rainerhind** [folivoraAI/BetterTouchTool#2495]
#### Description of bug/feature request/question:
After assigning a keyboard shortcut for move window one space/desktop to right/left, neither works at all. The mouse moves to the top of the window as expected, but the window doesn't move. This is for fullscreen and regular windows.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Macbook Pro 2012 internal keyboard and external Magic Keyboard 2.

#### Device information:
Type of Mac: MBP 2012 15" non-retina
macOS version: 10.12.6
BetterTouchTool version: 2.443

**Comment by fifafu** [comment]
This only works if you have multiple spaces open.

**Comment by rainer-uoy** [comment]
So my use case is that I have 2 monitors, with a space/desktop on each.

I've just added multiple spaces to a single screen, and the keyboard shortcut does allow me to move windows across the screens on that single monitor. 

However, moving a window from a space on one monitor to another monitor doesn't work.

I'm fairly sure this used to work, and since the action is called "Move window one space/**desktop**" I'd assume it is supposed to support that?

Thanks for the support!

**Comment by rainerhind** [comment]
(Apologies, used wrong account for prev. comment)


So my use case is that I have 2 monitors, with a space/desktop on each.

I've just added multiple spaces to a single screen, and the keyboard shortcut does allow me to move windows across the screens on that single monitor.

However, moving a window from a space on one monitor to another monitor doesn't work.

I'm fairly sure this used to work, and since the action is called "Move window one space/desktop" I'd assume it is supposed to support that?

Thanks for the support!

EDIT: Also, "Move window to desktop X" doesn't work unless the desktop is on the same monitor it seems

**Comment by fifafu** [comment]
BTT just calls the shortcuts from System Preferences => Keyboard => Shortcuts. If they don't support that BTT also doesn't ;-(

**Comment by rainerhind** [comment]
How does that work if there's no shortcut for moving the window in OSX prefs?

And am I wrong in thinking it used to be possible to move windows across screens?

Thanks

**Comment by fifafu** [comment]
Yup, there hasn't been a change to that. Maybe it's the "Displays Have Separate SPaces" setting in the macOS preferences that causes issues.

It works like this:
Usually if you click the titlebar of a window and press the shortcut from System Preferences => Keyboards => Shortcuts, it moves the window to the space defined by the shortcut.
BTT just clicks the titlebar, then calls the shortcut.
