### ISSUE TITLE
Silent Crash

### ISSUE THREAD

**Issue by macMikey** [folivoraAI/BetterTouchTool#2496]
#### Description of bug/feature request/question:
BTT is silently quitting/crashing.  When I expect custom touchbar buttons, they don't appear, then when I look in the menu, BTT's icon is gone.  I relaunch at that point.

#### Device information:

Type of Mac: MBP 2017
macOS version: 10.13.4
BetterTouchTool version: 2.422 (779)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by ZV95** [comment]
I will note that I also have this issue from time to time and notice it when my keyboard shortcuts stop working. 

Current BTT: 2.444 (806) (Has only occurred in previous versions at this time)
iMac (Retina 5K, 27-inch, 2017) 
10.13.4 (17E199)
