### ISSUE TITLE
WebView cannot show in full screen app

### ISSUE THREAD

**Issue by shimj** [folivoraAI/BetterTouchTool#2498]
WebView cannot show in full screen app
Is it impossible to be implemented or a bug?

**Comment by fifafu** [comment]
Ah I think I can add this with the next update. (I'm not using full screen apps often thus I didn't test it).

**Comment by fifafu** [comment]
If you want you can try this build: https://bettertouchtool.net/releases/btt2.445.zip I think it should now work in full screen apps

**Comment by shimj** [comment]
It works! Thanks a lot!

**Comment by oliviermattelaer** [comment]
On the same topic, your tutorial (the triple finger click one) does not trigger on full screen app.
I have a feeling that this is an apple limitation but I'm asking anyway.

By the way, thanks a lot for this amazing tutorial/ new version. This is a game changer.

**Comment by oliviermattelaer** [comment]
Just to point out, that it is quite simple to include any html inside the dashboard and that one is working even for fullscreen app. So I use that trick to have it working (up to the fact that is position is predefined in the dashboard view) for full screen app.
