### ISSUE TITLE
Changed behaviour with VirtualBox client

### ISSUE THREAD

**Issue by gkholman** [folivoraAI/BetterTouchTool#2499]
#### Description of bug/feature request/question:
A recent update to BetterTouchTool a few weeks ago has changed the behaviour with VirtualBox, and I tried to live with it but it is really irritating.  I run VirtualBox on my MacBook with a Windows 10 guest.

There is a keystroke in the VirtualBox client that, when pressed while in the guest environment, it escapes the keyboard so that I can use "Alt-Tab" to move to another application in my Mac environment. That still works.

However, before the BetterTouchTool update, BetterTouchTool would intercept my keyboard shortcuts upon pressing the escape key and give me the Mac application that I desire.

Since the BetterTouchTool update, after pressing the escape key, my keyboard shortcut is passed to the VirtualBox client and is not interpreted by BetterTouchTool to go to my Mac application.

I now have to both escape and press Alt-Tab to a Mac app before my BetterTouchTool keyboard shortcut is recognized.  It is doable, but it is really irritating now since it was seamless before.

#### Device information:

Type of Mac: MacBook 2015
macOS version: 10.13.4
BetterTouchTool version: 2.444

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by gkholman** [comment]
Thank you for the very prompt response, but it appears not to have addressed the issue.  Even after restarting BetterTouchTool the keystrokes after escaping VirtualBox are going back to VirtualBox.  Only Alt-Tab gets me away from VirtualBox, after which everything works as expected.

Thank you, again.

**Comment by fifafu** [comment]
You are sure the old keyboard shortcut implementation is checked?

Weird, maybe there was an update for virtual box and it now intercepts at an even deeper level?

Maybe also try to uncheck and re-enable BTT in System Preferences -> Security and Privacy -> Privacy -> Accessibility

**Comment by gkholman** [comment]
I appreciate your patience in trying to fix this so promptly.  Virtual box was not updated at the time, though BTT was.  Then last week I thought perhaps buying the perpetual license might engage some special behaviours, but it makes sense that it did not. Also the suggested accessibility toggle appears not to have changed anything.

![screen shot 2018-04-19 at 15 46 35](https://user-images.githubusercontent.com/1319773/39014901-a3f6f7b0-43e9-11e8-8474-8933f8afab40.png)

Please do not take any more time now if you could just keep it in the back of your mind. I can live without the old behaviour, it is just irritating.

Thank you, again!  . . . . . . . . Ken
