### ISSUE TITLE
App specific keyboard settings not working after mac screen lock

### ISSUE THREAD

**Issue by moonsign** [folivoraAI/BetterTouchTool#2502]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead. 

---

#### Description of bug/feature request/question:
Please only post one bug or feature request per issue.

#### Device information:

Type of Mac: Macbook Air mid 2013
macOS version: 10.13.4
BetterTouchTool version: 2.443(805)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

I found this issue after upgrading to 2.4 ( with release note "complete rewrite keyboard function" after downgrade to 2.3x, the app specific keyboard shortcut is work again.

I have several global keyboard shortcut settings ( as below)
![image](https://user-images.githubusercontent.com/29362054/39029682-ad85fa78-448f-11e8-9b63-c991c771c29c.png)

 I don't want it to conflict with eclipse hot keys, so I created the same shortcut setting in eclipse app specific settings and uncheck the "enabled" (as below) 
![image](https://user-images.githubusercontent.com/29362054/39029695-bedb859a-448f-11e8-8816-15156410a236.png)

At first it works fine, but once I wake up my mac from a locked screen it's not working, and when I restart BTT from the dropdown menu, it worked again.

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
This issue was moved to https://community.folivora.ai/t/app-specific-keyboard-settings-not-working-after-mac-screen-lock/23

**Comment by fifafu** [comment]
Sorry, please ignore the previous message. The migration didn't work correctly, for now the issues will stay here.
