### ISSUE TITLE
[Feature request] Refresh HTML when the webview was triggered

### ISSUE THREAD

**Issue by shimj** [folivoraAI/BetterTouchTool#2504]
#### Feature request:
refresh HTML from local file when the webview triggered.

I want to look up the meaning of a word by first generating an HTML file and then show it with webview.

**Comment by fifafu** [comment]
You could do it using the BTTInitialize() function

Just put a script tag in your HTML:
```HTML
<script>
 function BTTInitialize() {
            setTimeout(() => {
              window.location = 'file://theAbsolutePath/toYour/createdFile.html'
            }, 500);
        }
</script>
```

**Comment by shimj** [comment]
It's amazing. However, it causes continuous flashing... It reloads every 500ms

**Comment by fifafu** [comment]
You could add a check for a specific html element with a specific id and only do the timeout then. Like this:


```HTML
<script>
 function BTTInitialize() {
var elementExists = !!document.getElementById("theIdOfSomeElement");

if(!elementExists) {
            setTimeout(() => {
              window.location = 'file:///theAbsolutePath/toYour/createdFile.html'
            }, 500);
        }
}
</script>
```

Your generated html must then include some element with that id.
```HTML
<div id="theId"></div>

**Comment by fifafu** [comment]
And you may need to add another function that removes the element when closing the menu

Like this:
```HTML
<script>
 
    function BTTWillCloseWindow() {
          var elem = document.getElementById("theIdOfSomeElement");
          return elem.parentNode.removeChild(elem);
     }
</script>
```

**Comment by shimj** [comment]
Really thanks for your detailed answer! It does solve my problem!
