### ISSUE TITLE
[Feature Request] Button swaps

### ISSUE THREAD

**Issue by dzeruel** [folivoraAI/BetterTouchTool#2505]
#### Description of feature request/question:
Hello!
It would be nice if the app could handle "button swaps". 
For example:
I would like to map:
A key to B key
and
B key to A key.

Currently the app goes into an infinite loop and crashes. 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
MacBook

#### Device information:
Type of Mac: MacBook Pro (Retina, 13-inch, Early 2015)
macOS version: 10.13.4 (17E199)
BetterTouchTool version: 2.426

**Comment by fifafu** [comment]
You can check "prevent recursive triggers"

![image](https://user-images.githubusercontent.com/8820811/39052476-653124f6-44ac-11e8-87ca-f70de7931761.png)

However it is not recommended to do such remapping in BTT.
Apple has a little command line utility that can remap keys very performantly
https://developer.apple.com/library/content/technotes/tn2450/_index.html
