### ISSUE TITLE
Menu Option Error Text

### ISSUE THREAD

**Issue by ZV95** [folivoraAI/BetterTouchTool#2506]
Hey @fifafu!

First off, thanks so much for all the work you've been putting in as of late, it's been incredible to see so many new features!

After installing the preset listed here: https://folivora.ai/blog/post/13000 in BTT 2.444 (806) triggering Action2 (preset to Paste Date and Time) fails and closes the window when not activated in a text area.  I have the screen flash enabled in accessibility and as a result get the screen flash and sound as if there's an error message but no error is shown. Obviously this error is thrown due to the fact that there is no where to paste the text, but it brings up an issue that I think should be resolved. 

On a failure to complete an action, I would like the option to have a custom error text pop up. At the bare minimum "BetterTouchTool was unable to complete that action" as a default, but custom text would allow a user to set _why or what_ failed.

**Comment by fifafu** [comment]
Continue you track this here #1969
