### ISSUE TITLE
Feature request: Some kind of conditional logic for touchbar actions

### ISSUE THREAD

**Issue by jelleoverbeek** [folivoraAI/BetterTouchTool#251]
#### Description of your bug/question/feature request...:
It would be nice to have a way to configure conditional logic for touchbar actions. Example: tapping on a play action would toggle the play icon to a pause icon.

**What kind of Mac are you using?**
MacBook Pro 15" (late 2016)

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
Touchbar

**Which versions of macOS and BetterTouchTool are you running?**
macOS: 10.12.2
BTT: 1.978

**Comment by tillnagel** [comment]
Yes, would be wonderful. Would love to have a feature like that. 

However, I am not sure how feasible this is. The status of the action (e.g. play/pause) can be changed through various other means, and thus the button only could reflect the current state when communicating with the app (as other specific touch bar implementations do it, such as /xzzz9097/Muse)

**Comment by fifafu** [comment]
This issue was moved to https://community.folivora.ai/t/feature-request-some-kind-of-conditional-logic-for-touchbar-actions/86

**Comment by fifafu** [comment]
Sorry, please ignore the previous message. The migration didn't work correctly, for now the issues will stay here.
