### ISSUE TITLE
Apple Remote registering two up/down clicks per click

### ISSUE THREAD

**Issue by pintapass** [folivoraAI/BetterTouchTool#2512]
A single up/down click (*not* left/right) on the aluminum Apple Remote actually registers as two clicks. This means that a single downward click in, say, the Plex app will jump two rows down, making navigation extremely difficult.

Aluminum Apple Remote

Type of Mac: iMac 27" 2010
macOS version: 10.3.5 public beta
BetterTouchTool version: 2.444

This started several point (.) versions ago, but since BTT was free at the time, I just dealt with it. I've now paid for a 2-year license and would like the behavior corrected.

**Comment by fifafu** [comment]
I have just tried to reproduce this, but it seems to work fine here.

Is it possible that Plex somehow interferes with this?
