### ISSUE TITLE
Allow getting uuid of trigger via scripting

### ISSUE THREAD

**Issue by JackAppDev** [folivoraAI/BetterTouchTool#2513]
#### Description of bug/feature request/question:
I need this so that I can use the scripting methods to handle updating touchbar buttons that are dynamically created and deleted.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Touch bar

#### Device information:

Type of Mac: Macbook pro 2016
macOS version: High sierra
BetterTouchTool version: Newest stable version at time of writing this

**Comment by fifafu** [comment]
I think the method that creates a new trigger, already returns the uuid.

Doesn't this work?

**Comment by JackAppDev** [comment]
If that is the case it would help. However, a method to get an array of the triggers and their properties would be perfect.
