### ISSUE TITLE
AppleScript not working with keyboard trigger

### ISSUE THREAD

**Issue by bekmarshall** [folivoraAI/BetterTouchTool#2517]
#### Description of bug/feature request/question:
Not able to run Apple Script with keyboard shortcut trigger.  It works if triggered by trackpad gesture.  Script also works fine from text entry box.  

This worked fine until recently.  Not sure what changed. 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Macbook keyboard

#### Device information:

Type of Mac: MacBook Pro 13" (2017)
macOS version: 10.12.6 
BetterTouchTool version: 2.444

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

I am trying to run an Apple Script that moves Outlook email message to Omnifocus.

**Comment by fifafu** [comment]
Could you attach the Apple Script here?

**Comment by bekmarshall** [comment]
Here is a simple example.   Again, this one works with different triggers, except keyboard triggers.  It used to work and I'm not sure what has changed.
 

on run {}
	tell application "Microsoft Outlook"
		activate
		set msgSet to current messages
		if msgSet = {} then
			error "No messages selected. Select at least one message."
			error -128
		end if
		set theMsg to item 1 of msgSet
		set theAccount to account of theMsg
		set archiveFolder to folder "@Archive" of theAccount
		--set archiveFolder to folder "@Archive" of on my computer
		repeat with aMessage in msgSet
			move aMessage to archiveFolder
		end repeat
	end tell
end run
