### ISSUE TITLE
[Feature Request] Support for Fn as a modifier key in Touch Bar settings

### ISSUE THREAD

**Issue by GoldenChaos** [folivoraAI/BetterTouchTool#2518]
#### Description of bug/feature request/question:

Command, option, control, and shift are all available to select. Why not Fn?

#### Device information:

Type of Mac: MBP 15" 2016
macOS version: 10.13.5 Beta
BetterTouchTool version: 2.444

**Comment by fifafu** [comment]
The problem is that Apple reservers the FN key for Touch Bar specific stuff. 
At least it was like this until 10.13.3. I'll check if it's still the case tomorrow (my Touch Bar MBP is currently being repaired by Apple)
