### ISSUE TITLE
mission control problem 

### ISSUE THREAD

**Issue by jyao84** [folivoraAI/BetterTouchTool#2519]
#### Description of bug/feature request/question:
after active mission control, all apps windows are spread, every time i click Finder window, Finder window will not show on top of all other windows. 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Macbook trackpad and Magic mouse

#### Device information:

Type of Mac: Macbook pro
macOS version: 10.13.4
BetterTouchTool version: 2.444(806)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
![qq20180421-104347 2x](https://user-images.githubusercontent.com/38576150/39079611-ec8da8d0-4550-11e8-829b-fb1dd15128d8.jpg)

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
I don't think this is related to BetterTouchTool. Or am I wrong?
