### ISSUE TITLE
Question: Macro Keyboard (separate keyboard key recognition)

### ISSUE THREAD

**Issue by yongar** [folivoraAI/BetterTouchTool#2520]
I would like to connect another keyboard, a number pad keyboard and create a separate macro only keyboard. 

Is there a way to recognize the key from the keyboard number 2, so that key is mapped as certain key combination for macro
BetterTouchTool version: 2.444(806)

**Comment by fifafu** [comment]
Unfortunately this is not possible.
In the future I want to support multiple keyboards, but I don't have a timeline for this yet.
