### ISSUE TITLE
Trackpad top edge swipe gesture request

### ISSUE THREAD

**Issue by 1kko** [folivoraAI/BetterTouchTool#2524]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead. 

---
#### Description of feature request:
So I'm just newbie in bettertouchtool. I've been using nexTab, however I'm thinking to change to btt as it hasn't updated for years, few bugs such as sometimes it needs to restart, and definitely more features and supports on BTT.

I was able to replace all gestures done by nexTab, except one of my favorite, multitouch trackpad top edge swipe to switch between tabs.
I wasn't able to google nor create custom gestures that only works similarly to top edge swipe.

it is a single finger gesture, and when you swipe top edge of the trackpad, it scrolls through tabs.

If this feature is made, I'm planning to connect to Ctrl+Tab and Ctrl+Shift+Tab, so calling this gesture should be with frequency, so further you scroll, more switched tabs.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
MacBook Trackpad

#### Device information:

Type of Mac: MacBook Pro
macOS version: 10.13.4 High Sierra
BetterTouchTool version: 2.445

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

nexTab link:
https://itunes.apple.com/us/app/nextab/id468063641?mt=12

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by samneluomark** [comment]
hello
