### ISSUE TITLE
Sort gesture lists by any column

### ISSUE THREAD

**Issue by rltbennett** [folivoraAI/BetterTouchTool#2527]
#### Description of bug/feature request/question:
Please allow sorting by any column -- gesture (trackpad), shortcut (keyboard), etc. as well as assigned action. Currently you can only sort by "On down" and "Enabled"

**Comment by fifafu** [comment]
it's a bug that they are sortable at all using the headers .
It should only allow sorting by drag and drop currently.

In a future version I'll replace the table based layout and use a more dynamic approach. However with the tables I can't allow to use the headers to sort as it breaks the custom ordering using drag & drop.
