### ISSUE TITLE
Run AppleScript file in the background

### ISSUE THREAD

**Issue by rltbennett** [folivoraAI/BetterTouchTool#2529]
#### Description of bug/feature request/question:
Currently, it is possible to: run an AppleScript in the foreground (BTT hangs until it completes) via its file, run an AppleScript in the foreground by entering the script directly as text, and run an AppleScript in the background by entering the script directly as text.

Ideally, the fourth option, running an AppleScript in the background via a file, would be a possibility as well. It's annoying to have BTT hang when running AppleScripts from their files, and it's also annoying to enter AppleScripts directly in BTT as it makes them non-portable and difficult to debug.

**Comment by fifafu** [comment]
This is now possible in v2.503 (I have renamed the Run Apple Script actions and changed the ui a bit)

![image](https://user-images.githubusercontent.com/8820811/39932013-45540dd0-553f-11e8-90d9-06c5baa544d6.png)
![image](https://user-images.githubusercontent.com/8820811/39932019-4755b430-553f-11e8-86ab-6acd87da1322.png)
