### ISSUE TITLE
Allow deleting triggers through applescript

### ISSUE THREAD

**Issue by JackAppDev** [folivoraAI/BetterTouchTool#2530]
#### Description of bug/feature request/question:
You can add triggers through applescript yet you can't remove/delete triggers. 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
All

#### Device information:

Type of Mac:
macOS version: 
BetterTouchTool version: 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from

**Comment by fifafu** [comment]
Yep, this will be added with the next update!

**Comment by JackAppDev** [comment]
Great! Thanks!
