### ISSUE TITLE
Slow loading of webview when triggered from another webview

### ISSUE THREAD

**Issue by avncharlie** [folivoraAI/BetterTouchTool#2531]
#### Description of bug/feature request/question:
What I've done (to reproduce the problem:)
1. I made a keyboard trigger on `f1` that opens the example menu from the webview tutorial (https://folivora.ai/blog/post/13000).
2. I made a named trigger called `calendarOverlay` that loaded Google Calendar in a webview.
3. I made a keyboard trigger on `f2` that runs the named trigger `calendarOverlay`.
4. I made the first item in the menu (in step 1) trigger the named trigger `menuAction1`.
5. I made a named trigger called `menuAction1` that triggers the named trigger `calendarOverlay`.

When I press `f2` for the first time, Google Calendar takes a small amount of time to load, and then it comes up. Then, whenever I press it again, it comes up immediately. I don't know why it does this, but I'm guessing BTT stores or caches the website after it loads it and displays that whenever the shortcut is activated after the first time?

I expected the same thing to happen when I trigger `calendarOverlay` using the menu, that it would initially take a little bit of time to load, and then afterwards load instantaneously, like when pressing `f2` more than once.

However, every time I press the menu button that triggers the calendar, it seems to load the website every time before displaying. The short pause before the calendar triggers when I press `f2` for the first time happens every single time I press the menu button that triggers the calendar.

Is there something wrong with the way I set it up that this is happening? I'd like it to load instantaneously from the menu after the first load like it does when pressing `f2`.

Thanks for your help.

**Comment by fifafu** [comment]
Hi,

currently BTT reuses the same "view" for all menus. This causes it to only be able to store one menu at a time without needing to reload it. In the next version BTT will use different views for all menus and then it will automatically cache every menu (optionally as it will need a bit more memory to do that).

The next version should be available tomorrow or on wednesday.

**Comment by avncharlie** [comment]
Wow, thanks for your quick response! That sounds good, I can't wait!

**Comment by fifafu** [comment]
This should now be much faster in v2.445 alpha (get via "check for alpha version updates")

**Comment by fifafu** [comment]
Also you can now trigger actions much faster by using a little bit of java script on your links. 
For example:
```HTML
<a onClick="window.BTT.callHandler('trigger_named', {trigger_name: 'Action5' , closeFloatingHTMLMenu: 1} )">Test Link</a>
```

**Comment by avncharlie** [comment]
Thanks @fifafu, working perfectly.
