### ISSUE TITLE
Trigger "INSERT" key from macbook pro keyboard

### ISSUE THREAD

**Issue by jrmgx** [folivoraAI/BetterTouchTool#2532]
As you may now the macbook pro keyboard is missing a physical "INSERT" key
No native shortcut exists for that one (unless other like DELETE accessible via fn + Back space)

So my reflex was betterTouchTool and I wanted to bind the F3 key (or any other key) to INSERT action,
it turns out that this is way harder, if even possible, than expected.

In the Keyboard part of BTT I can add a shortcut to trigger another key, but basically impossible to put "INSERT" as the result here. Also it is not on the list of predefined action.

My suggestion, if possible, would be to add that to the list of predefined action.

#### Device information:

Type of Mac: MacBook Pro (Retina, 13-inch, Mid 2014)
macOS version: 10.13.3 (17D102)
BetterTouchTool version: latest

**Comment by fifafu** [comment]
I believe on macOS the insert key can be simulated using fn+return (the return on the numpad)

You could try to copy n paste this into the keyboard tab in BTT:

```JSON
{
  "BTTTriggerClass" : "BTTTriggerTypeKeyboardShortcut",
  "BTTPredefinedActionType" : -1,
  "BTTPredefinedActionName" : "No Action",
  "BTTShortcutToSend" : "63,76",
  "BTTAdditionalConfiguration" : "8388608",
  "BTTEnabled2" : 1,
  "BTTTriggerOnDown" : 1,
  "BTTEnabled" : 1,
  "BTTShortcutKeyCode" : 99,
  "BTTShortcutModifierKeys" : 8388608,
  "BTTOrder" : 4
}
```


Alternatively this may work (I think 114 should be the keycode for insert, but I'm not 100% sure). It will show as a questionmark in BTT.
```JSON
{
  "BTTTriggerClass" : "BTTTriggerTypeKeyboardShortcut",
  "BTTPredefinedActionType" : -1,
  "BTTPredefinedActionName" : "No Action",
  "BTTShortcutToSend" : "114",
  "BTTAdditionalConfiguration" : "8388608",
  "BTTEnabled2" : 1,
  "BTTTriggerOnDown" : 1,
  "BTTEnabled" : 1,
  "BTTShortcutKeyCode" : 99,
  "BTTShortcutModifierKeys" : 8388608,
  "BTTOrder" : 4
}
```
