### ISSUE TITLE
F5 key does not work

### ISSUE THREAD

**Issue by EDu-mac** [folivoraAI/BetterTouchTool#2534]
- Description of bug/feature request/question :
F5 key does not any effect to launch show floating webview, I have to use FN + F5 

- Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.) :
Trackpad

- Device information :
Type of Mac:MacBook Air mi-2015
macOS version: 10.13.4
BetterTouchTool version: 2.445 

- Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

I use FunctionFlip to load command/program with fx key only (without FN) and it works except into BetterToolTouch which requires FN + fx. 

I select F5 key into BetterTouchTool's keyboard config but I have to use FN+F5 ! 

![capture d ecran 2018-04-24 a 05 43 27](https://user-images.githubusercontent.com/12591165/39165579-626ad5f6-4785-11e8-9832-e2239fedfe04.png)

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
To solve this you may currently need to switch to the old keyboard shortcut implementation. Function Flip sends the replaced F5 shortcut at a too high level for BTT to intercept.

![image](https://user-images.githubusercontent.com/8820811/39170282-3c9e3e92-479b-11e8-9838-a9f0fdc1ce7d.png)

**Comment by EDu-mac** [comment]
Thanks

 <http://edu.mac.free.fr/> <http://edu.mac.free.fr/>
