### ISSUE TITLE
Overlap in presents

### ISSUE THREAD

**Issue by PKeves** [folivoraAI/BetterTouchTool#2537]
I'm currently having two presents, present A and present B. Present A includes my normal everyday shortcuts and my present B modifies my keys so that I amble to type with one hand by mapping letter combinations to corresponding letters using  key sequences such as:
a,a -> l 
s,s  -> k 
and so on...
the problem occurs that although my current present is A and the keyboard sequence mapping I set up is in the present B I'm triggering key sequences mappings from present B while being in the present A. This only happens with the key sequences and not with basic shortcuts.

Mac version: 10.12.6
Bettertouchtools version: 2.443

**Comment by fifafu** [comment]
Thanks for reporting, I'll look into this.
