### ISSUE TITLE
After upgrade to latest version the Touch bar layout is messed up

### ISSUE THREAD

**Issue by vladikoff** [folivoraAI/BetterTouchTool#2539]
## Before

![image](https://user-images.githubusercontent.com/128755/39215255-345ab734-47e5-11e8-9ec1-04f53676d278.png)

## After

![image](https://user-images.githubusercontent.com/128755/39215211-10913a12-47e5-11e8-848d-e76e2ac0be9a.png)

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Touch Bar

#### Device information:

Type of Mac: 
macOS version: MacBook Pro (15-inch, 2017)
BetterTouchTool version: latest stable, the one that is asking for the new license

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
That's weird, i haven't had similar reports yet.

Could you maybe send an export of your preset to andreas@folivora.ai?

**Comment by vladikoff** [comment]
@fifafu Yeah i went back to the old-license for now, no rush

**Comment by fifafu** [comment]
Would still be great if you could attach an export of your preset (or send it to andreas@folivora.ai). Maybe it's some special combination of things causing this.
