### ISSUE TITLE
After updating from version 2.340, the commands on the an app stop working

### ISSUE THREAD

**Issue by leolaurettimusic** [folivoraAI/BetterTouchTool#2540]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at andreas@folivora.ai instead. 

---

#### Description of bug/feature request/question:
Please only post one bug or feature request per issue.

After I updated the version to 2.44, all the commands that I had for a specific program, Ableton Live, stopped working I don't know why.. all the shortcuts I've made for this program, even tried changing them to some unused shortcuts, as Shift+A, stop working.. 

My current commands are
Press (Pad *) and it equals Command+Shift+T
Press (Pad /) and it equals Cmd+T
Press (Pad +) and it equals Cmd+M

Any suggestions?

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Keyboard

#### Device information:

Type of Mac: iMac
macOS version: 10.12.4
BetterTouchTool version: 2.340

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Do you still encounter this issue? So far I haven't been able to reproduce this.
