### ISSUE TITLE
[Feature] Allow specifying application when adding trigger via scripting

### ISSUE THREAD

**Issue by JackAppDev** [folivoraAI/BetterTouchTool#2541]
#### Description of bug/feature request/question:

All the triggers I add with scripting go to global. I need to be able to choose what application the trigger applies to.

**Comment by JackAppDev** [comment]
@fifafu would that replace the current triggers with the new ones specified in the add_new_trigger call?

**Comment by JackAppDev** [comment]
@fifafu would add_new_trigger return the uuids as an array/list when there are multiple triggers in the BTTTriggers property?

**Comment by fifafu** [comment]
Should now work in v2.463 alpha 
![image](https://user-images.githubusercontent.com/8820811/39394813-cdfe2710-4ad6-11e8-8b55-e89e7e9f4e66.png)
