### ISSUE TITLE
1-Finger Force click "Pressure Necessary to Recognize Force Clicks" not synced with haptic feedback

### ISSUE THREAD

**Issue by zsiegel92** [folivoraAI/BetterTouchTool#2542]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at andreas@folivora.ai instead. 

---

#### Description of bug/feature request/question:
Please only post one bug or feature request per issue.

When I toggle the "1 Finger Force Clicks" pressure, it only affects the pressure necessary to recognize the command. Haptic feedback seems to always occur at exactly 850 units. So, if I set the pressure below 850, I trigger the command BEFORE haptic feedback (which occurs after the command, at 850 units). If I set the pressure above 850, I get haptic feedback, then trigger the command only if I continue pressing harder. That is, I can trigger a command separately from haptic feedback by pressing between the set value and 850. Very strange, makes settings other than 850 nearly unusable.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Magic Trackpad 2, Macbook Air 2012.

#### Device information:

Type of Mac: 2012 MBA
macOS version: 10.13.1
BetterTouchTool version: 2.441

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

My system is one where certain per-gesture haptic feedback settings do not work. That is, when I create a gesture and assign it its own haptic feedback (by clicking the cog in the "Touchpad Gesture" section), it usually doesn't work. It only works on "Triple Light", "Triple Strong", "Light Spring" or "Strong Spring". In "Trackpad" settings, I can only select "New BTT Default" next to "Haptic response for force clicks" and "for normal clicks". I am not submitting this as another bug, only relating it so you can tell where my system is at with respect to BTT.

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
I can not influence this in BTT unfortunately as the 1 finger haptic feedback is done by the system. (That's why I haven't added the 1 finger force click for a long time, but some people still want to use it like this)
