### ISSUE TITLE
It is required to filter accidental trackpad palm touches at the right bottom area while doing single-finger click and touch gestures

### ISSUE THREAD

**Issue by msx2010** [folivoraAI/BetterTouchTool#2543]
Description of bug/feature request/question:

New MacBookPro has very large trackpad so It is very difficult to use single finger click gestures because of accidental bottom right area touches by the right palm. Please filter right bottom area while single-finger clicks and taps.

Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

MacBookPro15 w/TouchBar
Device information:

Type of Mac:
macOS version: 10.13.4
BetterTouchTool version: 2.445
Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

Note: Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
BetterTouchTool can only influence its own gestures, not the system gestures like single finger clicks.
Or are you trying to use the BetterTouchTool corner clicks & taps?
