### ISSUE TITLE
Touch bar custom button color somehow becomes a little brighter after entering "Advanced Configuration" dialog and exiting it by pressing "Save" button

### ISSUE THREAD

**Issue by msx2010** [folivoraAI/BetterTouchTool#2544]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at andreas@folivora.ai instead. 

---

#### Description of bug/feature request/question:
I made a few custom touchbar buttons, then I decided to make extra padding with some of them, after I noticed that changed buttons become brighter! I entered to "Advanced Configuration" dialog of remaining buttons and just press "Save" button and all buttons color got same color.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

MacBookPro15 w/TouchBar

#### Device information:

Type of Mac:
macOS version: 10.13.4
BetterTouchTool version: 2.445

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Weird, you just hit save and it changes the color?
Currently can't seem to reproduce, but will have a more detailed look.

**Comment by msx2010** [comment]
I've repeat an experiment just now: created 3 buttons, then changed padding of first 2 of them.  Their color become slightly brighter then 3rd (unchanged) button. Is it possible to take screenshot of touchbar area?
