### ISSUE TITLE
Continuous system.log spam

### ISSUE THREAD

**Issue by biziclop** [folivoraAI/BetterTouchTool#2546]
#### Description of bug/feature request/question:

I just noticed that BTT floods the system.log file with some security/keychain/__security_simulatecrash related entries about every second.  

By quitting BTT, the flood stops immediately.
 

#### Device information:

Type of Mac: Macmini6,2
macOS version: 10.11.6 (15G20015)
BetterTouchTool version: 2.450 (812) alpha and the stable version before
 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
System log extract:  
[system_log.txt](https://github.com/folivoraAI/BetterTouchTool/files/1946742/system_log.txt)

Activity Monitor of BTT doing nothing:  
[Sample of BetterTouchTool.txt](https://github.com/folivoraAI/BetterTouchTool/files/1946850/Sample.of.BetterTouchTool.txt)

Censored EtreCheck results:  
[EtreCheck.txt](https://github.com/folivoraAI/BetterTouchTool/files/1946855/EtreCheck.txt)

**Comment by fifafu** [comment]
Could you check whether disabling "Allow crash log and anonymized usage data collection"  in the settings fixes this (requires a restart of BTT)? Seems like the Fabric/Crashlytics SDK has a SSL problem on macOS 10.11.x
