### ISSUE TITLE
Feature request: 'store' for web plugins

### ISSUE THREAD

**Issue by avncharlie** [folivoraAI/BetterTouchTool#2547]
BetterTouchTool could have some kind of system of sharing user webviews like apps or plugins - a timer app, a calender app, etc. 

What I mean by this is something like what the app Übersicht has, at http://tracesof.net/uebersicht-widgets/. Another inspiration is also (the now not working) Flashlight App's store page at http://flashlight.nateparrott.com/browse.

These 'plugins' could just be the web files needed to show the webview, maybe a JSON file containing the preferences (height, width, should it be cached, etc...), and some information about it and the author. These could then be displayed on the BetterTouchTool website for download before being installed by the actual app.

**Comment by fifafu** [comment]
Yep, currently finishing such a platform :-)
WIll be online soon.

**Comment by avncharlie** [comment]
Sounds awesome! I'm really loving the floating webview, can't wait to migrate some of my Übersicht widgets onto it!
