### ISSUE TITLE
BBT Crashes when trying to use Edit Screen Shot

### ISSUE THREAD

**Issue by scottb908** [folivoraAI/BetterTouchTool#2551]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at andreas@folivora.ai instead. 

---

#### Description of bug/feature request/question:
Please only post one bug or feature request per issue.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Macbook Pro Touch

#### Device information:

Type of Mac:
macOS version:  10.12.6
BetterTouchTool version: 2.444

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

If you grab a screen shot.  Then hit the Edit Screen Shot function the application appears to hang.  You can move the window around but all options are grayed out, Unable to do anything but close the app.  

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
This works fine here, but maybe it is related to macOS 10.12.x.

**Comment by scottb908** [comment]
A second reboot of the PC seems to resolved it.  Not sure why 2 reboots were needed.  It was as if the application was waiting for the next process to happen after clicking the button.  When working the gray boarder slides out.  That was not happening before.

**Comment by scottb908** [comment]
closing ticket, seems to be working at this time after second reboot
