### ISSUE TITLE
1 finger double tap to zoom

### ISSUE THREAD

**Issue by lassespilling** [folivoraAI/BetterTouchTool#2553]
1 Finger double tap to zoom is a feature you can enable in regular Mac mouse settings,
however when enabling "1 finger single tap = left mouse click" then 1 finger double tap doesn't work anymore to zoom.

I also saw that 1 finger double tap isn't an option in BettetTouchTool, is this something you could implement? Maybe 1 finger single tap overrides since there is no 1 finger double tap option?

**Comment by fifafu** [comment]
the problem is that the single finger double tap is used for double-clicks / dragging / selecting text.

**Comment by lassespilling** [comment]
But shouldn’t you be able to select what it is used for?

Especially when it’s a native OSX feature?

What do you mean «is used for»? It isn’t used unless you enable it?

Is it possible to just add zoom as another option?

**Comment by fifafu** [comment]
I could make it configurable, but this would prevent the tap to left click from behaving as expected by most users.

I'll see if I can add a configuration option to one of the next versions.

**Comment by lassespilling** [comment]
Ok thanks, behave unexpectedly?
Isn’t it possible to adjustthe double tap rate? Like how fast tou should tap in order to seperate it from a single tap?

**Comment by fifafu** [comment]
single taps would still work, but no double-clicks, no dragging and no selecting text.

**Comment by zhangenwen** [comment]
If I chose the three  finger drag. And then double-tap drag is available now. So you should release a double click. I can custom double-tap to do an infinite number of things.
Like:
Copy and paste.
 Inputs. 
Delete. 
Closes. .
 Open chrome browser. 
Open a new window. 
Open a new tab bar. 
Open the clip.
Dictionary of the query. 
The next tab...........

i am an ios developer, with BTT, i found my imac become a big touchable big iphone, now my magic mouse is leaved away, thank you so much.it is a fucking amazing app.

ps.   are you also focus on neural network now?
