### ISSUE TITLE
[Feature Request] Touch Bar Icons That Auto-Update When Application Changes State

### ISSUE THREAD

**Issue by brunorsini** [folivoraAI/BetterTouchTool#2554]
#### Description of bug/feature request/question:

It would be great to have touch bar icons that auto-update. Examples of use cases I currently miss:

- see number of unread messages on messaging apps (I use Rambox on the Mac, love it)
- mute/unmute specific apps (I do that quite often and it's hard to remember the current state sometimes)

Thanks!

**Comment by fifafu** [comment]
You can do that with the Apple Script / Shell Script widget, however you'd need to figure out how to get the information you want to show from these apps.

**Comment by JackAppDev** [comment]
@brunorsini funny you mention that because I am actually working on one for finder. Let me know some other examples and I will make some of them.
