### ISSUE TITLE
Apple Pencil Support - BTT Remote

### ISSUE THREAD

**Issue by colossatr0n** [folivoraAI/BetterTouchTool#2555]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at andreas@folivora.ai instead. 

---

#### Description of bug/feature request/question:
Please only post one bug or feature request per issue.

Apple Pencil support would be awesome. The pencil can move the cursor around but it can’t click. Having the ability to left click with the pencil would be great.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Apple Pencil 

#### Device information:

Type of Mac: MacBook Late 2013, iPad 6th Generation 2018
macOS version: 10.13.1, iPad iOS 11
BetterTouchTool version: 2.426

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
This issue was moved to https://community.folivora.ai/t/apple-pencil-support-btt-remote/24
