### ISSUE TITLE
Feature Request: Add HID key remapping to BetterTouchTool

### ISSUE THREAD

**Issue by MarqueIV** [folivoraAI/BetterTouchTool#2556]
I'd love to see the ability to remap keyboard keys directly instead of mapping them to functions.  For instance, on my keyboard, for some reason, the rightmost modifier (closest to the arrows) is the Alt key and not the Ctrl key as I would expect, and the Fn key is where the Alt key normally would be.

Since I never use Alt from the right side, I simply used 'hdiutil' via terminal to remap Right-Alt to Right-Ctrl, like so:

```
hidutil property --set '{
    "UserKeyMapping":[
        {"HIDKeyboardModifierMappingSrc":0x7000000E6,"HIDKeyboardModifierMappingDst":0x7000000E7}
    ]}'
```

Sure the label is now wrong, but muscle-memory is what I need, and now, as far as any app is concerned (including BTT), I'm now pressing the Ctrl key, not Alt.

Here's info from Apple's page on how they added this natively in macOS 10.12.  This looks like it would be incredibly easy to add.

[https://developer.apple.com/library/content/technotes/tn2450/_index.html](https://developer.apple.com/library/content/technotes/tn2450/_index.html)

Not sure if this can be done per-device, but if so, that would be even better as I could make this apply to only this one keyboard.

**Comment by ikwkim** [comment]
One vote to this. I want to have this feature from BTT. Thanks.

**Comment by MarqueIV** [comment]
Just adding that this feature *can* target a specific device.  The trick is you set what you want for all devices first, then you can override just the specific devices you want using the ability to filter it for a specific one.  For now, I've just created functions in my bash profile to execute what I need via simple commands, but I had to write it there (as opposed to a GUI) and it's now something related to input that I have to track/configure separate from BTT's settings, hence the request to add it.
