### ISSUE TITLE
Feature Request: Pinch to resize window larger/smaller (like IINA)

### ISSUE THREAD

**Issue by colecovizion** [folivoraAI/BetterTouchTool#2558]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at andreas@folivora.ai instead. 

---

Feature Request: Allow pinching to resize window (3 finger pinch preferable so it doesn't interfere with zooming inside an app. A good example of this is with IINA video player (although they use 2 finger). 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Magic Trackpad

#### Device information:

Type of Mac:
macOS version: 10.13.4
BetterTouchTool version: 2.443

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
You can kind of achieve this using the "Custom Move/Resize" action:

![image](https://user-images.githubusercontent.com/8820811/39917659-9485b448-550e-11e8-8072-5a490b3db704.png)
![image](https://user-images.githubusercontent.com/8820811/39917689-a3e153fc-550e-11e8-891e-1e5f30fd9cfe.png)

However it will only work good with the two finger pinch and you may need to adjust how often it triggers in the advanced preferences:
![image](https://user-images.githubusercontent.com/8820811/39917717-b3e43d28-550e-11e8-9e92-4c2799339788.png)

Alternatively you could use the new "repeat action while fingers are still touching" option and combine it with the three/four finger pinch/spread

![image](https://user-images.githubusercontent.com/8820811/39917843-0f5d0432-550f-11e8-9a11-626dd92a7092.png)
