### ISSUE TITLE
Window snapping fails for some apps

### ISSUE THREAD

**Issue by allewun** [folivoraAI/BetterTouchTool#2559]
#### Description of bug/feature request/question:

Window snapping fails for some apps, Firefox and Skype are two examples I've encountered. I think I began noticing this after upgrading to macOS Sierra.

For these apps, the {`Maximize Window`, `Restore Old Window Size`, and `Maximize Window Left|Right`} actions don't really work (the window size does change, but it's completely broken). One difference between the failed and succeeded snapping is the window size animates as it attempts to snap. For apps where snapping works correctly, there is no animation and the snapping is instantaneous.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Keyboard.

#### Device information:

Type of Mac: MacBook Pro (Retina, 15-inch, Late 2013)
macOS version: 10.12.6
BetterTouchTool version: 2.441

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

[Screen recording](https://github.com/folivoraAI/BetterTouchTool/files/1949772/snap.mp4.zip)

I'm trying to maximize Firefox several times with the `Maximize Window` action. I think I also tried a few of the other actions mentioned above too.

Then I demonstrate that snapping works fine for Sublime Text.

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
This is a bug in the macOS api BTT needs to use in order to resize windows. As far as I know apple has fixed it in 10.13.x

Usually a system restart fixes it, but it can come back

**Comment by allewun** [comment]
On my other machine, which is running 10.13.4, I still see this behavior in Firefox.

**Comment by bwilliams18** [comment]
@allewun I see the same issue in Firefox. and only in firefox. I think this is a bug on the firefox side of things, as my previous window manager (Divvy) was exhibiting the same behavior.

**Comment by fifafu** [comment]
Mh it seems to work fine in my Firefox (59.0.2 (64-Bit))
Do you have any specific extensions installed?

**Comment by allewun** [comment]
@fifafu sorry for the delay, life's been busy :) I'll do some testing to see whether any Firefox extensions might be a cause. Does Skype window snapping work fine for you?

**Comment by allewun** [comment]
BetterTouchTool 2.530 fixes this, thank you!
