### ISSUE TITLE
Feature request: setting user agent of webview

### ISSUE THREAD

**Issue by avncharlie** [folivoraAI/BetterTouchTool#2561]
Some sites (like the google search page) would look way better and be more functional in floating webview form if the mobile version of the site could be loaded and not the desktop version, as is default now. A useful feature would be to be able to specify the user agent string, or maybe a checkbox that says 'load mobile version', or something similar.

**Comment by fifafu** [comment]
Good idea, I'll add this.

**Comment by fifafu** [comment]
I have not tested it yet, but it should work with the latest alpha:
![image](https://user-images.githubusercontent.com/8820811/39382451-d2a93956-4a65-11e8-97bd-5930ebd96802.png)
