### ISSUE TITLE
Feature request: option to open links in browser

### ISSUE THREAD

**Issue by avncharlie** [folivoraAI/BetterTouchTool#2562]
A useful option would be to be able to open links clicked in a webview in a browser, in the case of having a webview of Google or a search engine to quickly search something up.
Thanks for the quick replies.

**Comment by avncharlie** [comment]
This and my last request are heavily inspired by old [Flashlight](http://flashlight.nateparrott.com/) plugins.

**Comment by fifafu** [comment]
I have added this in the latest alpha (you can choose which prefix urls must have to be opened in the system browser)

![image](https://user-images.githubusercontent.com/8820811/39382434-c2567398-4a65-11e8-9a9e-99047d8090f5.png)

**Comment by avncharlie** [comment]
Weirdly, after updating to the latest alpha, none of my webviews work. I'll open this in a new issue.
