### ISSUE TITLE
Which version of BTT is optimal for Mac OS Sierra 10.12.6? 

### ISSUE THREAD

**Issue by slt-uxd** [folivoraAI/BetterTouchTool#2566]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at andreas@folivora.ai instead. 

---

#### QUESTION:

I finally decided to update my MacBook Pro 17-inch (Late 2011) from El Capitan (10.11.6) to the latest version of Sierra (10.12.6). 

I was just wondering which version/build of BTT is optimal for that OS version, as I don't have a Touch Bar, and have an older Mac. 

Thanks for any tips!

PS - I have exported all of my gesture and shortcuts (using BTT 2.04)

#### Device information:

Type of Mac: MacBook Pro 17-inch (Late 2011) 
macOS version: Sierra (10.12.6
BetterTouchTool version: 2.04

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
The latest one ;-)
(https://folivora.ai/downloads )
