### ISSUE TITLE
Add "Xiaomi Mi Bluetooth Audio Receiver" support (or any bluetooth audio receiver with buttons)

### ISSUE THREAD

**Issue by joseaio** [folivoraAI/BetterTouchTool#2567]
Add support for button clicks (one, two, three, click & hold) for this bluetooth audio device...

    It can be very interesting for controlling presentations with cheaper bluetooth "remote"

Of course, most interesting thing is add support for multi-button over any bluetooth audio receiver

Thank you

**Comment by fifafu** [comment]
This issue was moved to https://community.folivora.ai/t/add-xiaomi-mi-bluetooth-audio-receiver-support-or-any-bluetooth-audio-receiver-with-buttons/19

**Comment by fifafu** [comment]
Sorry, please ignore the previous message. The migration didn't work correctly, for now the issues will stay here.

**Comment by fifafu** [comment]
Sorry, please ignore the previous message. The migration didn't work correctly, for now the issues will stay here.
