### ISSUE TITLE
keyboard shortcut unmaximizes window

### ISSUE THREAD

**Issue by ocie** [folivoraAI/BetterTouchTool#2570]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at andreas@folivora.ai instead. 

---

#### Description of bug/feature request/question:
I have some shortcuts set up to allow shift+home and shift-end to select to the beginning and end of line by assigning the action "shift+command+left/right".  I also have the option to move windows when the shift key is held.

These both work independently, but when I use shift+home or shift+end on a maximized window, the window returns to its previous size/location.  Interestingly, if I press the  "shift+command+left/right" myself, this does not happen.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

external trackpad+keyboard

#### Device information:

Type of Mac:MacBook Pro (15-inch, 2017)
macOS version: 10.13.4 (17E202)
BetterTouchTool version: 2.444

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Do you maybe have the action "Restore Old Window Size" assigned somewhere in BTT?

**Comment by ocie** [comment]
I don't have that shortcut assigned.  If I disable either the "hold shift to move window" or "shift+end" to select to end of line, the problem goes away.
