### ISSUE TITLE
Strange click behavior in "additional action"

### ISSUE THREAD

**Issue by dondo** [folivoraAI/BetterTouchTool#2571]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at andreas@folivora.ai instead. 

---

#### Description of bug/feature request/question:
Trying to write a little macro to open an application's preferences and then click at the right point in the window to open the right pane in preferences. Expected this to work:

    [type cmd-,]
    Move X:[xpos] Y:[ypos] (from window top left)
    Left Click

However, this opened the window, moved the mouse to the right point, but did not click. 
Hitting the invocation key again resulted in the appropriate click.
On instinct, modified the macro:

    [type cmd-,]
    Move X:[xpos] Y:[ypos] (from window top left)
    Delay next action by 1.00 seconds
    Left Click

This works.

Having played with the delay timing a little, it appears that it ignores clicks <0.5s after the mouse move; it queues up (!) the click 0.5 to 1.0s - so the mouse moves, nothing happens, but then no matter where I move the mouse, the next click is eaten at the position it was moved to. Really interesting.

Seems that there's some sort of race condition somewhere.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Keyboard

#### Device information:

Type of Mac: MacBook Pro (Retina, 13-inch, Early 2015)
macOS version: OS X El Capitan (10.11.6)
BetterTouchTool version: 2.444

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

![image](https://user-images.githubusercontent.com/71211/39389871-cbe441ca-4a41-11e8-881f-e6d5ebd621b6.png)

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
This depends a lot on how fast the application in question is able to accept clicks after opening the preferences.
I just tested with Finder where it basically works instantly, then again Xcode takes much longer to be ready.

I don't think this is something I can fix in BTT.

**Comment by dondo** [comment]
Interesting. But I don’t think it’s about the speed of opening the window. Here’s another example I’ve been able to reproduce.

Assuming you have MS Office 2016 installed, configure Word to show “Track changes” on the bottom status bar (right-click on the bar, check “track changes”). Then try this little snippet:




(Obviously the actual button position will vary based on what other things you have showing.)

The button is already sitting there, but when I invoke the macro it doesn’t get the left click the first time. But if I hit cmd-shift-T again, track changes toggles. Not only that, but if I hit it twice very quickly - less than half a second - it works. 

But if I add a delay, even a relatively long one, the click still doesn’t make it:



So what is the application doing that the change in cursor position prevents the click from being received after a BTT cursor position change, but works just fine if the cursor position isn’t actually moved? 

So this got me curious and I started playing. The behavior is a bit surprising.

Word: “Send email” button embedded in the title bar on the top of the Word window: moves the window a couple pixels diagonally, up and to the left.
Word: A “Style” in the styles pane: produced effectively a right click on the style.

Ok, now I was really curious. So in BTT I moved the simple macro from application = word into application = global so I could play with other applications.
Textmate: Click the “file type” affordance at the bottom of the window: works perfectly.
Word: “Track changes": effectively right-clicks the track changes button!!
Textmate: click the file icon in the title bar, right clicks.
Word: with preferences already open, try to click on the “view” pane: highlights as though the mouse-up was lost; clicking anywhere completes the click
Google Chrome: click the “reload” button: highlights as though the mouse-up was lost; clicking anywhere completes the click
Apple preview app: click the “note” icon at the top of an active document: no visible change, but clicking anywhere creates a note.
Mac OS “notifications” affordance at the top right (): opens the notifications, leaves the icon highlighted as though the mouse-up was lost; clicking anywhere dismisses the dialog (including on one of the notifications, where in contrast a full left-click activates the application).

So there’s definitely a subtle timing issue of some kind, and you may not be able to fix it, but I’m not sure the problem is as simple as a poorly implemented application.

**Comment by fifafu** [comment]
One more thing you could try:
Replace the left click with the predefined action "More Mouse Buttons & Modifiers" . This uses a slightly different technique to send the left-click - maybe that works better on 10.11.x.

![image](https://user-images.githubusercontent.com/8820811/39398247-67ac0754-4b0b-11e8-8408-df202237aea6.png)

**Comment by fifafu** [comment]
Unfortunately my other testing machine is on 10.10, not 10.11. However it also seems to work correctly there. No stuck buttons or similar things.

Is it possible you have any other keyboard or mouse related software installed that may conflict with BTT? (If there are multiple apps intercepting mouse clicks, the click event has to travel through all of them and potentially all of them could cause issues :-))
