### ISSUE TITLE
Constantly asking for permissions to be granted.

### ISSUE THREAD

**Issue by raguay** [folivoraAI/BetterTouchTool#2572]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at andreas@folivora.ai instead. 

---

#### Description of bug/feature request/question:
Every time BTT is launched, it asks me to set permissions. I go to sysconfig and it has the checkmark for BTT already checked. I uncheck, check it back, and relaunch BTT, but it still says permissions are not set.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

The trackpad options are in purple and not black, but they do seem to work.

#### Device information:

Type of Mac:  MacBook Air 13"
macOS version: 10.13.4 (17E199)
BetterTouchTool version: 2.462

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Unfortunately this is a macOS bug and there is no real solution.
The best way to get rid of it is usually to delete the app, download it again and uncheck/check the accessibility permissions again.

This usually resets the broken macOS database.
