### ISSUE TITLE
Webviews don't work after updating to latest alpha.

### ISSUE THREAD

**Issue by avncharlie** [folivoraAI/BetterTouchTool#2573]
After updating to the latest alpha, none of my webviews seem to be working. These include webviews from local files on my Mac and and webviews for other websites.

Weirdly however, when I put something in the html section, it shows up there.

This is the setting for one of my webviews:
![image](https://user-images.githubusercontent.com/24058782/39392278-43992500-4af6-11e8-8766-77a60dd5deb9.png)

This is that same webview when opened in Chrome (and it was working before)
![image](https://user-images.githubusercontent.com/24058782/39392304-bd54d81c-4af6-11e8-8972-f6689c82d0e4.png)

And this is what shows up when I trigger the webview:
![image](https://user-images.githubusercontent.com/24058782/39392318-f7b49542-4af6-11e8-931b-304aa0fe2130.png)

No idea why it is happening, my internet connection is good and I can't think of any reason why they wouldn't work. Thanks

**Comment by fifafu** [comment]
Could you check whether 2.463 works?

**Comment by avncharlie** [comment]
Sorry, how would I get that version? I'm on 2.462 now.

**Comment by fifafu** [comment]
It should show up, if you click "Check for alpha version updates" in the menubar item

**Comment by avncharlie** [comment]
I updated it, and it still is not working.

**Comment by avncharlie** [comment]
Would the debug info be useful?

**Comment by fifafu** [comment]
Ah wait, you have HTML entered in the text field but also a file URL?
Currently if both are provided BTT uses the HTML directly entered. Could you try to delete that?

**Comment by avncharlie** [comment]
Removed it, it just shows the menu buttons now. I just put the HTML in to test if it was working, but it wasn't working before that either.

**Comment by fifafu** [comment]
Ah thanks for testing. I think I have identified the issue.
Will be fixed in a few minutes :-)

**Comment by fifafu** [comment]
Ok, I think it will now work again in v2.464

**Comment by avncharlie** [comment]
Working perfectly, thanks.
