### ISSUE TITLE
Keyboard shortcut to trigger press *and hold* of spacebar until shortcut deployed again

### ISSUE THREAD

**Issue by kiranmcc** [folivoraAI/BetterTouchTool#2574]
#### Description of bug/feature request/question:

Is there a way to create a keyboard shortcut that simulates pressing and holding the spacebar until the keyboard shortcut is deployed again?

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Macbook Keyboard

#### Device information:

Type of Mac: MacBook Pro Retina (early 2013)
macOS version: Device: OS High Sierra 10.13.2
BetterTouchTool version: 2.318

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by oliviermattelaer** [comment]
Hi,

you can do it via applescript:
https://apple.stackexchange.com/questions/248861/how-to-make-applescript-hold-a-key-for-2-seconds

Cheers,

Olivier
