### ISSUE TITLE
After trial touch bar stopped working

### ISSUE THREAD

**Issue by MindaugasMateika** [folivoraAI/BetterTouchTool#2575]
#### Description of bug/feature request/question:

After my trial ended I bought the license. Upon uploading license file and launching BTT I noticed that touch bar stopped working. Only default touchbar appears now.

Only touch bar affected. Trackpad gestures work like usually.

Restarting Mac, deleting presets and importing it again did not help.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Touchbar

#### Device information:

Type of Mac: Macbook Pro 2017 15"
macOS version: 10.13
BetterTouchTool version: 2.444

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

[Touchbar settings](https://user-images.githubusercontent.com/17873445/39397169-9b0ad420-4b03-11e8-9451-f4a068004bc5.png)

**Comment by fifafu** [comment]
Maybe it's just hidden.
In general it's a good idea to add a keyboard shortcut and assign the action "toggle BetterTouchTool Touchbar"

**Comment by MindaugasMateika** [comment]
Yup, it was hidden 🙈 I haven't thought about that toggle myself. :/

Thanks a lot. Closing.
