### ISSUE TITLE
Disable Touch Bar completely unless FN key is held down?

### ISSUE THREAD

**Issue by jacobgraf** [folivoraAI/BetterTouchTool#2577]
I am wondering if there is a way to completely disable the Touch Bar (Completely black) unless I am holding the FN key down, then it will show my BTT Touch Bar? When I let go of FN, it should go back to black. Thanks!

**Comment by fifafu** [comment]
Unfortunately the FN key is reserved for macOS.
You could do it with any other key by making every button and widget you want to have only show when holding that:

![image](https://user-images.githubusercontent.com/8820811/39400919-db48929e-4b39-11e8-8c54-ac98d843fbea.png)

**Comment by jacobgraf** [comment]
That works for me. Thanks so much for the quick replies! Bought BTT a while ago but haven't dug in until now and it's amazing so far! :-)
