### ISSUE TITLE
BUG: TimeZone ignored in Time/Date Widget

### ISSUE THREAD

**Issue by awindsor** [folivoraAI/BetterTouchTool#2581]
Touchbar Time/Date Widget ignores Timezone box. 

I have mine set to GMT+12 but it just displays the current timezone. Ideally I want to use this to display some international times. 

#### Device information:

Type of Mac: MacBook Pro (13 in, Late 2016)
macOS version: 10.13.4
BetterTouchTool version: 2.466

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Ah sorry, this should be fixed in 2.467
