### ISSUE TITLE
Feature Request: Time/Date Widget Timezones

### ISSUE THREAD

**Issue by awindsor** [folivoraAI/BetterTouchTool#2582]
I would like to be able to set a Location for the Time/Date widget and have it switch between standard and daylight savings time. Currently there is a GMT box (which is not working for me) but that would not manage the switch between daylight and standard times. 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Touch Bar. 

#### Device information:

Type of Mac: PowerBook Pro (13 in, late 2016)
macOS version: 10.13.4
BetterTouchTool version: 2.466

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
The GMT box should now be working again in 2.467. 
I think adding time zones is a good idea, I'll add this with one of the next updates.

**Comment by awindsor** [comment]
Sure enough. I installed the update and the clock on my Touch Bar updated
to the correct time.

Thanks,

Alistair

Alistair Windsor
Director, Institute for Intelligent Systems
Associate Professor, Department of Mathematical Sciences
355 Dunn Hall/436A FIT             tel:901-678-5008
University of Memphis                fax:901-678-1336
Memphis, TN 38152-3240

**Comment by brockgr** [comment]
+1 for string based timezone. 

I would like to see European and Pacific time at the same time..

Thanks!
