### ISSUE TITLE
Program reports version 2.466 while changelog has 2.446

### ISSUE THREAD

**Issue by Reperator** [folivoraAI/BetterTouchTool#2583]
#### Description of bug/feature request/question:
The latest update reports version 2.466 while the [changelog](https://updates.bettertouchtool.net/bettertouchtool_release_notes.html) refers to version 2.446.

**Comment by oliviermattelaer** [comment]
I thought the 2.466 was an alpha release. All the alpha release does not have their associated changelog. But you can take a look here for more details:
https://updates.bettertouchtool.net/alpharls.html

**Comment by fifafu** [comment]
sorry, it's just a typo. Will fix it later.
