### ISSUE TITLE
Feature Request: Enter Full Screen on Next Monitor

### ISSUE THREAD

**Issue by jandhau** [folivoraAI/BetterTouchTool#2587]
Inspired by the new Custom Move/Resize action, would you consider adding an action that combines "Move to Next Monitor" and "Enter Full Screen (if supported)" in one go? 
I have them set up as consecutive actions triggered by a single command, but it might be neat to have them as one preconfigured action.  Then I could even set the green window button to go full screen directly on the next monitor which would be awesome.

**Comment by fifafu** [comment]
You should be able to attach this as an additional action:
![image](https://user-images.githubusercontent.com/8820811/39416914-dd548896-4c50-11e8-96fc-2d3d6b850990.png)

**Comment by jandhau** [comment]
Yeah, exactly, that's how I have it currently, which is what I meant by "consecutive actions".   I just thought it might be neat to have it as a single action ... which would look a bit nicer and save a few milliseconds ... ;)  
Definitely not a terribly urgent request, but since you were asking for feedback ... I can't think of anything else that I _cannot_ do with BTT :)

**Comment by fifafu** [comment]
This probably wouldn't save anything as I would still need to execute both actions and call the different APIs :-)

In general I don't add actions that can be achieved by easy combinations of existing ones, so I probably won't add this.

I think using this setup your idea to set the green button to execute this is also already possible. Or am I missing something?

**Comment by jandhau** [comment]
Oh, I see, no worries then.  
So going full screen involves a different API from those involved in "maximize to next monitor"?  
As for the other "next monitor" actions there are so many options, like "move to", "center on", "maximize on" so I thought full screen might work similar, but from what you write it does not. 
Thanks for the explanation!
