### ISSUE TITLE
Bug: BTT needs to be restarted constantly, as keyboard shortcuts stop responding

### ISSUE THREAD

**Issue by dougdougdougdoug** [folivoraAI/BetterTouchTool#2588]
**#### Description of bug/feature request/question:**

I use BTT probably 100 times a day (and love it!) - for switching between apps with the keyboard shortcuts, and window snapping.

Recently, the keyboard shortcuts would stop responding to my input. When I restart BTT, the shortcuts work again, but only for a few moments.

Please help resolve this issue, I recently became a paid member as you've made a great product.

I have the most up-to-date version and have tried restarting.

**#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):**

Keyboard shortcuts only. The app still runs and the configuration window still opens and is responsive, window snapping still works.

**#### Device information:**

Type of Mac: MacBook Pro
macOS version: 10.13.4
BetterTouchTool version: 2.467 (822)

**Comment by fifafu** [comment]
Some third party apps may conflict with the new shortcut implementation. If that happens to you, you may need to use the old shortcut implementation 

![image](https://user-images.githubusercontent.com/8820811/39416842-6e05e570-4c50-11e8-8975-715ef8c800c1.png)

**Comment by dploeger** [comment]
I have that enabled, but it still does not work. And I think, that it does not have to do with SecureInput, as another app I use (aText) also shows, when secure Input is active, and it doesn't show anything.

The error looks goes like this for me:

* Restart BTT
* Use keyboard shortcuts (in my example: Ctrl+Alt+1 and Ctrl+Alt+2 for switching between two apps: Chrome and AirMail)
* After about 5 usages, the response of the shortcuts gets slower and then stops

I can provide you with logs or something else. Thanks!

**Comment by dougdougdougdoug** [comment]
Reverting to the "old keyboard implementation" worked for me, but there's a
twist: it only worked when I changed that setting on both my accounts.

I have 2 accounts on my Mac, both have BTT installed, and both run at the
same time: one active, one in the background which I can switch to via
macOS's account pulldown.

It looks like you've got a config issue, where the settings in one account
effect the other.

So I performed your fix on account #1, only to have strange behaviour until
I also did the fix on account #2, which then fixed it for account #1 (and
#2).

**Comment by dploeger** [comment]
@dougdougdougdoug Ah yes, that may just be the case on my system as well. I also noticed, that the error went away for some time now. Maybe I unknowingly corrected it like you said.
