### ISSUE TITLE
Nested button groups problems

### ISSUE THREAD

**Issue by CappyD** [folivoraAI/BetterTouchTool#259]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:
First - thanks for adding the button group feature.  Nice work and very helpful.  
But, it's pretty difficult to create nested button groups in the BTT interface.  If you create a button group and then click to create another inside it, you don't get the prompt about where to place it and it always becomes a separate group.  You can nest it by creating at least one button in the outer group and then drag/drop the second group into the first group.  

Also, when using nested groups the close button from the inner-most group takes you all the way out rather than back to the group it is nested within.

**What kind of Mac are you using?**
2016 MacBook Pro 13"

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

**Which versions of macOS and BetterTouchTool are you running?**
10.12.2 and 1.987

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by fifafu** [comment]
Sorry, currently only one level of groups is implemented for various reasons, it actually shouldn't be possible to drag groups into another group.
I'll add support for nested groups in a future version when everything else works stable enough.

**Comment by fifafu** [comment]
This issue was moved to https://community.folivora.ai/t/nested-button-groups-problems/83

**Comment by fifafu** [comment]
Sorry, please ignore the previous message. The migration didn't work correctly, for now the issues will stay here.
