### ISSUE TITLE
Feature request: Trigger drawing gestures using both left and right mouse click

### ISSUE THREAD

**Issue by sammcj** [folivoraAI/BetterTouchTool#2590]
#### Description of bug/feature request/question:

Add the ability to take gesture input while holding both left and right mouse buttons, rather than just right.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Any mouse

#### Device information:

Type of Mac: Any
macOS version:  10.13.4
BetterTouchTool version: 2.447

**Comment by fifafu** [comment]
This issue was moved to https://community.folivora.ai/t/feature-request-trigger-drawing-gestures-using-both-left-and-right-mouse-click/21
