### ISSUE TITLE
Feature Request: Scrollable Container Widget

### ISSUE THREAD

**Issue by rogueaskywalker** [folivoraAI/BetterTouchTool#2591]
I think it would be really useful to have some way to add a second scrollable container. I currently have a few websites that I have buttons for. It would be useful to have them in their own separate scrolling widget. I could also see it as a way to split work apps from personal apps. I could have a scrolling widget filled with my Adobe apps and then I'd have a second scrolling widget where I might have ITunes, Spotify, etc.

**Comment by fifafu** [comment]
This issue was moved to https://community.folivora.ai/t/feature-request-scrollable-container-widget/18

**Comment by fifafu** [comment]
This issue was moved to https://community.folivora.ai/t/feature-request-scrollable-container-widget/77
