### ISSUE TITLE
Touch Bar Icon No Long Showing after update

### ISSUE THREAD

**Issue by cliffordykho** [folivoraAI/BetterTouchTool#2593]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at andreas@folivora.ai instead. 

---

#### Description of bug/feature request/question:
Please only post one bug or feature request per issue.

After Updating to 2.467, all preset touch bar icons disappeared.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Touch Bar

#### Device information:

Type of Mac: 2016 MacBook Pro 15 Touch Bar
macOS version: macOS High Sierra 10.13.4
BetterTouchTool version: 2.467

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by cliffordykho** [comment]
Thanks for the reply, I just found out that they show back up if I set the action placement instead of leaving it blank.

**Comment by fifafu** [comment]
I think I have found an issue. Is it possible they disappear if you touch the Touch Bar with two fingers?

**Comment by fifafu** [comment]
I have just uploaded a little fix, you can try checking for updates manually.

**Comment by cliffordykho** [comment]
Thank you very much!

**Comment by fifafu** [comment]
Sorry needed to replace the update one more. The update check will work again in about 5 minutes.
