### ISSUE TITLE
Disappearing snap areas

### ISSUE THREAD

**Issue by davide42** [folivoraAI/BetterTouchTool#2598]
#### Description of bug/feature request/question:

Snap areas often disappear after my mac goes to sleep / periods of inactivity. I have to manually restart BTT for them to show up again.

#### Device information:

Type of Mac: 13 inch macbook pro, 2016.
macOS version: high sierra 10.13.3
BetterTouchTool version: 2.444

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

This kept happening also in previous versions of BTT.

**Comment by nienkeboomsma** [comment]
Same thing here. This has been a bug that I've been dealing with for as long as I can remember.
