### ISSUE TITLE
Spaces not allowed in "window title" on custom move/resize gesture

### ISSUE THREAD

**Issue by TheBartoMan** [folivoraAI/BetterTouchTool#2600]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at andreas@folivora.ai instead. 

When trying to set up a gesture to move the windows with the title Microsoft Outlook to a specific / location and resize, i cant because when i try to enter a space in the "Window with Title" field it doesn't accept it.
---

#### Description of bug/feature request/question:
Please only post one bug or feature request per issue.

#### Device information:

Type of Mac: Latest
macOS version: Latest
BetterTouchTool version: Latest 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Thanks for reporting! I have already fixed it for the upcoming version.
