### ISSUE TITLE
Hide menu items for fullscreen mode

### ISSUE THREAD

**Issue by FranzFelberer** [folivoraAI/BetterTouchTool#2601]
#### Description of bug/feature request/question:
Feature request/question: I want to use the hide menu items temporarily feature to access the menu items which are otherwise hidden. I case of fullscreen mode the desktop is automatically changed.
Can that be avoided, or can this feature be implemented?

#### Device information:

macOS version: High Sierra
BetterTouchTool version: 2.467

**Comment by fifafu** [comment]
Unfortunately I don't think this is possible.
However there is a great app called Bartender which can help you manage your menubar items.

There is also the free vanilla app: https://matthewpalmer.net/vanilla/?utm_source=22217ac8&utm_medium=rlink&utm_campaign=four_friends

I think it should also be able to do this.
