### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by miokap** [folivoraAI/BetterTouchTool#2603]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at andreas@folivora.ai instead. 

---

#### Description of bug/feature request/question:  
Over the last several BTT versions, the problem I have encountered have not been fixed. Namely, by selecting Trackpad Gesture "two finger force click" I assigned "Search Selected Text With Google". However, each time after I highlight the word(s), BTT for some reason does not recognize that word(s) but rather the previously highlighted word(s). 
Please only post one bug or feature request per issue.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):  
Macbook Trackpad

#### Device information:

Type of Mac: Macbook Pro early 2015, 13 inch
macOS version: 10.13.4
BetterTouchTool version: 2.467

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
Unrelated to this issue, but it would be nice if you can provide an RSS FEED for https://blog.boastr.net/blog so we can follow your blog.

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
This seems to work fine here.
Do you have any other keyboard or mouse related apps installed that could conflict with BTT?

**Comment by fifafu** [comment]
For the startup issue make sure to check launch on startup in the BetterTouchTool preferences

![image](https://user-images.githubusercontent.com/8820811/39582561-814dc062-4eee-11e8-98a8-f2a02a8609d1.png)

**Comment by miokap** [comment]
Thanks. I did not know I had to select it within the BBT as well. 
Regarding the original question, the trigger would only work if I also copy the highlighted phrase/word before I force click it in order for the trigger to work. I guess I need to find a conflicting app on my own since it's not a widespread issue but it rather pertains to my unique mac setup. Regards.

**Comment by fifafu** [comment]
I'm currently working on a service that will make this more reliable on some machines.
Keep watching the upcoming updates :-)
