### ISSUE TITLE
floating webview cannot be dismissed

### ISSUE THREAD

**Issue by adamjrice** [folivoraAI/BetterTouchTool#2605]
#### Description of bug/feature request/question:

If neither "close when clicking outside" nor "show window buttons" are enabled for the window, then there's no easy way to dismiss it. The escape key does not work. 

I suggest always enabling the escape key for dismissing the window, or forcing a choice between click outside/show window buttons.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Doesn't seem to be device-specific

#### Device information:

Type of Mac: MacBook Pro (Retina, 13-inch, Late 2013)
macOS version: 10.13.4
BetterTouchTool version: 2.466

**Comment by fifafu** [comment]
Hey, 

you can always dismiss the web view by performing the same trigger you use to show it!
