### ISSUE TITLE
can't link to dropbox

### ISSUE THREAD

**Issue by sagitt** [folivoraAI/BetterTouchTool#2607]
using last version 2.468b826 and dropbox 48.4.58 can't link to it
it tell me there is a problem with dropboxsdk

**Comment by sagitt** [comment]
DropboxSDK: unable to link; app isn't registered for correct URL scheme (db-023dchhmiya8zec). Add this scheme to your project Info.plist file, associated with following key: "Information Property List" > "URL types" > "Item 0" > "URL Schemes" > "Item <N>".

**Comment by bgutsche** [comment]
yep, same here

**Comment by fifafu** [comment]
Thanks for reporting, should be fixed in v2.469 alpha.

(get via "check for alpha version updates")

**Comment by bgutsche** [comment]
works now! :) thx a lot!
