### ISSUE TITLE
Preferences Window appears randomly

### ISSUE THREAD

**Issue by mliq** [folivoraAI/BetterTouchTool#2608]
#### Description of bug/feature request/question:
Randomly I notice that the BTT icon is present in my dock, and I have to click it and close the Preferences window. (Normally BTT only appears as a menu bar icon unless I choose to open the Preferences window by either running BTT again or choosing Preferences from menu bar icon menu).

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Mid-2015 15" Macbook Pro with bluetooth Magic Keyboard 2 and Magic Trackpad 2.

#### Device information:

Type of Mac: MacBook Pro (Retina, 15-inch, Mid 2015)
macOS version: 10.12.6
BetterTouchTool version: 2.426 (785)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
If anything of this nature can help, let me know and I will submit here.

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
could you check whether this build fixes this issue?
https://bettertouchtool.net/releases/btt2.426_recovery2.zip
