### ISSUE TITLE
Keeps launching in dock on startup

### ISSUE THREAD

**Issue by brianliyang** [folivoraAI/BetterTouchTool#2609]
Recently, I've noticed BTT launches and stays in my dock on startup when I turn my computer on. I have to click on it, open it, then close the window for it to hide and run in the background. I haven't changed any settings recently and I checked to make sure I don't have the run in dock setting enabled. Is this a regression?

macOS version: 10.13.3
BetterTouchTool version:  2.426

**Comment by fifafu** [comment]
could you check whether this build fixes this issue?
https://bettertouchtool.net/releases/btt2.426_recovery2.zip

**Comment by craftey** [comment]
Same here. Testing above build...

**Comment by brianliyang** [comment]
Seems like that build fixed it for me, thanks!
