### ISSUE TITLE
2 finger scrolling is laggy and jumpy while BTT is open.

### ISSUE THREAD

**Issue by ifeign** [folivoraAI/BetterTouchTool#2611]
#### Description of bug/feature request/question:

While BTT is open, if I attempt to two finger scroll too quickly or too often, windows will scroll with a stutter or will suddenly jump to the top or bottom. Closing BTT immediately fixes this.

I'm using no trackpad features, only a few application specific touch bar buttons and window snapping.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Trackpad

#### Device information:

Type of Mac: 2017 Macbook Pro 15"
macOS version: 10.13.4
BetterTouchTool version: 2.467 (has been happening in previous version and current alpha 2.468 as well)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

Closing BTT immediately fixes this.

---

**Comment by fifafu** [comment]
Do you have other mouse or keyboard related apps installed that could conflict with BTT?

**Comment by ifeign** [comment]
Possibly my Logitech Gaming Software, but I don't let it run on boot, and only open it when I need to change a mouse setting (almost never).

I'll uninstall it and report back.

**Comment by ifeign** [comment]
Still no difference made by uninstalling my mouse drivers. I have to quit BTT if I want to scroll smoothly in any application.
