### ISSUE TITLE
Touch bar not displaying

### ISSUE THREAD

**Issue by eponymz** [folivoraAI/BetterTouchTool#2612]
#### Description of bug/feature request/question:
Unsure the cause for this. It was displaying perfectly fine one minute and the next it was gone. Tried restarting the program, as well as quitting and launching fresh. Also tried restarting mac on a whole, touch bar is only displaying the mac default. I havent changed the display settings at all.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Touch bar.

#### Device information:
Type of Mac: MacBook Pro (15-inch, 2017)
macOS version: 10.13.4
BetterTouchTool version: 2.468 (826)

**Comment by fifafu** [comment]
Maybe you accidentally hid it by clicking the BTT Touch Bar button in the control strip?
In general it's a good idea to define a keyboard shortcut in BTT to hide/show the BTT Touch Bar. This can be done by assigning the predefined action "Toggle BetterTouchTool Touch Bar" to any keyboard shortcut

**Comment by eponymz** [comment]
That sounds extremely likely (facepalm) let me give it a shot. Thank you for the fast response!!

**Comment by eponymz** [comment]
Wow i failed hard. Thank you so much again!!
