### ISSUE TITLE
unable to pair Siri remote to use BTT

### ISSUE THREAD

**Issue by balufudus** [folivoraAI/BetterTouchTool#2613]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at andreas@folivora.ai instead. 

---

#### Description of bug/feature request/question: I was using a Siri remote with my work MacBook Air without any issues. I updated to High Sierra and since then have not been able to use it or even pair the remote. 
Please only post one bug or feature request per issue.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Siri Remore

#### Device information:

Type of Mac: MacBook Air 13" 2017
macOS version: High Sierra 10.13.4
BetterTouchTool version: 2.467 (825)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
you could try to shift+opt+click on the bluetooth icon in the menubar (if you don't have it visible in the menubar, go to system preferences => bluetooth and enable it).
Then you can click on Debug => Reset the Bluetooth Module or Debug => Factory Reset all connected Apple Devices" (both of them will temporarily disconnect all connected devices but they often solve connection problems).

![image](https://user-images.githubusercontent.com/8820811/39543540-ccde3528-4e4b-11e8-80e4-c3e0dda47ce5.png)

**Comment by balufudus** [comment]
That worked! Thanks!




Nhu
