### ISSUE TITLE
Shortcut Triggers Twice

### ISSUE THREAD

**Issue by ccwillia** [folivoraAI/BetterTouchTool#2614]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at andreas@folivora.ai instead. 

---

#### Description of bug/feature request/question:
Using apple remote when i assign up to keyboard shortcut up the shortcut is triggered twice.  This happens with down as well.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Apple Remote

#### Device information:

Type of Mac: MacMini
macOS version: 10.13.4
BetterTouchTool version: 2.445 (I have tried the latest version as well)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
What kind of Apple Remote?

**Comment by ccwillia** [comment]
The small silver remote

**Comment by fifafu** [comment]
Ok weird. I'll check tomorrow whether anything has changed in recent macOS versions.

**Comment by ccwillia** [comment]
Were you able to figure out what changed?

**Comment by fifafu** [comment]
unfortunately I'm unable to reproduce this. It seems to trigger correctly here.

In which application are you trying this?

Does the remote work correctly without BTT?

**Comment by ccwillia** [comment]
Even when I added BTT to the list of applications with up/down within the BTT application it triggers twice.  I’ll try the latest version later tonight

**Comment by fifafu** [comment]
When you quit BTT, does the remote work correctly? (e.g. in iTunes play/pause)

**Comment by ccwillia** [comment]
The up/down control the volume in iTunes now which is the reason I started using BTT as I wanted up/down mapped to keyboard-up/keyboard-down.  I removed all the BTT released files and tried a fresh install and I still have the same issue.  I am on OSX 10.3.4.  Any help is appreciated

**Comment by ccwillia** [comment]
From this thread it sounds like apple has reversed the changes they made when high Sierra was introduced

https://forums.plex.tv/discussion/289570/mac-mini-osx-updated-to-high-sierra-and-remote-problem/p3 <https://forums.plex.tv/discussion/289570/mac-mini-osx-updated-to-high-sierra-and-remote-problem/p3>
