### ISSUE TITLE
Question before I buy the app

### ISSUE THREAD

**Issue by mahoneyd** [folivoraAI/BetterTouchTool#2615]
Feature
 I currently use a LG monitor it has a application for mac called onscreen split. It has a feature, that I was wondering if your app supports. It splits the desktop in to four sections top left, top right, bottom right ,  and bottom left. There are way more option than the four way spilt, but it is the one I use most often. The snap area is the whole corner so it automatically snaps there and resizes the window. I am pretty sure you can make that happen with customizable snap area which I think your app supports. The feature that I am looking for, is when you resize one window it resizes all the other three automatically and automatically adjusts their corresponding snap area.  So I can make the bottom right bigger and the other three windows are auto resized and so is their snap areas. I hope that makes sense. Thanks!

**Comment by fifafu** [comment]
Currently BTT can only resize single windows and doesn't interact with the others. If you need this behavior you should keep using the LG software.
