### ISSUE TITLE
Mouse becomes jerky and unresponsive

### ISSUE THREAD

**Issue by modpod** [folivoraAI/BetterTouchTool#2616]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at andreas@folivora.ai instead. 

---

#### Description of bug/feature request/question:
Please only post one bug or feature request per issue.
Mouse becomes jerky and unresponsive
#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Logitech mouse

#### Device information:

Type of Mac: iMac late 2015
macOS version: 10.11.6
BetterTouchTool version: 2.467

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
Over time BTT makes mouse movement jerky and unresponsive. Restarting BTT usually solves the problem, but problem can reoccur as soon as 30 minutes latter. Restarting the system also fixes the problem. Disconnecting and re-connecting the mouse USB cord sometimes fixes the problem.

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Do you have any other mouse related apps installed? Unfortunately there can be conflicts which lead to such behavior if multiple apps try to work with the mouse events.

**Comment by fifafu** [comment]
Apparently Steer Mouse is an app that can cause such behavior when combined with BTT

**Comment by modpod** [comment]
Hi Andreas,
I am not using Steer Mouse, but embarrassingly I tracked down the problem
to dust on the lens of the mouse. A blast of compressed air seems to have
fixed the problem.

Thanks for a great product and support.

Nick
