### ISSUE TITLE
Bug: "Special middleclick mode (for CAD users)" does not work (tested on multiple computers)

### ISSUE THREAD

**Issue by perkinsb1024** [folivoraAI/BetterTouchTool#2618]
#### Description of bug/feature request/question:
I have enabled "Special middleclick mode (for CAD users)" and under "Trackpads" I enabled "Three Finger Click" with the predefined action "Middle Click".  In the Live View, I see that clicking and releasing three fingers triggers a middle click, but clicking three and releasing two does not trigger any recognized gesture, nor does it pan in my CAD software (tried Autodesk EAGLE and Fusion 360), despite both of those softwares panning correctly when using a mouse with a real middle click button. I've tried on two separate computers with the same results.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
MacBook Trackpad

#### Device information:

Type of Mac: MacBook Pro 15" 2017 with Magic Touchbar, MacBook Pro 15" 2013
macOS version: 10.13.3
BetterTouchTool version: 2.467

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
<img width="365" alt="screen shot 2018-05-02 at 6 14 29 pm" src="https://user-images.githubusercontent.com/7825815/39556381-cd1e917a-4e34-11e8-8122-ec393824ad8b.png">
<img width="505" alt="screen shot 2018-05-02 at 6 14 20 pm" src="https://user-images.githubusercontent.com/7825815/39556386-d15a049a-4e34-11e8-96bd-41490d1efdf9.png">

**Comment by fifafu** [comment]
Unfortunately that is a very old setting and only still works on old macOS versions.

With the latest alpha you could try to set it up like this:

1.) don't use the middle click action, instead use the "More Buttons & Modifiers & Custom Click" action and configure it like this (only mouse down).
![image](https://user-images.githubusercontent.com/8820811/39584896-d0e0351a-4ef3-11e8-8290-ee859b29a44e.png)

2.) Open the gesture preferences and define a named trigger that shall be executed when no fingers are touching the trackpad anymore
![image](https://user-images.githubusercontent.com/8820811/39584944-e9ed952a-4ef3-11e8-87ed-e71bf2386d07.png)

3.) Go to the "Other" tab and create a Named Trigger, then assign the middle mouse up.
![image](https://user-images.githubusercontent.com/8820811/39584971-f9b9307c-4ef3-11e8-959e-e9cbd8fd9fca.png)

**Comment by perkinsb1024** [comment]
Thank you @fifafu! That works and it definitely makes my workflow much, much easier. I have just one more request related to this feature, if possible. A lot of times when I'm panning, I need to swipe multiple times to pan far enough, but as soon as I lift my finger from the trackpad, the "middle mouse button (up)" gesture is sent. Is it possible to add a "wait X ms" slider to the "execute named trigger after removing..." option? IE: if I set the slider to 150ms, then the action will only be triggered if my fingers remains off the trackpad for 150ms, giving me time to get my finger back onto the trackpad and continue swiping (much like Apple's built-in tap-to-drag feature).
Thanks again!

**Comment by fifafu** [comment]
Yes, good idea!

**Comment by fifafu** [comment]
This is now available in v2.471 alpha :-)

**Comment by perkinsb1024** [comment]
Perfect! That resolves my issue entirely, thanks for implementing this 👍
