### ISSUE TITLE
BTT failed to start with "Version incompatible" error

### ISSUE THREAD

**Issue by delphet** [folivoraAI/BetterTouchTool#2619]
#### Description of bug/feature request/question:
BTT failed to start and displayed an error message: 

"BetterTouchTool version incompatible"

"The Version of BTT you are currently using isn't compatible with the version of your data file! Please update to a newer version of BTT. Maybe you have an old version in your startup items(autostart)"

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

MacBook Pro Trackpad, Magic Mouse

#### Device information:

Type of Mac: MacBook Pro, Mid 2010 Model
macOS version: Yosemite 10.10.5 
BetterTouchTool version: N/A

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

![screen shot 2018-05-02 at 10 51 14 pm](https://user-images.githubusercontent.com/5004216/39558570-b3c7c7ae-4e5d-11e8-9818-4bbb7b0aea63.png)

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
could you try to download a fresh copy from my website? (https://folivora.ai/downloads)
