### ISSUE TITLE
Secure input always enabled

### ISSUE THREAD

**Issue by ignaciobarrena** [folivoraAI/BetterTouchTool#2620]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at andreas@folivora.ai instead. 

---

#### Description of bug/feature request/question: secure input always activated
Please only post one bug or feature request per issue.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Macbook Pro Keyboard shortcuts

#### Device information:

Type of Mac: macbook pro retina 2015 13"
macOS version: 10.13.4
BetterTouchTool version: 2.468 (826)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

Since last update I've been having this issue, never had it before. Keyboard shortcuts doesn't work

https://imgur.com/a/NEMVEQQ

I don't have any login windows active. Tried to restart BTT and the Mac itself. Is it a new behaviour ?

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Unfortunately some apps break this (I don't have a list of incompatible apps yet, so far it seems some security related apps always enable secure input).
You can enable the old shortcut implementation in the advanced preferences:

![image](https://user-images.githubusercontent.com/8820811/39562815-e46aad18-4ead-11e8-81e1-a63b159ae931.png)


There is no other workaround for this.
