### ISSUE TITLE
Middle click on mac X11 is intermittent

### ISSUE THREAD

**Issue by pjyoung** [folivoraAI/BetterTouchTool#2621]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at andreas@folivora.ai instead. 

---

#### Description of bug/feature request/question:
Configured to have a centre mouse button for using with XQuartz on a mac (ie paster function) is very intermittent. Need several clicks for a paste to succeed. Most annoying!

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Magic Mouse

#### Device information:

Type of Mac: MacBook Pro, 15in, 2016
macOS version: High Sierra, 10.13.4
BetterTouchTool version: 2.425 (782)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
This probably can't be fixed in BTT (BTT just uses the default APIs to send middle-click events).

You could try to use the predefined action "More Mouse Buttons & Modifiers / Custom Click" and try to send separate down and up events with a little delay inbetween:

![image](https://user-images.githubusercontent.com/8820811/39563583-1514f89e-4eb1-11e8-9cb1-6ebce277cb5c.png)

**Comment by pjyoung** [comment]
Hi Andreas,

Thanks for fast response :)
Can’t quite see how you got a “Custom Click: Middle (Down)” gesture…

But in looking for it I noted the feature to set middle click area - I have changed that and will see if it improves.

Cheers, Peter


On 3 May 2018, at 5:05 pm, Andreas Hegenberg <notifications@github.com<mailto:notifications@github.com>> wrote:


This probably can't be fixed in BTT (BTT just uses the default APIs to send middle-click events).

You could try to use the predefined action "More Mouse Buttons & Modifiers / Custom Click" and try to send separate down and up events with a little delay inbetween:

[image]<https://user-images.githubusercontent.com/8820811/39563583-1514f89e-4eb1-11e8-9cb1-6ebce277cb5c.png>

**Comment by scottmetoyer** [comment]
Unfortunately I'm having the same issue. Middle click usually takes 3-4 clicks to work. I tried the custom click suggestion above, but that didn't seem to help. Any other ideas?

**Comment by fifafu** [comment]
Which gestures/trigger are you using to trigger the middle-click?

**Comment by scottmetoyer** [comment]
I'm using the '1 Finger Middle Click' gesture to trigger a middle click mouse action.

I tried adjusting my middle click area, and also tried the custom click approach but had the same issue.

**Comment by fifafu** [comment]
That gesture is indeed a bit tricky and may not work for everybody. In general I recommend to use the three finger click as a gesture for middle clicks, it's more reliable and also easy to trigger.

For the middle click action BTT needs to do various tricks to prevent accidental triggers which makes it a less reliable gesture. Usually it helps to increase the middle click area, but if it doesn't there is probably nothing you can do.

**Comment by scottmetoyer** [comment]
Awesome - will do. Thank you!
