### ISSUE TITLE
When working in X11 with Magic Mouse - focus gets lost

### ISSUE THREAD

**Issue by pjyoung** [folivoraAI/BetterTouchTool#2622]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at andreas@folivora.ai instead. 

---

#### Description of bug/feature request/question:
Focus lost randomly when working in a window using a magic mouse and Mac XQuartz

#### Device information:

Type of Mac: MacBook Pro, 15in, 2016
macOS version: 10.13.4
BetterTouchTool version: 2.425 (782)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Try to disable BTT for that application.
It's very possible these apps don't support the modern macOS apis correctly.

You may also try to just disable window snapping:
![image](https://user-images.githubusercontent.com/8820811/39563719-9e1390a6-4eb1-11e8-939a-c92f49f100f5.png)

**Comment by pjyoung** [comment]
Thanks again for fast response.

Have tried turning off window snapping - we will see how art works. Def need middle mouse for X11 ops though.
Principle reason I purchased BTT.

Cheers, Peter


On 3 May 2018, at 5:09 pm, Andreas Hegenberg <notifications@github.com<mailto:notifications@github.com>> wrote:


Try to disable BTT for that application.
It's very possible these apps don't support the modern macOS apis correctly.

You may also try to just disable window snapping:
[image]<https://user-images.githubusercontent.com/8820811/39563719-9e1390a6-4eb1-11e8-939a-c92f49f100f5.png>

**Comment by fifafu** [comment]
Problem is that X11 behaves vastly different from modern macOS, thus it is not really supported within BTT. Many things will probably work, but e.g. window snapping won't because X11 just doesn't support the new APIs.
