### ISSUE TITLE
Widget not visible when placed in scrollable main container

### ISSUE THREAD

**Issue by itsmyst** [folivoraAI/BetterTouchTool#2623]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at andreas@folivora.ai instead. 

---

#### Description of bug/feature request/question:
Please only post one bug or feature request per issue.

When I place a widget in the scrollable main container, it's not visible anymore. Though, when I choose to stick it to the left or right side of the touch bar, it's working just fine.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Touch Bar

#### Device information:

Type of Mac: 15-inch 2017 MBP
macOS version: 10.13.4
BetterTouchTool version: 2.467

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
There was one specific build that had an issue here. (It was only online for a few minutes but maybe you were unlucky and updated in that moment).
Try to check for updates again.

**Comment by itsmyst** [comment]
Checked for updates again and it found one (when I created this issue it didn't). I installed it and main container placement is working fine now. Thanks!
