### ISSUE TITLE
Custom Move/Resize Window's relative-to-screen coordinates do not use the *current* screen

### ISSUE THREAD

**Issue by meermanr** [folivoraAI/BetterTouchTool#2625]
I use multiple monitors with my Macbook, the exact number and arrangement depend on where I am working, but it is typically two landscape monitors in a vertical arrangement, or four landscape monitors in a "T" arrangement (the Macbook itself always being the bottom-most landscape monitor).

While attempting to configure BetterTouchTool's keyboard shortcuts to behave the same as [SizeUp](https://www.irradiatedsoftware.com/sizeup/) I've found that the action "Custom Move/Resize Window" always moves the window onto my Macbook's native monitor. I suspect this is because the "Relative to screen" values are being calculated with reference to my Macbook's native screen, and not the one the window is presently on.

A specific example of this is trying to configure the "Custom Move/Resize Window" action to centre a window and resize it to occupy most, but not all, of the screen (so I can see new messages arrive in the chat programs at the edge of the screen, for example). When I trigger this action on a window on the Macbook's native screen it does what I expect: the window is resized on the same screen to occupy most of the space, but when I trigger it on a window on one of my other monitors it jumps to the Macbook's native window and resizes to occupy most of *that* screen.

(I have interpreted "0 screens" to mean "do not move". Is that not correct?)

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

MacBook Keyboard

#### Device information:

Type of Mac: MacBook Pro (15-inch, 2017) with Touchbar
macOS version: 10.13.4
BetterTouchTool version: 2.467

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

Here is the JSON of the trigger + action, obtain using the context menu in the Gestures view:

**Edit**: Corrected JSON  (had initially copied from a different gesture, oops)

```
{
  "BTTTriggerClass" : "BTTTriggerTypeKeyboardShortcut",
  "BTTPredefinedActionType" : 251,
  "BTTPredefinedActionName" : "Custom Move\/Resize Window",
  "BTTActionMoveResizeConfig" : "{\"BTTOriginDisplay\":0,\"BTTChangeYOriginRelative\":0,\"BTTScreenOrigin\":0,\"BTTDirectionToMove\":0,\"BTTChangeHeightRelative\":1,\"BTTScreensToMove\":-1,\"BTTNewYAbsolute\":0,\"BTTNewXRelative\":0,\"BTTOriginToUse\":0,\"BTTNewWindowWidthRelative\":90,\"BTTChangeWindowWidth\":true,\"BTTNewXAbsolute\":0,\"BTTChangeYOrigin\":1,\"BTTUseVisibleFrame\":false,\"BTTChangeXOriginRelative\":1,\"BTTChangeWidthRelative\":1,\"BTTActiveOrHoveredWindow\":0,\"BTTNewWindowHeightRelative\":90,\"BTTChangeWindowHeight\":true,\"BTTNewYRelative\":0,\"BTTChangeXOrigin\":1}",
  "BTTActionMoveResizeName" : "Centre",
  "BTTAdditionalConfiguration" : "1835008",
  "BTTTriggerOnDown" : 1,
  "BTTEnabled" : 1,
  "BTTShortcutKeyCode" : 8,
  "BTTShortcutModifierKeys" : 1835008,
  "BTTOrder" : 6
}
```

**Comment by fifafu** [comment]
I think that was a bug. I'm not 100% sure if the fix was included in the last alpha I uploaded ( 2.469) but I think it was! (Otherwise it will be later today)
