### ISSUE TITLE
Dock icon is open even though this is disabled in the settings

### ISSUE THREAD

**Issue by cod3licious** [folivoraAI/BetterTouchTool#2626]
The BetterTouchTool icon is sometimes (randomly) showing in the dock even though in the advanced settings I have disabled this behaviour. 

I first noticed this behaviour when I disabled BetterTouchTool for the Sublime Text 2 editor, but I think this also coincided with some update of the app so I'm not sure what is really the culprit here.

#### Device information:

Type of Mac: MacBook Pro (Retina, 13-inch, Early 2015)
macOS version: 10.13.4 (17E202)
BetterTouchTool version: 2.426

**Comment by fifafu** [comment]
Hey, this should be fixed in this build: 
https://bettertouchtool.net/releases/btt2.426_recovery2.zip

I'll push it in a few days as autoupdate but you can download manually now.
