### ISSUE TITLE
Custom move/resize window failing to target window by title

### ISSUE THREAD

**Issue by JustinMullin** [folivoraAI/BetterTouchTool#2627]
The new "Custom Move/Resize Window" action is really great, but I've been unable to successfully configure it to target a particular window. I set the dropdown under Move/Resize to "Window With Title", but the action does not appear to do anything when run.

I have tried with a few different window titles (e.g. "Google Chrome", "Slack"), and a few variations of strings which I don't believe are the proper window title, to be sure ("chrome", "Chrome", "GoogleChrome", etc.). I have also confirmed that if I switch the dropdown to select "Active Window" or "Window Under Cursor" the action works successfully. If it's relevant I am attempting to trigger this action via a keyboard shortcut.

Running on:
2015 MacBook Pro
macOS: Sierra 10.12.6
BetterTouchTool: tested in 2.467 (825) and 2.471 (829)

**Comment by JustinMullin** [comment]
Almost immediately after opening this issue I realized that "window title" is probably not what I think it is. In the case of Chrome the window title is actually dynamically set based on the currently active tab. Choosing that value works with this action, but doesn't allow me to set an action to "move the Chrome window to such and such a position/size." Is there a way to do this currently as a triggered action?

**Comment by fifafu** [comment]
Hi Justin,

this is currently not possible but I think I can add a feature to "select" the frontmost window of an application to the next update.

**Comment by JustinMullin** [comment]
That'd be super cool! Please feel free to close this issue if preferable, it's not very accurate as I initially opened it.

**Comment by academo** [comment]
@JustinMullin Thanks a lot that would be amazing I am currently facing the same situation as @fifafu 

maybe a faster/easier would be adding a sort of regular expression to the window title? exp: `%Chrome%` when % would match any string like a `.*` ?
