### ISSUE TITLE
Wacom Bamboo CTH-460/K  Not Recognized

### ISSUE THREAD

**Issue by Wavewash** [folivoraAI/BetterTouchTool#2629]
#### Description of bug/feature request/question:
Wacom Bamboo CTH 460/K not recognized by BetterTouchTool.
Red text displays presenting:
"No Multitouch Capable Trackpad Found!"

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Wacom Bamboo CTH-460/K
(Trackpad)

#### Device information:

Type of Mac: Hackintosh
macOS version:  10.13.4
BetterTouchTool version: 2.466 (82)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
The wacom version displayed from System Preferences is:
5.3.7-6
All gestures in the system preferences wacom settings work fine. It just seems that Better Touch Tool does not recognize the tablet.

The previous version of BTT in the advanced setting had an experimental check box for wacom but it doesn't seem to be there anymore.

I'm a registered user - greatly appreciate all the work you've done with this. It's already really helped me a great deal even with this minor issue.

**Comment by fifafu** [comment]
currently Wacom support can only be enabled using this command (while BTT is quit):

```defaults write com.hegenberg.BetterTouchTool BTTWacomEnabled YES```

However I don't know whether the Bamboo CTH-460/K works.
