### ISSUE TITLE
Feature Request: Smooth Dragging Gestures

### ISSUE THREAD

**Issue by piotrnikov** [folivoraAI/BetterTouchTool#2630]
Hi!!
I just saw that you've added Finger Swipes and it's awesome :)
Just a thought: Is it possible to add a "smooth" gesture that wouldn't be a swipe but a slow directional movement (like a scroll like movement I guess)? Or does one already exist? I think it's officially called "dragging" but I didn't see any existing gestures in the preferences... 
It'd be awesome to control sound volume/screen brightness gradually as opposed to by big steps...
Thanks!!

Piotr

**Comment by fifafu** [comment]
Hi Piotr,

the swipes already do smooth scrolling.
I think if you assign the "Volume Up/Down (small steps)" predefined action it will be pretty good by default.
In the advanced settings of the gesture you can choose how often it will trigger based on the moved distance.

If that doesn't work for you, there is an option to trigger an apple script on every "step" and decide in the script what to do. I will soon add some examples on how to use that to the documentation.

**Comment by piotrnikov** [comment]
Hi Andreas,
Thanks for the prompt response :)
I just tried the setting you suggested (it's "Repeat assigned action while fingers are touching the trackpad", right?).
It works nicely but it's not based on the moved distance correct? More on how long my fingers stay on the trackpad?
Just to be sure I'm not missing out on another setting...
Thanks!

Piotr

**Comment by fifafu** [comment]
Ah sorry I thought you were talking about the new Touch Bar swipes (they have been added in the new alpha).

For the trackpad there is currently nothing like this unfortunately. It may come in the future but not in the near term as it is complicated to do with the current implementation.
