### ISSUE TITLE
BTT Asks for Access to Reminders after Wake-Up

### ISSUE THREAD

**Issue by chrisparker787** [folivoraAI/BetterTouchTool#2631]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at andreas@folivora.ai instead. 

---

#### Device information:

Type of Mac: MacBook Pro 15" 2016 
macOS version: 10.13.4
BetterTouchTool version: 2.471

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
I'm using the Script: Due Today to show my next reminder. I runs fine but when the Mac wakes up from sleep BTT shows this dialog:

<img width="514" alt="screenshot of path finder 04-05-2018 08-42-29" src="https://user-images.githubusercontent.com/38974378/39618221-af9c3dcc-4f7a-11e8-9c81-16058c1fdf54.png">

tell application "Reminders"
	set activeReminderNames to name of (reminders of list "Reminders" whose completed is false)
	set activeReminderDates to due date of (reminders of list "Reminders" whose completed is false)
	if activeReminderNames is not {} then
		set activeReminderNames to the reverse of activeReminderNames
		set activeReminderDates to the reverse of activeReminderDates
		if first item of activeReminderDates is less than or equal to (current date) then
			return first item of activeReminderNames
		else
			return ""
		end if
	else
		return ""
	end if
end tell

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Unfortunately this is not something that can be fixed in BTT.
Usually macOS remembers these decisions, but this is buggy in High Sierra. Sometimes it helps to delete the app completely, then granting the permissions again.

**Comment by chrisparker787** [comment]
Thanks Andreas!
