### ISSUE TITLE
Scrubbing bar widget in BTT

### ISSUE THREAD

**Issue by pa-friederich** [folivoraAI/BetterTouchTool#2632]
**Description of the feature request:**
Hi there,
It would be great to have a scrubbing bar as it appears when viewing a video in fullscreen like it does natively on Safari and YouTube. I have already implemented some media buttons for VLC but this would be a great addition. Is there already a way to do it or is it not possible to implement it in BTT? 
Thanks for your answer!

**Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):**
Touch Bar

**Additional information (e.g. related issues, screenshots, workarounds, etc.):**
MacBook Pro 15'' 2016
BetterTouchTool 2.466

**Comment by fifafu** [comment]
On the latest alpha you could use the new gestures to do this.
You can assign a custom apple script like this:

Move backward in VLC:
```AppleScript
on bttWidgetSliderMoved(percentageMoved)
	tell application "VLC"
		set current time to current time - 5
	end tell
end bttWidgetSliderMoved
````
Move forward:
```AppleScript
on bttWidgetSliderMoved(percentageMoved)
	tell application "VLC"
		set current time to current time + 5
	end tell
end bttWidgetSliderMoved
````

![image](https://user-images.githubusercontent.com/8820811/39627683-fbdc9de0-4fa6-11e8-8138-9d87d14dddd7.png)


In the main version you can use the custom slider widget with the same scripts assigned as action.
