### ISSUE TITLE
unable to choose license

### ISSUE THREAD

**Issue by sdfsdfsdfsdfsdfsdfsdfsdffwewerwrwerwer** [folivoraAI/BetterTouchTool#2634]
**Describe the bug**
I accidentally provided my old license when starting BTT.  Now it won't let me enter the new license anywhere.  It wants me to buy another license or continue using trial or downgrade to old version.

**Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):**

**Screenshots**

**Device information:**
- Type of Mac:
macbook pro mid 2015
- macOS version: 
10.13.4
- BetterTouchTool version: 
latest

**Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):**

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
hey, 

you can just double click your new license file or activation link. It will replace the old one.

**Comment by sdfsdfsdfsdfsdfsdfsdfsdffwewerwrwerwer** [comment]
awesome thanks
