### ISSUE TITLE
HTML overlay "Close when clicking outside" not working after using "reload" or "Inspect Element"

### ISSUE THREAD

**Issue by andyconlin** [folivoraAI/BetterTouchTool#2635]
**Describe the bug**
When an HTML overlay is showing (with "Close when clicking outside" setting checked), if the user right-clicks the HTML overlay area and selects either "Reload" or "Inspect Element", the ability to close the overlay by clicking outside seems to be cancelled.

**Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):**
N/A

**Screenshots**
(Clicks are not shown in this gif, but the mouse moving around outside the html overlay is clicking periodically.)
![htmloverlayclick](https://user-images.githubusercontent.com/24281063/39659470-c74dfb0c-4fe5-11e8-98cd-fdaf044eac12.gif)

**Device information:**
- Type of Mac: "MacBook Pro (13-inch, 2017, Four Thunderbolt 3 Ports)"
- macOS version: 10.13.4
- BetterTouchTool version: 2.467

**Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):**
Ways that I found to close the overlay in this situation was to quit BetterTouchTool. use the standard red 'x' button if using "Show window buttons," or re-trigger the overlay (which doesn't actually show the overlay again, but does remove the first overlay and shows the HUD for the second trigger (if applicable)

**Comment by fifafu** [comment]
Unfortunately this is expected and necessary to make the web inspector work. (I currently don't know of a good way to see when the inspector has been closed again as this is a system view).

However re-triggering the webview should hide it, so I'd recommend to do this for now.
