### ISSUE TITLE
FEATURE REQUEST: Custom keyboard shortcut for long press TouchBar button action

### ISSUE THREAD

**Issue by msx2010** [folivoraAI/BetterTouchTool#2637]
**Description of feature request:**
Presently BetterTouchTool can execute a trigger for long press touchbar button action. It would be great if it could simulate a keyboard shortcut directly without calling a trigger.

**Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):**

**Additional information (e.g. related issues, screenshots, workarounds, etc.):**

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
you can just assign a keyboard shortcut to the named trigger. 
This probably won't change in the near term as everything else would require a relatively complicated ui&data model change.
