### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by emongstad94** [folivoraAI/BetterTouchTool#2640]
Hey! I am using a bunch of 3d apps like "complete anatomy, complete heart" etc, where i use left-click and drag to spin the 3d object on the screen, and i need to right-click and drag to move the object on the screen. As far as i have tried, all 3d app software is using controls somehow similar to this. Therefore i am wondering wether you could add a feature to "right-click and drag/move", pretty much like the built in 3 finger click and move feature in the mac. Do you think its possible?

**Comment by fifafu** [comment]
You could e.g. use a three finger click combined with the new "Named Trigger" feature like this:
![image](https://user-images.githubusercontent.com/8820811/39915848-535755da-5509-11e8-8130-c2108036a25c.png)

![image](https://user-images.githubusercontent.com/8820811/39915883-644caf16-5509-11e8-8c4b-e8ce73080897.png)

![image](https://user-images.githubusercontent.com/8820811/39916146-fbcb5d4c-5509-11e8-8c9d-4b31b6413dc0.png)

It wouldn't be like the three finger drag, but you could click with three fingers, then remove two of them and move the mouse with the remaining finger. After you remove that last finger, BTT will trigger the right-mouse-up action.
