### ISSUE TITLE
Question before I buy

### ISSUE THREAD

**Issue by WillagerGA** [folivoraAI/BetterTouchTool#2642]
I would like to be able to move a file rather than copy it with drag and drop, without having to also use the keyboard. Can I set up BetterTouchTool to do that with a MagicTrackpad 2?

**Comment by fifafu** [comment]
Mh, well with the keyboard you can do it by pressing cmd +c and then option+cmd+v. So you could create two gestures that trigger these shortcuts. However this would probably not be very practical.

How did you imagine to do this?

**Comment by WillagerGA** [comment]
You are talking about using copy and paste.When doing drag and drop you would hold the CMD key as you drag and drop the file. I was hoping I could use your program to do this without having to hold down the CMD key. Maybe by using force touch?

**Comment by fifafu** [comment]
You could try something like this:

![image](https://user-images.githubusercontent.com/8820811/39915069-39c9c3f2-5507-11e8-87c7-2028a20edcf7.png)

![image](https://user-images.githubusercontent.com/8820811/39915090-4d75169a-5507-11e8-99b1-ea6a2f09d7c4.png)

![image](https://user-images.githubusercontent.com/8820811/39915140-6a8a12f8-5507-11e8-9ee1-e89fcc11975c.png)


However this will not block the original force-click unless you disable that in the system preferences. A better solution may be to use a three finger click like this:

![image](https://user-images.githubusercontent.com/8820811/39915412-2e4e986c-5508-11e8-9d58-e82b9a1803ab.png)

![image](https://user-images.githubusercontent.com/8820811/39915420-33e166a6-5508-11e8-8b14-2f0d577a90fc.png)
