### ISSUE TITLE
Custom Tap Sequence recorded incorrectly

### ISSUE THREAD

**Issue by zsiegel92** [folivoraAI/BetterTouchTool#2643]
**Describe the bug**

When I enter the custom tap sequence "4-3-1-2" it is recorded as "3-4-2-1". Other sequences work fine. I have a "4-3-2-1" and a "1-2-3-4" sequence, each of which I love using. Somehow, the sequence "4-3-1-2" is impossible to record. I click "rightmost finger" then "3. Finger" then "1. Finger" then "2. Finger" and somehow in my Gestures pane it appears as "3-4-2-1". Bizarre.

**Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):**

Magic Trackpad II

**Screenshots**

![screen shot 2018-05-05 at 2 57 43 pm](https://user-images.githubusercontent.com/26341564/39667895-bfc0cdf8-5074-11e8-8337-e5f44f64908a.png)
![screen shot 2018-05-05 at 2 57 59 pm](https://user-images.githubusercontent.com/26341564/39667896-bfda5ff2-5074-11e8-81da-6004bd5e88cb.png)

**Device information:**
- Type of Mac: MB Air 2013
- macOS version: 10.13.1
- BetterTouchTool version: 2.441 (802) 

**Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):**

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
this looks correct based on what you clicked.
The first finger you place is the right most one (thus a 1 on the right side).
The second touch is the finger left from that (thus a 2 at this position).
The third touch is the left most one thus a 3 at the first position.
