### ISSUE TITLE
Continuous gestures

### ISSUE THREAD

**Issue by vemv** [folivoraAI/BetterTouchTool#2644]
Hi!

Paying customer here (you can search `vemv` in your records).

Say I've set the `4-finger swipe up` gesture (Magic Trackpad) to the `Volume up` command.

It works, but I have to repeat the gesture for each 'step' of the volume adjustment.

It'd be intuitively better if with a single swipe gesture, the longer I perform the gesture, the more times the command is repeated.

e.g. `4-finger swipe up; 1 inch total swiped distance` -> volume goes up once.
e.g. `4-finger swipe up; 3 inches total swiped distance` -> volume goes up 3 times.

Hope it sounds like something that can be implemented at some point.

Cheers - Victor

**Comment by oliviermattelaer** [comment]
Hi,

In theory this should be possible from version btt2.470 ALPHA. (so not in the stable release yet)
There the developper introduce the following options:
Added option to repeat assigned actions for Touchpad Gestures while there are still fingers touching the trackpad after triggering the gesture. 

Actually, this option does not seems to work for me (btt2.472 on a macbook pro with touch bar with 10.13.4) so I would be interested to see if it works for you.

Cheers,

Olivier

**Comment by fifafu** [comment]
@Olivier which gesture did you try it with?

**Comment by oliviermattelaer** [comment]
I tried with three finger slide right/left.

**Comment by fifafu** [comment]
Could you attach a screenshot of your config?
This seems to work fine here:
![image](https://user-images.githubusercontent.com/8820811/39673304-f59909ac-5139-11e8-84e9-69b71e0c90d7.png)

**Comment by oliviermattelaer** [comment]
Ok sorry, looks like it was a miss-understanding on my side.
I failed to understand that I had to continue swiping to have the action to retrigger.
Stopping swiping (with the fingers still on the trackpad does not seem to be enough).

Sorry,

Olivier

**Comment by fifafu** [comment]
That's weird, it should be enough (after swiping far enough to trigger the action once)

**Comment by vemv** [comment]
Tried out! works.

I found two issues (the former being more objective than the latter):

* I can tweak the sliders while the checkbox is unchecked. This lead me to a frustrating experience where what I was doing had no effect.
* Acceleration could be taken into account. That's how e.g. the iPod has always worked - it's part of the 'Apple experience' :) otherwise it can be tedious to adjust the system audio volume by swiping.

Ideally one could have both fine- and coarse- grained volume control with the same gesture, by leveraging acceleration.

Thanks - Victor

**Comment by fifafu** [comment]
Currently the gestures in BTT don't support acceleration or any other similar measure, because they are discrete. Currently the repeat is completely time based.

It is quite complicated to change that, but for future versions I definitely plan to add some real "continuous" gestures. It's not for the near term though.

I'll fix the checkbox issue!

**Comment by vemv** [comment]
Perfect, understood.

Thank you Andreas!
