### ISSUE TITLE
Add option to move fullscreen window to another monitor

### ISSUE THREAD

**Issue by JulyIGHOR** [folivoraAI/BetterTouchTool#2646]
**Description of feature request:**

1) play YouTube on current monitor
2) press fullscreen button to view video fullscreen
3) press hotkey action to move current fullscreen workspace to next monitor with keeping it fullscreen

Currently there is option to move current window to next monitor, but it does not works with fullscreen YouTube video.

**Comment by fifafu** [comment]
Unfortunately I don't know a way that would allow me do this ;-(
