### ISSUE TITLE
Pressing Control/Option Shows BTT when Hidden

### ISSUE THREAD

**Issue by CarterVE** [folivoraAI/BetterTouchTool#2647]
**Describe the bug**

When I have hidden the BTT bar in favor of the regular touch bar (used for certain apps), if I press option or control (buttons I have configured for certain functions) the BTT bar reappears. Is there a way to disable this, so I only toggle between the BTT bar and the default bar with the set trackpad shortcut I have set? If not please add this option! Thanks!

**Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):**

Touch Bar

**Screenshots**

**Device information:**
- Type of Mac: MacBook Pro 15" 2017
- macOS version: 10.13.3
- BetterTouchTool version: 2.467

**Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):**

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Could you check whether v2.473 alpha fixes this?

**Comment by CarterVE** [comment]
Yes the 2.473 alpha fixes the issue, thank you so much!!
