### ISSUE TITLE
Move Right/Left a Space action becomes more sluggish until BTT is restarted

### ISSUE THREAD

**Issue by antontsvil** [folivoraAI/BetterTouchTool#2648]
**Describe the bug**
The bug happens when using the predefined actions Move Right(or Left) a Space;
The issue is the animation of switching between spaces becomes more and more sluggish the longer BTT is running (By sluggish I mean not only does it take an extra second to start the transition, but the transition is not smooth and loses frames). I've concluded this is a BTT specific problem, and not the system slowing down for 2 reasons :
* While switching via BTT's shortcut is sluggish, the system shortcut will still switch smoothly
* Restarting BTT alone will solve the issue, until a couple of hours pass and the switching becomes sluggish again.

**Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):**
I've only tested using modifier + mouse scroll binding. I'm **not** using a trackpad, just a wireless usb logitech mouse.

**Screenshots**
My bindings
![screen shot 2018-05-07 at 4 56 26 pm](https://user-images.githubusercontent.com/9003682/39724757-a4f1309a-5217-11e8-94ff-a947a73b715a.png)

**Device information:**
- Type of Mac: Macbook Pro 2016 15 inch
- macOS version: High Sierra 10.13.4
- BetterTouchTool version: 2.466

This bug has been present for as long as I've been using BTT, several months to a year. It's consistent enough that before I begin my day (after leaving the mac on overnight) I immediately restart BTT to get the smooth animations back.

**Comment by fifafu** [comment]
Mhh all BTT does is call the system shortcut, I currently don't see how that could behave differently than when being triggered by BTT :-(

**Comment by antontsvil** [comment]
Seems like after I posted this bug it's stopped happening? Very odd, unless anyone else is experiencing this I'm just gonna close it.
