### ISSUE TITLE
Lost all my settings after this recent update

### ISSUE THREAD

**Issue by bli0219** [folivoraAI/BetterTouchTool#2649]
Not expecting them back, just reporting this issue.

**Comment by fifafu** [comment]
Hey, which update?

BTT keeps various backups in case they are really gone.

**Comment by bli0219** [comment]
2.467 (825) is my current version.

**Comment by fifafu** [comment]
Could you send me the contents of this folder ~/Library/Application Support/BetterTouchTool to andreas@folivora.ai? (The Library folder is hidden by default you can go there by clicking the "Go => Library" menubar item in Finder.

**Comment by fifafu** [comment]
I have added some instructions on how to restore one of the automatic backups:
https://docs.bettertouchtool.net/docs/restoring_automatic_backups.html
