### ISSUE TITLE
Names of Named Triggers are not being assigned

### ISSUE THREAD

**Issue by githubniwis** [folivoraAI/BetterTouchTool#2650]
After an upgrade to version 2.47(831), name of named trigger can  be noted in the field with title “Named trigger name“, but disappears after saving.
The HUD title and HUD detail text are being saved.
In the default.json file: "BTTTriggerTypeDescription" : "Named Trigger: XYZ" is missing

**Comment by fifafu** [comment]
Sorry, this is now fixed in 2.474!
