### ISSUE TITLE
BTT Randomly Freezing

### ISSUE THREAD

**Issue by CarterVE** [folivoraAI/BetterTouchTool#2651]
**Describe the bug**

Sometimes (randomly as far as I can tell) BTT will just stop updating. Strangely, when I use the trackpad shortcut I have configured to toggle the BTT touch bar, instead of toggling the touch bar it appears to toggle to BTT again but the scripts then refresh. I notice this because I have a custom time AppleScript widget which will stop updating. 

If I enter the same trackpad shortcut again BTT then toggles. This seems to occur when I haven't used my keyboard in a little while, but I'm not sure if that's exclusively the cause. Sorry if this description isn't very helpful, I can send my current preset if that helps! 

**Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):**

Touch Bar, Trackpad

**Screenshots**

**Device information:**
- Type of Mac: MacBook Pro 15" 2017
- macOS version: 10.13.3
- BetterTouchTool version: 2.473

**Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):**

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
This issue was moved to https://community.folivora.ai/t/btt-randomly-freezing/72

**Comment by fifafu** [comment]
Sorry, please ignore the previous message. The migration didn't work correctly, for now the issues will stay here.
