### ISSUE TITLE
FEATURE REQUEST: Ability to change and display keyboard layout by BTT

### ISSUE THREAD

**Issue by msx2010** [folivoraAI/BetterTouchTool#2652]
**Description of feature request:**
It would be very great if BTT could change keyboard layout and display current keyboard layout in TouchBar widget. Also it would be very useful if BTT could set default keyboard layout when activating specific application, for example when activating Launchpad, Browser and XCode set layout to 'English', when activating Word application set keyboard layout to some pre-defined.

**Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):**

**Additional information (e.g. related issues, screenshots, workarounds, etc.):**

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
See https://github.com/folivoraAI/BetterTouchTool/issues/680 (there is also a solution on how to achieve that posted there)

Application activation triggers will be added soon.
