### ISSUE TITLE
BetterTouchTool shortcuts not working randomly when wake up from sleep.

### ISSUE THREAD

**Issue by chrisduong** [folivoraAI/BetterTouchTool#2655]
**Describe the bug**
BetterTouchTool shortcuts not working randomly when wake up from sleep.

**Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):**

Keyboard shortcuts

**Device information:**
- Type of Mac: macbook pro touchbar 2016
- macOS version:  10.13.4
- BetterTouchTool version:  2.467

**Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):**

**Comment by fifafu** [comment]
This issue was moved to https://community.folivora.ai/t/bettertouchtool-shortcuts-not-working-randomly-when-wake-up-from-sleep/70

**Comment by fifafu** [comment]
Sorry, please ignore the previous message. The migration didn't work correctly, for now the issues will stay here.

**Comment by chrisduong** [comment]
Hi,

Could you show me how I can enable BTT debugging mode for troubleshooting this issue

**Comment by chrisduong** [comment]
it is still happening
