### ISSUE TITLE
MiddleClick via Keyboard no longer working through TeamViewer

### ISSUE THREAD

**Issue by ingski** [folivoraAI/BetterTouchTool#2656]
**Describe the bug**
I used to generate a mouse middle click by typing "ctrl-cmd-P" through TeamViewer on my iPhone. 
For some reason this does not work any more since some weeks ago. Might be that there was a TeamViewer update involved before.

I tried with F1 instead but was not lucky.

**Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):**
Shortcut originated though TeamViewer on remote iOS device

**Screenshots**
![bildschirmfoto 2018-05-08 um 13 02 08](https://user-images.githubusercontent.com/39086798/39753948-db6e7034-52c0-11e8-9271-a9512e576eb6.png)

**Device information:**
- Type of Mac: MacBook Pro
- macOS version:  High Sierra 10.13.4
- BetterTouchTool version: 2.475

**Comment by fifafu** [comment]
Probably the Teamviewer app sends the shortcuts at a "too high" level. You could try to enable the old shortcut implementation in the advanced preferences, which should be able to catch them:
![image](https://user-images.githubusercontent.com/8820811/39754195-aaa8dc9a-52c1-11e8-967f-709a53329dc3.png)

**Comment by ingski** [comment]
Great hint. This did the job 👍. Thanks a lot 😀.
