### ISSUE TITLE
Copy Gestures

### ISSUE THREAD

**Issue by snemias** [folivoraAI/BetterTouchTool#2657]
Hi
Is it possible to copy gestures? I'd like to set a bunch of very similar gestures with "attached additional actions". It would simplify my life if I can duplicate already existing gestures.
Thanks
Simon

**Comment by fifafu** [comment]
cmd+c & cmd+v ;-)

**Comment by snemias** [comment]
I swear I tried this ... :) But now it works. Thanks.

**Comment by fifafu** [comment]
There was a bug that sometimes caused this to stop working. Should be fixed in the latest alpha version.
