### ISSUE TITLE
Smooth zoom in Apple Preview using Magic Mouse?

### ISSUE THREAD

**Issue by wuschiba** [folivoraAI/BetterTouchTool#2658]
Hi,

I'm trying to achieve what is possible with the Magic Trackpad in Preview using a Magic Mouse or rather close to that: **Smooth zoom**.

In Preview you can pinch-to-zoom on the Magic Trackpad to zoom in and out of images and pdf files.
How can I do this with BetterTouchTool for the Magic Mouse (2)?

What I was able to do in BTT: Set Ctrl and + sign to Ctrl and Scroll Up gesture. But that only gives me zoom in intervals (keyboard shortcut) which is not really satisfactory. It is not smooth like using touch.

**What I want is** to use smooth zoom like for example in Microsoft Word (Ctrl and scroll) or the Maps app (!) of macOS (Shift and scroll) or Safari (Ctrl / Command and scroll). How do I do that with BetterTouchTool in Preview app?

You already demonstrated that on _Youtube_ using pinch-to-zoom but I wasn't able to reproduce this: 
https://www.youtube.com/watch?v=31RcNcPXm4M

Maybe you could also update the description of the video on how to do this.

Thanks in advance!

**Comment by fifafu** [comment]
Unfortunately this is currently not possible anymore. The video is from an old version of macOS were this was still working, but the APIs have changed a bit and now this approach causes many problems.

Unfortunately Apple has no public way to generate these zoom events :-(

**Comment by wuschiba** [comment]
Wow, that was quick!
It's a pity but at least I can now stop trying to do that somehow (I already searched Google for hours).

Thanks a lot for your answer! You are doing a great job! :-)
