### ISSUE TITLE
Execute named trigger - only after no touch for x seconds not "sticking".

### ISSUE THREAD

**Issue by DavidMBrown** [folivoraAI/BetterTouchTool#2659]
**Describe the bug**
In the Touchpad Gesture options dialog (accessed by clicking the gear to the left of the Touchpad Gesture Menu), the setting for "Only execute named_trigger after no touch for x seconds:" does not retain it's setting after closing the dialog. 
**Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):**
Magic Trackpad 2

**Screenshots**

**Device information:**
- Type of Mac: Mac Pro, 10 core, 64GB RAM, 1TB SSD, Raedon Pro Vega 64 16GB
- macOS version: macOS 10.13.4 with Supplemental Update (17E202)
- BetterTouchTool version: 2.475 (833)
[BetterTouchToolDebug.zip](https://github.com/folivoraAI/BetterTouchTool/files/1984977/BetterTouchToolDebug.zip)

**Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):**

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Thanks for reporting! Should be fixed in 2.476 alpha
