### ISSUE TITLE
Window/dropdown/menu sometimes stuck to cursor

### ISSUE THREAD

**Issue by FearNaBoinne** [folivoraAI/BetterTouchTool#2663]
#### Description of bug/feature request/question:
Since installing BTT (and I have seen that on previous re-installs on both this MacBook Pro and another one) it sometimes (but regularly enough to be irritating) a Window, dropdown list or menu will get stuck to the cursor and be dragged around with it. I created a special gesture that uses "Start/Stop moving" to be able to get out of it. 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
MacBook Trackpad

#### Device information:
Type of Mac: late 2017 15" MBP with Touchbar, late 2013 MBP 13" 
macOS version: High Sierra 
BetterTouchTool version: 2.500, but also seen this in earlier versions

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
N/A

**Comment by fifafu** [comment]
Do you have any other app related to keyboard or mouse events installed? Sometimes they can conflict with BTT and cause such issues. Unfortunately there is no real solution to this...

**Comment by FearNaBoinne** [comment]
Weird, I responded to this, but do not see my response at all!!!!

No, no other apps doing mouse or keyboard events!
