### ISSUE TITLE
4 questions about your very productive app :-)

### ISSUE THREAD

**Issue by Saninl** [folivoraAI/BetterTouchTool#2665]
<img width="813" alt="schermafbeelding 2018-05-09 om 16 53 28" src="https://user-images.githubusercontent.com/39129440/39821888-8b2779ec-53a9-11e8-80de-7788c366edc9.png">

1.
When I press my lovely cup of coffee, I would like that my Macbook locks, and put the screen on black. Unfortunately, that does not work. It only goes on black, and when I press a key: we are back in. When I remove the additional action, the Macbook does lock down, but as you can guess: no black screen. Can somebody help me with that?

2. 
Even after a reinstall of both the app Franz and BTT, the Mac build-in emotion shortcut does not work. When I press ctrl + cmd + space, no window will pop up. Even when I try to build in a line in BTT to specify that shortcut, it will not work. Anyone? 

3.
(how) Is it possible to remove all the standard control shortcuts (e.g. brightness, sound) when I press CMD (what is the trigger for my personal BTT touchbar strip)?

4
(how) Is it possible to show a HUD overlay when I press on a trigger (e.g. battery icon) on my personal BTT touchbar strip?

Thanks in advance!

**Comment by fifafu** [comment]
1.) I think if you configure it the other way around it should work:
![image](https://user-images.githubusercontent.com/8820811/39914379-2ebf30c0-5505-11e8-8359-fe44e6e78174.png)

2.) This shortcut is not influenced by BTT unless you explicitly override it. Probably there is some other app blocking it. What shortcut does the edit => emoji menu item show for you?
![image](https://user-images.githubusercontent.com/8820811/39914422-4da0c1c0-5505-11e8-99e7-7eeaa386dc30.png)

3.) You can choose to hide the macOS control strip in the preferences:
![image](https://user-images.githubusercontent.com/8820811/39914547-9b8d24f0-5505-11e8-88a8-08535f549a4a.png)
Then you can create triggers and assign modifier keys to them in the advanced configuration (see screenshot for 4.)


4.) Yes: 
![image](https://user-images.githubusercontent.com/8820811/39914512-7b72512c-5505-11e8-92e7-bcb5edcec761.png)

**Comment by Saninl** [comment]
[image: Schermafbeelding 2018-05-22 om 13.43.58.png]
2) As you can see, no Emoji-shortcut..?

3) Thanks! Wow! I thought that I would be lost the control strip forever.
But it is only when the BTT-bar is visible. Fantastic!

4) I mean if it is possible to show, for example; the current song on
Spotify, the current battery level, when I activate the HUD. So not just a
plain text, but more than that. Is that possible?

Greetings,
Sander

Op vr 11 mei 2018 om 10:26 schreef Andreas Hegenberg <
notifications@github.com>:
