### ISSUE TITLE
Trigger Gesture in "Other Tab" is not being saved

### ISSUE THREAD

**Issue by niklasfink** [folivoraAI/BetterTouchTool#2666]
**Describe the bug**
In the "Other" tab in the settings, when adding a new Trigger and trying to select a gesture (such as "Move Mouse To Bottom Left Corner"), BTT is not saving the gesture. It works for some, but not for all. Video showing the bug: https://cl.ly/0V2o403H0W2k

**Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):**
x

**Screenshots**
![image](https://user-images.githubusercontent.com/1809301/39832134-b5820d98-53c6-11e8-8e2a-b3d4b224831a.png)

**Device information:**
- Type of Mac: MBP with Touchbar 2017
- macOS version: 10.13.4
- BetterTouchTool version: 2.500 (835)

**Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):**
x

**Comment by fifafu** [comment]
Should now work in v2.502!
