### ISSUE TITLE
Moving and resizing has become wonky

### ISSUE THREAD

**Issue by paulduv** [folivoraAI/BetterTouchTool#2667]
**Describe the bug**
BTT was installed on a clean install of a mid 2014 Macbook Pro. Window moving and resizing worked as expected. However, at some point in that first 24 hours, Window moving and resizing has become very unpleasant to use, as window movement randomly speeds up and slows down, and unevenly "chases" the cursor. I tried purchasing and installing the latest BTT, to no avail. 

**Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):**
Both trackpad and Apple mouse

**Screenshots**

**Device information:**
- Type of Mac: Macbook Pro 2014
- macOS version: High Sierra, 10.13.4
- BetterTouchTool version: 2.500

**Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):**

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
try to restart your Mac. sometimes the necessary system APIs behave strangely. A restart usually fixes this.

**Comment by paulduv** [comment]
Attachment available until Jun 8, 2018
Thanks for the suggestion. No luck.

In case this is useful to you, here’s a video of my screen in action. I’ve used BTT for years, and window moving has always been somewhat less snappy via BTT, but reasonable. This quite different — more of a random molasses kind of thing.

Order of movement:
• Native title bar drag
• Native window resize
• BTT drag
• BTT resize (works fine)

Shortcut keys:
Resize: command, shift
Move: command, option, shift


Of course I have no idea about such things, but this movement is reminiscent of the somewhat wonky motion that’s been introduced in High Sierra when triggering Mission Control via trackpad gestures (in the built-in trackpad preferences.) 

By the way, BTT moves windows with the usual speed on my 2010 laptop running El Capitan.



Cheers,

Paul


Click to Download
 <https://www.icloud.com/attachment/?u=https%3A%2F%2Fcvws.icloud-content.com%2FB%2FAQbkwqpZ_b09-B6lR9I2gnQLRO4kAXv5Bu1beg30cjB-CY3VUDg1joO4%2F%24%7Bf%7D%3Fo%3DAlntN4ahxPihJazDC7HWm4s9x8iTvsUJI_e2MdDP0CKp%26v%3D1%26x%3D3%26a%3DB9FQ2pYxdAvLSJ3PRRW66ibFRgviAxOyQwEACAHIAP9OaGeXA1MJQw%26e%3D1528493923%26k%3D%24%7Buk%7D%26fl%3D%26r%3D2DBA95D8-4078-47A8-B763-AFE944185105-1%26ckc%3Dcom.apple.largeattachment%26ckz%3D7B87F47A-BE81-41F8-B0E0-C699D3A818B3%26p%3D59%26s%3DqLmctCtDlTTrVK4FBdADC3VEfZs&uk=I6i1AO8WG2HJA3YNLkEujg&f=oWfTQd%2B%25SgObckt1ElcKFg.MOV&sz=20212072>oWfTQd+%SgObckt1ElcKFg.MOV
20.2 MB

**Comment by fifafu** [comment]
Weird. There hasn't been a change to BTT's window handling code. Can you think of any other software you installed recently that could conflict?

**Comment by paulduv** [comment]
I installed:

• Adobe Illustrator
• Adobe Photoshop
• Rhinoceros
• VLC
• Final Cut Pro

To be honest, I’m second-guessing myself now as to whether the window movement was ever ok on this new install on High Sierra.

By the way, I was googling the issue a little, and this user’s description is quite similar, although his solution didn’t work for me.

https://github.com/folivoraAI/BetterTouchTool/issues/1827 <https://github.com/folivoraAI/BetterTouchTool/issues/1827>

(user: Docmars)

Again with no real understanding, it definitely seems like some conflicting movement “instructions” rather than a performance thing. Something that’s new in High Sierra is that subtle window snapping at display edge. To take an uneducated guess...

(As noted before, things are perfectly smooth on window resizing.)

**Comment by fifafu** [comment]
I think the behavior your describe might be normal (I couldn't watch the video you made because the link says "Bad Gateway")

The system API's BTT needs to use are relatively slow, but it depends a lot on the application. E.g. moving TextEdit should be pretty fast, but moving more complex windows can be a bit slow causing this "following the mouse cursor" effect. This is something Apple would need to improve unfortunately.

**Comment by paulduv** [comment]
I’ve installed Flexiglass for the functionality of moving and resizing windows. FYI, it runs just about as smoothly as native window dragging and resizing.

Having said that, I remain a longtime fan of BTT.

**Comment by fifafu** [comment]
They just move the window twice the distance at a time and modify the mouse position at the same rate. This makes it seem faster but also loses precision. But I can definitely add this as an option if you prefer this behavior :-)

**Comment by paulduv** [comment]
Hunh, that’s rather interesting.

But as a troubleshooting thing, if this app is not appreciably smoother than BTT, then I guess the problem lies with my computer in particular.
