### ISSUE TITLE
BTT Crashes on Fullscreen

### ISSUE THREAD

**Issue by CarterVE** [folivoraAI/BetterTouchTool#2668]
**Describe the bug**

When I click the fullscreen button on the touch bar, BTT immediately crashes and does not restart without me doing it manually. I have multiple different buttons/widgets which use the built in BTT fullscreen operation, and all of them cause it to crash. This is a bug which appeared in the most recent release, as far as I can tell.

**Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):**

Touch Bar

**Screenshots**

**Device information:**
- Type of Mac: MacBook Pro 15" 2017
- macOS version: 10.13.3
- BetterTouchTool version: 2.500

**Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):**

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Weird, this seems to work fine here.
Could you check if there are any crashlogs in your Console.app => User Reports?

Maybe also try to restart your Mac, possibly the API BTT uses somehow got confused.

**Comment by CarterVE** [comment]
I both restarted the mac, and downgraded and then re-upgraded to the most recent version (2.503). I'm not sure which fixed the issue, but whatever the problem was it's been fixed!
