### ISSUE TITLE
Tooltip for floating HTML window

### ISSUE THREAD

**Issue by yeshymanoharan** [folivoraAI/BetterTouchTool#2669]
**Description of feature request:**
I think it would be really cool if the floating HTML window could be called as a tooltip window for some selected text in a similar fashion to the "data detector" and dictionary attached to the force click functionality on macOS. The reasoning for this is that the force click feature natively supported is lacking in functionality (force touch only selects one word, doesn't google the word, pulls up irrelevant results from itunes, etc), and with a custom tooltip window, we could make up for this lack in functionality. An fun use case for the tooltip would be enabling direct lookups of the selected text on relevant websites, like StackOverflow. 

**Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):**
Macbook Pro 2016

**Additional information (e.g. related issues, screenshots, workarounds, etc.):**
One issue that I think would be helpful in the development of this feature is being able to choose how the floating window spawns (currently the window spawns with the middle at the location of the cursor, but it would be nice to have the corner of the window by the cursor). Being able to pass in the location of the cursor to the HTML window would also be useful. The screenshot below is the force touch tooltip I am referring to and shows how useless it is. (imagine a tooltip that looks like this, curates data from multiple online sources, and returns a description of BTT instead of 'No Results Found')

<img width="429" alt="screen shot 2018-05-10 at 3 00 36 am" src="https://user-images.githubusercontent.com/11007399/39846870-5fc8da2a-53fe-11e8-87ca-28d46ea161fc.png">

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Unfortunately this is very complicated because not all apps support the same APIs :-(
The Apple Dictionary uses many tricks to achieve this, but I'm not sure if they can be done by third party apps.

Currently a way would be to do a chained thing that first copies the selected text to the clipboard, and then in the webview retrieves the clipboard content
