### ISSUE TITLE
Remove scrollbars on floating webview/html menu or window?

### ISSUE THREAD

**Issue by EDu-mac** [folivoraAI/BetterTouchTool#2671]
**Describe the bug**
If main "div" is larger than floating webview/html window, a white slider is shown at start.

**Affected input device : Trackpad

**Screenshots**
![capture d ecran 2018-05-10 a 07 54 04](https://user-images.githubusercontent.com/12591165/39854509-472ee1d8-5428-11e8-855a-de2a331e0313.png)

**Device information:**
- Type of Mac: macbook Air
- macOS version: 10.13.4
- BetterTouchTool version: 2.500 (835) 

**Additional information : May you add an "overflow:hidden;" option to hide this slider event if main window is moved to left or right.

**Comment by EDu-mac** [comment]
I thought that "overflow:hidden" should work but it is out of HTML/CSS main window and yes I created it.

**Comment by EDu-mac** [comment]
here is code : 

<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title></title>
		<style>
		
		.cadre {
			width:685px;
			height: 350px;
			border-radius:7px 7px;
			background: linear-gradient(to top, transparent, black);
			margin: -8px -8px ;		
		}
		.colonne  {
			width: 86px;
			height: 86px;
			padding:8px;
		}
		
		div {
			float:left;
			left:15px;
			width: 690px;
			height: 114px;
			margin:5px;
		}

		.zoom div img {
			transform: scale(1);
			transition: .4s ease-in-out;
		}
		.zoom div:hover img {
			filter: grayscale(100%);
			transform: scale(0.9) rotate(-5deg);
		}
		</style>
	</head>
	<body>
	<div class="cadre">
	<div class="zoom">
	<div class="colonne"><a href='javascript:' onClick="window.BTT.callHandler('trigger_named', {trigger_name: 'Action1' , closeFloatingHTMLMenu: 1} )"><img src="file:///users/.../..../picture1.png"/></a></div>		
	</div>
	</div>
	</body>
</html>

**Comment by fifafu** [comment]
maybe adding it to the body would help?
Like
```CSS
body {
   width:685px;
   height: 350px;
   overflow:hidden;
}
```

**Comment by EDu-mac** [comment]
I tried with : 

body {
   width:685px;
   height: 350px;
   overflow:hidden;
}

I can't move window  to right : 
![capture d ecran 2018-05-10 a 12 00 21](https://user-images.githubusercontent.com/12591165/39864676-a7b7e19a-544a-11e8-945b-0a87122534f8.png)

and

body {
   width:685px;
   height: 350px;
   overflow:auto;
}

![capture d ecran 2018-05-10 a 11 59 37](https://user-images.githubusercontent.com/12591165/39864700-bfec2438-544a-11e8-884a-ae73987737c5.png)

**Comment by fifafu** [comment]
what's wrong with the first one? This doesn't seem to show the scrollers anymore, or am I misunderstanding something?

**Comment by EDu-mac** [comment]
slider is still there

![capture d ecran 2018-05-10 a 12 26 52](https://user-images.githubusercontent.com/12591165/39865536-7b988af8-544d-11e8-8338-568bf705eb7e.png)

**Comment by fifafu** [comment]
Are you sure the overflow:hidden is added to the body?
It doesn't show up here anymore.

**Comment by fifafu** [comment]
```HTML
<title></title>
<style>
    body {
        overflow: hidden;
        width: 100%;
        height: 100%;
    }

    .cadre {
        width: 685px;
        height: 350px;
        border-radius: 7px 7px;
        background: linear-gradient(to top, transparent, black);
        margin: -8px -8px;
        overflow: auto;

    }

    .colonne {
        width: 86px;
        height: 86px;
        padding: 8px;
    }

    div {
        float: left;
        left: 15px;
        width: 690px;
        height: 114px;
        margin: 5px;
    }

    .zoom div img {
        transform: scale(1);
        transition: .4s ease-in-out;
    }

    .zoom div:hover img {
        filter: grayscale(100%);
        transform: scale(0.9) rotate(-5deg);
    }
</style>
</head>

<body>
    <div class="cadre">
        <div class="zoom">
            <div class="colonne">
                <a href='javascript:' onClick="window.BTT.callHandler('trigger_named', {trigger_name: 'Action1' , closeFloatingHTMLMenu: 1} )">
                    <img src="file:///users/.../..../picture1.png" />
                </a>
            </div>
        </div>
    </div>
</body>
```

**Comment by EDu-mac** [comment]
`
		<style>

		body {
    		overflow: hidden;
		width:100%;
		height:100%;
		}


		.cadre {
			width: 685px;
			height: 350px;
			border-radius: 7px 7px;
			background: linear-gradient(to top, transparent, black);
			margin: -8px -8px ;		
		        overflow:auto;
		} 
		
		.colonne  {
			width: 86px;
			height: 86px;
			padding:8px;
		}
		
		div {
			float:left;
			left:15px;
			width: 690px;
			height: 114px;
			margin:5px;
		}

		.zoom div img {
			transform: scale(1);
			transition: .4s ease-in-out;
		}
		.zoom div:hover img {
			filter: grayscale(100%);
			transform: scale(0.9) rotate(-5deg);
		}
		</style>
	</head>
	<body>
	<div class="cadre">
	<div class="zoom">
		<div class="colonne"><a href='javascript:' onClick="window.BTT.callHandler('trigger_named', {trigger_name: 'Action1' , closeFloatingHTMLMenu: 1} )"><img src="file:///.....internal.png"/></a></div>
		
	</div>
	</div>
	</body>
</html>`

**Comment by fifafu** [comment]
Ah it seems like it needs an additional container:

```HTML
<style>
    body {
        overflow: hidden;
    }

    .container {
        overflow: hidden;
        width: 100%;
        height: 100%;
    }


    .cadre {
        width: 685px;
        height: 350px;
        border-radius: 7px 7px;
        background: linear-gradient(to top, transparent, black);

        overflow: scroll;
    }

    .colonne {
        width: 86px;
        height: 86px;
        padding: 8px;
    }

    div {
        float: left;
        left: 15px;
        width: 690px;
        height: 114px;
        margin: 5px;
    }

    .zoom div img {
        transform: scale(1);
        transition: .4s ease-in-out;
    }

    .zoom div:hover img {
        filter: grayscale(100%);
        transform: scale(0.9) rotate(-5deg);
    }
</style>
</head>

<body>
    <div class="container">
        <div class="cadre">
            <div class="zoom">
                <div class="colonne">
                    <a href='javascript:' onClick="window.BTT.callHandler('trigger_named', {trigger_name: 'Action1' , closeFloatingHTMLMenu: 1} )">
                        <img src="file:///.....internal.png" />
                    </a>
                </div>

            </div>
        </div>
    </div>
</body>

</html>
```

**Comment by EDu-mac** [comment]
I change size but no slider and no movement.

![capture d ecran 2018-05-10 a 12 53 30](https://user-images.githubusercontent.com/12591165/39866504-458371d6-5451-11e8-8d63-67f4c5d9913d.png)
![capture d ecran 2018-05-10 a 12 53 43](https://user-images.githubusercontent.com/12591165/39866507-483fa6ba-5451-11e8-9988-34be7b7e424f.png)

**Comment by fifafu** [comment]
Ah I think it looks better here because I have "Show Scroll Bars" set to "automatically based on mouse or trackpad" in System Preferences => General.

This seems to be pretty tricky.
I found a workaround here: https://jsfiddle.net/VUSuZ/575/ that hides the scrollbars by moving them outside of the parent container like this:

```HTML
<style>
    div#box {
        height: 200px;
        width: 600px;
        overflow: hidden;
        padding: 10px;
        border-radius: 7px 7px;
        background: linear-gradient(to top, transparent, black);
    }

    div#content {
        height: 250px;
        width: 626px;
        /*
         * Uncomment to see scrollbar
        width:300px;
        */
        overflow-y: auto;
        display:grid;
    }

    .colonne {
        width: 86px;
        height: 86px;
        padding: 8px;
    }



    .zoom div img {
        transform: scale(1);
        transition: .4s ease-in-out;
    }

    .zoom div:hover img {
        filter: grayscale(100%);
        transform: scale(0.9) rotate(-5deg);
    }

    }
</style>

<div id="box">
    <div id="content">
        <div class="cadre">
            <div class="zoom">
                <div class="colonne">
                    <a href='javascript:' onClick="window.BTT.callHandler('trigger_named', {trigger_name: 'Action1' , closeFloatingHTMLMenu: 1} )">
                        <img src="file:///.....internal.png" />
                    </a>
                </div>
            </div>
            <div class="zoom">
                <div class="colonne">
                    <a href='javascript:' onClick="window.BTT.callHandler('trigger_named', {trigger_name: 'Action1' , closeFloatingHTMLMenu: 1} )">
                        <img src="file:///.....internal.png" />
                    </a>
                </div>
            </div>
        </div>
    </div>
```

Unfortunately there doesn't seem to be a way to just completely disable the scrollbars. However it looks much better when enabling "Automatic based on mouse or trackpad" in system preferences => General
![image](https://user-images.githubusercontent.com/8820811/39867084-85694242-5453-11e8-8b37-086c79ab4d73.png)

**Comment by fifafu** [comment]
Btw: I think you could save some code by putting the onClick handler directly on the div. You don't need the ```<a></a>``` tag.

Not important, just a note.

**Comment by EDu-mac** [comment]
Thank you

I didn’t know.
 <http://edu.mac.free.fr/> <http://edu.mac.free.fr/>
