### ISSUE TITLE
Two finger double-tap not working

### ISSUE THREAD

**Issue by githubniwis** [folivoraAI/BetterTouchTool#2672]
Os, BTT: Latest Version.
Mac mini 2011.
Trackpad two finger double-tap isn't working

**Comment by githubniwis** [comment]
Three and four finger double-tap aren't working either.

**Comment by fifafu** [comment]
They all seem to work fine here. ( and I don't think there has been a change to them)

What action have you assigned?

**Comment by githubniwis** [comment]
General: two finger double-tap: cmd-W, my most used gesture
iTunes: 4 f double-tap: go to current song, Works again!
When the two finger double-tap problems began, I noticed that, having opened multiple tabs in Safari, some closed correctly, others didn't. after a day or so, it stopped working completely in all the assigned programs(a lot).

**Comment by fifafu** [comment]
Have you already tried to restart your Mac?

**Comment by githubniwis** [comment]
Restart and PRAM

**Comment by fifafu** [comment]
Very weird.

If possible go to the about tab in BTT and click the "export debug information" button. This will create a folder called BetterTouchToolDebug on your Desktop. Would be great if you could send that to andreas@folivora.ai then I'll look into it.

**Comment by fifafu** [comment]
Unfortunately it seems to work fine here even with your exact settings :-(

Can you think of any system related settings you changed? Did you maybe enable three finger dragging? (This can be problematic in combination with BTT because it changes some basic parameters of the trackpad)

**Comment by githubniwis** [comment]
Tried everything, nothing helps.
Gonna rest the case(for now). 
Thanks a lot for your time.

**Comment by fifafu** [comment]
One more question: What kind of trackpad are you using?

**Comment by githubniwis** [comment]
When in Live View, 4 and 5 finger taps change the header text  in something like " last recog.... 09:138 5 Finger Tap" and the finger locations connected with lines are there, nothing wrong.

When after that I do a two finger tap, the two circles and line between them appears, but the header text remains the previous 5 finger one. Same goes for three finger tap.
Hope this helps.
tx

**Comment by githubniwis** [comment]
I feel guilty...
Did a "Reset All settings" and everything works.
Mea maxima culpa
