### ISSUE TITLE
cmd backspace (delete) not working

### ISSUE THREAD

**Issue by Wasser9** [folivoraAI/BetterTouchTool#2673]
Since the latest update, cmd backspace's not working anymore.

Trackpad

Type of Mac: Macbook Pro 15inch mid 2014
macOS version: newest
BetterTouchTool version: newest

cmd backspace still works manually without BTT, but not within it.

**Comment by fifafu** [comment]
What exactly do you mean? Could you show me your config?

**Comment by Wasser9** [comment]
hey andreas
thanks for your answer. see the screenshot below.

**Comment by Wasser9** [comment]
<img width="1440" alt="screen shot 2018-05-10 at 20 11 48" src="https://user-images.githubusercontent.com/26574621/39888369-e7820bd0-5494-11e8-8437-dc2bd332f016.png">

**Comment by Wasser9** [comment]
übrigens: deutsch geht auch ;)

**Comment by fifafu** [comment]
Komisch, das scheint hier korrekt zu funktionieren.
Liegt es vielleicht am Zwei Finger Klick und gar nicht an cmd+backspace?

Könntest du mir evtl. einen Export deines Presets an andreas@folivora.ai schicken?

**Comment by Wasser9** [comment]
Juhuuu, hab es endlich draussen! hatte (siehe screenshot) zweimal den finder drin ohne shortcuts. die rauslöschen hat das problem gelöst. danke trotzdem für deine hilfe!

gg, lino
