### ISSUE TITLE
Color coded presets

### ISSUE THREAD

**Issue by dzeruel** [folivoraAI/BetterTouchTool#2674]
**Description of feature request:**
Please only post one feature request per issue and use a descriptive title.

I really like to concept of presets and I recently use it a lot. I think it would make sense to have color codes on the presets so it would be clear which "side" preset is being active at the moment.
 
Black for the master preset, but when I activate the x preset it would show up as green, the other y preset would show up as yellow etc.

**Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):**

**Additional information (e.g. related issues, screenshots, workarounds, etc.):**

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Hi,

this will be added in the next version, I have already updated the data model for this :-)

**Comment by dzeruel** [comment]
Awesome, thank you! I am renewing my subscription!

**Comment by fifafu** [comment]
preset colors can now be selected in v2.502
