### ISSUE TITLE
New Magic Mouse Trigger

### ISSUE THREAD

**Issue by collinbell** [folivoraAI/BetterTouchTool#2675]
Similar to a tiptap, you could also do one stationary finger and the other slides up/down......

This would be a relatively simple gesture to enact.

**Description of feature request:**
Please only post one feature request per issue and use a descriptive title.

**Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):**

**Additional information (e.g. related issues, screenshots, workarounds, etc.):**

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
This issue was moved to https://community.folivora.ai/t/new-magic-mouse-trigger/71

**Comment by fifafu** [comment]
Sorry, please ignore the previous message. The migration didn't work correctly, for now the issues will stay here.
