### ISSUE TITLE
Snap Area buttons won't disappear

### ISSUE THREAD

**Issue by maximumwoltage** [folivoraAI/BetterTouchTool#2676]
**Describe the bug**
After using a bettersnaptool keyboard shortcut my snap area buttons won't fade away.
![image](https://user-images.githubusercontent.com/6847160/39870402-df7ebae6-5426-11e8-8582-f369e083c484.png)

MacBook Pro
<img width="262" alt="image" src="https://user-images.githubusercontent.com/6847160/39870454-0a0f5432-5427-11e8-8f94-935eba12cadf.png">

Bettersnaptool 1.8

**Comment by fifafu** [comment]
That's weird. Does this always happen?
