### ISSUE TITLE
Trackpad is not recognized after 2.441 update

### ISSUE THREAD

**Issue by hamiltoncolares** [folivoraAI/BetterTouchTool#2678]
My trackpad is not recognized anymore after 2.441 update. I'm a setapp user.

**Screenshots**
https://d.pr/i/pAf5Aj

**Device information:**
https://d.pr/i/yQhwqr
https://d.pr/i/XC1h87

[BetterTouchToolDebug.zip](https://github.com/folivoraAI/BetterTouchTool/files/1991903/BetterTouchToolDebug.zip)

**Comment by fifafu** [comment]
Your logs look strange for the setapp version. Are you sure you opened the setapp one?
Are you now running the BTT 2.500 version or 2.441?

**Comment by fifafu** [comment]
I just saw you are still on 2.441 in the screenshot.

Could you update to 2.500? 2.441 had various bugs.

**Comment by hamiltoncolares** [comment]
When the setapp version, I uninstalled my personal version and installed the setapp version. So, I only have this version.
https://d.pr/i/nMf9lO
https://d.pr/i/YK3eFD
I just asked for updates on setapp and it said that all apps are up to date. 
https://d.pr/i/DyFtU1

**Comment by fifafu** [comment]
Mhh, the 2.500 version should definitely be online in setapp
![image](https://user-images.githubusercontent.com/8820811/39875947-444c04ce-5472-11e8-9bc5-f59079362270.png)

**Comment by hamiltoncolares** [comment]
Strange.
https://d.pr/i/pngvf0
Do I have uninstall and reinstall it? 🤔

**Comment by hamiltoncolares** [comment]
I had to completely remove from setapp to install the 2.500 version. But, it still has the same bug.
https://d.pr/i/DbMGL8
https://d.pr/i/9b8U1a
My trackpad is working fine with macOS native gestures.
[BetterTouchToolDebug.zip](https://github.com/folivoraAI/BetterTouchTool/files/1992121/BetterTouchToolDebug.zip)

**Comment by fifafu** [comment]
That's really strange, internal trackpads should always be recognized correctly :-(

Could you try to restart your machine in case you haven't done that already? Maybe the system is somehow reporting wrong values to BTT.

**Comment by hamiltoncolares** [comment]
I've done many restarts. 😢

**Comment by fifafu** [comment]
Could you try this build? I made a little change based on an error log I saw in your debug information:
https://bettertouchtool.net/releases/btt2.501_debug.zip

**Comment by hamiltoncolares** [comment]
It show me this.
https://d.pr/i/iiOYZr

**Comment by hamiltoncolares** [comment]
Version 2.501. Can replace 2.500 for 2.501 on setapp folder?

**Comment by fifafu** [comment]
yes that should work!

**Comment by hamiltoncolares** [comment]
And the updates from setapp will stay coming?

**Comment by fifafu** [comment]
I don't know, but you can always delete that version and re-download from setapp if not.

**Comment by fifafu** [comment]
you can also copy it to the normal Application folder if you'd rather do that for testing

**Comment by hamiltoncolares** [comment]
That's ok. I'll stay tuned to make the next update manually. Thank you!

**Comment by fifafu** [comment]
I don't know whether my fix actually changes anything! It's just a shot in the dark :-)
Thus it would be great if you'd test. If it works I'll push an update to setapp.

**Comment by tburton31** [comment]
I'm having the same issue, Setapp user as well. Late 2013 Macbook Pro,

**Comment by fifafu** [comment]
If possible please also try https://bettertouchtool.net/releases/btt2.501_debug.zip and let me know whether that changes anything.

**Comment by tburton31** [comment]
Yep, that worked! Talk about a wicked quick bug fix, thanks.

**Comment by fifafu** [comment]
Perfect, thanks for testing! I'll do some refinements and submit the update to Setapp, so it should be there as a regular update tomorrow.
