### ISSUE TITLE
"Move mouse to position" bugs with "Relative to: text cursor/text selection"

### ISSUE THREAD

**Issue by justin-r-r** [folivoraAI/BetterTouchTool#2679]
I have started to try out the "Move mouse to position" predefined action, but there seem to be some cases when it does not function properly when using the "Relative to: text cursor/text selection" specification.

Expected behavior: Triggering should move mouse cursor to the location of the text cursor, or selected text (assuming offset coordinates set to 0,0).

Observed behavior: Partially works as expected, but only in some apps (TextEdit, Safari tested) but not others (Microsoft Word, Apple Mail tested). When it works, it does so only when text in text input fields is highlighted, and in Safari in text input fields when the text cursor is there, but no text is highlighted. Never works when text is highlighted that is not in a text input field (for example, doesn't work when text is highlighted on a webpage). 

I've tested this with both "Relative to: center of text cursor/text selection" and "Relative to: bottom right of text cursor/text selection"

Have only tested so far on MacBook Air, running 10.13.3, BTT 2.500

**Comment by fifafu** [comment]
Unfortunately I have observed the same :-(
I mostly tested on XCode where it was working nicely.

This probably means there is no reliable way to achieve this, so I will probably remove this again (or mark it as only working with some apps).

It's unfortunately there doesn't seem to be a reliable way to do this.

**Comment by justin-r-r** [comment]
Thanks for the quick response, Andreas! Good to at least know the status. Would love for the feature to at least stick around, as I do find this feature sometimes useful (even in its limited state).
