### ISSUE TITLE
BTT mouse corner does not work

### ISSUE THREAD

**Issue by hubgitname** [folivoraAI/BetterTouchTool#2680]
I wanted BTT to show me the mission control when I mouse over to the top left corner.
But it simply does not work. BTT doesn't recognize the gesture. pls see the screenshot.

<img width="814" alt="btt_mousecorner" src="https://user-images.githubusercontent.com/37636187/39910273-6109149c-54ab-11e8-833c-cb89344a0f8b.png">

**Device information:**
- Type of Mac: MacBook Pro 2015
- macOS version: 10.13.4
- BetterTouchTool version: BTT 2.500

**Comment by fifafu** [comment]
Thanks for reporting, this should now be fixed in 2.502
