### ISSUE TITLE
two finger and three finger Touch Bar gestures not detected

### ISSUE THREAD

**Issue by justplainlawr** [folivoraAI/BetterTouchTool#2683]
Created gestures for two and three finger swipes on the Touch Bar. 

I got it working  yesterday after I upgraded to BTT 2.50, but only after a full reboot of the machine.

Today upgraded to 10.13.5 developer beta version 4 and two and three finger swipes are not detected again.

**Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):**
Touchbar on MacBook Pro

**Screenshots**
![btt touchbar](https://user-images.githubusercontent.com/33459657/39928694-0a22db00-5504-11e8-823a-a8671336d50b.png)

**Device information:**
2016 MacBook Pro w/ Touch Bar
10.13.5 developer beta version 4
2.5000 (835)

**Comment by fifafu** [comment]
For this to work the BTT Touch Bar must be visible. It looks like you currently don't use any BTT touch bar configuration, thus the system bar is shown which unfortunately doesn't support gestures yet (I'm looking into options to make this work, but I have not yet found one that works on the latest macOS)

**Comment by justplainlawr** [comment]
I tried what you suggested... I got the two and three finger swipes to work once I toggled to show BTT Icon in Control Strip, but then stopped working after.

**Comment by fifafu** [comment]
The problem is that it will automatically hide again if you don't configure any button in BTT.

If you add some custom buttons it should be working. (you can do really cool stuff with custom buttons & widgets)

**Comment by justplainlawr** [comment]
Yeah I've added the recent apps widget and it feels and works great!

**Comment by msx2010** [comment]
May be some code from HapticKey app could help to implement gestures in system bar? https://github.com/niw/HapticKey

**Comment by fifafu** [comment]
No, they just listen for key presses, that is easy and not related to touch events unfortunately.

**Comment by fifafu** [comment]
Ah actually they try to listen for touches also, but this is not supported on the latest macOS anymore as far as I know. ( https://github.com/niw/HapticKey/blob/master/HapticKey/Classes/HTKTapGestureEventListener.m ). Also it's a performance killer unfortunately ;-(

**Comment by msx2010** [comment]
Understood. May be it is possible to integrate HapticKey into BTT? Presently I (and many other people) use it to together with BTT. It would be great have same functionality in BTT. ps. I also answered your question at issue #2543

**Comment by fifafu** [comment]
Ah actually the method works again in the latest beta of 10.13.5, so this would allow me to implement the gestures globally.

I  still don't like the performance impact of that approach, which is why I didn't really consider it so far ( it constantly uses approximately 2% CPU if you move your mouse using the trackpad or if you touch the Touch Bar - HapticKey does have that issue too). BTT already needs to do lots of stuff and an additional 2% CPU usage would be pretty bad for battery life ;-(

Maybe I'll add it as an option.

**Comment by Kanishkaz** [comment]
Based on your documentation, you can put these gestures in an invisible group. I tried doing that but the gestures stop working immediately after marking the group as invisible. Am I missing something?

**Comment by fifafu** [comment]
You still need to have some visible buttons configured in BTT, the gestures can be invisible, but BTT needs to show a touch bar.
