### ISSUE TITLE
BTT not replacing default touchbar

### ISSUE THREAD

**Issue by ichocobo** [folivoraAI/BetterTouchTool#2684]
I've been using BTT for six months happily but now my regular BTT touchbar is gone and it only shows the (shitty) regular macos touchbar. BTT is running and when I press the alt key it shows my secondary BTT touchbar as it does before. All keyboard shortcuts work as well.

Any ideas about what's going on?

**Comment by fifafu** [comment]
Maybe it's just hidden.
In general it's a good idea to have a keyboard shortcut in BTT and assign the "Toggle BetterTouchTool Touch Bar" action, to toggle the visibility.

**Comment by ichocobo** [comment]
You nailed it! Thanks!
