### ISSUE TITLE
FEATURE REQUEST: Dock-area (or user-defined desktop area) specific gestures

### ISSUE THREAD

**Issue by msx2010** [folivoraAI/BetterTouchTool#2685]
**Description of feature request:**
It would be great to have dock-area specific gestures. For example: four-fingers swipe down gesture over the window minimizes that window, but four-finger swipe down gestrure at the dock area minimizes the dock

**Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):**

**Additional information (e.g. related issues, screenshots, workarounds, etc.):**

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
You should be able to do that already:

![image](https://user-images.githubusercontent.com/8820811/39934586-9df5ce5e-5546-11e8-9b5d-95f694d2f006.png)

**Comment by msx2010** [comment]
Ok, thank you!

**Comment by msx2010** [comment]
Thanks for lightning speed to the answers!
