### ISSUE TITLE
Adjusting Volume Shifts Sound Balance

### ISSUE THREAD

**Issue by mergesort** [folivoraAI/BetterTouchTool#2686]
**Describe the bug**
When I adjust the volume via the volume widget it shifts my headphones sound balance to the left, rather than keeping it centered. Adjusting it via the native mechanisms available on macOS works just fine.

**Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):**
Touch Bar.

**Screenshots**

**Device information:**
- Type of Mac: MacBook Pro (Touch Bar)
- macOS version: 10.13.4
- BetterTouchTool version: 2.500

**Comment by fifafu** [comment]
Unfortunately I can not reproduce this. Is there anything special about your audio setup?
I have had a few such reports over the last year, but never found a way to reproduce it ;-(

**Comment by mergesort** [comment]
Looks like that fixed it. Not sure what caused it, but I'll close out this issue.

Thanks again!
