### ISSUE TITLE
Keys/Buttons get stuck + clicks are either delayed or occur in wrong location.

### ISSUE THREAD

**Issue by ChartrueseAubergine** [folivoraAI/BetterTouchTool#2687]
**Describe the bug**
Randomly keys and mouse buttons will get "stuck" in down state. Randomly clicks get delayed or their position gets modified (e.g. click at 100, 100; actual click even occurs at 200, 200). 

**Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):**
MacBook Pro keyboard/trackpad.

**Screenshots**
N/A

**Device information:**
- Type of Mac: MacBookPro14,3
- macOS version: 10.13.4 (17E202)
- BetterTouchTool version: Started in 2.500, still occurs in 2.503

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.
(I didn't restart since updating to 2.503. Trying now, but submitting b/c I don't want to lose the above text.)

**Comment by fifafu** [comment]
Usually this is caused when some other mouse/keyboard related app is conflicting with BTT. Most of the time there is no real solution to this but to only run one of the two apps ;-(

Can you think of any such app running on your machine?
