### ISSUE TITLE
Feature Request: trim whitespace in clipboard manager

### ISSUE THREAD

**Issue by colophonemes** [folivoraAI/BetterTouchTool#2688]
I frequently need to copy information from the web etc. and paste into a terminal or text editor. Sometimes these appear to be one-line strings, but in fact contain a line break at the end of the string. This can do weird things (like submit a command before I've finished writing it).

It'd be cool if the clipboard manager had an option to run a `trim()` function on the string when it's copied (or to have a predefined action to `Paste without whitespace`), so that `Some string\n` becomes `Some string`.

**Comment by fifafu** [comment]
There will soon be a way to pass the clipboard content to a javascript function before pasting, this will then e.g. allow to call trim() on it. I'll let you know when it's available

**Comment by colophonemes** [comment]
Amazing, that'd be perfect!
