### ISSUE TITLE
Gaps in App Switcher Widget

### ISSUE THREAD

**Issue by bentito** [folivoraAI/BetterTouchTool#2689]
**Describe the bug**
Some apps appear to show as blank spots in the Touch Bar App Switcher Widget

**Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):**
MacBook Pro Touch Bar

**Screenshots**
![image](https://user-images.githubusercontent.com/4449199/39951941-f169c624-555c-11e8-9be7-b8447fb3ba22.png)
![image](https://user-images.githubusercontent.com/4449199/39951950-01f85e74-555d-11e8-990e-c49a3d7043a6.png)

**Device information:**
- Type of Mac:MacBook Pro (15-inch, 2017)
- macOS version: 10.12.6 (16G1114)
- BetterTouchTool version: 2.503 (841)

**Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):**
From the widget setup screen, might be helpful:
![image](https://user-images.githubusercontent.com/4449199/39952000-9703f85c-555d-11e8-8fd1-db09eaa01522.png)

As a specific case, note that the icon for the Stickies app is missing, among others.

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
This issue was moved to https://community.folivora.ai/t/gaps-in-app-switcher-widget/78
