### ISSUE TITLE
Screencorner triggers wont select

### ISSUE THREAD

**Issue by fullmetalsheep** [folivoraAI/BetterTouchTool#2692]
**Describe the bug**
In "Other" area, screencorner triggers don't select when trying to assign it to something, see screenshot.

**Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):**
Macbook Pro 2017 13 inch, no touchbar

**Screenshots**
![3502b56a-ac74-4785-839f-40caa70828ec](https://user-images.githubusercontent.com/23723926/39964762-9d13d5a2-56be-11e8-9a10-26277a435a36.png)

**Device information:**
- Type of Mac: MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)
- macOS version:  High Sierra 10.13.4
- BetterTouchTool version: Setapp btt 2.5

**Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):**
I'm using the setapp version of btt (2.5) if it helps.

**Comment by fifafu** [comment]
Hey,

sorry this should already be fixed in the latest minor update. You may need to check for updates manually to receive it.

**Comment by fullmetalsheep** [comment]
Is that version 2.501? And how do i check manually check for updates if I'm using bettertouchtools via setapp? Thanks

**Comment by fifafu** [comment]
ah sorry on setapp it will probably appear later today!

**Comment by fullmetalsheep** [comment]
Perfect, thanks so much :)
