### ISSUE TITLE
TouchBar Icon: mute/unmute on a single icon / TouchBar Icons / BTT Workflow Community?

### ISSUE THREAD

**Issue by eggplantsplz** [folivoraAI/BetterTouchTool#2695]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at andreas@folivora.ai instead.

Not too well versed in applescripts - but I'm sure this can be done with initial and alternate logos. Would like ONE icon to show mute/unmute status like the original touchbar. 

Also, any way to get the original Apple TouchBar icons on BTT, and/or is there another repository of more high-def icons for use with BTT TouchBar?

Lastly, wondering if there is a community somewhere where people are actively sharing their BTT workflows? Would love some new ideas of what I can do to optimize my Mac experience.

**Comment by oliviermattelaer** [comment]
Hi,

Here is my setup:

In itself the applescript is very simple:
```
set curVolume to get volume settings
if output muted of curVolume is false then
	return "on"
else
	return "off"
end if
```
and the onclick applescript that I'm using:
```
set curVolume to get volume settings
if output muted of curVolume is false then
	set volume with output muted
	tell application "iTunes"
		pause
	end tell
	tell application "BetterTouchTool"
		refresh_widget "3D09A1C5-12E0-4F95-B4FB-12A105BA9BD2" 
		refresh_widget "BB441DD4-7ECA-450D-863D-BA53E51E3071" 
	end tell
	return "off"
else
	set volume without output muted
	return "on"
end if
```
You will notice that
when mutting, I also 
1) put itunes on pause.
2) refesh two widget (the play/pause button and the next track widget) 

Cheers,

Olivier 

PS: I have also configure my play/pause button to automatically unmute the computer/
PPS: the develloper of BTT will open (in principle very soon) a platform to share functionality.
In the meantime using google allow to find some people sharing their setup.
