### ISSUE TITLE
Switching to Dvorak switches shortcut key

### ISSUE THREAD

**Issue by vegasgeek** [folivoraAI/BetterTouchTool#2696]
This is an edge case, I realize that, but here's what I'm running into. 

I type in Dvorak and I use an external keyboard when I'm at my desk. I set up a handful of shortcuts while on my laptop. when I'm on my laptop, I have the keyboard language set to Dvorak. One of the shortcuts I created is essentially CTRL+OPTION+COMMAND+SHIFT+C = Open Chrome. 

When I plug in the external keyboard, I have to switch the keyboard language back to US, the shortcut changes automatically to CTRL+OPTION+COMMAND+SHIFT+I

**Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):**
MacBook Keyboard / External Keyboard

**Screenshots**
Here's a video showing what's happening: https://www.screencast.com/t/6jGl8A4mk

**Device information:**
- Type of Mac: Macbook
- macOS version: 10.13.4
- BetterTouchTool version: 2.503

**Comment by fifafu** [comment]
Unfortunately that's a known issue. (All the macOS APIs use the physical location of the key for shortcuts, thus if you change the layout the keyboard shortcuts will still work at the same "location" on the keyboard, but with different characters).

Maybe in the future there will be a specific action that allows to bind to characters instead (but this is complicated and error prone so it's not very high on my todo list unfortunately)

See https://github.com/folivoraAI/BetterTouchTool/issues/144

Currently the best solution would be to create two presets for the different keyboard layouts and toggle between them.
