### ISSUE TITLE
MacOS touchbar is always shown in v2.5

### ISSUE THREAD

**Issue by mikaelvasiliev** [folivoraAI/BetterTouchTool#2697]
I have custom touchbar widgets and button configured for use with and without modifier key. 
After upgrading from v 2.468 got this problem: the default (without modifier) buttons are never shown, instead I see default MacOS strip. Those with modifier key works normal. 
Disabling "Show MacOS control strip" option does't help.
My MacOS version: 10.13.4

**Comment by fifafu** [comment]
Your BetterTouchTool Touch Bar is probably just hidden.
In general it's a good idea to define a trigger (e.g. a keyboard shortcut to show/hide the custom touch bar using the "Toggle BetterTouchTool Touch Bar" predefined action.

**Comment by Timothee** [comment]
@fifafu does that mean there's no way to have the BTT TouchBar start automatically? It used to just do that before I upgraded. (and it was great 😄 )

**Comment by fifafu** [comment]
no, BTT remembers the last visibility state and restores that when starting. So if the BetterTouchTool touchbar is visible when quitting  BTT, it should also be visible when starting it again.
(Unless you have specified a application specific override)

**Comment by Timothee** [comment]
Sounds good, thanks!
