### ISSUE TITLE
Get button UUID via Applescript

### ISSUE THREAD

**Issue by GGRubbin** [folivoraAI/BetterTouchTool#2698]
I am working on an Applescript to create touchbar buttons that show current tabs in Google Chrome. I can create the buttons fine, but would need to delete the buttons after the tabs are closed so I don't end up with endless buttons in BTT. The delete method requires the UUID, which you get by right clicking the button in BTT. Is there a way to grab this UUID via Applescript without manual intervention?

#### Device information:

Type of Mac: Macbook Pro
macOS version: 10.13.3
BetterTouchTool version: 2.503

**Comment by fifafu** [comment]
When adding a new button, the Apple Script will provide the UUID as return value. This is currently the only way, in the future I'll probably add a function to get a list of all buttons.

**Comment by GGRubbin** [comment]
That should work for me I think, thanks!
