### ISSUE TITLE
preset sharing platform

### ISSUE THREAD

**Issue by sk777club** [folivoraAI/BetterTouchTool#2699]
hi, any news about preset sharing platform? Greetings, Sebastian

**Comment by fifafu** [comment]
This issue was moved to https://community.folivora.ai/t/preset-sharing-platform/32

**Comment by fifafu** [comment]
This issue was moved to https://community.folivora.ai/t/preset-sharing-platform/67

**Comment by fifafu** [comment]
Sorry, please ignore the previous message. The migration didn't work correctly, for now the issues will stay here.

**Comment by fifafu** [comment]
Btw. this will be the url of the sharing platform ;-)
It's basically online but the preset sharing part is not yet included. Will be sometime this week.
