### ISSUE TITLE
bug/feature: double tap for drag with resting right finger

### ISSUE THREAD

**Issue by iosonologio** [folivoraAI/BetterTouchTool#270]
I am having troubles to setup the magic mouse to perform easily dragging just by tapping.
I have setup left click bot for left tap and left TipTap. This allows left tapping also with right finger resting on mouse.

Dragging works well if I tap+(tap and hold) with only left finger on mouse. It fails if right finger is steady on mouse.

I like to have both index and middle finger on mouse at all time. An option to "hide resting finger" or similar, would be appreciated (to avoid the tiptap trick).

Also, if any user have found a way around it, I would be glad to know.
Best
Giovanni

MacBook Air (13-inch, Early 2015)
El Capitan
Magic mouse
BTT v 1.989

**Comment by fifafu** [comment]
This issue was moved to https://community.folivora.ai/t/bug-feature-double-tap-for-drag-with-resting-right-finger/84

**Comment by fifafu** [comment]
Sorry, please ignore the previous message. The migration didn't work correctly, for now the issues will stay here.
