### ISSUE TITLE
Modifier Key Sticky Key

### ISSUE THREAD

**Issue by CarterVE** [folivoraAI/BetterTouchTool#2700]
**Description of feature request:**
Please only post one feature request per issue and use a descriptive title.

I'm not sure if this is possible, but it'd be great to have the option to dictate a sticky key for modifiers keys in the touch bar. I use the modifiers to show different buttons/sliders, and it can be a pain to stretch to move sliders or hit buttons. If instead, I could just press the button rapidly twice or something, and have the TB buttons persist until I hit the key again, this would be very useful! Thanks!

**Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):**

Keyboard, Touch Bar

**Additional information (e.g. related issues, screenshots, workarounds, etc.):**

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
This issue was moved to https://community.folivora.ai/t/modifier-key-sticky-key/79

**Comment by fifafu** [comment]
Sorry, please ignore the previous message. The migration didn't work correctly, for now the issues will stay here.
