### ISSUE TITLE
The BTT Tool icon on touchbar is "unpressable" / "untouchable while seen when my 256GB 13" opens.

### ISSUE THREAD

**Issue by R3W1ND** [folivoraAI/BetterTouchTool#2701]
I have posted this bug on the past. I think someone asked me if it was repaired , but I wasn't able to answer.

**Comment by fifafu** [comment]
This issue was moved to https://community.folivora.ai/t/the-btt-tool-icon-on-touchbar-is-unpressable-untouchable-while-seen-when-my-256gb-13-opens/30
