### ISSUE TITLE
Move Window to Left/Right Monitors

### ISSUE THREAD

**Issue by emiliobusnelli** [folivoraAI/BetterTouchTool#2705]
**Description of feature request:**
Hello! I love bettertouchtool and I love watching it develop. I have been using BTT for a few months now to help fit my "power-user" necessities. I often work on my laptop which I first only had one external monitor but recently upgraded to 2 external monitors. The predefined action that allows us to set a gesture to move a window to our next monitor is amazing but I think it could be improved to identify which monitor you are trying to move it to. For example, my macbook sits in the middle of my 2 external monitors but I would like to move my window to the monitor to the right, but instead when I use the gesture assigned to it, it moves to the left screen, then I do it again to move it to the right screen. Is there a way to add a feature that can "identify" which screen the window is on, then set defined actions to move it to the left OR the right monitor? 

THANK YOU! THIS FEATURE WOULD BE AMAZING!

Emilio.

**Comment by fifafu** [comment]
This issue was moved to https://community.folivora.ai/t/move-window-to-left-right-monitors/29

**Comment by fifafu** [comment]
Sorry, please ignore the previous message. The migration didn't work correctly, for now the issues will stay here.
