### ISSUE TITLE
BTT Custom Touch Bar Buttons Not Shown Anymore

### ISSUE THREAD

**Issue by pahund** [folivoraAI/BetterTouchTool#2706]
**Describe the bug**

I have been using BTT to configure custom Touch Bar buttons for three applications, IntelliJ IDEA, iTerm and Propellerhead Reason.

Everything worked great, until a few days ago, although I didn't make any changes to my BTT configuration.

Now the custom buttons are not shown when the application is active.

I have tried without success:

* To restart my MacBook
* To update BTT to the latest version
* To change touch bar behavior for each application from “Default (no special handling” to “Show Better Tool Touch Bar, hide system control strip”
* To add new Touch Bar configurations for other applications, doesn't work as well

Since this is the only thing I'm using BTT and the only reason I've purchased it, BTT is now useless to me 😢

**Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):**

Touch Bar

**Screenshots**

**Device information:**
- Type of Mac: MacBook Pro 15" late 2016
- macOS version: 10.12.6 (16G1314)
- BetterTouchTool version: 2.503

**Comment by fifafu** [comment]
Most likely you just accidentally hid the BTT Touch Bar.
In general it's a good idea to define a keyboard shortcut in BTT and assign the predefined action "Toggle BetterTouchTool Touch Bar". This allows you to toggle between the BTT and system Touch Bar at any time.

**Comment by pahund** [comment]
👍 **Thanks for the quick reply, it worked!**

I've created a keyboard shortcut to turn on the BTT touch bar like you suggested and the applications now show my custom buttons
