### ISSUE TITLE
single tap always can't use

### ISSUE THREAD

**Issue by cccisbug** [folivoraAI/BetterTouchTool#2708]
**Describe the bug**
when mac sleep, or  not use magic mouse minite, single tap always  can't use

**Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):**
Magic Mouse

**Screenshots**

**Device information:**
- Type of Mac: macbook pro
- macOS version:  10.12
- BetterTouchTool version: 2.445

**Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):**

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
This issue was moved to https://community.folivora.ai/t/single-tap-always-cant-use/75

**Comment by fifafu** [comment]
Sorry, please ignore the previous message. The migration didn't work correctly, for now the issues will stay here.
