### ISSUE TITLE
volume mute/unmute control widget for TouchBar

### ISSUE THREAD

**Issue by kaloprominat** [folivoraAI/BetterTouchTool#2710]
**Description of feature request:**
it's very handy to utilise current multiple fingers swipe gestures for volume control, but there isn't any option to create control, which would allow to mute/unmute system volume, like one of default touchbar control strip items.

**Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):**
macbooks with touchbar

**Additional information (e.g. related issues, screenshots, workarounds, etc.):**

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by oliviermattelaer** [comment]
Actually, you can with a little of applescript.
See (for example) https://github.com/folivoraAI/BetterTouchTool/issues/2695

I will share directly the preset as soon as the official platform will be online (for the moment, I have to edit a lot of line to remove my shared secret which I guess will not be a problem with the official platform)

**Comment by kaloprominat** [comment]
@oliviermattelaer Thanks for suggestion! It will definitely work, and i'll get it a try) But why not to have some generic system-style toggles as a BTT touchbar built in widgets? That's what i meant by this issue.

**Comment by oliviermattelaer** [comment]
Hi,

Only the developper of the code (fifafu) can creates built in widgets.
So he has to prioritise all those requests and I can not comment on that.

As a community, we can however share our widget/configuration to each other.
The new platform created by fifafu which should be released soon will also help with that.

Cheers,

Olivier

On 16 May 2018, at 23:43, Pavel Kondratiev <notifications@github.com<mailto:notifications@github.com>> wrote:


@oliviermattelaer<https://github.com/oliviermattelaer> Thanks for suggestion! It will definitely work, and i'll get it a try) But why not to have some generic system-style toggles as a BTT touchbar built in widgets? That's what i meant by this issue.
