### ISSUE TITLE
BTT keeps crashing

### ISSUE THREAD

**Issue by wonderpezi** [folivoraAI/BetterTouchTool#2715]
#### Description of bug/feature request/question:

Hi there! 
I just updated to 2.503. Everything works fine, but only for a few minutes. Then BTT just disappears from my menu bar and I have to open it again. And again, and again...

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

MacBook Pro

#### Device information:

Type of Mac: MacBook Pro (Retina, 15-inch, Mid 2014)
macOS version: 10.13.4 (17E199)
BetterTouchTool version:  2.503 (841)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Weird, I haven't had similar reports so far.
Could you check whether there are any crashlogs in your macOS console app under "User Reports"

**Comment by wonderpezi** [comment]
yes there are some! i attached the last one
[Crash BTT.pdf](https://github.com/folivoraAI/BetterTouchTool/files/2012161/Crash.BTT.pdf)

**Comment by fifafu** [comment]
Weird crash. It could be related to a system service that has crashed. Have you already tried to restart your system?

if that doesn't help it would be great if you could go to the about tab in BTT and click the "export debug information" button. This will create a folder called BetterTouchToolDebug on your Desktop.  If possible please send that to andreas@folivora.ai

**Comment by wonderpezi** [comment]
I did restart my mac and updated to the latest iOS Version. I sent you a mail! Thanks
