### ISSUE TITLE
Webserver requests - focus previously focused app after call

### ISSUE THREAD

**Issue by Worie** [folivoraAI/BetterTouchTool#2717]
Hi! I was wondering if its possible to go back to previously focused application upon visiting / making request via `btt://` protocol. 

So for example:
1. I open the browser, visit the `btt://` link
2. The action gets called / widget refreshed  
3. The focus goes back to the browser.

I experience this issue when I create a simple node.js server which triggers command `btt://update_touch_bar_widget/?uuid=UUID&text=TEXT&icon_path=/PATH/&background_color=69,143,199,255`  every, lets say 15 seconds / or happends asynchronously on some event recieved there.

Every time this command gets called, BTT gains focus and my flow is broken, because I can no longer type in my text editor for example. I wonder whether this is possible to focus back the app that has lost the focus upon calling `btt`. 

Thanks in advance!

**Comment by fifafu** [comment]
Unfortunately that's a limitation of custom URL schemes and can not be fixed (I have tried a lot).

However you can use the integrated BetterTouchTool webserver for that: https://docs.bettertouchtool.net/docs/webserver.html

**Comment by Worie** [comment]
I'm not sure wether I should create additonal ticket for further questions, I'll ask them here and create the issue if you see that those should be separated.

I've got issues with updating any widgets icon via requests - text and color changes. But nor the icon_path, provided via local path (absolute, such as /Users/..../image.png) nor remote ones (I don't know if they're supported) seem to work when providing. 

1.
```js
fetch(`http://127.0.0.1:64472/update_touch_bar_widget/?uuid=UUID&text=${new Date().getTime()}&icon_path=/path/img.png&background_color=69,143,199,255"`);
```
does not seem to work, though the path is corrent. What formats are allowed there?


2. When I'm setting the icon for some widgets manually, by drag and dropping, for eg. https://i0.wp.com/www.cracks4win.com/wp-content/uploads/2017/11/BetterTouchTool-For-MacOsx-Free-Download.png 

The image seems to be loaded properly: https://i.imgur.com/5oiCRtL.png
But this one and few others is not visible on the touchbar (again, I'm using emulated one and that might be also an issue), thats all I'm getting: https://i.imgur.com/dz1qLIO.png (white square)

And lastly, if you seek for volonteers for creating some kind of documentation or any other kind of help, let me know. I love BTT and I seriously cannot think about using OSX without it :)

**Comment by fifafu** [comment]
Possibly it's pictures that only contain grey values? (Just for testing, could you try to add a little colored pixel to one of these images? :-))

**Comment by Worie** [comment]
Oh snap, you're right 🎉 I've added a little bit red to the BTT logo and it worked: https://i.imgur.com/dUki9iH.png . So I assume you know whats the issue here ;) 

But, the weird thing is that this image doesn't seem to be grayish, and its a white square, too: https://i.imgur.com/C07VNva.png 

Or perhaps permissions... I don't know, but the test case worked (even it wasn't a single pixel :) )
