### ISSUE TITLE
AppleScript "updateTouchBarWidget" UUID strange syntax in examples.

### ISSUE THREAD

**Issue by m-graf** [folivoraAI/BetterTouchTool#2720]
Under "[BetterTouchTool 2.426 ALPHA (April, 5 , 2018)](https://updates.bettertouchtool.net/alpharls.html)" describes the following example:

```
tell application "BetterTouchTool"
	updateTouchBarWidget uuid "C52C4B67-2C63-4204-9A01-D6A9EBCBBBF0" text "sdasdasdasdasd" backgroundColor "255,80,40,245" iconData "iVBORw0KGgoAAAANSUhEUgAAACgAAAAoCAYAAACM/rhtAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAZVJREFUeNrsWNFthDAMhXaA3mc/MwIjZISOwAbNCN3g1M9+MQIjQCcInSDZgHQC7pBSKbLsUCCkVoUlHxLGuZfn2HFSTtNUcJaHgrmcAP9a6rtOXs1dq8B2DWwa2LJIFQAIQc4iEVubO8QYIyIACOUlN8AL8s7654DYHOFzWHhHEMIRsNSkCvMW5gxIAEmwM09EAZDXowFqwJr4hc8bAFkfBQ6GTe7wTV521E4WLgj7yZIG1rVm4zgCJJdOAbJCBk1Z4Ju9GavBTpEiLDUAqagPS1+7XiMhEaAQ24TLJpQe+eZ9/umQgspFu0fP4szSM7NOad4uP4pTEu+xLYN111KVQjJKDrWmH7Q77G7B5taMKZCZ6KAbxmYqkfYL9n6K8BXed0RsFcagjTBAzbT3Nsz3K9Jd//yfI+wDFeKBQbLa2JnEcQf4yWQHIQFaBgC/uQPsYwA5JIlLmSQicoh/itjC92ItSR3Skhui2JqFfrIlCjHla7YcD7M2qFuvNXLoiF0wlQvrS2RKDPKsU56X6P8d4E2AAQCC42FwiOo6oQAAAABJRU5ErkJggg=="
end tell
```

From the description, replacing the UUID with the UUID of a widget (or button?) should allow an Apple Script update an icon. However, it appears there is a syntax error, as shown here:

<img width="700" alt="script" src="https://user-images.githubusercontent.com/28874386/40215092-17fe502c-5a24-11e8-8b02-c317d1c142f7.png">

Is there something I'm missing here?

**Comment by fifafu** [comment]
Since the alpha there have been a few changes. Have a look here: https://docs.bettertouchtool.net/docs/scripting_btt.html

**Comment by m-graf** [comment]
@fifafu – I found that as well. Have you had success emulating those examples? I've gone through the process of updating a widget (update_touch_bar_widget) and then refreshing, and I've never experienced a successful update. Searching for Apple Scripts for BTT on GitHub has proven futile as well... I'm unable to find a working example.

Can you provide one?

**Comment by fifafu** [comment]
Have you looked at the docs link? There are examples for all functions.
E.g.
```
tell application "BetterTouchTool"
	update_touch_bar_widget "69A9A2D4-40DC-4B61-A3E3-1FA1574F368D" text "newButtonText" background_color "255,100,100,255"
	
end tell
```

I have tested them all. If you want to provide  an image path you may need to escape the slashes e.g. "\/Users\/Tester\/blubb"

**Comment by m-graf** [comment]
@fifafu – sure I have, here is your exact example:

https://gfycat.com/IdleUntriedIchneumonfly

**Comment by fifafu** [comment]
@m-graf, ah I think you may have misunderstood this function.

It only works with the script widgets and it doesn't change their configuration, but instead only changes the current display of the widget.

If you want to update the properties of any trigger in BTT, you would need to use the update_trigger function instead

**Comment by m-graf** [comment]
@fifafu - thanks, got it.
