### ISSUE TITLE
Disable specific features per-application..

### ISSUE THREAD

**Issue by projx** [folivoraAI/BetterTouchTool#2721]
Can you enhance the disable BTT feature, I'd like to be able to disable "Keyboard" when using iterm2, but still continue using other features such as snapping. This could also be extended further, to disable Mouse etc :)

Reason for this, is I map CTRL shortcuts (CTRL-C, CTRL-V etc), but these are using in shell for other purposes (such as CTRL-C kills the running process). Since I can't disable just Keyboard input, I have to disable the who of BTT.

I have tried setting "Use Apple Default or Do Nothing", but this does not work... I still can't use CTRL-C in iterm.

**Comment by fifafu** [comment]
It's a bit complicated but you should be able to disable shortcuts for specific apps by assigning "Use Apple Default Or Do Nothing" to them.

![image](https://user-images.githubusercontent.com/8820811/40276798-7fa58d9e-5c13-11e8-8dd2-7b6e48582949.png)
