### ISSUE TITLE
BTT app-specific touchbar issue

### ISSUE THREAD

**Issue by ajloeffler15** [folivoraAI/BetterTouchTool#2731]
First of all, awesome application and I love what I've been able to do with it so far!

I have created a custom Apple Script Slider Widget for an application (Logic Pro X), and I also use a custom BTT touchbar globally. Before configuring the custom BTT touchbar, I accessed the Logic Pro slider using the Command and Option Modifiers. However, when I try to do that now, the slider comes up underneath the BTT global touchbar and I haven't found a way to solve this. I am aware of the app-specific disabling of BTT touchbar, but none of these options have worked for me.

I would like to figure out a way to disable all of the global touchbar buttons and widgets for Logic, but then still be able to use the slider which is an app-specific action. I'm not sure if there's a setup step I'm missing, or if it isn't possible with how things are currently setup. 

Thanks!

Type of Mac: Macbook Pro 2016 w/ touchbar 
macOS version: 10.12.6
BetterTouchTool version: 2.503

**Comment by fifafu** [comment]
If I understand correctly there is just not enough space to place all the items correctly. Maybe you want to hide the global items when app specific items have been configured?

This can be configured in the general touch bar settings:
![image](https://user-images.githubusercontent.com/8820811/40881023-92400552-66bc-11e8-8bf1-da29c2142626.png)

If you have some items that should always be shown regardless of that setting, you can tick this box when configuring a new button:
![image](https://user-images.githubusercontent.com/8820811/40881027-b3e53fba-66bc-11e8-9f8f-fd3c8b778683.png)

**Comment by oli-laban** [comment]
Not sure I can use that to achieve exactly what I need. All the global buttons need to be shown along with the app-specific buttons. 

A good solution would be to be able to hide the app-specific buttons when the modifier key is held.

**Comment by fifafu** [comment]
Alternatively just put the application specific icons all into the scrollable container. In your screenshot the problem is that you have many items pinned to the right side of the touch bar, leaving only little space for the scrollable area.

For feature requests please post them in the new community forum: https://community.folivora.ai

**Comment by oli-laban** [comment]
Discussion moved to a feature request: https://community.folivora.ai/t/ability-to-hide-buttons-with-a-modifier-key/1411

**Comment by ajloeffler15** [comment]
I believe I'm having a bit of a different issue than oli-laban. I checked the "Hide Global actions if app specific actions are configured in BTT" option, which helped. However, after I use the modifier keys to enable the app-specific widget, when I release the modifier keys the BTT global touchbar shows up instead of it returning to the app-default touchbar. Any thoughts?
