### ISSUE TITLE
Broken in Mojave

### ISSUE THREAD

**Issue by JJJ** [folivoraAI/BetterTouchTool#2734]
Application does not work in macOS Mojave.

* No menu icon appears
* Vanilla Touch Bar buttons are removed, but custom ones do not appear

**Device information:**
- Type of Mac: MacBook Pro (13-inch, 2017, Four Thunderbolt 3 Ports, Touch Bar)
- macOS version: 10.14 Beta (18A293u)
- BetterTouchTool version: Can't tell because I can't get to it

**Comment by fifafu** [comment]
please post new issues only on community.folivora.ai

There will be a beta build of BTT sometime tomorrow.
