### ISSUE TITLE
TouchBar AppleScript widget and AppleScript properties

### ISSUE THREAD

**Issue by meermanr** [folivoraAI/BetterTouchTool#2737]
Hi,

Inspired by https://robservatory.com/silently-mute-the-mic-input-via-applescript/ I'm trying to create a TouchBar widget that:

* Shows if my microphone input volume is 0 or not (i.e. "poor man's muted")
* When pressed, toggles between 0 and its previous value

The following works fine when run from the AppleScript editor:

```
property storedInputLevel : missing value

if input volume of (get volume settings) is 0 then
	-- we're muted, so it's time to unmute
	
	-- get the saved input level, and restore it
	set volume input volume storedInputLevel
	
else
	-- we're unmuted, so it's time to mute
	
	tell application "System Events"
		-- save the current input volume setting --
		set storedInputLevel to input volume of (get volume settings)
	end tell
	
	-- mute the input
	set volume input volume 0
	
end if

return input volume of (get volume settings)
```

but when I create a BetterTouchTool TouchBar AppleScript Widget and put the same script in as text (or a script file, tried both) it is only able to mute: it produces an error when attempting to restore because `storedInputLevel` is a missing value.

I've never attempted AppleScript before, but I suspect that means the property is not being retained between runs. From what I've read, properties are supposed to be like state variables that persist between runs...?

Am I doing something wrong?

What's a sensible way to achieve the behaviour I want: press to toggle between 0 and previous (non-zero) value?

Thanks!
Robert

**Comment by meermanr** [comment]
After some more playing, I've realised I've made a poor assumption: I assumed that when I tap the widget the AppleScript will be run, and then the return value will change the button's text.

It seems the AppleScript associated with the widget is purely for updating the button's text, and only runs on a timer? Can I get it to run only when the widget has been triggered (I need the update to be low-latency from when I toggle the mic)

I've moved my AppleScript to be a triggered action (so the button does do what I expect now), but the `property` still doesn't seem to be retained...

**Comment by fifafu** [comment]
I don't think global properties can work in BTT currently. Maybe I can add a way to save variables in BTT. If possible please post on https://community.folivora.ai, I'm not using GitHub anymore.

There is also a mute/unmute widget there: https://community.folivora.ai/t/mute-unmute-widget/1004

**Comment by meermanr** [comment]
Thank you for the example, it resulted in a far more responsive widget!

**Comment by meermanr** [comment]
FYI, I've added my widget to the community: https://community.folivora.ai/t/microphone-mute-unmute-widget/1579
