### ISSUE TITLE
Popup menus don't work when running a window manager

### ISSUE THREAD

**Issue by gretzky** [folivoraAI/BetterTouchTool#2738]
**Describe the bug**
When running a window manager, in this case chunkwm, the popup menus anywhere inside BTT (for example, when defining a predefined action) aren't able to be selected. When you click the menu and move the mouse to a selection, the menu fades away as if it was clicked out of.

**Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):**
Trackpad

**Device information:**
- Type of Mac: MacBook 14,2
- macOS version: 10.13.5
- BetterTouchTool version: 2.503

**Workarounds**
Quitting the window manager fixes it

**Comment by fifafu** [comment]
Sorry but this is a bug in the window manager then :-(
Not sure whether I'll be able to influence this.

If possible please post on community.folivora.ai, I'm not using GitHub for issue tracking anymore.

**Comment by gretzky** [comment]
Thanks for the response! I'll cross post in the WM repo and if anything comes up there I'll post on the community.
