### ISSUE TITLE
BTT Haptic feedback does not match native macOS haptic feedback

### ISSUE THREAD

**Issue by zefwef** [folivoraAI/BetterTouchTool#2741]
#### Description of bug/feature request/question:
The haptic feedback from the force touch trackpad when using BTT gestures does not match the native macOS haptic feedback.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
MacBook Trackpad

#### Device information:

Type of Mac: 2017 13-inch without touch bar
macOS version: 10.14
BetterTouchTool version: 2.526 (latest alpha)

**Comment by fifafu** [comment]
please use community.folivora.ai for bug reports, this github tracker is no longer being used.

Unfortunately the haptic feedback api in 10.14 beta  don't work anymore, thus I'm now using a different method. This may not be fixable but I'll keep an eye on it.
