### ISSUE TITLE
Middle click action doesn't work

### ISSUE THREAD

**Issue by ulope** [folivoraAI/BetterTouchTool#2746]
**Describe the bug**
No matter to what I assign the `Middle Click` action, it has no effect. For most of my tests it doesn't even show up in the live preview.

Tested assignments:
- Magic Mouse 1 Finger Middle Tap
- Magic Mouse 2 Finger Click
- Magic Mouse 3 Finger Click
- Internal Trackpad 3 Finger Tap
- Internal Trackpad 3 Finger Click
- Keyboard (various shortcuts)

All of the above work perfectly fine when assigning another action (also mouse action such as left or right click). Just middle click is not working.

**Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):**
See above.

**Device information:**
- Type of Mac: MacBook Pro (15-inch, 2017)
- macOS version: Sierra 10.12.6
- BetterTouchTool version: 2.530

**Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):**
There have been two prior issues about middle click that are unfortunately without resolution: #194, #511

**Comment by fifafu** [comment]
please use community.folivora.ai for issue reporting, this github tracker is not used anymore.

However I doubt think there are any known middle click issues in the latest release. How are you testing it? One thing to not : the default middle click action preforms a middle click by sending a middle mouse down followed by a middle mouse up event, no dragging or other stuff is possible with that setup.

**Comment by ulope** [comment]
> please use community.folivora.ai for issue reporting

Ok thanks

> this github tracker is not used anymore.

Could you maybe add that fact to the issue template so people aren't wasting there's and your time?

>  no dragging or other stuff is possible with that setup.

Ok, yeah that's my issue then.
