### ISSUE TITLE
Can't increase execute every x seconds past 100

### ISSUE THREAD

**Issue by lakailb87** [folivoraAI/BetterTouchTool#2748]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at andreas@folivora.ai instead. 

---

#### Description of bug/feature request/question: Why can't I increase Execute every x seconds past 100? I would like to go up to 1800 for a weather widget. This is for the AppleScripts on TouchBar
Please only post one bug or feature request per issue.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Touchbar

#### Device information:

Type of Mac: 2018 13" MBP
macOS version: 10.13.6
BetterTouchTool version: Newest Stable

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by blakeroyer-ttr** [comment]
Hi, try clicking on the number next to the slider, it is actually an input field. You can put any number in this field, your 1800 should work just fine.
![image](https://user-images.githubusercontent.com/36677853/42837683-bbfe9902-89cc-11e8-830c-152ec321a177.png)
