### ISSUE TITLE
trackpad speed affected by mouse speed

### ISSUE THREAD

**Issue by MLGochnauer** [folivoraAI/BetterTouchTool#275]
#### Description of your bug/question/feature request...:

Unexpected behaviour:   
BTT / Advanced / Trackpad / general settings / set trackpad speed   AND
BTT / Advanced / Trackpad / general settings / set mouse speed 
_both_ affect the Trackpad speed, each amplifying the other.

So:  If BTT's set-trackpad-speed is zero, I can adjust the Trackpad speed quite normally with the mouse-speed setting slider.  If I then bring the Trackpad speed slider up from zero, the speed increases very rapidly, as though one was increasing the rate of increase of the other (2nd derivative or something like that).

I expected mouse and trackpad speeds to be isolated from each other. 

**What kind of Mac are you using?**
MacBook Pro retina 15" late 2013

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
MacBook Trackpad

**Which versions of macOS and BetterTouchTool are you running?**
mac OS 10.12.2
BTT 1.980

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

This is unaffected by the OS trackpad speed setting.
No mouse is available to the OS when this occurs.

**Comment by fifafu** [comment]
This issue was moved to https://community.folivora.ai/t/trackpad-speed-affected-by-mouse-speed/85

**Comment by fifafu** [comment]
Sorry, please ignore the previous message. The migration didn't work correctly, for now the issues will stay here.
