### ISSUE TITLE
Can't start BTT after Mojave upgrade

### ISSUE THREAD

**Issue by truthfulie** [folivoraAI/BetterTouchTool#2751]
Tried deleting the app, deleting folder in Application Support and using the latest stable build and alpha build. The app would start and would immediately quit itself. After that, nothing pops up in Activity Monitor when I try to start it again.

What could be the issue?

**Comment by jacobpretorius** [comment]
Same issue here.

**Comment by fifafu** [comment]
This issue tracker is no longer used, head over to community.folivora.ai for future requests

For a solution to the issue see this post: https://folivora.ai/blog/post/13005
