### ISSUE TITLE
Mouse not working with BTT

### ISSUE THREAD

**Issue by TwisterMc** [folivoraAI/BetterTouchTool#2758]
I have a Logitech G400 and it's not working with BTT. I have mouse buttons setup with actions assigned and yet nothing happens. Even if I change the mouse speed in BTT nothing happens.  I have the latest BTT and latest MacOS on a MacBook Pro (15-inch, 2018).

**Comment by fifafu** [comment]
This issue tracker is not used anymore and has been replaced by https://community.folivora.ai
