### ISSUE TITLE
Not all active apps shown in switcher widget

### ISSUE THREAD

**Issue by CappyD** [folivoraAI/BetterTouchTool#279]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:
Thanks for the cool app switcher widget.  Very nice.  It looks like if you have the widget in a touch bar where there is limited room for its width so that you have to scroll the apps, then not all active apps are available.  But if there is room for the widget's full width, then all active apps are shown.

**What kind of Mac are you using?**
2016 MacBook Pro 13"

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

**Which versions of macOS and BetterTouchTool are you running?**
10.12.2 and 1.989

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by CappyD** [comment]
Hmm... after playing with it some more, it looks like if there is a small amount of space available for the widget (maybe only showing 2 app icons), then it becomes very hard to scroll the widget all the way to the right-most app icons.  But I think all the app icons are actually all there.

**Comment by fifafu** [comment]
I'll look into that!

**Comment by rogersmj** [comment]
I ran into this too. In fact with my current setup, if there isn't enough room to show the app switcher widget, it doesn't scroll at all. I have several global buttons stuck to the right side of the touch bar, and a couple app-specific buttons on the left (with the app switcher appearing right after those) when this happens.

**Comment by fifafu** [comment]
This issue was moved to https://community.folivora.ai/t/not-all-active-apps-shown-in-switcher-widget/82

**Comment by fifafu** [comment]
Sorry, please ignore the previous message. The migration didn't work correctly, for now the issues will stay here.
