### ISSUE TITLE
Feature request: Badges in App Switcher Widget (TouchBar)

### ISSUE THREAD

**Issue by andreykats** [folivoraAI/BetterTouchTool#283]
I love your implementation of the app switcher widget. I think Apple should of built that into the TouchBar from day one. 

It would be great if the App Switcher Widget also showed icon badges as shown in the system app switcher. Hope this is possible.

**Comment by fifafu** [comment]
I'll try to add this, however it may increate the CPU usage as there are no notifications I can listen to that would indicate the numbers have changed (thus I'd need to repeatedly run sort of a query to find out where to show badges)

**Comment by nayzak** [comment]
Hi @fifafu. Yesterday I spent whole night trying to get badges values using AppleScript and it seems to be impossible. It's possible, but only for the app, who runs this script. Then I thought, if you are going to implement this feature, than you have idea how to do that. So I spent some more time reading docs of NSWorkspace and nothing there. Accessibility docs didn't help either. Could you, please, tell me where you are going to get this data from? :) I just want to print it on TouchBar using AppleScript widget. Thanks.

**Comment by fifafu** [comment]
@nayzack I think you can get it from the Dock items but  I haven't checked in detail yet

**Comment by nayzak** [comment]
@fifafu, thanks! Finally I wrote a simple command line app just for personal usage. It accesses to Dock through Accessibility API and gets badge value from ```AXApplicationDockItem``` elements. 

If anybody interested in widget, that just prints a number of notifications in Dock, than feel free to get the app and use it with ```Run Apple Script and Show Return Value``` widget. https://github.com/nayzak/DockUtils
