### ISSUE TITLE
Advanced trackpad settings issues

### ISSUE THREAD

**Issue by pallavmac** [folivoraAI/BetterTouchTool#3]
MacBook Pro 15" Touchbar. 
Latest OS. Latest BTT version.

This was happening in the previous versions too, but there's two things in the Advanced trackpad settings which I think may be bugs:
1. Setting the pressure needed in the force trackpad section to be too low causes the app to just crash after having clicked once. There should probably be a limit or something to how low the pressure needed can go or filter out many taps within a second to prevent the app from crashing.

2. I changed "normal click" to "BTT silent click" for the single click option. But now, choosing normal click again does not give the sound back to the one-finger and two-finger clicks. The 3-finger clicks and above are fine.

**Comment by fifafu** [comment]
Thank you, I'll look into that!
I'll however move this issue to the "After official TouchBar Version" milestone.
