### ISSUE TITLE
[Feature Request] Save configuration to iCloud

### ISSUE THREAD

**Issue by ZV00** [folivoraAI/BetterTouchTool#32]
Feature Request: To be able to save configurations on BTT to iCloud and have them kept in sync throughout different computers, and even potentially through the iOS Apps as well (when applicable). 

This would allow for the removal of the import and export settings (or at least hiding them within settings) and a more continuous experience for users with more than one device.

**Comment by moshed** [comment]
i think icloud dync is only available to MAS apps. maybe use other cloud apps?

**Comment by ZV95** [comment]
Nope! Certain applications such as 1Password, Spark Mail, and others have the ability to sync data through iCloud. 

See: https://support.1password.com/sync-options-security/#icloud-and-dropbox-secure-and-customizable-services-you-can-trust

**Comment by fifafu** [comment]
I have already bought a framework that will allow me to add syncing capabilities for various cloud providers. However I'm not yet sure if I'll add iCloud aupport because it's the most complicated.

**Comment by ZV95** [comment]
Awesome to hear!

**Comment by jandubois** [comment]
👍 Looking forward to sync support via Dropbox (or iCloud)!

**Comment by lomafor** [comment]
@fifafu this will be very useful to me!

**Comment by milch** [comment]
Any updates to this? iCloud sync is more convenient than 3rd party because you don't need to install any dependencies when you set up a new machine

**Comment by fifafu** [comment]
The currently integrated dropbox sync also works without installing dropbox.

I may add icloud sync at some point but to be honest it's not very high up on my todo list.

**Comment by milch** [comment]
That makes sense. I understand it's not a high priority for you, as the amount of people wanting that feature seems to be relatively small judging by this thread. 

Instead of implementing any iCloud-sync-APIs (which would obviously be a big time investment for you) could there be a way of choosing the save folder using the existing Dropbox sync functionality? Lots of other apps implement sync that way, and it works pretty well in my experience (e.g. Dash, Alfred)

**Comment by fifafu** [comment]
What would be the advantage of choosing a Dropbox folder compared to the current solution where it just uses the default dropbox sync folder?

**Comment by milch** [comment]
Hmm, maybe I wasn't clear in my explanation. I'll walk you through what I mean with a different app. Suppose I want to sync Alfred using iCloud. Alfred doesn't specifically have support for iCloud, but it allows me to specify a folder to sync with. So, if I want to activate syncing via iCloud on Alfred, I just go into preferences, select "Advanced", click on "Set sync folder" and specify my iCloud Drive folder (which is usually `~/Library/Mobile Documents/com~apple~CloudDocs/`). 

This way no support for a specific API has to be coded in, and people can use whatever sync service they want: e.g. Dropbox, Box, OneDrive, Amazon Drive, iCloud Drive, etc.

**Comment by sillyfrog** [comment]
Having a configurable sync directory (so we can use things such as iCloud Drive and Google Drive) would be awesome!

**Comment by juanjonol** [comment]
As someone who uses Resilio Sync (to avoid the cloud as much as possible), I would love the option to set a sync folder.

**Comment by johan-lejdung** [comment]
Any updates on this?
