### ISSUE TITLE
scroll up/down modifier key didn't work

### ISSUE THREAD

**Issue by justinpma** [folivoraAI/BetterTouchTool#340]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:
I used the trackpad scroll up/down(command hold) with keyboard illumination up/down but it didn't work, however both trackpad gestures shows up fine on the Show Live View

**What kind of Mac are you using?**
15" MacBook Pro late 2016

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
trackpad

**Which versions of macOS and BetterTouchTool are you running?**
macOS 10.12.3, BTT 1.955

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)
if I use other gesture for keyboard illumination, it works just fine.

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by fifafu** [comment]
This issue was moved to https://community.folivora.ai/t/scroll-up-down-modifier-key-didnt-work/53
