### ISSUE TITLE
Feature Request: Display stock ticker in Touch Bar

### ISSUE THREAD

**Issue by mark248am** [folivoraAI/BetterTouchTool#355]
No idea if this is possible or not but I have a bunch of stocks I track in my Mac notification center. 

Could you make a widget for the touch bar that would pull in that info and display it in the touch bar?

**Comment by mark248am** [comment]
Here is a photo of what I mean

![c3a9r0ovmaetbvu](https://cloud.githubusercontent.com/assets/25271366/22425029/39ca62f6-e70a-11e6-88f9-12560584af10.jpg)

**Comment by fifafu** [comment]
Found this little Apple Script that you can use with the Apple Script widget (you shouldn't run it too often because it does web requests). From: http://www.macosxtips.co.uk/geeklets/productivity/reloading-stock-quotes/

```set tickerArray to {"AAPL"}
set finalString to ""
repeat with theTicker in tickerArray
	set impNumbers to (do shell script "curl \"http://www.google.com/finance?client=ob&q=" & theTicker & "\" | sed 's/<[^>]*>//g' | grep -A12 \"google.finance.renderRelativePerformance();\"")
	if character 1 of paragraph 12 of impNumbers = "+" then
		set posNeg to true
	else if character 1 of paragraph 12 of impNumbers = "-" then
		set posNeg to false
	end if
	set finalString to finalString & (theTicker as string)
	if (number of characters of theTicker) < 3 then
		set spacer to " "
	else
		set spacer to " "
	end if
	set finalString to finalString & spacer & (paragraph 9 of impNumbers)
	
	
	if (character 2 of paragraph 13 of impNumbers) as string = "-" then
		set finalString to finalString & "	 " & (paragraph 13 of impNumbers)
	else
		set finalString to finalString & " 	(" & (character 1 of paragraph 12 of impNumbers) & (characters 2 through -1 of paragraph 13 of impNumbers)
	end if
end repeat
return finalString```

**Comment by mark248am** [comment]
damn, that actually worked. You've suddenly made the Touch Bar so much more practical!

**Comment by mark248am** [comment]
For anyone who is interested in this script, I set the background color of the script to green, and the alternate color as red with the minus sign "-" as the activation key. So if the stock is going down its in red, if its going up its green.

<img width="825" alt="screen shot 2017-01-30 at 10 36 07 pm" src="https://cloud.githubusercontent.com/assets/25271366/22438355/aab81d8c-e73c-11e6-924e-5a2a351df2cb.png">

**Comment by mark248am** [comment]
quick question, if i want to show just the percentage without the price of the stock, what do i need to edit in the code?

**Comment by fifafu** [comment]
Something like this:
```AppleScript
set tickerArray to {"AAPL"}
set finalString to ""
repeat with theTicker in tickerArray
	set impNumbers to (do shell script "curl \"http://www.google.com/finance?client=ob&q=" & theTicker & "\" | sed 's/<[^>]*>//g' | grep -A12 \"google.finance.renderRelativePerformance();\"")
	if character 1 of paragraph 12 of impNumbers = "+" then
		set posNeg to true
	else if character 1 of paragraph 12 of impNumbers = "-" then
		set posNeg to false
	end if
	
	
	if (character 2 of paragraph 13 of impNumbers) as string = "-" then
		set finalString to (paragraph 13 of impNumbers)
	else
		set finalString to "(" & (character 1 of paragraph 12 of impNumbers) & (characters 2 through -1 of paragraph 13 of impNumbers)
	end if
end repeat
return finalString
```

**Comment by mark248am** [comment]
Thanks, I actually meant with the stock name so AAPL (-0.64%) for example. Ended up using your code plus the extra line to add the sock name

`set tickerArray to {"AAPL"}
set finalString to ""
repeat with theTicker in tickerArray
	set impNumbers to (do shell script "curl \"http://www.google.com/finance?client=ob&q=" & theTicker & "\" | sed 's/<[^>]*>//g' | grep -A12 \"google.finance.renderRelativePerformance();\"")
	if character 1 of paragraph 12 of impNumbers = "+" then
		set posNeg to true
	else if character 1 of paragraph 12 of impNumbers = "-" then
		set posNeg to false
	end if
	set finalString to finalString & (theTicker as string)
	
	
	if (character 2 of paragraph 13 of impNumbers) as string = "-" then
		set finalString to finalString & " " & (paragraph 13 of impNumbers)
	else
		set finalString to finalString & " 	(" & (character 1 of paragraph 12 of impNumbers) & (characters 2 through -1 of paragraph 13 of impNumbers)
	end if
end repeat
return finalString`

**Comment by mark248am** [comment]
This is how it currently looks. Takes up a lot of room so won't really be to fit many. might put them in a group.

![img_9941](https://cloud.githubusercontent.com/assets/25271366/22440228/a7331df4-e743-11e6-9212-c84425b79bf1.JPG)

**Comment by fifafu** [comment]
Nice :-) I'll add an option for smaller font-sizes soon, then maybe you can fit more

**Comment by mark248am** [comment]
Could you add an option to change the color of the text? right now its just white and we can change the color of boxes behind it but would be cool if we could change the color of the text as well.

**Comment by fifafu** [comment]
@mark248am yes, if possible add an additional issue because I'm closing here for now :-)

**Comment by mark248am** [comment]
Hey, did you change anything in the latest update of the BetterTouchTool that would effect this script? 

```AppleScript
set tickerArray to {"AAPL"}
set finalString to ""
repeat with theTicker in tickerArray
	set impNumbers to (do shell script "curl \"http://www.google.com/finance?client=ob&q=" & theTicker & "\" | sed 's/<[^>]*>//g' | grep -A12 \"google.finance.renderRelativePerformance();\"")
	if character 1 of paragraph 12 of impNumbers = "+" then
		set posNeg to true
	else if character 1 of paragraph 12 of impNumbers = "-" then
		set posNeg to false
	end if
	set finalString to finalString & (theTicker as string)
	if (character 2 of paragraph 13 of impNumbers) as string = "-" then
		set finalString to finalString & " " & (paragraph 13 of impNumbers)
	else
		set finalString to finalString & " 	(" & (character 1 of paragraph 12 of impNumbers) & (characters 2 through -1 of paragraph 13 of impNumbers)
	end if
end repeat
return finalString
```

For some reason I am getting around 4 empty spaces between APPL and (+0.XXX). In the previous version of the software I was getting just 1 space.


![img_0225](https://cloud.githubusercontent.com/assets/25271366/22663590/340c3f9c-ecbe-11e6-9799-9a73260e1e26.JPG)

**Comment by fifafu** [comment]
hehe no, but your AAPL stock has changed from red to green ;-)

Just remove the spacing from the last else case:
```
set finalString to finalString & " 	(" & (character 1 of paragraph 12 of impNumbers) & (characters 2 through -1 of paragraph 13 of impNumbers)
```

**Comment by mark248am** [comment]
hahaha yeah you're right, when the stock goes up there were extra spaces i missed that

**Comment by mark248am** [comment]
sorry to bother u with this again, but if i want to remove the brackets what part of the code do i need to change?

**Comment by fifafu** [comment]
This is more complicated because it's returned like this by the API.

This may work:

```
set tickerArray to {"BMW"}
set finalString to ""
repeat with theTicker in tickerArray
	set impNumbers to (do shell script "curl \"http://www.google.com/finance?client=ob&q=" & theTicker & "\" | sed 's/<[^>]*>//g' | grep -A12 \"google.finance.renderRelativePerformance();\"")
	if character 1 of paragraph 12 of impNumbers = "+" then
		set posNeg to true
	else if character 1 of paragraph 12 of impNumbers = "-" then
		set posNeg to false
	end if
	set finalString to finalString & (theTicker as string)
	if (character 2 of paragraph 13 of impNumbers) as string = "-" then
		set finalString to finalString & " " & (characters 2 through 6 of paragraph 13 of impNumbers)
	else
		set finalString to finalString & " " & (character 1 of paragraph 12 of impNumbers) & (characters 2 through 6 of paragraph 13 of impNumbers)
	end if
end repeat
return finalString
```

**Comment by mark248am** [comment]
yes that worked! no wonder i couldn't figure it out, i thought the code was adding the brackets so i tried removing them but didn't work. thanks, without the brackets the widgets eat up less space.

**Comment by HK8R0b1n** [comment]
Hello, unfortunately for exchange rate it's different, i have seen in code source, but i m not that good at cooding, anyone can help with "EURHKD" for example. Thanks

**Comment by nlpthk** [comment]
Hi @fifafu ,

Sorry to bother you, but how would I be able to use this script to get the current price off the "[Bitcoin](https://www.google.com/finance?q=CURRENCY%3ABTC&ei=bZ03WbHeBYL82AbaobG4Dg) ticker? Thanks so much for the help!

**Comment by fifafu** [comment]
Updated Script as Google has changed the API URL:

```
set tickerArray to {"BMW"}
set finalString to ""
repeat with theTicker in tickerArray
	set impNumbers to (do shell script "curl \"https://finance.google.com/finance?https://finance.google.com/finance?output=json&q=" & theTicker & "\" | sed 's/<[^>]*>//g' | grep -A12 \"google.finance.renderRelativePerformance();\"")
	if character 1 of paragraph 12 of impNumbers = "+" then
		set posNeg to true
	else if character 1 of paragraph 12 of impNumbers = "-" then
		set posNeg to false
	end if
	set finalString to finalString & (theTicker as string)
	if (character 2 of paragraph 13 of impNumbers) as string = "-" then
		set finalString to finalString & " " & (characters 2 through 6 of paragraph 13 of impNumbers)
	else
		set finalString to finalString & " " & (character 1 of paragraph 12 of impNumbers) & (characters 2 through 6 of paragraph 13 of impNumbers)
	end if
end repeat
return finalString
```

**Comment by BitterLox** [comment]
@nlpthk Here's what you're searching for:
```
tell application "JSON Helper"
	set result to fetch JSON from "https://api.coinmarketcap.com/v1/ticker/bitcoin/"
	set price to price_usd of item 1 of result
	
end tell

set result_string to "" & {price} & " $"
return result_string
```

**Comment by fifafu** [comment]
Quick Update:
With BetterTouchTool 2.322 alpha you can now also use the shell script widget, which should be much more performant than the Apple Script widget.

![image](https://user-images.githubusercontent.com/8820811/34916882-26418c6c-f93f-11e7-87e5-32ba37386ff4.png)

E.g. to get the Apple Stock price:
```
curl -s https://finance.google.com/finance\?q\=AAPL\&output\=json \
| tr -d '\n// ' \
| python -c "import sys, json; result=json.load(sys.stdin); \
print 'AAPL ' + result[0]['l'] + ' (' + result[0]['c'] + ')'" 
```

**Comment by mah185** [comment]
Hi fifafu, First I am by no means a programer. I'm trying to use this script for this stock (ACBFF). I tried replacing AAPL but it not working

**Comment by bacu12** [comment]
Add a space before ACBFF

So ' ACBFF '

**Comment by nlpthk** [comment]
I've wrote a crypto shell script which uses the Bittrex API. It's posted it on my page if anyone needs it:)

**Comment by mark248am** [comment]
Hi, this stopped working, did something change in BetterTouchTool?

**Comment by fifafu** [comment]
No, but maybe the api has changed?

**Comment by mark248am** [comment]
I thought so but then I tried this one which uses Yahoo and it didn't work also 
https://medium.com/@eunanhardy/how-to-create-a-stock-ticker-on-the-new-macbook-pro-touchbar-434012875b03

**Comment by fifafu** [comment]
yahoo discontinued their api a few months ago already as far as I know...
Not sure what currently would be a good free API to use. I'll reopen here in case somebody knows one.

**Comment by mark248am** [comment]
Would this work? They offer free API's but we have to individually register for a free key which should be fine https://www.alphavantage.co/

**Comment by fifafu** [comment]
That api would be able to return the current price, but I think it doesn't easily give you the change.

Something like this would work to get the price:

```
curl -s https://www.alphavantage.co/query\?function\=BATCH_STOCK_QUOTES\&symbols\=AAPL\&apikey\=YOURAPIKEY | python -c "import sys, json; result=json.load(sys.stdin); \
print 'AAPL ' + result['Stock Quotes'][0]['2. price']"```

![image](https://user-images.githubusercontent.com/8820811/38274233-77177a56-378e-11e8-9fb2-434a4af37f93.png)

**Comment by robgraeber** [comment]
Here's a python script for getting the percent change for a stock ticker:
Set the shell script launch path to /usr/bin/python
And do `sudo pip install lxml requests`
```
from lxml import html
import requests
page = requests.get('https://www.msn.com/en-us/money/stockdetails?symbol=US:UNH')
tree = html.fromstring(page.content)
percent_change = tree.xpath('//div[@data-role="percentchange"]/text()')
print 'UNH ' + percent_change[0]
```

**Comment by AndrewC7** [comment]
I also found this api: [iextrading.com](iextrading.com)
AAPL would look like this: [https://api.iextrading.com/1.0/stock/aapl/quote](https://api.iextrading.com/1.0/stock/aapl/quote)

returns the change and a bunch of other stuff

**Comment by thanosbetyping** [comment]
> That api would be able to return the current price, but I think it doesn't easily give you the change.
> 
> Something like this would work to get the price:
> 
> ```
> curl -s https://www.alphavantage.co/query\?function\=BATCH_STOCK_QUOTES\&symbols\=AAPL\&apikey\=YOURAPIKEY | python -c "import sys, json; result=json.load(sys.stdin); \
> print 'AAPL ' + result['Stock Quotes'][0]['2. price']"
> ```
> ![image](https://user-images.githubusercontent.com/8820811/38274275-9b41901a-378e-11e8-9c40-1ab32ab59461.png)

Hi - how can I lost the extra "00" at the end and possibly add a "$" ?

Currently the output is "AAPL 201.5900" - I'm looking for "AAPL $201.59"

Thanks.
