### ISSUE TITLE
Touchbar Volume Slider will not reflect external changes to volume

### ISSUE THREAD

**Issue by fantaaaaaa** [folivoraAI/BetterTouchTool#360]
When changing audio destinations (that might invoke a change in volume) or when using scripts or external programs to change the volume the volume slider will not update itself. it will stay on the same position if you change the volume externaly.

Here is a video of the bug. Is this reproducable?
https://www.dropbox.com/s/32p3s86g8tlrsrq/IMG_3346.MOV?dl=0

What kind of Mac are you using?
Macbook Pro late 2016 with Touchbar

Which input device is affected by this?
Macbook Trackpad

Which versions of macOS and BetterTouchTool are you running?
macOS Sierra 10.12.3, BetterTouchTool all versions up until 2.0

**Comment by fifafu** [comment]
Probably the volume changed notifications are not posted in those cases.
I'll just add an additional timer that regularly updates the volume with the next update.

**Comment by fantaaaaaa** [comment]
wont this affect performance?

**Comment by fifafu** [comment]
not really. It's quite cheap and doing it every 5 seconds or so should be good enough :-)

**Comment by fantaaaaaa** [comment]
hi andreas. can you give an update on this issue please? thanks!

**Comment by fifafu** [comment]
Nothing new yet. Will be fixed with one the next versions.

**Comment by fantaaaaaa** [comment]
is there a milestone on this?

**Comment by NSDodgers** [comment]
I am also interested in this. I have made a Mute button in BTT and I would like the slider to update.

**Comment by B4ttleCat** [comment]
I just discovered the pre-made widgets and they're great, but having the volume slider update with the system status would be amazing.
