### ISSUE TITLE
Feature Request: Configure different behaviors for touchbar buttons based on length of press

### ISSUE THREAD

**Issue by awindsor** [folivoraAI/BetterTouchTool#374]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:

Feature request: I would like to be able to configure different behavior for touchbar buttons based on the length of the press. E.g. Short press on gmail icon - take me to gmail in browser (or switch to open tab) and long press on gmail icon - compose message in gmail. 

**What kind of Mac are you using?**

MacBook Pro TouchBar

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

**Which versions of macOS and BetterTouchTool are you running?**

10.12.3 and 2.02 (598)

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by fantaaaaaa** [comment]
wow yes, that would be great! allowing two different actions for a short press and a long press would be awesome!!!

**Comment by fantaaaaaa** [comment]
that is maybe the most amazing idea next to being able to customize the touchbar itself! amazing idea! i would love that too, pleaseeeee :)

**Comment by awindsor** [comment]
Best idea ever ... totally amazing idea ... everybody loves it ;)

Alistair Windsor
Associate Professor, Department of Mathematical Sciences
355 Dunn Hall                             Ph:     901-318-3912
University of Memphis                Fax:    901-678-2480
Memphis, TN 38152-3240

**Comment by MrJarnould** [comment]
Can't wait!

**Comment by MrJarnould** [comment]
Really looking forward to this update!

**Comment by fantaaaaaa** [comment]
hey @fifafu, is there any eta on the "long press on touchbar" feature?
