### ISSUE TITLE
Please can we get a "Move Window to Prev Monitor" action

### ISSUE THREAD

**Issue by mctully** [folivoraAI/BetterTouchTool#392]
There is a "Move Window to Next Monitor" action, but there doesn't appear to be a "Move Window to Prev Monitor" one. It would be useful to be able to move the window in "both" directions through the monitors.

Thank you.

**What kind of Mac are you using?**

Macbook Pro Retina, Mid 2015

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

Keyboard

**Which versions of macOS and BetterTouchTool are you running?**

OS X 10.12.3, BTT 2.02 (598)

**Comment by Relequestual** [comment]
Sugggest closing in favour of https://github.com/fifafu/BetterTouchTool/issues/514 which is scheduled.

**Comment by fifafu** [comment]
In v2.460 (alpha) there is a new predefined action which can do all sorts of custom window moving and resizing:
![image](https://user-images.githubusercontent.com/8820811/39365653-08ef6b04-4a32-11e8-98be-4befc40b4506.png)
