### ISSUE TITLE
BTT stops responding to 3-finger click gesture on Magic Mouse.

### ISSUE THREAD

**Issue by agordeev** [folivoraAI/BetterTouchTool#397]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:

MagicMouse: I assigned 3-finger click to mouse middle click action, but it stops working pretty often. I have to restart the app to get it working again.

**What kind of Mac are you using?**

MBPro mid 2014.

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

Magic Mouse (previous gen).

**Which versions of macOS and BetterTouchTool are you running?**

macOS Sierra 10.12.2. BTT 1.961 (549)
**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by todivefor** [comment]
I have this same issue.  I use "1 finger middle click" to cmd+click / middle click.  Both work for awhile and then stop.  I have to disable/enable BTT to get support back.  Mac OS Sierra (10.12.3), BTT 2.02 (598), MacBook Pro mid 2012.

**Comment by todivefor** [comment]
This still happens, but a lot less frequently with BTT 2.071.
