### ISSUE TITLE
Add open menu bar in context menu of currently hovered app in dock

### ISSUE THREAD

**Issue by moshed** [folivoraAI/BetterTouchTool#403]
this would be very useful if i want to, say, open a new preview window on the current desktop without switching to the desktop with preview open going to the menubar and clicking new window and dragging it back to the desired desktop.

**Comment by cleverjackal** [comment]
There's a right click option. Can't you use that? Or what exactly do you mean by open the "menu bar"?

By the way, nice profile picture ;)

**Comment by moshed** [comment]
i would like to be able to access the menu bar of the app below the the mouse in the dock. similar to the already built in function of BTT " show menu bar in context menu" but for icons in the dock.
