### ISSUE TITLE
Three-finger tap not triggering with Magic Touchpad

### ISSUE THREAD

**Issue by redbits** [folivoraAI/BetterTouchTool#419]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...: Occasionally, the Magic Trackpad will stop recognizing a three-finger tap. Not sure what triggers it. Restarting the Mac solves the problem, but it would be nice if it didn't happen to begin with, as it keeps recurring.

**What kind of Mac are you using?** MacBook Air mid-2013

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?** Magic Trackpad

**Which versions of macOS and BetterTouchTool are you running?** macOS 10.12.3, BTT 2.02 (598)

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Can be fixed by restarting the Mac. Once, I was able to fix it by restarting BTT, but every other time I've had to restart the Mac.

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by x8808099** [comment]
This is a universal issue that persists for many versions of BTT and macOS, for my old 13 Macbook pro and new 17 Macbook pro, for Magic Trackpad 1 and 2.

In my case, all tap gestures can be affect (3\4\5 fingers tap), also they are not recognized in "Live View". I have to set up a gesture to restart BTT once it happens.

**Comment by fifafu** [comment]
Sorry for not replying earlier to this issue. I'm currently cleaning up here, which is why I'm closing some older issues. In case you still have questions or problems, please create a new issue - I'm now much more responsive than a few months ago.
