### ISSUE TITLE
BTT touch bar app specific buttons for 'wine' window?

### ISSUE THREAD

**Issue by rakros1161** [folivoraAI/BetterTouchTool#429]
Latest Macbook Pro 15 inch 2016 maxed out.     Running the latest version of BTT.

I want to create app specific buttons for eve online.    The application for the game is just the launcher.
It then pulls up a 'wine' window that runs the actual game.    I can create buttons for the launcher.. but when i pull up the game my buttons disappear.     I have located the 'wine' file but better touch tool won't see it as an application.     Any ideas on a work around?

Thanks!

**Comment by fifafu** [comment]
This will soon be supported, I'm already working on a way to add apps by process name or window title.

**Comment by rakros1161** [comment]
you're the man! Thank you so much. I'll be eagerly waiting. 😄

**Comment by rezashamdani** [comment]
just about asking the same question. thanks

**Comment by therealdjryan** [comment]
I'd like to see this feature too

**Comment by fifafu** [comment]
I believe this should already be possible when selecting the application from the running apps 
![image](https://user-images.githubusercontent.com/8820811/38383747-9d7a1cb4-390d-11e8-8975-83b9bcc8ffb9.png)

**Comment by therealdjryan** [comment]
No, I tried that. It doesn't work.
