### ISSUE TITLE
Feature Request: Apple Script Arrays as Buttons

### ISSUE THREAD

**Issue by mjsamberg** [folivoraAI/BetterTouchTool#434]
I have no idea if this is possible (and it may already be), but I would love to be able to display each element from an AppleScript array as a button, and pass a value to another AppleScript when pressed. 

Use case: I'm trying to recreate Safari's list of open tabs in Chrome. But I could also see using this to show open windows in an app and switch between them.

**Comment by dotansimha** [comment]
👍 👍 👍 👍 👍

**Comment by eitanfr** [comment]
buttons for all chrome active tabs can be an awesome usage
