### ISSUE TITLE
Feature Request: Vertical third window placement

### ISSUE THREAD

**Issue by edmckenna** [folivoraAI/BetterTouchTool#439]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:

I use a monitor rotated to a vertical orientation, and it would be awesome to have an option to snap a window to the top third, middle third, or bottom third. 

**What kind of Mac are you using?**

2012 Macbook Pro Retina

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

Trackpad/Magic Mouse
**Which versions of macOS and BetterTouchTool are you running?**

macOS:10.11.6 BTT:1.963

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by jjaaccoobb** [comment]
Seconded, please make this happen
