### ISSUE TITLE
Allow trackpad scrolling to carry out action without modifier if a mouse specific location is set

### ISSUE THREAD

**Issue by moshed** [folivoraAI/BetterTouchTool#44]
my desired functionality is to place the mouse on the menu bar and scroll up or down to control volume without needing to have a modifier. i understand the need for a modifier in general otherwise pandemonium would ensue with accidental volume changes, but in the case where a mouse specific location (such as menubar here)  <img width="1127" alt="image" src="https://cloud.githubusercontent.com/assets/8683379/20979054/32213612-bc79-11e6-9ab4-4ef0b2fb6c46.png"> was set, it would be intentional 99% of the time

**Comment by fifafu** [comment]
I'd love to do this, but the problem is, that this would probably mess up performance. Scrolling is very sensitive to interception and every calculations I make (to check whether the mouse is over the menubar) may be bad.

I'll look into it!

**Comment by fifafu** [comment]
This issue was moved to https://community.folivora.ai/t/allow-trackpad-scrolling-to-carry-out-action-without-modifier-if-a-mouse-specific-location-is-set/95

**Comment by fifafu** [comment]
Sorry, please ignore the previous message. The migration didn't work correctly, for now the issues will stay here.
