### ISSUE TITLE
cad middle click drag

### ISSUE THREAD

**Issue by justinpma** [folivoraAI/BetterTouchTool#450]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:
I can't seems to use the 3f click for middle mouse click drag, with the 3f click and release 2f,1f hold and drag method.

**What kind of Mac are you using?**
15"MacBook Pro 2016
**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
trackpad  & Magic Mouse 

**Which versions of macOS and BetterTouchTool are you running?**
12.10.4b2, 2.03

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by b-** [comment]
Either I am not understanding how this gesture works, or it still…doesn’t. I’m trying to use my trackpad to middle-drag in EAGLE and it’s simply not doing anything :(

**Comment by fifafu** [comment]
With the latest alpha (2.470) you could try to set it up like this:

1.) don't use the middle click action, instead use the "More Buttons & Modifiers & Custom Click" action and configure it like this (only mouse down).
![image](https://user-images.githubusercontent.com/8820811/39584896-d0e0351a-4ef3-11e8-8290-ee859b29a44e.png)

2.) Open the gesture preferences and define a named trigger that shall be executed when no fingers are touching the trackpad anymore
![image](https://user-images.githubusercontent.com/8820811/39584944-e9ed952a-4ef3-11e8-87ed-e71bf2386d07.png)

3.) Go to the "Other" tab and create a Named Trigger, then assign the middle mouse up.
![image](https://user-images.githubusercontent.com/8820811/39584971-f9b9307c-4ef3-11e8-959e-e9cbd8fd9fca.png)
