### ISSUE TITLE
Feature Request: condition

### ISSUE THREAD

**Issue by ghost** [folivoraAI/BetterTouchTool#462]
Hello, this app is great but it really lacks something important, conditions.

For example, i use shortcut but i want to perform the action only in certain situations.

Ideally, i think it's perfect if BetterTouchTool can intercept exit code and play differently attached action depending on the return code (tree) of apple script or bash script.

That way the user can customize his conditions and play different scenario without it being too painful for you.

Thanks for your tool.

**Comment by atian25** [comment]
+1 for this.

**Comment by alaq** [comment]
If I understand correctly, this would mean for instance that if a window is maximized to the left, using the same keyboard shortcut we could move it to the next monitor. Like in Windows. Works great :)
So, +1 for this!

**Comment by etheld** [comment]
+1
