### ISSUE TITLE
Add new functionality:  repeat a key sequence if I leave the key pressed.

### ISSUE THREAD

**Issue by isalsberg-mx** [folivoraAI/BetterTouchTool#470]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...: 
 
        _Feature request to add this functionality:  repeat a key sequence if I leave the key pressed.

        _I created a key sequence to execute forward delete when I press the alt right key (see the screenshot). However I would like to repeat deleting if I leave the key pressed.__

![unnamed](https://cloud.githubusercontent.com/assets/25750656/22895936/dcb726c8-f1e3-11e6-8cb4-c6bf9e7292ec.png)

**What kind of Mac are you using?**

         _iMac (21.5-inch, Mid 2010)_

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

      _iMac bluetooth keyboard (Apple wireless keyboard)_

**Which versions of macOS and BetterTouchTool are you running?**
   
    _OS X Sierra 10.12.3 (16D32) 
     BetterTouchTool 2.04 (603)_

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by pallavmac** [comment]
Yes! Especially useful for the keyboard shortcut which I assigned to increasing the volume.

**Comment by nguyenhimself** [comment]
I'd like to second this. Strangely, I believe that this used to work bak in El Capitan 10.11 but anymore after I got a new MacBook with Sierra 10.12 installed.

One example:

- **Use case**: 

Keep SHIFT pressed, then press LEFT or RIGHT ARROW to move to another space.

- **Expected**:

With the SHIFT key pressed, press RIGHT ARROW two times to move 2 space right.

- **Actual**:

With the SHIFT key pressed, Pressing RIGHT ARROW two times will only move 1 space right. To move another space right, I need to put up my finger, press SHIFT once more and then press RIGHT ARROW once more.

**Comment by Ericlee0210** [comment]
If there exists this feature, that would be very useful!!

**Comment by SaMeHub** [comment]
Yes, please ... I use the exact same key sequence, but the repeat feature only works for shortcuts!?
I use BTT2.530
