### ISSUE TITLE
[Feature Request] Additional actions on touchbar buttons (sliding and holding)

### ISSUE THREAD

**Issue by bestbrian** [folivoraAI/BetterTouchTool#488]
Hi, I found one of your scripts to make the TB fetch the song and artist from Spotify. I love it but there is one thing I wish I could do - add more functionality to this "widget". 

I increased the number of characters it could hold to 40 so I could see the full name of the song and artist but now it's taking up a lot of room on the touchbar. This is fine to me because I think it looks good, but I want to not have additional buttons needed to carry out actions. Here are some examples of what I want:

1. Slide right on the button = Next song
2. Slide left on the button = Previous song
3. Hold on the button = Open Spotify

Currently I just use the button as play/pause.

I think this functionality would be applicable in a variety of situations so I would love to have it as a feature. Thanks again for your work! 👍 

Macbook Pro 13" with Touch Bar

**Comment by fifafu** [comment]
v2.430 alpha now has options to set repeatRate, repeatDelay and also the option to set a different action for "long presses" / hold.
Sliding is not yet integrated but I'll probably add it soon.
