### ISSUE TITLE
Option for Tip Tap Angle

### ISSUE THREAD

**Issue by jhein05** [folivoraAI/BetterTouchTool#489]
#### Description of your bug/question/feature request...:

Hi, it would be really great if the 3 finger tip taps would also have an option to allow a certain angle between the finger. I was using tip taps mostly on an external Magic Trackpad and they worked without any problems. But now I have a new MacBook Pro and my fingers are no longer in a straight line when doing the tip taps. BTT expects them to be like this: -- but because of the location of the Touchpad in the middle of the keyboard, they are more aligned like that: / 

And that is no longer recognized as a tip tap. I hope I do make sense here :)

Thank you!

**What kind of Mac are you using?**

MacBook Pro 2016

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

Built in Touchpad

**Comment by nhooyr** [comment]
Weird thing is, sometimes it works but sometimes it does not.
