### ISSUE TITLE
Support per website touch bar settings

### ISSUE THREAD

**Issue by barnaclebarnes** [folivoraAI/BetterTouchTool#49]
#### Description of your bug/question/feature request...:

It would be great if the TouchBar feature could support per website/web page/regex url controls. For example when you are in Gmail you could customise certain tools or within Xero you could have buttons for reconciling transactions. 

**What kind of Mac are you using?**

MacBook Pro - Touch Bar

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

Touch Bar

**Comment by fifafu** [comment]
This will be possible soon as I'm currently adding an option to show buttons based on a windows title, and websites pretty much always change the title of the window :-)

**Comment by pallavmac** [comment]
That would be amazing!

**Comment by fifafu** [comment]
This issue was moved to https://community.folivora.ai/t/support-per-website-touch-bar-settings/96

**Comment by fifafu** [comment]
Sorry, please ignore the previous message. The migration didn't work correctly, for now the issues will stay here.

**Comment by imdadahad** [comment]
BTT is amazing, this would make it even more awesome!

Is there any update with this?
