### ISSUE TITLE
Bug: Disable single finger scrolling and horizontal single finger scrolling not working

### ISSUE THREAD

**Issue by effingchrist** [folivoraAI/BetterTouchTool#494]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:

Cannot disable single finger scrolling or horizontal single finger scrolling for MS Excel 2011 v14.7.1

**What kind of Mac are you using?**   27-inch iMac, mid-2010, Intel core i7

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**  Magic Mouse

**Which versions of macOS and BetterTouchTool are you running?**  OS X 10.11.6, BTT 2.07

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Disable single finger scrolling/horizontal single finger scrolling works poorly in other apps (tested Chrome and Word 2011). If you lift your finger from the mouse surface while scrolling, the scrolling takes place even when turned off in BTT. If you keep your finger on the surface, it seems to be disabled.

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by d2405** [comment]
I too have this issue. In particular in iTunes. I have set app specific "disable horizontal single finger scrolling" for iTunes and it doesn't work. I am using macos 10.11.6 and BTT 2.20. I use apple magic mouse. 
I notice that this issue was opened in February and there is no one assigned yet. What do you advise and is there anything I can do to facilitate getting this fixed?
Thanks.

**Comment by msdoeswork** [comment]
same problem here, with adobe indesign and adobe acrobat dc – activating "disable single finger scrolling" or "disable horizontal single finger scrolling" does have no effect.
