### ISSUE TITLE
[Feature Request] TouchBar Window Controls

### ISSUE THREAD

**Issue by Jason-Morcos** [folivoraAI/BetterTouchTool#499]
It would be awesome if a widget existed that included buttons like close, minimize, maximize, full screen... like the window controls on a corner of a window. I have made my own manually, however the options within BTT are limited to closing the window under the cursor and such when it would make much more sense if these actions were bound to the currently active application like the rest of the TouchBar buttons are. For instance, there should be a way to add a close window button to the TouchBar that closes the active application and not whichever application happens to be under the cursor.

**Comment by fifafu** [comment]
Hey,

You can just bind the keyboard shortcuts to the Touchbar buttons (e.g. Cmd+w to close the current window or cmd+m to minimize)

**Comment by Moballo** [comment]
I tried that, but not all applications support these keyboard shortcuts! I haha few key ones that don't

**Comment by lazee** [comment]
Works nicely with BetterSnapTool ;)
