### ISSUE TITLE
Bug: Window moves slightly when you click on its toolbar

### ISSUE THREAD

**Issue by tommit** [folivoraAI/BetterTouchTool#504]
When BetterTouchTool is running and you click on the toolbar of a non-active window, the window moves slightly up-left (a toolbar is the thing you normally click and drag to move the window around, and a non-active window is one that's not the latest one you've clicked on). The bug manifests itself even if you select "Disable BTT For All Apps" from BTT menu bar icon, so you need to fully quit BTT to see the correct behavior.

But if the non-active window you click on is positioned such that its right edge is aligned with the right edge of the screen, the window doesn't move horizontally and jumps only slightly upwards. And if the non-active window you click on is positioned such that its bottom edge is aligned with the bottom edge of the screen, the window doesn't move vertically and jumps only slightly to the left. These two combined, if the bottom right corner of the non-active window you click on is positioned at the bottom right corner of the screen, clicking on its toolbar doesn't cause it to move at all.

I'm using iMac (21.5-inch, Late 2013) and Apple Magic Trackpad 2, but I tested and verified that the bug happens also with Apple Magic Trackpad (version 1), Apple Magic Mouse and Logitech MX 518 Gaming Mouse.

I'm running macOS Sierra 10.12.3 and BetterTouchTool 2.071 (608).

**Comment by tommit** [comment]
I'm glad to report that I'm unable to reproduce this bug anymore. I haven't really been paying attention to this issue, so I can't tell you what made it go away - macOS update, BTT update, or a change in my BTT settings.

Anyway, I'm running macOS High Sierra 10.13.2 (17C205) and BetterTouchTool 2.318 (702) now.

**Comment by supa42** [comment]
I am still having this issue. 10.13.3 and 2.340

**Comment by tommit** [comment]
The bug came back for me. I can't tell you what made it come back (or rather what made it go away for a while). I'm using macOS High Sierra 10.13.3 (17D102) and BTT 2.340 (719).

**Comment by tommit** [comment]
I exported my BTT presets, did a clean reinstall of macOS High Sierra 10.13.3 (unrelated to this), installed the old BTT 2.318 (702) version, imported my BTT presets, and as a result this bug is gone again. From this, I think we can safely say that the bug lies somewhere in the diff between BTT versions 2.318 and 2.340.

**Comment by supa42** [comment]
Thank you, tommit! I just repeated the same steps as you (thankfully minus the reinstalling macOS!) and the bug has gone for me too :)

**Comment by tommit** [comment]
This doesn't seem to be an issue anymore. I've been using the latest versions for a while now and I haven't seen this issue happening (I just forgot to report back about it). I'm currently using BTT version 2.645 on macOS Mojave (but had no issues on macOS High Sierra either). Fine by me to close the issue.
