### ISSUE TITLE
Magic Mouse Gestures not working after waking up from sleep mode

### ISSUE THREAD

**Issue by julsdoe** [folivoraAI/BetterTouchTool#507]
I use Better Touch Tool to assign touch gestures (tap left / tap right) to mouse actions (left click / right click).
Every time my Mac wakes up from sleep mode the gesture recognition goes completely crazy, mostly it is that every sort of click, whether left or right gets interpreted as a right click. So clicking left is no longer possible when using touch gestures, physical clicks are still working. Usually after clicking around for about a minute everything goes back to normal.
 
I use a MacBook Air 2013 with Mac OS 10.12.3 and a Magic Mouse Gen 1.

**Comment by sundarv85** [comment]
+1

This seems to be an issue with the recent update. Can this be fixed soon. Otherwise, I end up restarting better touch tool everytime.

**Comment by jjustinn** [comment]
I'm having the same issue.

**Comment by eugene-volin** [comment]
+1 Same issue
