### ISSUE TITLE
Scroll wheel right/left click needs sensitivity adjuster

### ISSUE THREAD

**Issue by Voyeurista** [folivoraAI/BetterTouchTool#516]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:

Precision mice, specifically any Microsoft BlueTrack mouse, creates a double action, when sideways clicking the mouse wheel. This error occurs whether using the Bluetooth or USB dongle version of any BlueTrack mouse. 

I use the right and left mouse wheel clicks globally for:
Mouse Button > Scroll Right > Move Right a Space
Mouse Button > Scroll Left > Move Left a Space  

Seven times out of 10, the click will move the screen two spaces to the right or left. It appears to be somewhat dependent on either pressure or length of time pressed, but unsure which. 

I've been practicing clicking lightly enough to only get it to move one space for about 4 years now, but I still can't master it. I can usually (on the corrective try) tap it gently enough in the reverse direction to go back to the space I wanted, but it's an inconvenience. 

My request is: Please add sensitivity controls for "Normal Mice" to address overly sensitive wheel clicks (and whatever else might be overly sensitive if you buy one to test it). 

**What kind of Mac are you using?**
Currently on a MacBook Pro (Retina, 15-inch, Mid 2014). However, I can confirm it occurs on any MacBook Pro, except for the most recent model, which I haven't yet tested. BTW, I'm an independent Apple computer consultant. 

**Which input device (e.g. MacBook Trackpad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
Ultra Precision Normal Mice. Specifically Microsoft's BlueTrack mice. 

**Which versions of macOS and BetterTouchTool are you running?**
Currently running latest version of BTT. But this problem has been ongoing for about 4 years. Applies to Mountain Lion through Yosemite. Haven't tested it with El Cap or Sierra. 

**Other information:** (e.g. stacktraces, related issues, screenshots, suggestions how to fix, etc.)
Please see above. 

Note: In case of bug reports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by fifafu** [comment]
This issue was moved to https://community.folivora.ai/t/scroll-wheel-right-left-click-needs-sensitivity-adjuster/61
