### ISSUE TITLE
Cursor size being reset on quit

### ISSUE THREAD

**Issue by aldenc98** [folivoraAI/BetterTouchTool#517]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:
I have changed my OSX cursor size to be larger than normal:

Accessibility -> Display -> Cursor Size

When quitting BTT, it causes the cursor to change back to the normal size.  The only way to restore the size is to slightly change the cursor size slider, and then it will jump back.  Ideally, quitting BTT shouldn't change the cursor size.  I don't know if this is a BTT or OSX issue.

**What kind of Mac are you using?**
Macbook Pro, Retina, 15", Early 2013

**Which input device (e.g. MacBook Trackpad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
MBP Trackpad

**Which versions of macOS and BetterTouchTool are you running?**
OSX Sierra 10.12.3, BTT 2.071 (608)

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by Wasatch1** [comment]
I also have the same issue with cursor size reseting back to normal when launched. The cursor also reverted back to normal after wake from sleep.

**Comment by toyg** [comment]
Same here. OSX Sierra 10.12.4, mbp 15'' late 2016, radeon pro 455. I have an external screen attached, which means the radeon is always on. I'm using the old external Magic Trackpad.
