### ISSUE TITLE
[Feature Request] Be able to write our own Touch Bar widgets

### ISSUE THREAD

**Issue by epaga** [folivoraAI/BetterTouchTool#519]
#### Description of your bug/question/feature request...:

**What kind of Mac are you using?**
tMBP 15" 2016

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

Touch Bar

**Which versions of macOS and BetterTouchTool are you running?**

Latest

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Would be great as a developer to be able to easily write my own custom widgets for whatever I want to do and then be able to add it in with BTT. Or is there already a way to do this?

**Comment by pallavmac** [comment]
You can use the apple script widget.

**Comment by epaga** [comment]
Though that is very cool and helpful, it is for text only, though, right?

Would be nice to be able to create graphical widgets. (Like color pickers or whatever)
