### ISSUE TITLE
Bloated Usage Logging

### ISSUE THREAD

**Issue by Kimischa** [folivoraAI/BetterTouchTool#522]
Early (2015) MacBook Pro with force touch Trackpad
Sierra 10.12.3
BTT 2.071 (608)

The new logging data is very useful. It makes the prioritising of gestures easier.

I use the Rotating gesture to change the volume (highly recommend it).
BTT recognises each individual level change in Volume as a gesture. So when I change the volume by 7 levels it logs 7 gestures. But the actual gesture of my hand is just one - I rotate left or right with two fingers. 

![screenshot 2017-02-21 19 22 37](https://cloud.githubusercontent.com/assets/17577837/23179733/345a3cda-f86f-11e6-94a3-a592cd1aa091.png)

Would it be possible to let BTT recognise it as one gesture when volume is changed by several levels but only one gesture?

**Comment by fifafu** [comment]
This issue was moved to https://community.folivora.ai/t/bloated-usage-logging/58

**Comment by fifafu** [comment]
Sorry, please ignore the previous message. The migration didn't work correctly, for now the issues will stay here.
