### ISSUE TITLE
Extract Icon from Preset

### ISSUE THREAD

**Issue by sebastienbarre** [folivoraAI/BetterTouchTool#528]
#### Description of your bug/question/feature request...: How can I extract icons from a preset?

I'd like to derive new TouchBar actions from a set of actions I already found in a preset online.
One such action has a nice icon for "Maximize Window Left", and I'd like to create a new icon based off this one for a new "Resize Window to Left Two Thirds" action in my TouchBar. It would help if I could extract the icon from the already existing action, for consistency. Thanks.

**What kind of Mac are you using?**

MacBook Pro 2016 w/ TouchBar

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

It's in the context of the TouchBar

**Which versions of macOS and BetterTouchTool are you running?**

latest macOS Sierra and BTT 2.071

**Comment by fifafu** [comment]
Unfortunately that's currently not possible. I'll check if I can enable this somehow.

**Comment by sebastienbarre** [comment]
Thx! Or if you document the preset format, I might try to extract them myself...

**Comment by fifafu** [comment]
It's a core data binary store with images saved as NSData, I don't think it makes sense trying to extract from there (probably faster to find that icon online ;-)).

**Comment by sebastienbarre** [comment]
Oh I looked online :) To no avail :)
