### ISSUE TITLE
Touch Bar Brightness Slider doesn't work if used with ctrl modifier

### ISSUE THREAD

**Issue by xHarbourCom** [folivoraAI/BetterTouchTool#530]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:
The Brightness Slider does not work. Nothing happens if I uses it on the Tough Bar.
https://db.tt/5dZ4FayO3T

**What kind of Mac are you using?**
Macbook Pro 13"
https://db.tt/kFEUtFt9pR

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
Tough bar

**Which versions of macOS and BetterTouchTool are you running?**
Latest

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

**Comment by fifafu** [comment]
Sorry, the brightness slider currently can't be used for the internal display while CTRL is pressed. (Pressing ctrl while moving the slider changes the brightness of external displays).

I'll check if I can disable that behavior if the slider is marked to only show while ctrl is pressed.
