### ISSUE TITLE
Issue with Astropad and Photoshop

### ISSUE THREAD

**Issue by pstrudl25** [folivoraAI/BetterTouchTool#539]
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

When using Astropad (a great way to use your iPad like a Wacom Tablet) there is an issue with Photoshop, no other drawing apps are affected: When I want to draw every new stroke starts with a line from the previous position. So, when I try to draw e.g. two independent circles they are connected by a (unwanted) stroke. By deactivating BTT in Photoshop the problems are gone - I use this now as a workaround. 
Great piece of software anyway, I love it!

**What kind of Mac are you using?**
MacPro 2013

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

**Which versions of macOS and BetterTouchTool are you running?**
MacOS 10.12.3 (16D32)
BetterTouchTool 2.071 

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

![bildschirmfoto 2017-02-24 um 11 57 42](https://cloud.githubusercontent.com/assets/26002922/23301059/99aef4a2-fa88-11e6-8b99-bbd8586ab88c.png)

**Comment by Takuro123** [comment]
Issue seems to have resurfaced with a vengeance in BTT 2.310. Would be nice if we weren't *forced* to use the absolute latest version, granted attempts to downgrade raise a warning that the version is expired.

**Comment by fifafu** [comment]
That's not true, you are absolutely not forced to use the latest version. If a valid license is installed BetterTouchTool versions do not expire.

However the data format regularly changes, but BTT keeps copies of the previous ones in ~/Library/Application Support/BetterTouchTool (just remove the oldversionbackup extension.
