### ISSUE TITLE
[FEATURE REQUEST] - Timed touchbar with BBT

### ISSUE THREAD

**Issue by victorMalkov** [folivoraAI/BetterTouchTool#541]
I am running BBT (2.071) on the 13 inch MBP with touchbar (Sierra - 10.12.3). I have noticed that there are many times when I use BBT defined touchbar buttons, but I would also like to have access to app specific touchbar options (ones that are not defined by BBT). One way of dealing with this would be to let the user set a time interval after which the BBT touchbar action close and leave only the app defined ones.

Thanks!

**Comment by anas2204** [comment]
I have requested a similar feature as well:
https://github.com/fifafu/BetterTouchTool/issues/314
