### ISSUE TITLE
Allow users to update BTT's docs

### ISSUE THREAD

**Issue by cleverjackal** [folivoraAI/BetterTouchTool#545]
Why not? It seems like a cool idea. Then you wouldn't have to spend that much time updating the documentation yourself.

**Comment by fifafu** [comment]
That's the idea of this git repository ;-) people can checkout the documentation and submit merge requests. I have to admit that this focuses on advanced users with knowledge of GIT.

**Comment by cleverjackal** [comment]
Oh, I see. I must have looked at the the readme in the docs folder (which is write protected, I believe?) and thought automatically that everything was edit-protected. I can edit stuff now!

**Comment by fifafu** [comment]
Mhh there shouldn't be anything write protected.
I think it might be a good idea for me to describe the process of adding something to the documentation to the readme.

**Comment by cleverjackal** [comment]
No no, I think everything's fine. It's just README.md that I can't edit, and I think that doesn't really need to be edited. I can upload files too, I think. I'm just kind of new to GitHub. 

I could help in writing that, if you wanted me to.

Did you get my pull request?
