### ISSUE TITLE
[FEATURE] Context/Application-aware Keyboard Shortcuts

### ISSUE THREAD

**Issue by ghost** [folivoraAI/BetterTouchTool#547]
This is something that's done in several competing products. You bind a global command such as "Refresh", and anytime you press the "Refresh" key, the shortcut-application (such as BTT) sends the appropriate "Refresh" command based on whatever application is in focus.

Yes, BetterTouchTool can do this by adding per-application rules manually.

But that method means tons of duplication of tap-commands, and hassle keeping them all in sync. And it's not newbie-friendly. Newbies don't know what keypresses to send.

There are so many other actions in BTT, so why not add these smart "defaults"? Along with a Settings editor to add further exceptions to the defaults. What that would mean is that you just globally bind ONE action and it will intelligently adapt itself to the active application. And when you want to rebind it, you rebind ONE action, and you're done. :-) That's why the competition is much slicker in this regard.

Context-aware Keyboard Shortcuts in competing products provides the following actions, along with what they map to globally (which is the most common shortcuts for that kind of action in all applications on Mac), and what they map to when certain special applications are in the foreground:

- Previous Tab: ⌃⇧TAB
- Next Tab: ⌃TAB
- Open Link in New Tab: Send Middle-Click
- New Tab: ⌘T
- Close / Close Tab: ⌘W
- Open Recently Closed Tab: ⇧⌘T by default, ⌘Z in Safari
- Refresh: ⌘R by default, ⇧⌘N in Apple Mail (and Readdle's Spark Mail)
- Quit: ⌘Q
- Hide: ⌘H
- Full Screen: ⌃⌘F
- New: ⌘N
- Open: ⌘O
- Save: ⌘S
- Copy: ⌘C
- Paste: ⌘V
- Scroll to Top: HOME
- Scroll to Bottom: END

**Comment by fifafu** [comment]
Hey,

There won't be any integrated default actions, however this will become possible with the upcoming import/export system and the sharing platform. I'm planning to release that sometime next month :-)

**Comment by SteveJobzniak** [comment]
@fifafu Sounds cool, I'm excited! :-D
