### ISSUE TITLE
[ENHANCEMENT] Better way of starting gesture drawing

### ISSUE THREAD

**Issue by ghost** [folivoraAI/BetterTouchTool#551]
Recently you added a "hold right click and move the cursor to draw a gesture" mode. That's great for a mouse. Not great for a touchpad.

It doesn't react to mere two finger-tap right clicks. So I have to tap and press hard to CLICK, and then I have to draw on the pad while still pressing hard to keep the pad pressed down so that the right-click remains. It's a mess.

Please think about adding the way Jitouch does it: https://www.jitouch.com/characters/ (see the video).

You just place the index finger and ring finger on the pad and draw with two fingers. No need to click. No need to tap.

It detects the two control points on the touchpad, and the distance between them, and realizes "this person is drawing a gesture with their index and ring finger".

Download the demo to try it, Andreas. It's far better than anything in BTT. Because enabling gesture drawing with a keyboard shortcut in BTT is no good (that requires two hands). And having to deeply click the trackpad is no good (that requires force to keep it held down otherwise the drawing window vanishes, and using force means you can barely move your fingers due to friction, least on old trackpads). And using a gesture such as "4 finger tap" to start drawing is semi-ok in BTT but still not as slick as just "draw instantly with index finger and ring finger".

Please think about it. I seriously guarantee that this drawing method works perfectly and doesn't conflict with any other gestures. In 5 months of Jitouch, I've accidentally triggered drawing this many times: 0 times. ;-)

It is super ergonomic, and they let you configure the index to ring finger distance if you aren't a normal human. So its detection of drawing is literally perfect!

**Comment by arikd** [comment]
I wish the BetterTouchTool would be able to be able to create gestures without clicking too. JItouch is very good in this. I am a great fan of it, even if I struggle sometimes with it because it is not accessible.
👍
