### ISSUE TITLE
[FEATURE] More ergonomic window management tool

### ISSUE THREAD

**Issue by ghost** [folivoraAI/BetterTouchTool#553]
Final ticket. And it's about the number one feature I am missing since I left Jitouch (https://www.jitouch.com) to return to BetterTouchTool.

They have a feature called "Move / Resize". By default it's bound to "tap and hold with index finger, and slide with your middle finger next to it".

- 1 finger held, 1 finger slide down: Open move tool.
- 1 finger held, 1 finger slide up: Open resize tool.
- When a tool is open, keep holding 1 finger and then tap with the 2nd finger to switch between the tools.

This opens a small overlay tool on top of your mouse cursor, which shows some 4-way arrows when you are moving a window, and some 2-way diagonal arrows when you are resizing a window.

It's similar to BTT's "Start/Stop Moving" and "Start/Stop Resizing" actions. But they're baked into one single tool/action, and you can always see which tool is active (by the icon hovering next to your mouse cursor), and you can switch between them.

If there's one thing I loved more than anything else in Jitouch, it was having this perfect window move/resize tool bound to a single gesture. No need for multiple gestures. No need to constantly wonder if the tool was active or what tool was active. It just worked.

In BTT, my gestures may not be recognized and then I don't know if my move or resize action is active, and I just end up frustrated.

Try out Jitouch's method. Window management is such a hassle without having this excellent tool anymore. Hehe. ;-) It even made me consider keeping Jitouch instead of BTT. Or running both Jitouch and BTT at the same time. But seriously, BTT is a far more powerful product. And it nearly has this feature already.

All BTT needs is to merge "Start/Stop Moving" and "Start/Stop Resizing" into a single action which cycles between the tools _and_ shows a state-icon next to the cursor. Then this excellent window management feature could be bound to a single gesture and not take up more gestures than necessary.

**Comment by fifafu** [comment]
This issue was moved to https://community.folivora.ai/t/feature-more-ergonomic-window-management-tool/62
