### ISSUE TITLE
Menubar in Context Menu Accessibility: Font Size for Old Mother

### ISSUE THREAD

**Issue by aitte2** [folivoraAI/BetterTouchTool#563]
Hi! My old mother uses the "Show Menubar in Context Menu" action to be able to open an app's menu anywhere without having to move the mouse so much.

But the menu font is too small for her to see without glasses. Would it please be possible to make the context menu font size configurable so that she could make it big? :)

**Comment by cleverjackal** [comment]
_Perhaps_ you could try [this](https://discussions.apple.com/message/10050205?tstart=0#10050205)

**Comment by SteveJobzniak** [comment]
@cleverjackal That's from 2009, that setting isn't available anymore. :P

**Comment by cleverjackal** [comment]
@SteveJobzniak It's strange Apple has all these accessibility features, but no text size on the Mac...
