### ISSUE TITLE
One Finger Tap Fails to Click When Two Fingers Rest on Mouse

### ISSUE THREAD

**Issue by jjustinn** [folivoraAI/BetterTouchTool#564]
Hello,

I'm using the Magic Mouse 2 and Better Touch Tool.
I have set a Tap to function as a Click. However, I usually rest two fingers on the mouse when using it. After some time, the mouse will no longer recognize a Tap as a Click. Creating a TipTap has helped but it still happens on a regular basis.
Any solutions would be appreciated.

Macbook Pro Retina mid-2012
Magic Mouse 2
Sierra v.10.12.3
BTT 2.071

**Comment by maranthea** [comment]
^ I have same problem. 

I created a TipTap Left (1Finger Fix) Magic Mouse Gesture and set it to Left Click as Action. 

Process:
Rest middle finger on right side then tap other finger on left side = does the gesture. BUT when I scroll down after tapping left side of the mouse and I try to click again by tapping the left side, it usually doesn't work - to make it work, i have to remove both fingers and re-do the resting + tap again. Kinda frustrating to do it. I have set 1 Finger tap as Left Click also, but I don't want to re-do the finger resting and tap again. 

I tried to set the advance settings to:
Required Tap Pressure =0
Magic Mouse TipTap Sensitivity to 0 (Lighter Touch
Time fingers can be down until a tap is not recognized as a tap anymore: 0.5

 but that didn't fix it as well. 

Macbook Retina Early 2016
Magic Mouse 2
Sierra v10.12.3
BTT 2.071 / 2.08

**Comment by geowyn** [comment]
I have noticed the same thing.  I tend to rest my left index finger on trackpad when clicking.  this works fine if BTT not loaded, but with BTT the click is not recognized.  like @maranthea I have added the TipTap Left action to map to left click, but it does not seem to work consistently.  when in LiveView it is always recognized.

**Comment by fifafu** [comment]
Sorry, there is no solution to that. BTT needs to block clicks in some situations  when multiple fingers are touching the trackpad, otherwise BTT gestures wouldn't work reliably.
You can try to delete all 2 finger gestures you are using in BTT, this may solve your issues.

**Comment by geowyn** [comment]
Quick follow up... is there a reason why TipTap Left is not being recognized and activating a left click?  if the left finger is doing a click rather than a tap does that not trigger?

**Comment by fifafu** [comment]
@geowyn, tip taps currently only work with taps :-). Although "TipClicks" could also be interesting.
