### ISSUE TITLE
Disable Global Settings Per Application

### ISSUE THREAD

**Issue by mvdivotfixer** [folivoraAI/BetterTouchTool#567]
#### Description of your bug/question/feature request...:

Is it possible to define APPLICATION SPECIFIC to Touchbar Hide Global Actions?   Scenario:  I have several Global Actions defined (Time, Battery Life, ...).   In most applications I want them also visible (so NOT hidden in the global setting).  However when working with a code editor, I want to define Actions specific to that environment (say, using GIT) and don't want the global actions visible as they take up a bunch of space.  

Using the Application Specific menu I could only see how to hide the entire BTT Touchbar (or not) for a specific application.  What I want is an option on the Application Specific menu to say "Show BTT Touchbar, but not the Globals..." 

**What kind of Mac are you using?**

MacBook Pro 2016 15"

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

Touch Bar

**Which versions of macOS and BetterTouchTool are you running?**

BetterTouchTool 2.071
OSX 10.12.3

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by fifafu** [comment]
Good idea, I'll add this to the app-specific settings soon!

**Comment by mvdivotfixer** [comment]
👍👍👍 (that me, using my new Emoji Widget on my BTT enhanced toolbar...)

**Comment by rodalpho** [comment]
I would like to request this same functionality for other modules of the application including keyboard, touchpad, and mouse. 

Story is that I'm a windows switcher and remap CTRL-C to command-C to copy. But this really screws me over in the terminal where I have to stty remap intr to another button, and then do this every time I SSH somewhere. 

If there was a "disable global mappings for this specific application" flag, that would address my use-case.

**Comment by FlyingMoses** [comment]
I would second the above suggestion-- unless there is some way I do not know of to disable global BTT shortcuts without disabling BTT entirely? For example, I have several keyboard shortcuts for windows snapping, etc. but when I'm in a code editor or shortcut-heavy application, they conflict more than I would like. However I would still like to use the touchpad settings and custom gestures to link up with certain shortcuts.

**Comment by nashbridges** [comment]
@rodalpho "Use Apple Default Or Do Nothing" from [this comment](https://github.com/fifafu/BetterTouchTool/issues/608#issuecomment-284221063) did the trick for me.

**Comment by rodalpho** [comment]
Thanks, that worked! Not easily discoverable, gotta say.

**Comment by andredalbuq** [comment]
My thing here is: I have a few shortcuts on my global touchbar, but there are some specific things that i only want to do in an app. and dont care about other global things. does this make sense?

**Comment by kerim** [comment]
The "Use Apple Default Or Do Nothing" doesn't work for disabling the global touch bar on a per-application basis. There seems to be no way to allow the global settings in the touch bar to work for all but one app that has its own settings?

**Comment by Jendker** [comment]
+1 to kerim's question. This feature would be still so useful 😊

**Comment by lingdoc** [comment]
+1 to this - currently there seems to be no way to set app-specific controls in BTT while ALSO turning off BTT globals. The only option that seems to address this in the BTT menubar is the universally-applied preference:

> Hide global actions if app specific actions are configured in BTT

with its related two choices:
> Show Global Actions Before App Specific Actions
> Show App Specific Actions Before Global Actions

What this means is that if I want to use BTT in two apps, and 1) I want to show globals normally in App 1, but 2) I want to disable them for App 2 (to free up touch bar space), this is not possible.

 The only way to make this work is to disable globals for ALL apps via the setting above, and then to copy (one by one) all the global configurations to each app for which I DO want the globals to be available. If I use lots of different apps with a few individual configurations, but with global options as well, you can see how time-consuming this gets.

Better would be a single menu item in the 'App Specific' drop-down menu that allows the user to 'Disable BTT globals for this app'.

 Another option might be adding a button/widget type that activates immediately when the application in question runs, and then you could use the 'Force Show/Hide Global BTT Touch Bar Actions' trigger, but I can't figure out how to get this to work. Suggestions?

**Comment by Lamadros** [comment]
@mvdivotfixer 
For this case i set workaround:
1) I create "Condition Activation Group" ( screenshot - http://prntscr.com/lf8pkb )
2) in setting of this group i set rules for application on which i do not want to show my global buttons.
(screenshot -> http://prntscr.com/lf8q5e)
3) I move all buttons from global to custom condition group which i created on step(1)
(select global; press command + c; select custom group; press command +v ) 
4) i delete all buttons from global.

In this case all global buttons will display in all application except apps which we set on step(2).

**Comment by kerim** [comment]
@Lamadros Thanks. This works great. If "Global" had these "condition activation" settings built in it would solve the problem, but this seems to work just as well.
