### ISSUE TITLE
BTT Touch Bar often does not work, Global only works after interacting with BTT

### ISSUE THREAD

**Issue by bcoia** [folivoraAI/BetterTouchTool#578]
When switching apps, my BTT Touch Bar actions rarely appear in the Touch Bar. Both app-specific and global buttons tend to disappear when changing apps, and only appear when either a) changing a setting in BetterTouchTool (e.g. reordering buttons/widgets) or b) using a modifier key tied to a BTT Touch Bar button.

I've tried using it with and without the control strip enabled. Neither is consistent.

I've rebooted and rebuilt my app-specific preference from scratch. I'm not sure if there's a way to reset the 'General Touch Bar Settings' preferences short of deleting plists.

I'm not sure where to proceed from here. Ideally, I'd like app-specific buttons to always appear when switching to the app, and I'd like my global buttons to appear in place of the control strip, without needing to activate a modifier for them to start appearing.

**What kind of Mac are you using?**
15" Retina Touch Bar MacBook Pro (2016)

**Which input device (e.g. MacBook Trackpad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
Touch Bar

**Which versions of macOS and BetterTouchTool are you running?**
10.12.3, 2.08 (issue has been affecting me since late 1.x versions)

**Other information:** (e.g. stacktraces, related issues, screenshots, suggestions how to fix, etc)

Current settings:

![image](https://cloud.githubusercontent.com/assets/1163683/23377559/126340e6-fcf6-11e6-8564-bcf01a4189f4.png)

![image](https://cloud.githubusercontent.com/assets/1163683/23377565/190f4052-fcf6-11e6-97ef-9b276504b676.png)

Let me know if there is anything else I could upload to help!

**Comment by fifafu** [comment]
As far as I can tell it is working as intended, however maybe one day thing you need to know:
When you hide the BTT Touch Bar it will stay hidden until you unhide it manually (either by pressing the BTT Touch Bar button or by using the predefined action "toggle Touch Bar".

You can force the Touch Bar to show by using the "app-specific settings" (button below the application list)

**Comment by bcoia** [comment]
I think I understand now! I think my use case may be stretching what BTT's Touch Bar features are currently designed to handle.

Forcing the BTT bar to show for each application (e.g. Slack, where I have a couple of buttons + the global buttons) works as I expected.

However, with my current settings, the default global behavior for apps not forced to display the BTT bar is a bit strange--if I press alt, the app switcher shows, and on releasing alt, the global bar shows, replacing the app default bar and control strip. This occurs even if I force the app-default bar. (e.g. Airmail 3, regardless of if I define it as app-bar-only in BTT or remove it from BTT altogether, will show its app bar until I hit alt, then only shows the BTT global bar when releasing alt.)

Are my global bar preferences bending the rules, or is this by design?

(Also thanks for the quick response! 😄 )
