### ISSUE TITLE
Icon Sizing

### ISSUE THREAD

**Issue by minimumsix13** [folivoraAI/BetterTouchTool#595]
#### Description of your bug/question/feature request...:
Currently it looks like BTT only supports icon sizing up to 40px in width for the Touch Bar. Is this a limitation Apple enforces? If not, I'd love to see the padding customized based on dominant width/height for slightly longer icons.

**What kind of Mac are you using?**
15" 2016 MacBook Pro

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**
Touch Bar

**Which versions of macOS and BetterTouchTool are you running?**
macOS 10.12.3
BTT 2.08

**Comment by jl2012** [comment]
It'd be nice if the user could directly set the size of icon, not just the padding
