### ISSUE TITLE
Scrolling in BTT window is slow

### ISSUE THREAD

**Issue by cleverjackal** [folivoraAI/BetterTouchTool#599]
#### Description of your bug/question/feature request...:
For some reason I've noticed scrolling in BTT is always slow. In the Finder, for instance, scrolling when you have a lot of folders and files on screen is really smooth. In BTT, scrolling is kind of slow and almost laggy, it feels like. This isn't that important but I couldn't find anything when I searched for it :)

**What kind of Mac are you using?**
MacBook Pro 

**Which versions of macOS and BetterTouchTool are you running?**
macOS Sierra 10.12.3
BTT v2.08

**Comment by ovisan** [comment]
Same issue here. In fact, scrolling is slower overall with BTT running. Once it's closed, scrolling is smooth.
I saw also problems with delayed mouse clicks when BTT is running.

**Comment by fifafu** [comment]
@ovisan, that's a different issue. This can indeed happen when your computer is very busy, thus doesn't give BTT enough resources to handle all the events.
Maybe find out via activity monitor which process is using a lot of cpu.

The scrolling in the BTT window can definitely be improved though, it's not very optimized and e.g. does the icon scaling quite inefficiently at the moment.

**Comment by ovisan** [comment]
@fifafu the load was the same on my system and scrolling was definitely slower in Safari. I will reset BTT to the default settings and try again, to be sure.

**Comment by cleverjackal** [comment]
@fifafu I noticed that the scrolling in the Xcode code window is just as "slow" as in the BTT window. Nevertheless, it's not as fast as in the Finder, for example, so it also might be an optimization issue as you mentioned. Probably not the most important bug, though, haha.
