### ISSUE TITLE
Request: Make shortcuts with TuchID button

### ISSUE THREAD

**Issue by ISS5731** [folivoraAI/BetterTouchTool#601]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/question/feature request:
Request. Right now if you triple click the TouchID button, it brings up accessibility options. If you can add a feature where I can change what this button does that'd be awesome.

#### What kind of Mac are you using?
MacBook Pro 13' with touch bar. 256GB, 8GB RAM.

#### Input device affected (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar):
Touch Bar

#### BetterTouchTool and macOS version:

macOS 10.
10.12.4 Beta
BetterTouchTool v
Alpha 2.08
#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Unfortunately I haven't found a way to do this. I'll leave this issue open, but currently I have no idea whether this will ever be possible.
