### ISSUE TITLE
change default single click

### ISSUE THREAD

**Issue by rohku** [folivoraAI/BetterTouchTool#604]
Hello -- I just started using this great tool, but I couldn't find anything about changing the default click.  Apologies if it's a repost.

Here's an old post:

http://superuser.com/questions/920734/strong-force-touch-feedback-for-normal-clicks

where the top answer shows what I wanted.  But I don't see it in the current version.  Is there a way to change the default click to one of the options listed?

I also noticed that when changing settings in Advanced, Trackpad, FORCE Touchpad, the haptic response only changes for 4 or 5 finger clicks even though it says 2-5.

thanks!  Again an amazing tool and window snapping is great (coming from windows, forced to use mac for work).

BTT ver 2.071 (608)
OSX 10.12.3
macbook pro retina 15 inch, mid 2015

**Comment by holodoctor1** [comment]
Ditto... would love stronger feedback when single or double clicking.  I have to believe it is possible since a force click provides a stronger "click" sensation.  +1 to this feature from me as well!
