### ISSUE TITLE
Bug: TouchBar Widget Failure

### ISSUE THREAD

**Issue by jim1379** [folivoraAI/BetterTouchTool#606]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/question/feature request:
I used the brightness control widget with control button on my MBP2016 TB, but it cannot control when I added control button to call it.
Although it had control panel and even I slide it, that's inactive.

#### What kind of Mac are you using?
MacBook Pro 2016 15 inch with TouchBar 16gb/512gb

#### Input device affected (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar):
Touch Bar

#### BetterTouchTool and macOS version:

macOS 10.12.3

BetterTouchTool v.2071

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Currently when pressing ctrl the widget changes the brightness of external displays. I'll make this configurable with one of the next versions.
