### ISSUE TITLE
Snap areas disappeared.

### ISSUE THREAD

**Issue by sorttouchtool** [folivoraAI/BetterTouchTool#607]
My snap areas disappeared suddenly. They are still in my gestures, but when I use them they don't work, and when I press "edit snap areas" they are all gone. This is specifically on my monitor. I use them both on my laptop and my monitor.

Macbook Pro Retina 13 2013

Trackpad

#### BetterTouchTool and macOS version:

macOS 10.

BetterTouchTool v

---

Reset computer, but snap areas did not return.

**Comment by fifafu** [comment]
Hi!

Snap Areas currently need to be configured per screen, this means the ones that you have configured for your laptop screen won't show up on any other monitor by default.

This has various technical reasons, but maybe this will change in an upcoming version.

**Comment by sorttouchtool** [comment]
Yes, I set them up for both separately... but my monitor's snap area 
settings disappeared for some reason. It happened once before... I had 
to remake it. They still show up in my gestures, but the snap areas 
themselves are deleted.

**Comment by sorttouchtool** [comment]
This may have coincided with connecting to a different monitor (home TV) 
- perhaps this made the snap area system delete my previous monitor's 
snap areas?
