### ISSUE TITLE
BTT not working with apps installed via JetBrains Toolbox App

### ISSUE THREAD

**Issue by dvanoni** [folivoraAI/BetterTouchTool#609]
#### Description of bug/question/feature request:

I recently started using the [JetBrains Toolbox App](https://www.jetbrains.com/toolbox/app/) to install JetBrains IDEs (WebStorm, AppCode, etc.) Unfortunately it appears that BTT does not work with these apps when installed via the Toolbox; BTT appears to not detect that the app is active when it is. However BTT _does_ work if you install the standalone app directly.

#### What kind of Mac are you using?

MacBook Pro, 15-inch, 2016 (Touch Bar)

#### Input device affected (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar):

All

#### BetterTouchTool and macOS version:

macOS 10.12.3

BetterTouchTool v2.071

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

When installing apps via the Toolbox, they are installed to `~/Applications/JetBrains Toolbox/WebStorm.app` as opposed to the standard `/Applications/WebStorm.app`. I tried creating an alias of the app in `/Applications` and connecting BTT to the alias, but that did not work either.

I was able to set up BTT with another app in my home directory just fine; a Google Chrome web app located at `~/Applications/Chrome Apps.localized/Default fhbjgbiflinjbdggehcddcbncdddomop.app`

I did find an interesting workaround... I installed WebStorm directly to `/Applications` (via Homebrew Cask) and configured that in BTT. This worked fine with BTT, as mentioned above. Then I removed this app and, without changing any settings in BTT, launched the version of WebStorm installed via the Toolbox. BTT then worked with it, even though this version of the app was _not_ the one configured in BTT!

Workaround step-by-step:
1. Install standalone app (either from JetBrains website or via Homebrew Cask)
2. Configure standalone app in BTT
3. Uninstall standalone app
4. Install same app via JetBrains Toolbox App
5. BTT works with the app correctly

**Comment by fifafu** [comment]
I'll look into this! I'm currently adding a way to identify problematic apps via other means, which will probably also solve this issue.

**Comment by tarfu** [comment]
As a workaround you could do the following:
`cd /Applications
ln -s ~/Applications/JetBrains\ Toolbox JetBrains\ Toolbox`

This will link the folder and  you can select it in BTT and then in the "fn keys" option in the macOS settings
