### ISSUE TITLE
Add fade animation to window snapping

### ISSUE THREAD

**Issue by cleverjackal** [folivoraAI/BetterTouchTool#610]
#### Description of bug/question/feature request:

There's an option to "animate window snapping" in BTT. However, it "moves" a bit too much which is why I personally turned it off. What I really would love is to have an option to make the preview window fade in/out when snapping windows. Right now, if you turn the animation off, it just appears and disappears – which looks a bit jarring as well, in my opinion.

Also, maybe I'm being a bit picky, but I'd like to be able to choose the border radius for the "rounded corners" option for the preview window (I find the default radius too large). I'm only suggesting this because it may be really easy to implement – but then again, I don't know anything about it, so... :)

**Comment by fifafu** [comment]
Good idea!

The corner radius can be changed using this terminal command (while BTT is quit):
```
defaults write com.hegenberg.BetterTouchTool BSTCornerRoundness 20
```
Default value is 40.

**Comment by cleverjackal** [comment]
Cool, thanks! I'll put that in the docs sometime.

**Comment by fifafu** [comment]
I should just put it into the UI sometime :-)

**Comment by cleverjackal** [comment]
Sure yeah! That would also be great :)
