### ISSUE TITLE
Question: Disable Top Portion of TrackPad

### ISSUE THREAD

**Issue by fsmertz** [folivoraAI/BetterTouchTool#618]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
I am a total newbie when it comes to using this product. I may have a simple question (or it may not be supported at all), but I want to be able to prevent the top inch of the new large trackpad from accepting input. Is this possible with this product?

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
MacBook Trackpad

#### Device information:

Type of Mac: MacBook Pro 2016
macOS version: 10.2.3
BetterTouchTool version: 2.071

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by Tukan3** [comment]
I am also interested in this particulare feature.

**Comment by antoniovdeleon** [comment]
I know a lot of people who wish this feature was available.

**Comment by chrispine** [comment]
I would absolutely love this. I would definitely renew my license for this feature.
