### ISSUE TITLE
Feature Request "Touchbar Sliders/Buttons for MIDI & OSC bi-directional mapping"

### ISSUE THREAD

**Issue by erikvenhues** [folivoraAI/BetterTouchTool#62]
would like to see touchbar working as midi/osx mappable interface.
Hopefully BTT can make it happen :)

my wish:
-Sliders with OSC / MIDI
-Buttons with OSC / MIDI
-Data Fields for OSC / MIDI Data
-Layer option for many sliders / buttons

**Comment by kfigiela** [comment]
As a temporary solution it looks like https://github.com/DouglasHeriot/DHSendMIDI should work for buttons.
