### ISSUE TITLE
QUESTION: Custom Keyboard Shortcut to Include Mouse Click?

### ISSUE THREAD

**Issue by WuMyster** [folivoraAI/BetterTouchTool#620]
#### Description of bug/feature request/question:
I'm wanting to bind a three finger click to CMD+Shift+Middle Mouse Click (set as three finger tap) or CMD+Shift+Click however the custom keyboard shortcut obviously won't accept/register my shortcut due to the click. Anyway around this?

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
MacBook Pro Trackpad

#### Device information:

Type of Mac: MacBook Pro 15" Late 2016
macOS version: 10.12.3
BetterTouchTool version: 2.071

**Comment by kuglee** [comment]
You can use the "More Mouse Buttons & Modifiers" action.
![nevtelen](https://cloud.githubusercontent.com/assets/1316211/23743564/5a8a311e-04b1-11e7-9702-478a1553f71f.png)
