### ISSUE TITLE
Feature Request: support to ignore horizontal mouse scrolling

### ISSUE THREAD

**Issue by weinand** [folivoraAI/BetterTouchTool#621]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Today I still have to use MagicPrefs to disable horizontal mouse scrolling (in addition to BetterTouchTool). It would be great if BTT could support this feature as well.

Feature Request: support to ignore horizontal mouse scrolling

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Magic Mouse

#### Device information:

Type of Mac: MacBook Pro (15-inch, Late 2016)
macOS version: 10.12.3 (16D32)
BetterTouchTool version: 2.071

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by wanyaxing** [comment]
+1 for this fuature.

I googled this solution for many days and eventually I just found magicPrefs.
 https://superuser.com/a/1194004/821433

**Comment by abku** [comment]
+1 for this feature.

magicPrefs does it even in the latest version but it is unsupported and I do not want to have 2 applications running at the same time if one can do the job.

**Comment by weinand** [comment]
@fifafu was this closed because it is fixed or because the feature request is invalid?

**Comment by fifafu** [comment]
The BTT issue tracker has moved to https://community.folivora.ai early this year and all issues here have been auto-closed now. In case you still need help with this issue / feature / question please create a new post there.
