### ISSUE TITLE
Three and two fingers click doesn't work in certain apps

### ISSUE THREAD

**Issue by Yakow13** [folivoraAI/BetterTouchTool#627]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
I have set three and two fingers click for in global, but many times it works only in chrome. In Finder for example doesn't react for three and two fingers click. When I restart BTT it works for some minutes. 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
MacBook Trackpad

#### Device information:

Type of Mac: Macbook Pro 2016
macOS version: 10.12.3
BetterTouchTool version: 2.071

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
I have set three and two fingers click for in global, but many times it works only in chrome. In Finder for example doesn't react for three and two fingers click. When I restart BTT it works for some minutes. 

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by cygvis** [comment]
do you still have this issue after updating BTT?

if yes, can you please click 'Print current setup' on the bottom right of the gestures menu & attach here?

**Comment by Yakovlev13** [comment]
Hi,

Three click is still very unreliable even in current version

S pozdravom
Best regards

Adam Weinzettl
---
Student Government at FEI, Slovak university of technology in Bratislava

2017-07-11 20:06 GMT+02:00 cygvis <notifications@github.com>:
