### ISSUE TITLE
[Feature request] Advanced window management across displays

### ISSUE THREAD

**Issue by jkbbnk** [folivoraAI/BetterTouchTool#630]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
I often switch between external display attached with laptop in clamshell mode in work and native display while traveling. Although macOS provides some management it could be very cool if BTT could remember and reset position and size of each window separately in respect to which display I use.
For example, I resize browser to 70% width, snapped to the left, with text-editor/terminal/chat at 30% snapped to the left while I'm on external monitor, but when I detach ext monitor and open the lid to continue on my way, I would like to have browser at full width and smaller apps at 40%. By default, macOS downsizes only dimensions which outreach displays resolution. It's even less convenient when I go from internal display to external...

#### Device information:

Type of Mac: 13" retina
macOS version: 10.12.4 (beta)
BetterTouchTool version: 2.071

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by derekawalker** [comment]
I'd love this feature too. I've been using [Moom](https://manytricks.com/moom/) for this (see "Save Your Window Layouts" section), but I'd much rather only use one application for window management.
