### ISSUE TITLE
[Feature request] Add a Touch Bar "Release" Action

### ISSUE THREAD

**Issue by SanDooo** [folivoraAI/BetterTouchTool#634]
#### Description of bug/feature request/question:

I'd like to perform an action as long as I'm touching a Touch Bar custom icon (would be useful with Photoshop for instance).
For example, a custom TouchBar like :
 - Shift -> Shift Key Down
        \-----> "Touch Bar Related Action" Release
        \-----> Shift Key Up

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Touch Bar

#### Device information:

Type of Mac: MacBook Pro (15 pouces, mi-2010)
macOS version: 10.12.3
BetterTouchTool version: 2.071

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

Yep it's a 2010 MBP, I'm using the Touch Bar available with Duet Display (which basically moves the Touch Bar to an external touch screen). ;)

**Comment by fifafu** [comment]
Yep I'll add this!
