### ISSUE TITLE
Is it possible to move / resize a window from the keyboard?

### ISSUE THREAD

**Issue by chmac** [folivoraAI/BetterTouchTool#635]
#### Description of bug/feature request/question:

With VoiceOver it's possible to create a shortcut key that allows me to move a window left with the keyboard. Is there some similar option in BTT?

For example, I imagine a keyboard sequence that starts the mode, and then the arrow keys would push the window left / right / up / down. Likewise for resizing.

I've tried mapping a few keyboard shortcuts to the action "Start/Stop Moving" and "Start/Stop Resizing" but I can't figure out what those actions actually do. It seems like maybe they let me move / resize a window by moving the mouse, but they don't seem to work with the arrow keys.

**Comment by cleverjackal** [comment]
Check [this](http://stackoverflow.com/questions/2777927/window-bounds-set-on-window-using-applescript-in-os-x-are-being-ignored) out

**Comment by chmac** [comment]
Hmm. I really want to be able to push windows around. I prefer to have all my windows slightly overlapping so I can see what's open rather than maximise to sections of the screen (which you can do with BTT).

Does that mean it's not possible with BTT?

**Comment by cleverjackal** [comment]
Unfortunately I don't think this is possible at the current moment in BTT

**Comment by fifafu** [comment]
No it's currently not possible. However I like the idea. Let's see if I can add it with an upcoming version.

**Comment by caseros** [comment]
+1, Moving/resizing similar to the "moving/resizing with mouse" advanced option, would be great :)

**Comment by fifafu** [comment]
This is finally possible in v2.462 alpha using the new "Custom Move&Resize" action:

![image](https://user-images.githubusercontent.com/8820811/39382366-82cb8ace-4a65-11e8-9808-e1e44739ad77.png)
