### ISSUE TITLE
Ability to enable/disable trackpad gestures

### ISSUE THREAD

**Issue by cleverjackal** [folivoraAI/BetterTouchTool#642]
#### Description of bug/feature request/question:

This would be nice to have, but it's not urgently needed

**Priority:** 2

**Comment by cleverjackal** [comment]
I literally have no idea what I meant when I wrote this

**Comment by cleverjackal** [comment]
Ah! Silly me. Just like you can enable/disable individual keyboard shortcuts, I think it'd be nice to enable/disable individual trackpad gestures. Priority: low I guess

**Comment by istrasci** [comment]
+1  I'd like to be able to disable gestures without having to delete them completely.

**Comment by cleverjackal** [comment]
Oh yeah, now I remember. It would be nice to have.
