### ISSUE TITLE
Date Widget - Display in UTC or alternative time zone

### ISSUE THREAD

**Issue by virtzilla** [folivoraAI/BetterTouchTool#648]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

In the Touchbar Date Widget there seems to be no means to specify an alternate time zone setting to display. If there is from the date patterns, it's unclear to me ;-)  Would like to be able to display an alternate time zone in the contents of this widget (specifically GMT/UTC at this time).

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

TouchBar

#### Device information:

Type of Mac:
macOS version: 
BetterTouchTool version: 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
You can use any date format that's supported by Apple, see this link for the format to use:
http://www.unicode.org/reports/tr35/tr35-31/tr35-dates.html#Date_Format_Patterns

**Comment by fifafu** [comment]
Ah wait, you want to show a different time than your system clock shows? That's currently not supported.

**Comment by virtzilla** [comment]
Indeed - I'd like to be able to show different timezones/offset from GMT. Already love the patterns!

**Comment by FearNaBoinne** [comment]
I'd love to be able to set timezones on the widget too! That way I can have local time and home time on my touchbar...

**Comment by hholcombe** [comment]
+1

**Comment by sillyfrog** [comment]
That would be great

**Comment by spieglio** [comment]
I just fixed it myself with a little bit of a python widget that updates every 20 seconds. Probably not the cleanest code though 🙈, Python is not my language.

```
#!/usr/bin/python
# -*- coding: utf-8 -*-

# Install Pendulum:
# pip install pendulum
import pendulum
from datetime import datetime

# timezone0 = 'Asia/Kuala_Lumpur';
label0 = 'Local';
timeFormatted0 = pendulum.now().strftime("%a %d | %H:%M");

timezone1 = 'America/Chicago';
label1 = 'CST';
timeFormatted1 = pendulum.now(timezone1).strftime("%H:%M");

timezone2 = 'America/New_York';
label2 = 'EST';
timeFormatted2 = pendulum.now(timezone2).strftime("%H:%M");

timezone3 = 'Europe/Berlin';
label3 = 'Berlin';
timeFormatted3 = pendulum.now(timezone3).strftime("%H:%M");


print(timeFormatted0 + " | " +
  label1 + " " +
    timeFormatted1 + " | " +
  label2 + " " +
    timeFormatted2 + " | " +
  label3 + " " +
    timeFormatted3);
```

**Comment by osdiab** [comment]
I would also like to see this!

**Comment by osdiab** [comment]
I achieved it with a shell script widget:

```
echo "TYO: `TZ='Asia/Tokyo' date '+%a %H:%M'`"
```

and another example:

```
echo "ATH: `TZ='Europe/Athens' date '+%a %b %d %H:%M'`"
```

Search for "Interpreted sequences" in [the date man page](https://ss64.com/bash/date.html) to see what `%` sequences you should use.

Also, beware that if you type quote characters in the shell script text box in the BetterTouchTool app, it doesn't use correct apostrophes and quotation marks (it does the angled ones that are used in normal text), which will cause your script to not work properly; I recommend copy pasting from the terminal.

**Comment by Norandy** [comment]
Hi ! Thanks for the shell script widget. Unfortunately I couldn't find the way to change the location. For example, I tried to get the Boston time but I've got an error... I tried BOS, America/Boston but nothing works... Any help on who did you find the exact syntax ?

**Comment by fifafu** [comment]
That should be US/Eastern
(City => TZ mapping can be found in System/Library/PreferencePanes/DateAndTime.prefPane/Contents/Resources/TimeZone.prefPane/Contents/Resources/all_cities_adj.plist )

**Comment by fifafu** [comment]
Here a full example that can be copied and pasted into BTT:

```
{
  "BTTWidgetName" : "Date TZ",
  "BTTTriggerType" : 642,
  "BTTTriggerTypeDescription" : "Shell Script \/ Task Widget",
  "BTTTriggerClass" : "BTTTriggerTypeTouchBar",
  "BTTPredefinedActionType" : -1,
  "BTTPredefinedActionName" : "No Action",
  "BTTShellScriptWidgetGestureConfig" : "\/bin\/bash:::-c",
  "BTTAdditionalConfiguration" : "\/bin\/bash:::-c",
  "BTTEnabled" : 1,
  "BTTOrder" : 2,
  "BTTTriggerConfig" : {
    "BTTTouchBarItemIconHeight" : 22,
    "BTTTouchBarItemIconWidth" : 22,
    "BTTTouchBarItemPadding" : 0,
    "BTTTouchBarFreeSpaceAfterButton" : "5.000000",
    "BTTTouchBarButtonColor" : "75.323769, 75.323769, 75.323769, 255.000000",
    "BTTTouchBarAlwaysShowButton" : "0",
    "BTTTouchBarAppleScriptString" : "#example:\necho \"Boston: `TZ=' US\/Eastern' date '+%a %b %d %I:%M %p'`\"\n",
    "BTTTouchBarAlternateBackgroundColor" : "128.829533, 128.829533, 128.829533, 255.000000",
    "BTTTouchBarScriptUpdateInterval" : 1
  }
}
```

**Comment by Norandy** [comment]
Thank you @fifafu Copying this shell script works but the time is wrong :/ The time displayed is 07:58 and it should be 03:58.

**Comment by fifafu** [comment]
Uh sorry, accidentally got a space character in there.
This should work:
```
{
  "BTTWidgetName" : "Date TZ",
  "BTTTriggerType" : 642,
  "BTTTriggerTypeDescription" : "Shell Script \/ Task Widget",
  "BTTTriggerClass" : "BTTTriggerTypeTouchBar",
  "BTTPredefinedActionType" : -1,
  "BTTPredefinedActionName" : "No Action",
  "BTTShellScriptWidgetGestureConfig" : "\/bin\/bash:::-c",
  "BTTAdditionalConfiguration" : "\/bin\/bash:::-c",
  "BTTEnabled" : 1,
  "BTTOrder" : 2,
  "BTTTriggerConfig" : {
    "BTTTouchBarItemIconHeight" : 22,
    "BTTTouchBarItemIconWidth" : 22,
    "BTTTouchBarItemPadding" : 0,
    "BTTTouchBarFreeSpaceAfterButton" : "5.000000",
    "BTTTouchBarButtonColor" : "75.323769, 75.323769, 75.323769, 255.000000",
    "BTTTouchBarAlwaysShowButton" : "0",
    "BTTTouchBarAppleScriptString" : "#example:\necho \"Boston: `TZ='US\/Eastern' date '+%a %b %d %H:%M %p'`\"\n",
    "BTTTouchBarAlternateBackgroundColor" : "128.829533, 128.829533, 128.829533, 255.000000",
    "BTTTouchBarScriptUpdateInterval" : 1
  }
}
```
