### ISSUE TITLE
Mirroring Trackpad doesn't mirror "Right/Left Finger Harder" gestures

### ISSUE THREAD

**Issue by skovorodkin** [folivoraAI/BetterTouchTool#652]
#### Description of bug/feature request/question:

After enabling "Mirror complete Magic Trackpad orientation for upside-down usage" option, 3 Finger Click (Right/Left Finger Harder) gestures continue to work in "normal" orientation: when you press right finger harder, BTT fires an action for Left Finger Harder, and vice versa.

Other similar gestures may be affected as well, but I haven't tested anything else.

#### Affected input device:

Magic Trackpad 2

#### Device information:

macOS version: 10.12.3
BetterTouchTool version: 2.08

**Comment by stormbeta** [comment]
This also appears to affect two-finger force clicks for Left/Right finger harder.

It seems to be more than just reversed; I found that it gets "stuck" going one direction or the other. That doesn't happen if using the normal orientation.

Magic Trackpad 2

macOS version: 10.12.6
BetterTouchTool version: 2.297
