### ISSUE TITLE
Right-Click Area Customization

### ISSUE THREAD

**Issue by Nonsanity** [folivoraAI/BetterTouchTool#656]
I want to be able to expand the trackpad's right click zone to be half the width of the trackpad, so that my thumb can reach both clicks with minimal movement away from the middle.

By deafult, the Macbook Pro 2016 force-touch trackpad has a right click area ("click bottom right corner" mode) that takes about 25% of the width of the trackpad. This can be replaced with BTT's version which uses an even smaller area of about 10%. I'm used to older Macbook trackpads that were smaller and used a 50% area for their right click. (Or bonus, a customizable percentage.)

(This change to where the right-clicks are detected affects me everywhere, but particularly in games where left and right clicks are used with equal frequency.)

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Macbook Pro (late-2016) force touch trackpad

#### Device information:
Type of Mac: MacBook Pro (15-inch, 2016)
macOS version: 10.12.3 (16D32)
BetterTouchTool version: 2.08 (610)

**Comment by cleverjackal** [comment]
How about using a two-finger tab for a right click? Sounds easier to use, in my opinion.

**Comment by TechGizmo** [comment]
I would like to see future releases incorporating areas from the corner clicks as well! The area provided by BTT is too small in my opinion.

**Comment by sparr** [comment]
Adding support for enlarging the corner click area. The 2017 MBPs have ridiculously large trackpads. I miss the corner more often than I hit it.

**Comment by aequasi** [comment]
Has anyone found any other way of doing this?

**Comment by Nonsanity** [comment]
I bought a mouse. :P

**Comment by aequasi** [comment]
Was this resolved @fifafu ?

**Comment by fifafu** [comment]
The BTT issue tracker has moved to https://community.folivora.ai early this year and all issues here have been auto-closed now. In case you still need help with this issue / feature / question please create a new post there.
