### ISSUE TITLE
Allow Touch Bar buttons to have squared corners.

### ISSUE THREAD

**Issue by chuckharmston** [folivoraAI/BetterTouchTool#662]
#### Description of bug/feature request/question:

It'd be great if we could square corners of Touch Bar buttons, or otherwise conjoin them. That would allow buttons to look like the macOS Control Strip.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Touch Bar

#### Device information:

Type of Mac: Macbook Pro with Touch Bar
macOS version: 10.12.3
BetterTouchTool version: 2.08

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

![51112152008__cbef1db4-1e0d-440a-8919-6ff3f0cdd700 jpg](https://cloud.githubusercontent.com/assets/23885/23868781/be7ff736-07ee-11e7-8a1e-35340767d4ea.jpeg)

An example of where conjoined buttons would be an improvement.

**Comment by cleverjackal** [comment]
Protip: use ⇧⌘6 to take a screenshot of the Touch Bar

**Comment by chuckharmston** [comment]
@cleverjackal Good tip, thanks!

In this case, I found that the context of the added vertical spacing important to communicate what I was looking for; much of it gets clipped out in the screenshot.

**Comment by cleverjackal** [comment]
Oh right yeah, I see :)

**Comment by fifafu** [comment]
I'll add more styling options soon!

**Comment by gdelmas** [comment]
great & +1. just found this before posting the same request.

this will allow us to recreate a the control strip in btt.

ps: i found the control strip icon assets in `/System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/Assets.car`. but i can not find the volume icon. does one of you know where this asset might be located?

**Comment by medic89** [comment]
@fifafu 

Has this function already been implemented into BTT? Will it be possible to have buttons with lets say two rounded corners and two squared ones like the buttons on the edge of the control strip of Mac OS?
