### ISSUE TITLE
[Feature Request] Middle Mouse Button (MMB) click and hold.

### ISSUE THREAD

**Issue by chris-lesage** [folivoraAI/BetterTouchTool#670]
Feature request: The ability to hold down a MMB click.

I currently have 3-finger click to register as MMB click. I  also have a Touchbar button to register a MMB click. However, this seems to only register as a single click event. It would be great to be able to **hold** the MMB click down. This would be useful (and necessary) in some 3D applications, where MMB dragging is necessary for basic 3D navigation.

In SideFX Houdini, MMB is essential for changing parameters, and for displaying an information box on your current objects.
In Autodesk Maya, MMB is essential for changing parameter values and navigating the camera.

In sculpting software such as 3D-Coat, MMB dragging can be configured to change brush size, or navigate the viewport.

**Comment by cleverjackal** [comment]
That's a cool idea.

While we're at it, I think it would be nice to have a way to click and hold the mouse with the keyboard. Current it's only possible to assign a click gesture, to, let's say the letter C. I wouldn't be able to hold down C and drag something over to another place and then release C to release the mouse click. I think this would be really nice to have!

**Comment by chris-lesage** [comment]
Agreed! Controlling the mouse via keyboard would be fantastic for usability cases.

This is something that is currently possible to set up with Hammerspoon and Karabiner-Elements. (but a bit tricky and buggy because it requires scripting with Lua.) For example, Karabiner-Elements can distinguish the Right-CMD as a custom hotkey (I chose the fictional key, 'F18') and then Hammerspoon can trigger a MMB click while 'F18' is held.

**Comment by cleverjackal** [comment]
Oh wow! That's cool. I hadn't heard of that. I need to check it out. Thanks for the tip!

**Comment by fifafu** [comment]
Currently that is only possible for three finger clicks in BTT and it's quite hidden.
However adding separate mouse up/down actions should be quite easy (they wouldn't work well with trackpad gestures but for keyboard shortcuts, normal mouse presses and touchbar buttons they could be quite useful)
![Uploading image.png…]()

**Comment by TheCGCy** [comment]
Oh yes, I second that. It really bugs me when I realize I cant perform middle hold with Logitech mouse in Maya without installing their official driver. The only thing BTT missing here are just one simple middle click behaviour. I'm looking forward for this enhancement!

**Comment by chris-lesage** [comment]
Thanks for the suggestion fifafu, but this option is not working in Autodesk Maya or SideFX Houdini. I've checked the CAD option box you suggested. My trackpad gesture is 3-clicks. My assigned action is Middle Click.

I've also tried various combinations of Force Click enabled/disabled in both Macos and BTT preferences, in case the multiple levels of force were interfering with the release 2 fingers and drag. Because with Force Click, when you release 2 of your fingers, the force click releases a level.

I'm still unable to hold or drag MMB. A single middle click is still working just fine.

**Comment by 01msmr** [comment]
@fifafu 
I couldn´t get this working (Keyshot 7 has an option to switch between pan/rotate, so it´s not _that_ important).

But it would be nice to use it more intuitively, though …

**Comment by ahainen** [comment]
Yeah, that CAD feature/middle click doesnt work with Modo either. :(

**Comment by perkinsb1024** [comment]
Unfortunately, the CAD mode option doesn't work for me either. I've enabled the option and created a global gesture for "three finger click" that's mapped to the predefined action "middle click", but it doesn't work in EAGLE. Using a MacBook Pro with a force trackpad, in case that matters, MacOS 10.13.3
