### ISSUE TITLE
Bug/Feature Request: TipSwipe Gesture Sensitivity

### ISSUE THREAD

**Issue by kamykaze** [folivoraAI/BetterTouchTool#674]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

Ever since I got a new Macbook Pro (2016 with touch bar), I have a hard triggering the TipSwipe Left/Right/Up/Down gestures. It seems that I have to be very precise in order to trigger them.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Macbook Pro built-in trackpad with force touch support

#### Device information:

Type of Mac: MacBook Pro (15-inch, 2016)
macOS version: 10.12.3 Sierra
BetterTouchTool version: 2.071 (608)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

I'm not sure if this issue is due to the Force touch support on these trackpads, or just because these trackpads are HUGE, so the gestures need to be bigger. I've used the tipswipe gestures for years before on both a Macbook Air 11-in and in a Wacom Bamboo tablet. 

I noticed that if I swipe fast and far enough, the gesture still triggers, but it feels like a real stretch of my fingers.

If this is indeed due to the size of the trackpad, does BTT use a percentage of the trackpad size to calculate swipes? Instead of say "pixels" or physical distance? 

I don't mind having to adjust the sensitivity of the gestures, but I don't see anything available for tipswipes.
---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by tarvos21** [comment]
Yes, I also have the same problem, I use Tipswipe left finger up/down to go to top and bottom of the page in Safari, but it's not so sensitive to finger movements.

**Comment by fifafu** [comment]
I'll add a slider to change the sensitivity!
