### ISSUE TITLE
When Force Touch on Corner on, touching the corner will disable mouse left click

### ISSUE THREAD

**Issue by aahung** [folivoraAI/BetterTouchTool#679]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

When I turn on top left corner force click gesture, if I am using the mouse at the same time, weird thing happen: touching (not force clicking) the left top corner, the mouse left click will be disabled.
When I turn off that particular gesture, mouse click normal.  

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Trackpad -> Normal mouse (I tested 2 Logitech Bluetooths)

#### Device information:

Type of Mac: MacBook Pro 2016 13-inch w/ Touch Bar
macOS version: 10.12.3
BetterTouchTool version: 2.071 (608)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
This is quite complicated as BTT doesn't now which device triggered a click. Thus BTT needs to block clicks while the corner area is touched (when using corner clicks).

However for Force Touch Trackpads I could require a certain pressure before blocking a click. I'll look into that.
