### ISSUE TITLE
Please add action: Switch to a specific input source

### ISSUE THREAD

**Issue by technolingo** [folivoraAI/BetterTouchTool#680]
#### Description of bug/feature request/question:

I use multiple input sources on my Mac, I would like to set up specific hotkeys for each input source/method.

**Comment by cleverjackal** [comment]
You mean languages? I think you might be able to change that with an AppleScript

**Comment by evilplanet** [comment]
So is true with everything else BetterTouch Tool does, but I bought this app to make my life easier. It would be nice to have a designated hotkey or gesture for each language input method.

**Comment by cleverjackal** [comment]
Yeah, but you can BTT to invoke an AppleScript that changes the language input

**Comment by evilplanet** [comment]
Yeah, you are right. Problem solved using Applescript. I've just discovered a simple and powerful tool.

**Comment by cleverjackal** [comment]
All right great to hear that

**Comment by fifafu** [comment]
Would be great if you could post the Apple Script you are using for future reference!

**Comment by cleverjackal** [comment]
@fifafu perhaps it's [this](http://macscripter.net/viewtopic.php?id=31043) or [this](http://stackoverflow.com/a/23741934). I haven't tried those, though.

**Comment by evilplanet** [comment]
@fifafu Great idea! This is my first time using posting on this site, still adapting to the culture.

Below is the code I used:

on changekeyboardlayout(layoutName)
	tell application "System Events" to tell process "SystemUIServer"
		tell (1st menu bar item of menu bar 1 whose description is "text input") to {click, click (menu 1's menu item layoutName)}
	end tell
end changekeyboardlayout

changekeyboardlayout("British")

------------(code finished)-----
Note that keyboard layout names are localised, so if your system's language isn't English, then you should use the appeared layout names in the system's language, e.g. "美式英文", "Español".

**Comment by idoo** [comment]
Mac has default widget for such action, but I can't use it when I overwrite default panel layout, so it would be nice to have such in `BetterTouchTool`

I created better solution for change layout

```
tell application "System Events"
  key code 49 using {command down} -- shift-command-left
end tell
```
But still didn't find a option to get current input source name

**Comment by idoo** [comment]
as I understand there is no easy way to get current input source from console

I'm not sure, can you reuse standard widget from sierra, because it works nice

@fifafu so, it would be awesome to give some ability to create fully custom touchbar for non english native speakers ;) Please let me know if I can help you with implementation or testing.

**Comment by idoo** [comment]
@fifafu how much we have to donate for such feature?)

**Comment by cleverjackal** [comment]
@idoo What actually are you asking for? I'm not too sure tbh

**Comment by idoo** [comment]
@cleverjackal I mean that would be nice to add widget to that group http://take.ms/kFsr7 to indicate current input source language and switch it by tapping

**Comment by cleverjackal** [comment]
Ah, I see. Nice!

**Comment by idoo** [comment]
@cleverjackal please let me know if I can help you somehow

**Comment by cleverjackal** [comment]
@idoo Oh thanks, but I wasn't looking for it. Maybe @fifafu wants it

**Comment by xaralis** [comment]
@idoo For the record, it can be easily achived using this small bin: https://github.com/myshov/xkbswitch-macosx

You can then use this shell script with Better Touch Tool and embed it in a nice button, even with icons.

<img width="1134" alt="screenshot 2018-04-05 22 59 26" src="https://user-images.githubusercontent.com/441739/38391642-1eef4d20-3925-11e8-950d-d85270313002.png">
