### ISSUE TITLE
Detect which hand is on the Trackpad (mainly for the left-handed)?

### ISSUE THREAD

**Issue by tarvos21** [folivoraAI/BetterTouchTool#686]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

I have tried to set TipTap left finger/middle(2 finger fix) in Safari, to switch to left tab and right tab, it works great with my right hand's index finger and middle finger, but if I tried to use these gestures with my left hand(actually I am half left-handed), I have to use my ring finger and middle finger to do the same thing, which I found not so convenient. The same thing happens when I set Tipswipe left finger up/down to got to top and bottom of the page, with my right hand, I can use index finger as the left finger, but with my left hand, I have to use ring finger, which could be quite unnatural.

I know this may be a vain hope, that BetterTouchTool could detect which hand is used on the Trackpad automatically, thus the user can use left-hand or right-hand freely with the same gesture, symmetrically.

I don't know if I have expressed my idea clearly, thanks for reading!

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

MacBook Trackpad

#### Device information:

Type of Mac: MacBook Pro 2015 mid
macOS version: macOS Sierra 10.12.3
BetterTouchTool version: 2.08

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
This issue was moved to https://community.folivora.ai/t/detect-which-hand-is-on-the-trackpad-mainly-for-the-left-handed/64

**Comment by fifafu** [comment]
Sorry, please ignore the previous message. The migration didn't work correctly, for now the issues will stay here.
