### ISSUE TITLE
Disable keyboard shortcuts but allow window snapping for specific apps

### ISSUE THREAD

**Issue by zmorrissey** [folivoraAI/BetterTouchTool#687]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
I have a list of global keyboard shortcuts that I use for almost every app. However, for certain apps that use a lot of internal keyboard commands that conflict with my global keyboard shortcuts (e.g. Emacs), it would be useful to have an app specific option to disable keyboard shortcuts but still maintain window snapping and/or mouse commands. However, the current relevant app specific options only allow you to either disable BTT completely or only disable window snapping. Essentially, it'd be the opposite feature of "disable window snapping" and instead be "disable keyboard shortcuts". 

 Is there a current setting that could accomplish this, or would it be possible to implement this feature? 

Thank you. Great work on BTT.

#### Device information:

Type of Mac: MacBook Pro
macOS version: OS X El Capitan 10.11.3
BetterTouchTool version: 2.071

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

Relevant menu information:
![btt app specific menu](https://cloud.githubusercontent.com/assets/11972950/24083166/8459c45e-0ca0-11e7-9b23-60d3bdca605b.png)

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
I'll check if I can add this option.
For now you can add the same shortcuts to emacs and assign the "Use apple default or do nothing" action (I know this is quite tedious).

**Comment by orentrutner** [comment]
Oh yes please! App is Blender. I have dozens of global customizations, definitely tedious. Thanks!
