### ISSUE TITLE
Switching presets automatically / with script / without gestures

### ISSUE THREAD

**Issue by ffittschen** [folivoraAI/BetterTouchTool#691]
#### Description of feature request/question:
Hi, I'm often working at different locations with different input devices and would like to change my preset automatically (e.g. via a script, or via control plane). Currently the only trigger that I think could achieve this is the "Received Distributed Notification With Name" trigger, but I can't find any description of it in the docs. Can I send these distributed notifications with a script or do I need to use the DistributedNotificationCenter, i.e. use a compiled app to send the notifications?

Or is there any other possibility to change the presets based on non-gesture triggers? A great option to achieve such behaviour would be X-Callback-URLs.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
None / Other

#### Device information:

Type of Mac: MacBook Pro
macOS version: 10.12.3
BetterTouchTool version: 2.071

**Comment by fifafu** [comment]
Good point.

I'll add two new triggers to the Other Triggers:

- Execute Action If Apple Script returns true (with option to periodically run any Apple Script)
- Execute Action if BTT was called from Apple Script (e.g. something like "tell application BetterTouchTool trigger customNameOfTheTrigger")

Currently BTT supports a custom URL Scheme for Trackpad gestures (this is very hidden, you can right-click a trackpad gesture and select "Copy Link To Trigger this Gesture"). Then it'll give you a link like btt://170 which you could call from Apple Script like 
```AppleScript
tell application "BetterTouchTool"
	open location "btt://170"
end tell
```

**Comment by sydneycbd** [comment]
This is awesome! Is there a url scheme that might allow toggling a command on/off or switching a command with the same touchpad gesture?

**Comment by fifafu** [comment]
Closing here.
Scripting has been improved a lot in recent versions, see https://docs.bettertouchtool.net/docs/scripting_btt.html
