### ISSUE TITLE
Compose settings / presets

### ISSUE THREAD

**Issue by ffittschen** [folivoraAI/BetterTouchTool#692]
#### Description of feature request/question:
Hi, is it possible to compose settings? The use case would be to only have different settings for the _Normal Mice_ input device, but everything else should be active in both presets.

##### Composition
A matrix with applications in the first row and input devices in the first column would show the active preset per application/input device in he cells. When I'm at Home and **MouseA** and **KeyboardA** are connected, the matrix would look like this:

|   |Trackpads|Keyboards|Normal Mice|Other|
|--|----------|-----------|------------|------|
|Global|Default|**Home**|**Home**|Default|
|...|Default|**Home**|**Home**|Default|

When I'm at Work and **MouseB** and **TrackpadA** is connected:

|   |Trackpads|Keyboards|Normal Mice|Other|
|--|----------|-----------|------------|------|
|Global|**Work**|Default|**Work**|Default|
|...|**Work**|Default|**Work**|Default|

##### Alternative: differentiate between input devices
If we have a differentiation between different instances of input devices (like **MouseA** and **MouseB** from the example above), we could have different settings for these input devices _in the same preset_. 

|   |Trackpads|Keyboards|Normal Mice|Other|
|--|----------|-----------|------------|------|
|Global|Default|**Default (KeyboardA)**|**Default (MouseA)**|Default|
|...|Default|**Default (KeyboardA)**|**Default (MouseA)**|Default|

##### Alternative: inheritance
Another alternative would be to have a _base preset_ and different _child presets_ that inherit all settings from their parent, but can override some settings.

|   |Trackpads|Keyboards|Normal Mice|Other|
|--|----------|-----------|------------|------|
|Global|**Default/Home**|**Default/Home**|**Default/Home**|**Default/Home**|
|...|**Default/Home**|**Default/Home**|**Default/Home**|**Default/Home**|

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
All

#### Device information:

Type of Mac: MacBook Pro
macOS version: 10.12.3
BetterTouchTool version: 2.071

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
Current workaround:
* Create all presets and configure the default preset
* Copy all settings that should be active in other presets to the other presets
* When changing one setting, search for this setting in all presets and change it everywhere

**Comment by fifafu** [comment]
Unfortunately something like this is not possible using the current preset structure of BTT.
I'm however working on a new structure and will keep this request in mind.
