### ISSUE TITLE
App-Specific Gestures Occur in Multiple Apps (old and new iWork versions)

### ISSUE THREAD

**Issue by aleminopuy** [folivoraAI/BetterTouchTool#696]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
I have both Pages 09 (v4.3) and the current version (6.0.5) installed. I installed BTT to try and get Pages '09 to use pinch-to-zoom. I set up trackpad pinch to map to the zoom in and out keyboard shortcuts. It's not a smooth zoom like newer apps (goes in zoom "chunks", but I didn't expect it to be.

The issue is this: the BTT "shortcut" occurs in both versions of Pages, eliminating the standard nice smooth zooming that happens in the new Pages and replacing it with the "chunky" zoom. This is probably because both have the same bundle ID (which is why the old version doesn't show up in Launchpad). Is there any way to get it to work so I can target ONLY the old version of Pages?

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
MacBook Trackpad

#### Device information:

Type of Mac: 13" MacBook Pro with Touch Bar (2016)
macOS version: 10.12.3
BetterTouchTool version: 2.08

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
Workaround: for now, I've changed it so BTT looks for pinch/spread with thumb and two fingers. I'd like to find a way so I don't need to use a different gesture, but that's working *chunky zoom in 09, leaves regular pinch zoom alone in new pages) for now.

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by cleverjackal** [comment]
> It's not a smooth zoom like newer apps (goes in zoom "chunks", but I didn't expect it to be.

Yeah I think this has to do with how old pages worked, right?

But anyway, I think that more granular controlling of what applications it works in would be really cool. Maybe something to do with application titles? Idk.

**Comment by aleminopuy** [comment]
>>It's not a smooth zoom like newer apps (goes in zoom "chunks", but I didn't expect it to be.
>
>Yeah I think this has to do with how old pages worked, right?

Exactly. Zoom only happened in steps in this old version. I have no illusions about getting a smooth zoom experience from BTT, just a gesture shortcut for those zoom steps. The issue is I'd like to have it be the standard pinch/pull to zoom without overwriting the gesture for the new/current version of Pages.
