### ISSUE TITLE
How to stop BST activating when highlighting in iBooks?

### ISSUE THREAD

**Issue by woundedbreakfast** [folivoraAI/BetterTouchTool#700]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

I want to be able to snap the iBooks window when I'm taking notes but when I'm just reading and highlighting, I don't want BTS to activate because then the window will drag to a snap area and resize when I just meant to highlight.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

MacBook trackpad

#### Device information:

Type of Mac: Retina Macbook 2016
macOS version: 10.12.4
BetterTouchTool version: 1.7

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Thanks for reporting! I'll fix this.
