### ISSUE TITLE
scrollup event handler never triggers

### ISSUE THREAD

**Issue by AttilaForgacs** [folivoraAI/BetterTouchTool#704]
#### Description of bug/feature request/question:

Normal mouse ScrollIUp or ScrollDown with or without any modifiers 
are never triggered.

https://www.dropbox.com/s/cfsus7q23i84wmo/Screenshot%202017-03-22%2014.35.02.png?dl=0

So how can you run an action if lets say you command+scroll up

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Normal logitech mouses

#### Device information:

Type of Mac: 2015 early MBP
macOS version: sierra 10.12.3
BetterTouchTool version: 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

Nothing happens

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Hey,

which version of BTT are you running?

Best,
Andreas

**Comment by samuel-ye** [comment]
same here with latest BTT version 2.20
