### ISSUE TITLE
Window switching Touch Bar button

### ISSUE THREAD

**Issue by jomeyl** [folivoraAI/BetterTouchTool#706]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

I just received my Touch Bar MBP, and have been playing with BTT and the Touch Bar ever since. However, there is one thing I can’t seem to have to work : I wanted to create a button which would switch windows, reproducing the cmd+shift+^ shortcut on my Swiss keyboard. I saved it like that in BTT, but when I click that button in Safari for example, the windows don’t switch (the sign « ^ » actually even shows up in a text field). However, if I press the shortcut on the keyboard, it works fine… therefore, I guess BTT is not reproducing the shortcut correctly, maybe? Do you have any idea about what the problem could be?

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

MacBook Pro Touch Bar

#### Device information:

Type of Mac: MBP 15"
macOS version: 10.12.2
BetterTouchTool version: 2.08

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Mhm, this should work. Are you sure you have set it up like in this screenshot:

**Comment by jomeyl** [comment]
<img width="1127" alt="capture d ecran 2017-03-24 a 19 17 29" src="https://cloud.githubusercontent.com/assets/26604784/24307998/8ef616ea-10c6-11e7-8351-2fe24a801433.png">

Exactly like that I guess, am I wrong? If not, is there any thing else that could be causing that behavior? BTT is the only "input modifier" that I use...
