### ISSUE TITLE
TouchBar customisations stop displaying when touchbar 'hardware' disappears using Duet Display

### ISSUE THREAD

**Issue by admackin** [folivoraAI/BetterTouchTool#708]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

I am using [Duet](https://www.duetdisplay.com/) to use my iPad as a  second display and get a Touchbar on it. It mostly works great (everyone should do this! it's useful even if you have a new MBP but are using an external keyboard), but I find that if I disconnect my iPad, after a time, and then reconnect it, BTT 'forgets' that there is a TouchBar (fair enough! the touchbar "hardware" went away) and stops customising it (ie the BTT controls don't appear). The workaround is to go into general touchbar settings and unselect then reselect 'show BTT icon in control strip'.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

TouchBar (virtual, on iPad)

#### Device information:

Type of Mac: MacBookPro11,5
macOS version: 10.12.3
BetterTouchTool version: 2.071

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Hey,

I'm not yet sure if this can be fixed but I'll look into it!

Best,
Andreas

**Comment by admackin** [comment]
in fact, I have realised there is a simple workaround – using a BTT gesture to show/hide the BTT touchbar controls fixes everything (and the touchbar button to toggle BTT touchbar items reappears as well).

So, the only bug is that the BTT button on the touchbar disappears under certain, probably obscure conditions (I don't know if this happens on the hardware touchbar as well), which is not that big a deal.
