### ISSUE TITLE
[Semi-serious bug] "Delay" in all gestures in certain apps with BTT

### ISSUE THREAD

**Issue by cleverjackal** [folivoraAI/BetterTouchTool#718]
#### Description of bug/feature request/question:

I don't even know how to describe this. I've been experiencing it for weeks, ever since I got BTT. Essentially, here's what happens:

1. I assign a 3 finger tip tap left gesture (2 finger fix) to go back in the Finder, or in other words ⌘[

2. I use the gesture in the Finder. 

3. Actions in the Finder start acting weird. Whenever I click on something (click #1), nothing seems to happen. However, when I click somewhere else (click #2), click #1 is registered. Then, when I click yet again somewhere else (click #3), click #2 is registered and so on.

I have not been able to consistently reproduce this. All I know is that using it in the Finder with these tip tap gestures causes it to happen eventually. 

I also just experienced this when using the swipe back gesture in system preferences, so it doesn't seem like it's to do specifically with the Finder. I also couldn't scroll in a scroll view in system preferences when this happens.

I'm calling this a "semi-serious" bug because it's pretty bad for UX when new users use BTT, IMO, as it makes BTT seem kind of buggy.

#### Device information:

Type of Mac: MBP
macOS version: Sierra 10.12.3
BetterTouchTool version: 614

**Comment by fifafu** [comment]
Sounds like the mouse up event is not send correctly in some cases.
Are you running other mouse/keyboard related software besides BTT?

**Comment by cleverjackal** [comment]
Hmm... the only other thing I'm running is the Karabiner Elements beta. However, it shouldn't be interfering with the trackpad, but who knows. I'll try to disable it and see if this issue continues occurring.

**Comment by fifafu** [comment]
That'd be interesting! Karabiner Elements is probably using the same Event APIs BTT uses and in previous versions of macOS it has often caused problems when two apps where trying to work with that API.
This has gotten better with Sierra, but maybe there are still some situations where it can cause issues.
