### ISSUE TITLE
Middle Click

### ISSUE THREAD

**Issue by explus4host** [folivoraAI/BetterTouchTool#723]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

I have a problem with 1 Finger Tap Middle > Middle Click, sometimes it working and some times it's not working and it's not working at all if your app is not shown in the menu bar unlink tracking speed and wheels are working fine without turn on your app

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

iMac, Magic Mouse 2

#### Device information:

Type of Mac:
macOS version: 10.12.3
BetterTouchTool version: 2.08

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

https://i.imgur.com/pPKto1I.png

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
BetterTouchTool needs to run if you want it to work.

Tracking speed is special because it just changes a system setting, thus BTT doesn't need to run. For almost everything else it is necessary to have BTT in the menubar.

**Comment by explus4host** [comment]
Ok, so what about this awkward issue ? Can I control the sensitive of
Middle click ? or the speed itself ?












*--------*
*With best wishes,*
*Website: explus4host.com <http://WwW.Explus4Host.CoM>*
*Mobile: 002-01010102347*

*FB: https://www.fb.com/ExpCompany <https://www.facebook.com/ExpCompany>*
*Twitter: https://twitter.com/ExpCompany <https://twitter.com/ExpCompany>*

On Sun, Mar 26, 2017 at 4:08 PM, Andreas Hegenberg <notifications@github.com

**Comment by fifafu** [comment]
You can increase the middle-click area: 
![image](https://cloud.githubusercontent.com/assets/8820811/24332009/34fd17d6-123f-11e7-8b8d-1f1fac667d3b.png)

However middle click on magic mouse is always kind of problematic. I'd recommend to use something like "Three Finger Click" instead.

**Comment by explus4host** [comment]
I'm using Apple magic 2 not the old one, Of course I increased it once I
used your app and 3 fingers for Middle click is kinda hard
Is there any other option or some kind of upgrade for your app to solve
this issue ?












*--------*
*With best wishes,*
*Website: explus4host.com <http://WwW.Explus4Host.CoM>*
*Mobile: 002-01010102347*

*FB: https://www.fb.com/ExpCompany <https://www.facebook.com/ExpCompany>*
*Twitter: https://twitter.com/ExpCompany <https://twitter.com/ExpCompany>*

On Sun, Mar 26, 2017 at 4:14 PM, Andreas Hegenberg <notifications@github.com

**Comment by fifafu** [comment]
No, apart from increasing the middle-click area there is not much you can do.

However I'm also using a Magic Mouse 2 and use the middle click gesture a lot and it is working as expected here.

Maybe try to open the "Live View" in BTT to make sure the middle-click area you set (it is highlighted red in the live view) does match your clicking behavior.

![image](https://cloud.githubusercontent.com/assets/8820811/24332461/3418dd20-1247-11e7-8f4e-19a75591a951.png)

**Comment by explus4host** [comment]
How about the sensitive ?












*--------*
*With best wishes,*
*Website: explus4host.com <http://WwW.Explus4Host.CoM>*
*Mobile: 002-01010102347*

*FB: https://www.fb.com/ExpCompany <https://www.facebook.com/ExpCompany>*
*Twitter: https://twitter.com/ExpCompany <https://twitter.com/ExpCompany>*

On Sun, Mar 26, 2017 at 5:11 PM, Andreas Hegenberg <notifications@github.com
