### ISSUE TITLE
Window moving & resizing not working in certain applications

### ISSUE THREAD

**Issue by mepelman** [folivoraAI/BetterTouchTool#724]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

Window moving & resizing not working in certain applications; in particular, I am having trouble with Excel windows

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Magic Trackpad

#### Device information:

Type of Mac: 2016 Macbook 
macOS version: 10.11.6
BetterTouchTool version: 208

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by justin-r-r** [comment]
I experience this with Excel intermittently, too. Also, the issue only occurs when the mouse position when starting the move/resize is *within* the main pane of the Excel window (the area display the cells). It works fine when the mouse starts on the toolbar at the top of the window, or the status bars on the bottom of the window.

Perhaps related: The Preview app and PDF documents viewed from within the Safari app display this problem, too (but it can be intermittent with Preview). In these cases, too, the issue only appears when the mouse starts from within the display of the main content (i.e., PDF), and not when the mouse starts on toolbars, etc.

My modifier keys are ctrl to move, and alt to resize.

Type of Mac: iMac 5k 2014 and MacBook Air early 2015
macOS version: 10.13.2
BetterTouchTool version: 2.318
