### ISSUE TITLE
BUG - "Delay next actions" worflows with touchpad

### ISSUE THREAD

**Issue by remirpn** [folivoraAI/BetterTouchTool#734]
#### Description of bug/feature request/question:
I'vethe following workflow working specially in "Reeder" app, usingtouchpad
[http://i.imgur.com/JvALvwZ.png](http://i.imgur.com/JvALvwZ.png)

However, instead of delaying the "next action", it seems that BetterTouchTool delay ALSO the 1st action.

For example, if I modify the delay to "4sec", the left click will happen after 4sec, even if this action is BEFORE the delay action.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Macbook pro late 2013 touchpad

#### Device information:

Type of Mac: macbook pro
macOS version: Sierra (10.12.13)
BetterTouchTool version: 2.071 (608)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Could you check whether this also happens with the current alpha? ( I think I fixed a bug related to delays, maybe that also fixed your bug)

**Comment by remirpn** [comment]
I seem to have identified the issue: 
- I have the following trackpad gesture : two finger tap = right clic (because it much more faster than the apple right click, even if smart zoom is deactivated"
- When a I do the "tiptap" gesture, BTT undertand it often as a "double click". 

I deactivated the BTT 2 finer tap as double clic and deactivated smart gesture in trackpad and now it works fine.

The weird thing is that the previous configuration was working fine until the last update...
