### ISSUE TITLE
Feature Request: Support Power/eject button

### ISSUE THREAD

**Issue by rodalpho** [folivoraAI/BetterTouchTool#736]
#### Description of bug/feature request/question:
The power/eject button is not mappable, BTT simply ignores it.

The Karabiner developer claims this button cannot be addressed as of Sierra, but the Powerkey app handles it fine. I have it remapped to F13 right now, as Powerkey's configuration is very limited. 

Note the Powerkey source is available on github.

https://pkamb.github.io/PowerKey/

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
External keyboard (Das keyboard mac version).

#### Device information:

Type of Mac: tMBP 15"
macOS version: 10.12.4 
BetterTouchTool version: 2.08

**Comment by Kallaste** [comment]
I would also love to see power button mapping supported. I wanted to map forward delete to it, but had to use the backslash instead.
