### ISSUE TITLE
Question: MacBook screenshot app overrides BetterTouchTool

### ISSUE THREAD

**Issue by marekgaj** [folivoraAI/BetterTouchTool#742]
#### Description of bug/feature request/question:
I couldn't find anywhere how to disable BetterTouchTool for default mac's screenshot app. For example, when I click command+shift+4, I would like to hide my current touch bar and show the default screenshot options. At the moment, I need to close BTT, choose the screenshot option and activate BTT again.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Touch Bar

#### Device information:

Type of Mac: MacBook Pro 2016
macOS version: 10.12.4
BetterTouchTool version: 2.084

**Comment by fifafu** [comment]
I'll check if I can auto-hide the BTT TouchBar if the screenshot tool is active.
