### ISSUE TITLE
Group Button with "Run AppleScript and Show Results" Widget capability

### ISSUE THREAD

**Issue by woodybrood** [folivoraAI/BetterTouchTool#743]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
It even could be having Button Group Widget. 

I've created a button group for controlling Adium. And I created a Widget for showing my current Adium Status. It would be awesome if I could merge that into a single button. It would save a bunch of space.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
TouchBar

#### Device information:

Type of Mac:2016 MBP 15" with TouchBar
macOS version: 10.12.4
BetterTouchTool version: 2.071

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
The green button with the two smilies is my status change group button, right next to a status widget button.
<img width="1085" alt="touch bar shot 2017-03-29 at 11 59 26 am" src="https://cloud.githubusercontent.com/assets/133438/24466679/5667825a-1477-11e7-8801-5eb539c675fd.png">

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by SanduLu** [comment]
+1.

Having Apple Script support for groups would be very helpful.

**Comment by fifafu** [comment]
Sorry for not replying earlier.

With the latest BTT version you can easily make buttons/groups invisible.

To solve your issue you could e.g. configure it like this using the "open touch bar group" action.
![image](https://user-images.githubusercontent.com/8820811/39929619-ca83d0a0-5538-11e8-968c-9d5838d4bdf6.png)
