### ISSUE TITLE
Brightness widget doesnt work with modification keys

### ISSUE THREAD

**Issue by buborh** [folivoraAI/BetterTouchTool#748]
#### Description of bug/feature request/question:
I added brightness widget, it works, but when I set shift+ctrl "only show while modifiers are pressed", it appearances when I press modify key, but slider doesnt effect brightness.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Touch Bar

#### Device information:
Type of Mac: macbook pro 13" 2016 with 4 thunderbolt 
macOS version:  10.12.4
BetterTouchTool version: 2.084 (614) and the latest stable

**Comment by nienkeboomsma** [comment]
I have the same issue.

MacBook Pro (13-inch, Late 2016, Four Thunderbolt 3 Ports)
10.13 Beta (17A315i)
BetterTouchTool version 2.281
