### ISSUE TITLE
Include a 'Quit App' action (like in BetterSnapTool extras)

### ISSUE THREAD

**Issue by cygvis** [folivoraAI/BetterTouchTool#752]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

I've used BetterSnapTool alongside BTT (for I don't know how long now) and have a "right-click (the red button) to quit" action set in BetterSnapTool. 

I was trying to move everything from BST over to BTT since it's got most of the same settings. But I think the only way to have that "quit app" action in BTT is to do a CMD+Q keyboard shortcut. Unfortunately, this would just quit the frontmost app & I like that BST will use the app window that I actually clicked.

It'd be nice to port that action over to BTT. That's all. 

Let me know if there's a way to do this in BTT that I'm not seeing.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
n/a

#### Device information:

Type of Mac: n/a
macOS version: 10.12.4
BetterTouchTool version: 2.071

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Isn't the app window that is being clicked, automatically the frontmost?

**Comment by pallavmac** [comment]
You can make an action that does a click attached with the cmd-q action.

**Comment by tmmcz** [comment]
@fifafu Only for a left-click. You can _**right-click**_ background windows without leaving the frontmost app. BST does it this way and it's very convenient. It also prevents accidentally quitting the frontmost app.

@pallavmac I mentioned this in my post. The goal is to quit background apps, which CMD+Q can't do.

**Comment by 2b** [comment]
Hello,

I there any hope that we'll get this feature in the near future?
