### ISSUE TITLE
Question: Redefining area of trackpad that constitutes left/right click?

### ISSUE THREAD

**Issue by jcwren** [folivoraAI/BetterTouchTool#754]
I find myself frequently trying to left-click the trackpad on my 13" MBP too far to the right, resulting in the click being treated as a center-click or occasionally a right-click. Is it possible in BTT to define the areas on the trackpad that constitute the click regions? 

For me, I'd end up defining the left 60% as a left-click, the center 20% as a middle-click, and the right 20% as a right-click.

I went through the BTT setup, and I don't *think* what I'm asking for was present, but with so many options available, it's possible I'm not recognizing it.

Thank you for an excellent program. I only use a very small portion of its capabilities, but it does exactly what I need it to.

**Comment by fifafu** [comment]
Sorry, BTT can't do this. Why aren't you using two finger clicks?

**Comment by jcwren** [comment]
It's awkward, particularly with the right hand due an injury of the middle finger that prevents it from having a full range of motion.
