### ISSUE TITLE
Snap areas are deleted if presets are exported / imported

### ISSUE THREAD

**Issue by Korgun** [folivoraAI/BetterTouchTool#757]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Exporting/Importing BTT profiles seem to delete snap areas.

- I created snap areas and lots of misc gesture changes on ComputerA
- I exported my BTT settings on ComputerA as ProfileA to import to ComputerB. Snap Areas created on ComputerA did not carry over to ComputerB on the import of ProfileA (which was disappointing, but understandable considering they are different resolutions)
- I then made a few changes on ComputerB and exported ProfileB to import to ComputerA so they would be in sync. I hadn't considered the Snap Areas at the time. I imported ProfileB to ComputerA
- I realized ProfileB didn't retain carry over of snap areas on ComputerA. However even when I select ProfileA (which was the original profile with snap areas) all the snap areas are gone.
- At this point it seems if user wants to use snap areas they should avoid importing or exporting (or vice versa)?
 
#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
MachineA: MBP 15" with touchbar built in trackpad
MachineB: MBP 13" without touchbar built in trackpad

#### Device information:

Type of Mac: See above.
macOS version: 10.12.4
BetterTouchTool version: 2.071

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Hi,

I guess this is the problem:
Snap areas are display specific. This means snap areas will always only work on the display they where created on. So if you export your 15inch snap areas, they won't show up on the 13inch Macbook and vice versa.

It is on my long term TODO list to find a workaround for this, however it's like this due to some technical limitations (I have some ideas how to workaround it, but it will need some time)

**Comment by Korgun** [comment]
Thanks for the quick response!
"The snap areas are still in your preset, but they will only show on the monitor they were created on."
I tested again and MachineA with ProfileB and it loaded so I'm not sure why it didn't work before but it did now. So this is true! :)

So if I mimic the snap areas on MachineB my exported profiles will retain both snap areas for profile A and B?

Thanks again!

**Comment by fifafu** [comment]
Exactly!

**Comment by mrdampsquid** [comment]
I just ran into this... almost identical scenario, have now lost all my snap areas!  URGH!

**Comment by unphased** [comment]
I recognize the absolutely essential need to store different zones on different monitors, and to have it remember as it is doing, as described, BUT, there are these even more common (in the sense of being more basic or trivial) scenarios: 

1. The primary screen on Different machines. I have 3 macbooks now and re-creating the few snap zones on each computer is like a one hour ordeal!

2. different resolutions of the same machine. It's true that in a higher resolution that the relative dimensions of areas perhaps should be tweaked. But, for (I'd say most) situations being able to copy over zones on a relative scale (so they end up in a similar place) would be exactly what's desired. 

So there are a few capabilities that if they can be supported would make this practical: 

1. allow copying all (or a subset) of a given monitor's resolution's snap zones into **another existing config for another monitor and resolution** 

I actually think this capability (however it gets implemented) is enough to eliminate most of the manual repetitive box editing work that needs doing, while also not putting any configuration at risk for overwriting.

To make it actually easy to use for the common case I specify above though (just the main monitor on multiple different Macs) a single purpose button can be added (which imports the originating main monitor's snap areas into the current machine's main monitor for that profile)
