### ISSUE TITLE
Defined Snap areas don't fill screen

### ISSUE THREAD

**Issue by erawlings** [folivoraAI/BetterTouchTool#759]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
I set up a Snap Area to cover the mid portion of the screen, top to bottom. When I activate it the window resizes horizontally correctly, but only covers the top 2/3 of the screen, not the full vertical length as defined. 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Apple Trackpad

#### Device information:

Type of Mac: MacBook Pro 15" ~2015
macOS version: 10.11.6
BetterTouchTool version: 2.071

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Can you manually resize the window to fit into the defined area? Maybe the app has some size constraints set?
