### ISSUE TITLE
Make BetterSnapTool also use the increased recognition area on the topside of the screen

### ISSUE THREAD

**Issue by chrisramakers** [folivoraAI/BetterTouchTool#769]
#### Description of bug/feature request/question:

In BST setttings it's possible to increase the size of the recognition area that's used to snap the windows left or right. It would be great if this could also increase the recognition area on the top/bottom side of the screen. 

I've got 2 27inch screens side by side and my macbook below them in the middle. If i want to maximize my window on my macbook screen the recognition area along the top of my screen is only a few pixels high, drag a little bit to far and release and the window is sitting on one of my topside screens along the bottom which is pretty annoying.

![built-in_retina_display](https://cloud.githubusercontent.com/assets/562866/24692400/0b094e12-19d9-11e7-88ef-2556de6a5fd7.png)

#### Device information:

Type of Mac: 2017 MacBook Pro /w touchbar
macOS version:  Sierra
BetterSnapTool version: 1.7

**Comment by luukschakenraad** [comment]
Same here, would be a nice feature.
