### ISSUE TITLE
Mapping middle click to "No Action" doesn't work

### ISSUE THREAD

**Issue by kennylanse** [folivoraAI/BetterTouchTool#771]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
I'm using a lenovo thinkpad bluetooth keyboard with macbook pro. I use trackpoint + middle button to scroll pages, so I would like to disable single middle click globally. But after I assigned middle mouse button to "no action" in global application, middle click still works fine as if I haven't set anything in BTT. 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Thinkpad bluetooth Keyboard with trackpoint [http://shop.lenovo.com/us/en/itemdetails/0B47189/460/60AC6A0372B14F5BA7B12F1FF88E33C7]

#### Device information:

Type of Mac: MacBook Pro (Retina, 15-inch, Late 2013)
macOS version: 10.12.4
BetterTouchTool version: 2.071 (068)

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by jeremybundgaard** [comment]
I use the lenovo keyboard for my fedora VM on my iMac. Just found a work-around to disable the middle paste, while retaining trackpoint scrolling via the [USB Overdrive](http://www.usboverdrive.com/) app. I found this solution on this [StackExchange post](https://superuser.com/questions/189122/middle-click-using-ibm-lenovo-keyboard-with-trackpoint-to-scroll-on-mac-os-x)
