### ISSUE TITLE
Arrangement error of "Other triggers" section

### ISSUE THREAD

**Issue by rambokang** [folivoraAI/BetterTouchTool#773]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

When I select a trigger (Please Select a Gesture button) in other triggers section,

Left click
: green > orange > red > full screen

Right click and other click
: red > orange > green > full screen

maybe arrangement is not correct in Lt. click case..

#### Device information:

Type of Mac:New MacBook Pro 2016 non-touchbar
macOS version: Sierra
BetterTouchTool version: 2.08

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Mhh this seems to work correctly for me. Could you provide a screenshot with your setup?

**Comment by rambokang** [comment]
When I remove “other” section, vertical gray line below ‘b’ of A’b’out is still remained.



And, in “other” section, red-orange-green is misaligned in “Leftclick” related triggers.

Please make these issues fixed.

Thank you

**Comment by rambokang** [comment]
<img width="1127" alt="screen shot 2017-04-14 at 9 18 56 am" src="https://cloud.githubusercontent.com/assets/26964569/25035963/d8a382da-212b-11e7-9f1e-de53847f5a0b.png">
<img width="1127" alt="screen shot 2017-04-14 at 9 18 45 am" src="https://cloud.githubusercontent.com/assets/26964569/25035964/d8d51aac-212b-11e7-907a-aedba0a24c38.png">

When I remove “other” section, vertical gray line below ‘b’ of A’b’out is still remained.


<img width="386" alt="screen shot 2017-04-14 at 9 19 23 am" src="https://cloud.githubusercontent.com/assets/26964569/25035965/d8d70fc4-212b-11e7-8993-f8f7c77874bd.png">

And, in “other” section, red-orange-green is misaligned in “Leftclick” related triggers.

Please make these issues fixed.

Thank you
