### ISSUE TITLE
"You have not yet configured actions..." on Touchbar when waking from sleep

### ISSUE THREAD

**Issue by akiss20** [folivoraAI/BetterTouchTool#775]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Coming out of sleep, I often get the message "You have not yet configured actions in BetterTouchTool" on the touchbar. I have to dismiss this by hitting the escape location on the touchbar before I get my touchbar functionality back. 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Touchbar

#### Device information:

Type of Mac: 2016 15" Macbook Pro
macOS version: 10.12.4
BetterTouchTool version: 2.071

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

[Example screenshot](http://imgur.com/a/viiLD)

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by andrewheiss** [comment]
I'm seeing this behavior as well. It seems to happen after waking the display, but only when an application that doesn't have Touchbar support is active (I think). When something that uses the Touchbar is active (like Pages, or something with custom BetterTouchTool icons), the Touchbar shows the appropriate icons. When something without Touchbar icons (like Finder) is active, the "You have not yet configured actions in BetterTouchTool" message is displayed.

Using macOS 10.12.4 and BTT 2.08.

**Comment by akiss20** [comment]
I think that is a better diagnosis than mine of coming out of sleep. I have noticed this issue when the computer has been awake for a while as well. It is not consistent though.
