### ISSUE TITLE
[Feature Request] Touch Bar - Button Group Apple Script

### ISSUE THREAD

**Issue by KrishJoshi** [folivoraAI/BetterTouchTool#776]
## Feature 
Show a Dynamic Name on a button group. Currently achieved using Apple Script.

## Use case 
I currently have a button for Spotify and it shows the song name. 
![image](https://cloud.githubusercontent.com/assets/302342/24758429/45481c46-1ada-11e7-840b-510dec5b753d.png)

On click of this button, the user is currently taken to the Spotify app.

It would great if I could configure this button as a Button Group and on click the user is shown Previous/Next song buttons.
![image](https://cloud.githubusercontent.com/assets/302342/24758644/e4fbc6e8-1ada-11e7-86db-12570a90d487.png)

## Alternatively
If this would require too much work, would it be possible On click of the current button to show the Spotify Bar?
![image](https://cloud.githubusercontent.com/assets/302342/24758726/20dac498-1adb-11e7-8ee1-2d4488cb04f6.png)

**Comment by fifafu** [comment]
I think having Apple Script button groups should be relatively easy. I'll look into it!

**Comment by sidewinder12s** [comment]
This would be really cool, I was thinking the same thing with Spotify. Make the button group display what's playing, while a press would open up media controls or other Spotify specific things.

**Comment by etaba** [comment]
Would really like this feature!

**Comment by fifafu** [comment]
The latest version has an option to hide buttons/groups which e.g. allows a configuration like this:

![image](https://user-images.githubusercontent.com/8820811/39929753-27bbccb4-5539-11e8-9acc-22c35bef6755.png)
