### ISSUE TITLE
4 Finger Tap is hard to be recognized (GIF included)

### ISSUE THREAD

**Issue by quangbuule** [folivoraAI/BetterTouchTool#779]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
The 4 Finger Tap gesture is hard to recognized

#### Device information:

Type of Mac:
macOS version: 10.12.3
BetterTouchTool version: 2.08

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

The GIF is 2.2MB, please wait for it:

![apr-07-2017 08-29-00](https://cloud.githubusercontent.com/assets/5992964/24781807/5b4bf778-1b6c-11e7-9273-8202d600a6a4.gif)

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
This may be fixed in the current alpha version (v2.095)
