### ISSUE TITLE
Bug: Non BTT Screen Clicks Delayed + Other App Activation Issues

### ISSUE THREAD

**Issue by ghost** [folivoraAI/BetterTouchTool#784]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Bug: With v 2.084 (614) of BBT & Mac OS 10.12.4 I can restart my Mac and everything works fine for a while. Then normal (non-BTT assigned) screen clicks in apps don't act as they should as well as clicking on an open app in the dock to make it active.

If I'm in Mail, or AirMail 2, I can click on an eMail in the list hit delete & nothing happens until I click on another eMail or another part of the screen in the same app. Then the eMail gets trashed & the other eMails slide up the list as they should. This is repeatable & happens in BOTH apps. So it's not app specific.

In other apps clicking on anything will just be ignored. Sometimes quitting the app & opening it will restore the function. But the issue is OS wide — not app specific.

While my Mac is in this state I can navigate to the Finder, where windows are open already, by clicking on the Finder dock icon or Command-Tab navigation — either way the Finder never comes to the front. I can hide all the apps in front of the Finder, and click on a Finder window, then the Finder becomes active & I can see the Finder Menu become active.

Restarting the Mac will fix the problem for a time — 15 minutes? Not sure. The bug is consistent, the amount of time until it occurs I have not recorded.

The only other way to stop the problem without restarting is to quit BTT. All issues go away without restarting.

I first thought is was a Sierra issue. Then it dawned on me to try quitting BTT because it was the only other extension dealing with/altering clicks.

I also tested your competitors product JiTouch — no problems there — just a lack of features.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Apple Magic Trackpad

#### Device information:

Type of Mac: Retina 5K, 27-inch, Late 2014 RAM: 32 GB 1600 MHz DDR3
macOS version: 10.12.1
BetterTouchTool version: 2.084 (614)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

No workaround other than restarting or disabling BBT.

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.
[BetterTouchTool_2017-03-19-110522_joiMac.crash.txt](https://github.com/fifafu/BetterTouchTool/files/906616/BetterTouchTool_2017-03-19-110522_joiMac.crash.txt)

**Comment by fifafu** [comment]
Hey,

are you using any other keyboard or mouse tool on your Mac? Unfortunately some of them conflict with BTT and can cause such behavior. (It's not their fault but rather an issue with the macOS apis)

Best,
Andreas

**Comment by AsburyParkJoe** [comment]
Hi Andreas ...

The only keyboard/mouse tools I can think of off the top of my head are:
Keyboard Maestro
SizeUp

Do you have a list of incompatible apps/utilities/extensions?


Is there anything I can send you, system error log etc, that could help you pinpoint the issue? I'm willing to help nail this down. Don't want to stop using BTT or any of my current utilities. lol They make Mac-life so much easier.

<small rant>
	Sadly, Apple keeps making it harder to do the things that, in the past, differentiated the Mac from Windoze — personalizing your user experience. ¯\_(ツ)_/¯ 
</small rant>
Thanks ... Joe

  <http://www.go2jo.com/>
Joe Streno 
710 6th Ave Unit 207
Asbury Park NJ 07712
732.910.5254
 <https://www.facebook.com/joestreno> <http://twitter.com/joestreno> <https://plus.google.com/u/0/+JoeStreno> <https://www.instagram.com/joestreno/> <https://www.linkedin.com/in/joe-streno-6112091a/> <mailto:joe@go2jo.com> <http://www.go2jo.com/>

**Comment by madvani** [comment]
I have the same issue! 

For the past few days, my mouse clicks have been dropping sporadically. If I stop or quit BTT, everything works fine.  When I restart BTT, after a few minutes I see the same behavior - clicking the left mouse button on a button once doesn't seem to register on the target window (or button, or hyperlink or menu item) ... sometimes it takes more than 2 clicks before the click takes effect.

I've restarted my MacBook, disabled other apps (like SizeUp) but no luck. 

System Info:
MacBook Pro (Retina, 15-inch, Mid 2015) running MacOS Sierra (10.12.4)
BetterTouchTool Version 2.071 (608)

Thanks,
Mahendra
