### ISSUE TITLE
[Feature Request] Support Double-clicking

### ISSUE THREAD

**Issue by rodalpho** [folivoraAI/BetterTouchTool#785]
#### Description of bug/feature request/question:
I would like to trigger an action (minimize to dock) by double right-clicking on the titlebar.

Would be great if double and triple-clicking with arbitrary mousebuttons was supported. 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Applies to regular mice only

**Comment by pallavmac** [comment]
You could 'attach' another action which would do the action of 'right-click' twice

**Comment by rodalpho** [comment]
Yes but that's the action; what I'm looking for here is for double rightclicking to be the _trigger._

**Comment by prohtex** [comment]
I'm looking for this too!
