### ISSUE TITLE
Feature request: move window to back

### ISSUE THREAD

**Issue by unikitty37** [folivoraAI/BetterTouchTool#786]
On my Kubuntu box at work, I can move an open window behind all other open windows by middle-clicking its titlebar. I was hoping to gain this functionality by installing BetterTouchTool, but it doesn't seem to be supported.

Being able to easily move a window behind others allows me to show a piece of information needed to work in the now-frontmost window, without having to continually fiddle about with resizing and arranging things. Is it possible to add a send-to-back function, or is it something that Apple doesn't make particularly easy?

Type of Mac: Mac Pro (2009)
macOS version: 10.11.6
BetterTouchTool version:  2.08 (610)

Thanks!

**Comment by sdrygalski** [comment]
It would be really great, it's the last part I miss from Microsoft Windows... 

And Cmd-H is not enough, because it hides all other windows of active app.

**Comment by alexM8** [comment]
yep. please, implement this

**Comment by Casebash** [comment]
This would be an incredibly useful feature say if you want to be able to toggle between two windows on a screen
