### ISSUE TITLE
Lag When Moving Windows Using Keyboard Shortcut

### ISSUE THREAD

**Issue by vexir** [folivoraAI/BetterTouchTool#788]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

Dragging a window while using the keyboard shortcut to do so is laggy. I am using a MBP trackpad. It used to be much snappier in previous versions.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

MBP Trackpad.

#### Device information:

Type of Mac: MBP 15" Mid-2015
macOS version: Sierra (10.12.4)
BetterTouchTool version: 2.08 (610)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

Happy to provide on request.

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
I don't think there has been a change here. Have you already tried to restart your machine?
