### ISSUE TITLE
Magic Trackpad force touch feedback issues with multiple users logged in

### ISSUE THREAD

**Issue by coasterfan** [folivoraAI/BetterTouchTool#793]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
When there are multiple users logged into macOS, the force touch feedback on a Magic Trackpad intermittently will be incorrect. Instead of feeling two "levels" of a click, I feel many levels, perhaps 8 or so. The issue crops up intermittently and can be temporarily fixed by restarting BTT. This bug has existed for more than a year.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Magic Trackpad

#### Device information:

Type of Mac: Mac Pro (Late 2013)
macOS version: 10.12.4
BetterTouchTool version: 2.071 (608)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by dennishylau** [comment]
I can verify this. Problem disappears right after logging out all other accounts beside the one currently in use. When experiencing this problem on my mac, I consistently feel three levels of click. The first level of haptic feedback comes with the regular click, and the third level comes with the force click. The second level does not seem to be associated with either the regular or the force click, and just appears out of nowhere.
