### ISSUE TITLE
Feature request: Force Quit Front Application

### ISSUE THREAD

**Issue by Gribnif** [folivoraAI/BetterTouchTool#794]
I'd like to be able to immediately Force Quit the frontmost application when it hangs, without confirmation. I hate the number of clicks involved in Apple's solution. Thanks!

**Comment by rodalpho** [comment]
I believe mapping command-option-shift-escape should do what you need.

**Comment by Gribnif** [comment]
I was unaware of that pre-defined keystroke. Given its existence, I think I'll close this request. Thanks!

**Comment by Gribnif** [comment]
Even though command-option-shift-escape is supposed to "Force Quit" the frontmost app, I tried it when an app was actually hung and it had no effect. That's despite the fact that I could even hold down the Shift key and select the command from the Apple menu.

Using command-option-escape and selecting it from the list does work, as does "kill -9".

So I'm reopening the request.
