### ISSUE TITLE
Feature Request; need shortcut to quick restart and/or OS switch (bootcamp)

### ISSUE THREAD

**Issue by Brohecan** [folivoraAI/BetterTouchTool#807]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Feature request; I would like to be able to make a shutdown/restart shortcut for my Mac not just BTT. I use bootcamp Windows on my Mac and I am in need of an easy way to initiate switch from macOS to Win. 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Keyboard and/or Touch Bar

#### Device information:

Type of Mac: 15" 2016 MacBook Pro w/ Touch Bar and 21.5" late 2013 iMac
macOS version: both on 10.12.4
BetterTouchTool version: both should be 2.08 (610) (but not near iMac)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

If you unfamiliar with BootCamp, there are two ways to switch from Mac to Win.
1. From shutdown (or during restart) hold 'opt' during start up to get option of choosing which OS
2. While in macOS go to System Preferences > Startup Disk > select OS and there is a restart button.

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by Rayyis** [comment]
I was looking for a way to do this, would be very sweet to have.
