### ISSUE TITLE
Left click mouse doesn't work sometimes after last actualization...

### ISSUE THREAD

**Issue by RexTheHut** [folivoraAI/BetterTouchTool#810]
Hi all...
After last BTT actualization my left click mouse doesn't work sometimes.
I try change my old wireless mouse by a new (both Logitech) but the problem remains.
I tried again with a new Logitech Bluetooth mouse (M535)  but also show the same issue.
I read in some discussions forums about this issue and after run AHT and others hardware testers, i was instructed to isolate the problem uninstalling all secondary apps. And when I remove BTT, the left click mouses back work fine again.

How can I fix this issue and use normally my BTT that i like much...

Macmini Late 2012 / OSX Sierra / Mouse Logitech Bluetooth M535

**Comment by fifafu** [comment]
Which version of BTT are you running now?
The latest alpha? (2.094?)

**Comment by RexTheHut** [comment]
I was using the 2.08 version (non alpha)...

**Comment by RexTheHut** [comment]
Does this "alpha"version working better?

**Comment by RexTheHut** [comment]
Hi Mr. Andreas.

I had problems with the previous BTT where my mouse did not work well (left click button).
I am currently using the Alpha version (2.094) and saw that there is a new version for updating.
Is this new update fixed this mouse click bug or should I still be using the Alpha version for what?

Thanks

Eduardo Lorena
EM Lorena Assessoria & Consultoria
+55 81 9.8111.1975
elorena@icloud.com
