### ISSUE TITLE
FEATURE - Adding move mouse to position with click

### ISSUE THREAD

**Issue by pallavmac** [folivoraAI/BetterTouchTool#814]
The 'move mouse to position' is an AMAZING feature when you attach additional actions to it to do certain tasks which would require lots of movement. However when making a macro, it is very tedious to constantly have to add 'move mouse to position' and then 'left click' individually. Could you add a feature or an option which combines the two since they are used so commonly together? So you could choose 'move mouse to position X and then click'.

**Comment by qwerty1123** [comment]
hey dude, i had the same question as you so i googled it and your post was the most relevant thing. i found the way to do it though and i got so excited that i made an account just to tell you in case you haven't figured it out yourself yet!

So, 
1. you create the first shortcut eg. Move Mouse to X: 123 Y: 123 
2. you click on the "Attach Additional Action" button which is right next to the "Add New Shortcut or Key Sequence" button.
3. you select the trigger predefined action of eg. Left Click
4. Enjoy!
