### ISSUE TITLE
Feature request: more PC keyboard key shortcuts (PrtScrn, ScrLck, etc)

### ISSUE THREAD

**Issue by bfod** [folivoraAI/BetterTouchTool#817]
#### Description of bug/feature request/question:

I work jumping between emulated computers (not just windows and mac, also Linux and DOS). It would be great if BTT could add support for more extended keyboard keys - beyond Del, PgUp, PgDn.

In particular:
Insert, Pause/Break, Scroll Lock, PrtScrn, Home, End, NumLock, and all the Numpad keys.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Touch Bar

#### Device information:

Type of Mac: Macbook Pro with Touch Bar
macOS version: 10.12.3
BetterTouchTool version: 2.094

**Comment by cleverjackal** [comment]
As a workaround for now, try remapping those keys to virtual f11, f12, etc. keys in Karabiner Elements and then setting them in BTT. This is, assuming BTT supports those... if not, maybe try some other keys?

**Comment by marekkaczkowski** [comment]
👍  for numpad on regular apple keyboard

**Comment by DrParanoia** [comment]
Yes, please, add numpad keys! Would be really useful for certain applications or games.
