### ISSUE TITLE
[BUG] Touchbar Button color

### ISSUE THREAD

**Issue by itxsvv** [folivoraAI/BetterTouchTool#819]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
BUG: Incorrect color after saving button
Steps to reproduce
Add new touchbar button
Set TouchBar Button Color to #AAAAAA
Click on Save
Open Advanced configuration
Click on TouchBar button color
Color is #9A9A9A

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Touch Bar

#### Device information:

Type of Mac: Macbbok Pro 13 with touchbar
macOS version: Sierra
BetterTouchTool version: 2.094(620)

**Comment by cornelius1** [comment]
I see the same issue with BetterTouchTool version 2.12 (631) on MBP 15 with touchbar & macOS 10.12.5.
