### ISSUE TITLE
Feature request: Change Icon Size in Finder

### ISSUE THREAD

**Issue by cedkar** [folivoraAI/BetterTouchTool#820]
macOS version:  OSX

#### Description of bug/feature request/question:
Please create a Better Touch Feature which allows you to change the size of thumbnail icons in finder. There is currently no keyboard shortcut or way to access through a feature menu. This would be greatly appreciated as music folders will display better album art on a home theatre computer from afar.

Thanks! 
PS love the app! Maybe a windows 10 version in the future?

**Comment by kuglee** [comment]
For the time being I've created these AppleScripts to change the icon size:

To halve the icon size: [https://drive.google.com/open?id=0B587aHGRbsYOWGJNVF9ydGJPdEE](url)
To double the icon size: [https://drive.google.com/open?id=0B587aHGRbsYOcUFkOHhHS2g1aEE](url)
