### ISSUE TITLE
Feature request: TouchBar confirmation on press

### ISSUE THREAD

**Issue by mickaelperrin** [folivoraAI/BetterTouchTool#821]
Hi,

Thanks for this incredible piece of software. I finally found an use of the touchbar thanks to your software.

I was wondering if it could be possible to add an option to the touchbar icon configuration to ask for a confirmation before launching the associated action ?

It would prevent accidental launch of potential dangerous commands.

**Comment by brantwedel** [comment]
You could make a button group for each "dangerous" command, with a single button with in "Confirm" that actually executed the action.
