### ISSUE TITLE
Palm blocking not working

### ISSUE THREAD

**Issue by jackson1442** [folivoraAI/BetterTouchTool#822]
#### Description of bug/feature request/question:
With the new MacBook pro, palm blocking is a necessity, but now my clicks are being handled incorrectly. Whenever I try to click something and I have any sort of part of my hand on the trackpad, it won't click.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Built in 2016 MBP trackpad

#### Device information:

Type of Mac: Macbook Pro 2016 Touchbar 13"
macOS version: 10.12.4 (16E195)
BetterTouchTool version: 2.094 (620)

**Comment by ArminMahban** [comment]
Same issue here on the 15" Touchbar Pro (2.094)

**Comment by akiss20** [comment]
I have noticed that 3 finger taps/clicks often fail when the palm is on the trackpad. Two finger and single finger taps/clicks seem okay for me though. Also on a 15" Touchbar MBP, 10.12.4

**Comment by ArminMahban** [comment]
2.10 has not fixed the issue unfortunately. Have to revert back to 2.071

**Comment by fifafu** [comment]
Would be great if you could test v2.17 alpha.
