### ISSUE TITLE
Specify which apps are allowed to use Snap Areas

### ISSUE THREAD

**Issue by robinckarlsson** [folivoraAI/BetterTouchTool#829]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
I would love it if you could exclude certain apps from using Snap Areas, or maybe just specify which apps are allowed to use it. Great feature in any case!

#### Device information:

Type of Mac:
macOS version: 
BetterTouchTool version: 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Yes I can add this.
For now you can specify it for every snap area like in that screenshot:

![image](https://cloud.githubusercontent.com/assets/8820811/25723216/6ef6d20a-3117-11e7-84ca-0b5ad45b3885.png)

**Comment by robinckarlsson** [comment]
Alright! Hadn't found that function yet, thanks! It will do for now. =)
