### ISSUE TITLE
Cheat sheet showing shortcuts in the given context

### ISSUE THREAD

**Issue by BrianSiimAndersen** [folivoraAI/BetterTouchTool#83]
I have a feature request. I have looked at the different settings and can't seem to find any that does this.

What I would like is to setup a shortcut to show a cheat sheet containing all the available shortcuts in the given context. I have set up quite a few shortcuts for indvidual applications, and it can be tricky to remember all the shortcuts. So an easy way to view the shortcuts I've set up in BTT would be nice.

So when setting up a shortcut it might be a good idea to be able to set a title for the shortcut.

**Comment by fifafu** [comment]
Good idea!

**Comment by fifafu** [comment]
This issue was moved to https://community.folivora.ai/t/cheat-sheet-showing-shortcuts-in-the-given-context/87

**Comment by fifafu** [comment]
Sorry, please ignore the previous message. The migration didn't work correctly, for now the issues will stay here.
