### ISSUE TITLE
[bug] Wacom tablet support disabled after reboot

### ISSUE THREAD

**Issue by joacovidal** [folivoraAI/BetterTouchTool#830]
#### Description of bug/feature request/question:
After a reboot, the "Enable experimental support for Wacom tablets" checkbox is still checked, but in the gestures panel says that there's no compatible device connected.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Wacom Intuos Pen & Touch

#### Device information:

Type of Mac: iMac / Macbook Pro
macOS version: 10.12.4 (Sierra) in both of them
BetterTouchTool version: 2.071 (608)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
If I uncheck/check again that option, it gets working again. But I have to do this every time I reboot my mac.

**Comment by roinigo** [comment]
Hello! I have the same problem. Did you find a way to solve it ?
Where's is the "_Enable experimental support for wacom tablets_" checkbox, please ?

**Comment by joacovidal** [comment]
No, sorry, I didn't solve it.

"Enable experimental support for wacom tablets" option is in the advanced settings tab

**Comment by roinigo** [comment]
Thank's for the answer Joaquin... but i don't have this option in my version (2.310)... :(
My Wacom tablet doesn't work anymore...
