### ISSUE TITLE
Close Currently Open Touch Bar Group

### ISSUE THREAD

**Issue by DTowersM** [folivoraAI/BetterTouchTool#832]
#### Description of bug/feature request/question:
In the touch bar, if you have a group within a group, the "Close Currently Open Touch Bar Group" closes all currently open groups. It would be nice if we had the option to only close the current group, keeping the parent group open. 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Touchbar

**Comment by fifafu** [comment]
Currently BTT officialy only supports one level of groups but I just noticed you can get groups into other groups by dragging them there :-) (this wasn't intended).

I'll have to think about how to handle this properly.
