### ISSUE TITLE
[Feature Request] Toggle Visibility of Buttons

### ISSUE THREAD

**Issue by DTowersM** [folivoraAI/BetterTouchTool#833]
#### Description of bug/feature request/question:
Allow for the visibility of the Touch Bar "Run Apple Script and Show Return Value" Widget to disappear under certain conditions. In the same way that we can toggle the icon and color under certain circumstances, allow us to set it up so the button simply does not appear.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Touch Bar

**Comment by fifafu** [comment]
Hey,

if you return an empty string from your Apple Script it will hide the button!

Best,
Andreas
