### ISSUE TITLE
Gestures lost everytime I upgrade to new version

### ISSUE THREAD

**Issue by mpweaver** [folivoraAI/BetterTouchTool#836]
Everytime I upgrade to a new version of BTT none of my gestures remain and I have to import them again. Can this be fixed? I'm on OS X 10.11.6

**Comment by fifafu** [comment]
Sounds like some sort of file permission problem. 
You could try to delete the ~/Preferences/Library/Preferences/com.hegenberg.BetterTouchTool.plist and the ~/Library/Application Support/BetterTouchTool folder, however this will reset all BTT settings.

Alternatively try to use the repair file permissions option in apple's Disk utility

**Comment by mpweaver** [comment]
Thanks I'll give those suggestions a try.

**Comment by rodalpho** [comment]
I also lost my configuration upgrading from 2.08 to 2.094. Luckily I had exported a backup this time, which imported fine.
