### ISSUE TITLE
binding 2 keystrokes at the same time on a single keystroke or mouseclick

### ISSUE THREAD

**Issue by sanzo77** [folivoraAI/BetterTouchTool#843]
#### Description of bug/feature request/question:
I'd like to bind 2 different keystrokes at the same time (e.g. SPACE+W, then not a modifier like ctrl+otherkey) on a single keystroke or on a mouseclick. I found in BTT only the way to bind two sequential keystrokes but not two keystrokes together.
Is there a way that I missed or is it necessary the developing of a feature?

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Every mouse or keyboard

#### Device information:

Type of Mac:Macbook pro
macOS version: 10.12.4
BetterTouchTool version: 2.094

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by Trucksterdk** [comment]
I have the same issue. I need to make a gesture for copy/paste (CMD+c and CMD+v)
I wonder why anyone hasn't picked up this issue. It's 1 year old. 😊

**Comment by amarpatel** [comment]
<img width="818" alt="untitled 2" src="https://user-images.githubusercontent.com/5858247/38627957-05e5d22e-3d65-11e8-8c14-11ba7b675fff.png">

I was able to bind `ctrl+b` to the sequence `cmd+a`, `cmd+c`, `cmd+v` (select all, copy, paste).

**Comment by Trucksterdk** [comment]
Already tried that... doesn't work for me😒

**Comment by Trucksterdk** [comment]
Correction... it works... thanks 😊
