### ISSUE TITLE
Version 2.094 needs to be opened for shortcuts to work again

### ISSUE THREAD

**Issue by haniag** [folivoraAI/BetterTouchTool#847]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

After updating to version 2.094, my shortcuts in finder intermittently work. When they don't work, I have to re-open the app, and close again.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

rMBP on 10.12.4, using wired Apple keyboard.

#### Device information:

Type of Mac: 13-inch, Late 2013
macOS version: 10.12.4
BetterTouchTool version: 2.094

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
could you check whether this still occurs in 2.097 alpha?

**Comment by haniag** [comment]
I version I was able to get is 2.098 alpha. I will try it, but will report back in a couple of days, as this has been intermittent

**Comment by haniag** [comment]
After installing 2.098 alpha, I received an update notification to 2.10 which I thought will have the same updates as the alpha. After updating, the issue still persists.

**Comment by fifafu** [comment]
Weird i can not reproduce this at all :-( 
Could you please open the BetterTouchTool preferences, then go to the "about" tab and select the "export debug information" button?

This will create a folder on your desktop called BetterTouchToolDebug, could you send that to me?

**Comment by haniag** [comment]
sent data to your gmail.
