### ISSUE TITLE
fn -   and fn = cannot be mapped

### ISSUE THREAD

**Issue by joobei** [folivoraAI/BetterTouchTool#857]
#### Description of bug/feature request/question:
I am trying to map fn - (fn+minus key) to volume-up and fn = to volume_down but it doesn't work. It could be this is happening because the fn key is used by macos sierra by default to expand the Touch Bar. Is there any work around to this using Better Touch Tool?  This seems related to #764.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Macbook Keyboard

#### Device information:
Type of Mac: macbook pro late 2016 with touchbar
macOS version:  Sierra 10.12.4
BetterTouchTool version: 2.094

**Comment by fpenguin** [comment]
I just upgraded from 2013 macbook air to 2017 macbook pro with touch bar.
my old short cuts that have FN no longer works (eg. FN+M = open Mail app, FN+S = open Slack)
while all the other short cuts work just fine (ctl+opt+cmd+delete = empty trash)
