### ISSUE TITLE
Key repeat is too slow

### ISSUE THREAD

**Issue by hpello** [folivoraAI/BetterTouchTool#880]
#### Description of bug/feature request/question:
Hi,

I am using BetterTouchTool to remap all arrow shortcuts (left, shift+left, ...) to ctrl+hjkl (ctrl+h, shift+ctrl+h, ...)
It would be great if the minimum (0) delay for key repeat could at least match the minimum key repeat of OSX, as right now BTT's delay it is still a bit longer (and I kind of rely on that to navigate fast :) )

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Keyboard

#### Device information:

Type of Mac: MacBook Pro Retina
macOS version: 10.12.4
BetterTouchTool version: 2.10

**Comment by cleverjackal** [comment]
That's true. I noticed as well. This was discussed in another issue, too

**Comment by nschaper** [comment]
+1 
I also need faster key repeat.  I use Emacs-style bindings for the arrow keys.  

It would be nice if key repeat matched the OSX Key Repeat setting in keyboard preferences.

I'm using v2.297

**Comment by ashussen** [comment]
Hey, 

Could you please tell me how to allow the key repeat on the BTT?
I couldn't find the option and its annoying to keep repeating key manually (ctrl+h, ctrl+h, ctrl+h, ...)
