### ISSUE TITLE
Quick Three Finger Swipe Recognized as Swipe+Scroll

### ISSUE THREAD

**Issue by monstermac77** [folivoraAI/BetterTouchTool#881]
#### Description of bug/feature request/question:
I believe since using BTT on my 2016 Macbook Pro, I've been having this incredibly annoying issue. I use a three finger swipe on applications to switch between their tabs (e.g. switch between Chrome tabs or Sublime Text tabs), and when I quickly swipe three fingers on the trackpad, the tab is switched but then also the content of the new tab seems to get a short horizontal scroll gesture, because it scrolls its content slightly. 

It appears to be dependent on the speed at which I swipe, as a very slow and deliberate three finger swipe does not trigger this scrolling. 

**Update:** I just updated to BTT 2.10 and the issue seems to be either gone or significantly reduced; was an improvement made in 2.10?

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Trackpad

#### Device information:
Type of Mac: 2016 Touch Bar Macbook Pro
macOS version: 10.12.4
BetterTouchTool version: 2.8

**Comment by Murgatroyd314** [comment]
I can confirm this issue, and that it still exists in 2.11 (630).

Touch Bar MBP, Sierra 10.12.4

**Comment by monstermac77** [comment]
This issue appears to have gotten _significantly_ worse in more recent BTT versions.

**Comment by monstermac77** [comment]
@fifafu any update on this? I've been running 2.427 and this issue has been pretty bad. I'd like to downgrade back to 2.11, but it's not compatible with my data file.
