### ISSUE TITLE
"Touch bar behavior" setting for Global does not work

### ISSUE THREAD

**Issue by agj** [folivoraAI/BetterTouchTool#884]
In the 'General touch bar settings' menu I have 'Show macOS Control Strip' disabled. If I try to enable it only for the 'Global' case, as per the setting when right-clicking 'Global' on the left hand-side application list, the setting won't work. It works as expected when set for individual apps, but it does not seem to be observed for Global (which I'm taking to mean, any app that is not on the list), which just uses the default. Tried the opposite case, but the result is the same; it looks like the setting is just being ignored.

I'm using BTT 2.10 on a 15-inch touch bar MBP, on macOS 10.12.4. If there's any other information that may be of help, please let me know. Thank you!

**Comment by fifafu** [comment]
Hey,

That's true, it's currently not supported for the global section. I'll add this soon!

**Comment by agj** [comment]
Cool, thank you!
