### ISSUE TITLE
With tap=click double tap isn't double click

### ISSUE THREAD

**Issue by herbs** [folivoraAI/BetterTouchTool#886]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Device information:

Type of Mac:
macOS version: 
BetterTouchTool version: 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by herbs** [comment]
iMac (late 2011) and MacBook Pro (mid-2015) both running Sierra as well as 11" MacBook Air (mid 2012) running El Capitan (latest version of each macOS) I have single finger tap = click set but now double tap no longer acts as double click.

**Comment by fifafu** [comment]
Touchpad taps are not handled by BTT. They are done by the system.
Are you sure you have enabled System Preferences => Accessibility => Mouse & Trackpad => Trackpad Options => Enable dragging without draglock?

**Comment by herbs** [comment]
> On May 6, 2017, at 1:45 AM, Andreas Hegenberg <notifications@github.com> wrote:
> 
> Touchpad taps are not handled by BTT. They are done by the system.
> Are you sure you have enabled System Preferences => Accessibility => Mouse & Trackpad => Trackpad Options => Enable dragging without draglock?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Howdy,

I just noticed that when I delay the second tap it works. But I used to be able to double tap quickly and have it work. If I enable the Tap->Click in System Preferences I get that for the full trackpad; I want it only along the bottom (left, center, right) and that used to work without me setting that System Preference.

Good Luck,

Herb Schulz
(herbs at wideopenwest dot com)

**Comment by herbs** [comment]
Howdy,

Ok, I understand it better. Setting Tap=Click all along the bottom. with earlier versions of BTT (before 2.10 and 2.095) a quick two taps would be the same as a Double Click. With 2.095 and 2.10 there must be a considerably longer delay between the taps for it to be detected as a Double Click. 

Good Luck,
Herb Schulz

**Comment by herbs** [comment]
Howdy,

The 2.14 alpha has fixed this problem! Thanks!

Good Luck,
Herb Schulz
