### ISSUE TITLE
TipTap Right/Left (2 Fingers Fix) : Hard to trigger on new MBP 2016

### ISSUE THREAD

**Issue by piotrnikov** [folivoraAI/BetterTouchTool#887]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

I've been using TipTap Right (2 Fingers Fix) to close my windows on my previous MBP 2012 successfully. Since I changed my Mac, this command seems to be randomly working... I have to insist a couple of times for it to eventually work. Live View shows me that I'm doing the gesture correctly. Please help :)

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

MacBook Trackpad

#### Device information:

Type of Mac: MacBookPro 2016
macOS version: 10.12.4
BetterTouchTool version: 2.10

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Try to increase the allowed distance between the fingers:
![image](https://cloud.githubusercontent.com/assets/8820811/25771118/b06a0f40-3248-11e7-9dab-70a1f7f664bb.png)

**Comment by piotrnikov** [comment]
I tried but didn't seem to make a difference...

On Sat, May 6, 2017 at 10:42 AM, Andreas Hegenberg <notifications@github.com

**Comment by fifafu** [comment]
Have you also tried to adjust the tip tap sensitivity to a lighter value? 
See this screenshot:
![image](https://cloud.githubusercontent.com/assets/8820811/25771278/a70b0d1e-324d-11e7-840b-af3418ff4234.png)

**Comment by piotrnikov** [comment]
Yup!
I think I tried everything in that menu :)
That's why I submitted this thread...
I just tried BTT on my old laptop again (MBP 2012). Works as expected.


On Sat, May 6, 2017 at 11:18 AM, Andreas Hegenberg <notifications@github.com

**Comment by fifafu** [comment]
Weird, I can't seem to reproduce that on my 2016 Touchbar Macbook.

Do you also have the Touchbar version or the one without Touchbar?

**Comment by piotrnikov** [comment]
Yes touchbar...
I'll reset everything and redo my settings by hand  (I imported everything
from a settings file) and report back.


On Sat, May 6, 2017 at 12:04 PM, Andreas Hegenberg <notifications@github.com

**Comment by jasminengn** [comment]
@fifafu Hi, I would like to report that I might have the same issue. Currently on my MBP 2017 Touchbar tip tap RIGHT (2 fingers fixed) is working perfectly. 

However the tip tap LEFT (2 fingers fixed) is not working at all. Could you please look into this when you can? Thank you.
