### ISSUE TITLE
Shift+CMD+Q Logout KeyMapping overwriting not working

### ISSUE THREAD

**Issue by LandoKarusian** [folivoraAI/BetterTouchTool#891]
Hi,
i want to overwrite the shortcut shift+cmd+q which brings the mac to logout. I was able to overwrite cmd+q
but when i try to put in shift+cmd+q the logout appears. So i tried to map the function to another shortcut with "trigger predefined action" which works as the new shortcut but other tha for example "cmd+q" it's working beside the old one(shift+cmd+q). So instead of rermapping it's working parallel.
Sorry for my english i hope you understood my problem.
Greetings

Keyboard

Type of Mac: iMac (Retina 5K, 27'', ultimo 2014)
macOS version: macOS Sierra 10.12.4 
BetterTouchTool version: 2.10

**Comment by LandoKarusian** [comment]
Anyone?

**Comment by fifafu** [comment]
This is a special shortcut. The only workaround I can think of is to redefine it in System Preferences, so it overrides the default shortcut. Then you can use the default shortcut in BTT.

See this screenshot (System Preferences => Keyboard => Shortcuts => App Shortcuts)
![image](https://cloud.githubusercontent.com/assets/8820811/25780589/04321d66-332a-11e7-8376-0c793d0c0dc7.png)
