### ISSUE TITLE
Feature request: Further styling options (e.g., editable border radius) for Touch Bar buttons

### ISSUE THREAD

**Issue by RichardTsc** [folivoraAI/BetterTouchTool#892]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

Currently, all Touch Bar buttons are created with rounded corners with a fixed border radius (e.g., 3px). It would be great, if some more styling options (e.g.,  this border radius oder top margin, ...) would be configurable per button.

That way, I could bring the optic of my config closer to the MS PowerPoint standard optic:

BBT config:
<img width="1085" alt="ctrl - coloring" src="https://cloud.githubusercontent.com/assets/6375308/25771563/aedc0266-3255-11e7-9955-dc090f92e7a6.png">

PPT Standard Touch Bar
<img width="1085" alt="ppt" src="https://cloud.githubusercontent.com/assets/6375308/25771576/02f5cecc-3256-11e7-8942-9c859339c349.png">

#### Device information:

Type of Mac:
macOS version: 
BetterTouchTool version: 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by RichardTsc** [comment]
The current option "free space after button" equals a css margin-right and "extra padding inside" equals padding. 

One possibility would be to use a syntax similar to the css shorthand syntax for padding/margin: https://www.w3schools.com/css/tryit.asp?filename=trycss_padding_shorthand2

**Comment by adammascherin** [comment]
I second this feature. Definitely needed. This would allow creating button groups. 

For example, 
- left button: rounded corners on the left side, sharp corners on the right
- middle button: sharp corners on both left and right
- right button: sharp corners on the left, rounded corners on the right
