### ISSUE TITLE
AppleScript using "curl" hanging

### ISSUE THREAD

**Issue by fantaaaaaa** [folivoraAI/BetterTouchTool#894]
Hi Andreas,

i am using AppleScripts to check the status of some of my devices via the web. Sometimes, my server is not available for checking which will hang BTT and the script in the background.

I have tried implementing a maximum time for the curl request and it works in the script editor but not in the final script in BTT.

Thats the script, which should time out after 3 seconds:

```
property baseURL : "http://xxxxxx:8099/zuhause/assets/php/homekitHandler.php?device=SCHLAFZIMMER_LAUTSPRECHER&action=status"
set ergebnis to "empty"

try
	set ergebnis to do shell script "curl --max-time 3 '" & baseURL & "'"
	if ergebnis = "1" then set ergebnis to "on"
	if ergebnis = "0" then set ergebnis to "off"
	return ergebnis
on error
	set ergebnis to "error"
end try
```

its working fine in apples script editor but in BTT it either does not finish at all or it takes a loooot longer. 
is it possible that BTT works differently here? any ideas?

**Comment by fifafu** [comment]
I'll be adding a modified widget that is able to run bash scripts directly - unfortunately Apple Scripts have various restrictions (e.g. they are always executed in a queue, which may cause this issue)

**Comment by fantaaaaaa** [comment]
is this something that might come soon? :)

**Comment by fifafu** [comment]
Yes, sometime next week!
