### ISSUE TITLE
Only show buttons on touch bar when an app is open

### ISSUE THREAD

**Issue by graiffgarcia** [folivoraAI/BetterTouchTool#899]
#### Description of bug/feature request/question:
I'm able to add previous/playpause/next buttons to the touch bar, and they're very useful with Spotify and iTunes. However, I'd like those buttons to only show if either of those applications are running -- just like the very useful AppleScript to show the currently playing track.

I've tried using AppleScript, to disastrous results (if I write a script like "if *app* is running, tell *app* next track", then it will happen automatically without me needing to interact with the button) -- but maybe I'm using it incorrectly? In either case, is it possible to add a button that only shows if an app is running?

Edit: just to clarify, my idea is to have these buttons appear "globally", no matter which app is active -- but only if those apps are open.

Thank you!

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Touch Bar

#### Device information:

Type of Mac: Macbook Pro 15"
macOS version: 10.12.4
BetterTouchTool version: 2.10

**Comment by MalabarFront** [comment]
I've done this with the Applescript and Show Return Value widget with okay results. Example 'Next track' button:

```
if application "Spotify" is running then
	return "Next"
else
	return ""
end if
```

With the predefined action on that button being 'Keyboard Keys -> Next'. I have it set to only show the icon, but either way if the return value is blank, the button isn't shown.
