### ISSUE TITLE
apple script

### ISSUE THREAD

**Issue by sbrar17** [folivoraAI/BetterTouchTool#902]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
When apple script is run (from a touch bar button) the script does not run properly. Touch bar button is used to launch a Keyboard Maestro apple script that finds an image on screen (in Citrix Viewer) and is supposed to click it. Running macro in betterTouchTools moves mouse to image position but mouse click appears to fail. Apple script runs fine using a keyboard shortcut trigger (Keyboard Maestro) and directly from within Keyboard Maestro. Apple script also runs fine when triggered from an external USB device (X-keys). Issue is limited to BTT best I can tell as script executes as expected through other triggers.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Touch bar

#### Device information:

Type of Mac: MacBook Pro (15 inch, late 2016)
macOS version: 10.12.4
BetterTouchTool version: 2.11 (630)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
BetterTouchTool just tells the system to execute the script - it doesn't modify it it any way.

Maybe it users Keyboard Maestro specific functionality?
