### ISSUE TITLE
Feature Request : IFTTT integration

### ISSUE THREAD

**Issue by TheBartoMan** [folivoraAI/BetterTouchTool#911]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

It would be awesome if you could integrate this. I could make things happen on my Touchbar to notify me of things that are happenning with my other devices and also action them.

Please consider this would be a massive expansion for your application, plus the millions of IFTTT users would be instantly informed your app has been added giving you a lot more users/sales.

#### Device information:

Type of Mac:
macOS version: 
BetterTouchTool version: 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by TheBartoMan** [comment]
After over a year it would of been nice to get an opinion before it was just closed :(

**Comment by fifafu** [comment]
The BTT issue tracker has moved to https://community.folivora.ai early this year and all issues here have been auto-closed now. In case you still need help with this issue / feature / question please create a new post there.
