### ISSUE TITLE
Feature Request : Much larger window for writing the Applescripts.

### ISSUE THREAD

**Issue by TheBartoMan** [folivoraAI/BetterTouchTool#913]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

I have some large applescripts which it is really hard to work on in the window you have provided.

#### Device information:

Type of Mac:
macOS version: 
BetterTouchTool version: 

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Just drag it bigger, or doesn't this work for you?
Starting with macOS 10.11 BTT windows should be resizable.

**Comment by TheBartoMan** [comment]
Thanks I will wait for the update.
