### ISSUE TITLE
TipTap gestures suddenly stop working, reset doesn't fix it

### ISSUE THREAD

**Issue by ignaciobarrena** [folivoraAI/BetterTouchTool#916]
#### Description of bug/feature request/question:

TipTap gestures suddenly stop working, reset doesn't fix it, had to quit and start de app again.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Macbook Pro 2015 13" Trackpad

#### Device information:

Type of Mac: rMBP 20115 13"
macOS version: 10.12.4
BetterTouchTool version: 2.11

**Comment by mastahype** [comment]
Same here. Only noticed in 2.11 update. Also tried changing sensitivities and distance for TipTaps. Persisted after restarting.
HW: Mac Mini (Late 2012). MagicTrackPad (non force)
macOS: 10.12.4
BTT: 2.11
