### ISSUE TITLE
Feature request: Trigger basic key value / remap keys

### ISSUE THREAD

**Issue by christianjul** [folivoraAI/BetterTouchTool#923]
#### Description of bug/feature request/question:

I use BTT to map special danish characters unto a us keyboard layout in the same places that they would be on danish keyboard, but with a modifier key.

As far as I can see there is no action which is to simply output the value of another key. 

I currently use the paste action to achieve this, but it is slow in some apps, leading to a paste in the wrong position if I keep on typing. Also some apps listen for a paste event and show a context menu.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

all.

#### Device information:

Type of Mac: MacBook Pro (Retina, 15-inch, Mid 2014)
macOS version: 10.12.4 (16E195)
BetterTouchTool version: 2.11

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

Great product :)

**Comment by oqibidipo** [comment]
How about creating a custom US/Danish keyboard layout instead?
You can do that easily with Ukelele:
http://scripts.sil.org/ukelele

**Comment by christianjul** [comment]
That sounds like a very good way to solve it, didn't know it is possible to make custom layouts. Thanks a lot @oqibidipo I'll take a look at the tool.

Still thinks the mapping feature would be handy though.

**Comment by JohnSchlerf** [comment]
I'd like some support for this feature, as BTT would then allow app-specific key-switching in this case.

For my use case, I often toggle between Jupyter (where Shift+Enter submits, Enter inserts a newline) and Slack (where Shift+Enter inserts a newline, Enter submits). This drives me bonkers, and I would LOVE to switch this behavior in one of the apps. Currently, either shortcut works on its own just fine, but once both are enabled nothing. I'm guessing the first shortcut triggers the second, which triggers the first... and then hooray, I've disabled my Enter key.
