### ISSUE TITLE
Jumping cursor

### ISSUE THREAD

**Issue by pskling** [folivoraAI/BetterTouchTool#925]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Trackpad

#### Device information:

Type of Mac: Mac Mini
macOS version: 10.12.4
BetterTouchTool version: 2.12

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
BTT doesn't change the cursor location unless you configured some action that does it. Could  you attach an export of your current setup? (via manage presets)
