### ISSUE TITLE
five finger swipes not working as well !

### ISSUE THREAD

**Issue by hsnmapar** [folivoraAI/BetterTouchTool#936]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
each time I wanna use five finger swipes, must restart BTT

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Trackpad

#### Device information:

Type of Mac: MacBook Pro (13-inch, Early 2011)
macOS version: Sierra (10.12.4)
BetterTouchTool version: 2.12 (631)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by jacobwil** [comment]
I'm experiencing the same issue with three finger swipes. They break a short period after BTT launches.
