### ISSUE TITLE
Bluetooth LE triggers not working

### ISSUE THREAD

**Issue by pawelkondraciuk** [folivoraAI/BetterTouchTool#940]
#### Description of bug/feature request/question:
Bluetooth triggers are not working. I've bought iTAG, it is listed on bluetooth devices. If I move away nothing happens.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Bluetooth LE

#### Device information:

Type of Mac: Macbook Pro
macOS version: Sierra 10.12.14
BetterTouchTool version: 2.12

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

![image](https://cloud.githubusercontent.com/assets/7136191/26025519/e6e76ada-37e9-11e7-929d-cdf1e3537d99.png)

![image](https://cloud.githubusercontent.com/assets/7136191/26025510/bc7a2c88-37e9-11e7-9eea-b2ef22a52835.png)

**Comment by Porco-Rosso** [comment]
I'm having the same issue. It would also be great to have a trigger: bluetooth device connects.

**Comment by kmcnellis** [comment]
Same here

**Comment by joshuamking** [comment]
Not working for me either 😭

**Comment by civersen** [comment]
Not working for me either (v2.530)
