### ISSUE TITLE
[FEATURE REQUEST] Run Javascript Bookmarklets in Chrome through the touchbar

### ISSUE THREAD

**Issue by jayfehr** [folivoraAI/BetterTouchTool#950]
I have a few bookmarklets that I run in Chrome using the standard bookmarks bar. I was hoping that I could move those to the touchbar and have single press access to them.

**Comment by chris-scheurle** [comment]
Two options how to achieve this completely without any new features:

:arrow_right: Install [Shortkeys](https://github.com/mikecrittenden/chrome-shortkeys) (or any other shortcut tool) from the Chrome Web Store, map some keyboard shortcuts to the bookmarklets, trigger _those_ via **BTT**.

:arrow_right: Create an action "Send Shortcut to Specific App" with options "`⌘L`", "`Google Chrome`" and "Bring app to front before sending the shortcut". Attach an additional Action "Delay Next Action" with option "`0.75 seconds`". Attach an additional Action "Type Custom Text" with option "Insert Text by Typing" and your bookmarklet's contents as the text.

I like the first one better, but it requires additional software. With the second, you'd have to copy every bookmarklet's code to some **BTT** action and you can see the text beeing typed into the URL bar, which I consider a bit unaesthetic.

**Comment by chris-scheurle** [comment]
_Ooops_, I just edited the post above, I had forgotten to mention:

> _followed by an empty new line_

**Comment by itsskin** [comment]
Thx a lot for help! Shortkeys was my first try. But it's a little buggy fails in some situations.
I ended up running an applescript that runs an external javascript file. Here is the code:

=======================

on readFile(theFile)
	set theFile to theFile as string
	return read file theFile
end readFile

set theFile to POSIX file "/Users/Shared/ESPScripts/ToggleMinimalInterface.js"


tell application "Google Chrome"
	execute active tab of front window javascript read file theFile
	
end tell

=======================
