### ISSUE TITLE
I think most recent update broke "Open Native OS X Split View for Window"

### ISSUE THREAD

**Issue by gilgameshskytrooper** [folivoraAI/BetterTouchTool#956]
#### Description of bug/feature request/question:
Previously, we could split the screen left or right based on the setting in btt, but now it seems that the behavior of which side the native fullscreen side the app will end up on completely depends on the original position of the app (It will automatically try to anchor to the right if the app is relatively right of the scree, anchor left if the app is left)
![screenshot](https://68.media.tumblr.com/3a528ac439c6934f50b27ec3bb5f9fd4/tumblr_oq263p8xo91s5a4bko1_1280.png)

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Regular Keyboard shortcut (but probably not the cause of the bug)

#### Device information:

Type of Mac: Macbook Pro Mid-2015 (maxed out 15inch specs)
macOS version: 10.12.4
BetterTouchTool version: 2.12

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
None, but if you need it, I will be fine to do it.

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Weird, this still seems to be working fine here.
Have you already tried to restart your system?

**Comment by adamw** [comment]
Should this work on High Sierra? I tried configuring a keyboard shortcut for this action, but when I use it on a full-screen app nothing happens (both the left & right variants).

**Comment by gilgameshskytrooper** [comment]
@adamw For me, the issue wasn't that the fullscreen split didn't work at all. Instead, it was I could not specify which direction (left or right) the application split into using my keyboard shortcut. Or to put it another way, even if I had a keyboard shortcut to split the current application into a left pane, and another shortcut to split the current application into a right pane, neither keyboard shortcut exhibited consistent behavior of directionality. Instead, it seems that where the application will appear largely depends on the location of your mouse. (Although I have never tested this theory extensively, so it is possible that the location of where it will end up is completely arbitrarily picked by macOS).

**Comment by adamw** [comment]
@gilgameshskytrooper Ah, I see. It doesn't work for me at all. I'll create another issue then.
