### ISSUE TITLE
Special Middle Click Mode for CAD doesn't work

### ISSUE THREAD

**Issue by Azeria07** [folivoraAI/BetterTouchTool#959]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
I have selected the option for the Special Middle Click and set up the three finger click and mapped it to the middle click action but this does not seem to work. Often, when I click with three fingers I feel the haptic click, then when releasing the other two fingers (attempting to not change pressure) I feel another haptic click and I get a left click. I need the middle click and drag for CAD work that I do while remote-ing into a Windows 7 machine.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Magic Trackpad 2 (Force Touch).

#### Device information: 
Type of Mac: Macbook Pro (Mid 2012)
macOS version: macOS Sierra 10.12.5
BetterTouchTool version: 2.12

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
I've tried getting this to work ever since the force touch trackpad came out and it has never worked for me. I did get this to work on the old Magic Trackpad but this was a pain since clicking required so much force.

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by combdn** [comment]
The same situation here. 
I need a middle-click drag, but the special middle-click mode doesn’t work :(

**Comment by fifafu** [comment]
Unfortunately that is a very old setting and only still works on old macOS versions.

With the latest alpha you could try to set it up like this:

1.) don't use the middle click action, instead use the "More Buttons & Modifiers & Custom Click" action and configure it like this (only mouse down).
![image](https://user-images.githubusercontent.com/8820811/39584896-d0e0351a-4ef3-11e8-8290-ee859b29a44e.png)

2.) Open the gesture preferences and define a named trigger that shall be executed when no fingers are touching the trackpad anymore
![image](https://user-images.githubusercontent.com/8820811/39584944-e9ed952a-4ef3-11e8-87ed-e71bf2386d07.png)

3.) Go to the "Other" tab and create a Named Trigger, then assign the middle mouse up.
![image](https://user-images.githubusercontent.com/8820811/39584971-f9b9307c-4ef3-11e8-959e-e9cbd8fd9fca.png)
