### ISSUE TITLE
Erratic mouse behavior / palm rejection issue

### ISSUE THREAD

**Issue by bobleitner** [folivoraAI/BetterTouchTool#966]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
It seems that since the latest update of btt I'm having erratic mouse behavior with the mouse jumping around and changing active windows while I'm typing, predominately in MS Outlook 2016 (ver 15.33 170409). If I use disable for this application, the problem seem to disappear, or at least I haven't noticed it in any other app yet. Is there a way I can roll back to previous version for now?

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Mackbook Pro trackpad

#### Device information:

Type of Mac: Macbook Pro 2016 15"
macOS version: 10.12.4
BetterTouchTool version: 2.12 (631)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Would be great if you could test alpha version 2.14 (get via "Check for Alpha Versions" in the menubar menu item). I have changed the palm/thumb recognition quite a bit, let's see if that helps

**Comment by bobleitner** [comment]
I downloaded, will let you know how it goes

Thanks,
Bob
