### ISSUE TITLE
Associate mouse additional buttons to horizontal scrolling

### ISSUE THREAD

**Issue by marco-brandizi** [folivoraAI/BetterTouchTool#970]
Is it possible to map buttons 4 and 3 from a 'Normal Mouse' to the action of horizontal scrolling left/right? Is there a two-finger drag gesture emulation?

Many thanks in advance.

**Comment by fifafu** [comment]
Hey,


sorry, this is currently not possible but I'll put it onto my TODO list!

Best,
Andreas

**Comment by ssaumitra** [comment]
+1. It would help me as well.

**Comment by marco-brandizi** [comment]
Hi all, 

I'd like to ask if there are news on this option and let you know about [something I've discovered](http://osxdaily.com/2012/01/26/scroll-horizontally-with-a-mouse-wheel-by-holding-shift/): one can scroll horizontally by rotating the mouse wheel while keeping the keyboard Shift button pressed. So, if I could remap extra-buttons to these combinations, that would do. However, at the moment it doesn't seem that this is possible. BTT allows for remapping a mouse button press to another button, but wheel switches don't appear among the mouse actions that I can assign there.

**Comment by Fanchao-Qi** [comment]
+1 BTW, has this feature been added?

**Comment by jbyler** [comment]
For anyone looking for a workaround: another tool called [Karabiner](https://pqrs.org/osx/karabiner/) does have the ability to map keys or mouse buttons to scroll events.  See [How to change mouse buttons ](https://pqrs.org/osx/karabiner/help.html#mouse-button) if you want to map mouse buttons, and look for "mouse_key" in the [karabiner.json Reference Manual](https://pqrs.org/osx/karabiner/json.html#to-event-definition) for details.
