### ISSUE TITLE
touch bar volume slider causing left and right channel to scale differently system wide

### ISSUE THREAD

**Issue by Sebastian-blu** [folivoraAI/BetterTouchTool#971]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
On the latest version of btt the volume slider has been causing left and right channels of core audio to scale at different rates. So much so that at full volume it sound like the right channel is just completely off. This occurs on internal speakers and through the headphones. It is remedied by opening audio midi setup matching the volumes of the left and right channel and then restarting btt. This only just started happening with latest update. 

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

2016 15inch maxed specs 

#### Device information:

Type of Mac: 2016 MBP touch bar
macOS version: 10.12.5
BetterTouchTool version: 2.11

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Have you already tried to restart your system? The code for this hasn't been changed since it was added to BTT, thus I think this might not be caused by BTT.

I can't observe any strange things here.
Does it show a moved left/right balance in System Preferences => Sound => Output?

**Comment by TheYorickable** [comment]
@fifafu I am also having difficulties with this issue.

[Video](https://www.youtube.com/watch?v=DKrCCxh4qRo)

Here is an example. I use the option key as modifier to show the sliders. Then when touching those it changes the sound balance.

This is after a fresh restart fyi.
If you need any additional information let me know.
