### ISSUE TITLE
3 Finger swipe left and right in Safari not working.

### ISSUE THREAD

**Issue by drewauff** [folivoraAI/BetterTouchTool#972]
3 Finger swipe left and right not being recognised in Safari.

Sometimes 3 Finger swipe left does work but 3 Finger swipe right does not work at all.

MacBook Trackpad

#### Device information:

Type of Mac:  Mackbook Pro 15" (non-touchbar)
macOS version: 10.12.4
BetterTouchTool version: 2.11 (630) 
Safari version: 10.0.1

**Comment by fifafu** [comment]
How have you configured them in BTT?

**Comment by drewauff** [comment]
certainly have..

I have tried so many different things. But nothing works. Literally the only gesture that does not work in Safari.

I use 3 Finger swipe left and right to switch tabs. Everything was perfect until I upgraded to Sierra.
