### ISSUE TITLE
Many mouse gestures not working

### ISSUE THREAD

**Issue by MLModel** [folivoraAI/BetterTouchTool#981]
I have turned off most of the optional Mouse actions in System Preferences and changed some to not conflict with what I want to use with BTT. I am finding that quite a few mouse gestures are not working, which I have confirmed with live view. (More accurately, they work very occasionally.)  These include:

- 2 Finger Click
- 2 Finger Tap
- 2 Finger Double-Tap
- 3 Finger Tap

I have been trying to assign these to simple actions such as Double Click or keystrokes.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Magic Mouse

#### Device information:

Type of Mac: MacBook Pro
macOS version: OSX 10.11.6
BetterTouchTool version: 2.11

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
That's weird, they seem to be working fine here. Could you check whether they work with other actions like e.g. mission control?

Keystrokes and clicks could possibly be conflicting with other keyboard/mouse related apps.
