### ISSUE TITLE
Ignore edges/create gesture zone

### ISSUE THREAD

**Issue by mergesort** [folivoraAI/BetterTouchTool#987]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Long time BTT user, and huge fan. Thanks so much for making this product!

The new MacBook Pro trackpad is so huge that I find myself accidentally 3 finger clicking, just by my palm resting on the edge of the trackpad when I'm in the middle of typing. This is problematic for me since I have it mapped to cmd + w, and it ends up closing windows for me all the time. I would love it if it could be possible to disable gestures around the edges, or more broadly define a zone where gestures are listened to.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
MacBook Trackpad

#### Device information:

Type of Mac: MacBook Pro
macOS version: 10.12
BetterTouchTool version: 2.12

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

N/A

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
I'll probably add something like this soon.

For now it would be great if you could check whether the new alpha 2.14 improves the accidental clicks/touches.

**Comment by mergesort** [comment]
Trying it out, will let you know how that goes.

Thanks!
